"""
zones.py — Travel zones and challenges.

All challenges use "type": "quiz" with multiple-choice options.
Guided by 先生 (Sensei), a wise, patient Japanese teacher.
"""

ZONE_ORDER = [
    "transportation",
    "directions",
    "hotel",
    "asking_help",
    "sightseeing",
    "emergencies",
]

ZONES = {
    # -- Zone 1: Transportation -----------------------------------------------
    "transportation": {
        "id": "transportation",
        "name": "Transportation",
        "description": "Trains, buses, taxis: でんしゃ, バス, タクシー, しんかんせん",
        "level_required": 1,
        "challenges": [
            {
                "id": "trans_densha",
                "title": "Train",
                "type": "quiz",
                "question": "でんしゃ (densha) means: (Romaji: densha)",
                "options": ["Bus", "Train", "Airplane", "Bicycle"],
                "answer": "b",
                "hints": [
                    "でん = electric, しゃ = vehicle.",
                    "Trains are the primary mode of transport in Japanese cities.",
                ],
                "xp": 25,
                "lesson": "でんしゃ (densha) = train (electric). Japan's train system is legendary for punctuality. でんしゃにのる (densha ni noru) = to ride a train.",
                "is_boss": False,
                "flavor": "Sensei hears the familiar chime of an approaching train.",
            },
            {
                "id": "trans_eki",
                "title": "Station",
                "type": "quiz",
                "question": "えき (eki) means: (Romaji: eki)",
                "options": ["Airport", "Station", "Bus stop", "Parking lot"],
                "answer": "b",
                "hints": [
                    "えき is one of the first signs you'll read in Japan.",
                    "とうきょうえき = Tokyo Station.",
                ],
                "xp": 25,
                "lesson": "えき (eki) = station. Combined with place names: とうきょうえき (Tokyo Station), しぶやえき (Shibuya Station). えきいん (ekiin) = station staff.",
                "is_boss": False,
                "flavor": "Sensei points to the station sign overhead.",
            },
            {
                "id": "trans_shinkansen",
                "title": "Bullet Train",
                "type": "quiz",
                "question": "しんかんせん (shinkansen) is: (Romaji: shinkansen)",
                "options": ["A subway line", "A bullet train / high-speed rail", "A local bus", "An express taxi"],
                "answer": "b",
                "hints": [
                    "しん = new, かんせん = trunk line.",
                    "Speeds up to 320 km/h, connecting major Japanese cities.",
                ],
                "xp": 25,
                "lesson": "しんかんせん (shinkansen) = bullet train. Connects Tokyo-Osaka in 2.5 hours. Types: のぞみ (Nozomi, fastest), ひかり (Hikari), こだま (Kodama, all stops).",
                "is_boss": False,
                "flavor": "Sensei watches a sleek bullet train glide into the platform.",
            },
            {
                "id": "trans_basu_takushi",
                "title": "Bus & Taxi",
                "type": "quiz",
                "question": "タクシーのりば (takushii noriba) means: (Romaji: takushii noriba)",
                "options": ["Taxi company", "Taxi fare", "Taxi stand", "Taxi driver"],
                "answer": "c",
                "hints": [
                    "タクシー = taxi, のりば (noriba) = boarding place.",
                    "のりば is used for any vehicle boarding point.",
                ],
                "xp": 25,
                "lesson": "タクシーのりば = taxi stand. バスのりば = bus stop. のりば = boarding place/platform. タクシー doors open automatically in Japan -- don't touch them!",
                "is_boss": False,
                "flavor": "Sensei hails a taxi -- the door opens by itself!",
            },
            {
                "id": "trans_kippu",
                "title": "Ticket",
                "type": "quiz",
                "question": "きっぷをかう (kippu o kau) means: (Romaji: kippu o kau)",
                "options": ["To lose a ticket", "To buy a ticket", "To check a ticket", "To cancel a ticket"],
                "answer": "b",
                "hints": [
                    "きっぷ (kippu) = ticket, かう (kau) = to buy.",
                    "Modern Japan mostly uses IC cards (Suica, Pasmo) instead.",
                ],
                "xp": 30,
                "lesson": "きっぷをかう = to buy a ticket. きっぷ = ticket, かう = buy. ICカード (IC kaado) = IC card (Suica/Pasmo) -- tap-and-go cards used on most Japanese transit.",
                "is_boss": False,
                "flavor": "Sensei taps an IC card -- ピッ!",
            },
            {
                "id": "transportation_boss",
                "title": "Transit Master",
                "type": "quiz",
                "question": "You need to get from Tokyo to Kyoto fast. Which do you take?",
                "options": ["ちかてつ (chikatetsu -- subway)", "しんかんせん (shinkansen -- bullet train)", "バス (basu -- bus)", "タクシー (takushii -- taxi)"],
                "answer": "b",
                "hints": [
                    "Tokyo to Kyoto is about 475 km -- too far for subway or taxi.",
                    "The しんかんせん covers this in about 2 hours 15 minutes.",
                ],
                "xp": 35,
                "lesson": "For long distances between major cities, the しんかんせん is the best choice. Tokyo to Kyoto: ~2h15m by Nozomi. ちかてつ = subway (city only), バス = bus (slower), タクシー = taxi (short trips).",
                "is_boss": True,
                "flavor": "Sensei tests your ability to choose the right transport.",
            },
        ],
    },

    # -- Zone 2: Directions ---------------------------------------------------
    "directions": {
        "id": "directions",
        "name": "Directions",
        "description": "Ask and understand directions: みぎ, ひだり, まっすぐ",
        "level_required": 2,
        "challenges": [
            {
                "id": "dir_migi_hidari",
                "title": "Right & Left",
                "type": "quiz",
                "question": "みぎ (migi) means right. What is ひだり (hidari)? (Romaji: migi / hidari)",
                "options": ["Straight", "Left", "Behind", "Above"],
                "answer": "b",
                "hints": [
                    "みぎ and ひだり are the most basic direction pair.",
                    "みぎにまがる = turn right, ひだりにまがる = turn left.",
                ],
                "xp": 25,
                "lesson": "みぎ (migi) = right. ひだり (hidari) = left. みぎにまがってください = please turn right. ひだりにまがってください = please turn left.",
                "is_boss": False,
                "flavor": "Sensei points right, then left -- みぎ, ひだり.",
            },
            {
                "id": "dir_massugu",
                "title": "Straight Ahead",
                "type": "quiz",
                "question": "まっすぐいってください (massugu itte kudasai) means: (Romaji: massugu itte kudasai)",
                "options": ["Please turn around", "Please go straight", "Please stop here", "Please go back"],
                "answer": "b",
                "hints": [
                    "まっすぐ (massugu) = straight, いって = go, ください = please.",
                    "One of the most common directions you'll receive.",
                ],
                "xp": 25,
                "lesson": "まっすぐいってください = please go straight. まっすぐ = straight ahead. This is often followed by distance or landmarks: まっすぐいって、つぎのかどをみぎ = go straight, turn right at the next corner.",
                "is_boss": False,
                "flavor": "Sensei gestures down a long straight road.",
            },
            {
                "id": "dir_doko",
                "title": "Where Is...?",
                "type": "quiz",
                "question": "えきはどこですか (eki wa doko desu ka) means: (Romaji: eki wa doko desu ka)",
                "options": ["Is there a station?", "Where is the station?", "Which station?", "How far is the station?"],
                "answer": "b",
                "hints": [
                    "どこ (doko) = where.",
                    "Pattern: [place]はどこですか = where is [place]?",
                ],
                "xp": 25,
                "lesson": "...はどこですか = where is...? どこ = where. トイレはどこですか = where is the bathroom? コンビニはどこですか = where is the convenience store?",
                "is_boss": False,
                "flavor": "Sensei asks for directions to practice the pattern.",
            },
            {
                "id": "dir_chikai_tooi",
                "title": "Near & Far",
                "type": "quiz",
                "question": "ちかい (chikai) means near. What is とおい (tooi)? (Romaji: chikai / tooi)",
                "options": ["Near", "Far", "Fast", "Slow"],
                "answer": "b",
                "hints": [
                    "ちかい and とおい are distance opposites.",
                    "えきはちかいですか = is the station nearby?",
                ],
                "xp": 25,
                "lesson": "ちかい (chikai) = near/close. とおい (tooi) = far. ここからちかいですか = is it near from here? あるいてじゅっぷん = 10 minutes on foot.",
                "is_boss": False,
                "flavor": "Sensei gauges the distance to the nearest landmark.",
            },
            {
                "id": "dir_kousaten",
                "title": "Intersection & Corner",
                "type": "quiz",
                "question": "つぎのこうさてんをみぎにまがってください means: (Romaji: tsugi no kousaten o migi ni magatte kudasai)",
                "options": ["Turn left at the light", "Turn right at the next intersection", "Go straight past the corner", "Stop at the intersection"],
                "answer": "b",
                "hints": [
                    "つぎ = next, こうさてん = intersection, みぎ = right, まがる = turn.",
                    "This is a complete, real-world direction sentence.",
                ],
                "xp": 30,
                "lesson": "つぎのこうさてんをみぎにまがってください = please turn right at the next intersection. こうさてん = intersection, かど = corner, しんごう = traffic light.",
                "is_boss": False,
                "flavor": "Sensei gives detailed real-world directions.",
            },
            {
                "id": "directions_boss",
                "title": "Navigation Challenge",
                "type": "quiz",
                "question": "Someone says: まっすぐいって、ふたつめのしんごうをひだりにまがってください。What do you do?",
                "options": [
                    "Go straight, turn left at the first traffic light",
                    "Go straight, turn right at the second traffic light",
                    "Go straight, turn left at the second traffic light",
                    "Turn around and go back"
                ],
                "answer": "c",
                "hints": [
                    "ふたつめ = second, しんごう = traffic light, ひだり = left.",
                    "まっすぐ = straight, まがる = turn.",
                ],
                "xp": 35,
                "lesson": "まっすぐいって、ふたつめのしんごうをひだりに = go straight, turn left at the second light. Counting landmarks: ひとつめ (1st), ふたつめ (2nd), みっつめ (3rd).",
                "is_boss": True,
                "flavor": "Sensei tests your ability to follow multi-step directions.",
            },
        ],
    },

    # -- Zone 3: Hotel --------------------------------------------------------
    "hotel": {
        "id": "hotel",
        "name": "Hotel & Accommodation",
        "description": "Check in and out: よやく, チェックイン, へや, りょかん",
        "level_required": 3,
        "challenges": [
            {
                "id": "hotel_yoyaku",
                "title": "Reservation",
                "type": "quiz",
                "question": "よやくがあります (yoyaku ga arimasu) means: (Romaji: yoyaku ga arimasu)",
                "options": ["I need a reservation", "I have a reservation", "I want to cancel", "Is there a room?"],
                "answer": "b",
                "hints": [
                    "よやく (yoyaku) = reservation, あります = there is / I have.",
                    "Say this at the front desk when checking in.",
                ],
                "xp": 25,
                "lesson": "よやくがあります = I have a reservation. よやく = reservation. よやくをおねがいします = I'd like to make a reservation. よやくをキャンセルしたい = I want to cancel.",
                "is_boss": False,
                "flavor": "Sensei approaches the front desk with confidence.",
            },
            {
                "id": "hotel_checkin",
                "title": "Check In",
                "type": "quiz",
                "question": "チェックインをおねがいします (chekku in o onegaishimasu) means: (Romaji: chekku in o onegaishimasu)",
                "options": ["I'd like to check out", "I'd like to check in, please", "Where is my room?", "I need a wake-up call"],
                "answer": "b",
                "hints": [
                    "チェックイン = check-in (loanword).",
                    "おねがいします = please (polite request).",
                ],
                "xp": 25,
                "lesson": "チェックインをおねがいします = check-in, please. チェックアウト = check-out. チェックアウトはなんじですか = what time is check-out?",
                "is_boss": False,
                "flavor": "Sensei checks into a traditional ryokan.",
            },
            {
                "id": "hotel_heya",
                "title": "Room",
                "type": "quiz",
                "question": "へやにタオルがありません (heya ni taoru ga arimasen) means: (Romaji: heya ni taoru ga arimasen)",
                "options": ["The room has extra towels", "There are no towels in the room", "I don't need towels", "The towels are dirty"],
                "answer": "b",
                "hints": [
                    "へや (heya) = room, タオル (taoru) = towel, ありません = there isn't.",
                    "A useful complaint pattern for hotels.",
                ],
                "xp": 25,
                "lesson": "へやにタオルがありません = there are no towels in the room. Pattern: へやに[item]がありません = there's no [item] in the room. Useful for any missing amenity.",
                "is_boss": False,
                "flavor": "Sensei teaches you how to politely flag missing items.",
            },
            {
                "id": "hotel_ryokan",
                "title": "Traditional Inn",
                "type": "quiz",
                "question": "りょかん (ryokan) is: (Romaji: ryokan)",
                "options": ["A modern hotel", "A traditional Japanese inn", "A youth hostel", "A capsule hotel"],
                "answer": "b",
                "hints": [
                    "りょかん features たたみ (tatami) floors and ふとん (futon) beds.",
                    "Many include おんせん (onsen, hot spring baths).",
                ],
                "xp": 25,
                "lesson": "りょかん (ryokan) = traditional Japanese inn. Features: たたみ rooms, ふとん beds, おんせん (hot springs), ゆかた (light kimono). A uniquely Japanese experience.",
                "is_boss": False,
                "flavor": "Sensei slides open a shoji screen to reveal a beautiful tatami room.",
            },
            {
                "id": "hotel_wifi",
                "title": "Practical Requests",
                "type": "quiz",
                "question": "Wi-Fiのパスワードをおしえてください means: (Romaji: waifai no pasuwaado o oshiete kudasai)",
                "options": ["Is there Wi-Fi?", "Please tell me the Wi-Fi password", "The Wi-Fi is broken", "How much is Wi-Fi?"],
                "answer": "b",
                "hints": [
                    "パスワード = password, おしえて = tell/teach me.",
                    "ください makes it a polite request.",
                ],
                "xp": 30,
                "lesson": "Wi-Fiのパスワードをおしえてください = please tell me the Wi-Fi password. Other useful requests: もうふをもう一まいください (one more blanket please), ちょうしょくはなんじですか (what time is breakfast?).",
                "is_boss": False,
                "flavor": "Sensei asks the essential modern travel question.",
            },
            {
                "id": "hotel_boss",
                "title": "Hotel Challenge",
                "type": "quiz",
                "question": "The front desk says おへやのかぎです (oheya no kagi desu). What are they giving you?",
                "options": ["A map of the hotel", "Your room key", "A breakfast ticket", "The Wi-Fi password"],
                "answer": "b",
                "hints": [
                    "おへや = room (polite), かぎ (kagi) = key.",
                    "です = this is.",
                ],
                "xp": 35,
                "lesson": "おへやのかぎです = this is your room key. かぎ = key. Other hotel vocabulary: フロント (furonto) = front desk, エレベーター (erebeetaa) = elevator, ちゅうしゃじょう (chuushajou) = parking lot.",
                "is_boss": True,
                "flavor": "Sensei tests your hotel check-in comprehension.",
            },
        ],
    },

    # -- Zone 4: Asking for Help ----------------------------------------------
    "asking_help": {
        "id": "asking_help",
        "name": "Asking for Help",
        "description": "Get assistance: すみません, たすけて, わかりません",
        "level_required": 4,
        "challenges": [
            {
                "id": "help_sumimasen",
                "title": "Excuse Me",
                "type": "quiz",
                "question": "すみません、ちょっといいですか (sumimasen, chotto ii desu ka) means: (Romaji: sumimasen, chotto ii desu ka)",
                "options": ["Sorry, I'm busy", "Excuse me, do you have a moment?", "Sorry, that's not good", "Excuse me, is this okay?"],
                "answer": "b",
                "hints": [
                    "ちょっと (chotto) = a little, いい = good/okay.",
                    "A very polite way to get someone's attention.",
                ],
                "xp": 25,
                "lesson": "すみません、ちょっといいですか = excuse me, do you have a moment? This is the politest way to approach a stranger for help. Always start with すみません.",
                "is_boss": False,
                "flavor": "Sensei demonstrates the perfect approach to a stranger.",
            },
            {
                "id": "help_eigo",
                "title": "Do You Speak English?",
                "type": "quiz",
                "question": "えいごはだいじょうぶですか (eigo wa daijoubu desu ka) means: (Romaji: eigo wa daijoubu desu ka)",
                "options": ["Is English difficult?", "Is English okay? / Do you speak English?", "I don't speak English", "Can you translate to English?"],
                "answer": "b",
                "hints": [
                    "えいご (eigo) = English, だいじょうぶ = okay/alright.",
                    "A gentle way to ask without putting pressure on them.",
                ],
                "xp": 25,
                "lesson": "えいごはだいじょうぶですか = is English okay? A soft way to ask if someone speaks English. Also: えいごをはなせますか (eigo o hanasemasu ka) = can you speak English?",
                "is_boss": False,
                "flavor": "Sensei teaches the gentle approach to language barriers.",
            },
            {
                "id": "help_wakarimasen",
                "title": "I Don't Understand",
                "type": "quiz",
                "question": "にほんごがわかりません (nihongo ga wakarimasen) means: (Romaji: nihongo ga wakarimasen)",
                "options": ["I understand Japanese", "I'm studying Japanese", "I don't understand Japanese", "I speak Japanese"],
                "answer": "c",
                "hints": [
                    "わかりません = don't understand (polite negative).",
                    "An honest and useful phrase for any traveler.",
                ],
                "xp": 25,
                "lesson": "にほんごがわかりません = I don't understand Japanese. Follow with: えいごでおねがいします (eigo de onegaishimasu) = in English, please. Or: かいてください (kaite kudasai) = please write it down.",
                "is_boss": False,
                "flavor": "Sensei reassures you that admitting confusion is brave.",
            },
            {
                "id": "help_tasukete",
                "title": "Help!",
                "type": "quiz",
                "question": "たすけてください (tasukete kudasai) means: (Romaji: tasukete kudasai)",
                "options": ["Leave me alone", "Please help me", "Thank you for helping", "I can help you"],
                "answer": "b",
                "hints": [
                    "たすけて (tasukete) = help (imperative form of たすける).",
                    "ください makes it polite, but in emergencies, just shout たすけて!",
                ],
                "xp": 25,
                "lesson": "たすけてください = please help me. In an emergency, just shout たすけて! (tasukete = help!). For less urgent help: てつだってください (tetsudatte kudasai) = please assist me.",
                "is_boss": False,
                "flavor": "Sensei teaches the word you hope to never need.",
            },
            {
                "id": "help_kore_nani",
                "title": "What Is This?",
                "type": "quiz",
                "question": "これはなんですか (kore wa nan desu ka) means: (Romaji: kore wa nan desu ka)",
                "options": ["How much is this?", "What is this?", "Where is this?", "Whose is this?"],
                "answer": "b",
                "hints": [
                    "これ (kore) = this, なん (nan) = what.",
                    "Point at anything and ask -- people love to explain.",
                ],
                "xp": 30,
                "lesson": "これはなんですか = what is this? Incredibly useful when you encounter unfamiliar food, signs, or objects. Point and ask -- Japanese people are happy to explain.",
                "is_boss": False,
                "flavor": "Sensei points at mysterious items and asks confidently.",
            },
            {
                "id": "asking_help_boss",
                "title": "Help Challenge",
                "type": "quiz",
                "question": "You're lost and need the train station. What's the best thing to say?",
                "options": [
                    "えきにいきたいです (eki ni ikitai desu)",
                    "すみません、えきはどこですか (sumimasen, eki wa doko desu ka)",
                    "えき! えき! (eki! eki!)",
                    "でんしゃがすきです (densha ga suki desu)"
                ],
                "answer": "b",
                "hints": [
                    "Start with すみません to be polite.",
                    "どこですか is the 'where is' pattern you learned.",
                ],
                "xp": 35,
                "lesson": "すみません、えきはどこですか = excuse me, where is the station? Always start with すみません, use the どこですか pattern, and bow slightly. Politeness gets you help faster.",
                "is_boss": True,
                "flavor": "Sensei tests your ability to ask for help in a real scenario.",
            },
        ],
    },

    # -- Zone 5: Sightseeing -------------------------------------------------
    "sightseeing": {
        "id": "sightseeing",
        "name": "Sightseeing",
        "description": "Explore Japan: おてら, じんじゃ, おしろ, しゃしん",
        "level_required": 5,
        "challenges": [
            {
                "id": "sight_otera",
                "title": "Temple",
                "type": "quiz",
                "question": "おてら (otera) is: (Romaji: otera)",
                "options": ["A Shinto shrine", "A Buddhist temple", "A castle", "A garden"],
                "answer": "b",
                "hints": [
                    "おてら = Buddhist temple. The お is a polite prefix.",
                    "Temples are associated with Buddhism, shrines with Shinto.",
                ],
                "xp": 25,
                "lesson": "おてら (otera) = Buddhist temple. Key difference: おてら = Buddhist (has a ほとけ/Buddha), じんじゃ = Shinto (has a とりい/gate). At temples, you put hands together and bow.",
                "is_boss": False,
                "flavor": "Sensei leads you through ancient temple grounds.",
            },
            {
                "id": "sight_jinja",
                "title": "Shrine",
                "type": "quiz",
                "question": "じんじゃ (jinja) is identified by its: (Romaji: jinja)",
                "options": ["Buddha statue", "とりい (torii) gate", "Castle tower", "Zen garden"],
                "answer": "b",
                "hints": [
                    "The とりい gate marks the entrance to sacred Shinto space.",
                    "じんじゃ = Shinto shrine, distinct from Buddhist temples.",
                ],
                "xp": 25,
                "lesson": "じんじゃ (jinja) = Shinto shrine. Identified by とりい (torii) gates. Worship: bow twice, clap twice, bow once (にはいにはくしゅいちれい). おまもり (omamori) = protective charm.",
                "is_boss": False,
                "flavor": "Sensei passes through a vermilion torii gate.",
            },
            {
                "id": "sight_oshiro",
                "title": "Castle",
                "type": "quiz",
                "question": "おしろ (oshiro) means: (Romaji: oshiro)",
                "options": ["Palace", "Castle", "Tower", "Museum"],
                "answer": "b",
                "hints": [
                    "しろ (shiro) = castle, お is the polite prefix.",
                    "Famous ones: ひめじじょう, おおさかじょう, くまもとじょう.",
                ],
                "xp": 25,
                "lesson": "おしろ (oshiro) = castle. Famous: ひめじじょう (Himeji Castle, UNESCO), おおさかじょう (Osaka Castle), まつもとじょう (Matsumoto Castle). じょう/しろ both mean castle.",
                "is_boss": False,
                "flavor": "Sensei gazes up at a magnificent castle tower.",
            },
            {
                "id": "sight_shashin",
                "title": "Taking Photos",
                "type": "quiz",
                "question": "しゃしんをとってもいいですか (shashin o totte mo ii desu ka) means: (Romaji: shashin o totte mo ii desu ka)",
                "options": ["Can you take my photo?", "Is it okay to take photos?", "Where can I print photos?", "No photography allowed"],
                "answer": "b",
                "hints": [
                    "しゃしん = photo, とる = take, ~てもいいですか = is it okay to?",
                    "Always ask before photographing in temples and private areas.",
                ],
                "xp": 25,
                "lesson": "しゃしんをとってもいいですか = is it okay to take photos? ~てもいいですか = may I...? さつえいきんし (satsuei kinshi) = photography prohibited.",
                "is_boss": False,
                "flavor": "Sensei reminds you to always ask permission first.",
            },
            {
                "id": "sight_omiyage",
                "title": "Souvenirs",
                "type": "quiz",
                "question": "おみやげ (omiyage) means: (Romaji: omiyage)",
                "options": ["Admission fee", "Souvenir / gift from travels", "Tour guide", "Map"],
                "answer": "b",
                "hints": [
                    "おみやげ culture is huge in Japan -- you bring gifts back for everyone.",
                    "Every tourist spot sells local おみやげ.",
                ],
                "xp": 30,
                "lesson": "おみやげ (omiyage) = souvenir/travel gift. In Japan, bringing おみやげ back for coworkers, friends, and family is expected. Every region has its famous local omiyage.",
                "is_boss": False,
                "flavor": "Sensei browses a shop full of regional specialties.",
            },
            {
                "id": "sightseeing_boss",
                "title": "Sightseeing Challenge",
                "type": "quiz",
                "question": "You see a とりい gate, then a building with a bell and incense. Is this a じんじゃ or an おてら?",
                "options": ["じんじゃ (Shinto shrine)", "おてら (Buddhist temple)", "Both combined", "Neither -- it's an おしろ"],
                "answer": "b",
                "hints": [
                    "とりい gates can appear at temples too, but bells and incense are Buddhist.",
                    "Temples have bells (かね) and incense (おこう), shrines have clapping rituals.",
                ],
                "xp": 35,
                "lesson": "Bells and incense = Buddhist temple (おてら). Though とりい occasionally appear at temples, the incense burner (おこう) and bell (かね) are distinctly Buddhist. Shrines use かしわで (clapping).",
                "is_boss": True,
                "flavor": "Sensei tests your ability to tell temples from shrines.",
            },
        ],
    },

    # -- Zone 6: Emergencies --------------------------------------------------
    "emergencies": {
        "id": "emergencies",
        "name": "Emergencies",
        "description": "Survive crises: たすけて, けいさつ, びょういん, 110/119",
        "level_required": 6,
        "challenges": [
            {
                "id": "emerg_tasukete",
                "title": "Help!",
                "type": "quiz",
                "question": "In a true emergency, you shout: (Romaji: tasukete!)",
                "options": ["すみません! (sumimasen)", "たすけて! (tasukete)", "おねがいします! (onegaishimasu)", "ちょっとまって! (chotto matte)"],
                "answer": "b",
                "hints": [
                    "たすけて is the urgent cry for help.",
                    "No need for ください in a real emergency.",
                ],
                "xp": 25,
                "lesson": "たすけて! (tasukete!) = Help! In emergencies, shout this loudly. Drop all politeness. あぶない! (abunai!) = Danger! / Watch out! にげて! (nigete!) = Run! / Flee!",
                "is_boss": False,
                "flavor": "Sensei teaches the word with appropriate gravity.",
            },
            {
                "id": "emerg_keisatsu",
                "title": "Police",
                "type": "quiz",
                "question": "けいさつをよんでください (keisatsu o yonde kudasai) means: (Romaji: keisatsu o yonde kudasai)",
                "options": ["Where is the police station?", "Please call the police", "I am the police", "The police are here"],
                "answer": "b",
                "hints": [
                    "けいさつ (keisatsu) = police, よんで = call, ください = please.",
                    "Japan's police number is 110.",
                ],
                "xp": 25,
                "lesson": "けいさつをよんでください = please call the police. Emergency: 110 (police), 119 (fire/ambulance). こうばん (kouban) = police box -- small police stations on street corners.",
                "is_boss": False,
                "flavor": "Sensei points out a こうばん on the nearest corner.",
            },
            {
                "id": "emerg_kyukyusha",
                "title": "Ambulance",
                "type": "quiz",
                "question": "きゅうきゅうしゃをおねがいします (kyuukyuusha o onegaishimasu) means: (Romaji: kyuukyuusha o onegaishimasu)",
                "options": ["I need a taxi", "I need an ambulance, please", "Where is the hospital?", "I need medicine"],
                "answer": "b",
                "hints": [
                    "きゅうきゅうしゃ (kyuukyuusha) = ambulance.",
                    "Call 119 for both fire and ambulance services.",
                ],
                "xp": 25,
                "lesson": "きゅうきゅうしゃをおねがいします = ambulance please. Call 119. They'll ask: かじですか、きゅうきゅうですか (fire or medical emergency?). Reply: きゅうきゅうです (medical).",
                "is_boss": False,
                "flavor": "Sensei drills the life-saving vocabulary.",
            },
            {
                "id": "emerg_nakushita",
                "title": "I Lost Something",
                "type": "quiz",
                "question": "パスポートをなくしました (pasupooto o nakushimashita) means: (Romaji: pasupooto o nakushimashita)",
                "options": ["I found a passport", "I lost my passport", "I need a passport", "Is this your passport?"],
                "answer": "b",
                "hints": [
                    "パスポート = passport, なくしました = lost (past tense).",
                    "Go to the nearest こうばん or embassy if this happens.",
                ],
                "xp": 25,
                "lesson": "パスポートをなくしました = I lost my passport. なくしました = lost (something). さいふをなくしました = I lost my wallet. けいたいをなくしました = I lost my phone.",
                "is_boss": False,
                "flavor": "Sensei prepares you for the traveler's worst nightmare.",
            },
            {
                "id": "emerg_jishin",
                "title": "Earthquake",
                "type": "quiz",
                "question": "じしん (jishin) means: (Romaji: jishin)",
                "options": ["Typhoon", "Earthquake", "Flood", "Fire"],
                "answer": "b",
                "hints": [
                    "じ = earth/ground, しん = shake/quake.",
                    "Japan experiences thousands of earthquakes every year.",
                ],
                "xp": 30,
                "lesson": "じしん (jishin) = earthquake. Japan is earthquake-prone. たいふう (taifuu) = typhoon, つなみ (tsunami) = tsunami, かじ (kaji) = fire. ひなんじょ (hinanjo) = evacuation shelter.",
                "is_boss": False,
                "flavor": "Sensei explains Japan's relationship with natural disasters.",
            },
            {
                "id": "emergencies_boss",
                "title": "Emergency Response",
                "type": "quiz",
                "question": "Your friend collapses. What number do you call in Japan?",
                "options": ["110 (police)", "119 (fire/ambulance)", "911 (universal)", "118 (coast guard)"],
                "answer": "b",
                "hints": [
                    "Medical emergencies use the same number as fire.",
                    "110 is for police, 119 is for fire and ambulance.",
                ],
                "xp": 35,
                "lesson": "119 for fire and ambulance. 110 for police. When they answer, say: きゅうきゅうです (medical emergency), give your location, describe the situation. Japan's emergency services are excellent.",
                "is_boss": True,
                "flavor": "Sensei tests your emergency preparedness with the most critical question.",
            },
        ],
    },
}
