"""
zones.py — Hobbies & Free Time zones and challenges.

5 zones x 8 challenges = 40 total.
Mix of quiz and text types. Guided by 龙龙 (Long Long).
"""

ZONE_ORDER = [
    "sports_exercise",
    "music_art",
    "reading_media",
    "outdoor_activities",
    "talking_about_hobbies",
]

ZONES = {
    "sports_exercise": {
        "id": "sports_exercise",
        "name": "The Arena of Athletes",
        "description": "Learn sports and exercise vocabulary in Chinese",
        "level_required": 1,
        "challenges": [
            {
                "id": "sport_basketball",
                "title": "The Court of Champions",
                "type": "quiz",
                "question": "打篮球 (dǎ lánqiú) means...?",
                "options": ["Play football", "Play basketball", "Play tennis", "Play volleyball"],
                "answer": "b",
                "hints": [
                    "篮 means 'basket' and 球 means 'ball.'",
                    "打 here means 'to play' (used for ball sports played with hands).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "打篮球 (dǎ lánqiú) = play basketball. 打 = hit/play (for hand sports), 篮 = basket, 球 = ball. 打 is used for basketball, volleyball, badminton — any sport where you strike with your hands. 我喜欢打篮球 = 'I like playing basketball.'",
                "is_boss": False,
                "flavor": "龙龙 bounces an enchanted ball off the castle wall with its tail.",
            },
            {
                "id": "sport_football",
                "title": "The Kicking Field",
                "type": "quiz",
                "question": "踢足球 (tī zúqiú) means...?",
                "options": ["Play basketball", "Play baseball", "Play soccer/football", "Play badminton"],
                "answer": "c",
                "hints": [
                    "踢 means 'to kick' — note the foot radical 足 on the left.",
                    "足球 literally means 'foot ball.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "踢足球 (tī zúqiú) = play soccer/football. 踢 = kick, 足 = foot, 球 = ball. Unlike 打 (play with hands), 踢 is used specifically for kicking sports. 他每天踢足球 = 'He plays soccer every day.'",
                "is_boss": False,
                "flavor": "龙龙 tries to kick a leather ball but accidentally singes it with a sneeze of flame.",
            },
            {
                "id": "sport_running",
                "title": "The Swift Stride",
                "type": "quiz",
                "question": "跑步 (pǎobù) means...?",
                "options": ["Swimming", "Running/jogging", "Walking", "Cycling"],
                "answer": "b",
                "hints": [
                    "跑 means 'to run' and 步 means 'step.'",
                    "Together they describe the activity of running for exercise.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "跑步 (pǎobù) = running/jogging. 跑 = run, 步 = step. 我每天早上跑步 = 'I go running every morning.' Related: 散步 (sànbù) = take a walk (散 = scatter/leisurely + 步 = step).",
                "is_boss": False,
                "flavor": "龙龙 sprints across the courtyard, wings folded tight. 'Even dragons need cardio!'",
            },
            {
                "id": "sport_swimming",
                "title": "The Castle Moat",
                "type": "quiz",
                "question": "游泳 (yóuyǒng) means...?",
                "options": ["Diving", "Fishing", "Swimming", "Sailing"],
                "answer": "c",
                "hints": [
                    "Both characters contain the water radical 氵.",
                    "游 means 'to swim/travel' and 泳 means 'to swim.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "游泳 (yóuyǒng) = swimming. Both 游 and 泳 contain the water radical 氵, a clear clue! 游泳池 (yóuyǒngchí) = swimming pool. 我夏天喜欢游泳 = 'I like swimming in summer.'",
                "is_boss": False,
                "flavor": "龙龙 dives into the castle moat and surfaces with a grin. 'Water dragons swim best!'",
            },
            {
                "id": "sport_cycling",
                "title": "The Iron Steed",
                "type": "quiz",
                "question": "骑自行车 (qí zìxíngchē) means...?",
                "options": ["Drive a car", "Ride a bicycle", "Take the bus", "Ride a horse"],
                "answer": "b",
                "hints": [
                    "骑 means 'to ride,' and 自行车 literally means 'self-moving vehicle.'",
                    "自 = self, 行 = move, 车 = vehicle.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "骑自行车 (qí zìxíngchē) = ride a bicycle. 骑 = ride, 自行车 = bicycle (self-moving vehicle). 骑 is also used for horses: 骑马 (qímǎ). 我骑自行车去学校 = 'I ride my bicycle to school.'",
                "is_boss": False,
                "flavor": "龙龙 eyes a bicycle suspiciously. 'Why ride that when you can fly?'",
            },
            {
                "id": "sport_verb_pattern",
                "title": "打 vs. 踢 — The Action Pattern",
                "type": "text",
                "question": "In Chinese, 打 (dǎ) is used for hand/racket sports and 踢 (tī) for kicking sports. Which pairing is correct?",
                "options": [
                    "打足球, 踢篮球",
                    "打篮球, 踢足球",
                    "踢篮球, 踢足球",
                    "打篮球, 打足球",
                ],
                "answer": "b",
                "hints": [
                    "Basketball uses hands (打), football uses feet (踢).",
                    "打 = hit/strike (hands), 踢 = kick (feet).",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "打 (dǎ) is for hand/racket sports: 打篮球, 打排球, 打网球, 打羽毛球. 踢 (tī) is for kicking sports: 踢足球. This distinction is important — mixing them up sounds very odd to native speakers!",
                "is_boss": False,
                "flavor": "龙龙 holds up two claws — one for 打, one for 踢. 'Hands or feet? Choose wisely!'",
            },
            {
                "id": "sport_frequency",
                "title": "How Often Do You Play?",
                "type": "quiz",
                "question": "我每天都跑步 (Wǒ měitiān dōu pǎobù) means...?",
                "options": [
                    "I sometimes go running",
                    "I run every day",
                    "I used to run",
                    "I want to go running",
                ],
                "answer": "b",
                "hints": [
                    "每天 = every day, 都 = all/always.",
                    "跑步 = running. The sentence expresses a daily habit.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "每天都 (měitiān dōu) = every day (always). 每 = every, 天 = day, 都 = all. Use this pattern for habits: 我每天都游泳 = 'I swim every day.' Also: 每周 (měizhōu) = every week, 每年 (měinián) = every year.",
                "is_boss": False,
                "flavor": "龙龙 marks a tally on the wall. 'Consistency builds mastery — in sports AND in Chinese!'",
            },
            {
                "id": "sport_boss",
                "title": "Arena Champion",
                "type": "quiz",
                "question": "Match them all: 打篮球, 踢足球, 跑步, 游泳, 骑自行车. Which list is correct?",
                "options": [
                    "Play basketball, play soccer, run, swim, ride a bike",
                    "Play soccer, play basketball, swim, run, ride a horse",
                    "Play basketball, play soccer, swim, run, drive a car",
                    "Play tennis, play soccer, run, swim, ride a bike",
                ],
                "answer": "a",
                "hints": [
                    "打篮球 = basketball (hands), 踢足球 = soccer (feet).",
                    "骑自行车 = ride a bicycle, not a horse.",
                ],
                "xp": 50,
                "difficulty": "hard",
                "lesson": "Full review: 打篮球 (play basketball), 踢足球 (play soccer), 跑步 (run), 游泳 (swim), 骑自行车 (ride a bicycle). You now know five sports in Chinese and the correct verbs to use with each!",
                "is_boss": True,
                "flavor": "龙龙 raises a champion's banner. 'Five sports mastered — you are a true athlete of language!'",
            },
        ],
    },
    "music_art": {
        "id": "music_art",
        "name": "The Bard's Tower",
        "description": "Learn music and art vocabulary in Chinese",
        "level_required": 3,
        "challenges": [
            {
                "id": "art_listen_music",
                "title": "The Melody Within",
                "type": "quiz",
                "question": "听音乐 (tīng yīnyuè) means...?",
                "options": ["Play music", "Listen to music", "Write music", "Study music"],
                "answer": "b",
                "hints": [
                    "听 means 'to listen' — it has the ear radical 耳.",
                    "音乐 = music (sound + joy).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "听音乐 (tīng yīnyuè) = listen to music. 听 = listen, 音 = sound, 乐 = joy/music. 音乐 literally means 'joyful sounds.' 我喜欢听音乐 = 'I like listening to music.' 音乐家 (yīnyuèjiā) = musician.",
                "is_boss": False,
                "flavor": "龙龙 hums a haunting tune that echoes through the tower's stone halls.",
            },
            {
                "id": "art_piano",
                "title": "Keys of the Kingdom",
                "type": "quiz",
                "question": "弹钢琴 (tán gāngqín) means...?",
                "options": ["Play the drums", "Play the piano", "Play the guitar", "Play the flute"],
                "answer": "b",
                "hints": [
                    "弹 means 'to pluck/play' (for string and key instruments).",
                    "钢琴: 钢 = steel, 琴 = stringed instrument.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "弹钢琴 (tán gāngqín) = play the piano. 弹 = pluck/play (keys or strings), 钢 = steel, 琴 = instrument. 弹 is used for piano, guitar, and other string instruments. 她会弹钢琴 = 'She can play the piano.'",
                "is_boss": False,
                "flavor": "龙龙 presses a piano key with one massive claw. A single note rings out beautifully.",
            },
            {
                "id": "art_singing",
                "title": "The Dragon's Song",
                "type": "quiz",
                "question": "唱歌 (chànggē) means...?",
                "options": ["Dance", "Sing (a song)", "Shout", "Whisper"],
                "answer": "b",
                "hints": [
                    "唱 means 'to sing' and 歌 means 'song.'",
                    "Notice the mouth radical 口 in 唱 — singing comes from the mouth!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "唱歌 (chànggē) = sing (a song). 唱 = sing, 歌 = song. 歌手 (gēshǒu) = singer (song + hand/expert). 我喜欢唱歌 = 'I like singing.' KTV (karaoke) is hugely popular in China!",
                "is_boss": False,
                "flavor": "龙龙 opens its jaws and sings a note so loud it rattles the chandeliers.",
            },
            {
                "id": "art_drawing",
                "title": "Brush and Canvas",
                "type": "quiz",
                "question": "画画 (huàhuà) means...?",
                "options": ["Write calligraphy", "Draw/paint", "Take photos", "Make crafts"],
                "answer": "b",
                "hints": [
                    "画 means both 'to draw/paint' and 'a drawing/painting.'",
                    "When doubled (画画), it becomes the casual verb 'to draw.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "画画 (huàhuà) = draw/paint. The first 画 is the verb, the second is the object. Related: 画家 (huàjiā) = painter/artist, 国画 (guóhuà) = traditional Chinese painting. 我在画画 = 'I'm drawing.'",
                "is_boss": False,
                "flavor": "龙龙 dips its tail in ink and paints a perfect circle on the tower wall.",
            },
            {
                "id": "art_dancing",
                "title": "The Grand Ball",
                "type": "quiz",
                "question": "跳舞 (tiàowǔ) means...?",
                "options": ["Jump rope", "Dance", "Exercise", "Perform acrobatics"],
                "answer": "b",
                "hints": [
                    "跳 means 'to jump' and 舞 means 'dance.'",
                    "Dancing involves jumping and movement — 跳舞!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "跳舞 (tiàowǔ) = dance. 跳 = jump, 舞 = dance. 舞蹈 (wǔdǎo) is the more formal word for dance as an art form. 她跳舞跳得很好 = 'She dances very well.' Chinese traditional dance (中国舞) is a celebrated art.",
                "is_boss": False,
                "flavor": "龙龙 attempts an elegant waltz, knocking over a suit of armor in the process.",
            },
            {
                "id": "art_verb_pattern",
                "title": "The 琴 Family — Instruments Pattern",
                "type": "text",
                "question": "琴 (qín) appears in 钢琴 (piano), 小提琴 (violin), 吉他 (guitar uses 弹 too). What does 琴 tell you about a word?",
                "options": [
                    "It's a type of food",
                    "It's a stringed or keyboard instrument",
                    "It's a type of sport",
                    "It's a loud sound",
                ],
                "answer": "b",
                "hints": [
                    "琴 originally referred to a Chinese zither — a stringed instrument.",
                    "钢琴 = steel + instrument, 小提琴 = small + carry + instrument.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "琴 (qín) = stringed/keyboard instrument. It appears in: 钢琴 (piano), 小提琴 (violin), 大提琴 (cello), 古琴 (ancient zither). The verb 弹 (tán) is used with all of them. Recognizing 琴 instantly tells you 'this is an instrument.'",
                "is_boss": False,
                "flavor": "龙龙 traces the character 琴 in fire. 'One character, a whole orchestra!'",
            },
            {
                "id": "art_ability",
                "title": "Can You Play?",
                "type": "quiz",
                "question": "你会弹钢琴吗? (Nǐ huì tán gāngqín ma?) means...?",
                "options": [
                    "Do you like the piano?",
                    "Can you play the piano?",
                    "Do you have a piano?",
                    "Do you want to learn piano?",
                ],
                "answer": "b",
                "hints": [
                    "会 (huì) means 'can / know how to' — it expresses learned ability.",
                    "吗 at the end makes it a yes/no question.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "会 (huì) = can / know how to (learned skill). 你会弹钢琴吗? = Can you play the piano? Answer: 我会 (I can) or 我不会 (I can't). Use 会 for skills: 你会唱歌吗? 你会画画吗? 你会跳舞吗?",
                "is_boss": False,
                "flavor": "龙龙 asks with genuine curiosity. 'I can breathe fire — what can YOU do?'",
            },
            {
                "id": "art_boss",
                "title": "Master of the Arts",
                "type": "quiz",
                "question": "Match them all: 听音乐, 弹钢琴, 唱歌, 画画, 跳舞. Which list is correct?",
                "options": [
                    "Listen to music, play piano, sing, draw, dance",
                    "Play music, play guitar, sing, paint, jump",
                    "Listen to music, play piano, shout, draw, exercise",
                    "Write music, play piano, sing, draw, dance",
                ],
                "answer": "a",
                "hints": [
                    "听 = listen, 弹 = play (keys/strings), 唱 = sing.",
                    "画画 = draw, 跳舞 = dance.",
                ],
                "xp": 50,
                "difficulty": "hard",
                "lesson": "Full review: 听音乐 (listen to music), 弹钢琴 (play piano), 唱歌 (sing), 画画 (draw/paint), 跳舞 (dance). Five creative hobbies, each with its own verb. You are now a master of the arts!",
                "is_boss": True,
                "flavor": "龙龙 applauds with its wings. 'Music, art, song, paint, and dance — the five treasures of the Bard's Tower!'",
            },
        ],
    },
    "reading_media": {
        "id": "reading_media",
        "name": "The Scribe's Library",
        "description": "Learn reading and media vocabulary in Chinese",
        "level_required": 5,
        "challenges": [
            {
                "id": "media_reading",
                "title": "The Ancient Tomes",
                "type": "quiz",
                "question": "看书 (kànshū) means...?",
                "options": ["Buy books", "Read (a book)", "Write a book", "Sell books"],
                "answer": "b",
                "hints": [
                    "看 means 'to look/read/watch' and 书 means 'book.'",
                    "看 is one of the most versatile verbs in Chinese!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "看书 (kànshū) = read (a book). 看 = look/read/watch, 书 = book. 看 is incredibly versatile: 看书 (read), 看电影 (watch a movie), 看电视 (watch TV). 我在看书 = 'I'm reading a book.'",
                "is_boss": False,
                "flavor": "龙龙 peers over your shoulder at an ancient tome. 'This one's a real page-turner!'",
            },
            {
                "id": "media_movies",
                "title": "The Moving Pictures",
                "type": "quiz",
                "question": "看电影 (kàn diànyǐng) means...?",
                "options": ["Watch TV", "Watch a movie", "Take a photo", "Play a game"],
                "answer": "b",
                "hints": [
                    "电影: 电 = electric, 影 = shadow/image.",
                    "Literally: 'electric shadows' — what a poetic name for movies!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "看电影 (kàn diànyǐng) = watch a movie. 电 = electric, 影 = shadow. Movies are literally 'electric shadows' in Chinese — a beautiful name from early cinema. 我们去看电影吧! = 'Let's go watch a movie!'",
                "is_boss": False,
                "flavor": "龙龙 projects flickering shadows on the library wall with its flame. 'The first cinema!'",
            },
            {
                "id": "media_games",
                "title": "The Game Chamber",
                "type": "quiz",
                "question": "玩游戏 (wán yóuxì) means...?",
                "options": ["Watch games", "Play games", "Design games", "Buy games"],
                "answer": "b",
                "hints": [
                    "玩 means 'to play/have fun' and 游戏 means 'game.'",
                    "玩 is for leisure activities, not sports.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "玩游戏 (wán yóuxì) = play games. 玩 = play (for fun/leisure), 游戏 = game. Note: 玩 is for fun activities, while 打 is for sports. 玩电子游戏 = play video games. 别玩游戏了! = 'Stop playing games!'",
                "is_boss": False,
                "flavor": "龙龙 picks up a carved chess piece. 'Dragons invented strategy games, you know.'",
            },
            {
                "id": "media_internet",
                "title": "The Crystal Network",
                "type": "quiz",
                "question": "上网 (shàngwǎng) means...?",
                "options": ["Go fishing", "Go online / surf the internet", "Cast a net", "Go shopping"],
                "answer": "b",
                "hints": [
                    "上 means 'to go up/onto' and 网 means 'net.'",
                    "上网 literally means 'go onto the net' — the internet!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "上网 (shàngwǎng) = go online / surf the internet. 上 = go up/onto, 网 = net. 网 is used in many internet terms: 网站 (website), 网友 (online friend), 网购 (online shopping). 我在上网 = 'I'm online.'",
                "is_boss": False,
                "flavor": "龙龙 squints at a glowing crystal ball. 'In my day, we used carrier ravens!'",
            },
            {
                "id": "media_photos",
                "title": "Capturing Moments",
                "type": "quiz",
                "question": "拍照 (pāizhào) means...?",
                "options": ["Draw a picture", "Take a photo", "Paint a portrait", "Watch a show"],
                "answer": "b",
                "hints": [
                    "拍 means 'to clap/slap/snap' and 照 means 'photo/shine.'",
                    "拍照 = snap a photo. Think of the 'snap' of a shutter.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "拍照 (pāizhào) = take a photo. 拍 = snap/clap, 照 = photo/image. Related: 照片 (zhàopiàn) = photograph, 自拍 (zìpāi) = selfie (self + snap). 我们拍照吧! = 'Let's take a photo!'",
                "is_boss": False,
                "flavor": "龙龙 strikes a dramatic pose. 'Make sure you get my good side!'",
            },
            {
                "id": "media_kan_pattern",
                "title": "The 看 Pattern — One Verb, Many Uses",
                "type": "text",
                "question": "看 (kàn) appears in 看书 (read), 看电影 (watch a movie), 看电视 (watch TV), 看病 (see a doctor). What is the core meaning of 看?",
                "options": [
                    "To buy",
                    "To look at / see / watch / read",
                    "To enjoy",
                    "To study",
                ],
                "answer": "b",
                "hints": [
                    "看 covers all forms of visual attention.",
                    "Reading, watching, and seeing all involve looking.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "看 (kàn) = look/see/watch/read. It's one of the most versatile verbs: 看书 (read), 看电影 (watch a movie), 看电视 (watch TV), 看病 (see a doctor), 看朋友 (visit a friend). Context determines the exact meaning!",
                "is_boss": False,
                "flavor": "龙龙 points to its eyes. 'One verb for all things seen — that's elegant!'",
            },
            {
                "id": "media_weekend",
                "title": "What Did You Do This Weekend?",
                "type": "quiz",
                "question": "周末你做了什么? (Zhōumò nǐ zuòle shénme?) means...?",
                "options": [
                    "What do you want to do?",
                    "What did you do this weekend?",
                    "What will you do tomorrow?",
                    "Where did you go yesterday?",
                ],
                "answer": "b",
                "hints": [
                    "周末 = weekend, 做了 = did (past tense with 了).",
                    "什么 = what. The sentence asks about past weekend activities.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "周末你做了什么? = What did you do this weekend? 周末 (zhōumò) = weekend, 做 (zuò) = do, 了 (le) = past tense marker. Answer: 我看了电影 = 'I watched a movie.' 了 after a verb signals the action is completed.",
                "is_boss": False,
                "flavor": "龙龙 leans in eagerly. 'Tell me everything — I love a good weekend story!'",
            },
            {
                "id": "media_boss",
                "title": "Lord of the Library",
                "type": "quiz",
                "question": "Match them all: 看书, 看电影, 玩游戏, 上网, 拍照. Which list is correct?",
                "options": [
                    "Read, watch a movie, play games, go online, take a photo",
                    "Write, watch TV, play sports, go shopping, draw",
                    "Read, watch a movie, play games, go fishing, take a photo",
                    "Read, watch a movie, buy games, go online, take a photo",
                ],
                "answer": "a",
                "hints": [
                    "看书 = read (look + book), 上网 = go online (go on + net).",
                    "玩游戏 = play games (play + game), 拍照 = take a photo.",
                ],
                "xp": 50,
                "difficulty": "hard",
                "lesson": "Full review: 看书 (read), 看电影 (watch a movie), 玩游戏 (play games), 上网 (go online), 拍照 (take a photo). Five modern hobbies — you now know how to talk about your screen time in Chinese!",
                "is_boss": True,
                "flavor": "龙龙 stamps a golden seal on a scroll. 'The Scribe's Library yields its secrets to you!'",
            },
        ],
    },
    "outdoor_activities": {
        "id": "outdoor_activities",
        "name": "The Wilds Beyond the Wall",
        "description": "Learn outdoor activity vocabulary in Chinese",
        "level_required": 7,
        "challenges": [
            {
                "id": "outdoor_hiking",
                "title": "The Mountain Path",
                "type": "quiz",
                "question": "爬山 (páshān) means...?",
                "options": ["Climb a tree", "Hike / climb a mountain", "Cross a river", "Build a camp"],
                "answer": "b",
                "hints": [
                    "爬 means 'to climb/crawl' and 山 means 'mountain.'",
                    "爬山 is a very popular weekend activity in China.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "爬山 (páshān) = hike / climb a mountain. 爬 = climb, 山 = mountain. Hiking is hugely popular in China — famous mountains include 黄山 (Huáng Shān) and 泰山 (Tài Shān). 周末我们去爬山吧! = 'Let's go hiking this weekend!'",
                "is_boss": False,
                "flavor": "龙龙 gazes at a distant peak. 'I could fly, but where's the fun in that?'",
            },
            {
                "id": "outdoor_fishing",
                "title": "The Quiet Pond",
                "type": "quiz",
                "question": "钓鱼 (diàoyú) means...?",
                "options": ["Cook fish", "Catch fish (fishing)", "Eat fish", "Buy fish"],
                "answer": "b",
                "hints": [
                    "钓 means 'to fish with a hook' and 鱼 means 'fish.'",
                    "钓 has the metal radical 钅— think of a metal fishhook.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "钓鱼 (diàoyú) = fishing. 钓 = to angle/fish, 鱼 = fish. The 钅radical in 钓 hints at the metal hook. 他喜欢钓鱼 = 'He likes fishing.' Chinese fishing culture is ancient — 姜太公钓鱼 is a famous proverb about patience.",
                "is_boss": False,
                "flavor": "龙龙 lowers its tail into the pond and waits. 'Patience is a dragon's greatest virtue.'",
            },
            {
                "id": "outdoor_walking",
                "title": "A Leisurely Stroll",
                "type": "quiz",
                "question": "散步 (sànbù) means...?",
                "options": ["Run fast", "Take a walk / stroll", "March in formation", "Wander lost"],
                "answer": "b",
                "hints": [
                    "散 means 'leisurely/scattered' and 步 means 'step.'",
                    "散步 is a gentle, relaxing walk — not exercise.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "散步 (sànbù) = take a walk / stroll. 散 = leisurely, 步 = step. Unlike 跑步 (running), 散步 is relaxed. 饭后散步 = 'walk after dinner' — a beloved Chinese custom. 我们出去散散步吧 = 'Let's go for a walk.'",
                "is_boss": False,
                "flavor": "龙龙 ambles along a castle path, smelling flowers. 'Not everything needs to be an adventure.'",
            },
            {
                "id": "outdoor_travel",
                "title": "The Open Road",
                "type": "quiz",
                "question": "旅游 (lǚyóu) means...?",
                "options": ["Travel / tourism", "Move to a new city", "Get lost", "Go to work"],
                "answer": "a",
                "hints": [
                    "旅 means 'journey/travel' and 游 means 'tour/wander.'",
                    "旅游 is the general word for travel/tourism.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "旅游 (lǚyóu) = travel / tourism. 旅 = journey, 游 = tour. Related: 旅行 (lǚxíng) = travel/trip, 旅馆 (lǚguǎn) = hotel, 游客 (yóukè) = tourist. 我喜欢旅游 = 'I like traveling.' 你去哪儿旅游了? = 'Where did you travel to?'",
                "is_boss": False,
                "flavor": "龙龙 unfurls an ancient map. 'The world is vast — let's see it all!'",
            },
            {
                "id": "outdoor_picnic",
                "title": "The Feast in the Field",
                "type": "quiz",
                "question": "野餐 (yěcān) means...?",
                "options": ["Wild animal", "Picnic", "Barbecue", "Camping"],
                "answer": "b",
                "hints": [
                    "野 means 'wild/field' and 餐 means 'meal.'",
                    "野餐 = a meal in the wild = picnic!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "野餐 (yěcān) = picnic. 野 = wild/field, 餐 = meal. Literally 'wild meal' — eating outdoors! 我们去公园野餐 = 'Let's have a picnic in the park.' Related: 野外 (yěwài) = outdoors, 餐厅 (cāntīng) = restaurant.",
                "is_boss": False,
                "flavor": "龙龙 lays out a blanket and produces snacks from nowhere. 'Adventuring works up an appetite!'",
            },
            {
                "id": "outdoor_bu_pattern",
                "title": "步 — The Step Pattern",
                "type": "text",
                "question": "步 (bù) appears in 跑步 (run), 散步 (walk), 进步 (progress), 脚步 (footstep). What is the core meaning of 步?",
                "options": [
                    "Speed",
                    "Step / pace",
                    "Direction",
                    "Foot",
                ],
                "answer": "b",
                "hints": [
                    "步 means 'step' — it combines with other characters to describe movement.",
                    "跑步 = running steps, 散步 = leisurely steps, 进步 = forward steps.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "步 (bù) = step/pace. It appears in: 跑步 (run), 散步 (stroll), 进步 (progress — forward steps), 脚步 (footstep), 步行 (walk on foot). Recognizing 步 tells you the word involves movement or pace.",
                "is_boss": False,
                "flavor": "龙龙 stomps one foot. 'Every journey begins with a single 步!'",
            },
            {
                "id": "outdoor_suggestion",
                "title": "Let's Go Together!",
                "type": "quiz",
                "question": "我们去爬山吧! (Wǒmen qù páshān ba!) means...?",
                "options": [
                    "I climbed the mountain yesterday.",
                    "Let's go hiking!",
                    "Do you like hiking?",
                    "The mountain is very tall.",
                ],
                "answer": "b",
                "hints": [
                    "吧 (ba) at the end makes a suggestion — 'let's...'",
                    "我们 = we, 去 = go, 爬山 = hike.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "吧 (ba) turns a statement into a suggestion: 'let's...!' 我们去爬山吧! = Let's go hiking! Use this pattern for any activity: 我们去钓鱼吧! (Let's go fishing!), 我们去旅游吧! (Let's go traveling!), 我们去野餐吧! (Let's have a picnic!)",
                "is_boss": False,
                "flavor": "龙龙 spreads its wings invitingly. 'Adventures are better with friends!'",
            },
            {
                "id": "outdoor_boss",
                "title": "Warden of the Wilds",
                "type": "quiz",
                "question": "Match them all: 爬山, 钓鱼, 散步, 旅游, 野餐. Which list is correct?",
                "options": [
                    "Hike, fish, walk, travel, picnic",
                    "Climb a tree, swim, walk, travel, barbecue",
                    "Hike, fish, run, travel, picnic",
                    "Hike, fish, walk, move, picnic",
                ],
                "answer": "a",
                "hints": [
                    "爬山 = climb + mountain, 钓鱼 = hook + fish, 散步 = leisurely + step.",
                    "旅游 = travel/tour, 野餐 = wild + meal.",
                ],
                "xp": 50,
                "difficulty": "hard",
                "lesson": "Full review: 爬山 (hike), 钓鱼 (fish), 散步 (walk/stroll), 旅游 (travel), 野餐 (picnic). Five outdoor activities — you can now talk about your adventures beyond the castle walls!",
                "is_boss": True,
                "flavor": "龙龙 roars triumphantly from a hilltop. 'The wilds hold no secrets from you now!'",
            },
        ],
    },
    "talking_about_hobbies": {
        "id": "talking_about_hobbies",
        "name": "The Council of Interests",
        "description": "Learn to discuss hobbies and preferences in Chinese",
        "level_required": 9,
        "challenges": [
            {
                "id": "hobby_ask",
                "title": "The First Question",
                "type": "quiz",
                "question": "你的爱好是什么? (Nǐ de àihào shì shénme?) means...?",
                "options": [
                    "What is your name?",
                    "What are your hobbies?",
                    "What do you do for work?",
                    "What is your favorite food?",
                ],
                "answer": "b",
                "hints": [
                    "爱好 (àihào) = hobby/interest. 爱 = love, 好 = good/like.",
                    "什么 = what. The sentence asks about hobbies.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "你的爱好是什么? = What are your hobbies? 爱好 (àihào) = hobby (love + good). This is the standard way to ask about hobbies. Answer: 我的爱好是___ = 'My hobby is ___.' 爱好 can also be a verb: 我爱好音乐 = 'I'm fond of music.'",
                "is_boss": False,
                "flavor": "龙龙 settles into a great chair. 'Tell me, what brings you joy?'",
            },
            {
                "id": "hobby_like",
                "title": "I Like...",
                "type": "quiz",
                "question": "我喜欢打篮球 (Wǒ xǐhuan dǎ lánqiú) means...?",
                "options": [
                    "I don't like basketball",
                    "I like playing basketball",
                    "I want to play basketball",
                    "I used to play basketball",
                ],
                "answer": "b",
                "hints": [
                    "喜欢 (xǐhuan) = like/enjoy.",
                    "我 = I, 打篮球 = play basketball.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "我喜欢___ = I like ___. 喜欢 (xǐhuan) is the most common way to express liking. Place any hobby after it: 我喜欢听音乐, 我喜欢看书, 我喜欢旅游. You can add 很 for emphasis: 我很喜欢跳舞 = 'I really like dancing.'",
                "is_boss": False,
                "flavor": "龙龙 nods encouragingly. 'Good! Now say it with feeling!'",
            },
            {
                "id": "hobby_dislike",
                "title": "Not My Cup of Tea",
                "type": "quiz",
                "question": "我不太喜欢跑步 (Wǒ bú tài xǐhuan pǎobù) means...?",
                "options": [
                    "I really like running",
                    "I can't run",
                    "I don't really like running",
                    "I never go running",
                ],
                "answer": "c",
                "hints": [
                    "不太 = not very/not really — a polite way to express dislike.",
                    "不太喜欢 is softer than 不喜欢 (don't like).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "不太喜欢 (bú tài xǐhuan) = don't really like — a polite, soft way to express dislike. Chinese culture values tactfulness, so 不太喜欢 is preferred over blunt 不喜欢. 我不太喜欢上网 = 'I don't really like going online.'",
                "is_boss": False,
                "flavor": "龙龙 shrugs politely. 'There's an art to saying no gently.'",
            },
            {
                "id": "hobby_most_like",
                "title": "My Absolute Favorite",
                "type": "quiz",
                "question": "我最喜欢画画 (Wǒ zuì xǐhuan huàhuà) means...?",
                "options": [
                    "I sometimes draw",
                    "I like drawing the most / Drawing is my favorite",
                    "I want to learn drawing",
                    "I can draw well",
                ],
                "answer": "b",
                "hints": [
                    "最 (zuì) = most — it creates the superlative.",
                    "最喜欢 = like the most = favorite.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "最喜欢 (zuì xǐhuan) = like the most / favorite. 最 (zuì) = most. 我最喜欢___ = My favorite is ___. You can also ask: 你最喜欢什么? = 'What's your favorite?' This pattern works for anything: 最好 (best), 最大 (biggest), 最快 (fastest).",
                "is_boss": False,
                "flavor": "龙龙 places a golden crown on the word 最. 'The king of comparisons!'",
            },
            {
                "id": "hobby_reason",
                "title": "Because...",
                "type": "text",
                "question": "我喜欢游泳，因为很好玩 (Wǒ xǐhuan yóuyǒng, yīnwèi hěn hǎowán). What does 因为 mean?",
                "options": [
                    "But / however",
                    "Because",
                    "And also",
                    "Even though",
                ],
                "answer": "b",
                "hints": [
                    "因为 (yīnwèi) introduces a reason or cause.",
                    "好玩 = fun. The sentence explains WHY they like swimming.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "因为 (yīnwèi) = because. Use it to give reasons: 我喜欢唱歌，因为很有趣 = 'I like singing because it's fun.' Pair with 所以 (suǒyǐ) = so/therefore: 因为下雨，所以我在家看书 = 'Because it rained, I read at home.'",
                "is_boss": False,
                "flavor": "龙龙 raises a claw. 'WHY you like something matters as much as WHAT you like.'",
            },
            {
                "id": "hobby_free_time",
                "title": "In My Free Time",
                "type": "quiz",
                "question": "你有空的时候喜欢做什么? (Nǐ yǒu kòng de shíhou xǐhuan zuò shénme?) means...?",
                "options": [
                    "What did you do yesterday?",
                    "What do you like to do in your free time?",
                    "What is your job?",
                    "When are you free?",
                ],
                "answer": "b",
                "hints": [
                    "有空 = have free time, 的时候 = when/at the time of.",
                    "喜欢做什么 = like to do what.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "有空的时候 (yǒu kòng de shíhou) = when (you) have free time. 有空 = have free time, 的时候 = when. This is a natural way to discuss hobbies: 我有空的时候喜欢看电影 = 'In my free time, I like watching movies.'",
                "is_boss": False,
                "flavor": "龙龙 stretches lazily. 'Even dragons need downtime!'",
            },
            {
                "id": "hobby_together",
                "title": "Shall We Do It Together?",
                "type": "quiz",
                "question": "你想不想一起去看电影? (Nǐ xiǎng bu xiǎng yìqǐ qù kàn diànyǐng?) means...?",
                "options": [
                    "Did you watch a movie?",
                    "Do you want to go watch a movie together?",
                    "Do you like movies?",
                    "Where is the movie theater?",
                ],
                "answer": "b",
                "hints": [
                    "想不想 = want or not want (A-not-A question pattern).",
                    "一起 = together, 去看电影 = go watch a movie.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "想不想 (xiǎng bu xiǎng) = the A-not-A question pattern (want or not want?). 一起 (yìqǐ) = together. This is a natural way to invite someone: 你想不想一起去爬山? = 'Do you want to go hiking together?' Answer: 想! (Yes!) or 不想 (No).",
                "is_boss": False,
                "flavor": "龙龙 extends a wing toward you. 'Hobbies are better shared!'",
            },
            {
                "id": "hobby_boss",
                "title": "Grand Councilor of Interests",
                "type": "quiz",
                "question": "Which sentence correctly says 'My hobby is listening to music, because it's very relaxing'?",
                "options": [
                    "我的爱好是听音乐，因为很放松",
                    "我的爱好是听音乐，所以很放松",
                    "我的爱好听音乐，因为很放松",
                    "我爱好是听音乐，因为很放松",
                ],
                "answer": "a",
                "hints": [
                    "The structure is: 我的爱好是___, 因为___ (My hobby is ___, because ___).",
                    "是 links the subject to the hobby; 因为 introduces the reason.",
                ],
                "xp": 50,
                "difficulty": "hard",
                "lesson": "Complete hobby sentence: 我的爱好是听音乐，因为很放松 = My hobby is listening to music, because it's very relaxing. Structure: 我的爱好是 + [hobby] + 因为 + [reason]. You can now introduce your hobbies, express preferences, and give reasons — all in Chinese!",
                "is_boss": True,
                "flavor": "龙龙 bows deeply. 'You can speak of your passions with eloquence and grace. The Council is impressed!'",
            },
        ],
    },
}
