"""
zones.py — Solar System Deep Dive zones and challenges for the Planets skill pack.

All challenges use "type": "quiz" with multiple-choice options.
Designed for ages 7-10, guided warmly by Puck.
Goes deep into each planet — far beyond the basics.
"""

ZONE_ORDER = [
    "mercury_venus",
    "earth_moon_deep",
    "mars_deep",
    "jupiter_saturn_deep",
    "ice_giants",
    "dwarf_planets",
    "space_missions",
]

ZONES = {
    # ── Zone 1: Mercury & Venus ──────────────────────────────────────
    "mercury_venus": {
        "id": "mercury_venus",
        "name": "The Scorched Worlds",
        "description": "Explore Mercury's craters and Venus's deadly greenhouse",
        "level_required": 1,
        "challenges": [
            {
                "id": "mercury_craters",
                "title": "A World of Craters",
                "type": "quiz",
                "question": "Mercury is covered in craters. Why doesn't it have weather or wind to wear them away?",
                "options": [
                    "It spins too fast",
                    "It has almost no atmosphere",
                    "Its craters are made of diamond",
                    "It is too far from the Sun",
                ],
                "answer": "b",
                "hints": [
                    "Think about what you need for wind and weather — air!",
                    "Mercury is the closest planet to the Sun, but it has almost nothing around it.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Mercury has almost no atmosphere — just a thin wisp of gas called an exosphere. Without air, there is no wind, no rain, and no weather to erode its ancient craters. Some craters are billions of years old!",
                "is_boss": False,
                "flavor": "Puck holds the telescope steady. Mercury's battered surface glows silver-grey.",
            },
            {
                "id": "mercury_temps",
                "title": "Hot and Cold Extremes",
                "type": "quiz",
                "question": "Mercury's daytime temperature can reach 430°C, but at night it drops to -180°C. Why are the swings so extreme?",
                "options": [
                    "It has no thick atmosphere to trap heat",
                    "It is made of ice on one side",
                    "The Sun turns off at night",
                    "Mercury has two suns",
                ],
                "answer": "a",
                "hints": [
                    "Earth stays warm at night because something holds the heat in — like a blanket.",
                    "Mercury doesn't have that blanket.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "An atmosphere acts like a blanket — it traps heat and keeps temperatures steady. Mercury has almost no atmosphere, so heat escapes into space as soon as the Sun sets, causing extreme temperature swings of over 600°C!",
                "is_boss": False,
                "flavor": "The telescope shows one side of Mercury blazing white, the other side dark and frozen.",
            },
            {
                "id": "mercury_caloris",
                "title": "The Caloris Basin",
                "type": "quiz",
                "question": "Mercury's largest crater, the Caloris Basin, is about 1,550 km across. What caused it?",
                "options": [
                    "A massive asteroid impact",
                    "A volcanic eruption",
                    "An earthquake",
                    "The Sun's gravity pulling the surface",
                ],
                "answer": "a",
                "hints": [
                    "Something very large crashed into Mercury long ago.",
                    "The impact was so powerful it sent shockwaves through the entire planet!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The Caloris Basin was created by a huge asteroid slamming into Mercury about 3.9 billion years ago. The impact was so powerful that it created hills on the exact opposite side of the planet from the shockwaves traveling all the way through!",
                "is_boss": False,
                "flavor": "Puck whistles. The crater fills the entire telescope view — it's enormous!",
            },
            {
                "id": "venus_greenhouse",
                "title": "Venus: The Greenhouse Trap",
                "type": "quiz",
                "question": "Venus is hotter than Mercury even though it's farther from the Sun. What causes this?",
                "options": [
                    "Venus has active volcanoes everywhere",
                    "Venus has a runaway greenhouse effect",
                    "Venus is closer to Jupiter's heat",
                    "Venus has a second hidden sun",
                ],
                "answer": "b",
                "hints": [
                    "Venus has a super-thick atmosphere made mostly of carbon dioxide.",
                    "A greenhouse traps heat inside — Venus's atmosphere does the same thing, but much worse.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Venus has a thick atmosphere of carbon dioxide that traps the Sun's heat and never lets it escape — a runaway greenhouse effect. The surface temperature is about 465°C, hot enough to melt lead! It's the hottest planet in our solar system.",
                "is_boss": False,
                "flavor": "Puck peers through swirling yellow clouds. 'Don't touch anything down there,' Puck warns.",
            },
            {
                "id": "venus_spin",
                "title": "Spinning Backwards",
                "type": "quiz",
                "question": "Venus rotates in the opposite direction from most planets. What does this mean?",
                "options": [
                    "The Sun rises in the west on Venus",
                    "Venus has no gravity",
                    "Venus orbits the Sun backwards",
                    "Days on Venus last only one hour",
                ],
                "answer": "a",
                "hints": [
                    "On Earth, the Sun rises in the east because of how we spin. If you spun the other way...",
                    "Venus rotates clockwise while most planets rotate counter-clockwise.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Venus has retrograde rotation — it spins clockwise while most planets spin counter-clockwise. This means the Sun rises in the west and sets in the east! Scientists think a massive collision long ago may have flipped Venus upside down.",
                "is_boss": False,
                "flavor": "Puck spins in a circle the wrong way. 'Like this! Everything is backwards on Venus!'",
            },
            {
                "id": "venus_volcanoes",
                "title": "A Volcanic World",
                "type": "quiz",
                "question": "Venus has more volcanoes than any other planet in our solar system. About how many have scientists found?",
                "options": [
                    "About 50",
                    "About 500",
                    "About 1,600",
                    "About 85,000",
                ],
                "answer": "c",
                "hints": [
                    "It's a LOT more than Earth's volcanoes.",
                    "Think in the thousands, but not tens of thousands.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Scientists have found about 1,600 major volcanoes on Venus — more than any other planet! Some may still be active. The thick clouds of sulfuric acid in Venus's atmosphere make it very hard to see the surface, so radar from spacecraft is used to map it.",
                "is_boss": True,
                "flavor": "The telescope cuts through Venus's clouds. A landscape of volcanoes stretches to the horizon.",
            },
        ],
    },

    # ── Zone 2: Earth & Moon Deep Dive ───────────────────────────────
    "earth_moon_deep": {
        "id": "earth_moon_deep",
        "name": "Our World Up Close",
        "description": "Explore Earth's hidden layers and the Moon's secrets",
        "level_required": 3,
        "challenges": [
            {
                "id": "earth_layers",
                "title": "Layers of the Earth",
                "type": "quiz",
                "question": "The Earth has four main layers. Which is the correct order from the outside in?",
                "options": [
                    "Crust, Mantle, Outer Core, Inner Core",
                    "Mantle, Crust, Inner Core, Outer Core",
                    "Inner Core, Outer Core, Crust, Mantle",
                    "Crust, Outer Core, Mantle, Inner Core",
                ],
                "answer": "a",
                "hints": [
                    "We live on the outermost layer — the thin, rocky one.",
                    "The very center of the Earth is a solid ball of metal.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Earth has four layers: the thin rocky Crust on the outside, the thick hot Mantle beneath it, the liquid metal Outer Core, and the solid metal Inner Core at the center. The inner core is as hot as the surface of the Sun — about 5,500°C!",
                "is_boss": False,
                "flavor": "Puck slices the Primer's globe in half like an apple. Four coloured rings glow inside.",
            },
            {
                "id": "tectonic_plates",
                "title": "The Moving Puzzle",
                "type": "quiz",
                "question": "Earth's crust is broken into giant pieces called tectonic plates. What happens when two plates push into each other?",
                "options": [
                    "They create rainbows",
                    "Mountains can form",
                    "The ocean dries up",
                    "Gravity gets weaker",
                ],
                "answer": "b",
                "hints": [
                    "Think about what happens when you push two pieces of paper together on a table.",
                    "The Himalayas — the tallest mountains — formed this way!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When tectonic plates collide, the crust crumples and folds upward, creating mountains! The Himalayas formed when the Indian plate crashed into the Asian plate — and they're still growing by about 1 cm per year!",
                "is_boss": False,
                "flavor": "Two glowing puzzle pieces on the globe slowly push together. Mountains rise where they meet.",
            },
            {
                "id": "magnetic_field",
                "title": "Earth's Invisible Shield",
                "type": "quiz",
                "question": "Earth has a magnetic field that protects us. What creates it?",
                "options": [
                    "The Moon pulling on Earth",
                    "Swirling liquid iron in the outer core",
                    "The ozone layer spinning",
                    "Magnetized rocks on the surface",
                ],
                "answer": "b",
                "hints": [
                    "The answer is deep inside the Earth — in one of the layers.",
                    "It involves liquid metal moving around, creating a giant magnet.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Earth's magnetic field is created by swirling liquid iron in the outer core — this acts like a giant electromagnet! The magnetic field extends far into space and deflects harmful solar wind and radiation. Without it, life on Earth might not exist!",
                "is_boss": False,
                "flavor": "Puck draws invisible lines arcing from pole to pole. 'Our shield!' Puck whispers.",
            },
            {
                "id": "moon_formation",
                "title": "How the Moon Was Born",
                "type": "quiz",
                "question": "Most scientists believe the Moon formed when something happened to early Earth. What was it?",
                "options": [
                    "Earth captured a passing asteroid",
                    "A Mars-sized object crashed into Earth",
                    "Part of the Sun broke off",
                    "Earth spun so fast a piece flew off",
                ],
                "answer": "b",
                "hints": [
                    "Something enormous — the size of a planet — hit Earth long ago.",
                    "The debris from this giant impact collected in orbit and became the Moon.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "About 4.5 billion years ago, a Mars-sized object called Theia crashed into early Earth. The collision was so violent that huge amounts of debris were thrown into orbit, which eventually clumped together to form our Moon! This is called the Giant Impact Hypothesis.",
                "is_boss": False,
                "flavor": "The Primer shows a fiery collision — rocks and magma flying everywhere — and then, slowly, the Moon forming.",
            },
            {
                "id": "eclipses",
                "title": "When Shadows Cross",
                "type": "quiz",
                "question": "During a total solar eclipse, what blocks the Sun's light?",
                "options": [
                    "Earth's shadow falls on the Sun",
                    "The Moon passes between Earth and the Sun",
                    "A large asteroid crosses the Sun",
                    "Clouds in space block the light",
                ],
                "answer": "b",
                "hints": [
                    "It's our closest neighbor in space — something that orbits Earth.",
                    "Even though the Moon is much smaller than the Sun, it's also much closer to us.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A solar eclipse happens when the Moon passes directly between Earth and the Sun, casting a shadow on Earth. The Moon is 400 times smaller than the Sun, but it's also about 400 times closer — so they look almost the same size in our sky! This is a remarkable coincidence.",
                "is_boss": False,
                "flavor": "The telescope view darkens. The Moon slides across the Sun, and a ring of fire appears.",
            },
            {
                "id": "earth_tilt_seasons",
                "title": "Why We Have Seasons",
                "type": "quiz",
                "question": "What causes the four seasons on Earth?",
                "options": [
                    "Earth getting closer to and farther from the Sun",
                    "The Sun getting hotter and cooler",
                    "Earth's axis being tilted 23.5 degrees",
                    "The Moon's gravity changing the weather",
                ],
                "answer": "c",
                "hints": [
                    "It's about how Earth is tilted, not how far away it is.",
                    "When your part of Earth tilts toward the Sun, you get more direct sunlight — summer!",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Earth's axis is tilted 23.5 degrees. As Earth orbits the Sun, different parts of the planet tilt toward or away from the Sun, creating seasons. When the Northern Hemisphere tilts toward the Sun, it's summer there and winter in the Southern Hemisphere!",
                "is_boss": True,
                "flavor": "Puck tilts the Primer's globe and slowly walks it around a glowing lamp. 'Watch what happens!'",
            },
        ],
    },

    # ── Zone 3: Mars Deep Dive ───────────────────────────────────────
    "mars_deep": {
        "id": "mars_deep",
        "name": "The Red Planet Revealed",
        "description": "Climb Olympus Mons, explore canyons, and drive the rovers",
        "level_required": 5,
        "challenges": [
            {
                "id": "olympus_mons",
                "title": "The Tallest Mountain",
                "type": "quiz",
                "question": "Olympus Mons on Mars is the tallest volcano in the solar system. How does it compare to Mount Everest?",
                "options": [
                    "About the same height",
                    "Twice as tall",
                    "Nearly three times as tall",
                    "Ten times as tall",
                ],
                "answer": "c",
                "hints": [
                    "Everest is about 8.8 km tall. Olympus Mons is about 21.9 km tall.",
                    "Think about how many Everests you'd need to stack to reach the top.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Olympus Mons is about 21.9 km tall — nearly three times the height of Mount Everest! It's also enormous in area — about the size of the entire country of France. Mars has lower gravity than Earth, which allowed volcanoes to grow much, much larger.",
                "is_boss": False,
                "flavor": "The telescope zooms in on Mars. A volcano so tall its peak pokes above the clouds!",
            },
            {
                "id": "valles_marineris",
                "title": "The Grand Canyon's Big Brother",
                "type": "quiz",
                "question": "Valles Marineris on Mars is the largest canyon in the solar system. How long is it?",
                "options": [
                    "About 450 km — like the Grand Canyon",
                    "About 4,000 km — stretching across the entire United States",
                    "About 500 km — about the size of Texas",
                    "About 100 km — smaller than most canyons on Earth",
                ],
                "answer": "b",
                "hints": [
                    "It's much, much bigger than the Grand Canyon on Earth.",
                    "If you put it on Earth, it would stretch from New York to Los Angeles!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Valles Marineris is about 4,000 km long, up to 200 km wide, and 7 km deep! It would stretch across the entire United States. The Grand Canyon could fit inside one of its smaller side channels. Scientists think it formed as Mars's crust was pulled apart by volcanic activity.",
                "is_boss": False,
                "flavor": "Puck gasps. The canyon stretches across the entire face of Mars in the telescope.",
            },
            {
                "id": "mars_water",
                "title": "Where Did the Water Go?",
                "type": "quiz",
                "question": "Scientists believe Mars once had rivers and maybe even an ocean. Where is most of that water now?",
                "options": [
                    "It evaporated into outer space and is gone forever",
                    "Frozen underground and in the polar ice caps",
                    "It was absorbed by Mars's core",
                    "Aliens took it to another planet",
                ],
                "answer": "b",
                "hints": [
                    "Mars still has ice at its north and south poles.",
                    "There's also a lot of frozen water hidden beneath the surface.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Mars once had flowing water on its surface — we can see dried-up river channels and lake beds. Most of that water is now frozen in the polar ice caps and trapped underground as permafrost. Some water was also lost to space as Mars's atmosphere thinned over billions of years.",
                "is_boss": False,
                "flavor": "The Primer shows ancient Mars — blue rivers flowing through red canyons — then fades to the dry world of today.",
            },
            {
                "id": "mars_red",
                "title": "Why Mars Is Red",
                "type": "quiz",
                "question": "Why does Mars appear red when we look at it?",
                "options": [
                    "It is very hot and glowing",
                    "Its soil is rich in iron oxide — rust",
                    "Red plants cover the surface",
                    "Sunlight reflects differently on Mars",
                ],
                "answer": "b",
                "hints": [
                    "Think about what happens when iron gets wet and sits outside for a long time.",
                    "The same orange-red colour you see on a rusty nail is covering Mars!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Mars is red because its soil is rich in iron oxide — the same chemical that makes rust! Billions of years ago, iron in Martian rocks reacted with a small amount of oxygen in the atmosphere, coating the surface in fine red-orange dust. This dust also fills the Martian sky, making sunsets on Mars look blue!",
                "is_boss": False,
                "flavor": "Puck picks up a pinch of rusty-red dust and lets it blow across the Primer's page.",
            },
            {
                "id": "curiosity_rover",
                "title": "Curiosity's Mission",
                "type": "quiz",
                "question": "NASA's Curiosity rover landed on Mars in 2012. What is its main mission?",
                "options": [
                    "To find living Martians",
                    "To investigate whether Mars ever had conditions suitable for life",
                    "To build a base for astronauts",
                    "To collect rocks and bring them back to Earth",
                ],
                "answer": "b",
                "hints": [
                    "Curiosity doesn't bring anything back — it studies things on Mars.",
                    "It's looking for clues that tiny life forms could have lived there long ago.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Curiosity is a car-sized rover exploring Gale Crater on Mars. Its mission is to investigate whether Mars ever had the right conditions — water, chemicals, and energy — to support microbial life. It has found evidence of ancient lakes and organic molecules!",
                "is_boss": False,
                "flavor": "The Primer shows a six-wheeled robot trundling across a rust-red landscape, its camera arm waving.",
            },
            {
                "id": "perseverance_rover",
                "title": "Perseverance and Ingenuity",
                "type": "quiz",
                "question": "The Perseverance rover brought a small helicopter called Ingenuity to Mars. Why was flying on Mars so difficult?",
                "options": [
                    "Mars has too much gravity for helicopters",
                    "Mars's atmosphere is about 100 times thinner than Earth's",
                    "There is too much wind on Mars",
                    "Helicopters cannot work without water",
                ],
                "answer": "b",
                "hints": [
                    "Helicopter blades push against air to fly. What if there's very little air?",
                    "Mars has an atmosphere, but it's extremely thin compared to Earth's.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Mars's atmosphere is about 100 times thinner than Earth's, so helicopter blades have almost nothing to push against! Ingenuity solved this with blades that spin at over 2,500 rpm — five times faster than a helicopter on Earth. In April 2021, it became the first aircraft to fly on another planet!",
                "is_boss": True,
                "flavor": "A tiny helicopter rises above the red dust, its blades a blur. Puck cheers: 'It flew! It actually flew!'",
            },
        ],
    },

    # ── Zone 4: Jupiter & Saturn Deep Dive ───────────────────────────
    "jupiter_saturn_deep": {
        "id": "jupiter_saturn_deep",
        "name": "The Gas Giants",
        "description": "Explore Jupiter's storms and moons, and Saturn's magnificent rings",
        "level_required": 7,
        "challenges": [
            {
                "id": "great_red_spot",
                "title": "The Great Red Spot",
                "type": "quiz",
                "question": "Jupiter's Great Red Spot is a giant storm. How long has it been raging?",
                "options": [
                    "About 10 years",
                    "About 100 years",
                    "At least 350 years (maybe longer)",
                    "Exactly 1 million years",
                ],
                "answer": "c",
                "hints": [
                    "Astronomers have been watching it since the 1600s!",
                    "It's been going for centuries, not just decades.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The Great Red Spot is a massive anticyclonic storm that has been observed since at least 1665 — over 350 years! It's so large that Earth could fit inside it. The storm has been slowly shrinking over the last century, but it's still the largest storm in the solar system.",
                "is_boss": False,
                "flavor": "The telescope shows Jupiter's swirling bands — and there, like a giant eye, the Great Red Spot stares back.",
            },
            {
                "id": "europa_ocean",
                "title": "Europa's Hidden Ocean",
                "type": "quiz",
                "question": "Jupiter's moon Europa is one of the most exciting places in the solar system. What's hidden under its icy surface?",
                "options": [
                    "A giant diamond",
                    "A liquid water ocean",
                    "A ball of pure iron",
                    "Nothing — it's solid ice all the way down",
                ],
                "answer": "b",
                "hints": [
                    "Scientists are very interested in Europa because of something essential for life.",
                    "Cracks in the ice suggest something liquid is moving underneath!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Europa has a vast liquid water ocean hidden beneath a shell of ice! The ocean may contain twice as much water as all of Earth's oceans combined. Jupiter's gravity flexes Europa's interior and creates heat, keeping the water liquid. Scientists think this ocean could possibly harbor simple life forms.",
                "is_boss": False,
                "flavor": "Puck points to a smooth, icy moon with cracks like a broken eggshell. 'There's an ocean under there!'",
            },
            {
                "id": "io_volcanoes",
                "title": "Io: The Volcanic Moon",
                "type": "quiz",
                "question": "Jupiter's moon Io is the most volcanically active body in the solar system. What causes all its volcanic activity?",
                "options": [
                    "Io is very close to the Sun",
                    "Tidal forces from Jupiter's gravity squeeze and heat Io",
                    "Io has a core made of dynamite",
                    "Solar wind heats Io's surface",
                ],
                "answer": "b",
                "hints": [
                    "Jupiter is enormous and pulls on Io very strongly.",
                    "The constant squeezing and stretching from gravity creates heat inside Io.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Io orbits very close to massive Jupiter, and the other large moons pull on it too. This tidal tug-of-war constantly squeezes and flexes Io's interior, generating intense heat — enough to power hundreds of active volcanoes! Some eruptions shoot material 500 km above the surface.",
                "is_boss": False,
                "flavor": "The telescope reveals a yellow-orange moon spewing fountains of lava into the blackness of space.",
            },
            {
                "id": "saturn_rings",
                "title": "Saturn's Rings Revealed",
                "type": "quiz",
                "question": "What are Saturn's beautiful rings mostly made of?",
                "options": [
                    "Solid rock plates",
                    "Dust and gas",
                    "Pieces of ice and rock, ranging from tiny grains to house-sized chunks",
                    "Frozen light from the Sun",
                ],
                "answer": "c",
                "hints": [
                    "The rings contain billions of individual pieces orbiting Saturn.",
                    "Some pieces are as tiny as a grain of sand, others as big as a house!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Saturn's rings are made of billions of pieces of ice and rock, from tiny grains to chunks the size of houses. The rings stretch out 282,000 km from Saturn but are incredibly thin — only about 10 meters thick in most places! They may have formed when a moon was shattered by an impact.",
                "is_boss": False,
                "flavor": "Puck flies through the telescope view, weaving between glittering chunks of ice. 'Like a cosmic skating rink!'",
            },
            {
                "id": "titan_atmosphere",
                "title": "Titan: Saturn's Giant Moon",
                "type": "quiz",
                "question": "Saturn's largest moon, Titan, is special because it has something very unusual for a moon. What is it?",
                "options": [
                    "A thick atmosphere with clouds and rain",
                    "Rings like Saturn",
                    "Its own tiny moon",
                    "Active nuclear reactions on the surface",
                ],
                "answer": "a",
                "hints": [
                    "Titan is the only moon in the solar system that has this feature, which is thick and orange.",
                    "It even has lakes and rivers — but not made of water!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Titan has a thick orange atmosphere — denser than Earth's! It even has weather: methane and ethane rain falls from clouds, flows in rivers, and collects in lakes and seas. Titan is the only moon with a substantial atmosphere and the only place beyond Earth with known stable liquid on its surface.",
                "is_boss": False,
                "flavor": "An orange haze surrounds a mysterious moon. 'It rains there,' Puck whispers, 'but not water!'",
            },
            {
                "id": "jupiter_size",
                "title": "The King of Planets",
                "type": "quiz",
                "question": "Jupiter is the largest planet in our solar system. How many Earths could fit inside it?",
                "options": [
                    "About 11",
                    "About 100",
                    "About 1,300",
                    "About 10,000",
                ],
                "answer": "c",
                "hints": [
                    "Jupiter's diameter is about 11 times Earth's, but volume grows much faster.",
                    "Think of how many small marbles fit inside a basketball.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "About 1,300 Earths could fit inside Jupiter by volume! Jupiter is so massive that it contains more than twice the mass of all the other planets combined. Despite its size, Jupiter spins incredibly fast — a day on Jupiter is only about 10 hours long!",
                "is_boss": True,
                "flavor": "The Primer shows tiny Earths streaming into Jupiter like marbles into a barrel. It just keeps going and going...",
            },
        ],
    },

    # ── Zone 5: Ice Giants ───────────────────────────────────────────
    "ice_giants": {
        "id": "ice_giants",
        "name": "The Distant Ice Worlds",
        "description": "Discover Uranus's wild tilt, Neptune's fierce winds, and diamond rain",
        "level_required": 9,
        "challenges": [
            {
                "id": "uranus_tilt",
                "title": "The Sideways Planet",
                "type": "quiz",
                "question": "Uranus is tilted almost completely on its side — about 98 degrees. What does this mean for its seasons?",
                "options": [
                    "It has no seasons at all",
                    "Each pole gets 42 years of sunlight followed by 42 years of darkness",
                    "Seasons change every day",
                    "Only the equator ever sees the Sun",
                ],
                "answer": "b",
                "hints": [
                    "Uranus takes 84 years to orbit the Sun. When a pole points at the Sun, it stays that way for a long time.",
                    "Imagine lying on your side and slowly rolling around a lamp — each end faces the light for half the trip.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Uranus is tilted 98 degrees — nearly on its side! This means each pole points toward the Sun for about 42 years, then faces away for 42 years. Scientists think a massive collision with an Earth-sized object billions of years ago knocked Uranus onto its side.",
                "is_boss": False,
                "flavor": "Puck tilts the telescope until the pale blue planet rolls on its side. 'It's been doing this for billions of years!'",
            },
            {
                "id": "neptune_winds",
                "title": "The Windiest Planet",
                "type": "quiz",
                "question": "Neptune has the fastest winds in the solar system. How fast can they blow?",
                "options": [
                    "About 100 km/h — like a fast car",
                    "About 400 km/h — like a race car",
                    "About 2,100 km/h — faster than the speed of sound",
                    "About 10,000 km/h — almost as fast as a rocket",
                ],
                "answer": "c",
                "hints": [
                    "Neptune's winds are much faster than any hurricane on Earth.",
                    "They can exceed the speed of sound!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Neptune's winds can reach 2,100 km/h — the fastest in the solar system! That's about 1.5 times the speed of sound. What makes this even more mysterious is that Neptune is so far from the Sun that it gets very little solar energy, yet it still generates these incredibly powerful winds.",
                "is_boss": False,
                "flavor": "The deep blue planet churns with bands of howling wind. Puck grips the telescope tightly.",
            },
            {
                "id": "triton_moon",
                "title": "Triton: The Captured Moon",
                "type": "quiz",
                "question": "Neptune's largest moon, Triton, orbits in the opposite direction from Neptune's rotation. What does this suggest?",
                "options": [
                    "Triton formed at the same time as Neptune",
                    "Triton was probably captured from the Kuiper Belt",
                    "Neptune spins the wrong way",
                    "All moons orbit backwards",
                ],
                "answer": "b",
                "hints": [
                    "Moons that form with their planet usually orbit in the same direction as the planet spins.",
                    "If it goes the wrong way, it probably came from somewhere else!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Triton orbits Neptune backwards (retrograde), which strongly suggests it didn't form with Neptune but was captured from the Kuiper Belt. Triton has geysers that shoot nitrogen gas 8 km high! It's one of the coldest objects in the solar system at -235°C.",
                "is_boss": False,
                "flavor": "A frozen world spirals the wrong way around deep blue Neptune. Geysers erupt from its icy surface.",
            },
            {
                "id": "diamond_rain",
                "title": "It Rains Diamonds",
                "type": "quiz",
                "question": "Scientists believe that deep inside Uranus and Neptune, something extraordinary happens. What is it?",
                "options": [
                    "Water turns into gold",
                    "Carbon is squeezed into diamonds that rain downward",
                    "Lightning creates rubies",
                    "Hydrogen becomes solid rock",
                ],
                "answer": "b",
                "hints": [
                    "The pressures deep inside these planets are unimaginably high.",
                    "Carbon exists in their atmospheres, and under extreme pressure, carbon becomes...",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Deep inside Uranus and Neptune, extreme pressure and temperature crush carbon atoms into diamonds! These diamonds may rain down through the interior like hailstones. Scientists have recreated these conditions in labs and confirmed that diamond rain is possible. There could be oceans of liquid diamond deep inside these planets!",
                "is_boss": False,
                "flavor": "Puck's eyes go wide. 'Diamonds! Raining! Like a treasure storm inside a planet!'",
            },
            {
                "id": "ice_giant_magnetic",
                "title": "Wonky Magnetic Fields",
                "type": "quiz",
                "question": "The magnetic fields of Uranus and Neptune are very unusual compared to Earth's. What makes them strange?",
                "options": [
                    "They are tilted far off-center and don't line up with the poles",
                    "They don't have magnetic fields at all",
                    "Their magnetic fields point toward the Sun",
                    "The fields switch on and off every hour",
                ],
                "answer": "a",
                "hints": [
                    "Earth's magnetic field comes from the center and lines up roughly with the north-south poles.",
                    "On these planets, the magnetic field is tilted and shifted away from the center.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Unlike Earth, where the magnetic field is roughly aligned with the rotation axis, Uranus's magnetic field is tilted 59 degrees and Neptune's is tilted 47 degrees from their rotation axes. They're also offset from the center of the planet! Scientists think this is because the fields are generated in a thin shell of electrically conducting water, not deep in the core.",
                "is_boss": True,
                "flavor": "Puck draws wobbly magnetic lines around the ice giants. 'Nothing about these planets is normal!'",
            },
        ],
    },

    # ── Zone 6: Dwarf Planets ────────────────────────────────────────
    "dwarf_planets": {
        "id": "dwarf_planets",
        "name": "The Small Worlds",
        "description": "Meet Pluto, Ceres, Eris, and the icy worlds beyond Neptune",
        "level_required": 11,
        "challenges": [
            {
                "id": "pluto_heart",
                "title": "Pluto's Frozen Heart",
                "type": "quiz",
                "question": "When NASA's New Horizons spacecraft flew past Pluto in 2015, it discovered a heart-shaped feature on the surface. What is it made of?",
                "options": [
                    "Red rock and iron",
                    "Frozen nitrogen, carbon monoxide, and methane ice",
                    "Liquid water",
                    "Volcanic ash",
                ],
                "answer": "b",
                "hints": [
                    "Pluto is extremely cold — about -230°C — so unusual things freeze there.",
                    "The heart-shaped region is called Tombaugh Regio, and it's made of exotic ices.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Pluto's famous heart-shaped feature is called Tombaugh Regio (named after Pluto's discoverer, Clyde Tombaugh). The left side, called Sputnik Planitia, is a vast plain of frozen nitrogen ice that slowly flows like glaciers on Earth. New Horizons revealed that Pluto is far more complex and interesting than anyone expected!",
                "is_boss": False,
                "flavor": "The telescope focuses on a tiny distant world — and there it is: a perfect heart shape on its surface!",
            },
            {
                "id": "pluto_reclassified",
                "title": "Why Pluto Was Reclassified",
                "type": "quiz",
                "question": "In 2006, Pluto was reclassified from a planet to a dwarf planet. What is one reason it didn't meet the full definition of a planet?",
                "options": [
                    "It's too hot",
                    "It hasn't cleared the neighborhood around its orbit",
                    "It doesn't orbit the Sun",
                    "It has no moons",
                ],
                "answer": "b",
                "hints": [
                    "Pluto does orbit the Sun and it is round, but there's a third requirement...",
                    "A full planet must be the dominant object in its orbital zone.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "To be a planet, an object must: (1) orbit the Sun, (2) be massive enough to be round, and (3) have 'cleared the neighborhood' around its orbit — meaning it's the dominant gravitational force. Pluto shares the Kuiper Belt with many other icy objects, so it hasn't cleared its orbit. Pluto has five known moons, including Charon!",
                "is_boss": False,
                "flavor": "Puck looks sympathetic. 'Pluto is still wonderful — it just got a new category!'",
            },
            {
                "id": "ceres_dwarf",
                "title": "Ceres: The Asteroid Belt's Giant",
                "type": "quiz",
                "question": "Ceres is the largest object in the asteroid belt and is classified as a dwarf planet. Where is the asteroid belt?",
                "options": [
                    "Between Earth and Venus",
                    "Between Mars and Jupiter",
                    "Between Saturn and Uranus",
                    "Beyond Neptune",
                ],
                "answer": "b",
                "hints": [
                    "The asteroid belt separates the rocky inner planets from the gas giants.",
                    "It's between the fourth and fifth planets from the Sun.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The asteroid belt lies between Mars and Jupiter, and Ceres is its largest object at about 940 km across. NASA's Dawn spacecraft visited Ceres and found bright spots that turned out to be salt deposits — evidence that salty water once reached the surface! Ceres may still have liquid water underground.",
                "is_boss": False,
                "flavor": "The telescope sweeps past Mars into a field of tumbling rocks — and one round dwarf planet shining among them.",
            },
            {
                "id": "eris_discovery",
                "title": "Eris: The Troublemaker",
                "type": "quiz",
                "question": "The discovery of Eris in 2005 helped cause Pluto's reclassification. Why?",
                "options": [
                    "Eris crashed into Pluto",
                    "Eris is more massive than Pluto, raising the question of what counts as a planet",
                    "Eris blocked Pluto's orbit",
                    "Eris is a star, not a planet",
                ],
                "answer": "b",
                "hints": [
                    "If Pluto is a planet, then what about this new object that's even more massive?",
                    "Scientists had to decide: either add more planets or change the definition.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Eris is about 27% more massive than Pluto and orbits even farther from the Sun. Its discovery forced astronomers to ask: if Pluto is a planet, shouldn't Eris be one too? Rather than keep adding planets, the International Astronomical Union created the 'dwarf planet' category in 2006. Eris is named after the Greek goddess of discord — fitting!",
                "is_boss": False,
                "flavor": "Puck chuckles. 'One little icy world caused a BIG argument among scientists!'",
            },
            {
                "id": "makemake_haumea",
                "title": "The Egg and the Red World",
                "type": "quiz",
                "question": "Dwarf planet Haumea has a very unusual shape. What does it look like?",
                "options": [
                    "A perfect sphere",
                    "A cube",
                    "An elongated egg or rugby ball",
                    "A flat disc",
                ],
                "answer": "c",
                "hints": [
                    "Haumea spins extremely fast — completing a rotation in just 4 hours.",
                    "Spinning very fast stretches an object at the middle.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Haumea rotates in just 3.9 hours — faster than any other large object in the solar system! This rapid spin stretches it into an egg or rugby ball shape. Haumea also has a ring and two small moons. Meanwhile, Makemake is one of the brightest objects in the Kuiper Belt and has a reddish-brown surface covered in frozen methane.",
                "is_boss": False,
                "flavor": "An egg-shaped world tumbles through the darkness, spinning so fast it's a blur.",
            },
            {
                "id": "kuiper_belt",
                "title": "The Kuiper Belt",
                "type": "quiz",
                "question": "The Kuiper Belt is a vast region beyond Neptune. What is it most similar to?",
                "options": [
                    "The asteroid belt, but much larger and made of icy objects",
                    "A ring system like Saturn's",
                    "A cloud of hot gas",
                    "A solid wall of rock",
                ],
                "answer": "a",
                "hints": [
                    "Think of the asteroid belt between Mars and Jupiter, but scaled up enormously.",
                    "Instead of rocky asteroids, the Kuiper Belt is full of icy bodies.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "The Kuiper Belt extends from Neptune's orbit (30 AU) to about 50 AU from the Sun. It contains hundreds of thousands of icy objects left over from the formation of the solar system. It's 20 times as wide and 20-200 times as massive as the asteroid belt! Pluto, Eris, Makemake, and Haumea all live here.",
                "is_boss": True,
                "flavor": "The telescope pulls back to show a glittering band of ice beyond Neptune. 'A whole frontier!' Puck breathes.",
            },
        ],
    },

    # ── Zone 7: Space Missions ───────────────────────────────────────
    "space_missions": {
        "id": "space_missions",
        "name": "Humanity's Greatest Voyages",
        "description": "From Voyager to James Webb — the missions that revealed the cosmos",
        "level_required": 13,
        "challenges": [
            {
                "id": "voyager_golden_record",
                "title": "Voyager's Golden Record",
                "type": "quiz",
                "question": "Both Voyager 1 and Voyager 2 carry a Golden Record. What is on it?",
                "options": [
                    "A map showing how to get back to Earth",
                    "Sounds and images from Earth — music, greetings, and pictures of life",
                    "Instructions for building a spaceship",
                    "A recording of the President of the United States",
                ],
                "answer": "b",
                "hints": [
                    "It's a message to anyone — or anything — that might find the spacecraft someday.",
                    "It includes greetings in 55 languages, music from around the world, and photos of Earth.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The Voyager Golden Records carry sounds and images of Earth: greetings in 55 languages, music from Bach to Chuck Berry, sounds of nature, and 116 images. Voyager 1, launched in 1977, is now the farthest human-made object from Earth — over 24 billion km away and still sending data!",
                "is_boss": False,
                "flavor": "Puck holds up a tiny golden disc. 'A message in a bottle, thrown into an ocean of stars.'",
            },
            {
                "id": "voyager_discoveries",
                "title": "What Voyager Found",
                "type": "quiz",
                "question": "The Voyager missions made incredible discoveries at the outer planets. Which of these did Voyager discover?",
                "options": [
                    "Water on Mars",
                    "Active volcanoes on Jupiter's moon Io",
                    "The Great Red Spot on Jupiter",
                    "Rings around Earth",
                ],
                "answer": "b",
                "hints": [
                    "Voyager visited Jupiter and Saturn (and Voyager 2 continued to Uranus and Neptune).",
                    "One of the most stunning discoveries was finding erupting volcanoes on a moon.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Voyager 1 discovered active volcanoes on Io in 1979 — the first time volcanic activity was found beyond Earth! Voyager 2 is the only spacecraft to have visited all four giant planets: Jupiter, Saturn, Uranus, and Neptune. Together, they discovered new moons, rings, and features that transformed our understanding of the outer solar system.",
                "is_boss": False,
                "flavor": "Two tiny spacecraft arc through the darkness past giant planets, each one revealing new wonders.",
            },
            {
                "id": "hubble_telescope",
                "title": "Hubble: The Eye in Space",
                "type": "quiz",
                "question": "The Hubble Space Telescope orbits Earth and has taken stunning images of the universe. Why was it put in space instead of on the ground?",
                "options": [
                    "To get closer to the stars",
                    "Earth's atmosphere blurs and blocks some light",
                    "There wasn't enough room on Earth",
                    "It needs zero gravity to work",
                ],
                "answer": "b",
                "hints": [
                    "When you look at stars, they seem to twinkle. That twinkling is caused by something...",
                    "Earth's atmosphere bends and distorts light. Above the atmosphere, the view is perfectly clear.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Earth's atmosphere causes starlight to shimmer and blocks certain wavelengths. By orbiting above the atmosphere at 547 km, Hubble gets a perfectly clear view. Since 1990, Hubble has taken over 1.5 million observations and helped us discover that the universe is expanding faster than we thought!",
                "is_boss": False,
                "flavor": "A silver telescope glides silently above the blue curve of Earth, its mirror eye open to the cosmos.",
            },
            {
                "id": "james_webb",
                "title": "James Webb: Seeing the Invisible",
                "type": "quiz",
                "question": "The James Webb Space Telescope (JWST) launched in 2021. What kind of light does it mainly observe?",
                "options": [
                    "Visible light, like our eyes see",
                    "Infrared light — heat radiation that can see through dust",
                    "X-rays, like in a hospital",
                    "Radio waves, like a car radio",
                ],
                "answer": "b",
                "hints": [
                    "JWST needs to be very cold to work because it detects a kind of light related to heat.",
                    "This type of light can pass through cosmic dust clouds that block visible light.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "JWST observes mainly in infrared light, which can penetrate dust clouds and reveal newborn stars, distant galaxies, and the atmospheres of exoplanets. Its gold-coated mirror is 6.5 meters across — over 6 times the light-collecting area of Hubble. It orbits the Sun at a point 1.5 million km from Earth!",
                "is_boss": False,
                "flavor": "A golden honeycomb mirror unfolds in the darkness, 1.5 million kilometres from home.",
            },
            {
                "id": "artemis_program",
                "title": "Artemis: Back to the Moon",
                "type": "quiz",
                "question": "NASA's Artemis program aims to return humans to the Moon. What makes Artemis different from the Apollo missions of the 1960s-70s?",
                "options": [
                    "Artemis will land on the Sun instead",
                    "Artemis plans to build a lasting presence and land the first woman and person of color on the Moon",
                    "Artemis uses sailing ships, not rockets",
                    "Artemis is only sending robots, not people",
                ],
                "answer": "b",
                "hints": [
                    "Apollo went to the Moon six times but never built a permanent base.",
                    "Artemis wants to do something more lasting — and be more inclusive.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Artemis aims to return humans to the Moon and establish a sustainable presence there, including a lunar space station called Gateway. It will land the first woman and first person of color on the Moon. Artemis is also a stepping stone — the technologies developed will help send astronauts to Mars in the future!",
                "is_boss": False,
                "flavor": "A mighty rocket rises from the launchpad. Puck salutes. 'We're going back — and this time, we're staying.'",
            },
            {
                "id": "future_mars_missions",
                "title": "The Journey to Mars",
                "type": "quiz",
                "question": "Sending humans to Mars is one of the biggest challenges in space exploration. About how long would the trip take with current technology?",
                "options": [
                    "About 3 days (like going to the Moon)",
                    "About 2 weeks",
                    "About 7 months",
                    "About 10 years",
                ],
                "answer": "c",
                "hints": [
                    "Mars is much, much farther than the Moon.",
                    "Think in terms of months, not days or years.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "A one-way trip to Mars takes about 7 months with current rockets! Astronauts would face radiation exposure, muscle and bone loss from low gravity, and the challenge of carrying enough food, water, and air. Space agencies around the world, including NASA, ESA, and SpaceX, are working on the technologies to make this journey possible by the 2030s or 2040s.",
                "is_boss": True,
                "flavor": "The Primer shows a red dot growing larger through a spacecraft window. Puck whispers: 'One day — maybe your day.'",
            },
        ],
    },
}
