"""
zones.py — Robotics zones and challenges.

All challenges use "type": "quiz" or "type": "text".
Designed for ages 5-12, guided warmly by Puck.
"""

ZONE_ORDER = [
    "what_is_a_robot",
    "robot_parts",
    "programming_robots",
    "robots_in_the_real_world",
    "future_of_robots",
]

ZONES = {
    "what_is_a_robot": {
        "id": "what_is_a_robot",
        "name": "What Is a Robot?",
        "subtitle": "Meet your first mechanical friend",
        "icon": "🤖",
        "description": "Learn what makes a robot a robot — sensors, actuators, and brains",
        "level_required": 1,
        "challenges": [
            {
                "id": "wir_01",
                "title": "Robot or Not?",
                "type": "quiz",
                "question": "Which of these is the BEST description of a robot?",
                "options": [
                    "A machine that can sense the world and take actions on its own",
                    "Any machine that uses electricity",
                    "A computer that looks like a person",
                    "A toy that makes sounds",
                ],
                "answer": "a",
                "lesson": "A [bold yellow]robot[/bold yellow] is a machine that can sense the world around it, decide what to do, and then act. Not all robots look like people — many look like arms, cars, or even vacuum cleaners!",
                "hints": ["Think about what makes a robot special compared to a toaster.", "Robots can sense AND act."],
                "xp": 25,
            },
            {
                "id": "wir_02",
                "title": "Sensors Everywhere",
                "type": "quiz",
                "question": "What does a sensor do on a robot?",
                "options": [
                    "It helps the robot sense things like light, sound, or distance",
                    "It makes the robot look shiny",
                    "It stores electricity",
                    "It connects the robot to the internet",
                ],
                "answer": "a",
                "lesson": "[bold yellow]Sensors[/bold yellow] are like a robot's eyes, ears, and fingertips. They gather information from the world — like how far away a wall is, how bright a room is, or whether someone is speaking.",
                "hints": ["Think of your own senses — eyes, ears, skin.", "Sensors collect information from the world."],
                "xp": 25,
            },
            {
                "id": "wir_03",
                "title": "What Is an Actuator?",
                "type": "quiz",
                "question": "An actuator is the part of a robot that...",
                "options": [
                    "Thinks about what to do",
                    "Moves or does something — like spinning a wheel or lifting an arm",
                    "Stores information in memory",
                    "Charges the battery",
                ],
                "answer": "b",
                "lesson": "An [bold yellow]actuator[/bold yellow] is anything that lets a robot take action in the real world. Motors, wheels, grippers, speakers — those are all actuators. Sensors take IN information; actuators put OUT action!",
                "hints": ["It's the part that actually moves.", "Think of muscles — actuators are a robot's muscles."],
                "xp": 25,
            },
            {
                "id": "wir_04",
                "title": "Sense, Think, Act",
                "type": "quiz",
                "question": "A robot vacuum bumps into a wall, turns, and drives a different direction. What is the correct order of what happened?",
                "options": [
                    "Act, Sense, Think",
                    "Think, Act, Sense",
                    "Sense, Think, Act",
                    "Act, Act, Act",
                ],
                "answer": "c",
                "lesson": "Robots follow a loop: [bold yellow]Sense → Think → Act[/bold yellow]. First the vacuum sensed the wall (bump sensor), then it decided to turn (think), then it drove a new direction (act). This loop repeats over and over!",
                "hints": ["What happened first — did the robot feel the wall or turn?", "First it senses, then it decides, then it moves."],
                "xp": 25,
            },
            {
                "id": "wir_05",
                "title": "AI vs. Pre-Programmed",
                "type": "quiz",
                "question": "What is the difference between an AI robot and a pre-programmed robot?",
                "options": [
                    "AI robots are bigger",
                    "Pre-programmed robots follow fixed rules; AI robots can learn from experience",
                    "There is no difference",
                    "Pre-programmed robots are newer technology",
                ],
                "answer": "b",
                "lesson": "A [bold yellow]pre-programmed robot[/bold yellow] follows rules written by a human — it always does the same thing in the same situation. An [bold yellow]AI robot[/bold yellow] can learn from data and get better over time, even handling situations it has never seen before!",
                "hints": ["One follows a fixed script. The other learns.", "Think about whether the robot can improve on its own."],
                "xp": 30,
            },
            {
                "id": "wir_06",
                "title": "Robot Examples",
                "type": "quiz",
                "question": "Which of these is a real robot?",
                "options": [
                    "A robot vacuum that cleans your floor",
                    "A toaster that pops bread up when it's done",
                    "A lamp that turns on when you flip a switch",
                    "A regular bicycle",
                ],
                "answer": "a",
                "lesson": "A robot vacuum [bold yellow]senses[/bold yellow] obstacles, [bold yellow]decides[/bold yellow] where to go, and [bold yellow]acts[/bold yellow] by driving and cleaning. A toaster and a lamp follow simple rules but don't sense, think, or adapt — they're just machines, not robots!",
                "hints": ["Which one can sense the world and make decisions?", "A robot needs sensors AND the ability to act."],
                "xp": 25,
            },
            {
                "id": "wir_07",
                "title": "Human vs. Robot Senses",
                "type": "text",
                "question": "Humans have five senses: sight, hearing, touch, taste, and smell. Name one robot sensor and explain which human sense it is most like.",
                "options": [],
                "answer": "camera is like sight or microphone is like hearing",
                "lesson": "Robots use [bold yellow]cameras[/bold yellow] (like eyes), [bold yellow]microphones[/bold yellow] (like ears), [bold yellow]pressure sensors[/bold yellow] (like touch), and even [bold yellow]chemical sensors[/bold yellow] (like smell). They experience the world through technology instead of biology!",
                "hints": ["Think of a camera — which human sense does it copy?", "Microphones are like ears, cameras are like eyes."],
                "xp": 35,
            },
            {
                "id": "wir_08",
                "title": "The Robot Brain",
                "type": "quiz",
                "question": "Where does a robot do its 'thinking' — deciding what to do next?",
                "options": [
                    "In its wheels",
                    "In its computer (processor or controller)",
                    "In its battery",
                    "In its paint job",
                ],
                "answer": "b",
                "lesson": "A robot's [bold yellow]computer[/bold yellow] (also called its processor or controller) is its brain. It takes information from sensors, runs its program, and tells the actuators what to do. No computer, no thinking!",
                "hints": ["Think about what part runs the program.", "It's the electronic brain inside."],
                "xp": 25,
            },
        ],
    },
    "robot_parts": {
        "id": "robot_parts",
        "name": "Robot Parts",
        "subtitle": "Build a robot piece by piece",
        "icon": "🔧",
        "description": "Discover motors, wheels, arms, cameras, and batteries",
        "level_required": 3,
        "challenges": [
            {
                "id": "rp_01",
                "title": "Motors Make Movement",
                "type": "quiz",
                "question": "What does a motor do inside a robot?",
                "options": [
                    "It stores data",
                    "It converts energy into spinning or moving motion",
                    "It takes pictures",
                    "It connects to Wi-Fi",
                ],
                "answer": "b",
                "lesson": "A [bold yellow]motor[/bold yellow] converts electrical energy into movement — usually spinning. Motors power wheels, arms, propellers, and almost anything that moves on a robot!",
                "hints": ["Think about what makes wheels spin.", "Motors create movement from electricity."],
                "xp": 25,
            },
            {
                "id": "rp_02",
                "title": "Wheels and Tracks",
                "type": "quiz",
                "question": "Why might a robot use tracks (like a tank) instead of wheels?",
                "options": [
                    "Tracks look cooler",
                    "Tracks work better on rough, uneven ground",
                    "Tracks are cheaper than wheels",
                    "Tracks go faster on smooth floors",
                ],
                "answer": "b",
                "lesson": "[bold yellow]Tracks[/bold yellow] spread the robot's weight over a larger area and grip rough terrain better — perfect for mud, sand, or rubble. [bold yellow]Wheels[/bold yellow] are simpler and faster on smooth surfaces. Engineers choose based on where the robot will work!",
                "hints": ["Think about where tanks go — not smooth roads.", "Rough ground needs more grip."],
                "xp": 25,
            },
            {
                "id": "rp_03",
                "title": "Robot Arms",
                "type": "quiz",
                "question": "A robot arm in a factory picks up car parts and welds them together. What TWO things does the arm need?",
                "options": [
                    "A gripper to hold things and a welder to join them",
                    "Legs and a camera",
                    "A speaker and a microphone",
                    "Two batteries and a screen",
                ],
                "answer": "a",
                "lesson": "Robot arms use different [bold yellow]end effectors[/bold yellow] — tools at the tip of the arm. A [bold yellow]gripper[/bold yellow] holds objects. A [bold yellow]welder[/bold yellow] joins metal. Some arms can swap tools depending on the job, just like changing a drill bit!",
                "hints": ["It needs to grab AND join.", "Think about what a human hand and a torch do."],
                "xp": 25,
            },
            {
                "id": "rp_04",
                "title": "Cameras as Eyes",
                "type": "quiz",
                "question": "Why do many robots have cameras?",
                "options": [
                    "To take selfies",
                    "To see and understand the world around them",
                    "To record TV shows",
                    "To light up dark rooms",
                ],
                "answer": "b",
                "lesson": "Cameras give robots [bold yellow]vision[/bold yellow]. With computer vision software, a robot can recognize faces, read signs, spot obstacles, or find objects. Cameras are one of the most important sensors a robot can have!",
                "hints": ["Think about why YOU have eyes.", "Robots use cameras to see and understand."],
                "xp": 25,
            },
            {
                "id": "rp_05",
                "title": "Battery Power",
                "type": "quiz",
                "question": "A mobile robot runs on a battery. What happens when the battery gets low?",
                "options": [
                    "The robot gets angry",
                    "The robot slows down and eventually stops working",
                    "The robot gets smarter",
                    "Nothing — batteries last forever",
                ],
                "answer": "b",
                "lesson": "[bold yellow]Batteries[/bold yellow] store the energy a robot needs to move, think, and sense. When the battery runs low, the robot loses power — just like your phone. Some robots can even drive themselves back to a charger!",
                "hints": ["Think about what happens to your phone when its battery dies.", "No energy means no action."],
                "xp": 25,
            },
            {
                "id": "rp_06",
                "title": "Name That Part",
                "type": "text",
                "question": "A robot needs to pick up a glass of water without breaking it. What robot part would help it grip gently? Describe what kind of gripper you would design.",
                "options": [],
                "answer": "soft gripper or pressure-sensitive gripper",
                "lesson": "Engineers design [bold yellow]soft grippers[/bold yellow] with rubber fingers or air-filled pads that can hold delicate objects without crushing them. [bold yellow]Pressure sensors[/bold yellow] tell the gripper how hard it's squeezing — just like your hand knows not to crush an egg!",
                "hints": ["Think about how gently you hold a glass.", "A soft, squishy gripper with pressure feedback."],
                "xp": 35,
            },
            {
                "id": "rp_07",
                "title": "Degrees of Freedom",
                "type": "quiz",
                "question": "A robot arm that can move up/down, left/right, and rotate has 3 'degrees of freedom.' What does that mean?",
                "options": [
                    "It can move in 3 different ways",
                    "It has 3 motors but none of them work",
                    "It costs 3 dollars",
                    "It can only work for 3 minutes",
                ],
                "answer": "a",
                "lesson": "[bold yellow]Degrees of freedom[/bold yellow] means the number of independent ways a robot can move. Your arm has 7 degrees of freedom (shoulder, elbow, wrist). More degrees of freedom = more flexible movement!",
                "hints": ["Think of each direction as one freedom.", "Up/down is one, left/right is two, rotate is three."],
                "xp": 30,
            },
            {
                "id": "rp_08",
                "title": "Putting It All Together",
                "type": "quiz",
                "question": "If you were building a robot to explore a dark cave, which combination of parts would be MOST useful?",
                "options": [
                    "Tracks, a flashlight, a camera, and a distance sensor",
                    "Wheels, a speaker, and a screen",
                    "Just a really big battery",
                    "An arm with a paintbrush",
                ],
                "answer": "a",
                "lesson": "A cave-exploring robot needs [bold yellow]tracks[/bold yellow] for rough terrain, a [bold yellow]light[/bold yellow] because it's dark, a [bold yellow]camera[/bold yellow] to see, and a [bold yellow]distance sensor[/bold yellow] to avoid crashing into walls. Great engineers pick parts that match the mission!",
                "hints": ["Caves are dark and rocky — what do you need?", "You need to see, move on rough ground, and avoid obstacles."],
                "xp": 30,
            },
        ],
    },
    "programming_robots": {
        "id": "programming_robots",
        "name": "Programming Robots",
        "subtitle": "Give your robot a brain",
        "icon": "💻",
        "description": "Learn how we write instructions for robots — commands, loops, and sensor logic",
        "level_required": 5,
        "challenges": [
            {
                "id": "pr_01",
                "title": "Step-by-Step",
                "type": "quiz",
                "question": "You want a robot to walk forward, pick up a ball, and come back. What kind of instructions do you need to give it?",
                "options": [
                    "Just say 'get the ball' and it figures it out",
                    "Clear step-by-step instructions: move forward, lower arm, grip ball, turn around, move forward",
                    "One instruction: 'do everything'",
                    "No instructions — robots know what to do",
                ],
                "answer": "b",
                "lesson": "Robots need [bold yellow]precise, step-by-step instructions[/bold yellow]. They can't guess what you mean! Every action — move, turn, grip, release — must be spelled out in order. That's what programming is: writing those steps clearly.",
                "hints": ["Think about giving directions to someone who has never been to your house.", "Be specific and go step by step."],
                "xp": 25,
            },
            {
                "id": "pr_02",
                "title": "Loops for Robots",
                "type": "quiz",
                "question": "A robot needs to check its sensors 100 times every second. Should the programmer write 'check sensor' 100 times?",
                "options": [
                    "Yes — write it out 100 times",
                    "No — use a loop that repeats 'check sensor' 100 times per second",
                    "No — just check once and hope for the best",
                    "Yes — but use really small handwriting",
                ],
                "answer": "b",
                "lesson": "A [bold yellow]loop[/bold yellow] repeats instructions without writing them again and again. Robots use loops constantly — checking sensors, adjusting motors, and updating decisions many times per second!",
                "hints": ["Would you write the same sentence in an essay 100 times?", "Loops repeat actions automatically."],
                "xp": 25,
            },
            {
                "id": "pr_03",
                "title": "If This, Then That",
                "type": "quiz",
                "question": "A robot is programmed: 'IF distance sensor reads less than 30cm, THEN stop.' What will it do when it's 20cm from a wall?",
                "options": [
                    "Keep driving forward",
                    "Stop",
                    "Turn off completely",
                    "Spin in a circle",
                ],
                "answer": "b",
                "lesson": "The robot checks: is 20cm less than 30cm? Yes! So it follows the THEN instruction and [bold yellow]stops[/bold yellow]. This is called a [bold yellow]conditional[/bold yellow] — the robot does different things depending on what its sensors say.",
                "hints": ["Is 20 less than 30?", "If the condition is true, it follows the THEN instruction."],
                "xp": 25,
            },
            {
                "id": "pr_04",
                "title": "Sensors Trigger Actions",
                "type": "quiz",
                "question": "A robot's light sensor detects darkness. Its program says: 'IF dark, THEN turn on headlights.' What connects the sensor to the action?",
                "options": [
                    "Magic",
                    "The program — it reads the sensor and decides what to do",
                    "A wire that goes directly from the sensor to the lights",
                    "The robot asks a human what to do",
                ],
                "answer": "b",
                "lesson": "The [bold yellow]program[/bold yellow] is the bridge between sensors and actions. It reads sensor data, makes decisions using conditionals and logic, and sends commands to actuators. Without a program, sensors and motors are just disconnected parts!",
                "hints": ["Something reads the sensor and decides what happens.", "The program connects sensing to acting."],
                "xp": 25,
            },
            {
                "id": "pr_05",
                "title": "Sequence Matters",
                "type": "quiz",
                "question": "A robot arm needs to: (1) move above a cup, (2) lower down, (3) grip the cup, (4) lift up. What happens if you swap steps 3 and 4?",
                "options": [
                    "Nothing — it works the same",
                    "The arm lifts up before gripping, so it rises without the cup",
                    "The cup flies across the room",
                    "The robot shuts down",
                ],
                "answer": "b",
                "lesson": "[bold yellow]Sequence matters[/bold yellow] in programming! If the robot lifts before gripping, it goes up without the cup. Getting steps in the right order is one of the most important parts of writing good robot programs.",
                "hints": ["Think about what happens if you lift your hand before grabbing something.", "Order matters!"],
                "xp": 25,
            },
            {
                "id": "pr_06",
                "title": "Fixing a Bug",
                "type": "text",
                "question": "A robot is supposed to stop at a red line on the floor, but it keeps driving right over it. The program says: 'IF color sensor sees BLUE, THEN stop.' What's the bug, and how would you fix it?",
                "options": [],
                "answer": "the program checks for blue instead of red",
                "lesson": "The bug is that the program checks for [bold yellow]blue[/bold yellow] instead of [bold yellow]red[/bold yellow]! Fixing it is simple: change BLUE to RED. This is a classic [bold yellow]logic error[/bold yellow] — the program runs fine, but the instructions are wrong.",
                "hints": ["Look at the color in the IF statement.", "What color is the line? What color does the program look for?"],
                "xp": 35,
            },
            {
                "id": "pr_07",
                "title": "While Loops",
                "type": "quiz",
                "question": "A program says: 'WHILE battery is above 10%, KEEP driving.' When will the robot stop?",
                "options": [
                    "When the battery drops to 10% or below",
                    "Never — it drives forever",
                    "After exactly 10 minutes",
                    "When someone presses a button",
                ],
                "answer": "a",
                "lesson": "A [bold yellow]WHILE loop[/bold yellow] keeps repeating as long as a condition is true. When the battery drops to 10%, the condition becomes false, and the loop stops. WHILE loops are how robots keep doing something until a condition changes!",
                "hints": ["When does 'above 10%' become false?", "It stops when the condition is no longer true."],
                "xp": 30,
            },
            {
                "id": "pr_08",
                "title": "Plan a Robot Program",
                "type": "text",
                "question": "Design a simple program for a robot that waters plants. It should: find a plant, check if the soil is dry, and water it if needed. Write your steps in order.",
                "options": [],
                "answer": "move to plant then check soil sensor then if dry water then move to next plant",
                "lesson": "A plant-watering robot program might be: [bold yellow]1) Move to next plant. 2) Check soil moisture sensor. 3) IF soil is dry, THEN turn on water for 5 seconds. 4) Move to next plant. 5) Repeat![/bold yellow] This uses movement, sensors, conditionals, and a loop — real robot programming!",
                "hints": ["Start by finding the plant, then check if it needs water.", "Use IF dry THEN water, and repeat for each plant."],
                "xp": 40,
            },
        ],
    },
    "robots_in_the_real_world": {
        "id": "robots_in_the_real_world",
        "name": "Robots in the Real World",
        "subtitle": "Robots are already all around us",
        "icon": "🌍",
        "description": "Explore how robots help in factories, hospitals, space, and the ocean",
        "level_required": 7,
        "challenges": [
            {
                "id": "rw_01",
                "title": "Factory Robots",
                "type": "quiz",
                "question": "In a car factory, robot arms do the same task thousands of times a day. Why are robots BETTER than humans at this?",
                "options": [
                    "Robots are smarter than humans",
                    "Robots don't get tired, bored, or make mistakes from fatigue",
                    "Robots don't need electricity",
                    "Robots build cars faster because they skip steps",
                ],
                "answer": "b",
                "lesson": "Factory robots excel at [bold yellow]repetitive tasks[/bold yellow] because they never get tired, never get bored, and do the exact same motion perfectly every time. Humans are still better at creative problem-solving — but for repeating the same weld 10,000 times, robots win!",
                "hints": ["What happens when you do the same boring task for 8 hours?", "Robots don't feel fatigue."],
                "xp": 25,
            },
            {
                "id": "rw_02",
                "title": "Surgical Robots",
                "type": "quiz",
                "question": "In some hospitals, doctors control robot arms to perform surgery. Why is a robot arm sometimes better for surgery than a human hand alone?",
                "options": [
                    "Robot arms can make extremely tiny, precise movements without shaking",
                    "Robot arms are cheaper than paying a doctor",
                    "Robot arms don't need a doctor at all",
                    "Robot arms can think better than doctors",
                ],
                "answer": "a",
                "lesson": "[bold yellow]Surgical robots[/bold yellow] can make cuts smaller than a millimeter with zero tremor. A human hand naturally shakes a tiny bit, but a robot arm holds perfectly still. The doctor still controls everything — the robot just makes their hands more precise!",
                "hints": ["Hold your hand out — does it shake even a little?", "Robots can be more precise and steady."],
                "xp": 25,
            },
            {
                "id": "rw_03",
                "title": "Robots in Space",
                "type": "quiz",
                "question": "Why do we send robots to Mars instead of humans (for now)?",
                "options": [
                    "Mars has a shop where robots can buy snacks",
                    "Robots don't need air, food, or water, and can survive harsh conditions",
                    "Humans are not allowed in space",
                    "Robots are lighter than feathers",
                ],
                "answer": "b",
                "lesson": "Mars rovers like [bold yellow]Curiosity[/bold yellow] and [bold yellow]Perseverance[/bold yellow] survive without air, food, or water. They handle extreme cold, radiation, and dust storms that would be very dangerous for humans. Robots are our scouts — exploring where we can't yet go!",
                "hints": ["What do humans need that robots don't?", "Air, food, water, warmth — robots skip all of that."],
                "xp": 25,
            },
            {
                "id": "rw_04",
                "title": "Ocean Explorers",
                "type": "quiz",
                "question": "Underwater robots (called ROVs) explore the deep ocean. Why can't humans just dive that deep themselves?",
                "options": [
                    "The water is too cold for swimming trunks",
                    "The pressure at great depths would crush a human, but robots can be built to withstand it",
                    "Humans can't hold their breath that long",
                    "There are too many fish in the way",
                ],
                "answer": "b",
                "lesson": "At the bottom of the ocean, the [bold yellow]pressure[/bold yellow] is enormous — enough to crush a submarine. [bold yellow]ROVs[/bold yellow] (Remotely Operated Vehicles) are built with strong materials to survive these extremes. They've found shipwrecks, new species, and underwater volcanoes!",
                "hints": ["What happens to things under very heavy pressure?", "Deep water pressure is extreme — robots are built tough."],
                "xp": 25,
            },
            {
                "id": "rw_05",
                "title": "Warehouse Robots",
                "type": "quiz",
                "question": "In a big warehouse, robots zip around carrying shelves to human workers. How do they avoid crashing into each other?",
                "options": [
                    "They don't — they crash all the time",
                    "They all follow a central computer system that coordinates their paths",
                    "They honk tiny horns",
                    "Each robot has its own room",
                ],
                "answer": "b",
                "lesson": "Warehouse robots use a [bold yellow]central coordination system[/bold yellow] — a computer that knows where every robot is and plans paths so they never collide. It's like air traffic control, but for robots on the ground!",
                "hints": ["Something keeps track of ALL the robots.", "Think of an air traffic controller, but for robots."],
                "xp": 25,
            },
            {
                "id": "rw_06",
                "title": "Search and Rescue",
                "type": "text",
                "question": "After an earthquake, buildings collapse and it's dangerous for humans to search the rubble. How could a small robot help find people who are trapped? What sensors would it need?",
                "options": [],
                "answer": "heat sensor or camera or microphone to detect survivors in rubble",
                "lesson": "Rescue robots can crawl through tiny gaps in rubble carrying [bold yellow]heat sensors[/bold yellow] (to detect body warmth), [bold yellow]cameras[/bold yellow] (to see in the dark), and [bold yellow]microphones[/bold yellow] (to hear people calling for help). They go where it's too dangerous for human rescuers!",
                "hints": ["How would you find a person buried under rocks?", "Heat, sound, and sight — those are clues."],
                "xp": 35,
            },
            {
                "id": "rw_07",
                "title": "Medical Delivery Robots",
                "type": "quiz",
                "question": "Some hospitals use robots to deliver medicine to patient rooms. What is ONE big advantage of using a robot instead of a human for this?",
                "options": [
                    "Robots tell better jokes to patients",
                    "Robots can work 24/7 without breaks and reduce the spread of germs",
                    "Robots are better at reading prescriptions",
                    "Robots can heal patients with a touch",
                ],
                "answer": "b",
                "lesson": "Hospital delivery robots work [bold yellow]around the clock[/bold yellow] without breaks and reduce [bold yellow]germ spread[/bold yellow] because they can be disinfected easily. This frees up nurses and doctors to spend more time actually caring for patients!",
                "hints": ["Can a robot get tired? Can it spread germs like a human?", "Robots work non-stop and are easy to clean."],
                "xp": 25,
            },
            {
                "id": "rw_08",
                "title": "Robots Helping Farmers",
                "type": "quiz",
                "question": "Farming robots can plant seeds, pull weeds, and pick fruit. Why is this helpful for farmers?",
                "options": [
                    "Farmers don't like being outside",
                    "Robots can work faster, cover more land, and reduce the need for harmful chemicals",
                    "Robots make plants grow faster just by being near them",
                    "Robots eat the weeds",
                ],
                "answer": "b",
                "lesson": "[bold yellow]Agricultural robots[/bold yellow] can target individual weeds (instead of spraying a whole field), pick ripe fruit without bruising it, and work day and night. This helps farmers grow more food while using fewer chemicals — better for people AND the planet!",
                "hints": ["Think about the biggest challenges of farming.", "Speed, precision, and less chemicals."],
                "xp": 30,
            },
        ],
    },
    "future_of_robots": {
        "id": "future_of_robots",
        "name": "Future of Robots",
        "subtitle": "What's next for robots and us?",
        "icon": "🚀",
        "description": "Self-driving cars, drones, and the big ethical questions",
        "level_required": 9,
        "challenges": [
            {
                "id": "fr_01",
                "title": "Self-Driving Cars",
                "type": "quiz",
                "question": "Self-driving cars use cameras, radar, and AI to drive without a human. What is the HARDEST part for them?",
                "options": [
                    "Going in a straight line on a highway",
                    "Dealing with unexpected situations — like a dog running into the road",
                    "Choosing a radio station",
                    "Filling up with fuel",
                ],
                "answer": "b",
                "lesson": "Highways are fairly predictable, but [bold yellow]unexpected events[/bold yellow] — a child chasing a ball, construction, or an animal — are incredibly hard for AI. Humans use common sense and experience to react; self-driving cars are still learning how to handle the unpredictable!",
                "hints": ["What would surprise you while driving?", "The hard part is things that don't follow normal rules."],
                "xp": 25,
            },
            {
                "id": "fr_02",
                "title": "Delivery Drones",
                "type": "quiz",
                "question": "Companies want to use flying drones to deliver packages. What is ONE challenge they need to solve?",
                "options": [
                    "Drones are too heavy to carry anything",
                    "Safely flying near buildings, trees, birds, and other drones without crashing",
                    "Drones can only fly at night",
                    "Packages are too small for drones",
                ],
                "answer": "b",
                "lesson": "Delivery drones must navigate [bold yellow]crowded airspace[/bold yellow] — avoiding buildings, power lines, birds, planes, and other drones. They also need to handle wind, rain, and landing safely. The technology is improving fast, but safety comes first!",
                "hints": ["What obstacles exist between a warehouse and your front door?", "Think about everything in the sky and on the ground."],
                "xp": 25,
            },
            {
                "id": "fr_03",
                "title": "Robot Ethics — Jobs",
                "type": "quiz",
                "question": "If robots can do many jobs that humans currently do, what is one important question society needs to think about?",
                "options": [
                    "Should we paint robots fun colors?",
                    "How do we make sure people can still earn a living and find meaningful work?",
                    "Should robots pay taxes on their snacks?",
                    "Will robots want weekends off?",
                ],
                "answer": "b",
                "lesson": "When robots replace human jobs, [bold yellow]people need new opportunities[/bold yellow]. Society must plan for retraining, new kinds of jobs, and making sure the benefits of robots are shared fairly. Technology should help everyone, not just a few!",
                "hints": ["If a robot does your job, what do you do?", "Think about people who lose their jobs to automation."],
                "xp": 30,
            },
            {
                "id": "fr_04",
                "title": "Robot Ethics — Decisions",
                "type": "text",
                "question": "A self-driving car's brakes fail. It can either swerve left (hitting one person) or keep going straight (hitting three people). Should a robot be making this decision? Why or why not?",
                "options": [],
                "answer": "this is a hard ethical question with no easy answer",
                "lesson": "This is called the [bold yellow]trolley problem[/bold yellow] and it has no easy answer. Some people think robots should never make life-or-death decisions. Others say robots might be more consistent than panicking humans. This is why [bold yellow]robot ethics[/bold yellow] — thinking carefully about right and wrong in technology — is so important!",
                "hints": ["There's no single right answer — think about why it's hard.", "Should a machine decide who gets hurt? Why or why not?"],
                "xp": 40,
            },
            {
                "id": "fr_05",
                "title": "Robot Companions",
                "type": "quiz",
                "question": "Some robots are designed to keep elderly people company — talking, playing music, and reminding them to take medicine. Is this a good idea?",
                "options": [
                    "No — robots should only work in factories",
                    "Yes, but they should help alongside human caregivers, not replace them completely",
                    "Yes — robots are better than humans at everything",
                    "No — robots are too scary for older people",
                ],
                "answer": "b",
                "lesson": "[bold yellow]Companion robots[/bold yellow] can help with reminders, entertainment, and monitoring health — but human connection is irreplaceable. The best approach is robots and humans [bold yellow]working together[/bold yellow], where robots handle routine tasks and humans provide warmth and understanding!",
                "hints": ["Can a robot truly replace a friend?", "Think about what robots are good at AND what only humans can give."],
                "xp": 30,
            },
            {
                "id": "fr_06",
                "title": "Swarm Robots",
                "type": "quiz",
                "question": "Scientists are building 'swarm robots' — hundreds of tiny robots that work together like ants. Why might a swarm be better than one big robot?",
                "options": [
                    "Tiny robots are cuter",
                    "If one breaks, the others keep going, and they can cover more area at once",
                    "Big robots cost exactly the same as small ones",
                    "Swarms are louder and scare away predators",
                ],
                "answer": "b",
                "lesson": "[bold yellow]Swarm robots[/bold yellow] are resilient — if one breaks, the rest keep working. They can search a large area simultaneously, build structures together, or monitor environments. It's inspired by how ants, bees, and fish work as teams in nature!",
                "hints": ["What happens to an ant colony if one ant is lost?", "Many small robots = more coverage and backup."],
                "xp": 30,
            },
            {
                "id": "fr_07",
                "title": "Robots and Privacy",
                "type": "quiz",
                "question": "A home robot with cameras and microphones helps around the house. What is ONE privacy concern people should think about?",
                "options": [
                    "The robot might rearrange the furniture",
                    "The robot could be recording conversations or images that get shared without your knowledge",
                    "The robot will judge your taste in music",
                    "The robot might eat your food",
                ],
                "answer": "b",
                "lesson": "Robots with cameras and microphones collect [bold yellow]private data[/bold yellow] — your face, your voice, your home layout. If that data is stored, hacked, or shared, it's a privacy problem. It's important to know what a robot records, where the data goes, and who can access it!",
                "hints": ["What could a robot with a camera see in your home?", "Think about who else might see what the robot records."],
                "xp": 30,
            },
            {
                "id": "fr_08",
                "title": "Your Dream Robot",
                "type": "text",
                "question": "If you could build any robot to help the world, what would it do? Describe what sensors it would have, how it would move, and what problem it would solve.",
                "options": [],
                "answer": "any creative robot design that includes sensors movement and a purpose",
                "lesson": "The best robots start with a [bold yellow]problem worth solving[/bold yellow]. Then engineers ask: what sensors does it need? How should it move? What should its program do? Whether it cleans the ocean, helps disabled people, or plants trees — [bold yellow]you[/bold yellow] could design the next great robot!",
                "hints": ["Think of a problem in the world you care about.", "What would your robot sense, decide, and do?"],
                "xp": 40,
            },
        ],
    },
}
