"""
zones.py — Earth Science zones and challenges.

All challenges use "type": "quiz" or "type": "text" with multiple-choice options.
Designed for ages 5-12, guided warmly by Puck.
"""

ZONE_ORDER = [
    "rocks_and_minerals",
    "volcanoes_and_earthquakes",
    "water_cycle",
    "soil_and_erosion",
    "natural_resources",
]

ZONES = {
    "rocks_and_minerals": {
        "id": "rocks_and_minerals",
        "name": "The Rock Collection",
        "subtitle": "What are rocks made of, and how do they form?",
        "icon": "\U0001faa8",
        "description": "Discover the three types of rocks and the minerals hidden inside them",
        "level_required": 1,
        "challenges": [
            {
                "id": "rm_01",
                "title": "Three Kinds of Rock",
                "type": "quiz",
                "question": "What are the three main types of rock?",
                "lesson": "All rocks on Earth are either [bold yellow]igneous[/bold yellow] (made from cooled lava or magma), [bold yellow]sedimentary[/bold yellow] (made from layers of sand and mud pressed together), or [bold yellow]metamorphic[/bold yellow] (changed by heat and pressure deep underground).",
                "options": ["Big, medium, and small", "Igneous, sedimentary, and metamorphic", "Red, grey, and brown", "Hard, soft, and crumbly"],
                "answer": "b",
                "hints": ["Scientists sort rocks by how they were made, not how they look.", "One comes from volcanoes, one from layers, one from heat and pressure."],
                "xp": 30,
            },
            {
                "id": "rm_02",
                "title": "Born from Fire",
                "type": "quiz",
                "question": "Igneous rock forms when what cools down and hardens?",
                "lesson": "[bold yellow]Igneous[/bold yellow] means 'made by fire.' When hot melted rock (magma or lava) cools down, it hardens into igneous rock. Granite and obsidian are both igneous!",
                "options": ["Water", "Sand", "Melted rock (magma or lava)", "Ice"],
                "answer": "c",
                "hints": ["Think about volcanoes and what comes out of them.", "The word 'igneous' comes from the Latin word for fire!"],
                "xp": 30,
            },
            {
                "id": "rm_03",
                "title": "Layer by Layer",
                "type": "quiz",
                "question": "Sedimentary rock forms when tiny pieces of sand, mud, and shells get ___.",
                "lesson": "Over millions of years, layers of sand, mud, and tiny shells pile up. The weight presses them together until they become [bold yellow]sedimentary rock[/bold yellow]. Sandstone and limestone are examples!",
                "options": ["Frozen", "Melted", "Pressed together over a long time", "Shaken up"],
                "answer": "c",
                "hints": ["Imagine stacking pancakes and pressing down — layer after layer.", "Sediment means tiny bits that settle to the bottom."],
                "xp": 30,
            },
            {
                "id": "rm_04",
                "title": "Changed by Pressure",
                "type": "quiz",
                "question": "What does 'metamorphic' mean?",
                "lesson": "[bold yellow]Metamorphic[/bold yellow] means 'changed in form.' When any rock gets buried deep underground and squeezed by enormous heat and pressure, it transforms into something new — like limestone turning into marble!",
                "options": ["Broken apart", "Changed in form", "Very old", "Made of metal"],
                "answer": "b",
                "hints": ["Think of a butterfly going through metamorphosis — it changes form!", "Heat + pressure deep underground = a rock that transforms."],
                "xp": 35,
            },
            {
                "id": "rm_05",
                "title": "What Is a Mineral?",
                "type": "quiz",
                "question": "What is a mineral?",
                "lesson": "A mineral is a [bold yellow]natural, non-living solid[/bold yellow] with a specific crystal shape. Rocks are made of one or more minerals. Quartz, feldspar, and mica are common minerals you can find almost anywhere!",
                "options": ["A type of plant", "A natural non-living solid found in rocks", "A kind of fossil", "A liquid inside the Earth"],
                "answer": "b",
                "hints": ["Minerals are the building blocks of rocks.", "They're natural, solid, and have a crystal structure."],
                "xp": 30,
            },
            {
                "id": "rm_06",
                "title": "Sparkle and Shine",
                "type": "text",
                "question": "Diamonds, rubies, and emeralds are all examples of what? (one word)",
                "answer": "gems",
                "lesson": "[bold yellow]Gems[/bold yellow] (or gemstones) are minerals that are especially beautiful, rare, and hard. A diamond is the hardest natural substance on Earth — it can scratch anything!",
                "hints": ["They sparkle, they're rare, and people wear them in jewelry.", "Another word is 'gemstones.'"],
                "xp": 35,
            },
            {
                "id": "rm_07",
                "title": "The Hardness Test",
                "type": "quiz",
                "question": "Which mineral is the hardest natural substance on Earth?",
                "lesson": "Scientists use the [bold yellow]Mohs hardness scale[/bold yellow] from 1 to 10. Talc is the softest (1). Diamond is the hardest (10). If a mineral can scratch another, it's harder!",
                "options": ["Gold", "Talc", "Diamond", "Quartz"],
                "answer": "c",
                "hints": ["It's used to cut glass and other hard materials.", "It scores a perfect 10 on the hardness scale!"],
                "xp": 35,
            },
            {
                "id": "rm_boss",
                "title": "The Rock Cycle",
                "type": "quiz",
                "question": "In the rock cycle, any type of rock can become any other type. What keeps the rock cycle going?",
                "lesson": "The [bold yellow]rock cycle[/bold yellow] never stops! Heat from inside the Earth melts rock into magma. Weathering breaks rock into sediment. Pressure transforms rock underground. Over millions of years, rocks keep changing from one type to another — round and round forever!",
                "options": ["Gravity alone", "Heat, pressure, and weathering working together", "Rain only", "People breaking rocks"],
                "answer": "b",
                "hints": ["It's not just one force — several forces work together.", "Volcanoes provide heat. Rain provides weathering. Deep burial provides pressure."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "volcanoes_and_earthquakes": {
        "id": "volcanoes_and_earthquakes",
        "name": "The Shaking Earth",
        "subtitle": "Why does the ground shake and mountains explode?",
        "icon": "\U0001f30b",
        "description": "Explore volcanoes, earthquakes, and the moving plates beneath our feet",
        "level_required": 2,
        "challenges": [
            {
                "id": "ve_01",
                "title": "Puzzle Pieces of Earth",
                "type": "quiz",
                "question": "The Earth's outer layer is broken into giant pieces that slowly move. What are these pieces called?",
                "lesson": "The Earth's crust is cracked into huge slabs called [bold yellow]tectonic plates[/bold yellow]. They float on hot, soft rock below and move very slowly — just a few centimeters per year, about as fast as your fingernails grow!",
                "options": ["Continents", "Tectonic plates", "Rock layers", "Fault lines"],
                "answer": "b",
                "hints": ["Think of the Earth's surface as a giant cracked eggshell.", "The word 'tectonic' comes from a Greek word meaning 'to build.'"],
                "xp": 30,
            },
            {
                "id": "ve_02",
                "title": "When Plates Collide",
                "type": "quiz",
                "question": "What can happen when two tectonic plates push into each other?",
                "lesson": "When plates collide, enormous forces crumple the ground upward, creating [bold yellow]mountains[/bold yellow]! The Himalayas — the tallest mountains on Earth — were formed when the Indian plate crashed into the Asian plate. This is still happening today!",
                "options": ["Nothing happens", "Mountains can form", "The ocean disappears", "The plates melt"],
                "answer": "b",
                "hints": ["Push two pieces of paper together on a table — what happens?", "The biggest mountain ranges were formed this way."],
                "xp": 30,
            },
            {
                "id": "ve_03",
                "title": "Lava vs. Magma",
                "type": "quiz",
                "question": "What is the difference between magma and lava?",
                "lesson": "It's the same melted rock — the name just changes based on where it is! [bold yellow]Magma[/bold yellow] is underground. Once it erupts and reaches the surface, it's called [bold yellow]lava[/bold yellow].",
                "options": ["Magma is hotter", "Magma is underground; lava is above ground", "They are completely different substances", "Lava is underground; magma is above ground"],
                "answer": "b",
                "hints": ["The difference is all about location — inside or outside the Earth.", "Underground = magma. On the surface = lava."],
                "xp": 30,
            },
            {
                "id": "ve_04",
                "title": "The Ring of Fire",
                "type": "quiz",
                "question": "The Ring of Fire is a zone around the Pacific Ocean known for having many ___.",
                "lesson": "The [bold yellow]Ring of Fire[/bold yellow] is a horseshoe-shaped zone around the Pacific Ocean where about 75% of the world's volcanoes are found and 90% of earthquakes happen. It follows the edges of several tectonic plates!",
                "options": ["Deserts", "Volcanoes and earthquakes", "Tropical islands", "Ice caps"],
                "answer": "b",
                "hints": ["It's named 'fire' for a reason — think eruptions!", "It circles the entire Pacific Ocean."],
                "xp": 35,
            },
            {
                "id": "ve_05",
                "title": "Earthquake Waves",
                "type": "quiz",
                "question": "What causes an earthquake?",
                "lesson": "Earthquakes happen when tectonic plates [bold yellow]suddenly slip or crack[/bold yellow] along a fault line. The energy released travels through the ground as seismic waves — that's what makes the shaking!",
                "options": ["Strong winds", "Tectonic plates suddenly moving along a fault", "Underground rivers", "The moon's gravity"],
                "answer": "b",
                "hints": ["It's connected to those giant puzzle pieces of the Earth's crust.", "When plates that are stuck finally slip, energy is released."],
                "xp": 35,
            },
            {
                "id": "ve_06",
                "title": "Measuring Earthquakes",
                "type": "text",
                "question": "Scientists measure earthquake strength using what scale? (last name of the scientist)",
                "answer": "richter",
                "lesson": "The [bold yellow]Richter scale[/bold yellow] measures how much energy an earthquake releases. Each number is about 30 times more energy than the one before! A magnitude 3 is barely felt, but a magnitude 8 is catastrophic.",
                "hints": ["It's named after Charles ___.", "It rhymes with 'pick-ter.'"],
                "xp": 35,
            },
            {
                "id": "ve_07",
                "title": "Layers of the Earth",
                "type": "quiz",
                "question": "What are the four main layers of the Earth, from outside to inside?",
                "lesson": "The Earth has four layers: the thin [bold yellow]crust[/bold yellow] (where we live), the thick [bold yellow]mantle[/bold yellow] (hot and slowly flowing), the liquid [bold yellow]outer core[/bold yellow], and the solid [bold yellow]inner core[/bold yellow] made mostly of iron — as hot as the surface of the sun!",
                "options": ["Crust, mantle, outer core, inner core", "Soil, rock, water, fire", "Top, middle, bottom, center", "Sand, stone, metal, lava"],
                "answer": "a",
                "hints": ["The thinnest layer is where we live — the crust.", "Think of it like a hard-boiled egg: shell, white, yolk!"],
                "xp": 35,
            },
            {
                "id": "ve_boss",
                "title": "Why Do Volcanoes Erupt?",
                "type": "quiz",
                "question": "Why does a volcano erupt?",
                "lesson": "Deep underground, hot [bold yellow]magma[/bold yellow] is under tremendous pressure. When pressure builds up enough, the magma forces its way through cracks in the crust and erupts as lava, ash, and gas. It's like shaking a soda bottle and popping the cap!",
                "options": ["The mountain gets too hot from the sun", "Pressure from magma underground forces it to the surface", "Earthquakes push lava out", "Rain seeps in and boils"],
                "answer": "b",
                "hints": ["Think about what happens when you shake a bottle of soda.", "Pressure builds up underground until something has to give."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "water_cycle": {
        "id": "water_cycle",
        "name": "The Water Wanderers",
        "subtitle": "Where does water go, and where does it come from?",
        "icon": "\U0001f4a7",
        "description": "Follow water as it travels from sky to ground and back again",
        "level_required": 3,
        "challenges": [
            {
                "id": "wc_01",
                "title": "Round and Round",
                "type": "quiz",
                "question": "The water cycle describes how water moves between ___.",
                "lesson": "The [bold yellow]water cycle[/bold yellow] is the endless journey of water: from oceans and lakes up into the sky as vapor, forming clouds, falling as rain or snow, flowing into rivers, and back to the ocean. The same water has been cycling for billions of years!",
                "options": ["The North and South Poles", "The Earth's surface, the atmosphere, and back", "Underground caves only", "Oceans and rivers only"],
                "answer": "b",
                "hints": ["Water goes up, forms clouds, comes back down, and repeats.", "It moves between the ground and the sky."],
                "xp": 30,
            },
            {
                "id": "wc_02",
                "title": "Disappearing Puddles",
                "type": "quiz",
                "question": "When a puddle dries up on a sunny day, what happened to the water?",
                "lesson": "The water didn't disappear — it [bold yellow]evaporated[/bold yellow]! The sun's heat turned the liquid water into invisible water vapor (gas) that floated up into the air. Evaporation is happening all around you, all the time.",
                "options": ["The ground drank it all", "It turned into invisible water vapor and floated into the air", "The wind blew it away as liquid", "It sank underground"],
                "answer": "b",
                "hints": ["The sun's heat does something to the water — it changes form.", "The water became a gas you can't see."],
                "xp": 30,
            },
            {
                "id": "wc_03",
                "title": "Cloud Makers",
                "type": "quiz",
                "question": "Clouds form when water vapor in the air cools and turns back into tiny water droplets. What is this process called?",
                "lesson": "[bold yellow]Condensation[/bold yellow] is when water vapor (gas) cools down and turns back into tiny liquid water droplets. Billions of these droplets clump together to form clouds. You see condensation on a cold glass of water on a hot day!",
                "options": ["Evaporation", "Condensation", "Precipitation", "Filtration"],
                "answer": "b",
                "hints": ["It's the opposite of evaporation.", "Think of the fog on a cold glass — that's this process!"],
                "xp": 30,
            },
            {
                "id": "wc_04",
                "title": "Falling Water",
                "type": "text",
                "question": "Rain, snow, sleet, and hail are all forms of what? (one word starting with 'p')",
                "answer": "precipitation",
                "lesson": "[bold yellow]Precipitation[/bold yellow] is any water that falls from clouds to the ground — rain, snow, sleet, or hail. It happens when water droplets in clouds get too heavy to stay floating in the air.",
                "hints": ["It starts with 'p' and has six syllables.", "Pre-cip-i-ta-tion."],
                "xp": 35,
            },
            {
                "id": "wc_05",
                "title": "Hidden Water",
                "type": "quiz",
                "question": "What is groundwater?",
                "lesson": "[bold yellow]Groundwater[/bold yellow] is water that soaks into the soil and collects in underground spaces between rocks. It fills wells and feeds springs. About 30% of Earth's fresh water is groundwater — much more than all the rivers and lakes combined!",
                "options": ["Water on the ground's surface", "Water stored underground in soil and rock", "Water in swimming pools", "Frozen water at the poles"],
                "answer": "b",
                "hints": ["It's water that's under the ground — literally!", "When rain soaks into the earth, where does it go?"],
                "xp": 35,
            },
            {
                "id": "wc_06",
                "title": "Salty or Fresh?",
                "type": "quiz",
                "question": "Most of Earth's water is in the oceans. Is ocean water fresh or salty?",
                "lesson": "About [bold yellow]97% of Earth's water is salty[/bold yellow] ocean water. Only 3% is fresh water, and most of that is locked in ice caps and glaciers. Less than 1% of all Earth's water is available for us to drink!",
                "options": ["Fresh", "Salty", "Both equally", "Neither"],
                "answer": "b",
                "hints": ["Have you ever tasted ocean water?", "Oceans contain dissolved salts and minerals."],
                "xp": 30,
            },
            {
                "id": "wc_07",
                "title": "Transpiration Station",
                "type": "quiz",
                "question": "Plants release water vapor through their leaves. What is this process called?",
                "lesson": "[bold yellow]Transpiration[/bold yellow] is when plants release water vapor through tiny holes in their leaves called stomata. A single large tree can release hundreds of liters of water into the air every day — plants are part of the water cycle too!",
                "options": ["Photosynthesis", "Transpiration", "Respiration", "Condensation"],
                "answer": "b",
                "hints": ["It sounds like 'perspiration' — which is sweating. Plants do something similar!", "Trans- means 'across.' The water moves across, from roots to leaves to air."],
                "xp": 35,
            },
            {
                "id": "wc_boss",
                "title": "The Oldest Water",
                "type": "quiz",
                "question": "The water you drank today could be the same water that ___.",
                "lesson": "Water is [bold yellow]never created or destroyed[/bold yellow] — it just keeps cycling. The water molecules on Earth today are the same ones that existed billions of years ago. The water in your glass might once have been in a dinosaur's lake, a medieval well, or an ancient cloud!",
                "options": ["Was made last week at a factory", "Dinosaurs drank millions of years ago", "Fell from space yesterday", "Was created when you turned on the tap"],
                "answer": "b",
                "hints": ["Water doesn't get 'used up' — it recycles endlessly.", "The water cycle has been going for billions of years."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "soil_and_erosion": {
        "id": "soil_and_erosion",
        "name": "The Ground Beneath Us",
        "subtitle": "What's under your feet, and why does it matter?",
        "icon": "\U0001fab4",
        "description": "Dig into soil layers, erosion, composting, and fossils hidden in rock",
        "level_required": 4,
        "challenges": [
            {
                "id": "se_01",
                "title": "What Is Soil?",
                "type": "quiz",
                "question": "Soil is a mixture of ___.",
                "lesson": "Soil isn't just dirt! It's a mixture of [bold yellow]broken-down rock, dead plant and animal material, water, and air[/bold yellow]. It takes hundreds of years to make just one inch of topsoil. Soil is precious!",
                "options": ["Only rocks", "Broken-down rock, dead plants and animals, water, and air", "Sand and water only", "Mud and nothing else"],
                "answer": "b",
                "hints": ["Soil has many ingredients — not just one.", "Living things that decompose become part of soil."],
                "xp": 30,
            },
            {
                "id": "se_02",
                "title": "Layers of Soil",
                "type": "quiz",
                "question": "The dark, nutrient-rich top layer of soil where plants grow best is called ___.",
                "lesson": "Soil has layers called [bold yellow]horizons[/bold yellow]. The top layer is [bold yellow]topsoil[/bold yellow] — dark, rich, and full of nutrients and living things. Below that is subsoil (lighter, with fewer nutrients), then broken rock, then solid bedrock at the bottom.",
                "options": ["Bedrock", "Subsoil", "Topsoil", "Clay"],
                "answer": "c",
                "hints": ["It's literally the top layer of soil — the name gives it away!", "It's where most plant roots live and worms tunnel."],
                "xp": 30,
            },
            {
                "id": "se_03",
                "title": "Nature's Recyclers",
                "type": "quiz",
                "question": "Composting turns food scraps and yard waste into ___.",
                "lesson": "[bold yellow]Composting[/bold yellow] is nature's recycling! Tiny organisms like bacteria, fungi, and worms break down food scraps, leaves, and grass into rich, dark soil called compost. It's like superfood for gardens!",
                "options": ["Plastic", "Rich soil full of nutrients", "Rocks", "Sand"],
                "answer": "b",
                "hints": ["Banana peels and leaves break down into something gardens love.", "Worms and tiny organisms do the hard work of breaking things down."],
                "xp": 30,
            },
            {
                "id": "se_04",
                "title": "Wearing Away",
                "type": "quiz",
                "question": "What is weathering?",
                "lesson": "[bold yellow]Weathering[/bold yellow] is the slow breaking down of rocks by water, wind, ice, and even plant roots. Over time, giant boulders crumble into pebbles, and pebbles crumble into sand. The Grand Canyon was carved by millions of years of weathering!",
                "options": ["Checking the weather forecast", "The slow breaking down of rocks by natural forces", "Painting rocks different colors", "Rocks getting wet in the rain"],
                "answer": "b",
                "hints": ["It's about rocks breaking apart, not the weather report.", "Water, wind, ice, and roots all slowly break rocks down."],
                "xp": 35,
            },
            {
                "id": "se_05",
                "title": "On the Move",
                "type": "quiz",
                "question": "Erosion is the process of ___.",
                "lesson": "[bold yellow]Erosion[/bold yellow] is when weathered rock, soil, and sediment get carried away by water, wind, ice, or gravity. Weathering breaks things down; erosion moves the pieces. Rivers carry soil to the sea. Wind blows sand across deserts.",
                "options": ["Rocks growing bigger", "Broken rock and soil being carried away by water, wind, or ice", "Plants growing in soil", "Underground rivers forming"],
                "answer": "b",
                "hints": ["First things break apart (weathering), then they get moved (this).", "Rivers, wind, and glaciers are all agents of this process."],
                "xp": 35,
            },
            {
                "id": "se_06",
                "title": "Frozen in Stone",
                "type": "quiz",
                "question": "How do fossils form in sedimentary rock?",
                "lesson": "When an animal or plant dies and gets buried quickly by mud or sand, its hard parts (bones, shells) can be preserved. Over millions of years, [bold yellow]minerals replace the original material[/bold yellow], turning it to stone. That's a fossil — a record of ancient life locked in rock!",
                "options": ["Animals crawl inside rocks", "Dead organisms get buried and slowly turn to stone over millions of years", "Scientists carve them into rocks", "Lightning strikes create them"],
                "answer": "b",
                "hints": ["It takes millions of years and lots of layers piling up.", "The organism gets buried, and minerals slowly replace its remains."],
                "xp": 35,
            },
            {
                "id": "se_07",
                "title": "Worm Heroes",
                "type": "text",
                "question": "What small creature is famous for mixing and aerating soil by tunneling through it? (one word)",
                "answer": "earthworm",
                "lesson": "[bold yellow]Earthworms[/bold yellow] are soil superheroes! As they tunnel, they mix soil layers, create air pockets for roots, and leave behind nutrient-rich castings (worm poop). Charles Darwin called them the most important creatures in the history of the world!",
                "hints": ["It's long, wiggly, and lives underground.", "Earth + worm = ?"],
                "xp": 30,
            },
            {
                "id": "se_boss",
                "title": "Why Soil Matters",
                "type": "quiz",
                "question": "Why is healthy soil important for all life on Earth?",
                "lesson": "Almost everything we eat grows in soil or eats something that grew in soil. Soil filters our water, stores carbon, and is home to billions of organisms. Without healthy [bold yellow]topsoil[/bold yellow], crops can't grow, ecosystems collapse, and life as we know it could not exist. Protecting soil is protecting life!",
                "options": ["It isn't — only water matters", "It grows our food, filters water, and supports nearly all life", "Only farmers need it", "It's just for building houses on"],
                "answer": "b",
                "hints": ["Think about where your food comes from — every fruit, vegetable, grain.", "Soil supports plants, which support animals, which support us."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "natural_resources": {
        "id": "natural_resources",
        "name": "Treasures of the Earth",
        "subtitle": "What does the Earth give us, and how do we protect it?",
        "icon": "\u267b\ufe0f",
        "description": "Learn about renewable and nonrenewable resources, conservation, and recycling",
        "level_required": 5,
        "challenges": [
            {
                "id": "nr_01",
                "title": "What Is a Natural Resource?",
                "type": "quiz",
                "question": "A natural resource is something ___.",
                "lesson": "A [bold yellow]natural resource[/bold yellow] is anything from nature that people use — water, air, soil, trees, minerals, sunlight, and fossil fuels. Some can be replaced; some cannot. Learning the difference is the key to taking care of our planet.",
                "options": ["Made in a factory", "Found in nature that people use", "Only found underground", "That costs a lot of money"],
                "answer": "b",
                "hints": ["Nature provides it — we don't manufacture it.", "Water, trees, sunlight, coal — all examples."],
                "xp": 30,
            },
            {
                "id": "nr_02",
                "title": "Renewable or Not?",
                "type": "quiz",
                "question": "Which of these is a renewable resource?",
                "lesson": "[bold yellow]Renewable resources[/bold yellow] can be replaced naturally in a human lifetime — like sunlight, wind, water, and trees. [bold yellow]Nonrenewable resources[/bold yellow] like coal, oil, and natural gas take millions of years to form and will eventually run out.",
                "options": ["Coal", "Oil", "Sunlight", "Natural gas"],
                "answer": "c",
                "hints": ["Does the sun stop shining? Does coal grow back?", "If nature can replace it quickly, it's renewable."],
                "xp": 30,
            },
            {
                "id": "nr_03",
                "title": "Fossil Fuels",
                "type": "quiz",
                "question": "Why are coal, oil, and natural gas called 'fossil fuels'?",
                "lesson": "[bold yellow]Fossil fuels[/bold yellow] formed from the remains of ancient plants and animals buried deep underground for millions of years. Heat and pressure slowly transformed them into coal, oil, and gas. They're called 'fossil' fuels because they come from prehistoric life!",
                "options": ["They are found near dinosaur fossils", "They formed from ancient living things over millions of years", "They were discovered by fossil hunters", "They look like fossils"],
                "answer": "b",
                "hints": ["The 'fossil' part is a clue about where they came from.", "Ancient plants and animals, buried and transformed over millions of years."],
                "xp": 35,
            },
            {
                "id": "nr_04",
                "title": "Reduce, Reuse, Recycle",
                "type": "quiz",
                "question": "Of the 'three Rs' — reduce, reuse, recycle — which one helps the MOST?",
                "lesson": "[bold yellow]Reduce[/bold yellow] helps the most because using less means less waste in the first place! Reuse is second best (use things again instead of throwing them away). Recycling is good too, but it still uses energy. The order matters: Reduce first, Reuse second, Recycle third.",
                "options": ["Recycle", "Reuse", "Reduce", "They all help exactly the same"],
                "answer": "c",
                "hints": ["The most helpful one prevents waste before it happens.", "Using LESS in the first place is better than recycling what you used."],
                "xp": 35,
            },
            {
                "id": "nr_05",
                "title": "Conservation Heroes",
                "type": "quiz",
                "question": "What does conservation mean?",
                "lesson": "[bold yellow]Conservation[/bold yellow] means using natural resources wisely and carefully so they last for future generations. Turning off lights, saving water, protecting forests, and not wasting food are all acts of conservation. Everyone can be a conservation hero!",
                "options": ["Using as much as you want", "Protecting and using resources wisely so they last", "Never using any resources at all", "Storing things in a museum"],
                "answer": "b",
                "hints": ["It's about being smart and careful with what nature gives us.", "To conserve means to save and protect."],
                "xp": 30,
            },
            {
                "id": "nr_06",
                "title": "Power from Nature",
                "type": "text",
                "question": "Energy from the sun is called ___ energy. (one word)",
                "answer": "solar",
                "lesson": "[bold yellow]Solar energy[/bold yellow] comes from the sun. Solar panels convert sunlight directly into electricity. The sun provides more energy in one hour than the entire world uses in a year! Solar power is clean, renewable, and getting cheaper every year.",
                "hints": ["It comes from the Latin word 'sol,' meaning sun.", "Solar panels capture this kind of energy."],
                "xp": 35,
            },
            {
                "id": "nr_07",
                "title": "What Can Be Recycled?",
                "type": "quiz",
                "question": "Which of these materials can typically be recycled?",
                "lesson": "[bold yellow]Paper, glass, metal cans, and many plastics[/bold yellow] can be recycled. Recycling turns old materials into new products, saving energy and reducing waste in landfills. An aluminum can that's recycled today can be back on the shelf as a new can in just 60 days!",
                "options": ["Aluminum cans", "Used tissues", "Broken mirrors", "Styrofoam"],
                "answer": "a",
                "hints": ["Think about what goes in the recycling bin at home.", "Metal cans are one of the easiest things to recycle."],
                "xp": 30,
            },
            {
                "id": "nr_boss",
                "title": "One Earth",
                "type": "quiz",
                "question": "Why is it important to use both renewable and nonrenewable resources wisely?",
                "lesson": "We only have [bold yellow]one Earth[/bold yellow]. Nonrenewable resources will run out someday, so we need to switch to renewable ones. But even renewable resources need care — forests can be cut down faster than they grow, and water can be polluted. Being wise with ALL resources means a healthier planet for everyone, now and in the future.",
                "options": ["It doesn't matter — we can always find more", "Nonrenewable resources will run out, and even renewable ones need careful management", "Only scientists need to worry about this", "Resources are unlimited"],
                "answer": "b",
                "hints": ["Think about what happens if we use something up and it can't come back.", "Even trees and water can be harmed if we're not careful."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },
}
