"""
zones.py — Greetings zones and challenges.

All challenges use "type": "quiz" with multiple-choice options.
Guided by 先生 (Sensei), a wise, patient Japanese teacher.
"""

ZONE_ORDER = [
    "hello_goodbye",
    "self_intro",
    "thanks_sorry",
    "counting_people",
    "classroom",
    "keigo_basics",
]

ZONES = {
    # ── Zone 1: Hello & Goodbye ──────────────────────────────────────
    "hello_goodbye": {
        "id": "hello_goodbye",
        "name": "Hello & Goodbye",
        "description": "Learn daily greetings: こんにちは, おはよう, こんばんは, さようなら",
        "level_required": 1,
        "challenges": [
            {
                "id": "greet_konnichiwa",
                "title": "Good Afternoon",
                "type": "quiz",
                "question": "こんにちは (konnichiwa) is used to say: ",
                "options": ["Good morning", "Hello / Good afternoon", "Good evening", "Goodbye"],
                "answer": "b",
                "hints": [
                    "This is the most general Japanese greeting.",
                    "Used roughly from late morning through the afternoon.",
                ],
                "xp": 25,
                "lesson": "こんにちは (konnichiwa) = hello / good afternoon. It's the most common greeting, used from about 10am to evening. Note: the は is read 'wa' (particle).",
                "is_boss": False,
                "flavor": "Sensei greets you with a warm こんにちは.",
            },
            {
                "id": "greet_ohayou",
                "title": "Good Morning",
                "type": "quiz",
                "question": "おはようございます (ohayou gozaimasu) means: (Romaji: ohayou gozaimasu)",
                "options": ["Good evening", "Good night", "Good morning (polite)", "Goodbye"],
                "answer": "c",
                "hints": [
                    "This greeting is for the morning hours.",
                    "ございます makes it polite. Casual form: おはよう.",
                ],
                "xp": 25,
                "lesson": "おはようございます (ohayou gozaimasu) = good morning (polite). The casual form おはよう (ohayou) is used with friends and family.",
                "is_boss": False,
                "flavor": "Sensei opens the morning shutters and greets you brightly.",
            },
            {
                "id": "greet_konbanwa",
                "title": "Good Evening",
                "type": "quiz",
                "question": "When the sun goes down, you say: (Romaji: konbanwa)",
                "options": ["おはよう (ohayou)", "こんにちは (konnichiwa)", "こんばんは (konbanwa)", "おやすみ (oyasumi)"],
                "answer": "c",
                "hints": [
                    "This greeting is for evening time.",
                    "こんばん means 'this evening', は is the topic particle.",
                ],
                "xp": 25,
                "lesson": "こんばんは (konbanwa) = good evening. Used from around sunset onward. Like こんにちは, the は is read 'wa'.",
                "is_boss": False,
                "flavor": "The sun sets outside Sensei's window as you learn the evening greeting.",
            },
            {
                "id": "greet_sayounara",
                "title": "Goodbye",
                "type": "quiz",
                "question": "さようなら (sayounara) means goodbye, but when is it typically used? (Romaji: sayounara)",
                "options": ["Only with close friends", "For longer or more formal farewells", "At bedtime only", "Only at funerals"],
                "answer": "b",
                "hints": [
                    "さようなら is more formal and implies you won't see someone for a while.",
                    "For casual 'bye', Japanese people often use じゃね or またね instead.",
                ],
                "xp": 25,
                "lesson": "さようなら (sayounara) = goodbye (formal/longer farewells). Casual alternatives: じゃね (ja ne) = see ya, またね (mata ne) = see you later, バイバイ (baibai) = bye-bye.",
                "is_boss": False,
                "flavor": "Sensei explains that さようなら carries more weight than a casual goodbye.",
            },
            {
                "id": "greet_oyasumi",
                "title": "Good Night",
                "type": "quiz",
                "question": "おやすみなさい (oyasumi nasai) is said when: (Romaji: oyasumi nasai)",
                "options": ["Waking up", "Going to bed / saying goodnight", "Leaving work", "Entering a store"],
                "answer": "b",
                "hints": [
                    "おやすみ comes from the verb 'to rest'.",
                    "なさい makes it polite. Casual: おやすみ.",
                ],
                "xp": 25,
                "lesson": "おやすみなさい (oyasumi nasai) = good night (polite). Casual: おやすみ (oyasumi). Said when going to bed or parting ways in the evening.",
                "is_boss": False,
                "flavor": "Sensei dims the lights as you learn the bedtime farewell.",
            },
            {
                "id": "hello_goodbye_boss",
                "title": "Greeting Master",
                "type": "quiz",
                "question": "It's 8:00 AM. You meet your teacher. What do you say?",
                "options": ["こんにちは (konnichiwa)", "こんばんは (konbanwa)", "おはようございます (ohayou gozaimasu)", "さようなら (sayounara)"],
                "answer": "c",
                "hints": [
                    "8 AM is morning, and a teacher deserves polite speech.",
                    "The polite morning greeting includes ございます.",
                ],
                "xp": 35,
                "lesson": "At 8 AM with a teacher, use the polite morning greeting: おはようございます. Choosing the right greeting for the time and audience is key to Japanese social skills.",
                "is_boss": True,
                "flavor": "Sensei tests whether you can match greetings to real situations.",
            },
        ],
    },

    # ── Zone 2: Self-Introduction ────────────────────────────────────
    "self_intro": {
        "id": "self_intro",
        "name": "Self-Introduction",
        "description": "Learn to introduce yourself: はじめまして, 私は...です",
        "level_required": 2,
        "challenges": [
            {
                "id": "intro_hajimemashite",
                "title": "Nice to Meet You",
                "type": "quiz",
                "question": "はじめまして (hajimemashite) means: (Romaji: hajimemashite)",
                "options": ["Thank you", "I'm sorry", "Nice to meet you / How do you do", "See you later"],
                "answer": "c",
                "hints": [
                    "This is the first thing you say when meeting someone new.",
                    "It literally means 'for the first time' -- this is our first meeting.",
                ],
                "xp": 25,
                "lesson": "はじめまして (hajimemashite) = nice to meet you / how do you do. Said only at FIRST meetings. Literally: 'for the first time'.",
                "is_boss": False,
                "flavor": "Sensei introduces you to an imaginary new friend.",
            },
            {
                "id": "intro_watashi_wa",
                "title": "I am...",
                "type": "quiz",
                "question": "わたしは サム です (watashi wa Samu desu) means: (Romaji: watashi wa ... desu)",
                "options": ["My friend is Sam", "I am Sam", "Sam is here", "Do you know Sam?"],
                "answer": "b",
                "hints": [
                    "わたし (watashi) = I/me, は (wa) = topic marker, です (desu) = am/is.",
                    "Pattern: [I] は [name] です = I am [name].",
                ],
                "xp": 25,
                "lesson": "わたしは...です (watashi wa ... desu) = I am .... This is the basic pattern for stating your name. わたし = I, は = topic marker, です = am/is.",
                "is_boss": False,
                "flavor": "Sensei helps you construct your first Japanese sentence about yourself.",
            },
            {
                "id": "intro_from",
                "title": "Where I'm From",
                "type": "quiz",
                "question": "アメリカからきました (amerika kara kimashita) means: (Romaji: amerika kara kimashita)",
                "options": ["I like America", "I'm going to America", "I came from America", "America is far away"],
                "answer": "c",
                "hints": [
                    "から (kara) = from, きました (kimashita) = came.",
                    "Pattern: [place] から きました = I came from [place].",
                ],
                "xp": 30,
                "lesson": "...からきました (...kara kimashita) = I came from .... から = from, きました = came (polite past). Use this to tell people your home country or city.",
                "is_boss": False,
                "flavor": "Sensei asks where you're from, helping you practice the pattern.",
            },
            {
                "id": "intro_yoroshiku",
                "title": "Please Treat Me Well",
                "type": "quiz",
                "question": "よろしくおねがいします (yoroshiku onegaishimasu) is said: (Romaji: yoroshiku onegaishimasu)",
                "options": ["When angry", "At the end of a self-introduction (please treat me well)", "When ordering food", "When saying goodbye"],
                "answer": "b",
                "hints": [
                    "This phrase ends almost every self-introduction.",
                    "It expresses 'please look favorably on me' or 'please treat me well'.",
                ],
                "xp": 30,
                "lesson": "よろしくおねがいします (yoroshiku onegaishimasu) = pleased to meet you / please treat me well. It closes the self-introduction and shows humility and goodwill.",
                "is_boss": False,
                "flavor": "Sensei bows as they say this essential closing phrase.",
            },
            {
                "id": "intro_occupation",
                "title": "What I Do",
                "type": "quiz",
                "question": "がくせいです (gakusei desu) means: (Romaji: gakusei desu)",
                "options": ["I'm a teacher", "I'm a student", "I'm a doctor", "I'm working"],
                "answer": "b",
                "hints": [
                    "がくせい (gakusei) = student, です (desu) = am/is.",
                    "Other occupations: せんせい (teacher), かいしゃいん (office worker).",
                ],
                "xp": 25,
                "lesson": "がくせいです (gakusei desu) = I am a student. Common occupations: せんせい (sensei) = teacher, いしゃ (isha) = doctor, かいしゃいん (kaishain) = company employee.",
                "is_boss": False,
                "flavor": "Sensei helps you add your occupation to your introduction.",
            },
            {
                "id": "self_intro_boss",
                "title": "Full Introduction",
                "type": "quiz",
                "question": "Put the self-introduction in the correct order:",
                "options": [
                    "はじめまして → わたしは...です → よろしくおねがいします",
                    "よろしくおねがいします → はじめまして → わたしは...です",
                    "わたしは...です → さようなら → はじめまして",
                    "こんにちは → ありがとう → さようなら"
                ],
                "answer": "a",
                "hints": [
                    "Start with 'nice to meet you', then state your name, then close politely.",
                    "はじめまして always comes first, よろしく always comes last.",
                ],
                "xp": 35,
                "lesson": "The standard self-introduction order: 1) はじめまして (nice to meet you), 2) わたしは[name]です (I am [name]), 3) よろしくおねがいします (please treat me well). This pattern is universal in Japan.",
                "is_boss": True,
                "flavor": "Sensei tests the complete introduction sequence.",
            },
        ],
    },

    # ── Zone 3: Thanks & Sorry ───────────────────────────────────────
    "thanks_sorry": {
        "id": "thanks_sorry",
        "name": "Thanks & Sorry",
        "description": "Master ありがとう, すみません, and polite expressions",
        "level_required": 3,
        "challenges": [
            {
                "id": "thanks_arigatou",
                "title": "Thank You",
                "type": "quiz",
                "question": "ありがとうございます (arigatou gozaimasu) is the polite form of: (Romaji: arigatou gozaimasu)",
                "options": ["I'm sorry", "Thank you", "Excuse me", "You're welcome"],
                "answer": "b",
                "hints": [
                    "ありがとう = thanks (casual), ございます adds politeness.",
                    "This is one of the first words every visitor to Japan learns.",
                ],
                "xp": 25,
                "lesson": "ありがとうございます (arigatou gozaimasu) = thank you (polite). Casual: ありがとう (arigatou). Use ございます with strangers, elders, and in formal settings.",
                "is_boss": False,
                "flavor": "Sensei receives a gift and demonstrates proper thanks.",
            },
            {
                "id": "thanks_sumimasen",
                "title": "Excuse Me / Sorry",
                "type": "quiz",
                "question": "すみません (sumimasen) can mean all of the following EXCEPT: (Romaji: sumimasen)",
                "options": ["Excuse me (getting attention)", "I'm sorry (light apology)", "Thank you (with nuance of 'sorry to trouble you')", "Goodbye"],
                "answer": "d",
                "hints": [
                    "すみません is incredibly versatile in Japanese.",
                    "It can mean excuse me, sorry, and even a humble thank you.",
                ],
                "xp": 30,
                "lesson": "すみません (sumimasen) = excuse me / I'm sorry / (humble) thank you. One of the most versatile Japanese words. It can get someone's attention, apologize, and express grateful humility.",
                "is_boss": False,
                "flavor": "Sensei shows the many faces of すみません.",
            },
            {
                "id": "thanks_gomen",
                "title": "I'm Sorry (Casual)",
                "type": "quiz",
                "question": "ごめんなさい (gomen nasai) is used when: (Romaji: gomen nasai)",
                "options": ["Thanking someone", "Apologizing sincerely", "Greeting someone", "Ordering food"],
                "answer": "b",
                "hints": [
                    "ごめん is a sincere apology, なさい adds politeness.",
                    "More personal than すみません -- used when you truly feel sorry.",
                ],
                "xp": 25,
                "lesson": "ごめんなさい (gomen nasai) = I'm sorry (sincere). Casual: ごめん (gomen). Use this for personal apologies. すみません is for lighter 'excuse me' situations.",
                "is_boss": False,
                "flavor": "Sensei explains the difference between すみません and ごめんなさい.",
            },
            {
                "id": "thanks_douitashimashite",
                "title": "You're Welcome",
                "type": "quiz",
                "question": "どういたしまして (dou itashimashite) means: (Romaji: dou itashimashite)",
                "options": ["Thank you very much", "You're welcome", "I'm sorry", "See you tomorrow"],
                "answer": "b",
                "hints": [
                    "This is the response when someone thanks you.",
                    "Literally means 'what have I done?' (implying 'it was nothing').",
                ],
                "xp": 25,
                "lesson": "どういたしまして (dou itashimashite) = you're welcome. In casual speech, people often say いいえ (iie, 'no, no') or いえいえ (ie ie) instead.",
                "is_boss": False,
                "flavor": "Sensei teaches the proper response to thanks.",
            },
            {
                "id": "thanks_onegai",
                "title": "Please",
                "type": "quiz",
                "question": "おねがいします (onegaishimasu) means: (Romaji: onegaishimasu)",
                "options": ["I'm sorry", "Thank you", "Please (I make a request)", "Goodbye"],
                "answer": "c",
                "hints": [
                    "Used when making a request or asking for something.",
                    "Literally: 'I humbly request.'",
                ],
                "xp": 25,
                "lesson": "おねがいします (onegaishimasu) = please (when requesting something). Example: これ、おねがいします (kore, onegaishimasu) = this one, please. Used in shops, restaurants, and daily life.",
                "is_boss": False,
                "flavor": "Sensei demonstrates polite requesting.",
            },
            {
                "id": "thanks_sorry_boss",
                "title": "Politeness Master",
                "type": "quiz",
                "question": "Someone holds the door for you. Which is the MOST appropriate response?",
                "options": ["ごめんなさい (gomen nasai)", "すみません、ありがとうございます (sumimasen, arigatou gozaimasu)", "さようなら (sayounara)", "おねがいします (onegaishimasu)"],
                "answer": "b",
                "hints": [
                    "In Japan, people often combine すみません (sorry to trouble you) with ありがとう (thank you).",
                    "This shows humility and gratitude together.",
                ],
                "xp": 35,
                "lesson": "Combining すみません with ありがとうございます shows both humility and gratitude -- very Japanese! This dual expression is natural and polite.",
                "is_boss": True,
                "flavor": "Sensei tests your instinct for the right polite expression.",
            },
        ],
    },

    # ── Zone 4: Counting People ──────────────────────────────────────
    "counting_people": {
        "id": "counting_people",
        "name": "Counting People",
        "description": "Learn to count people: ひとり, ふたり, さんにん...",
        "level_required": 4,
        "challenges": [
            {
                "id": "people_hitori",
                "title": "One Person",
                "type": "quiz",
                "question": "ひとり (hitori) means: (Romaji: hitori)",
                "options": ["One thing", "One person / alone", "One animal", "First place"],
                "answer": "b",
                "hints": [
                    "ひと (hito) = person, り is a counter suffix.",
                    "ひとり is an irregular reading -- not いちにん.",
                ],
                "xp": 25,
                "lesson": "ひとり (hitori) = one person / alone. This is IRREGULAR -- not いちにん. ひとり also means 'alone'. Example: ひとりでたべる (hitori de taberu) = eat alone.",
                "is_boss": False,
                "flavor": "Sensei holds up one finger -- ひとり.",
            },
            {
                "id": "people_futari",
                "title": "Two People",
                "type": "quiz",
                "question": "ふたり (futari) means: (Romaji: futari)",
                "options": ["Two things", "Two animals", "Two people", "Second floor"],
                "answer": "c",
                "hints": [
                    "ふた (futa) = two (native Japanese), り is the counter.",
                    "This is also irregular -- not ににん.",
                ],
                "xp": 25,
                "lesson": "ふたり (futari) = two people. Also irregular. From 3 onward, use the regular pattern: さんにん, よにん, ごにん...",
                "is_boss": False,
                "flavor": "Sensei holds up two fingers -- ふたり.",
            },
            {
                "id": "people_sannin",
                "title": "Three to Five People",
                "type": "quiz",
                "question": "How do you say 'three people'? (Romaji: sannin)",
                "options": ["さんり (sanri)", "さんにん (sannin)", "みり (miri)", "みにん (minin)"],
                "answer": "b",
                "hints": [
                    "From three onward, use number + にん (nin).",
                    "さん (san) = three + にん (nin) = people counter.",
                ],
                "xp": 25,
                "lesson": "From three onward: さんにん (3), よにん (4, note: よ not し), ごにん (5). The counter にん (nin) is regular from here.",
                "is_boss": False,
                "flavor": "Sensei counts three, four, five students in the room.",
            },
            {
                "id": "people_nannin",
                "title": "How Many People?",
                "type": "quiz",
                "question": "なんにん (nannin) means: (Romaji: nannin)",
                "options": ["Many people", "How many people?", "No people", "Famous people"],
                "answer": "b",
                "hints": [
                    "なん (nan) = what/how many + にん (nin) = people counter.",
                    "Used to ask about the number of people.",
                ],
                "xp": 25,
                "lesson": "なんにん (nannin) = how many people? なんにんですか (nannin desu ka) = how many people is it? Used at restaurants, events, etc.",
                "is_boss": False,
                "flavor": "Sensei asks you about a group of visitors.",
            },
            {
                "id": "people_family",
                "title": "Family Members",
                "type": "quiz",
                "question": "なんにんかぞくですか (nannin kazoku desu ka) means: (Romaji: nannin kazoku desu ka)",
                "options": ["How many families?", "How many people are in your family?", "Do you have a family?", "Where is your family?"],
                "answer": "b",
                "hints": [
                    "かぞく (kazoku) = family.",
                    "This is a common getting-to-know-you question.",
                ],
                "xp": 30,
                "lesson": "なんにんかぞくですか = how many people in your family? Common answer: よにんかぞくです (yonin kazoku desu) = we're a family of four.",
                "is_boss": False,
                "flavor": "Sensei asks about your family size.",
            },
            {
                "id": "counting_people_boss",
                "title": "People Counter Challenge",
                "type": "quiz",
                "question": "Which pair has IRREGULAR people-counting forms?",
                "options": ["さんにん and よにん (3 and 4)", "ひとり and ふたり (1 and 2)", "ごにん and ろくにん (5 and 6)", "しちにん and はちにん (7 and 8)"],
                "answer": "b",
                "hints": [
                    "Only one and two people use the native Japanese counting words.",
                    "ひとり and ふたり don't follow the ~にん pattern.",
                ],
                "xp": 35,
                "lesson": "ひとり (1 person) and ふたり (2 people) are the irregular forms. From 3 onward, the pattern is regular: さんにん, よにん, ごにん, etc.",
                "is_boss": True,
                "flavor": "Sensei tests the tricky irregular people counters.",
            },
        ],
    },

    # ── Zone 5: Classroom Phrases ────────────────────────────────────
    "classroom": {
        "id": "classroom",
        "name": "Classroom Phrases",
        "description": "Essential phrases for learning: わかりますか, もういちど, etc.",
        "level_required": 5,
        "challenges": [
            {
                "id": "class_wakarimasu",
                "title": "I Understand",
                "type": "quiz",
                "question": "わかりますか (wakarimasu ka) means: (Romaji: wakarimasu ka)",
                "options": ["Do you understand?", "Do you speak Japanese?", "Can you hear me?", "Are you ready?"],
                "answer": "a",
                "hints": [
                    "わかります (wakarimasu) = understand, か (ka) = question marker.",
                    "Answer: はい、わかります or いいえ、わかりません.",
                ],
                "xp": 25,
                "lesson": "わかりますか (wakarimasu ka) = do you understand? はい、わかります (hai, wakarimasu) = yes, I understand. いいえ、わかりません (iie, wakarimasen) = no, I don't understand.",
                "is_boss": False,
                "flavor": "Sensei asks if you understand with a gentle smile.",
            },
            {
                "id": "class_wakarimasen",
                "title": "I Don't Understand",
                "type": "quiz",
                "question": "わかりません (wakarimasen) means: (Romaji: wakarimasen)",
                "options": ["I understand", "I don't understand", "I forgot", "I don't care"],
                "answer": "b",
                "hints": [
                    "ません (masen) is the polite negative ending.",
                    "わかります → わかりません (understand → don't understand).",
                ],
                "xp": 25,
                "lesson": "わかりません (wakarimasen) = I don't understand. The ~ません (~masen) ending makes any ~ます verb negative. This is one of the most useful survival phrases.",
                "is_boss": False,
                "flavor": "Sensei teaches the most honest phrase a learner can say.",
            },
            {
                "id": "class_mouichido",
                "title": "One More Time",
                "type": "quiz",
                "question": "もういちど おねがいします (mou ichido onegaishimasu) means: (Romaji: mou ichido onegaishimasu)",
                "options": ["Please speak louder", "One more time, please", "Please write it down", "Please stop"],
                "answer": "b",
                "hints": [
                    "もういちど (mou ichido) = one more time, おねがいします = please.",
                    "Essential when you miss something the first time.",
                ],
                "xp": 25,
                "lesson": "もういちどおねがいします = one more time please. Also useful: ゆっくりおねがいします (yukkuri onegaishimasu) = slowly please.",
                "is_boss": False,
                "flavor": "Sensei encourages you to always ask for repetition when needed.",
            },
            {
                "id": "class_nihongo",
                "title": "Japanese Language",
                "type": "quiz",
                "question": "にほんごがわかりますか (nihongo ga wakarimasu ka) means: (Romaji: nihongo ga wakarimasu ka)",
                "options": ["Do you like Japanese?", "Do you understand Japanese?", "Do you study Japanese?", "Is this Japanese?"],
                "answer": "b",
                "hints": [
                    "にほんご (nihongo) = Japanese language, が (ga) = subject marker.",
                    "わかります = understand.",
                ],
                "xp": 30,
                "lesson": "にほんごがわかりますか = do you understand Japanese? にほんご = Japanese language. えいご (eigo) = English. ちゅうごくご (chuugokugo) = Chinese.",
                "is_boss": False,
                "flavor": "Sensei asks the question you'll hear often as a Japanese learner.",
            },
            {
                "id": "class_hai_iie",
                "title": "Yes and No",
                "type": "quiz",
                "question": "はい (hai) and いいえ (iie) mean: (Romaji: hai / iie)",
                "options": ["Please and thank you", "Yes and no", "Hello and goodbye", "Here and there"],
                "answer": "b",
                "hints": [
                    "はい = yes / that's correct. いいえ = no / that's not correct.",
                    "はい is also used to show you're listening (like 'uh-huh').",
                ],
                "xp": 25,
                "lesson": "はい (hai) = yes. いいえ (iie) = no. Note: はい is also used as a listening response ('I'm following'). It doesn't always mean agreement!",
                "is_boss": False,
                "flavor": "Sensei teaches the most basic responses.",
            },
            {
                "id": "classroom_boss",
                "title": "Classroom Survival",
                "type": "quiz",
                "question": "Your teacher speaks too fast. What do you say?",
                "options": ["はい、わかりました (hai, wakarimashita)", "ゆっくり おねがいします (yukkuri onegaishimasu)", "さようなら (sayounara)", "ありがとう (arigatou)"],
                "answer": "b",
                "hints": [
                    "ゆっくり (yukkuri) = slowly.",
                    "Combined with おねがいします, it's a polite request to slow down.",
                ],
                "xp": 35,
                "lesson": "ゆっくりおねがいします (yukkuri onegaishimasu) = slowly, please. Other survival phrases: かいてください (kaite kudasai) = please write it, もういちど (mou ichido) = one more time.",
                "is_boss": True,
                "flavor": "Sensei tests your ability to handle real classroom situations.",
            },
        ],
    },

    # ── Zone 6: Keigo Basics ─────────────────────────────────────────
    "keigo_basics": {
        "id": "keigo_basics",
        "name": "Keigo Basics",
        "description": "Introduction to polite speech: です/ます form",
        "level_required": 6,
        "challenges": [
            {
                "id": "keigo_desu",
                "title": "です — The Polite Copula",
                "type": "quiz",
                "question": "です (desu) makes a sentence polite. What's the difference between がくせいだ and がくせいです? (Romaji: desu)",
                "options": ["No difference", "です is polite, だ is casual", "だ is polite, です is casual", "They mean different things"],
                "answer": "b",
                "hints": [
                    "だ (da) is the casual form, です (desu) is polite.",
                    "Use です with anyone you don't know well.",
                ],
                "xp": 25,
                "lesson": "です (desu) = is/am/are (polite). だ (da) = is/am/are (casual). Always use です with strangers, elders, and in professional settings. Casual だ is for friends and family.",
                "is_boss": False,
                "flavor": "Sensei explains the foundation of Japanese politeness.",
            },
            {
                "id": "keigo_masu",
                "title": "ます — Polite Verb Ending",
                "type": "quiz",
                "question": "たべます (tabemasu) is the polite form of たべる (taberu). What does ます indicate? (Romaji: masu)",
                "options": ["Past tense", "Polite/formal present tense", "Negative", "Question"],
                "answer": "b",
                "hints": [
                    "ます (masu) is added to verb stems to make them polite.",
                    "たべる (casual) → たべます (polite).",
                ],
                "xp": 30,
                "lesson": "ます (masu) = polite verb ending. たべる → たべます (eat), のむ → のみます (drink), いく → いきます (go). The ~ます form is essential for polite Japanese.",
                "is_boss": False,
                "flavor": "Sensei transforms casual verbs into their polite forms.",
            },
            {
                "id": "keigo_masen",
                "title": "ません — Polite Negative",
                "type": "quiz",
                "question": "たべません (tabemasen) means: (Romaji: tabemasen)",
                "options": ["I eat", "I ate", "I don't eat", "I want to eat"],
                "answer": "c",
                "hints": [
                    "ません (masen) is the negative form of ます.",
                    "たべます (eat) → たべません (don't eat).",
                ],
                "xp": 25,
                "lesson": "ません (masen) = polite negative. たべます → たべません (don't eat). のみます → のみません (don't drink). Change ます to ません for negation.",
                "is_boss": False,
                "flavor": "Sensei shows how to politely decline.",
            },
            {
                "id": "keigo_mashita",
                "title": "ました — Polite Past",
                "type": "quiz",
                "question": "たべました (tabemashita) means: (Romaji: tabemashita)",
                "options": ["I eat", "I will eat", "I ate", "I don't eat"],
                "answer": "c",
                "hints": [
                    "ました (mashita) is the past tense of ます.",
                    "たべます (eat) → たべました (ate).",
                ],
                "xp": 25,
                "lesson": "ました (mashita) = polite past. たべます → たべました (ate). のみます → のみました (drank). Change ます to ました for past tense.",
                "is_boss": False,
                "flavor": "Sensei adds the past tense to your polite speech toolkit.",
            },
            {
                "id": "keigo_levels",
                "title": "Levels of Politeness",
                "type": "quiz",
                "question": "Japanese has multiple levels of politeness. Which order goes from MOST casual to MOST polite?",
                "options": [
                    "たべる → たべます → めしあがります",
                    "めしあがります → たべます → たべる",
                    "たべます → たべる → めしあがります",
                    "たべる → めしあがります → たべます"
                ],
                "answer": "a",
                "hints": [
                    "たべる is plain/casual, たべます is standard polite.",
                    "めしあがります is honorific (super polite, used for others' actions).",
                ],
                "xp": 30,
                "lesson": "Three politeness levels for 'eat': たべる (casual) → たべます (polite) → めしあがります (honorific). As a beginner, master the ます form first -- it covers most situations.",
                "is_boss": False,
                "flavor": "Sensei reveals the layers of Japanese politeness.",
            },
            {
                "id": "keigo_boss",
                "title": "Keigo Challenge",
                "type": "quiz",
                "question": "Convert to polite form: 'にほんごをべんきょうする' (I study Japanese). (Romaji: nihongo o benkyou suru → shimasu)",
                "options": [
                    "にほんごをべんきょうします (nihongo o benkyou shimasu)",
                    "にほんごをべんきょうした (nihongo o benkyou shita)",
                    "にほんごをべんきょうしない (nihongo o benkyou shinai)",
                    "にほんごをべんきょうしろ (nihongo o benkyou shiro)"
                ],
                "answer": "a",
                "hints": [
                    "する (suru) = do (casual) → します (shimasu) = do (polite).",
                    "べんきょうする → べんきょうします.",
                ],
                "xp": 35,
                "lesson": "する → します is one of the most important conversions. べんきょうします (study), りょうりします (cook), うんどうします (exercise). Master this pattern!",
                "is_boss": True,
                "flavor": "Sensei tests your ability to speak politely about daily activities.",
            },
        ],
    },
}
