"""
zones.py — Electricity zones and challenges.

All challenges use "type": "quiz" or "type": "text".
Designed for ages 5-12, guided warmly by Puck.
"""

ZONE_ORDER = [
    "what_is_electricity",
    "circuits_and_batteries",
    "conductors_and_insulators",
    "magnets_and_electromagnets",
    "electricity_in_daily_life",
]

ZONES = {
    "what_is_electricity": {
        "id": "what_is_electricity",
        "name": "The Spark Chamber",
        "subtitle": "Atoms, electrons, and the tiny things that make lightning",
        "icon": "\u26a1",
        "description": "Discover what electricity really is",
        "level_required": 1,
        "challenges": [
            {
                "id": "we_01",
                "title": "What Are Things Made Of?",
                "type": "quiz",
                "question": "Everything around you \u2014 your desk, the air, even YOU \u2014 is made of tiny building blocks. What are they called?",
                "lesson": "Everything in the universe is made of [bold yellow]atoms[/bold yellow]. They are so small you can't see them, even with a regular microscope. A single grain of sand has billions of atoms!",
                "options": ["Molecules", "Atoms", "Sparks", "Cells"],
                "answer": "b",
                "hints": ["They're the smallest building blocks of matter!", "A-T-O-M-S \u2014 the tiniest pieces of everything!"],
                "xp": 30,
            },
            {
                "id": "we_02",
                "title": "Inside an Atom",
                "type": "quiz",
                "question": "Atoms have tiny particles spinning around them called ___. These particles carry electricity!",
                "lesson": "[bold yellow]Electrons[/bold yellow] are tiny particles that orbit the center of an atom. They carry a negative charge, and when they move from atom to atom, that movement is what we call electricity!",
                "options": ["Neutrons", "Protons", "Electrons", "Photons"],
                "answer": "c",
                "hints": ["Their name starts with 'E' \u2014 just like electricity!", "These tiny particles carry a negative charge and can jump between atoms."],
                "xp": 30,
            },
            {
                "id": "we_03",
                "title": "Static Shock!",
                "type": "quiz",
                "question": "You rub your feet on the carpet and then touch a doorknob \u2014 ZAP! What caused that little shock?",
                "lesson": "When you rub your feet on carpet, [bold yellow]electrons[/bold yellow] build up on your body. When you touch metal, all those electrons jump at once \u2014 that's [bold yellow]static electricity[/bold yellow]! The same thing happens with lightning, just much bigger.",
                "options": ["The carpet is too hot", "Electrons built up on your body and jumped to the doorknob", "The doorknob is magnetic", "The air is too dry"],
                "answer": "b",
                "hints": ["It's about electrons piling up and then suddenly moving!", "Rubbing creates a buildup of charge \u2014 that's static electricity!"],
                "xp": 35,
            },
            {
                "id": "we_04",
                "title": "Lightning!",
                "type": "quiz",
                "question": "Lightning is a giant spark of electricity in the sky. What causes it?",
                "lesson": "Inside storm clouds, ice and water bump together and build up huge amounts of [bold yellow]static electricity[/bold yellow]. When the charge gets big enough, it jumps to the ground (or another cloud) as a massive spark \u2014 lightning! It can be hotter than the surface of the sun!",
                "options": ["The sun shining through clouds", "A buildup of static electricity in storm clouds", "Wind blowing very fast", "Clouds crashing into each other"],
                "answer": "b",
                "hints": ["It's like the carpet-and-doorknob trick, but ENORMOUS!", "Charge builds up in clouds until it has to release \u2014 ZAP!"],
                "xp": 35,
            },
            {
                "id": "we_05",
                "title": "Balloon Magic",
                "type": "quiz",
                "question": "You rub a balloon on your hair and it sticks to the wall. Why?",
                "lesson": "Rubbing the balloon on your hair moves [bold yellow]electrons[/bold yellow] from your hair to the balloon. The balloon now has extra negative charge, so it sticks to the neutral wall \u2014 opposite charges attract! That's static electricity at work.",
                "options": ["The balloon gets warm and melts onto the wall", "The balloon picks up electrons and the static charge makes it stick", "The wall is magnetic", "Air pressure holds it up"],
                "answer": "b",
                "hints": ["It's the same idea as the carpet shock \u2014 electrons moving around!", "The balloon gains extra electrons, giving it a charge that attracts to the wall."],
                "xp": 35,
            },
            {
                "id": "we_06",
                "title": "What Is Electric Current?",
                "type": "quiz",
                "question": "Static electricity stays in one place. But when electrons flow steadily through a wire, what is that called?",
                "lesson": "[bold yellow]Electric current[/bold yellow] is electrons flowing through a wire, like water flowing through a pipe. This is the kind of electricity that powers your lights, your TV, and your phone charger!",
                "options": ["Static electricity", "Electric current", "Magnetic force", "Solar power"],
                "answer": "b",
                "hints": ["Think of it like a river of tiny particles flowing through a wire.", "It's called a _____ \u2014 like a current in a river!"],
                "xp": 35,
            },
            {
                "id": "we_07",
                "title": "Electrons on the Move",
                "type": "text",
                "question": "In your own words, what is the difference between static electricity and electric current? (Hint: think about whether the electrons stay still or flow.)",
                "options": [],
                "answer": "static electricity stays in one place and current flows",
                "lesson": "[bold yellow]Static electricity[/bold yellow] is when electrons build up in one spot and then jump. [bold yellow]Electric current[/bold yellow] is when electrons flow steadily through a wire, like water in a pipe. Your house runs on current, but a doorknob shock is static!",
                "hints": ["One stays still and then jumps. The other keeps moving.", "Static = stays put and zaps. Current = flows like a river."],
                "xp": 40,
            },
            {
                "id": "we_boss",
                "title": "The Spark Master Challenge",
                "type": "quiz",
                "question": "A scientist named Benjamin Franklin flew a kite in a thunderstorm to prove that lightning is electricity. What did he attach to the kite string to collect the charge?",
                "lesson": "Benjamin Franklin tied a [bold yellow]metal key[/bold yellow] to the kite string. When lightning hit nearby, the electric charge traveled down the wet string to the key, making a spark. This proved lightning is electricity! (NEVER try this \u2014 it's extremely dangerous!)",
                "options": ["A magnet", "A metal key", "A light bulb", "A battery"],
                "answer": "b",
                "hints": ["It's a small metal object you might use to open a door!", "He attached something metal to attract the charge \u2014 a ___!"],
                "xp": 80,
                "is_boss": True,
            },
        ],
    },

    "circuits_and_batteries": {
        "id": "circuits_and_batteries",
        "name": "The Circuit Workshop",
        "subtitle": "Loops of power \u2014 open, closed, series, and parallel",
        "icon": "\U0001f50b",
        "description": "Learn how circuits and batteries make electricity useful",
        "level_required": 2,
        "challenges": [
            {
                "id": "cb_01",
                "title": "What Is a Circuit?",
                "type": "quiz",
                "question": "For electricity to flow and power a light bulb, the wire path must form a complete ___.",
                "lesson": "A [bold yellow]circuit[/bold yellow] is a complete loop that electricity can flow through. If there's a gap anywhere in the loop, the electricity stops \u2014 just like water stops flowing if you cut a hose!",
                "options": ["Line", "Loop (circuit)", "Square", "Zigzag"],
                "answer": "b",
                "hints": ["The word 'circuit' comes from 'circle' \u2014 it goes all the way around!", "Electricity needs a complete path with no gaps."],
                "xp": 30,
            },
            {
                "id": "cb_02",
                "title": "Open vs. Closed",
                "type": "quiz",
                "question": "When a light switch is OFF, the circuit is ___. When you flip the switch ON, the circuit becomes ___.",
                "lesson": "A switch works by breaking or completing the circuit. [bold yellow]Open circuit = gap = no flow = OFF[/bold yellow]. [bold yellow]Closed circuit = complete loop = flow = ON[/bold yellow]. A switch just opens or closes a tiny gap in the wire!",
                "options": ["Closed, then open", "Open, then closed", "Broken, then fixed", "Hot, then cold"],
                "answer": "b",
                "hints": ["'Open' means there's a gap. 'Closed' means the loop is complete.", "Think: open door = gap = electricity can't cross!"],
                "xp": 30,
            },
            {
                "id": "cb_03",
                "title": "How Does a Battery Work?",
                "type": "quiz",
                "question": "A battery has a + end and a - end. What does a battery do in a circuit?",
                "lesson": "A battery is like a tiny [bold yellow]electron pump[/bold yellow]. Chemical reactions inside push electrons out of the negative (-) end, through the wire, and back in the positive (+) end. This flow of electrons is the electric current that powers your devices!",
                "options": ["It stores light", "It pushes electrons through the circuit", "It makes the wire hot", "It creates new electrons"],
                "answer": "b",
                "hints": ["A battery is the power source \u2014 it pushes something through the wires.", "Batteries push electrons around the loop using chemical energy!"],
                "xp": 35,
            },
            {
                "id": "cb_04",
                "title": "Series Circuits",
                "type": "quiz",
                "question": "In a series circuit, three light bulbs are connected in a single loop, one after another. What happens if one bulb burns out?",
                "lesson": "In a [bold yellow]series circuit[/bold yellow], everything is on one path. If one bulb burns out, it breaks the loop \u2014 and [bold yellow]ALL the bulbs go dark[/bold yellow]. Old Christmas lights worked this way, which is why one bad bulb killed the whole string!",
                "options": ["Only that one bulb goes out", "All the bulbs go out", "The other bulbs get brighter", "Nothing changes"],
                "answer": "b",
                "hints": ["There's only ONE path for electricity. If it's blocked anywhere...", "One break in the chain stops everything!"],
                "xp": 35,
            },
            {
                "id": "cb_05",
                "title": "Parallel Circuits",
                "type": "quiz",
                "question": "In a parallel circuit, each light bulb has its own separate path back to the battery. What happens if one bulb burns out?",
                "lesson": "In a [bold yellow]parallel circuit[/bold yellow], each device has its own path. If one bulb burns out, the others keep working because electricity still flows through the other paths. That's how your house is wired \u2014 one light going out doesn't kill them all!",
                "options": ["All the bulbs go out", "Only that one bulb goes out", "The battery explodes", "The circuit reverses"],
                "answer": "b",
                "hints": ["Each bulb has its OWN path. Does losing one road block all the other roads?", "Parallel means separate paths \u2014 so the others keep going!"],
                "xp": 40,
            },
            {
                "id": "cb_06",
                "title": "Series vs. Parallel",
                "type": "text",
                "question": "Your house has many lights and appliances. Are they wired in series or parallel? Why? (Hint: what happens when one light bulb burns out at home?)",
                "options": [],
                "answer": "parallel because one light going out does not turn off the others",
                "lesson": "Your house uses [bold yellow]parallel circuits[/bold yellow]! Each light and appliance has its own path to the power source. That way, turning off a lamp doesn't shut down your fridge. If houses used series circuits, one burned-out bulb would kill every light in the house!",
                "hints": ["When one bulb burns out at home, do ALL the lights go off?", "Each device in your house works independently \u2014 that means parallel!"],
                "xp": 40,
            },
            {
                "id": "cb_07",
                "title": "Short Circuit!",
                "type": "quiz",
                "question": "A short circuit happens when electricity takes a shortcut and skips the device it's supposed to power. Why is this dangerous?",
                "lesson": "In a [bold yellow]short circuit[/bold yellow], electricity bypasses the device and flows through a path with very little resistance. This makes the wire get [bold yellow]extremely hot[/bold yellow] very fast, which can start a fire! That's why we have fuses and circuit breakers \u2014 they cut the power if this happens.",
                "options": ["It wastes batteries", "Too much current flows and wires overheat, which can cause fires", "It makes the lights too bright", "It uses too much electricity"],
                "answer": "b",
                "hints": ["What happens when way too much electricity flows through a thin wire?", "Overheating wires = fire danger! That's why short circuits are dangerous."],
                "xp": 40,
            },
            {
                "id": "cb_boss",
                "title": "The Circuit Master Challenge",
                "type": "quiz",
                "question": "You have a battery, a light bulb, and a wire. What is the MINIMUM you need to do to make the bulb light up?",
                "lesson": "You need to connect the wire from one end of the battery, through the bulb, and back to the other end \u2014 making a [bold yellow]complete closed circuit[/bold yellow]. The battery pushes electrons through the wire and through the bulb's filament, which glows with heat and light!",
                "options": ["Just touch the wire to the battery", "Connect a complete loop from battery through the bulb and back", "Hold the bulb near the battery", "Wrap the wire around the bulb"],
                "answer": "b",
                "hints": ["Electricity needs a complete path \u2014 from the battery, through the bulb, and back!", "A loop! Battery \u2192 wire \u2192 bulb \u2192 wire \u2192 battery."],
                "xp": 80,
                "is_boss": True,
            },
        ],
    },

    "conductors_and_insulators": {
        "id": "conductors_and_insulators",
        "name": "The Material Lab",
        "subtitle": "What lets electricity through \u2014 and what blocks it",
        "icon": "\U0001f9ea",
        "description": "Discover which materials carry electricity and which stop it",
        "level_required": 3,
        "challenges": [
            {
                "id": "ci_01",
                "title": "Conductors",
                "type": "quiz",
                "question": "Materials that let electricity flow through them easily are called ___.",
                "lesson": "[bold yellow]Conductors[/bold yellow] are materials that let electrons move through them easily. Most metals are great conductors \u2014 that's why wires are made of copper! The electrons in metals can jump from atom to atom very freely.",
                "options": ["Insulators", "Conductors", "Magnets", "Reflectors"],
                "answer": "b",
                "hints": ["They 'conduct' electricity \u2014 like a train conductor guides the train!", "These materials let electrons flow easily. Most metals are this."],
                "xp": 30,
            },
            {
                "id": "ci_02",
                "title": "Insulators",
                "type": "quiz",
                "question": "Materials that BLOCK electricity from flowing are called ___.",
                "lesson": "[bold yellow]Insulators[/bold yellow] are materials that don't let electrons pass through easily. Rubber, plastic, glass, and wood are all insulators. That's why electrical wires are covered in plastic \u2014 to keep the electricity safely inside!",
                "options": ["Conductors", "Insulators", "Batteries", "Circuits"],
                "answer": "b",
                "hints": ["They 'insulate' \u2014 like a cozy jacket insulates you from the cold!", "These materials block electricity. Think: rubber, plastic, glass."],
                "xp": 30,
            },
            {
                "id": "ci_03",
                "title": "Why Copper?",
                "type": "quiz",
                "question": "Most electrical wires in your house are made of copper. Why is copper used?",
                "lesson": "Copper is an excellent [bold yellow]conductor[/bold yellow] \u2014 electrons flow through it very easily. It's also flexible (easy to bend into wires), doesn't rust easily, and isn't as expensive as gold or silver, which are also great conductors.",
                "options": ["It's the cheapest metal", "It's a great conductor and easy to shape into wires", "It's the strongest metal", "It looks pretty"],
                "answer": "b",
                "hints": ["What two qualities make copper perfect for wires?", "It conducts electricity well AND it bends easily into wire shapes!"],
                "xp": 35,
            },
            {
                "id": "ci_04",
                "title": "Rubber Gloves",
                "type": "quiz",
                "question": "Electricians wear rubber gloves when working with wires. Why?",
                "lesson": "Rubber is an [bold yellow]insulator[/bold yellow] \u2014 it blocks electricity from flowing through. Rubber gloves protect electricians by stopping any electric current from reaching their hands. Without them, touching a live wire could be deadly!",
                "options": ["To keep their hands clean", "Rubber blocks electricity from reaching their skin", "To grip the wires better", "To stay warm"],
                "answer": "b",
                "hints": ["What kind of material is rubber? (Conductor or insulator?)", "Rubber is an insulator \u2014 it stops electricity from passing through!"],
                "xp": 35,
            },
            {
                "id": "ci_05",
                "title": "Test It!",
                "type": "quiz",
                "question": "You build a simple circuit with a battery and a light bulb. You put different objects between the wires to test them. Which one will make the bulb light up?",
                "lesson": "The [bold yellow]metal spoon[/bold yellow] is a conductor \u2014 it lets electricity flow through and completes the circuit, so the bulb lights up. The rubber band, wooden stick, and plastic straw are all insulators that block the current.",
                "options": ["A rubber band", "A wooden stick", "A metal spoon", "A plastic straw"],
                "answer": "c",
                "hints": ["Which of these is made of metal?", "Metal conducts electricity. The others are insulators!"],
                "xp": 35,
            },
            {
                "id": "ci_06",
                "title": "Water and Electricity",
                "type": "quiz",
                "question": "Is water a conductor or an insulator?",
                "lesson": "Pure water is actually a poor conductor. But the water in your home, in pools, and in nature has [bold yellow]minerals and salts dissolved in it[/bold yellow], which make it a good conductor. That's why you should NEVER use electrical devices near water \u2014 it can carry electricity right to you!",
                "options": ["Always a perfect insulator", "Pure water is a poor conductor, but tap water with minerals conducts well", "Always a perfect conductor", "Water has nothing to do with electricity"],
                "answer": "b",
                "hints": ["Think about what's dissolved in the water you drink...", "Pure water = poor conductor. Tap water with salts = good conductor. Stay safe!"],
                "xp": 40,
            },
            {
                "id": "ci_07",
                "title": "Name That Material",
                "type": "text",
                "question": "Name one conductor and one insulator you can find in your home right now. Explain why each one is a conductor or insulator.",
                "options": [],
                "answer": "metal is a conductor because electrons flow through it and rubber or plastic is an insulator because it blocks electricity",
                "lesson": "Conductors (metals like copper, aluminum, steel) let electrons flow freely. Insulators (rubber, plastic, wood, glass) hold electrons tightly so they can't move. Look at any power cord \u2014 [bold yellow]copper wire inside (conductor), plastic coating outside (insulator)[/bold yellow]. They work together to keep electricity where it belongs!",
                "hints": ["Look at a lamp cord \u2014 what's inside? What's outside?", "Metal inside = conductor. Plastic outside = insulator. They're a team!"],
                "xp": 40,
            },
            {
                "id": "ci_boss",
                "title": "The Material Master Challenge",
                "type": "quiz",
                "question": "A bird sits on a high-voltage power line and doesn't get shocked. Why?",
                "lesson": "Electricity always follows the [bold yellow]easiest path to the ground[/bold yellow]. The bird is touching only ONE wire, so electricity has no reason to flow through it \u2014 there's no complete circuit through the bird. If the bird touched two wires, or a wire and the ground at the same time, it would be shocked!",
                "options": ["Birds are made of rubber", "Birds are too light for electricity", "The bird only touches one wire, so there's no complete circuit through it", "Power lines don't actually have electricity"],
                "answer": "c",
                "hints": ["Remember: electricity needs a complete path to flow!", "The bird isn't completing a circuit \u2014 it's only touching one wire!"],
                "xp": 80,
                "is_boss": True,
            },
        ],
    },

    "magnets_and_electromagnets": {
        "id": "magnets_and_electromagnets",
        "name": "The Magnet Workshop",
        "subtitle": "Invisible forces, spinning motors, and the link between magnets and electricity",
        "icon": "\U0001f9f2",
        "description": "Discover how magnets and electricity are secretly connected",
        "level_required": 4,
        "challenges": [
            {
                "id": "me_01",
                "title": "What Is a Magnet?",
                "type": "quiz",
                "question": "Every magnet has two ends called ___. What happens when you push two of the SAME end together?",
                "lesson": "Every magnet has a [bold yellow]north pole and a south pole[/bold yellow]. Opposite poles attract (north pulls south). Same poles repel (north pushes north away). You can feel the invisible push if you try to force two same ends together!",
                "options": ["Sides \u2014 they stick together", "Poles \u2014 they push apart (repel)", "Ends \u2014 nothing happens", "Corners \u2014 they spin"],
                "answer": "b",
                "hints": ["Magnets have a North and South ___.", "Same poles push away. Opposite poles pull together!"],
                "xp": 30,
            },
            {
                "id": "me_02",
                "title": "What Do Magnets Attract?",
                "type": "quiz",
                "question": "A magnet will stick to which of these objects?",
                "lesson": "Magnets attract metals that contain [bold yellow]iron, nickel, or cobalt[/bold yellow]. A steel paper clip contains iron, so it sticks. Aluminum, copper, wood, and plastic are NOT magnetic. Not all metals are magnetic!",
                "options": ["An aluminum can", "A steel paper clip", "A copper penny", "A wooden block"],
                "answer": "b",
                "hints": ["Not ALL metals are magnetic \u2014 only certain ones!", "Iron and steel are magnetic. Which object contains steel?"],
                "xp": 30,
            },
            {
                "id": "me_03",
                "title": "The Electricity-Magnetism Connection",
                "type": "quiz",
                "question": "When electricity flows through a wire, something invisible appears around the wire. What is it?",
                "lesson": "Moving electricity creates a [bold yellow]magnetic field[/bold yellow] around the wire! This is one of the most amazing discoveries in science. Electricity and magnetism are connected \u2014 you can't have one moving without creating the other.",
                "options": ["Heat waves", "A magnetic field", "Light", "Sound waves"],
                "answer": "b",
                "hints": ["Electricity and magnetism are secretly connected...", "Flowing electricity creates something magnetic around the wire!"],
                "xp": 40,
            },
            {
                "id": "me_04",
                "title": "Build an Electromagnet!",
                "type": "quiz",
                "question": "To build an electromagnet, you wrap wire around an iron nail and connect the wire to a battery. What happens?",
                "lesson": "The electric current flowing through the coiled wire creates a [bold yellow]magnetic field[/bold yellow], and the iron nail makes it much stronger. Now the nail acts like a magnet and can pick up paper clips! Disconnect the battery and the magnetism stops. That's what makes electromagnets special \u2014 [bold yellow]you can turn them on and off[/bold yellow]!",
                "options": ["The nail gets hot", "The nail becomes a magnet that can be turned on and off", "The nail melts", "Nothing happens"],
                "answer": "b",
                "hints": ["Electricity flowing through wire coiled around iron creates...", "An electromagnet! It's a magnet you can switch on and off!"],
                "xp": 40,
            },
            {
                "id": "me_05",
                "title": "How Electric Motors Work",
                "type": "quiz",
                "question": "Inside every electric motor (like in a fan or toy car), what two things work together to create spinning motion?",
                "lesson": "An electric motor uses [bold yellow]magnets and electric current[/bold yellow] working together. The current creates a magnetic field that pushes against permanent magnets, causing a shaft to spin. This is how fans, blenders, electric cars, and washing machines all work!",
                "options": ["Fire and water", "Magnets and electric current", "Gears and springs", "Heat and cold"],
                "answer": "b",
                "hints": ["We just learned that electricity and magnetism are connected...", "Magnets + electricity = motion! That's how motors spin."],
                "xp": 40,
            },
            {
                "id": "me_06",
                "title": "Generators: The Reverse Motor",
                "type": "quiz",
                "question": "A generator is like a motor running BACKWARDS. Instead of electricity making something spin, spinning makes ___.",
                "lesson": "A [bold yellow]generator[/bold yellow] spins a magnet inside coils of wire (or spins wire inside magnets). This moving magnetic field pushes electrons through the wire, creating electric current! Wind turbines, hydroelectric dams, and power plants ALL use generators to make electricity.",
                "options": ["Heat", "Light", "Electricity", "Sound"],
                "answer": "c",
                "hints": ["If electricity + magnets = motion, then motion + magnets = ???", "Spinning magnets near wire creates electric current!"],
                "xp": 40,
            },
            {
                "id": "me_07",
                "title": "Electromagnets in Real Life",
                "type": "text",
                "question": "Electromagnets can be turned on and off. Name one real-world machine or device that uses an electromagnet, and explain why being able to turn the magnet on and off is useful.",
                "options": [],
                "answer": "a junkyard crane uses an electromagnet to pick up metal cars and drop them by turning off",
                "lesson": "Electromagnets are everywhere! [bold yellow]Junkyard cranes[/bold yellow] pick up and drop cars. [bold yellow]Doorbells[/bold yellow] use them to strike the bell. [bold yellow]MRI machines[/bold yellow] in hospitals use giant electromagnets to look inside your body. Being switchable is the key advantage!",
                "hints": ["Think about a junkyard \u2014 how do they pick up and drop heavy metal things?", "A crane that picks up cars with magnetism \u2014 it needs to let go too!"],
                "xp": 40,
            },
            {
                "id": "me_boss",
                "title": "The Magnet Master Challenge",
                "type": "quiz",
                "question": "A compass needle always points north. The needle is a tiny magnet. What is it actually being attracted to?",
                "lesson": "The Earth itself is a giant [bold yellow]magnet[/bold yellow]! It has a magnetic north pole and a magnetic south pole. The compass needle's north pole is attracted to Earth's magnetic south (which is near the geographic North Pole). Earth's magnetism comes from swirling liquid iron deep in its core!",
                "options": ["The North Star", "The Earth's magnetic field", "Cold air at the North Pole", "The moon's gravity"],
                "answer": "b",
                "hints": ["The Earth is more than just a big rock \u2014 it has a hidden superpower!", "Earth has its own magnetic field, created by liquid iron in its core!"],
                "xp": 80,
                "is_boss": True,
            },
        ],
    },

    "electricity_in_daily_life": {
        "id": "electricity_in_daily_life",
        "name": "The Power Grid",
        "subtitle": "Power plants, solar panels, and staying safe",
        "icon": "\U0001f3e0",
        "description": "Discover how electricity gets to your home and how to stay safe around it",
        "level_required": 5,
        "challenges": [
            {
                "id": "dl_01",
                "title": "Where Does Electricity Come From?",
                "type": "quiz",
                "question": "Most electricity in the world is made at ___. How do they generate it?",
                "lesson": "[bold yellow]Power plants[/bold yellow] generate electricity by spinning huge generators. They use different energy sources to do the spinning \u2014 burning coal or gas creates steam that spins turbines, flowing water pushes turbines, and wind pushes wind turbines. The spinning motion creates electricity!",
                "options": ["Batteries", "Power plants that spin generators", "Lightning rods that catch storms", "The sun directly powers every house"],
                "answer": "b",
                "hints": ["Remember generators? Power plants have GIANT ones!", "Power plants spin massive generators to create electricity."],
                "xp": 30,
            },
            {
                "id": "dl_02",
                "title": "Solar Power",
                "type": "quiz",
                "question": "Solar panels turn sunlight directly into electricity. What are they made of?",
                "lesson": "Solar panels are made of [bold yellow]silicon[/bold yellow], a special material called a semiconductor. When sunlight hits the silicon, it knocks electrons loose, creating electric current \u2014 no spinning generators needed! Solar panels are getting cheaper and more popular every year.",
                "options": ["Glass and mirrors", "Special silicon cells that turn light into electricity", "Tiny wind turbines", "Magnets that absorb sunlight"],
                "answer": "b",
                "hints": ["They use a special material that reacts to light...", "Silicon cells convert sunlight directly into electricity!"],
                "xp": 35,
            },
            {
                "id": "dl_03",
                "title": "How Does Electricity Get to Your House?",
                "type": "quiz",
                "question": "Electricity is made at a power plant far away. How does it travel to your home?",
                "lesson": "Electricity travels through a network of [bold yellow]power lines[/bold yellow] (the tall towers and wires you see along roads). It travels at very high voltage (pressure) through thick wires, then transformers lower the voltage to safe levels before it enters your home through the electrical panel.",
                "options": ["Through underground tunnels of water", "Through power lines and transformers", "In trucks that deliver it like fuel", "Through the air like radio waves"],
                "answer": "b",
                "hints": ["Look outside \u2014 can you see tall towers with wires stretching between them?", "Power lines carry electricity from the plant to your neighborhood!"],
                "xp": 35,
            },
            {
                "id": "dl_04",
                "title": "Renewable vs. Nonrenewable",
                "type": "quiz",
                "question": "Solar, wind, and water power are called 'renewable' energy. Coal and oil are 'nonrenewable.' What does that mean?",
                "lesson": "[bold yellow]Renewable[/bold yellow] means it won't run out \u2014 the sun keeps shining, the wind keeps blowing, and rivers keep flowing. [bold yellow]Nonrenewable[/bold yellow] means it CAN run out \u2014 coal and oil took millions of years to form, and once we burn them, they're gone. That's why we're switching to renewable energy!",
                "options": ["Renewable costs more money", "Renewable sources won't run out, but nonrenewable sources can", "Nonrenewable is better for the environment", "There's no real difference"],
                "answer": "b",
                "hints": ["Will the sun stop shining? Will we run out of coal someday?", "Renewable = won't run out. Nonrenewable = limited supply!"],
                "xp": 40,
            },
            {
                "id": "dl_05",
                "title": "Electrical Safety",
                "type": "quiz",
                "question": "Which of these is the SAFEST thing to do around electricity?",
                "lesson": "Electricity can be very dangerous. Always [bold yellow]keep electrical devices away from water[/bold yellow], never stick anything into an outlet, don't touch frayed wires, and stay far away from downed power lines. Electricity follows the easiest path to the ground \u2014 don't let that path be through YOU!",
                "options": ["Stick a fork in an outlet to test it", "Use a hair dryer in the bathtub", "Keep electrical devices away from water", "Pull a plug out by yanking the cord"],
                "answer": "c",
                "hints": ["Water and electricity are a dangerous combination!", "The safe choice involves keeping water and electricity apart."],
                "xp": 35,
            },
            {
                "id": "dl_06",
                "title": "What Is a Fuse?",
                "type": "quiz",
                "question": "A fuse or circuit breaker protects your house. What does it do if too much electricity flows through a wire?",
                "lesson": "A fuse contains a thin wire that [bold yellow]melts and breaks the circuit[/bold yellow] if too much current flows, stopping a potential fire. A circuit breaker does the same thing but can be reset with a switch. They're safety devices that cut the power before wires overheat!",
                "options": ["It makes the electricity stronger", "It cuts off the electricity to prevent overheating and fires", "It stores the extra electricity", "It sends the electricity back to the power plant"],
                "answer": "b",
                "hints": ["What should happen if too much electricity flows? Stop it!", "Fuses and breakers cut the power to prevent fires!"],
                "xp": 35,
            },
            {
                "id": "dl_07",
                "title": "Saving Energy",
                "type": "text",
                "question": "Name three things you can do at home to save electricity and explain why saving electricity is important.",
                "options": [],
                "answer": "turn off lights when leaving a room unplug devices and use less air conditioning to save energy and help the environment",
                "lesson": "Easy ways to save electricity: [bold yellow]Turn off lights[/bold yellow] when you leave a room. [bold yellow]Unplug chargers[/bold yellow] when not in use. Use [bold yellow]LED bulbs[/bold yellow] instead of old ones. Saving electricity means less fuel burned at power plants, which means less pollution and lower bills!",
                "hints": ["What uses electricity at home that you could turn off when not needed?", "Think: lights, screens, chargers \u2014 turning them off when not in use saves energy!"],
                "xp": 40,
            },
            {
                "id": "dl_boss",
                "title": "The Power Grid Master Challenge",
                "type": "quiz",
                "question": "Imagine all power plants stopped working tomorrow. No electricity anywhere. Name the most important reason we need to find clean, renewable ways to make electricity.",
                "lesson": "Burning coal and gas to make electricity releases [bold yellow]carbon dioxide[/bold yellow] and other gases that trap heat in our atmosphere, causing [bold yellow]climate change[/bold yellow]. Renewable energy (solar, wind, water) makes electricity without these harmful gases. Switching to renewables helps protect our planet for future generations!",
                "options": ["So we can watch more TV", "To prevent climate change by reducing harmful gases from burning fossil fuels", "Because solar panels look cool", "Because wind is free"],
                "answer": "b",
                "hints": ["What happens to our planet when we burn too much coal and oil?", "Burning fossil fuels releases gases that warm our planet \u2014 that's climate change!"],
                "xp": 80,
                "is_boss": True,
            },
        ],
    },
}
