"""
zones.py — Cooking & Nutrition zones and challenges for the Cooking skill pack.

All challenges use "type": "quiz" with multiple-choice options.
Designed for ages 7-10, guided warmly by Puck.
"""

ZONE_ORDER = [
    "food_groups",
    "vitamins_and_nutrients",
    "reading_labels",
    "kitchen_safety",
    "cooking_basics",
    "foods_around_world",
    "healthy_choices",
]

ZONES = {
    "food_groups": {
        "id": "food_groups",
        "name": "The Five Food Groups",
        "description": "Learn what fruits, vegetables, grains, protein, and dairy do for your body",
        "level_required": 1,
        "challenges": [
            {
                "id": "fg_fruit_vitamin",
                "title": "Nature's Candy",
                "type": "quiz",
                "question": "Fruits like oranges, strawberries, and blueberries are packed with vitamins and natural sweetness. What is one big reason fruits are good for you?",
                "options": [
                    "They give you vitamins that help you stay healthy",
                    "They are made of the same stuff as candy",
                    "They have no flavor at all",
                    "They make your teeth grow faster",
                ],
                "answer": "a",
                "hints": [
                    "Think about what your body needs to fight off colds.",
                    "Oranges are famous for having lots of Vitamin C!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Fruits are full of vitamins, natural sugars, and fiber. They give your body energy and help keep your immune system strong. Eating different colored fruits gives you different vitamins!",
                "is_boss": False,
                "flavor": "Puck holds up a tiny orange that glows like a lantern. 'Fruits are nature's treasure chest!'",
            },
            {
                "id": "fg_vegetables_power",
                "title": "The Veggie Shield",
                "type": "quiz",
                "question": "Vegetables like broccoli, carrots, and spinach help your body in many ways. What do vegetables help build?",
                "options": [
                    "A strong body with healthy eyes, skin, and bones",
                    "A collection of trading cards",
                    "A taller house",
                    "A faster bicycle",
                ],
                "answer": "a",
                "hints": [
                    "Carrots are famous for helping with one of your senses.",
                    "Spinach has iron, which helps your blood carry oxygen.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Vegetables are loaded with vitamins and minerals. Carrots help your eyesight, spinach builds strong blood, and broccoli has vitamin C and fiber. Eating veggies every day is one of the best things you can do for your body!",
                "is_boss": False,
                "flavor": "Puck flexes a tiny arm. 'Vegetables are your body's shield!'",
            },
            {
                "id": "fg_grains_energy",
                "title": "The Energy Engine",
                "type": "quiz",
                "question": "Bread, rice, oatmeal, and pasta are all made from grains. What do grains give your body?",
                "options": [
                    "Energy to run, think, and play",
                    "The ability to fly",
                    "X-ray vision",
                    "Nothing useful at all",
                ],
                "answer": "a",
                "hints": [
                    "Think about what you eat before a big day of running around.",
                    "Grains are carbohydrates — your body's favorite fuel!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Grains are your body's main source of energy. Whole grains like brown rice and whole wheat bread are extra good because they also have fiber, which helps your tummy work well.",
                "is_boss": False,
                "flavor": "Puck stacks tiny bread slices into a tower. 'Grains are your engine fuel!'",
            },
            {
                "id": "fg_protein_muscles",
                "title": "The Muscle Builder",
                "type": "quiz",
                "question": "Chicken, fish, eggs, beans, and nuts are all protein foods. What does protein help your body do?",
                "options": [
                    "Grow taller and see in the dark",
                    "Build and repair muscles, skin, and hair",
                    "Turn invisible",
                    "Breathe underwater",
                ],
                "answer": "b",
                "hints": [
                    "When you get a scrape, your body needs this to heal.",
                    "Athletes eat a lot of this to keep their muscles strong.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Protein is the building block of your body. It helps build muscles, repair skin, grow hair, and keep your whole body strong. You can get protein from meat, fish, eggs, beans, nuts, and tofu!",
                "is_boss": False,
                "flavor": "Puck lifts a tiny dumbbell. 'Protein builds you up from the inside!'",
            },
            {
                "id": "fg_dairy_bones",
                "title": "The Bone Builder",
                "type": "quiz",
                "question": "Milk, cheese, and yogurt are dairy foods. They are especially important for building strong what?",
                "options": [
                    "Fingernails only",
                    "Bones and teeth",
                    "Eyebrows",
                    "Shoelaces",
                ],
                "answer": "b",
                "hints": [
                    "Dairy is famous for having lots of calcium.",
                    "Your skeleton is made of these — and they need calcium to stay strong!",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Dairy foods are rich in calcium, which is the mineral your body uses to build strong bones and teeth. Growing kids need calcium every day! If you can't have dairy, foods like fortified orange juice and leafy greens also have calcium.",
                "is_boss": False,
                "flavor": "Puck taps a tiny glass of milk against the page. 'Strong bones start here!'",
            },
            {
                "id": "fg_balanced_plate",
                "title": "The Perfect Plate",
                "type": "quiz",
                "question": "A balanced meal has foods from several food groups. Which plate sounds the most balanced?",
                "options": [
                    "Just a big bowl of rice and nothing else",
                    "Grilled chicken, brown rice, steamed broccoli, and a glass of milk",
                    "Three candy bars and a soda",
                    "Only cheese, lots and lots of cheese",
                ],
                "answer": "b",
                "hints": [
                    "A balanced plate has protein, grains, vegetables, and dairy.",
                    "Look for the plate that has the most different food groups!",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "A balanced meal includes foods from multiple food groups: protein, grains, vegetables or fruits, and dairy. This way your body gets all the different nutrients it needs to be healthy and strong!",
                "is_boss": True,
                "flavor": "Puck arranges a miniature feast on the page. 'A balanced plate is a work of art!'",
            },
        ],
    },
    "vitamins_and_nutrients": {
        "id": "vitamins_and_nutrients",
        "name": "Vitamins & Super Nutrients",
        "description": "Discover the vitamins and nutrients that keep your body running",
        "level_required": 2,
        "challenges": [
            {
                "id": "vn_vitamin_c",
                "title": "The Cold Fighter",
                "type": "quiz",
                "question": "Oranges, strawberries, and bell peppers are all rich in a vitamin that helps your body fight off colds. Which vitamin is it?",
                "options": [
                    "Vitamin A",
                    "Vitamin B",
                    "Vitamin C",
                    "Vitamin Z",
                ],
                "answer": "c",
                "hints": [
                    "This vitamin shares its letter with the first letter of 'citrus.'",
                    "Sailors used to eat limes to prevent a disease called scurvy.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Vitamin C helps your immune system fight germs, heals cuts faster, and keeps your skin healthy. Citrus fruits like oranges and lemons are famous for it, but strawberries and bell peppers have lots too!",
                "is_boss": False,
                "flavor": "Puck squeezes a tiny orange and a drop of sunshine falls out.",
            },
            {
                "id": "vn_calcium_bones",
                "title": "The Skeleton Key",
                "type": "quiz",
                "question": "Your bones need a special mineral to stay strong and grow. You find it in milk, cheese, and yogurt. What is it called?",
                "options": [
                    "Iron",
                    "Calcium",
                    "Sugar",
                    "Salt",
                ],
                "answer": "b",
                "hints": [
                    "This mineral's name starts with 'Cal.'",
                    "Without enough of it, your bones could become weak and brittle.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Calcium is the mineral that makes your bones and teeth hard and strong. Kids aged 7-10 need about 1,000 milligrams of calcium every day — that's about three glasses of milk!",
                "is_boss": False,
                "flavor": "Puck taps a tiny bone and it rings like a bell. 'Strong as steel — thanks to calcium!'",
            },
            {
                "id": "vn_iron_blood",
                "title": "The Blood Builder",
                "type": "quiz",
                "question": "Iron is a nutrient found in red meat, beans, and spinach. What does iron help your blood do?",
                "options": [
                    "Turn blue",
                    "Carry oxygen to every part of your body",
                    "Become magnetic",
                    "Taste like metal",
                ],
                "answer": "b",
                "hints": [
                    "Your blood needs to deliver something from your lungs to your muscles.",
                    "Without enough iron, people feel very tired and weak.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Iron helps your red blood cells carry oxygen from your lungs to the rest of your body. Without enough iron, you can feel tired and weak. Spinach, beans, and red meat are all great sources of iron.",
                "is_boss": False,
                "flavor": "Puck holds up a tiny spinach leaf like a superhero cape.",
            },
            {
                "id": "vn_fiber_tummy",
                "title": "The Tummy Helper",
                "type": "quiz",
                "question": "Fiber is found in whole grains, fruits, and vegetables. What does fiber help with?",
                "options": [
                    "Making your hair curly",
                    "Helping your digestive system work smoothly",
                    "Making food taste like chocolate",
                    "Turning food into gold",
                ],
                "answer": "b",
                "hints": [
                    "Think about what helps food move through your body.",
                    "Oatmeal and apples are both great sources of this.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Fiber helps food move through your digestive system smoothly. It keeps your tummy happy and healthy! Fruits, vegetables, whole grains, and beans are all great sources of fiber.",
                "is_boss": False,
                "flavor": "Puck pats a tiny tummy. 'Fiber keeps everything running smoothly!'",
            },
            {
                "id": "vn_water_body",
                "title": "The Life Drink",
                "type": "quiz",
                "question": "Your body is made of about 60% water. Why is drinking water so important?",
                "options": [
                    "It helps every cell in your body work properly",
                    "It makes you magnetic",
                    "It turns your skin blue",
                    "It's not important — you can skip it",
                ],
                "answer": "a",
                "hints": [
                    "When you're thirsty, your body is telling you it needs this!",
                    "Your brain, muscles, and blood all need water to work.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Water is the most important thing you drink! It helps your brain think, your muscles move, your body cool down when you're hot, and your blood flow. Kids should drink about 6-8 glasses of water every day.",
                "is_boss": False,
                "flavor": "Puck holds up a sparkling glass of water. 'The most powerful drink in the world!'",
            },
            {
                "id": "vn_vitamin_a_eyes",
                "title": "The Eye Guardian",
                "type": "quiz",
                "question": "Carrots, sweet potatoes, and mangoes are all orange because they are rich in a vitamin that helps your eyes. Which vitamin is it?",
                "options": [
                    "Vitamin A",
                    "Vitamin C",
                    "Vitamin E",
                    "Vitamin K",
                ],
                "answer": "a",
                "hints": [
                    "This vitamin is the very first letter of the alphabet.",
                    "The orange color in carrots comes from beta-carotene, which your body turns into this vitamin.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Vitamin A keeps your eyes healthy and helps you see in dim light. Orange and yellow foods like carrots, sweet potatoes, and mangoes are rich in beta-carotene, which your body converts into Vitamin A!",
                "is_boss": True,
                "flavor": "Puck peers through a tiny carrot like a telescope. 'I can see forever!'",
            },
        ],
    },
    "reading_labels": {
        "id": "reading_labels",
        "name": "Label Detectives",
        "description": "Learn to read nutrition labels and ingredient lists like a detective",
        "level_required": 4,
        "challenges": [
            {
                "id": "rl_what_is_label",
                "title": "The Secret Code",
                "type": "quiz",
                "question": "Most packaged foods have a 'Nutrition Facts' label on them. What does this label tell you?",
                "options": [
                    "The name of the person who bought it",
                    "What nutrients are inside the food and how much of each",
                    "The price of the food",
                    "What color the food is",
                ],
                "answer": "b",
                "hints": [
                    "This label shows things like calories, fat, sugar, and vitamins.",
                    "It's a box with numbers and percentages on the side of the package.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A Nutrition Facts label tells you exactly what's inside a packaged food — how many calories, how much fat, sugar, protein, and vitamins are in each serving. Learning to read it is like having a superpower!",
                "is_boss": False,
                "flavor": "Puck pulls out a magnifying glass and peers at a cereal box. 'Let's crack the code!'",
            },
            {
                "id": "rl_serving_size",
                "title": "The Serving Surprise",
                "type": "quiz",
                "question": "A bag of chips says it has 150 calories per serving, but the bag contains 3 servings. If you eat the whole bag, how many calories is that?",
                "options": [
                    "150 calories",
                    "300 calories",
                    "450 calories",
                    "50 calories",
                ],
                "answer": "c",
                "hints": [
                    "You need to multiply the calories per serving by the number of servings.",
                    "150 times 3 equals…",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Serving size is one of the most important things on a label! A package often contains more than one serving. To know how much you're really eating, multiply the numbers on the label by how many servings you eat.",
                "is_boss": False,
                "flavor": "Puck counts on tiny fingers. 'One serving… two servings… three servings — surprise!'",
            },
            {
                "id": "rl_ingredients_list",
                "title": "The First Ingredient",
                "type": "quiz",
                "question": "On a food package, the ingredients list shows what's inside. The ingredients are listed in a special order. What comes first?",
                "options": [
                    "The ingredient the company likes best",
                    "The ingredient there is the MOST of",
                    "The ingredient that was added last",
                    "The cheapest ingredient",
                ],
                "answer": "b",
                "hints": [
                    "If sugar is listed first, that means the food is mostly made of…",
                    "The order goes from the most to the least.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Ingredients are listed from most to least. The first ingredient is what the food is mostly made of! If sugar or corn syrup is one of the first ingredients, the food has a lot of added sugar.",
                "is_boss": False,
                "flavor": "Puck reads a tiny ingredients list with a detective hat on.",
            },
            {
                "id": "rl_sugar_names",
                "title": "Sugar in Disguise",
                "type": "quiz",
                "question": "Sugar can hide on ingredient lists under different names. Which of these is actually a type of sugar?",
                "options": [
                    "Calcium",
                    "Fiber",
                    "High fructose corn syrup",
                    "Vitamin D",
                ],
                "answer": "c",
                "hints": [
                    "Look for words that end in '-ose' or include 'syrup.'",
                    "This one is very common in sodas and candy.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Sugar has many names on ingredient lists: high fructose corn syrup, sucrose, glucose, dextrose, maltose, and honey are all types of sugar. If you see several of these in one list, the food has a LOT of sugar!",
                "is_boss": False,
                "flavor": "Puck pulls off a tiny mask from a sugar cube. 'Caught you!'",
            },
            {
                "id": "rl_percent_daily",
                "title": "The Percent Puzzle",
                "type": "quiz",
                "question": "On a nutrition label, you see '% Daily Value.' If a food has 50% Daily Value of calcium, what does that mean?",
                "options": [
                    "The food is 50% calcium",
                    "One serving gives you half the calcium you need in a whole day",
                    "You should eat 50 of them",
                    "It expires in 50 days",
                ],
                "answer": "b",
                "hints": [
                    "Daily Value means the total amount you need in one day.",
                    "50% means half of something.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "The % Daily Value tells you how much of a nutrient one serving gives you compared to what you need all day. 5% or less is LOW — 20% or more is HIGH. It helps you see at a glance if a food is a good source of a nutrient!",
                "is_boss": True,
                "flavor": "Puck holds up a pie chart. 'Halfway there with just one bite!'",
            },
        ],
    },
    "kitchen_safety": {
        "id": "kitchen_safety",
        "name": "The Safe Kitchen",
        "description": "Learn the rules that keep you safe while cooking",
        "level_required": 6,
        "challenges": [
            {
                "id": "ks_hand_washing",
                "title": "The Golden Rule",
                "type": "quiz",
                "question": "What is the FIRST thing you should always do before you start cooking or touching food?",
                "options": [
                    "Turn on the oven",
                    "Taste the ingredients",
                    "Wash your hands with soap and water",
                    "Put on a fancy hat",
                ],
                "answer": "c",
                "hints": [
                    "Germs on your hands can get into the food you're making.",
                    "Soap and water for at least 20 seconds — sing 'Happy Birthday' twice!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Washing your hands with soap and warm water for at least 20 seconds is the number one rule of kitchen safety. It removes germs that could make you or others sick. Always wash before cooking and after touching raw meat!",
                "is_boss": False,
                "flavor": "Puck scrubs tiny hands under a sparkly waterfall. 'Clean hands, safe food!'",
            },
            {
                "id": "ks_knife_safety",
                "title": "The Sharp Truth",
                "type": "quiz",
                "question": "Knives are important tools in the kitchen, but they must be used carefully. What is the safest way to use a knife?",
                "options": [
                    "Run while holding it",
                    "Always cut away from your body, with an adult nearby",
                    "Use it with your eyes closed to practice",
                    "Throw it to a friend across the kitchen",
                ],
                "answer": "b",
                "hints": [
                    "The blade should always move AWAY from your fingers and body.",
                    "Kids should always have a grown-up helper when using sharp knives.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Always cut away from your body, keep your fingers curled back (called 'the claw grip'), and have an adult nearby when using sharp knives. Never run or play with knives, and always put them down carefully.",
                "is_boss": False,
                "flavor": "Puck demonstrates a tiny claw grip with careful precision. 'Respect the blade!'",
            },
            {
                "id": "ks_hot_surfaces",
                "title": "The Heat Warning",
                "type": "quiz",
                "question": "Stoves, ovens, and boiling water are very hot. What should you always use to pick up a hot pot or pan?",
                "options": [
                    "Your bare hands",
                    "A wet paper towel",
                    "Oven mitts or thick pot holders",
                    "A thin plastic bag",
                ],
                "answer": "c",
                "hints": [
                    "You need something thick that protects your hands from heat.",
                    "These are special gloves made just for the kitchen.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Always use oven mitts or thick, dry pot holders to pick up hot pots, pans, and baking trays. Never use wet cloths — steam from wet fabric can burn you! And always ask an adult to help with the oven and stove.",
                "is_boss": False,
                "flavor": "Puck waves tiny oven mitts like boxing gloves. 'Hot stuff — handle with care!'",
            },
            {
                "id": "ks_food_allergies",
                "title": "The Allergy Alert",
                "type": "quiz",
                "question": "Some people are allergic to certain foods like peanuts, milk, or eggs. What should you do if you're cooking for someone with a food allergy?",
                "options": [
                    "Ignore it — allergies aren't real",
                    "Make sure none of the food they're allergic to is in the meal",
                    "Add extra of the food they're allergic to",
                    "Just tell them not to worry about it",
                ],
                "answer": "b",
                "hints": [
                    "Food allergies can make people very, very sick.",
                    "Always read labels and ask about ingredients!",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Food allergies are serious — some can even be life-threatening. The most common allergens are peanuts, tree nuts, milk, eggs, wheat, soy, fish, and shellfish. Always ask your friends about allergies and read ingredient labels carefully!",
                "is_boss": False,
                "flavor": "Puck holds up a tiny warning sign. 'Knowing about allergies can save a life!'",
            },
            {
                "id": "ks_raw_meat",
                "title": "The Raw Danger",
                "type": "quiz",
                "question": "Raw chicken can have harmful bacteria on it. After cutting raw chicken on a cutting board, what should you do?",
                "options": [
                    "Use the same board to cut vegetables right away",
                    "Just wipe it with a dry towel",
                    "Wash the board with hot, soapy water before using it again",
                    "Flip the board over and use the other side",
                ],
                "answer": "c",
                "hints": [
                    "Bacteria from raw meat can spread to other foods — this is called cross-contamination.",
                    "Hot water and soap kill the germs that raw meat leaves behind.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Raw meat can carry bacteria like salmonella. Always wash cutting boards, knives, and your hands with hot, soapy water after touching raw meat. Never let raw meat juices touch food you'll eat without cooking, like salad.",
                "is_boss": False,
                "flavor": "Puck scrubs a cutting board with determined focus. 'No germs allowed!'",
            },
            {
                "id": "ks_fire_safety",
                "title": "The Fire Marshal",
                "type": "quiz",
                "question": "If a small grease fire starts in a pan on the stove, what is the safest thing to do?",
                "options": [
                    "Pour water on it",
                    "Slide a metal lid over the pan to smother the flames",
                    "Fan it with a towel",
                    "Throw flour on it",
                ],
                "answer": "b",
                "hints": [
                    "Water makes grease fires WORSE — it splatters the burning oil!",
                    "Fire needs air to burn. What could you do to cut off the air?",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "NEVER put water on a grease fire — it will make it explode! Instead, slide a metal lid over the pan to cut off the air, or use a fire extinguisher. Turn off the burner and call an adult immediately. Prevention is best: never leave a hot pan unattended!",
                "is_boss": True,
                "flavor": "Puck holds up a tiny fire extinguisher. 'The most important lesson in the whole kitchen!'",
            },
        ],
    },
    "cooking_basics": {
        "id": "cooking_basics",
        "name": "Cooking 101",
        "description": "Learn about measuring, mixing, and the basics of making food",
        "level_required": 8,
        "challenges": [
            {
                "id": "cb_measuring_cups",
                "title": "The Measuring Mystery",
                "type": "quiz",
                "question": "A recipe says you need 1 cup of flour. What tool do you use to measure it?",
                "options": [
                    "A regular drinking glass",
                    "A measuring cup",
                    "Your hands cupped together",
                    "A soup bowl",
                ],
                "answer": "b",
                "hints": [
                    "This tool has exact markings on the side showing cups and milliliters.",
                    "Baking needs precise measurements — eyeballing it doesn't work!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Measuring cups and measuring spoons are essential tools for following recipes. Dry ingredients (like flour) use flat-topped measuring cups that you level off. Liquid ingredients (like milk) use clear measuring cups with a spout.",
                "is_boss": False,
                "flavor": "Puck peers into a tiny measuring cup with scientific precision.",
            },
            {
                "id": "cb_teaspoon_tablespoon",
                "title": "Spoons Big and Small",
                "type": "quiz",
                "question": "A recipe calls for 1 tablespoon of butter. How many teaspoons is that?",
                "options": [
                    "1 teaspoon",
                    "2 teaspoons",
                    "3 teaspoons",
                    "10 teaspoons",
                ],
                "answer": "c",
                "hints": [
                    "A tablespoon is bigger than a teaspoon.",
                    "Think: 'table' is bigger than 'tea' — and it takes 3 small ones to make 1 big one.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "1 tablespoon equals 3 teaspoons. This is one of the most useful measurements to know in cooking! Teaspoons (tsp) are small and tablespoons (tbsp) are bigger. Knowing this helps you follow any recipe.",
                "is_boss": False,
                "flavor": "Puck lines up three tiny teaspoons next to one tablespoon. 'See? A perfect match!'",
            },
            {
                "id": "cb_baking_vs_frying",
                "title": "Heat It Up!",
                "type": "quiz",
                "question": "What is the difference between baking and frying?",
                "options": [
                    "They are exactly the same thing",
                    "Baking uses hot air in an oven; frying uses hot oil in a pan",
                    "Baking is cold and frying is also cold",
                    "Baking uses water and frying uses ice",
                ],
                "answer": "b",
                "hints": [
                    "Think about where cookies are made versus where eggs are cooked.",
                    "An oven surrounds food with hot air; a pan heats food from below with oil.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Baking cooks food with hot air all around it inside an oven — great for bread, cookies, and casseroles. Frying cooks food in hot oil in a pan on the stovetop — great for eggs, pancakes, and stir-fry. Each method gives food a different taste and texture!",
                "is_boss": False,
                "flavor": "Puck stands between a tiny oven and a tiny frying pan. 'Two ways to make delicious!'",
            },
            {
                "id": "cb_mixing_techniques",
                "title": "Stir, Whisk, Fold",
                "type": "quiz",
                "question": "When a recipe says to 'fold' ingredients together, what does that mean?",
                "options": [
                    "Fold the bowl in half",
                    "Stir as fast as you possibly can",
                    "Gently scoop from the bottom and turn over, keeping air in the mixture",
                    "Pour everything into a paper folder",
                ],
                "answer": "c",
                "hints": [
                    "Folding is the gentlest way to mix things together.",
                    "You do this when you want to keep the mixture light and fluffy — like with whipped cream.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Stirring moves a spoon in circles. Whisking uses a whisk to add air and make things smooth. Folding is the gentlest — you scoop from the bottom and turn the mixture over slowly to keep it fluffy. Each technique is used for a reason!",
                "is_boss": False,
                "flavor": "Puck gently folds a cloud of whipped cream. 'Soft and slow — that's the way to fold!'",
            },
            {
                "id": "cb_recipe_order",
                "title": "Follow the Recipe",
                "type": "quiz",
                "question": "Why is it important to read a recipe ALL the way through before you start cooking?",
                "options": [
                    "It's not important — just start cooking!",
                    "So you know all the ingredients and steps you need before you begin",
                    "So you can memorize it and throw it away",
                    "Because recipes self-destruct after you read them once",
                ],
                "answer": "b",
                "hints": [
                    "Imagine getting halfway through and realizing you don't have an ingredient!",
                    "A recipe is like a map — you should see the whole path before you walk it.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Always read the whole recipe before starting! This way you can check that you have all the ingredients, understand each step, and know how long it will take. Chefs call this 'mise en place' — French for 'everything in its place.'",
                "is_boss": False,
                "flavor": "Puck unrolls a tiny recipe scroll and studies it carefully.",
            },
            {
                "id": "cb_kids_recipe",
                "title": "The Kid Chef Challenge",
                "type": "quiz",
                "question": "Which of these is a simple recipe that kids can safely help make at home?",
                "options": [
                    "Deep-fried whole turkey",
                    "Fruit salad with bananas, strawberries, and blueberries",
                    "Flambéed dessert with open flames",
                    "A meal that requires 8 hours of unsupervised cooking",
                ],
                "answer": "b",
                "hints": [
                    "The safest recipes for kids don't need sharp knives or hot stoves.",
                    "Washing fruit and mixing it in a bowl is something any kid can do!",
                ],
                "xp": 35,
                "difficulty": "easy",
                "lesson": "Great kid-friendly recipes include fruit salad, sandwiches, smoothies, trail mix, and ants on a log (celery with peanut butter and raisins). As you learn more, you can help with cooking on the stove — always with an adult!",
                "is_boss": True,
                "flavor": "Puck tosses berries into a tiny bowl with a chef's flourish. 'You're already a chef!'",
            },
        ],
    },
    "foods_around_world": {
        "id": "foods_around_world",
        "name": "The World Kitchen",
        "description": "Taste your way around the globe — discover famous foods from every continent",
        "level_required": 10,
        "challenges": [
            {
                "id": "fw_sushi_japan",
                "title": "The Art of Sushi",
                "type": "quiz",
                "question": "Sushi is a famous dish made with vinegared rice, often topped with raw fish or vegetables. Which country is it from?",
                "options": [
                    "Mexico",
                    "Italy",
                    "Japan",
                    "France",
                ],
                "answer": "c",
                "hints": [
                    "This country is a group of islands in East Asia.",
                    "The same country is famous for ramen, miso soup, and tempura.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Sushi comes from Japan, where it has been made for hundreds of years. The word 'sushi' actually refers to the seasoned rice, not the fish! Sushi chefs train for many years to perfect their craft.",
                "is_boss": False,
                "flavor": "Puck carefully places a tiny piece of sushi on the atlas. 'A bite-sized work of art!'",
            },
            {
                "id": "fw_tacos_mexico",
                "title": "Taco Time!",
                "type": "quiz",
                "question": "Tacos are made with a tortilla filled with meat, beans, cheese, and salsa. Which country are they from?",
                "options": [
                    "India",
                    "Mexico",
                    "China",
                    "Germany",
                ],
                "answer": "b",
                "hints": [
                    "This country is directly south of the United States.",
                    "Tortillas are made from corn — and corn was first grown in this country thousands of years ago!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Tacos come from Mexico, where people have been making tortillas from corn for thousands of years. Mexican food also includes burritos, enchiladas, guacamole, and tamales. Corn, beans, and chili peppers are the heart of Mexican cooking!",
                "is_boss": False,
                "flavor": "Puck takes a tiny bite of a taco and salsa drips everywhere. 'Delicioso!'",
            },
            {
                "id": "fw_pasta_italy",
                "title": "Pasta Perfection",
                "type": "quiz",
                "question": "Spaghetti, penne, and lasagna are all types of pasta. Which country is pasta most famously from?",
                "options": [
                    "Italy",
                    "Australia",
                    "Brazil",
                    "Egypt",
                ],
                "answer": "a",
                "hints": [
                    "This country is shaped like a boot on the map.",
                    "Pizza also comes from this country!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Pasta has been a staple food in Italy for centuries. There are over 300 different shapes of pasta! Italian cooking is based on simple, fresh ingredients — tomatoes, olive oil, garlic, and herbs like basil.",
                "is_boss": False,
                "flavor": "Puck twirls a tiny forkful of spaghetti. 'Perfetto!'",
            },
            {
                "id": "fw_curry_india",
                "title": "The Spice Trail",
                "type": "quiz",
                "question": "Curry is a flavorful dish made with a blend of many spices like turmeric, cumin, and coriander. Which country is most famous for its curries?",
                "options": [
                    "Canada",
                    "India",
                    "Sweden",
                    "South Korea",
                ],
                "answer": "b",
                "hints": [
                    "This country in South Asia is the world's largest producer of spices.",
                    "Different regions of this country make very different styles of curry!",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "India is the world's spice capital! Indian curries come in hundreds of varieties — from mild and creamy to fiery hot. Common spices include turmeric (which makes curry yellow), cumin, coriander, and garam masala. Indian food also includes naan bread, samosas, and biryani.",
                "is_boss": False,
                "flavor": "Puck sniffs a trail of golden spice and sneezes happily. 'So many flavors!'",
            },
            {
                "id": "fw_dim_sum_china",
                "title": "Little Treasures",
                "type": "quiz",
                "question": "Dim sum is a style of eating with many small dishes — dumplings, buns, and rolls — brought out on carts. Which country does it come from?",
                "options": [
                    "Japan",
                    "Thailand",
                    "China",
                    "Italy",
                ],
                "answer": "c",
                "hints": [
                    "This country has the world's largest population and a very ancient cooking tradition.",
                    "The name 'dim sum' means 'touch the heart' in Cantonese!",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Dim sum comes from China, where it started as a snack served with tea over a thousand years ago. Chinese cooking is incredibly diverse — Cantonese, Sichuan, Hunan, and Beijing styles all taste very different! China also gave the world stir-fry, fried rice, and noodles.",
                "is_boss": False,
                "flavor": "Puck lifts the lid of a tiny bamboo steamer. 'Little treasures inside!'",
            },
            {
                "id": "fw_world_staple",
                "title": "The World's Most Eaten Food",
                "type": "quiz",
                "question": "One food is eaten by more than half the people on Earth every single day. It is a staple food in Asia, Africa, and South America. What is it?",
                "options": [
                    "Pizza",
                    "Hamburgers",
                    "Rice",
                    "Chocolate cake",
                ],
                "answer": "c",
                "hints": [
                    "It grows in flooded fields called paddies, mostly in Asia.",
                    "Countries like China, India, and Japan eat this at almost every meal.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Rice is the most important food in the world — over 3.5 billion people depend on it every day! It grows in flooded fields called paddies and has been farmed for over 9,000 years. There are more than 40,000 varieties of rice!",
                "is_boss": True,
                "flavor": "Puck holds up a single grain of rice. 'Tiny, but it feeds the whole world!'",
            },
        ],
    },
    "healthy_choices": {
        "id": "healthy_choices",
        "name": "Choosing Wisely",
        "description": "Learn to build balanced meals, snack smart, and make choices that fuel your day",
        "level_required": 12,
        "challenges": [
            {
                "id": "hc_balanced_meal",
                "title": "Building a Balanced Meal",
                "type": "quiz",
                "question": "A balanced meal means eating foods from several food groups. Which of these lunches is the most balanced?",
                "options": [
                    "A bag of potato chips and a cookie",
                    "A turkey sandwich on whole wheat, an apple, and a glass of milk",
                    "Three slices of plain white bread",
                    "A bowl of sugar with a spoon",
                ],
                "answer": "b",
                "hints": [
                    "Look for protein, grains, fruit or vegetables, and dairy.",
                    "The best meal has something from at least three food groups.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A balanced meal has protein (turkey), whole grains (wheat bread), fruit or vegetables (apple), and dairy (milk). Your body needs all these different nutrients to grow, think, and have energy. Try to include at least three food groups at every meal!",
                "is_boss": False,
                "flavor": "Puck arranges a tiny perfect lunch. 'Balance is the secret ingredient!'",
            },
            {
                "id": "hc_smart_snacking",
                "title": "Snack Attack!",
                "type": "quiz",
                "question": "You're hungry between meals and want a snack. Which choice will give you the best energy to keep going?",
                "options": [
                    "A candy bar",
                    "Apple slices with peanut butter",
                    "A can of soda",
                    "A bag of gummy bears",
                ],
                "answer": "b",
                "hints": [
                    "The best snacks combine something natural with some protein.",
                    "Fruit gives you natural sugar for energy, and peanut butter has protein to keep you full.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Smart snacks combine real food — like fruit, vegetables, nuts, cheese, or yogurt — instead of candy or chips. Apple slices with peanut butter give you fiber, natural sugar, and protein, which keeps your energy steady instead of a sugar crash!",
                "is_boss": False,
                "flavor": "Puck dips a tiny apple slice into peanut butter. 'Now THAT'S a snack!'",
            },
            {
                "id": "hc_sugar_awareness",
                "title": "The Sugar Detective",
                "type": "quiz",
                "question": "A can of regular soda has about 10 teaspoons of sugar in it. Health experts say kids should have no more than how many teaspoons of added sugar per day?",
                "options": [
                    "About 6 teaspoons",
                    "About 25 teaspoons",
                    "About 50 teaspoons",
                    "As much as you want — sugar is always fine",
                ],
                "answer": "a",
                "hints": [
                    "One can of soda already has MORE than a whole day's worth!",
                    "The American Heart Association recommends a surprisingly small amount for kids.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Health experts recommend kids have no more than about 6 teaspoons (25 grams) of added sugar per day. One soda has almost DOUBLE that! Too much sugar can cause cavities, tummy aches, and make it hard to focus. Water and milk are much better drinks!",
                "is_boss": False,
                "flavor": "Puck stacks ten tiny sugar cubes next to a soda can. 'That's a LOT of sugar!'",
            },
            {
                "id": "hc_breakfast_power",
                "title": "The Morning Fuel",
                "type": "quiz",
                "question": "Why do nutritionists say breakfast is one of the most important meals of the day?",
                "options": [
                    "Because it's the fanciest meal",
                    "It gives your brain and body energy after sleeping all night",
                    "Because restaurants are only open in the morning",
                    "It's not important — skipping it is better",
                ],
                "answer": "b",
                "hints": [
                    "Your body hasn't eaten in 8-12 hours while you slept!",
                    "'Breakfast' literally means 'breaking the fast' — ending the time without food.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "After sleeping all night, your body needs fuel! Breakfast gives your brain energy to focus at school and your muscles energy to move. Kids who eat breakfast do better on tests and have more energy. A good breakfast has protein, whole grains, and fruit.",
                "is_boss": False,
                "flavor": "Puck cracks a tiny egg into a pan as the sun rises. 'Rise and dine!'",
            },
            {
                "id": "hc_drink_choices",
                "title": "What Should You Drink?",
                "type": "quiz",
                "question": "You're thirsty after playing outside. Which drink is the healthiest choice for most of the day?",
                "options": [
                    "Soda",
                    "Energy drink",
                    "Water",
                    "Juice box with added sugar",
                ],
                "answer": "c",
                "hints": [
                    "Your body is 60% of this — so it makes sense to drink more of it!",
                    "This drink has zero sugar, zero calories, and is exactly what your body craves.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Water is the best drink for your body! It has no sugar, no calories, and is exactly what your cells need. Milk is great too for the calcium. Save juice for small amounts, and avoid sodas and energy drinks — they have way too much sugar and caffeine for kids.",
                "is_boss": False,
                "flavor": "Puck takes a big gulp from a sparkling glass of water. 'Ahhhh — nothing beats it!'",
            },
            {
                "id": "hc_everything_in_moderation",
                "title": "The Golden Balance",
                "type": "quiz",
                "question": "Is it okay to eat a cookie or a piece of cake sometimes?",
                "options": [
                    "No — sweets are poison and should never be eaten",
                    "Yes — as long as most of what you eat is healthy, treats are fine sometimes",
                    "Yes — you should eat sweets at every meal",
                    "Only on February 29th",
                ],
                "answer": "b",
                "hints": [
                    "The key word in healthy eating is 'balance.'",
                    "No single food is 'bad' — what matters is your overall pattern of eating.",
                ],
                "xp": 35,
                "difficulty": "easy",
                "lesson": "Healthy eating isn't about being perfect — it's about balance! If most of your meals are full of fruits, vegetables, whole grains, and protein, then enjoying a cookie or a slice of birthday cake is absolutely fine. The goal is a healthy pattern, not perfection!",
                "is_boss": True,
                "flavor": "Puck winks and takes a tiny bite of cake. 'Balance — that's the real recipe for life!'",
            },
        ],
    },
}
