"""
zones.py — Numbers zones and challenges.

All challenges use "type": "quiz" with multiple-choice options.
Guided by 先生 (Sensei), a wise, patient Japanese teacher.
"""

ZONE_ORDER = [
    "one_to_ten",
    "eleven_to_99",
    "hundreds_plus",
    "counters",
    "time",
    "money",
]

ZONES = {
    # ── Zone 1: 1-10 ─────────────────────────────────────────────────
    "one_to_ten": {
        "id": "one_to_ten",
        "name": "Numbers 1-10",
        "description": "Learn いち through じゅう (1-10)",
        "level_required": 1,
        "challenges": [
            {
                "id": "num_ichi",
                "title": "いち — One",
                "type": "quiz",
                "question": "いち (ichi) means: (Romaji: ichi)",
                "options": ["One", "Two", "Three", "Ten"],
                "answer": "a",
                "hints": [
                    "This is the very first number.",
                    "いちばん (ichiban) means 'number one' or 'the best'.",
                ],
                "xp": 25,
                "lesson": "いち (ichi) = 1. Example: いちばん (ichiban) = number one / the best. In Japan, いちばん is used to mean 'the most' or 'the best'.",
                "is_boss": False,
                "flavor": "Sensei holds up one finger and says いち.",
            },
            {
                "id": "num_ni_san",
                "title": "に and さん — Two and Three",
                "type": "quiz",
                "question": "に (ni) = 2, さん (san) = 3. What is にさんにち (ni san nichi)? (Romaji: ni, san)",
                "options": ["23 days", "Two or three days", "Sunday", "February 3rd"],
                "answer": "b",
                "hints": [
                    "にさん together means 'two or three' (approximate).",
                    "にち (nichi) = day(s).",
                ],
                "xp": 25,
                "lesson": "に (ni) = 2, さん (san) = 3. にさん as a pair means 'two or three' (approximate). にち = day(s). Note: さん also means Mr./Ms. (different word, same sound).",
                "is_boss": False,
                "flavor": "Sensei counts に, さん on the abacus.",
            },
            {
                "id": "num_shi_yon",
                "title": "し / よん — Four (Two Readings!)",
                "type": "quiz",
                "question": "4 in Japanese has TWO readings: し (shi) and よん (yon). Why is し sometimes avoided? (Romaji: shi / yon)",
                "options": ["し is too long", "し sounds like 死 (shi, death)", "し is old-fashioned", "し is only for counting money"],
                "answer": "b",
                "hints": [
                    "し has an unfortunate homophone in Japanese.",
                    "死 (し) means 'death', so よん is often preferred.",
                ],
                "xp": 30,
                "lesson": "4 = し (shi) or よん (yon). し sounds like 死 (death), so よん is often preferred. Many hospitals skip room/floor 4. よん is the safe choice in most contexts.",
                "is_boss": False,
                "flavor": "Sensei explains the cultural significance of number superstitions.",
            },
            {
                "id": "num_go_roku",
                "title": "ご and ろく — Five and Six",
                "type": "quiz",
                "question": "ご (go) = 5, ろく (roku) = 6. How do you say 'May' (the 5th month)? (Romaji: go, roku)",
                "options": ["ごがつ (gogatsu)", "ろくがつ (rokugatsu)", "ごつき (gotsuki)", "ごげつ (gogetsu)"],
                "answer": "a",
                "hints": [
                    "がつ (gatsu) = month. ご (5) + がつ (month) = ?",
                    "Months in Japanese are simply number + がつ.",
                ],
                "xp": 25,
                "lesson": "ご (go) = 5, ろく (roku) = 6. Months: いちがつ (Jan), にがつ (Feb)... ごがつ (May), ろくがつ (June). Simple: number + がつ!",
                "is_boss": False,
                "flavor": "Sensei teaches numbers through the calendar.",
            },
            {
                "id": "num_shichi_nana",
                "title": "しち / なな — Seven",
                "type": "quiz",
                "question": "7 has two readings: しち (shichi) and なな (nana). Which is more common in everyday counting? (Romaji: shichi / nana)",
                "options": ["しち (shichi)", "なな (nana)", "They're equally common", "Neither -- Japanese use a different word"],
                "answer": "b",
                "hints": [
                    "Like し (4), しち can be confused with other numbers.",
                    "なな is clearer and more commonly used.",
                ],
                "xp": 25,
                "lesson": "7 = しち (shichi) or なな (nana). なな is more common because しち sounds similar to いち (1) and し (4). Use しち in しちがつ (July) and しちごさん (7-5-3 festival).",
                "is_boss": False,
                "flavor": "Sensei explains why なな is the safer choice.",
            },
            {
                "id": "num_hachi_kyu_ju",
                "title": "はち, きゅう, じゅう — 8, 9, 10",
                "type": "quiz",
                "question": "9 has two readings: きゅう (kyuu) and く (ku). Like し, く is avoided because: (Romaji: kyuu / ku)",
                "options": ["く sounds like 苦 (ku, suffering)", "く is too short", "く is informal", "く is only used in math"],
                "answer": "a",
                "hints": [
                    "く (ku) sounds like 苦 (suffering/pain).",
                    "きゅう is generally preferred, similar to よん for 4.",
                ],
                "xp": 30,
                "lesson": "はち (hachi) = 8, きゅう/く (kyuu/ku) = 9, じゅう (juu) = 10. く sounds like 苦 (suffering), so きゅう is preferred. 8 is lucky -- はち sounds like 'prosperity'.",
                "is_boss": False,
                "flavor": "Sensei finishes the basic ten with cultural context.",
            },
            {
                "id": "one_to_ten_boss",
                "title": "Count to Ten",
                "type": "quiz",
                "question": "Which sequence correctly counts 1-5 in Japanese?",
                "options": [
                    "いち, に, さん, し/よん, ご",
                    "いち, さん, に, よん, ご",
                    "ひと, ふた, み, よ, いつ",
                    "わん, つー, すりー, ふぉー, ふぁいぶ"
                ],
                "answer": "a",
                "hints": [
                    "The standard Sino-Japanese counting system.",
                    "Option c is the native Japanese system (also valid but less common for plain counting).",
                ],
                "xp": 35,
                "lesson": "1-5: いち, に, さん, し/よん, ご. 6-10: ろく, しち/なな, はち, きゅう/く, じゅう. Note: option c (ひと, ふた, み...) is the native Japanese system, used with certain counters.",
                "is_boss": True,
                "flavor": "Sensei tests your complete knowledge of 1-10.",
            },
        ],
    },

    # ── Zone 2: 11-99 ────────────────────────────────────────────────
    "eleven_to_99": {
        "id": "eleven_to_99",
        "name": "Numbers 11-99",
        "description": "Build two-digit numbers: じゅういち to きゅうじゅうきゅう",
        "level_required": 2,
        "challenges": [
            {
                "id": "num_eleven",
                "title": "じゅういち — Eleven",
                "type": "quiz",
                "question": "11 in Japanese is じゅういち (juu-ichi). What is the pattern? (Romaji: juuichi)",
                "options": ["ten + one = じゅう + いち", "one + ten = いち + じゅう", "eleven = じゅういち (single word)", "ten-first = じゅうだいいち"],
                "answer": "a",
                "hints": [
                    "11 = 10 + 1 = じゅう + いち.",
                    "Japanese numbers build logically: 10+1, 10+2, 10+3...",
                ],
                "xp": 25,
                "lesson": "11-19: じゅう + digit. じゅういち(11), じゅうに(12), じゅうさん(13)... じゅうきゅう(19). Simply add the ones digit after じゅう.",
                "is_boss": False,
                "flavor": "Sensei shows the elegant logic of Japanese number building.",
            },
            {
                "id": "num_twenty",
                "title": "にじゅう — Twenty",
                "type": "quiz",
                "question": "20 in Japanese is にじゅう (ni-juu). What's the pattern for tens? (Romaji: nijuu)",
                "options": ["digit + じゅう = tens", "じゅう + digit = tens", "にじゅう is irregular", "Twenty has a special word"],
                "answer": "a",
                "hints": [
                    "にじゅう = に(2) + じゅう(10) = two-tens = 20.",
                    "さんじゅう = 30, よんじゅう = 40, etc.",
                ],
                "xp": 25,
                "lesson": "Tens: digit + じゅう. にじゅう(20), さんじゅう(30), よんじゅう(40), ごじゅう(50), ろくじゅう(60), ななじゅう(70), はちじゅう(80), きゅうじゅう(90).",
                "is_boss": False,
                "flavor": "Sensei builds the tens on the abacus.",
            },
            {
                "id": "num_25",
                "title": "にじゅうご — 25",
                "type": "quiz",
                "question": "How do you say 25 in Japanese? (Romaji: nijuugo)",
                "options": ["にご (nigo)", "にじゅうご (nijuugo)", "ふたじゅうご (futajuugo)", "じゅうにご (juunigo)"],
                "answer": "b",
                "hints": [
                    "25 = 20 + 5 = にじゅう + ご.",
                    "Two-digit numbers: [tens] + [ones].",
                ],
                "xp": 25,
                "lesson": "25 = にじゅうご. Pattern: [tens-digit]じゅう[ones-digit]. 47 = よんじゅうなな. 83 = はちじゅうさん. Completely logical!",
                "is_boss": False,
                "flavor": "Sensei demonstrates building any two-digit number.",
            },
            {
                "id": "num_99",
                "title": "きゅうじゅうきゅう — 99",
                "type": "quiz",
                "question": "What is 99 in Japanese? (Romaji: kyuujuukyuu)",
                "options": ["きゅうきゅう (kyuukyuu)", "きゅうじゅうきゅう (kyuujuukyuu)", "くじゅうく (kujuuku)", "ここのじゅうここの (kokonojuukokono)"],
                "answer": "b",
                "hints": [
                    "99 = 90 + 9 = きゅうじゅう + きゅう.",
                    "Use きゅう (not く) for clarity.",
                ],
                "xp": 25,
                "lesson": "99 = きゅうじゅうきゅう (kyuujuukyuu). Fun fact: きゅうきゅう (kyuukyuu) without じゅう means 'emergency' (救急) -- that's the ambulance number!",
                "is_boss": False,
                "flavor": "Sensei reaches the peak of two-digit numbers.",
            },
            {
                "id": "num_phone",
                "title": "Phone Numbers",
                "type": "quiz",
                "question": "Japanese phone numbers are read digit by digit. How do you say 03-1234? (Romaji: zero san no ichi ni san yon)",
                "options": [
                    "ぜろさんの いちにさんよん (zero san no ichi ni san yon)",
                    "さんじゅうの せんにひゃくさんじゅうよん",
                    "さんいちにさんよん",
                    "ぜろさん いちにさんし"
                ],
                "answer": "a",
                "hints": [
                    "Phone numbers are read one digit at a time.",
                    "の (no) separates groups. ぜろ (zero) = 0.",
                ],
                "xp": 30,
                "lesson": "Phone numbers: read digit by digit, with の between groups. ぜろ (zero) = 0. よん is preferred over し for 4. なな is preferred over しち for 7.",
                "is_boss": False,
                "flavor": "Sensei teaches practical number reading for daily life.",
            },
            {
                "id": "eleven_to_99_boss",
                "title": "Two-Digit Challenge",
                "type": "quiz",
                "question": "What number is よんじゅうはち (yonjuuhachi)?",
                "options": ["38", "48", "84", "44"],
                "answer": "b",
                "hints": [
                    "よんじゅう = 40, はち = 8.",
                    "40 + 8 = ?",
                ],
                "xp": 35,
                "lesson": "よんじゅうはち = 48. Breakdown: よん(4) + じゅう(10) = 40, + はち(8) = 48. You can now read any two-digit number!",
                "is_boss": True,
                "flavor": "Sensei tests your number-decoding speed.",
            },
        ],
    },

    # ── Zone 3: 100+ ─────────────────────────────────────────────────
    "hundreds_plus": {
        "id": "hundreds_plus",
        "name": "Hundreds & Beyond",
        "description": "Learn ひゃく, せん, まん — hundreds, thousands, ten-thousands",
        "level_required": 3,
        "challenges": [
            {
                "id": "num_hyaku",
                "title": "ひゃく — Hundred",
                "type": "quiz",
                "question": "ひゃく (hyaku) means: (Romaji: hyaku)",
                "options": ["Ten", "Hundred", "Thousand", "Million"],
                "answer": "b",
                "hints": [
                    "ひゃく = 100.",
                    "にひゃく = 200, さんびゃく = 300 (note the sound change!).",
                ],
                "xp": 25,
                "lesson": "ひゃく (hyaku) = 100. 200 = にひゃく. But 300 = さんびゃく (NOT さんひゃく), 600 = ろっぴゃく, 800 = はっぴゃく. Sound changes!",
                "is_boss": False,
                "flavor": "Sensei introduces the first of the big numbers.",
            },
            {
                "id": "num_hyaku_changes",
                "title": "Sound Changes in Hundreds",
                "type": "quiz",
                "question": "Which hundreds have sound changes (ひゃく → びゃく or ぴゃく)? (Romaji: byaku, pyaku)",
                "options": ["100 and 200", "300, 600, and 800", "400 and 900", "500 and 700"],
                "answer": "b",
                "hints": [
                    "300 = さんびゃく (b), 600 = ろっぴゃく (pp), 800 = はっぴゃく (pp).",
                    "These three are the ones that change.",
                ],
                "xp": 30,
                "lesson": "Sound changes: 300 = さんびゃく, 600 = ろっぴゃく, 800 = はっぴゃく. All others are regular: よんひゃく(400), ごひゃく(500), ななひゃく(700), きゅうひゃく(900).",
                "is_boss": False,
                "flavor": "Sensei drills the tricky sound changes.",
            },
            {
                "id": "num_sen",
                "title": "せん — Thousand",
                "type": "quiz",
                "question": "せん (sen) = 1000. How do you say 3000? (Romaji: sen)",
                "options": ["さんせん (sansen)", "さんぜん (sanzen)", "みせん (misen)", "さんびゃくせん (sanbyakusen)"],
                "answer": "b",
                "hints": [
                    "Like ひゃく, せん has sound changes: 3000 = さんぜん.",
                    "The 's' becomes 'z' after さん.",
                ],
                "xp": 30,
                "lesson": "せん (sen) = 1000. Sound changes: 3000 = さんぜん, 8000 = はっせん. Others regular: にせん(2000), よんせん(4000), ごせん(5000)...",
                "is_boss": False,
                "flavor": "Sensei moves to the thousands on the abacus.",
            },
            {
                "id": "num_man",
                "title": "まん — Ten Thousand",
                "type": "quiz",
                "question": "Japanese has a special word for 10,000: まん (man). How do you say 50,000? (Romaji: man)",
                "options": ["ごじゅうせん (gojuusen)", "ごまん (goman)", "ごせんまん (gosenman)", "ごひゃくひゃく (gohyakuhyaku)"],
                "answer": "b",
                "hints": [
                    "50,000 = 5 × 10,000 = ご + まん.",
                    "Japanese counts in units of 10,000, not 1,000 like English.",
                ],
                "xp": 30,
                "lesson": "まん (man) = 10,000. This is unique to Japanese/Chinese number systems. いちまん(10,000), ごまん(50,000), じゅうまん(100,000). English has no single word for 10,000!",
                "is_boss": False,
                "flavor": "Sensei reveals the まん unit -- a concept that doesn't exist in English.",
            },
            {
                "id": "num_oku",
                "title": "Big Numbers in Context",
                "type": "quiz",
                "question": "Japan's population is about いちおくにせんまん (ichi oku nisen man). おく means: (Romaji: oku)",
                "options": ["One million", "Ten million", "One hundred million", "One billion"],
                "answer": "c",
                "hints": [
                    "おく = 100,000,000 (one hundred million).",
                    "いちおく = 100 million, にせんまん = 20 million → about 120 million.",
                ],
                "xp": 30,
                "lesson": "おく (oku) = 100,000,000. Japan's population: about いちおくにせんまん (120 million). The Japanese number ladder: じゅう(10) → ひゃく(100) → せん(1000) → まん(10,000) → おく(100M).",
                "is_boss": False,
                "flavor": "Sensei connects big numbers to real-world context.",
            },
            {
                "id": "hundreds_plus_boss",
                "title": "Big Number Challenge",
                "type": "quiz",
                "question": "How do you say 3,500 in Japanese?",
                "options": [
                    "さんぜんごひゃく (sanzen gohyaku)",
                    "さんせんごひゃく (sansen gohyaku)",
                    "みっせんごひゃく (missen gohyaku)",
                    "さんごひゃく (sangohyaku)"
                ],
                "answer": "a",
                "hints": [
                    "3000 = さんぜん (with sound change), 500 = ごひゃく.",
                    "3000 + 500 = さんぜんごひゃく.",
                ],
                "xp": 35,
                "lesson": "3,500 = さんぜんごひゃく. Remember the sound change: 3000 = さんぜん (not さんせん). Combining thousands and hundreds is straightforward once you know the changes.",
                "is_boss": True,
                "flavor": "Sensei tests your mastery of big numbers and sound changes.",
            },
        ],
    },

    # ── Zone 4: Counters ─────────────────────────────────────────────
    "counters": {
        "id": "counters",
        "name": "Counters",
        "description": "Learn essential counters: つ (general), 人 (people), 本 (long things), 枚 (flat things)",
        "level_required": 4,
        "challenges": [
            {
                "id": "counter_tsu",
                "title": "つ — General Counter",
                "type": "quiz",
                "question": "The つ counter uses native Japanese numbers. ひとつ (hitotsu) means: (Romaji: hitotsu)",
                "options": ["One person", "One thing (general)", "One time", "One day"],
                "answer": "b",
                "hints": [
                    "つ is the general-purpose counter for objects.",
                    "ひとつ(1), ふたつ(2), みっつ(3)... up to とお(10).",
                ],
                "xp": 25,
                "lesson": "The つ counter: ひとつ(1), ふたつ(2), みっつ(3), よっつ(4), いつつ(5), むっつ(6), ななつ(7), やっつ(8), ここのつ(9), とお(10). Use when you don't know the specific counter.",
                "is_boss": False,
                "flavor": "Sensei introduces the universal fallback counter.",
            },
            {
                "id": "counter_nin",
                "title": "人 (にん) — People Counter",
                "type": "quiz",
                "question": "さんにん (sannin) means 'three people'. But 'one person' and 'two people' are: (Romaji: nin)",
                "options": ["いちにん and ににん", "ひとり and ふたり (irregular!)", "いちじん and にじん", "ひとにん and ふたにん"],
                "answer": "b",
                "hints": [
                    "1 and 2 people use native Japanese words, not Chinese-origin numbers.",
                    "You learned these in the greetings pack!",
                ],
                "xp": 30,
                "lesson": "People counter 人: ひとり(1), ふたり(2), さんにん(3), よにん(4), ごにん(5)... ひとり and ふたり are irregular -- all others use number + にん.",
                "is_boss": False,
                "flavor": "Sensei reminds you of the irregular people counters.",
            },
            {
                "id": "counter_hon",
                "title": "本 (ほん) — Long Things",
                "type": "quiz",
                "question": "本 (ほん/ぼん/ぽん) counts long, cylindrical objects. Which would you count with 本? (Romaji: hon/bon/pon)",
                "options": ["Pencils, bottles, and umbrellas", "Books and magazines", "Flat papers and tickets", "Round balls and fruits"],
                "answer": "a",
                "hints": [
                    "本 is for long, thin things -- not books (despite the kanji)!",
                    "Pencils, pens, bottles, trees, roads, rivers...",
                ],
                "xp": 30,
                "lesson": "本 counts LONG things: pencils, bottles, umbrellas, trees, roads, movies, phone calls. Sound changes: いっぽん(1), にほん(2), さんぼん(3), よんほん(4)... 1,6,8,10 = ぽん; 3 = ぼん; rest = ほん.",
                "is_boss": False,
                "flavor": "Sensei holds up a pencil, a bottle, and an umbrella -- all use 本.",
            },
            {
                "id": "counter_mai",
                "title": "枚 (まい) — Flat Things",
                "type": "quiz",
                "question": "枚 (まい) counts flat, thin objects. Which would you count with 枚? (Romaji: mai)",
                "options": ["Bottles and pens", "Sheets of paper, tickets, and plates", "People and animals", "Cars and buses"],
                "answer": "b",
                "hints": [
                    "Think FLAT: paper, shirts, CDs, stamps, pizza...",
                    "まい has NO sound changes -- always まい.",
                ],
                "xp": 25,
                "lesson": "枚 (まい) counts flat things: paper, tickets, plates, shirts, CDs, stamps, sliced bread. いちまい(1), にまい(2), さんまい(3)... No sound changes!",
                "is_boss": False,
                "flavor": "Sensei fans out sheets of paper -- いちまい, にまい, さんまい.",
            },
            {
                "id": "counter_practice",
                "title": "Counter Practice",
                "type": "quiz",
                "question": "You want to buy 3 pencils. Which counter do you use?",
                "options": ["さんまい (3 flat things)", "さんぼん (3 long things)", "さんにん (3 people)", "みっつ (3 general)"],
                "answer": "b",
                "hints": [
                    "Pencils are long, thin objects.",
                    "Long things use 本 → three = さんぼん.",
                ],
                "xp": 25,
                "lesson": "Pencils = long things = 本 counter. さんぼん = three (long things). If unsure, みっつ (general counter) is always acceptable, though less precise.",
                "is_boss": False,
                "flavor": "Sensei hands you three pencils to count.",
            },
            {
                "id": "counters_boss",
                "title": "Counter Master",
                "type": "quiz",
                "question": "Match: 'Two tickets, please' = きっぷを _____ おねがいします",
                "options": ["ふたり (futari)", "にまい (nimai)", "にほん (nihon)", "ふたつ (futatsu)"],
                "answer": "b",
                "hints": [
                    "Tickets are flat, thin objects.",
                    "Flat things use 枚 → two = にまい.",
                ],
                "xp": 35,
                "lesson": "きっぷをにまいおねがいします = two tickets please. Tickets are flat → 枚 counter. にまい = 2 flat things. This is real, practical Japanese!",
                "is_boss": True,
                "flavor": "Sensei tests your counter skills at a train station.",
            },
        ],
    },

    # ── Zone 5: Time ─────────────────────────────────────────────────
    "time": {
        "id": "time",
        "name": "Telling Time",
        "description": "Learn to tell time: なんじですか, ~じ, ~ふん",
        "level_required": 5,
        "challenges": [
            {
                "id": "time_nanji",
                "title": "What Time Is It?",
                "type": "quiz",
                "question": "なんじですか (nanji desu ka) means: (Romaji: nanji desu ka)",
                "options": ["What day is it?", "What time is it?", "How old are you?", "What number is it?"],
                "answer": "b",
                "hints": [
                    "なん (nan) = what, じ (ji) = hour/o'clock.",
                    "ですか = is it? (polite question).",
                ],
                "xp": 25,
                "lesson": "なんじですか = what time is it? じ (ji) = o'clock. Answer: [number]じです. Example: さんじです (sanji desu) = it's 3 o'clock.",
                "is_boss": False,
                "flavor": "Sensei points to the clock and asks the time.",
            },
            {
                "id": "time_hours",
                "title": "Hours",
                "type": "quiz",
                "question": "4 o'clock in Japanese is: (Romaji: yoji)",
                "options": ["しじ (shiji)", "よじ (yoji)", "よんじ (yonji)", "しいじ (shiiji)"],
                "answer": "b",
                "hints": [
                    "4 o'clock uses よ, not し or よん.",
                    "よじ is one of the irregular time readings.",
                ],
                "xp": 30,
                "lesson": "Irregular hours: よじ(4), くじ(9). All others regular: いちじ(1), にじ(2), さんじ(3), ごじ(5), ろくじ(6), しちじ(7), はちじ(8), じゅうじ(10), じゅういちじ(11), じゅうにじ(12).",
                "is_boss": False,
                "flavor": "Sensei highlights the tricky hour readings.",
            },
            {
                "id": "time_minutes",
                "title": "Minutes",
                "type": "quiz",
                "question": "Minutes use ふん (fun) or ぷん (pun). 5 minutes is: (Romaji: fun / pun)",
                "options": ["ごふん (gofun)", "ごぷん (gopun)", "いつふん (itsufun)", "ごびょう (gobyou)"],
                "answer": "a",
                "hints": [
                    "5 = ご, minutes = ふん with certain numbers.",
                    "ぷん is used after 1, 3, 4, 6, 8, 10.",
                ],
                "xp": 30,
                "lesson": "Minutes: ふん after 2, 5, 7, 9. ぷん after 1, 3, 4, 6, 8, 10. いっぷん(1), にふん(2), さんぷん(3), よんぷん(4), ごふん(5), ろっぷん(6)...",
                "is_boss": False,
                "flavor": "Sensei explains the ふん/ぷん alternation.",
            },
            {
                "id": "time_half",
                "title": "Half Past",
                "type": "quiz",
                "question": "はん (han) means 'half'. How do you say '3:30'? (Romaji: han)",
                "options": ["さんじはん (sanji han)", "さんじさんじゅっぷん (sanji sanjuppun)", "はんさんじ (hansanji)", "みじはん (miji han)"],
                "answer": "a",
                "hints": [
                    "さんじ (3 o'clock) + はん (half) = 3:30.",
                    "はん always comes after じ.",
                ],
                "xp": 25,
                "lesson": "はん (han) = half past. さんじはん = 3:30. ごじはん = 5:30. Very common in daily conversation. Simpler than counting 30 minutes!",
                "is_boss": False,
                "flavor": "Sensei shows the easy way to express half past.",
            },
            {
                "id": "time_ampm",
                "title": "AM and PM",
                "type": "quiz",
                "question": "ごぜん (gozen) and ごご (gogo) mean: (Romaji: gozen / gogo)",
                "options": ["Morning and evening", "AM and PM", "Early and late", "Before and after"],
                "answer": "b",
                "hints": [
                    "ごぜん = before noon (AM), ごご = after noon (PM).",
                    "They come BEFORE the time: ごぜんくじ = 9 AM.",
                ],
                "xp": 25,
                "lesson": "ごぜん (gozen) = AM, ごご (gogo) = PM. Placed before the time: ごぜんくじ = 9 AM, ごごさんじ = 3 PM. Japan also uses 24-hour time for trains and schedules.",
                "is_boss": False,
                "flavor": "Sensei clarifies the morning and afternoon distinction.",
            },
            {
                "id": "time_boss",
                "title": "Time Master",
                "type": "quiz",
                "question": "Your train leaves at ごごよじじゅうごふん (gogo yoji juugofun). When is that?",
                "options": ["4:15 AM", "4:15 PM", "4:50 PM", "3:15 PM"],
                "answer": "b",
                "hints": [
                    "ごご = PM, よじ = 4 o'clock, じゅうごふん = 15 minutes.",
                    "PM + 4:15 = 4:15 PM.",
                ],
                "xp": 35,
                "lesson": "ごごよじじゅうごふん = 4:15 PM. Breakdown: ごご(PM) + よじ(4 o'clock) + じゅうごふん(15 minutes). You can now catch any train in Japan!",
                "is_boss": True,
                "flavor": "Sensei tests your time-telling with a train schedule.",
            },
        ],
    },

    # ── Zone 6: Money ────────────────────────────────────────────────
    "money": {
        "id": "money",
        "name": "Money & Shopping",
        "description": "Learn about 円 (yen), prices, and shopping phrases",
        "level_required": 6,
        "challenges": [
            {
                "id": "money_en",
                "title": "円 (えん) — Yen",
                "type": "quiz",
                "question": "円 (えん, en) is Japan's currency. ひゃくえん (hyaku en) means: (Romaji: en)",
                "options": ["1 yen", "10 yen", "100 yen", "1000 yen"],
                "answer": "c",
                "hints": [
                    "ひゃく = 100, えん = yen.",
                    "100 yen coins are very common in Japan.",
                ],
                "xp": 25,
                "lesson": "円 (えん) = yen. Japan uses coins: いちえん(1), ごえん(5), じゅうえん(10), ごじゅうえん(50), ひゃくえん(100), ごひゃくえん(500). Bills: せんえん(1000), ごせんえん(5000), いちまんえん(10,000).",
                "is_boss": False,
                "flavor": "Sensei lays out Japanese coins and bills.",
            },
            {
                "id": "money_ikura",
                "title": "How Much?",
                "type": "quiz",
                "question": "いくらですか (ikura desu ka) means: (Romaji: ikura desu ka)",
                "options": ["How many?", "How much (price)?", "How old?", "How far?"],
                "answer": "b",
                "hints": [
                    "いくら (ikura) = how much (price).",
                    "Essential phrase for shopping in Japan.",
                ],
                "xp": 25,
                "lesson": "いくらですか = how much is it? Answer: [number]えんです. Example: さんびゃくえんです (sanbyaku en desu) = it's 300 yen.",
                "is_boss": False,
                "flavor": "Sensei teaches the most important shopping phrase.",
            },
            {
                "id": "money_kudasai",
                "title": "I'll Take This",
                "type": "quiz",
                "question": "これをください (kore o kudasai) means: (Romaji: kore o kudasai)",
                "options": ["What is this?", "Please give me this / I'll take this", "How much is this?", "I don't want this"],
                "answer": "b",
                "hints": [
                    "これ = this, を = object marker, ください = please (give me).",
                    "Point at an item and say this phrase.",
                ],
                "xp": 25,
                "lesson": "これをください = please give me this / I'll take this. Point and say it -- works everywhere in Japan! それ (sore) = that (near you), あれ (are) = that (over there).",
                "is_boss": False,
                "flavor": "Sensei demonstrates the point-and-say technique.",
            },
            {
                "id": "money_100yen",
                "title": "The 100 Yen Shop",
                "type": "quiz",
                "question": "ひゃくえんショップ (hyaku en shoppu) are famous in Japan. Everything costs: (Romaji: hyaku en shoppu)",
                "options": ["10 yen", "100 yen (about $0.70 USD)", "1000 yen", "Free"],
                "answer": "b",
                "hints": [
                    "ひゃく = 100, えん = yen.",
                    "Japan's version of a dollar store.",
                ],
                "xp": 25,
                "lesson": "100 yen shops (ひゃくえんショップ) like Daiso are hugely popular in Japan. 100 yen ≈ $0.70 USD. They sell everything from stationery to kitchen tools.",
                "is_boss": False,
                "flavor": "Sensei takes you on a virtual trip to a 100 yen shop.",
            },
            {
                "id": "money_change",
                "title": "Getting Change",
                "type": "quiz",
                "question": "おつりは にひゃくえんです (otsuri wa nihyaku en desu). おつり means: (Romaji: otsuri)",
                "options": ["Total", "Change (money returned)", "Tax", "Discount"],
                "answer": "b",
                "hints": [
                    "おつり = the money you get back after paying.",
                    "にひゃくえん = 200 yen.",
                ],
                "xp": 30,
                "lesson": "おつり (otsuri) = change (money returned). おつりはにひゃくえんです = your change is 200 yen. Japan is still heavily cash-based, so knowing money vocabulary is essential.",
                "is_boss": False,
                "flavor": "Sensei teaches you about receiving change.",
            },
            {
                "id": "money_boss",
                "title": "Shopping Challenge",
                "type": "quiz",
                "question": "A meal costs せんにひゃくえん (sen nihyaku en). You pay にせんえん (nisen en). What's your change?",
                "options": ["ひゃくえん (100 yen)", "さんびゃくえん (300 yen)", "ごひゃくえん (500 yen)", "はっぴゃくえん (800 yen)"],
                "answer": "d",
                "hints": [
                    "せんにひゃく = 1,200 yen. にせん = 2,000 yen.",
                    "2,000 - 1,200 = ?",
                ],
                "xp": 35,
                "lesson": "2,000 - 1,200 = 800 = はっぴゃくえん. Note the sound change: 800 = はっぴゃく (not はちひゃく). Real math with real Japanese money!",
                "is_boss": True,
                "flavor": "Sensei sets up a real shopping scenario to test your money skills.",
            },
        ],
    },
}
