"""
zones.py — Auth skill pack zones for NEXUS Quest.
Cover the full authentication & identity domain: basics through zero trust.
"""

from engine.zone import Zone
from engine.challenge import Challenge

ZONE_ORDER = [
    "authentication_basics",
    "session_management",
    "oauth2_oidc",
    "api_authentication",
    "zero_trust_modern_auth",
]

ZONES = {
    # ──────────────────────────────────────────────
    # ZONE 1 — AUTHENTICATION BASICS
    # ──────────────────────────────────────────────
    "authentication_basics": Zone(
        id="authentication_basics",
        title="The Front Gate",
        description="Passwords, hashing, bcrypt, salting — the fundamentals of proving identity.",
        challenges=[
            Challenge(
                id="authn_definition",
                type="quiz",
                prompt="What does authentication fundamentally answer?",
                options=[
                    "What resources can this user access?",
                    "Who is this user? Are they who they claim to be?",
                    "How fast can the user connect to the server?",
                    "Where is the user geographically located?",
                ],
                answer="b",
                explanation="Authentication (AuthN) answers the identity question: 'Who are you?' It verifies a claimed identity through credentials. Authorization (AuthZ) is the separate step that determines what that verified identity is allowed to do.",
                hints=["Think about identity verification, not permissions.", "The question is about 'who,' not 'what can they do.'"],
                xp=25,
            ),
            Challenge(
                id="plaintext_passwords",
                type="quiz",
                prompt="A database breach exposes a user table. Passwords were stored in plaintext. What is the immediate consequence?",
                options=[
                    "Attackers can read every user's password directly and use them on other sites where users reused credentials",
                    "The passwords are safe because the database was encrypted at rest",
                    "Only the admin passwords are at risk",
                    "The passwords will expire automatically after the breach",
                ],
                answer="a",
                explanation="Plaintext password storage means every credential is immediately usable by attackers. Combined with password reuse (which is extremely common), a single breach can cascade across dozens of services. This is why passwords must always be hashed — never encrypted, never plaintext.",
                hints=["What can an attacker do if they can literally read the password column?", "Think about credential stuffing attacks."],
                xp=25,
            ),
            Challenge(
                id="hashing_vs_encryption",
                type="quiz",
                prompt="Why should passwords be hashed rather than encrypted?",
                options=[
                    "Hashing is faster than encryption",
                    "Hashing is a one-way function — you can verify a password without ever being able to recover the original, eliminating the risk of key compromise exposing all passwords",
                    "Encryption produces shorter output than hashing",
                    "Hashing allows password recovery via email",
                ],
                answer="b",
                explanation="Hashing is one-way: you cannot reverse a hash back to the original password. Encryption is two-way: whoever has the key can decrypt. If you encrypt passwords and the encryption key is stolen, every password is exposed. With hashing, there is no key to steal — verification works by hashing the input and comparing hashes.",
                hints=["Think about what happens if the key or hash database is stolen.", "One-way vs. two-way is the critical distinction."],
                xp=30,
            ),
            Challenge(
                id="rainbow_table_attack",
                type="quiz",
                prompt="An attacker uses a precomputed table mapping common passwords to their SHA-256 hashes to crack a stolen hash database. This attack is called:",
                options=[
                    "Brute force attack",
                    "Dictionary attack",
                    "Rainbow table attack",
                    "Side-channel attack",
                ],
                answer="c",
                explanation="A rainbow table is a precomputed lookup table of hash values for known passwords. Instead of hashing each guess at runtime, the attacker looks up the stolen hash in the table. This is why salting exists — a unique random salt per password makes precomputed tables useless because the same password produces different hashes.",
                hints=["The key word is 'precomputed table.'", "This attack trades storage space for computation time."],
                xp=30,
            ),
            Challenge(
                id="salt_purpose",
                type="quiz",
                prompt="What is the purpose of a salt in password hashing?",
                options=[
                    "To encrypt the hash so it cannot be read from the database",
                    "To add a unique random value per password so identical passwords produce different hashes, defeating precomputed attacks",
                    "To slow down the hashing algorithm",
                    "To compress the password before hashing",
                ],
                answer="b",
                explanation="A salt is a unique random value generated per password and stored alongside the hash. Even if two users have the same password, their hashes will be different because the salts are different. This defeats rainbow tables and makes batch cracking (cracking many hashes at once) impossible.",
                hints=["Think about what happens if two users have the same password.", "It makes precomputed attacks useless."],
                xp=30,
            ),
            Challenge(
                id="bcrypt_advantage",
                type="quiz",
                prompt="Why is bcrypt preferred over SHA-256 for password hashing?",
                options=[
                    "Bcrypt produces shorter hashes",
                    "Bcrypt is intentionally slow with a configurable work factor and includes a built-in salt, making brute-force attacks computationally expensive",
                    "SHA-256 is cryptographically broken",
                    "Bcrypt can be reversed to recover passwords for account recovery",
                ],
                answer="b",
                explanation="Bcrypt has a cost factor (work factor) that controls how many iterations are performed. At cost 12, a single hash takes ~250ms — fast enough for login, catastrophically slow for brute force. Bcrypt also handles salting automatically. Argon2id is the modern successor, adding memory-hardness to resist GPU attacks.",
                hints=["Speed is the enemy for password hashing.", "Think about what happens when an attacker tries billions of guesses."],
                xp=35,
            ),
            Challenge(
                id="argon2_memory_hard",
                type="text",
                prompt="Argon2id is considered the state-of-the-art password hashing algorithm. What property does it add beyond bcrypt's time-cost, and why does that matter for defending against GPU-based cracking?",
                options=[],
                answer="memory-hardness",
                explanation="Argon2id is memory-hard: it requires a configurable amount of RAM per hash computation. GPUs have many cores but limited per-core memory. A memory-hard function forces attackers to either use enormous amounts of RAM (expensive) or serialize computations (slow), neutralizing the GPU parallelism advantage that makes bcrypt crackable at scale.",
                hints=["Think about the hardware attackers use — GPUs have many cores but limited memory per core.", "The key property starts with 'memory.'"],
                xp=40,
            ),
            Challenge(
                id="credential_stuffing",
                type="quiz",
                prompt="An attacker takes email/password pairs leaked from Site A and tries them on Site B, C, and D. This attack is called:",
                options=[
                    "Phishing — tricking users into revealing credentials",
                    "Credential stuffing — automated reuse of stolen credentials across services",
                    "Brute force — guessing passwords systematically",
                    "Pass-the-hash — using stolen hashes directly for authentication",
                ],
                answer="b",
                explanation="Credential stuffing exploits password reuse. Billions of leaked credentials are available on the dark web. Attackers automate login attempts across popular services. Defenses include rate limiting, CAPTCHA, breached-password detection (like HaveIBeenPwned integration), and encouraging users to use unique passwords via a password manager.",
                hints=["The attack depends on users reusing the same password across sites.", "It's automated and uses real leaked credentials, not guesses."],
                xp=35,
            ),
        ],
    ),

    # ──────────────────────────────────────────────
    # ZONE 2 — SESSION MANAGEMENT
    # ──────────────────────────────────────────────
    "session_management": Zone(
        id="session_management",
        title="The Session Vault",
        description="Cookies, JWTs, refresh tokens, CSRF protection — maintaining authenticated state securely.",
        challenges=[
            Challenge(
                id="session_purpose",
                type="quiz",
                prompt="HTTP is stateless. After a user logs in, how does the server know subsequent requests come from the same authenticated user?",
                options=[
                    "The server remembers the user's IP address",
                    "The server issues a session identifier (cookie or token) that the client sends with every request",
                    "The user re-enters their password with each request",
                    "The browser caches the login page",
                ],
                answer="b",
                explanation="After authentication, the server creates a session and gives the client a session identifier — typically a cookie or token. The client includes this identifier in every subsequent request. The server looks up the session to determine who the user is and what they're authorized to do.",
                hints=["HTTP has no memory between requests.", "Something must be exchanged to maintain state."],
                xp=25,
            ),
            Challenge(
                id="cookie_flags_secure",
                type="quiz",
                prompt="Which cookie flags should be set on a session cookie to prevent it from being sent over unencrypted connections and accessed by JavaScript?",
                options=[
                    "SameSite=Lax and Path=/",
                    "Secure and HttpOnly",
                    "Domain=* and Expires=never",
                    "Max-Age=0 and Priority=High",
                ],
                answer="b",
                explanation="The Secure flag ensures the cookie is only sent over HTTPS, preventing interception on unencrypted connections. The HttpOnly flag prevents JavaScript from reading the cookie via document.cookie, mitigating XSS-based session theft. Both should always be set on session cookies. SameSite is also important but addresses CSRF, not these two threats.",
                hints=["One flag is about transport security, the other about script access.", "Think about the two attack vectors: network sniffing and XSS."],
                xp=30,
            ),
            Challenge(
                id="jwt_structure",
                type="quiz",
                prompt="A JSON Web Token (JWT) consists of three parts separated by dots. What are they?",
                options=[
                    "Username, password, and timestamp",
                    "Header, payload, and signature",
                    "Public key, private key, and certificate",
                    "Issuer, audience, and expiration",
                ],
                answer="b",
                explanation="A JWT is header.payload.signature, each Base64URL-encoded. The header specifies the algorithm (e.g., RS256). The payload contains claims (sub, iat, exp, custom data). The signature is created by signing header+payload with a secret (HMAC) or private key (RSA/ECDSA). The signature lets the server verify the token wasn't tampered with.",
                hints=["Think about the three dot-separated segments you see in a JWT.", "One part says how it's signed, one holds data, one proves integrity."],
                xp=30,
            ),
            Challenge(
                id="jwt_none_algorithm",
                type="quiz",
                prompt="An attacker modifies a JWT's header to set the algorithm to 'none' and removes the signature. If the server accepts it, what vulnerability is being exploited?",
                options=[
                    "SQL injection in the token parsing logic",
                    "The 'alg: none' vulnerability — the server fails to enforce signature verification",
                    "A timing attack on the signature comparison",
                    "Buffer overflow in the Base64 decoder",
                ],
                answer="b",
                explanation="The JWT spec allows alg:'none' for unsecured tokens. If a server naively reads the algorithm from the token header and honors 'none,' an attacker can forge any token by stripping the signature. The fix: never accept 'none' as an algorithm; always validate against a server-side allowlist of expected algorithms.",
                hints=["The attacker is telling the server to skip verification.", "The vulnerability is in trusting the token's own claim about how to verify it."],
                xp=35,
            ),
            Challenge(
                id="refresh_token_pattern",
                type="quiz",
                prompt="An application uses short-lived access tokens (15 min) and long-lived refresh tokens (7 days). Why use two tokens instead of one long-lived access token?",
                options=[
                    "Two tokens are harder for attackers to steal than one",
                    "Short-lived access tokens limit the window of exploitation if stolen, while refresh tokens allow session continuity and can be revoked server-side",
                    "Refresh tokens are encrypted while access tokens are not",
                    "The two-token pattern is required by the OAuth 2.0 specification",
                ],
                answer="b",
                explanation="Access tokens are sent with every API request, increasing exposure. If stolen, a 15-minute token limits damage. Refresh tokens are only sent to the token endpoint, reducing exposure. They can be stored in a server-side allowlist and revoked instantly. This pattern balances security (short exposure window) with UX (no constant re-login).",
                hints=["Think about the blast radius if each token type is stolen.", "One is used frequently (high exposure), the other rarely (low exposure)."],
                xp=35,
            ),
            Challenge(
                id="csrf_attack",
                type="quiz",
                prompt="A user is logged into their bank. They visit a malicious site that contains <img src='https://bank.com/transfer?to=attacker&amount=10000'>. What attack is this?",
                options=[
                    "XSS — Cross-Site Scripting",
                    "CSRF — Cross-Site Request Forgery",
                    "Clickjacking — UI redress attack",
                    "SSRF — Server-Side Request Forgery",
                ],
                answer="b",
                explanation="CSRF exploits the browser's automatic inclusion of cookies with cross-origin requests. The user's bank session cookie is sent with the malicious request, authenticating it as the legitimate user. Defenses: CSRF tokens (unique per-session values the attacker can't guess), SameSite cookie attribute, and requiring non-GET methods for state changes.",
                hints=["The browser automatically sends cookies — even from a different site.", "The attacker forges a request that rides on the victim's session."],
                xp=35,
            ),
            Challenge(
                id="samesite_cookie",
                type="quiz",
                prompt="Setting SameSite=Strict on a session cookie prevents it from being sent on which type of requests?",
                options=[
                    "Only AJAX requests from JavaScript",
                    "Any cross-site request — the cookie is only sent when the request originates from the same site as the cookie's domain",
                    "Requests over HTTP (non-HTTPS) only",
                    "Requests that include a Referer header",
                ],
                answer="b",
                explanation="SameSite=Strict means the cookie is never sent on cross-site requests — not even when clicking a link from another site to yours. SameSite=Lax is less restrictive: cookies are sent on top-level navigations (clicking links) but not on cross-site subrequests (images, iframes, AJAX). Lax is the default in modern browsers and prevents most CSRF.",
                hints=["'Same site' means the request originates from the same domain.", "Think about what 'Strict' means literally — no exceptions for cross-site."],
                xp=30,
            ),
            Challenge(
                id="session_fixation",
                type="text",
                prompt="In a session fixation attack, the attacker sets a known session ID in the victim's browser before the victim logs in. What is the critical server-side defense against this attack?",
                options=[],
                answer="regenerate the session ID after authentication",
                explanation="Session fixation works because the pre-login session ID survives authentication. The attacker knows the ID, so after the victim logs in, the attacker can use that same ID to hijack the session. The defense is simple: always regenerate (rotate) the session ID immediately after successful authentication. The old ID becomes invalid.",
                hints=["The problem is that the session ID doesn't change when the user's privilege level changes.", "What should happen to the session identifier at the moment of login?"],
                xp=40,
            ),
        ],
    ),

    # ──────────────────────────────────────────────
    # ZONE 3 — OAUTH 2.0 & OPENID CONNECT
    # ──────────────────────────────────────────────
    "oauth2_oidc": Zone(
        id="oauth2_oidc",
        title="The Trust Broker",
        description="OAuth 2.0 flows, scopes, PKCE, ID tokens — delegated authorization and federated identity.",
        challenges=[
            Challenge(
                id="oauth2_purpose",
                type="quiz",
                prompt="OAuth 2.0 is primarily a protocol for:",
                options=[
                    "Encrypting data in transit between client and server",
                    "Delegated authorization — allowing a third-party app to access resources on behalf of a user without sharing the user's password",
                    "Storing passwords securely in a database",
                    "Establishing a VPN tunnel between two services",
                ],
                answer="b",
                explanation="OAuth 2.0 solves the delegation problem: how can a user grant a third-party application limited access to their resources (e.g., Google Drive files) without giving that app their Google password? The answer: the user authenticates with the resource owner directly and an access token with limited scope is issued to the third party.",
                hints=["Think about 'Sign in with Google' — does the third-party app ever see your Google password?", "The key word is 'delegated.'"],
                xp=25,
            ),
            Challenge(
                id="authorization_code_flow",
                type="quiz",
                prompt="In the OAuth 2.0 Authorization Code flow, what is exchanged for an access token?",
                options=[
                    "The user's username and password",
                    "A short-lived authorization code received after user consent",
                    "The client's TLS certificate",
                    "A refresh token from a previous session",
                ],
                answer="b",
                explanation="The Authorization Code flow is the most secure standard flow. The user authenticates with the authorization server and consents. A short-lived authorization code is sent to the client's redirect URI. The client exchanges this code (plus its client secret) for an access token via a back-channel request. The access token never passes through the browser.",
                hints=["The flow has two steps: get a code, then exchange it for a token.", "The code is a one-time intermediary — not the final credential."],
                xp=30,
            ),
            Challenge(
                id="oauth2_scopes",
                type="quiz",
                prompt="An OAuth 2.0 access token is issued with scope 'read:email read:profile'. What does this mean?",
                options=[
                    "The token can access any resource on the server",
                    "The token is limited to reading the user's email and profile — it cannot write data or access other resources",
                    "The token is valid for reading emails and profiles of all users",
                    "The scope is just a label with no enforcement",
                ],
                answer="b",
                explanation="Scopes define the boundaries of an access token's permissions. They implement the principle of least privilege for delegated access. The resource server must enforce scopes — rejecting requests that exceed the token's granted permissions. A token with 'read:email' cannot modify the email or access other resources.",
                hints=["Scopes are the 'what can this token do' boundary.", "Think of them as granular permissions granted by the user."],
                xp=30,
            ),
            Challenge(
                id="pkce_purpose",
                type="quiz",
                prompt="PKCE (Proof Key for Code Exchange) was introduced to protect the Authorization Code flow against:",
                options=[
                    "Man-in-the-middle attacks on HTTPS connections",
                    "Authorization code interception — where an attacker captures the code before the legitimate client can exchange it",
                    "Brute force attacks on the client secret",
                    "SQL injection in the authorization server",
                ],
                answer="b",
                explanation="In mobile/SPA apps, the authorization code passes through the OS or browser where it can be intercepted. PKCE adds a cryptographic challenge: the client generates a random code_verifier, sends its SHA-256 hash (code_challenge) with the auth request, then proves possession of the original code_verifier during token exchange. An intercepted code is useless without the verifier.",
                hints=["PKCE protects the code exchange step specifically.", "Think about mobile apps where the redirect URI can be intercepted by a malicious app."],
                xp=35,
            ),
            Challenge(
                id="oidc_vs_oauth",
                type="quiz",
                prompt="What does OpenID Connect (OIDC) add on top of OAuth 2.0?",
                options=[
                    "Encryption of access tokens",
                    "An identity layer — it adds authentication (ID tokens) to OAuth 2.0's authorization framework",
                    "A replacement for refresh tokens",
                    "Server-to-server authentication via mutual TLS",
                ],
                answer="b",
                explanation="OAuth 2.0 is about authorization — it issues access tokens but doesn't standardize identity. OIDC adds an identity layer: the ID token (a JWT containing user identity claims like sub, email, name). OIDC also standardizes a UserInfo endpoint and discovery mechanism. 'Sign in with Google' is OIDC — you get both an access token (for API access) and an ID token (for identity).",
                hints=["OAuth 2.0 tells you what the user allowed, not who the user is.", "The key addition is the ID token."],
                xp=35,
            ),
            Challenge(
                id="id_token_validation",
                type="quiz",
                prompt="When your application receives an ID token from an OIDC provider, which of these validations is critical before trusting it?",
                options=[
                    "Check that the token is longer than 256 characters",
                    "Verify the signature, check the issuer (iss) matches your OIDC provider, and confirm the audience (aud) matches your client ID",
                    "Decode the token and check that it contains a password field",
                    "Ensure the token was sent over HTTP for compatibility",
                ],
                answer="b",
                explanation="ID token validation must verify: (1) the signature is valid (using the provider's public keys from the JWKS endpoint), (2) the issuer (iss) is your expected provider, (3) the audience (aud) includes your client ID (preventing token misuse across apps), (4) the token hasn't expired (exp), and (5) the nonce matches if one was sent. Skipping any of these enables token forgery or replay.",
                hints=["Think about what an attacker could forge if you skip each check.", "The audience claim prevents tokens meant for App A from being used at App B."],
                xp=35,
            ),
            Challenge(
                id="implicit_flow_deprecated",
                type="quiz",
                prompt="The OAuth 2.0 Implicit flow returns the access token directly in the browser URL fragment. Why is this flow now discouraged?",
                options=[
                    "It requires the user to enter their password twice",
                    "The access token is exposed in the browser history, URL bar, and potentially to JavaScript on the page, making it vulnerable to token leakage",
                    "It doesn't support refresh tokens, which is an inconvenience but not a security issue",
                    "It only works with OIDC, not standard OAuth 2.0",
                ],
                answer="b",
                explanation="The Implicit flow was designed for SPAs that couldn't make back-channel requests. But exposing tokens in URLs means they appear in browser history, server logs (via Referer headers), and are accessible to any JavaScript on the page (including injected scripts). The modern recommendation is Authorization Code + PKCE, even for SPAs.",
                hints=["Think about everywhere a URL fragment might be logged or leaked.", "The problem is where the token physically appears."],
                xp=30,
            ),
            Challenge(
                id="token_exchange_pattern",
                type="text",
                prompt="In a microservices architecture, Service A receives a user's access token and needs to call Service B on behalf of that user. What OAuth 2.0 pattern allows Service A to exchange the user's token for a new token scoped to Service B?",
                options=[],
                answer="token exchange",
                explanation="OAuth 2.0 Token Exchange (RFC 8693) allows a service to present a token it received and request a new token with different audience/scope for a downstream service. This avoids passing the original broad-scope token to every service and supports the principle of least privilege across the service mesh. The alternative, token relay (forwarding the same token), is simpler but less secure.",
                hints=["The service needs a new token specifically for the downstream call.", "There's an RFC specifically for this pattern — exchanging one token for another."],
                xp=40,
            ),
        ],
    ),

    # ──────────────────────────────────────────────
    # ZONE 4 — API AUTHENTICATION
    # ──────────────────────────────────────────────
    "api_authentication": Zone(
        id="api_authentication",
        title="The Machine Gate",
        description="API keys, bearer tokens, mutual TLS, HMAC signatures — authenticating machines and services.",
        challenges=[
            Challenge(
                id="api_key_risks",
                type="quiz",
                prompt="API keys are commonly used for service authentication. What is their primary security weakness compared to OAuth 2.0 tokens?",
                options=[
                    "API keys are too short to be secure",
                    "API keys are long-lived shared secrets with no built-in expiration, scoping, or revocation mechanism, and they're frequently leaked in code repositories",
                    "API keys cannot be transmitted over HTTPS",
                    "API keys are only supported by REST APIs",
                ],
                answer="b",
                explanation="API keys are static shared secrets — they don't expire, they can't be scoped to specific operations (without custom logic), and they're the #1 secret leaked in public GitHub repos. OAuth 2.0 tokens are short-lived, scoped, and rotatable. API keys are appropriate for identifying a project (like a Maps API key) but not as the sole authentication mechanism for sensitive operations.",
                hints=["Think about what happens when an API key is accidentally committed to a public repo.", "Compare the lifecycle: API keys are static; tokens are dynamic."],
                xp=25,
            ),
            Challenge(
                id="bearer_token_usage",
                type="quiz",
                prompt="An HTTP request includes the header 'Authorization: Bearer eyJhbGciOi...'. What does 'Bearer' mean in this context?",
                options=[
                    "The token is encrypted with the bearer's public key",
                    "Whoever bears (possesses) this token is granted access — no additional proof of identity is required",
                    "The token can only be used by the original bearer who requested it",
                    "Bearer is a deprecated authentication scheme replaced by Basic",
                ],
                answer="b",
                explanation="Bearer authentication means the token itself is the credential — anyone who possesses it can use it. This is why bearer tokens must be protected in transit (HTTPS) and storage. Unlike PoP (Proof of Possession) tokens, there's no cryptographic binding between the token and the client. If intercepted, a bearer token can be replayed.",
                hints=["Think about the literal meaning of 'bearer' — the one who carries it.", "What happens if someone else gets a copy of this token?"],
                xp=30,
            ),
            Challenge(
                id="mtls_authentication",
                type="quiz",
                prompt="In mutual TLS (mTLS), both the client and server present certificates. What does this achieve that standard TLS does not?",
                options=[
                    "Faster encryption through symmetric key exchange",
                    "The server authenticates the client's identity, not just the other way around — both parties prove who they are",
                    "Protection against DDoS attacks",
                    "Compression of HTTP payloads for faster transmission",
                ],
                answer="b",
                explanation="Standard TLS authenticates the server to the client (you verify the bank's certificate). Mutual TLS adds client authentication — the server verifies the client's certificate too. This is commonly used in service-to-service communication (service mesh), API gateways, and zero-trust architectures where every connection must prove both identities cryptographically.",
                hints=["Standard TLS is one-way authentication. What does 'mutual' add?", "Both sides prove identity, not just the server."],
                xp=35,
            ),
            Challenge(
                id="hmac_signature",
                type="quiz",
                prompt="An API requires clients to sign requests using HMAC-SHA256 with a shared secret. What does the signature prove?",
                options=[
                    "That the request body is encrypted and cannot be read",
                    "That the request originated from someone who possesses the shared secret and that the request has not been tampered with in transit",
                    "That the client's IP address is trusted",
                    "That the request was sent over HTTPS",
                ],
                answer="b",
                explanation="An HMAC signature proves two things: (1) authenticity — only someone with the shared secret could produce the correct signature, and (2) integrity — any modification to the signed content (headers, body, timestamp) invalidates the signature. AWS Signature V4 and Stripe webhook verification both use this pattern. Including a timestamp in the signed content prevents replay attacks.",
                hints=["HMAC requires a secret to produce — and to verify.", "Think about both who sent it and whether it was modified."],
                xp=35,
            ),
            Challenge(
                id="api_key_header_vs_url",
                type="quiz",
                prompt="Why should API keys be sent in an HTTP header (e.g., X-API-Key) rather than as a URL query parameter?",
                options=[
                    "Headers are encrypted but query parameters are not",
                    "Query parameters appear in server access logs, browser history, and Referer headers, increasing the risk of key leakage",
                    "URL query parameters have a 50-character limit",
                    "HTTP headers are faster to parse than query parameters",
                ],
                answer="b",
                explanation="URLs (including query parameters) are logged by web servers, proxy servers, CDNs, and browser history. They also leak via the Referer header when following links. HTTP headers are not included in these logs by default. Over HTTPS, both headers and query parameters are encrypted in transit — but the URL is logged in many more places than headers.",
                hints=["Think about everywhere a URL gets stored or forwarded.", "The security issue is about logging and leakage, not encryption."],
                xp=30,
            ),
            Challenge(
                id="jwt_vs_opaque_token",
                type="quiz",
                prompt="An opaque access token (random string) requires the resource server to call the authorization server for validation. A JWT access token does not. What is the tradeoff?",
                options=[
                    "JWTs are more secure because they're encrypted",
                    "JWTs enable stateless validation (no network call) but cannot be instantly revoked, while opaque tokens require a network call but support immediate revocation",
                    "Opaque tokens are faster because they're shorter",
                    "There is no meaningful difference — they're interchangeable",
                ],
                answer="b",
                explanation="JWTs are self-contained — the resource server can validate them locally by checking the signature and expiration. No database or network call needed. The tradeoff: you can't revoke a JWT before expiration without maintaining a blocklist (defeating the stateless benefit). Opaque tokens must be introspected (network call to the auth server) but can be revoked instantly by deleting them from the store.",
                hints=["Think about what 'stateless' means for revocation.", "If the token contains its own validity proof, who do you call to invalidate it?"],
                xp=35,
            ),
            Challenge(
                id="service_account_auth",
                type="text",
                prompt="In the OAuth 2.0 Client Credentials grant, there is no user involved. What type of authentication scenario is this grant designed for, and what does the client exchange for an access token?",
                options=[],
                answer="service-to-service authentication using client ID and client secret",
                explanation="The Client Credentials grant is for machine-to-machine (service-to-service) authentication where no human user is involved. The client authenticates directly with the authorization server using its client_id and client_secret (or a signed JWT assertion) and receives an access token scoped to the service's own permissions — not any user's permissions.",
                hints=["No user login screen — this is machine identity.", "The client authenticates as itself, not on behalf of a user."],
                xp=35,
            ),
            Challenge(
                id="request_signing_replay",
                type="text",
                prompt="An API uses HMAC request signing for authentication. An attacker captures a valid signed request and replays it 30 minutes later. What mechanism prevents this replay attack?",
                options=[],
                answer="timestamp in the signed content with a server-side time window check",
                explanation="By including a timestamp in the signed content and rejecting requests where the timestamp is outside an acceptable window (e.g., +/- 5 minutes), replay attacks are mitigated. The signature binds the timestamp to the request — the attacker cannot change the timestamp without invalidating the signature. Additionally, a nonce (unique per-request ID) can be checked against a short-lived cache to prevent replays within the time window.",
                hints=["The attacker can't modify any part of the signed request without breaking the signature.", "What time-based check would make an old request invalid?"],
                xp=40,
            ),
        ],
    ),

    # ──────────────────────────────────────────────
    # ZONE 5 — ZERO TRUST & MODERN AUTH
    # ──────────────────────────────────────────────
    "zero_trust_modern_auth": Zone(
        id="zero_trust_modern_auth",
        title="The Identity Nexus",
        description="Passkeys, FIDO2, SSO, MFA, identity providers — the future of authentication.",
        challenges=[
            Challenge(
                id="zero_trust_principle",
                type="quiz",
                prompt="The core principle of Zero Trust architecture is:",
                options=[
                    "Trust internal network traffic but verify external traffic",
                    "Never trust, always verify — authenticate and authorize every request regardless of network location",
                    "Use a single firewall to protect all internal services",
                    "Encrypt all data but trust authenticated users completely",
                ],
                answer="b",
                explanation="Zero Trust eliminates the concept of a trusted internal network. Every request — even from inside the corporate network — must be authenticated, authorized, and encrypted. Identity becomes the new perimeter, not the network. Continuous verification (device health, user behavior, request context) replaces the castle-and-moat model.",
                hints=["The name says it: zero trust. Not 'some trust' or 'internal trust.'", "Network location is no longer a proxy for trust."],
                xp=25,
            ),
            Challenge(
                id="passkeys_overview",
                type="quiz",
                prompt="Passkeys (based on FIDO2/WebAuthn) replace passwords with cryptographic key pairs. Where is the private key stored?",
                options=[
                    "On the server in an encrypted database",
                    "On the user's device (phone, laptop, or security key) — it never leaves the device",
                    "In the browser's localStorage",
                    "In a shared secret between client and server",
                ],
                answer="b",
                explanation="Passkeys use public-key cryptography. The private key is generated and stored in the device's secure hardware (TPM, Secure Enclave, or security key). The server only stores the public key. During authentication, the device signs a challenge with the private key, and the server verifies it with the public key. The private key never leaves the device — there's no shared secret to steal from the server.",
                hints=["Think public-key cryptography: one key stays, one key goes.", "The server never has the secret material."],
                xp=30,
            ),
            Challenge(
                id="fido2_phishing_resistance",
                type="quiz",
                prompt="Why are FIDO2/WebAuthn passkeys considered phishing-resistant?",
                options=[
                    "They use longer passwords that are harder to guess",
                    "The credential is cryptographically bound to the origin (domain) — a fake site on a different domain cannot trigger the correct credential",
                    "They require a VPN connection to authenticate",
                    "They encrypt the user's email to prevent phishing emails",
                ],
                answer="b",
                explanation="WebAuthn credentials are origin-bound: a passkey created for bank.com will only respond to challenges from bank.com. If an attacker creates a phishing site at bank-secure.com, the authenticator won't find a matching credential. This is a fundamental improvement over passwords and TOTP, which the user can accidentally enter on any site.",
                hints=["The authenticator checks the website's actual domain, not what the page claims to be.", "Phishing works by impersonating a domain — what if the credential itself knows the real domain?"],
                xp=35,
            ),
            Challenge(
                id="mfa_totp_mechanism",
                type="quiz",
                prompt="A TOTP (Time-based One-Time Password) app generates a 6-digit code that changes every 30 seconds. What inputs does the algorithm use?",
                options=[
                    "The user's password and the current time",
                    "A shared secret (established during setup) and the current time, processed through HMAC-SHA1",
                    "The server's IP address and a random seed",
                    "The user's biometric data and a hardware serial number",
                ],
                answer="b",
                explanation="TOTP (RFC 6238) takes a shared secret (the QR code you scan during setup) and the current Unix timestamp divided by the time step (30 seconds). These are fed into HMAC-SHA1 to produce a hash, from which 6 digits are extracted. Both the server and the app compute the same code independently — no network communication needed during verification.",
                hints=["You scan a QR code once during setup — that establishes the shared input.", "The code changes with time — so time must be an input."],
                xp=30,
            ),
            Challenge(
                id="sso_saml_vs_oidc",
                type="quiz",
                prompt="Enterprise Single Sign-On (SSO) commonly uses either SAML 2.0 or OpenID Connect. What is a key architectural difference?",
                options=[
                    "SAML is more secure than OIDC in all cases",
                    "SAML uses XML-based assertions and browser redirects; OIDC uses JSON/JWT tokens and is built on OAuth 2.0, making it lighter and more API-friendly",
                    "OIDC only works with Google; SAML works with all providers",
                    "SAML is for authentication; OIDC is only for authorization",
                ],
                answer="b",
                explanation="SAML 2.0 (2005) uses XML assertions, XML signatures, and browser POST/redirect bindings. OIDC (2014) uses JSON Web Tokens, REST APIs, and OAuth 2.0 infrastructure. OIDC is generally preferred for new applications — especially mobile and SPA — due to its simplicity. SAML remains dominant in enterprise environments with existing IdP infrastructure.",
                hints=["Think about the era each was designed in: XML-era vs. JSON/REST-era.", "One is built on OAuth 2.0, the other predates it."],
                xp=30,
            ),
            Challenge(
                id="idp_role",
                type="quiz",
                prompt="In a federated identity system, what is the role of an Identity Provider (IdP)?",
                options=[
                    "To store application data and serve API requests",
                    "To authenticate users and issue identity assertions (tokens/assertions) that Service Providers (relying parties) trust",
                    "To encrypt all network traffic between services",
                    "To monitor application performance and uptime",
                ],
                answer="b",
                explanation="An Identity Provider (IdP) like Okta, Azure AD, or Auth0 is the authoritative source for user authentication. When a user accesses a Service Provider (SP/relying party), the SP delegates authentication to the IdP. The IdP authenticates the user and issues a signed assertion (SAML) or ID token (OIDC) that the SP trusts. This enables SSO — authenticate once at the IdP, access many SPs.",
                hints=["The IdP is the 'source of truth' for identity.", "Service Providers delegate the 'who are you?' question to the IdP."],
                xp=30,
            ),
            Challenge(
                id="mfa_fatigue_attack",
                type="quiz",
                prompt="In an MFA fatigue (push bombing) attack, the attacker repeatedly triggers push notifications to the victim's phone. What is the most effective defense?",
                options=[
                    "Increase the push notification timeout to 60 seconds",
                    "Require number matching — the user must enter a number displayed on the login screen into their authenticator app, not just tap 'approve'",
                    "Switch to SMS-based MFA",
                    "Disable MFA for the affected account temporarily",
                ],
                answer="b",
                explanation="MFA fatigue exploits simple approve/deny push notifications — the victim eventually taps 'approve' out of frustration or confusion. Number matching (used by Microsoft Authenticator, Duo, etc.) requires the user to see a number on the login screen and enter it in the app. An attacker triggering pushes remotely doesn't know the number. Phishing-resistant methods (FIDO2) are even better.",
                hints=["The attack works because 'approve' requires no context about which login is being authenticated.", "What if the user had to prove they could see the login screen?"],
                xp=35,
            ),
            Challenge(
                id="step_up_authentication",
                type="text",
                prompt="A user browses their account dashboard with a standard session. When they attempt to change their password or initiate a wire transfer, the application requires them to re-authenticate with a stronger factor. What is this pattern called?",
                options=[],
                answer="step-up authentication",
                explanation="Step-up authentication (or adaptive authentication) escalates the authentication strength based on the sensitivity of the action. Browsing might require a session cookie; changing a password might require re-entering the password; initiating a financial transfer might require MFA. This balances security and usability — routine actions are frictionless while sensitive actions demand stronger proof.",
                hints=["The authentication requirement 'steps up' based on what you're trying to do.", "Think about how banks require extra verification for transfers but not for checking your balance."],
                xp=40,
            ),
        ],
    ),
}
