"""
zones.py — Writing zones and challenges for The Writer's Workshop skill pack.

All challenges use "type": "quiz" or "type": "text".
Designed for ages 5-12, guided warmly by Puck.
"""

ZONE_ORDER = [
    "sentences_capitalization",
    "punctuation_power",
    "parts_of_story",
    "descriptive_writing",
    "writing_for_purpose",
]

ZONES = {
    # ──────────────────────────────────────────────
    #  ZONE 1 — Sentences & Capitalization
    # ──────────────────────────────────────────────
    "sentences_capitalization": {
        "id": "sentences_capitalization",
        "name": "Sentences & Capitalization",
        "description": "Learn what makes a complete sentence and when to use capital letters",
        "level_required": 1,
        "challenges": [
            {
                "id": "sc_complete1",
                "title": "Complete or Not?",
                "type": "quiz",
                "question": "Which of these is a COMPLETE sentence?",
                "options": ["Running in the park.", "The dog ran fast.", "Under the big tree.", "Happy and excited."],
                "answer": "b",
                "hints": [
                    "A complete sentence needs a WHO (subject) and a WHAT THEY DID (verb).",
                    "Look for the one that tells you WHO did WHAT.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A complete sentence has two parts: a subject (who or what) and a predicate (what they did). 'The dog ran fast' tells us WHO (the dog) and WHAT THEY DID (ran fast)!",
                "is_boss": False,
                "flavor": "Puck holds up a puzzle with two pieces — one says WHO, the other says WHAT THEY DID. 'Snap them together and you get a sentence!'",
            },
            {
                "id": "sc_capital1",
                "title": "Capital Start",
                "type": "quiz",
                "question": "Which sentence uses capital letters correctly?",
                "options": ["the cat sat on the mat.", "The Cat sat on the Mat.", "The cat sat on the mat.", "the Cat Sat on the mat."],
                "answer": "c",
                "hints": [
                    "Only the FIRST word of a sentence needs a capital letter.",
                    "Regular words in the middle of a sentence stay lowercase.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Every sentence starts with a capital letter! But words in the middle of a sentence stay lowercase — unless they're a name or special word. 'The cat sat on the mat.' is perfect!",
                "is_boss": False,
                "flavor": "Puck waves a tiny flag with a big letter T on it. 'Every sentence gets to start with a capital — it's like wearing a crown!'",
            },
            {
                "id": "sc_names1",
                "title": "Name That Capital",
                "type": "quiz",
                "question": "Which word in this sentence should have a capital letter? 'My friend emma loves to paint.'",
                "options": ["friend", "emma", "loves", "paint"],
                "answer": "b",
                "hints": [
                    "People's names are special — they always get capital letters.",
                    "Which word is somebody's name?",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Names of people ALWAYS start with a capital letter. Emma is a name, so it should be 'Emma' with a capital E. This rule goes for pet names, city names, and country names too!",
                "is_boss": False,
                "flavor": "Puck pulls out a golden stamp and presses a capital E onto the name. 'Names deserve to stand tall!'",
            },
            {
                "id": "sc_fragment1",
                "title": "Fix the Fragment",
                "type": "text",
                "question": "This is NOT a complete sentence: 'Because it was raining.' Can you turn it into a complete sentence? Type a full sentence that includes this idea.",
                "options": [],
                "answer": "stayed inside because it was raining",
                "hints": [
                    "Add a subject and an action to the beginning. WHO did WHAT because it was raining?",
                    "Try something like: 'We stayed inside because...'",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "'Because it was raining' is a FRAGMENT — it's missing the main action. Adding 'We stayed inside' gives it a subject and a verb, making it complete. Fragments need a partner to become sentences!",
                "is_boss": False,
                "flavor": "Puck picks up the lonely fragment and looks for its missing piece. 'Every fragment is just a sentence that lost its other half!'",
            },
            {
                "id": "sc_capital2",
                "title": "Days and Months",
                "type": "quiz",
                "question": "Which sentence uses capital letters correctly?",
                "options": [
                    "We have a picnic on saturday.",
                    "We have a picnic on Saturday.",
                    "we have a Picnic on saturday.",
                    "We have a Picnic on Saturday.",
                ],
                "answer": "b",
                "hints": [
                    "Days of the week are special words — they always get capitals!",
                    "But regular words like 'picnic' don't need a capital in the middle of a sentence.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Days of the week (Monday, Tuesday...) and months of the year (January, February...) ALWAYS start with a capital letter. They're proper nouns — names for specific days and months!",
                "is_boss": False,
                "flavor": "Puck flips through a calendar where every day and month name wears a tiny crown. 'These words are VIPs — Very Important Proper nouns!'",
            },
            {
                "id": "sc_sentence_type1",
                "title": "Statement or Question?",
                "type": "quiz",
                "question": "Which of these is a STATEMENT (a telling sentence)?",
                "options": ["Where is my book?", "Did you eat lunch?", "The sun is shining today.", "Can we go outside?"],
                "answer": "c",
                "hints": [
                    "A statement TELLS you something. It doesn't ask.",
                    "Which one gives you information instead of asking for it?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A statement is a sentence that TELLS something. It ends with a period. A question is a sentence that ASKS something and ends with a question mark. 'The sun is shining today' tells us a fact!",
                "is_boss": False,
                "flavor": "Puck holds up two signs — one says TELL and one says ASK. 'Every sentence is doing one or the other!'",
            },
            {
                "id": "sc_order1",
                "title": "Word Jumble",
                "type": "text",
                "question": "Put these words in order to make a correct sentence: 'park the played We in'. Type the complete sentence with correct capitalization and a period.",
                "options": [],
                "answer": "We played in the park.",
                "hints": [
                    "Start with WHO did the action. Which word should come first?",
                    "The sentence should tell you WHO played WHERE.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Sentences follow an order: usually WHO + DID WHAT + WHERE/WHEN. 'We played in the park' puts the subject first, then the action, then where it happened. And don't forget the capital W and the period!",
                "is_boss": False,
                "flavor": "Puck juggles the jumbled words in the air and then catches them in the right order. 'Sentences have a rhythm — WHO, WHAT, WHERE!'",
            },
            {
                "id": "sc_boss",
                "title": "The Sentence Architect",
                "type": "text",
                "question": "Write a complete sentence about your favourite animal. It must start with a capital letter, end with a period, and include a subject (who/what) and a verb (what they do).",
                "options": [],
                "answer": "complete sentence about an animal",
                "hints": [
                    "Pick an animal you love. What does it do? Now tell me!",
                    "Try this pattern: 'My favourite [animal] likes to [action].'",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "You just built a perfect sentence from scratch! It has a subject, a verb, a capital letter at the start, and a period at the end. That's the foundation of ALL writing — and you've nailed it!",
                "is_boss": True,
                "flavor": "Puck unveils a tiny architect's table and hands you a golden pen. 'Build me a sentence — your very own creation!'",
            },
        ],
    },

    # ──────────────────────────────────────────────
    #  ZONE 2 — Punctuation Power
    # ──────────────────────────────────────────────
    "punctuation_power": {
        "id": "punctuation_power",
        "name": "Punctuation Power",
        "description": "Master periods, commas, question marks, and exclamation points",
        "level_required": 2,
        "challenges": [
            {
                "id": "pp_period1",
                "title": "The Full Stop",
                "type": "quiz",
                "question": "What punctuation mark goes at the end of this sentence? 'The bird flew over the tree'",
                "options": ["Question mark (?)", "Exclamation point (!)", "Period (.)", "Comma (,)"],
                "answer": "c",
                "hints": [
                    "This sentence is TELLING you something calmly. It's not asking or shouting.",
                    "Calm, telling sentences end with a...",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A period (.) goes at the end of a statement — a sentence that calmly tells you something. 'The bird flew over the tree.' No question, no excitement — just a fact. Period!",
                "is_boss": False,
                "flavor": "Puck drops a tiny dot at the end of the sentence. 'Small but mighty — the period is the stop sign of writing!'",
            },
            {
                "id": "pp_question1",
                "title": "Ask Away",
                "type": "quiz",
                "question": "Which sentence needs a QUESTION MARK at the end?",
                "options": ["I like pizza", "What time is it", "She ran to school", "The sky is blue"],
                "answer": "b",
                "hints": [
                    "Which sentence is ASKING something?",
                    "Question words include: what, where, when, who, why, how.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Question marks (?) go at the end of sentences that ASK something. 'What time is it?' is asking for information. Tip: sentences that start with who, what, where, when, why, or how are usually questions!",
                "is_boss": False,
                "flavor": "Puck curls into the shape of a question mark. 'I'm the mark that means TELL ME MORE!'",
            },
            {
                "id": "pp_exclamation1",
                "title": "Shout It Out!",
                "type": "quiz",
                "question": "Which sentence should end with an EXCLAMATION POINT?",
                "options": ["The cat is sleeping.", "What is your name?", "Watch out for that car!", "I went to the store."],
                "answer": "c",
                "hints": [
                    "An exclamation point shows strong feeling — excitement, surprise, or urgency.",
                    "Which sentence sounds like someone is shouting or warning?",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Exclamation points (!) show strong emotion — excitement, surprise, fear, or urgency. 'Watch out for that car!' is urgent and important. When feelings are BIG, use an exclamation point!",
                "is_boss": False,
                "flavor": "Puck jumps up with a big exclamation point. 'I show up when feelings are LOUD!'",
            },
            {
                "id": "pp_comma_list1",
                "title": "The List Separator",
                "type": "quiz",
                "question": "Which sentence uses commas correctly in a list?",
                "options": [
                    "I packed apples bananas and grapes.",
                    "I packed apples, bananas, and grapes.",
                    "I packed, apples bananas and, grapes.",
                    "I, packed apples bananas and grapes.",
                ],
                "answer": "b",
                "hints": [
                    "In a list of three or more things, commas go BETWEEN each item.",
                    "The pattern is: item, item, and item.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When you list three or more things, put a comma between each one. The pattern is: first thing, second thing, and last thing. 'Apples, bananas, and grapes' — commas keep your list neat and clear!",
                "is_boss": False,
                "flavor": "Puck lines up three fruits and places tiny commas between them. 'Commas are the spacers that keep lists from becoming a jumble!'",
            },
            {
                "id": "pp_mixed1",
                "title": "Pick the Punctuation",
                "type": "quiz",
                "question": "What punctuation goes at the end? 'Have you ever seen a shooting star'",
                "options": ["Period (.)", "Question mark (?)", "Exclamation point (!)", "Comma (,)"],
                "answer": "b",
                "hints": [
                    "Read it out loud. Is it telling, asking, or shouting?",
                    "It starts with 'Have you' — that's a clue!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Sentences starting with 'Have you,' 'Do you,' 'Can you,' 'Is it,' and similar phrases are almost always questions. 'Have you ever seen a shooting star?' — question mark for sure!",
                "is_boss": False,
                "flavor": "Puck gazes up at a shooting star streaking across the page. 'Even stars can inspire a question!'",
            },
            {
                "id": "pp_comma_pause1",
                "title": "The Pause Comma",
                "type": "quiz",
                "question": "Where does the comma go in this sentence? 'After the rain stopped we went outside.'",
                "options": [
                    "After 'After'",
                    "After 'rain'",
                    "After 'stopped'",
                    "After 'we'",
                ],
                "answer": "c",
                "hints": [
                    "Read it out loud. Where do you naturally pause?",
                    "The comma goes after the opening part, before the main action.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When a sentence starts with an introductory phrase (like 'After the rain stopped'), put a comma after it, before the main part. The comma marks the pause: 'After the rain stopped, we went outside.'",
                "is_boss": False,
                "flavor": "Puck holds up a tiny pause button. 'Commas are breath marks — they tell your reader where to pause!'",
            },
            {
                "id": "pp_fix1",
                "title": "Punctuation Repair",
                "type": "text",
                "question": "This sentence is missing its punctuation mark: 'What a beautiful sunset' What punctuation should go at the end? Type the full sentence with the correct mark.",
                "options": [],
                "answer": "What a beautiful sunset!",
                "hints": [
                    "Is this asking a question, or expressing a strong feeling?",
                    "'What a beautiful...' shows amazement and excitement!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Even though it starts with 'What,' this isn't a question — it's an exclamation of wonder! 'What a beautiful sunset!' expresses strong feeling. Not every sentence starting with 'what' is a question!",
                "is_boss": False,
                "flavor": "Puck watches a gorgeous sunset paint the page in gold and orange. 'Sometimes words are so full of feeling they need an exclamation point!'",
            },
            {
                "id": "pp_boss",
                "title": "The Punctuation Master",
                "type": "quiz",
                "question": "Read this: 'Wow I cant believe we won the game did you see that amazing goal' How many punctuation marks does this passage need (periods, commas, question marks, or exclamation points)?",
                "options": ["1", "2", "3", "4"],
                "answer": "c",
                "hints": [
                    "Break it into separate sentences. How many thoughts are there?",
                    "There are three sentences: 'Wow, I can't believe we won the game!' + 'Did you see that amazing goal?' — that's an exclamation, a period or exclamation, and a question mark.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "This passage has three sentences crammed together! 'Wow!' (exclamation) 'I can't believe we won the game!' (exclamation) 'Did you see that amazing goal?' (question). Three end marks needed — punctuation brings order to chaos!",
                "is_boss": True,
                "flavor": "Puck faces a wall of words with no punctuation at all. 'It's a punctuation emergency! Only a true master can sort this out!'",
            },
        ],
    },

    # ──────────────────────────────────────────────
    #  ZONE 3 — Parts of a Story
    # ──────────────────────────────────────────────
    "parts_of_story": {
        "id": "parts_of_story",
        "name": "Parts of a Story",
        "description": "Learn how stories are built: beginning, middle, end, characters, and setting",
        "level_required": 3,
        "challenges": [
            {
                "id": "ps_beginning1",
                "title": "Once Upon a Time",
                "type": "quiz",
                "question": "What usually happens at the BEGINNING of a story?",
                "options": [
                    "The problem gets solved",
                    "We meet the characters and learn the setting",
                    "The most exciting part happens",
                    "The story ends happily",
                ],
                "answer": "b",
                "hints": [
                    "Think about what you need to know FIRST when a story starts.",
                    "Before anything can happen, you need to know WHO and WHERE.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The BEGINNING of a story introduces the characters (who the story is about) and the setting (where and when it happens). It sets the stage so you know who to follow and where the adventure takes place!",
                "is_boss": False,
                "flavor": "Puck opens a brand-new storybook to the first page. 'Every great adventure starts with two questions: WHO and WHERE!'",
            },
            {
                "id": "ps_middle1",
                "title": "The Exciting Middle",
                "type": "quiz",
                "question": "What usually happens in the MIDDLE of a story?",
                "options": [
                    "We meet the characters for the first time",
                    "The story ends",
                    "A problem or challenge appears and the characters try to solve it",
                    "The title is introduced",
                ],
                "answer": "c",
                "hints": [
                    "The middle is where the ACTION happens!",
                    "Characters face something difficult and try to overcome it.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The MIDDLE is where the excitement lives! A problem or challenge appears, and the characters try to solve it. This is the longest part of the story — full of action, surprises, and suspense!",
                "is_boss": False,
                "flavor": "Puck flips to the middle of the book, where the pages are practically vibrating with action. 'This is where things get interesting!'",
            },
            {
                "id": "ps_end1",
                "title": "The End",
                "type": "quiz",
                "question": "What usually happens at the END of a story?",
                "options": [
                    "New characters are introduced",
                    "The problem gets worse with no solution",
                    "The problem is solved and we learn how things turn out",
                    "The setting changes completely",
                ],
                "answer": "c",
                "hints": [
                    "The end wraps things up. What happens to the problem?",
                    "After all the excitement, the ending tells us HOW IT ALL TURNED OUT.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The END of a story is where the problem gets solved (or sometimes doesn't!) and we learn how everything turned out. It's the wrap-up — the final piece of the puzzle that makes the whole story complete.",
                "is_boss": False,
                "flavor": "Puck turns to the last page and sighs happily. 'Endings are like the last piece of a jigsaw puzzle — everything clicks into place!'",
            },
            {
                "id": "ps_character1",
                "title": "Character Clues",
                "type": "quiz",
                "question": "Read this: 'Maya shared her lunch with the new girl who forgot hers, even though Maya was hungry too.' What does this tell us about Maya?",
                "options": ["She is selfish", "She is kind and generous", "She doesn't like food", "She is scared"],
                "answer": "b",
                "hints": [
                    "Maya shared her lunch even though she was hungry. What kind of person does that?",
                    "Sharing when you don't have to is a sign of...",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "We learn about characters through their ACTIONS. Maya shared her lunch even when she was hungry — that action shows us she's kind and generous. What characters DO tells us WHO THEY ARE!",
                "is_boss": False,
                "flavor": "Puck watches Maya hand over her sandwich and smiles. 'Actions speak louder than words — especially in stories!'",
            },
            {
                "id": "ps_setting1",
                "title": "Setting the Scene",
                "type": "text",
                "question": "Read this: 'Snow covered the ground. Icicles hung from the rooftops. Children bundled in scarves and mittens ran down the street.' What SEASON is this story set in? Type your answer.",
                "options": [],
                "answer": "winter",
                "hints": [
                    "Snow, icicles, scarves, and mittens — what season has all of these?",
                    "It's cold, white, and frosty!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Authors don't always SAY the setting directly — they describe it with details. Snow, icicles, scarves, and mittens all point to WINTER. Good readers use description clues to figure out the setting!",
                "is_boss": False,
                "flavor": "Puck shivers as snowflakes drift off the page. 'The author painted winter without ever saying the word!'",
            },
            {
                "id": "ps_problem1",
                "title": "What's the Problem?",
                "type": "quiz",
                "question": "Read this: 'Leo wanted to play in the football match, but he had twisted his ankle that morning. He watched his friends run onto the field.' What is Leo's problem?",
                "options": [
                    "He doesn't like football",
                    "His friends won't let him play",
                    "He hurt his ankle and can't play",
                    "It's raining outside",
                ],
                "answer": "c",
                "hints": [
                    "Leo WANTS to play but something is stopping him. What happened that morning?",
                    "A twisted ankle makes it hard to...",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Every story has a PROBLEM (also called a conflict). Leo's problem is that he wants to play football but his twisted ankle won't let him. Problems drive the story forward — they give characters something to overcome!",
                "is_boss": False,
                "flavor": "Puck sits on the sideline next to Leo, both of them looking longingly at the field. 'Every hero has a problem to solve!'",
            },
            {
                "id": "ps_order1",
                "title": "Story Order",
                "type": "quiz",
                "question": "Put these story events in the correct order: (1) The dragon was defeated. (2) A brave knight set out on a journey. (3) The knight found a dragon guarding a castle.",
                "options": ["1, 2, 3", "3, 2, 1", "2, 3, 1", "2, 1, 3"],
                "answer": "c",
                "hints": [
                    "What has to happen FIRST? The knight needs to start the journey before finding anything.",
                    "Beginning: sets out. Middle: finds the dragon. End: defeats the dragon.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Stories follow a logical order: BEGINNING (the knight sets out), MIDDLE (finds the dragon), END (defeats the dragon). Events happen in a sequence — each one leads to the next. That's called the PLOT!",
                "is_boss": False,
                "flavor": "Puck lines up three storybook pages and shuffles them. 'First this, then this, then THIS — stories are a chain of events!'",
            },
            {
                "id": "ps_boss",
                "title": "The Story Builder",
                "type": "text",
                "question": "Write the BEGINNING of a short story (2-3 sentences). It should introduce a character (who), a setting (where), and a problem. Example: 'Sam was a curious cat who lived in a bakery. One morning, all the cupcakes disappeared!'",
                "options": [],
                "answer": "story beginning with character setting and problem",
                "hints": [
                    "Pick a character — a person or animal. Where are they? What goes wrong?",
                    "Try this pattern: [Character] lived in [setting]. One day, [problem].",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "You just wrote the beginning of a real story! You introduced a character, set the scene, and created a problem. That's EXACTLY how every great author starts — you're thinking like a writer now!",
                "is_boss": True,
                "flavor": "Puck hands you a glowing quill. 'Every story in the world started with someone writing a beginning — just like you're about to do!'",
            },
        ],
    },

    # ──────────────────────────────────────────────
    #  ZONE 4 — Descriptive Writing
    # ──────────────────────────────────────────────
    "descriptive_writing": {
        "id": "descriptive_writing",
        "name": "Descriptive Writing",
        "description": "Paint pictures with words using adjectives, similes, and sensory details",
        "level_required": 4,
        "challenges": [
            {
                "id": "dw_adjective1",
                "title": "Word Paintbrush",
                "type": "quiz",
                "question": "Which sentence uses an ADJECTIVE (a describing word) to make the picture more vivid?",
                "options": [
                    "The dog sat down.",
                    "The fluffy golden dog sat down.",
                    "The dog sat down quickly.",
                    "The dog sat down here.",
                ],
                "answer": "b",
                "hints": [
                    "Adjectives describe WHAT something looks like, sounds like, or feels like.",
                    "Which sentence tells you more about the dog's appearance?",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Adjectives are describing words that make your writing more vivid. 'Fluffy' and 'golden' are adjectives that paint a picture of the dog. Without them, we just see 'a dog' — with them, we see a fluffy golden dog!",
                "is_boss": False,
                "flavor": "Puck dips a paintbrush into the sentence and adds colour — suddenly the plain dog on the page becomes fluffy and golden. 'Adjectives are a writer's paintbrush!'",
            },
            {
                "id": "dw_adjective2",
                "title": "Add Some Colour",
                "type": "text",
                "question": "Make this sentence more descriptive by adding at least TWO adjectives: 'The castle stood on the hill.' Type your improved sentence.",
                "options": [],
                "answer": "adjectives describing the castle or hill",
                "hints": [
                    "Think about the castle — is it tall? Old? Crumbling? Dark? And what about the hill — steep? Green? Misty?",
                    "Try: 'The [adjective] [adjective] castle stood on the [adjective] hill.'",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Adding adjectives transforms flat sentences into vivid pictures. 'The ancient stone castle stood on the misty hill' lets the reader SEE the scene. Every adjective adds another brushstroke to your word painting!",
                "is_boss": False,
                "flavor": "Puck points at the plain castle on the page. 'Give me details! What does it LOOK like? Make me see it!'",
            },
            {
                "id": "dw_simile1",
                "title": "Like What?",
                "type": "quiz",
                "question": "Which sentence contains a SIMILE (a comparison using 'like' or 'as')?",
                "options": [
                    "The stars were bright.",
                    "The stars twinkled like diamonds in the sky.",
                    "I could see many stars.",
                    "Stars are made of gas.",
                ],
                "answer": "b",
                "hints": [
                    "A simile compares two different things using the word 'like' or 'as'.",
                    "Which sentence says something is LIKE something else?",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A simile compares two different things using 'like' or 'as.' Stars aren't really diamonds, but saying they 'twinkled like diamonds' helps you picture how bright and sparkly they were. Similes make writing magical!",
                "is_boss": False,
                "flavor": "Puck holds up a diamond next to a star. 'Similes say: THIS thing is like THAT thing — and suddenly both things make more sense!'",
            },
            {
                "id": "dw_simile2",
                "title": "Simile Creator",
                "type": "text",
                "question": "Finish this simile: 'The thunder was as loud as ___.' Type something that is very loud to complete the comparison.",
                "options": [],
                "answer": "a loud comparison",
                "hints": [
                    "What's something REALLY loud? A drum? A lion's roar? An explosion?",
                    "Think of the loudest thing you can imagine!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Similes work by comparing something to another thing we can easily imagine. 'As loud as a drum,' 'as loud as a lion's roar' — these help readers HEAR the thunder in their minds. Your comparison creates a picture!",
                "is_boss": False,
                "flavor": "Puck covers its ears as thunder rumbles across the page. 'Compare it to something — make me HEAR how loud it is!'",
            },
            {
                "id": "dw_senses1",
                "title": "Five Senses",
                "type": "quiz",
                "question": "Which sentence uses the sense of SMELL to describe a scene?",
                "options": [
                    "The market was crowded with people.",
                    "The aroma of fresh bread drifted from the bakery.",
                    "The building was very tall.",
                    "It was a sunny afternoon.",
                ],
                "answer": "b",
                "hints": [
                    "The five senses are: sight, hearing, smell, taste, and touch.",
                    "Which sentence talks about something you can SMELL?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Great writers use ALL five senses — not just sight! 'The aroma of fresh bread drifted from the bakery' uses SMELL to put you right there in the scene. When you write, ask yourself: what would I see, hear, smell, taste, and feel?",
                "is_boss": False,
                "flavor": "Puck sniffs the air as the scent of warm bread floats off the page. 'Writing isn't just about what you SEE — it's about what you smell, hear, taste, and touch too!'",
            },
            {
                "id": "dw_senses2",
                "title": "Sensory Snapshot",
                "type": "text",
                "question": "Describe a beach using at least TWO different senses (sight, hearing, smell, taste, or touch). Write 1-2 sentences.",
                "options": [],
                "answer": "beach description using two or more senses",
                "hints": [
                    "Close your eyes and imagine a beach. What do you SEE? HEAR? FEEL under your feet? SMELL?",
                    "Try: 'The warm sand tickled my toes (touch) as waves crashed on the shore (hearing).'",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Using multiple senses makes your writing come alive! Instead of just telling the reader about a beach, you put them ON the beach — feeling the sand, hearing the waves, smelling the salt air. That's the power of sensory writing!",
                "is_boss": False,
                "flavor": "Puck sets up a tiny beach on the page — sand, waves, seagulls. 'Use your senses to bring this place to life!'",
            },
            {
                "id": "dw_show1",
                "title": "Show, Don't Tell",
                "type": "quiz",
                "question": "Which sentence SHOWS that a character is scared (instead of just telling)?",
                "options": [
                    "Ella was scared.",
                    "Ella's hands trembled and her heart pounded as she peered into the dark room.",
                    "Ella felt a little scared.",
                    "Ella was the most scared she had ever been.",
                ],
                "answer": "b",
                "hints": [
                    "'Show, don't tell' means describing what the character DOES or FEELS physically, not just naming the emotion.",
                    "Which sentence makes you FEEL the fear?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "'Show, don't tell' is a writer's golden rule. Instead of saying 'Ella was scared,' SHOW the fear: trembling hands, pounding heart, peering into darkness. Showing makes the reader FEEL the emotion!",
                "is_boss": False,
                "flavor": "Puck shivers dramatically. 'Don't TELL me you're scared — SHOW me! Make my fur stand on end!'",
            },
            {
                "id": "dw_boss",
                "title": "The Word Painter",
                "type": "text",
                "question": "Describe a thunderstorm in 2-3 sentences. Use at least one adjective, one simile (using 'like' or 'as'), and one sensory detail (sound, sight, smell, or touch).",
                "options": [],
                "answer": "thunderstorm description with adjective simile and sensory detail",
                "hints": [
                    "Think about what a thunderstorm looks like, sounds like, and feels like. Use 'like' or 'as' somewhere!",
                    "Try: 'The dark sky rumbled like a hungry giant. Rain hammered on the roof and cold wind stung my face.'",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "You just combined adjectives, similes, and sensory details in one description — that's the toolkit of a real writer! Adjectives add colour, similes create comparisons, and sensory details put the reader right in the storm. Masterful!",
                "is_boss": True,
                "flavor": "Puck stands in a swirling storm on the page, lightning flashing. 'Paint this storm with words — I want to FEEL the rain and HEAR the thunder!'",
            },
        ],
    },

    # ──────────────────────────────────────────────
    #  ZONE 5 — Writing for a Purpose
    # ──────────────────────────────────────────────
    "writing_for_purpose": {
        "id": "writing_for_purpose",
        "name": "Writing for a Purpose",
        "description": "Write letters, lists, instructions, and invitations for real-world purposes",
        "level_required": 5,
        "challenges": [
            {
                "id": "wp_letter1",
                "title": "Dear Friend",
                "type": "quiz",
                "question": "What is the correct way to start a friendly letter?",
                "options": [
                    "Hey! So anyway,",
                    "Dear Grandma,",
                    "GRANDMA!!!!",
                    "To whom it may concern,",
                ],
                "answer": "b",
                "hints": [
                    "A friendly letter starts with a greeting. The most common one is 'Dear [name],'",
                    "It should feel warm but still polite!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Friendly letters start with a greeting: 'Dear [name],' — with a comma after the name. It's warm, polite, and tells the reader the letter is for THEM. Every letter has a greeting, a body, and a closing!",
                "is_boss": False,
                "flavor": "Puck pulls out a piece of fancy stationery and a feather quill. 'Letters are conversations on paper — and every conversation starts with a hello!'",
            },
            {
                "id": "wp_letter2",
                "title": "Letter Ending",
                "type": "quiz",
                "question": "Which is the correct way to END a friendly letter?",
                "options": [
                    "THE END.",
                    "Your friend, \nAlex",
                    "bye bye bye bye",
                    "SINCERELY YOURS TRULY FOREVER,",
                ],
                "answer": "b",
                "hints": [
                    "Letters end with a closing (like 'Your friend,') and then your name on the next line.",
                    "It should match the friendly tone of the letter.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Letters end with a CLOSING ('Your friend,' 'Love,' 'Sincerely,') followed by your name. The closing has a comma after it and your name goes on the next line. It's like saying goodbye at the end of a visit!",
                "is_boss": False,
                "flavor": "Puck signs the bottom of a letter with a flourish. 'The closing is your wave goodbye — make it warm!'",
            },
            {
                "id": "wp_list1",
                "title": "List It!",
                "type": "quiz",
                "question": "You're packing for a camping trip. Which list is organized BEST?",
                "options": [
                    "tent sleeping bag flashlight snacks water",
                    "Tent, Sleeping bag, Flashlight, Snacks, Water",
                    "Things to bring:\n• Tent\n• Sleeping bag\n• Flashlight\n• Snacks\n• Water",
                    "I need a tent and a sleeping bag and a flashlight and snacks and water",
                ],
                "answer": "c",
                "hints": [
                    "A good list has a TITLE that tells you what the list is for, and each item on its own line.",
                    "Which option is easiest to read and check off?",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A well-organized list has a clear TITLE and each item on its own line with a bullet point or number. This makes it easy to read and check off items. Lists are one of the most useful types of writing in real life!",
                "is_boss": False,
                "flavor": "Puck pulls out a scroll that unrolls into a perfect checklist. 'Lists keep life organized — and the best lists are clear and simple!'",
            },
            {
                "id": "wp_instructions1",
                "title": "Step by Step",
                "type": "quiz",
                "question": "You're writing instructions for making a peanut butter sandwich. What should come FIRST?",
                "options": [
                    "Eat the sandwich.",
                    "Spread peanut butter on one slice.",
                    "Get two slices of bread, a knife, and peanut butter.",
                    "Put the two slices together.",
                ],
                "answer": "c",
                "hints": [
                    "Before you can DO anything, you need to GATHER what you need.",
                    "Instructions always start with what you need before the steps.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Good instructions start with what you NEED (materials/ingredients) before the steps. You can't spread peanut butter if you haven't gotten the bread and knife first! Order matters in instructions!",
                "is_boss": False,
                "flavor": "Puck assembles sandwich ingredients on a tiny table. 'Instructions are a recipe for success — but only if you start at the beginning!'",
            },
            {
                "id": "wp_instructions2",
                "title": "Order Matters",
                "type": "quiz",
                "question": "Which set of instructions is in the CORRECT order for brushing your teeth?",
                "options": [
                    "1. Rinse your mouth. 2. Put toothpaste on the brush. 3. Brush your teeth.",
                    "1. Brush your teeth. 2. Put toothpaste on the brush. 3. Rinse your mouth.",
                    "1. Put toothpaste on the brush. 2. Brush your teeth. 3. Rinse your mouth.",
                    "1. Rinse your mouth. 2. Brush your teeth. 3. Put toothpaste on the brush.",
                ],
                "answer": "c",
                "hints": [
                    "Think about what you do every morning. What comes first, second, third?",
                    "You need toothpaste on the brush BEFORE you brush!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Instructions must be in the right ORDER or they won't work! You can't brush before putting on toothpaste, and you rinse AFTER brushing. When you write instructions, imagine doing each step — does the order make sense?",
                "is_boss": False,
                "flavor": "Puck mimes brushing teeth in the wrong order and gets toothpaste everywhere. 'See what happens when steps are out of order?!'",
            },
            {
                "id": "wp_invitation1",
                "title": "You're Invited!",
                "type": "quiz",
                "question": "What information MUST be included in a party invitation?",
                "options": [
                    "Just the date",
                    "The date, time, and place",
                    "Just your name",
                    "A list of games you'll play",
                ],
                "answer": "b",
                "hints": [
                    "If someone invited you to a party, what would you NEED to know to get there?",
                    "You'd need to know WHEN and WHERE!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Every invitation needs the essential information: WHAT (the event), WHEN (date and time), and WHERE (the place). Without any of these, your guests won't know where to go or when to show up!",
                "is_boss": False,
                "flavor": "Puck holds up a sparkly invitation with blank spaces. 'An invitation without a date or place is just a pretty piece of paper!'",
            },
            {
                "id": "wp_invitation2",
                "title": "Write the Invite",
                "type": "text",
                "question": "Write a short invitation for a birthday party. Include: what the event is, the date, the time, and the place. (You can make up the details!)",
                "options": [],
                "answer": "invitation with event date time and place",
                "hints": [
                    "Start with an exciting line like 'You're invited to...' Then add the date, time, and place.",
                    "Try: 'You're invited to [name]'s birthday party! Date: [date]. Time: [time]. Place: [place].'",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "You just wrote a real invitation! It has everything a guest needs: the event, date, time, and place. Writing for a purpose means making sure your reader gets all the information they need. That's practical writing power!",
                "is_boss": False,
                "flavor": "Puck scatters confetti across the page. 'Now THAT'S an invitation that'll make people want to come!'",
            },
            {
                "id": "wp_boss",
                "title": "The Purpose Master",
                "type": "text",
                "question": "Your friend is sick and missed school. Write a short friendly letter (3-4 sentences) telling them what they missed and wishing them well. Start with 'Dear' and end with a closing and your name.",
                "options": [],
                "answer": "friendly letter with greeting body and closing",
                "hints": [
                    "Start with 'Dear [friend's name],' — then tell them what happened at school, and wish them well.",
                    "End with something like 'Your friend,' followed by your name.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "You just wrote a complete friendly letter with a greeting, body, and closing — AND it had a real PURPOSE: to help and comfort a friend. The best writing isn't just correct — it DOES something meaningful. You're a true writer now!",
                "is_boss": True,
                "flavor": "Puck seals the letter with a wax stamp and smiles. 'This letter has heart. It's not just writing — it's kindness on paper. That's what the best writing always is.'",
            },
        ],
    },
}
