"""
zones.py — Databases skill pack zones for NEXUS Quest.
Cover the full database stack: fundamentals through security.
"""

from engine.zone import Zone
from engine.challenge import Challenge

ZONE_ORDER = [
    "database_fundamentals",
    "sql_mastery",
    "nosql_world",
    "database_design",
    "migrations_and_versioning",
    "replication_and_scaling",
    "backup_and_recovery",
    "database_security",
]

ZONES = {
    # ──────────────────────────────────────────────
    # ZONE 1 — DATABASE FUNDAMENTALS
    # ──────────────────────────────────────────────
    "database_fundamentals": Zone(
        id="database_fundamentals",
        title="The Foundation Layer",
        description="Relational vs NoSQL, ACID properties, CAP theorem, schemas, and choosing the right database.",
        challenges=[
            Challenge(
                id="db_relational_definition",
                type="quiz",
                prompt="What is the defining characteristic of a relational database?",
                options=[
                    "Data is stored as JSON documents with flexible schemas",
                    "Data is organized into tables with rows and columns, linked by relationships and keys",
                    "Data is stored as key-value pairs in memory for sub-millisecond access",
                    "Data is stored as nodes and edges in a graph structure",
                ],
                answer="b",
                explanation="Relational databases (PostgreSQL, MySQL, Oracle) organize data into tables (relations) with defined columns (attributes) and rows (tuples). Tables are linked through primary and foreign keys, enabling powerful JOIN operations across related data.",
                hints=["Think about the word 'relational' — it describes how data is connected.", "Tables, rows, columns, keys — the building blocks of SQL databases."],
                xp=25,
            ),
            Challenge(
                id="db_acid_acronym",
                type="quiz",
                prompt="What does ACID stand for in database transactions?",
                options=[
                    "Asynchronous, Consistent, Isolated, Durable",
                    "Atomic, Concurrent, Indexed, Distributed",
                    "Atomicity, Consistency, Isolation, Durability",
                    "Automated, Centralized, Immutable, Decoupled",
                ],
                answer="c",
                explanation="ACID guarantees reliable transactions: Atomicity (all-or-nothing), Consistency (valid state transitions), Isolation (concurrent transactions don't interfere), Durability (committed data survives crashes). These properties are the backbone of relational database reliability.",
                hints=["Each letter represents a guarantee about how transactions behave.", "The 'A' means a transaction either fully completes or fully rolls back."],
                xp=25,
            ),
            Challenge(
                id="db_cap_theorem",
                type="quiz",
                prompt="The CAP theorem states that a distributed database can guarantee at most two of three properties simultaneously. Which three?",
                options=[
                    "Compression, Availability, Performance",
                    "Consistency, Availability, Partition tolerance",
                    "Concurrency, Atomicity, Persistence",
                    "Caching, Authentication, Parallelism",
                ],
                answer="b",
                explanation="CAP theorem (Brewer's theorem): in a distributed system, you can have at most two of Consistency (every read gets the latest write), Availability (every request gets a response), and Partition tolerance (system works despite network splits). Since network partitions are inevitable, real systems choose between CP (e.g., MongoDB) and AP (e.g., Cassandra).",
                hints=["This theorem is about trade-offs in distributed systems.", "Network partitions are unavoidable — so the real choice is between C and A."],
                xp=30,
            ),
            Challenge(
                id="db_schema_vs_schemaless",
                type="quiz",
                prompt="What is the primary advantage of a schema-on-write (relational) approach over schema-on-read (NoSQL)?",
                options=[
                    "Faster write throughput because no validation is needed",
                    "Data integrity is enforced at write time — invalid data is rejected before it enters the system",
                    "Horizontal scaling is simpler because data has no constraints",
                    "Schema-on-write allows storing any data format without migration",
                ],
                answer="b",
                explanation="Schema-on-write enforces structure at insertion: column types, NOT NULL constraints, foreign keys, and CHECK constraints ensure only valid data enters the database. Schema-on-read (common in document stores) pushes validation to the application layer, offering flexibility at the cost of data quality guarantees.",
                hints=["Think about when validation happens — at write time or read time.", "Relational databases reject bad data before it's stored."],
                xp=30,
            ),
            Challenge(
                id="db_when_to_use_nosql",
                type="quiz",
                prompt="Which scenario is the BEST fit for a NoSQL document database over a traditional RDBMS?",
                options=[
                    "A banking system requiring strict transaction guarantees across multiple accounts",
                    "A content management system where each article has varying metadata fields and nested structures",
                    "A payroll system with strict regulatory reporting requirements",
                    "An accounting ledger requiring double-entry bookkeeping with referential integrity",
                ],
                answer="b",
                explanation="Document databases (MongoDB, DynamoDB) excel when data is semi-structured, varies between records, and is typically accessed as a whole document. A CMS where articles have different metadata, embedded media, and nested tags is a natural fit. Banking and accounting need ACID transactions and strict schemas — relational territory.",
                hints=["Which scenario has the most variability in data structure?", "Document databases shine when each record can have different fields."],
                xp=35,
            ),
            Challenge(
                id="db_oltp_vs_olap",
                type="quiz",
                prompt="What is the key difference between OLTP and OLAP database workloads?",
                options=[
                    "OLTP uses SQL; OLAP uses NoSQL",
                    "OLTP handles many short read/write transactions; OLAP handles complex analytical queries over large datasets",
                    "OLTP is for cloud databases; OLAP is for on-premise databases",
                    "OLTP stores data in columns; OLAP stores data in rows",
                ],
                answer="b",
                explanation="OLTP (Online Transaction Processing) handles high volumes of short, simple transactions — inserts, updates, lookups (e.g., an e-commerce checkout). OLAP (Online Analytical Processing) handles complex queries aggregating large datasets — reports, dashboards, trend analysis. Different workloads, different optimizations: row-store for OLTP, column-store for OLAP.",
                hints=["The T stands for Transaction, the A stands for Analytical.", "Think about a cash register vs. a quarterly business report."],
                xp=30,
            ),
        ],
    ),

    # ──────────────────────────────────────────────
    # ZONE 2 — SQL MASTERY
    # ──────────────────────────────────────────────
    "sql_mastery": Zone(
        id="sql_mastery",
        title="The Query Forge",
        description="SELECT, JOIN, GROUP BY, HAVING, subqueries, indexes, query planning, and EXPLAIN.",
        challenges=[
            Challenge(
                id="sql_join_types",
                type="quiz",
                prompt="What does a LEFT JOIN return?",
                options=[
                    "Only rows that have matching values in both tables",
                    "All rows from the left table, plus matched rows from the right table (NULLs where no match exists)",
                    "All rows from the right table, plus matched rows from the left table",
                    "The Cartesian product of both tables",
                ],
                answer="b",
                explanation="LEFT JOIN (LEFT OUTER JOIN) returns every row from the left table. For rows with a match in the right table, the joined columns are filled in. For rows without a match, the right-side columns are NULL. This is essential for finding records that exist in one table but not another.",
                hints=["The 'left' table is always fully included.", "Unmatched rows from the right side become NULLs."],
                xp=25,
            ),
            Challenge(
                id="sql_group_by_having",
                type="quiz",
                prompt="What is the difference between WHERE and HAVING in a SQL query?",
                options=[
                    "WHERE filters rows before aggregation; HAVING filters groups after aggregation",
                    "WHERE is used with SELECT; HAVING is used with INSERT",
                    "WHERE works on text columns; HAVING works on numeric columns",
                    "They are interchangeable — HAVING is just an alias for WHERE",
                ],
                answer="a",
                explanation="WHERE filters individual rows before GROUP BY runs. HAVING filters aggregated groups after GROUP BY. Example: WHERE salary > 50000 excludes rows; HAVING COUNT(*) > 5 excludes groups with too few members. You cannot use aggregate functions in WHERE — that's what HAVING is for.",
                hints=["One operates on rows, the other on groups.", "Think about the order of operations: WHERE runs first, then GROUP BY, then HAVING."],
                xp=30,
            ),
            Challenge(
                id="sql_subquery_vs_join",
                type="quiz",
                prompt="When is a correlated subquery executed?",
                options=[
                    "Once, before the outer query runs",
                    "Once for each row of the outer query, referencing columns from the outer row",
                    "Only when the database cannot use an index",
                    "Only during INSERT operations, never during SELECT",
                ],
                answer="b",
                explanation="A correlated subquery references columns from the outer query, so it must re-execute for each outer row. Example: SELECT * FROM employees e WHERE salary > (SELECT AVG(salary) FROM employees WHERE dept = e.dept). This is powerful but can be slow — a JOIN or window function often performs better.",
                hints=["'Correlated' means the subquery depends on the outer query.", "It runs repeatedly — once per row in the outer result set."],
                xp=35,
            ),
            Challenge(
                id="sql_index_purpose",
                type="quiz",
                prompt="What is the primary purpose of a database index?",
                options=[
                    "To enforce unique constraints on columns",
                    "To speed up data retrieval by creating a sorted lookup structure that avoids full table scans",
                    "To compress data and reduce storage requirements",
                    "To automatically back up table data",
                ],
                answer="b",
                explanation="An index (typically a B-tree) creates an ordered structure that lets the database find rows without scanning every page. Like a book index — instead of reading every page to find 'TCP', you look up 'TCP' in the index and jump to the right page. Indexes speed reads but slow writes (the index must be updated too).",
                hints=["Think of the index at the back of a textbook.", "It trades write speed for read speed."],
                xp=25,
            ),
            Challenge(
                id="sql_explain_plan",
                type="quiz",
                prompt="What does EXPLAIN (or EXPLAIN ANALYZE) show you in PostgreSQL?",
                options=[
                    "The table schema and column data types",
                    "The query execution plan — how the database will (or did) retrieve the data, including scan types, join methods, and costs",
                    "The list of indexes available on the queried tables",
                    "The transaction isolation level and lock status",
                ],
                answer="b",
                explanation="EXPLAIN shows the query planner's chosen execution plan: sequential scan vs. index scan, nested loop vs. hash join, estimated rows and costs. EXPLAIN ANALYZE actually runs the query and shows real execution times. This is the #1 tool for diagnosing slow queries.",
                hints=["It reveals the database's strategy for executing your query.", "ANALYZE adds actual timing data to the plan."],
                xp=30,
            ),
            Challenge(
                id="sql_index_selectivity",
                type="quiz",
                prompt="Why might a database optimizer choose a sequential scan over an index scan even when an index exists?",
                options=[
                    "The database engine has a bug in its query planner",
                    "When the query returns a large percentage of the table's rows, a sequential scan is faster than many random index lookups",
                    "Sequential scans are always faster than index scans",
                    "Indexes can only be used with WHERE clauses, never with JOINs",
                ],
                answer="b",
                explanation="Index scans involve random I/O — jumping to different disk pages for each row. When a query returns a large fraction of the table (low selectivity), sequential scan's linear I/O is faster. The optimizer estimates row counts and chooses the cheaper plan. A common threshold is roughly 10-15% of the table.",
                hints=["Think about random I/O vs. sequential I/O.", "If you need most of the rows anyway, is the index saving you work?"],
                xp=35,
            ),
        ],
    ),

    # ──────────────────────────────────────────────
    # ZONE 3 — NoSQL WORLD
    # ──────────────────────────────────────────────
    "nosql_world": Zone(
        id="nosql_world",
        title="The Unstructured Frontier",
        description="MongoDB, Redis, DynamoDB, Cassandra — document, key-value, column-family, and graph databases.",
        challenges=[
            Challenge(
                id="nosql_document_db",
                type="quiz",
                prompt="In MongoDB, data is stored as documents. What format are these documents?",
                options=[
                    "XML with strict XSD schema validation",
                    "BSON (Binary JSON) — a binary-encoded superset of JSON",
                    "CSV rows with a header line defining columns",
                    "Protocol Buffers with a .proto schema file",
                ],
                answer="b",
                explanation="MongoDB stores documents in BSON (Binary JSON), which extends JSON with additional types like Date, ObjectId, and BinData, plus efficient binary encoding. Documents are grouped into collections (analogous to tables). Each document can have a different structure — no fixed schema is enforced by default.",
                hints=["MongoDB is a document database — think about what format documents use.", "It's JSON-like but binary-encoded for performance."],
                xp=25,
            ),
            Challenge(
                id="nosql_redis_use_case",
                type="quiz",
                prompt="Redis is an in-memory key-value store. Which use case is it BEST suited for?",
                options=[
                    "Storing terabytes of historical transaction records for regulatory compliance",
                    "Caching session data, rate limiting, and real-time leaderboards requiring sub-millisecond latency",
                    "Running complex multi-table JOIN queries across normalized data",
                    "Storing large binary files like images and videos",
                ],
                answer="b",
                explanation="Redis keeps all data in RAM, delivering sub-millisecond reads and writes. It's ideal for caching (session stores, page fragments), rate limiting (atomic counters with TTL), leaderboards (sorted sets), and pub/sub messaging. It's NOT suited for large datasets that exceed memory or complex relational queries.",
                hints=["In-memory means blazing fast but limited by RAM.", "Think about what benefits from microsecond response times."],
                xp=25,
            ),
            Challenge(
                id="nosql_dynamodb_keys",
                type="quiz",
                prompt="In DynamoDB, what is a composite primary key made of?",
                options=[
                    "A table name and an index name",
                    "A partition key (hash key) and a sort key (range key)",
                    "A foreign key referencing another table and a unique row ID",
                    "An auto-incrementing integer and a timestamp",
                ],
                answer="b",
                explanation="DynamoDB's composite key has two parts: the partition key (determines which physical partition stores the item) and the sort key (orders items within a partition). Example: partition key = user_id, sort key = timestamp. This enables efficient queries like 'all orders for user X sorted by date'.",
                hints=["DynamoDB distributes data across partitions — one key determines where, the other determines order.", "Think hash + range."],
                xp=30,
            ),
            Challenge(
                id="nosql_cassandra_model",
                type="quiz",
                prompt="Cassandra's data model is optimized for which access pattern?",
                options=[
                    "Ad-hoc queries with arbitrary WHERE clauses and JOINs",
                    "High-throughput writes and reads by known partition key — query-first design",
                    "Graph traversals finding shortest paths between nodes",
                    "Full-text search with ranking and relevance scoring",
                ],
                answer="b",
                explanation="Cassandra is a wide-column store designed for massive write throughput and reads by partition key. You model tables around your query patterns (query-first design), not around entity relationships. It sacrifices ad-hoc query flexibility for linear horizontal scalability and high availability across data centers.",
                hints=["Cassandra is designed for scale — you design your tables around your queries.", "It's write-optimized and partition-key-oriented."],
                xp=30,
            ),
            Challenge(
                id="nosql_graph_db",
                type="quiz",
                prompt="Which type of NoSQL database is best suited for modeling social networks, recommendation engines, and fraud detection?",
                options=[
                    "Key-value store (Redis, Memcached)",
                    "Document store (MongoDB, CouchDB)",
                    "Graph database (Neo4j, Amazon Neptune)",
                    "Column-family store (Cassandra, HBase)",
                ],
                answer="c",
                explanation="Graph databases store data as nodes (entities) and edges (relationships), making them ideal for traversing connections: 'friends of friends', 'products bought by people who bought X', 'transactions connected to known fraud accounts'. They execute multi-hop relationship queries orders of magnitude faster than relational JOINs.",
                hints=["Social networks are literally graphs — people are nodes, friendships are edges.", "When relationships ARE the data, you need a database that models relationships natively."],
                xp=30,
            ),
            Challenge(
                id="nosql_eventual_consistency",
                type="quiz",
                prompt="What does 'eventual consistency' mean in a distributed NoSQL database?",
                options=[
                    "The database will eventually crash if too many writes occur",
                    "After a write, replicas may temporarily return stale data, but all replicas will converge to the same value given enough time with no new writes",
                    "Transactions are never consistent and always fail",
                    "Data is only consistent when the database is restarted",
                ],
                answer="b",
                explanation="Eventual consistency is a trade-off for availability and partition tolerance (AP in CAP). After a write, not all replicas are immediately updated — a read might hit a stale replica. But given time (often milliseconds), all replicas converge. DynamoDB and Cassandra offer tunable consistency, letting you choose strong or eventual per query.",
                hints=["It's about what happens between the write and all replicas being updated.", "The key word is 'eventually' — not immediately, but guaranteed over time."],
                xp=35,
            ),
        ],
    ),

    # ──────────────────────────────────────────────
    # ZONE 4 — DATABASE DESIGN
    # ──────────────────────────────────────────────
    "database_design": Zone(
        id="database_design",
        title="The Schema Blueprint",
        description="Normalization (1NF/2NF/3NF), denormalization, ERDs, foreign keys, and data modeling.",
        challenges=[
            Challenge(
                id="design_1nf",
                type="quiz",
                prompt="A table violates First Normal Form (1NF). Which of these is the most likely reason?",
                options=[
                    "The table has no primary key defined",
                    "A column contains comma-separated lists of values instead of atomic (single) values",
                    "The table has too many columns (more than 20)",
                    "The table uses VARCHAR instead of TEXT for string columns",
                ],
                answer="b",
                explanation="1NF requires every column to contain atomic (indivisible) values — no repeating groups, no arrays, no comma-separated lists. A 'phone_numbers' column containing '555-1234, 555-5678' violates 1NF. Fix: create a separate phone_numbers table with one row per phone number.",
                hints=["1NF is about atomicity — each cell holds one value.", "Comma-separated values in a single column are the classic violation."],
                xp=25,
            ),
            Challenge(
                id="design_2nf",
                type="quiz",
                prompt="A table has a composite primary key (student_id, course_id) and a column 'student_name' that depends only on student_id. This violates which normal form?",
                options=[
                    "First Normal Form (1NF)",
                    "Second Normal Form (2NF)",
                    "Third Normal Form (3NF)",
                    "Boyce-Codd Normal Form (BCNF)",
                ],
                answer="b",
                explanation="2NF requires that every non-key column depends on the WHOLE primary key, not just part of it. If student_name depends only on student_id (part of the composite key), it's a partial dependency — a 2NF violation. Fix: move student_name to a separate students table keyed by student_id.",
                hints=["2NF addresses partial dependencies in composite keys.", "If a non-key column depends on only PART of the key, it's a violation."],
                xp=30,
            ),
            Challenge(
                id="design_3nf",
                type="quiz",
                prompt="A table has columns: employee_id (PK), department_id, department_name. The department_name depends on department_id, not directly on employee_id. This violates:",
                options=[
                    "1NF — because department_name is not atomic",
                    "2NF — because of a partial key dependency",
                    "3NF — because of a transitive dependency (employee_id → department_id → department_name)",
                    "No normal form — this design is correct",
                ],
                answer="c",
                explanation="3NF eliminates transitive dependencies: non-key columns must depend directly on the primary key, not through another non-key column. Here department_name depends on department_id (not the PK). Fix: move department_id and department_name to a departments table; keep only department_id as a FK in employees.",
                hints=["A transitive dependency is when column A determines B, and B determines C.", "The non-key column depends on another non-key column, not the primary key."],
                xp=30,
            ),
            Challenge(
                id="design_denormalization",
                type="quiz",
                prompt="When is intentional denormalization a good design choice?",
                options=[
                    "Always — normalized designs are outdated",
                    "When read performance is critical and the cost of JOINs across many normalized tables is too high for the workload",
                    "When you want to save storage space",
                    "When you have fewer than 1000 rows in the database",
                ],
                answer="b",
                explanation="Denormalization deliberately introduces redundancy to avoid expensive JOINs. Common in read-heavy OLAP workloads, caching layers, and NoSQL designs. The trade-off: faster reads but harder updates (redundant data must be kept in sync). Normalize first, denormalize strategically when profiling proves JOINs are the bottleneck.",
                hints=["It's a performance optimization, not a default design choice.", "Fewer JOINs mean faster reads, but redundant data means harder updates."],
                xp=35,
            ),
            Challenge(
                id="design_erd_cardinality",
                type="quiz",
                prompt="In an Entity-Relationship Diagram, a line between 'Order' and 'OrderItem' marked with '1' on the Order side and '*' on the OrderItem side represents:",
                options=[
                    "One-to-one: each order has exactly one item",
                    "One-to-many: each order can have many items, but each item belongs to exactly one order",
                    "Many-to-many: orders and items can freely associate",
                    "Zero-to-one: an order may or may not have an item",
                ],
                answer="b",
                explanation="The 1:* notation means one-to-many. One Order has many OrderItems; each OrderItem belongs to exactly one Order. This is implemented with a foreign key: OrderItem.order_id references Order.id. One-to-many is the most common relationship in relational design.",
                hints=["The '*' (or 'N') side is the 'many' side of the relationship.", "Think about it practically: one order, multiple line items."],
                xp=25,
            ),
            Challenge(
                id="design_foreign_key_purpose",
                type="quiz",
                prompt="What does a FOREIGN KEY constraint enforce?",
                options=[
                    "That a column's values are unique across the table",
                    "That a column's values must exist in the referenced table's primary key — ensuring referential integrity",
                    "That a column cannot be NULL",
                    "That a column is automatically indexed for fast lookups",
                ],
                answer="b",
                explanation="A FOREIGN KEY constraint ensures referential integrity: you cannot insert a value into the FK column unless that value exists in the referenced table's primary key. You also cannot delete a referenced row unless you handle the dependent rows (CASCADE, SET NULL, or RESTRICT). This prevents orphaned records.",
                hints=["It's about maintaining valid relationships between tables.", "You can't reference a parent row that doesn't exist."],
                xp=25,
            ),
        ],
    ),

    # ──────────────────────────────────────────────
    # ZONE 5 — MIGRATIONS AND VERSIONING
    # ──────────────────────────────────────────────
    "migrations_and_versioning": Zone(
        id="migrations_and_versioning",
        title="The Evolution Chamber",
        description="Schema migrations, Flyway/Alembic, zero-downtime migrations, rollbacks, and version control for schemas.",
        challenges=[
            Challenge(
                id="mig_what_is_migration",
                type="quiz",
                prompt="What is a database migration?",
                options=[
                    "Moving a database from one cloud provider to another",
                    "A versioned, repeatable script that changes the database schema (add table, alter column, create index) in a controlled way",
                    "A backup of the database taken before a deployment",
                    "A query that moves data between tables within the same database",
                ],
                answer="b",
                explanation="A migration is a version-controlled script that applies an incremental schema change: CREATE TABLE, ALTER COLUMN, ADD INDEX, etc. Tools like Flyway, Alembic, and Liquibase track which migrations have been applied (usually in a metadata table) so changes are applied exactly once, in order.",
                hints=["Think of it like a git commit, but for your database schema.", "Each migration has a version number and is applied in sequence."],
                xp=25,
            ),
            Challenge(
                id="mig_flyway_vs_alembic",
                type="quiz",
                prompt="How do Flyway and Alembic track which migrations have been applied?",
                options=[
                    "They store migration state in a local file on the developer's machine",
                    "They use a metadata table in the database itself (e.g., flyway_schema_history or alembic_version) to record applied versions",
                    "They compare the live schema against a reference schema in version control",
                    "They rely on file timestamps to determine migration order",
                ],
                answer="b",
                explanation="Both Flyway and Alembic create a metadata table in the database: flyway_schema_history (Flyway) or alembic_version (Alembic). This table records which migration versions have been applied, checksums, and timestamps. The tool compares this table against available migration files to determine what needs to run.",
                hints=["The database itself is the source of truth for what has been applied.", "Look for a special tracking table inside the database."],
                xp=25,
            ),
            Challenge(
                id="mig_zero_downtime_add_column",
                type="quiz",
                prompt="You need to add a non-nullable column to a large production table with zero downtime. What is the safe approach?",
                options=[
                    "ALTER TABLE ADD COLUMN NOT NULL DEFAULT — the database will lock the table until every row is updated",
                    "Add the column as nullable first, backfill data in batches, then add the NOT NULL constraint",
                    "Drop the table and recreate it with the new column",
                    "Export all data to CSV, modify it, truncate the table, and re-import",
                ],
                answer="b",
                explanation="Zero-downtime migration pattern: (1) Add column as nullable (fast, no rewrite in modern Postgres). (2) Backfill data in small batches to avoid long locks. (3) Add NOT NULL constraint with a default or after verifying all rows are populated. This avoids the long table lock that a single ALTER TABLE NOT NULL would cause on a large table.",
                hints=["The key is avoiding long-running locks on the table.", "Do it in phases: add nullable, backfill, then constrain."],
                xp=35,
            ),
            Challenge(
                id="mig_rollback_strategy",
                type="quiz",
                prompt="Why should every forward migration have a corresponding rollback (down) migration?",
                options=[
                    "Rollback migrations are required by SQL standards",
                    "So that if a deployment fails, you can revert the schema change and restore the previous application version without data loss",
                    "Rollback migrations improve query performance",
                    "Databases automatically execute rollback migrations during replication",
                ],
                answer="b",
                explanation="Rollback (down) migrations provide a safety net: if a deployment breaks, you can revert the schema to match the previous application code. Without them, a failed deploy may leave you with a schema that doesn't match any deployable code version. Note: some changes (DROP COLUMN) are destructive and hard to roll back — plan accordingly.",
                hints=["Think about what happens when a deployment goes wrong.", "You need to be able to revert to the previous schema state."],
                xp=30,
            ),
            Challenge(
                id="mig_expand_contract",
                type="quiz",
                prompt="The 'expand and contract' migration pattern involves which sequence?",
                options=[
                    "Lock the table, make all changes at once, unlock the table",
                    "Expand: add new schema elements alongside the old. Migrate data. Contract: remove the old elements once all consumers have switched",
                    "Export the database, transform the schema, import to a new database",
                    "Run migrations only during scheduled maintenance windows",
                ],
                answer="b",
                explanation="Expand-and-contract is the gold standard for zero-downtime schema evolution. Expand phase: add new columns/tables while keeping old ones (both old and new code works). Migration phase: backfill data into new structures. Contract phase: drop old columns/tables after all consumers use the new schema. Safe, reversible, zero-downtime.",
                hints=["It's a two-phase approach: add new, then remove old.", "Both the old and new schema coexist during the transition."],
                xp=35,
            ),
        ],
    ),

    # ──────────────────────────────────────────────
    # ZONE 6 — REPLICATION AND SCALING
    # ──────────────────────────────────────────────
    "replication_and_scaling": Zone(
        id="replication_and_scaling",
        title="The Replication Grid",
        description="Primary-replica, sharding, read replicas, connection pooling, partitioning, and horizontal scaling.",
        challenges=[
            Challenge(
                id="scale_primary_replica",
                type="quiz",
                prompt="In a primary-replica (master-slave) replication setup, what is the role of the replica?",
                options=[
                    "The replica handles all write operations while the primary handles reads",
                    "The replica receives a copy of all writes from the primary and serves read queries, offloading read traffic from the primary",
                    "The replica stores only backup data and cannot serve queries",
                    "The replica automatically replaces the primary if the primary fails — no other function",
                ],
                answer="b",
                explanation="Replicas (read replicas) continuously apply changes streamed from the primary via replication logs (WAL in Postgres, binlog in MySQL). They serve read queries, distributing read load across multiple servers. Writes still go to the primary. This is the simplest horizontal read-scaling pattern. Replicas can also be promoted to primary during failover.",
                hints=["Replicas mirror the primary's data and handle read traffic.", "Writes still go to one place — the primary."],
                xp=25,
            ),
            Challenge(
                id="scale_sharding",
                type="quiz",
                prompt="What is database sharding?",
                options=[
                    "Compressing database files to reduce disk usage",
                    "Splitting data across multiple database instances based on a shard key, so each shard holds a subset of the total data",
                    "Creating backup copies of the database on different servers",
                    "Encrypting individual columns to meet compliance requirements",
                ],
                answer="b",
                explanation="Sharding horizontally partitions data across multiple database servers. A shard key (e.g., user_id % 4) determines which shard stores each record. Each shard is an independent database holding a subset of data. Sharding enables horizontal write scaling but adds complexity: cross-shard queries, rebalancing, and distributed transactions become hard problems.",
                hints=["Think about dividing data across multiple independent databases.", "Each piece (shard) holds a portion of the total dataset."],
                xp=30,
            ),
            Challenge(
                id="scale_connection_pooling",
                type="quiz",
                prompt="Why is connection pooling (e.g., PgBouncer) important for database scalability?",
                options=[
                    "It encrypts database connections for security",
                    "It reuses a pool of existing database connections instead of creating new ones per request — reducing connection overhead and preventing exhaustion of database connection limits",
                    "It automatically shards queries across multiple databases",
                    "It caches query results to avoid hitting the database",
                ],
                answer="b",
                explanation="Each database connection consumes memory (5-10 MB in PostgreSQL). With hundreds of application instances, connection counts explode. A connection pooler (PgBouncer, pgpool) maintains a smaller pool of actual DB connections and multiplexes application requests over them. This prevents the 'too many connections' error and reduces database memory usage.",
                hints=["Database connections are expensive to create and maintain.", "The pooler sits between your app and the database, sharing connections."],
                xp=30,
            ),
            Challenge(
                id="scale_partitioning",
                type="quiz",
                prompt="What is the difference between table partitioning and sharding?",
                options=[
                    "They are the same thing — different names for the same concept",
                    "Partitioning splits a table into segments within the same database server; sharding splits data across multiple separate database servers",
                    "Partitioning is for NoSQL databases; sharding is for relational databases",
                    "Partitioning works on columns; sharding works on rows",
                ],
                answer="b",
                explanation="Partitioning (e.g., PostgreSQL table partitioning) divides a large table into smaller pieces on the SAME server — by range (date), list (region), or hash. The database transparently routes queries to relevant partitions. Sharding distributes data across DIFFERENT servers. Partitioning improves query performance; sharding enables horizontal scaling beyond one machine.",
                hints=["One stays within a single server; the other spans multiple servers.", "Partitioning is a single-server optimization; sharding is a distributed architecture."],
                xp=35,
            ),
            Challenge(
                id="scale_replication_lag",
                type="quiz",
                prompt="What is replication lag, and why does it matter?",
                options=[
                    "The time it takes to execute a query on the primary",
                    "The delay between a write on the primary and that write being visible on a replica — causing stale reads if not managed",
                    "The time it takes to create a new replica from a backup",
                    "The network latency between the application server and the database",
                ],
                answer="b",
                explanation="Replication lag is the time between a write committing on the primary and appearing on the replica. During this window, reading from the replica returns stale data. For user-facing reads-after-writes (e.g., 'I just updated my profile'), route those reads to the primary. Monitor lag with pg_stat_replication (Postgres) or SHOW SLAVE STATUS (MySQL).",
                hints=["It's the delay between the primary and replica being in sync.", "Reading from a lagging replica means you might see old data."],
                xp=30,
            ),
            Challenge(
                id="scale_read_write_split",
                type="quiz",
                prompt="In a read/write splitting architecture, which component typically routes queries to the appropriate database?",
                options=[
                    "The database itself decides which server handles each query",
                    "A proxy layer or application-level logic that sends writes to the primary and reads to replicas",
                    "The operating system kernel's network stack",
                    "DNS round-robin between the primary and replicas",
                ],
                answer="b",
                explanation="Read/write splitting is implemented by either a proxy (ProxySQL, PgBouncer with routing, AWS RDS Proxy) or application-level logic (using separate connection strings for reads vs. writes). The proxy inspects the query type: INSERT/UPDATE/DELETE goes to the primary; SELECT goes to a replica. This maximizes read throughput without changing application SQL.",
                hints=["Something needs to inspect the query and decide: primary or replica?", "It can be a middleware proxy or logic in your application code."],
                xp=30,
            ),
        ],
    ),

    # ──────────────────────────────────────────────
    # ZONE 7 — BACKUP AND RECOVERY
    # ──────────────────────────────────────────────
    "backup_and_recovery": Zone(
        id="backup_and_recovery",
        title="The Disaster Vault",
        description="Backup strategies, point-in-time recovery, WAL, RTO/RPO, and disaster recovery planning.",
        challenges=[
            Challenge(
                id="backup_rto_rpo",
                type="quiz",
                prompt="What is the difference between RTO and RPO?",
                options=[
                    "RTO is the backup frequency; RPO is the backup size",
                    "RTO (Recovery Time Objective) is the maximum acceptable downtime; RPO (Recovery Point Objective) is the maximum acceptable data loss measured in time",
                    "RTO is for databases; RPO is for application servers",
                    "RTO measures read latency; RPO measures write latency",
                ],
                answer="b",
                explanation="RTO answers: 'How quickly must we be back online?' (e.g., 1 hour). RPO answers: 'How much data can we afford to lose?' (e.g., 5 minutes of transactions). An RPO of zero requires synchronous replication. These two metrics drive your entire backup and disaster recovery architecture.",
                hints=["One is about time to recover, the other is about data loss tolerance.", "Think: how fast do we recover (RTO) and how far back might we lose (RPO)?"],
                xp=25,
            ),
            Challenge(
                id="backup_wal_purpose",
                type="quiz",
                prompt="What is the Write-Ahead Log (WAL) in PostgreSQL?",
                options=[
                    "A log of all user authentication attempts",
                    "A sequential log where every change is written before being applied to data files — enabling crash recovery and replication",
                    "A query plan cache that stores frequently executed queries",
                    "A monitoring dashboard showing write throughput over time",
                ],
                answer="b",
                explanation="The WAL (Write-Ahead Log) records every change before it's applied to the actual data pages. On crash, PostgreSQL replays the WAL to recover committed transactions. The WAL also enables streaming replication (replicas replay the same log) and point-in-time recovery (replay WAL up to a specific timestamp). It's the foundation of durability.",
                hints=["'Write-Ahead' means the log is written BEFORE the data files.", "It's how the database guarantees durability and enables replication."],
                xp=30,
            ),
            Challenge(
                id="backup_full_vs_incremental",
                type="quiz",
                prompt="What is the advantage of incremental backups over full backups?",
                options=[
                    "Incremental backups are always more reliable than full backups",
                    "Incremental backups only capture changes since the last backup, requiring less storage and time — but restoration requires the full backup plus all incremental backups in sequence",
                    "Incremental backups eliminate the need for any full backups",
                    "Incremental backups compress data better than full backups",
                ],
                answer="b",
                explanation="A full backup copies everything — slow and large. An incremental backup copies only what changed since the last backup — fast and small. To restore: apply the base full backup, then replay each incremental in order. Trade-off: faster backups but slower, more complex restores. A common strategy: weekly full + daily incrementals.",
                hints=["Incremental means 'only the changes since last time'.", "Think about the restore process — you need the full chain."],
                xp=25,
            ),
            Challenge(
                id="backup_pitr",
                type="quiz",
                prompt="Point-in-time recovery (PITR) allows you to restore a database to a specific moment. What does it require?",
                options=[
                    "Only the most recent full backup",
                    "A base backup plus all WAL (Write-Ahead Log) segments from the backup time to the target recovery point",
                    "A complete export of the database in CSV format",
                    "A snapshot of the operating system's disk image",
                ],
                answer="b",
                explanation="PITR combines a base backup (pg_basebackup) with continuous WAL archiving. To recover to time T: restore the base backup, then replay archived WAL segments up to T. This lets you recover to the exact moment before a destructive event (e.g., accidental DROP TABLE at 14:32:07 — recover to 14:32:06).",
                hints=["You need a starting point (base backup) and a record of all changes (WAL).", "Replay changes up to the exact moment you want to recover to."],
                xp=35,
            ),
            Challenge(
                id="backup_test_your_backups",
                type="quiz",
                prompt="What is the single most important practice for database backup reliability?",
                options=[
                    "Using the most expensive backup storage tier available",
                    "Regularly testing restores by actually recovering from backups to verify they work — untested backups are not backups",
                    "Taking backups every minute to minimize data loss",
                    "Storing backups on the same server as the database for fastest access",
                ],
                answer="b",
                explanation="An untested backup is Schrodinger's backup — you don't know if it works until you try to restore. Regularly schedule restore tests: recover to a staging environment, verify data integrity, measure how long recovery takes (validate your RTO). Many disaster stories involve discovering corrupt or incomplete backups during a real emergency.",
                hints=["A backup is only as good as your ability to restore from it.", "The most common backup failure: never testing the restore process."],
                xp=30,
            ),
        ],
    ),

    # ──────────────────────────────────────────────
    # ZONE 8 — DATABASE SECURITY
    # ──────────────────────────────────────────────
    "database_security": Zone(
        id="database_security",
        title="The Encryption Perimeter",
        description="SQL injection prevention, least privilege, encryption at rest and in transit, audit logging, and access control.",
        challenges=[
            Challenge(
                id="sec_sql_injection",
                type="quiz",
                prompt="What is the PRIMARY defense against SQL injection attacks?",
                options=[
                    "Input validation with regex to block special characters",
                    "Parameterized queries (prepared statements) that separate SQL code from user-supplied data",
                    "Encrypting all database columns",
                    "Running the database on a non-standard port",
                ],
                answer="b",
                explanation="Parameterized queries (prepared statements) send SQL structure and user data separately to the database. The database compiles the query template first, then binds parameters — user input is NEVER interpreted as SQL code. This eliminates SQL injection entirely, unlike regex filtering which can always be bypassed.",
                hints=["The defense must make it impossible for user input to be treated as SQL code.", "Prepared statements separate code from data at the protocol level."],
                xp=25,
            ),
            Challenge(
                id="sec_least_privilege",
                type="quiz",
                prompt="Applying the principle of least privilege to database access means:",
                options=[
                    "Every application and user gets full admin (superuser) access for simplicity",
                    "Each application or user is granted only the minimum permissions needed to perform their specific function — no more",
                    "All database access goes through a single shared account",
                    "Permissions are only reviewed during annual security audits",
                ],
                answer="b",
                explanation="Least privilege: the web app's DB user gets SELECT/INSERT/UPDATE on its tables — not DROP TABLE or CREATE USER. The analytics service gets read-only access. The migration runner gets DDL permissions only during deployments. If any account is compromised, the blast radius is limited to its granted permissions.",
                hints=["Give each account only what it needs, nothing more.", "A compromised read-only account can't DROP TABLE."],
                xp=25,
            ),
            Challenge(
                id="sec_encryption_at_rest",
                type="quiz",
                prompt="What does 'encryption at rest' protect against?",
                options=[
                    "Network sniffing and man-in-the-middle attacks",
                    "Unauthorized access to data on disk — if physical storage is stolen or accessed without authorization, the data is unreadable without the encryption key",
                    "SQL injection attacks from the application layer",
                    "Brute-force password guessing against database accounts",
                ],
                answer="b",
                explanation="Encryption at rest protects data stored on disk (data files, backups, WAL). If someone steals a hard drive, copies a backup file, or gains raw filesystem access, they see encrypted bytes — not your data. This is implemented via Transparent Data Encryption (TDE), filesystem encryption (LUKS), or cloud-managed encryption (AWS RDS encryption).",
                hints=["'At rest' means data sitting on disk, not moving across a network.", "Think about what happens if someone physically steals the storage."],
                xp=30,
            ),
            Challenge(
                id="sec_encryption_in_transit",
                type="quiz",
                prompt="Enabling TLS/SSL for database connections protects against which threat?",
                options=[
                    "Data corruption during disk writes",
                    "Eavesdropping on database traffic — an attacker on the network cannot read queries or results in transit",
                    "Unauthorized schema changes by DBA accounts",
                    "Denial-of-service attacks against the database port",
                ],
                answer="b",
                explanation="TLS encrypts the connection between client and database server. Without it, queries and results (including passwords, personal data, credentials) travel in plaintext — readable by anyone who can capture network traffic (e.g., on a shared network or compromised router). Always require TLS for database connections, especially across networks.",
                hints=["'In transit' means data moving across the network.", "Without encryption, network traffic is an open book."],
                xp=25,
            ),
            Challenge(
                id="sec_audit_logging",
                type="quiz",
                prompt="What is the purpose of database audit logging?",
                options=[
                    "To improve query performance by caching frequent operations",
                    "To record who accessed what data, when, and what changes were made — providing an evidence trail for security investigations and compliance",
                    "To automatically encrypt sensitive columns",
                    "To compress old data and free up disk space",
                ],
                answer="b",
                explanation="Audit logging records database operations: who connected, what queries they ran, which rows were modified, when it happened. This is critical for security investigations ('Who accessed the PII table at 3am?'), compliance (SOX, HIPAA, GDPR), and change tracking. Tools: pgAudit (Postgres), MySQL Enterprise Audit, AWS CloudTrail for RDS.",
                hints=["It's about accountability — who did what and when.", "Think security investigations and regulatory compliance."],
                xp=30,
            ),
            Challenge(
                id="sec_row_level_security",
                type="quiz",
                prompt="Row-Level Security (RLS) in PostgreSQL allows you to:",
                options=[
                    "Encrypt individual rows with different encryption keys",
                    "Define policies that control which rows a user can see or modify — enforcing data isolation at the database level",
                    "Compress rows to reduce storage size",
                    "Replicate specific rows to different database servers",
                ],
                answer="b",
                explanation="RLS policies define per-row access rules: 'tenant_a can only see rows where tenant_id = tenant_a'. The database enforces this transparently — queries automatically filter to permitted rows. This is powerful for multi-tenant applications: even if application code has a bug, the database prevents cross-tenant data access.",
                hints=["It's access control at the individual row level, not just the table level.", "Think multi-tenant: each tenant sees only their own data."],
                xp=35,
            ),
        ],
    ),
}
