"""
zones.py — Zones and challenges for the Basic Math skill pack.
"""

ZONE_ORDER = [
    "addition_fun",
    "subtraction_station",
    "multiplication_tables",
    "division_basics",
    "word_problems",
]

ZONES = {
    "addition_fun": {
        "id": "addition_fun",
        "name": "Addition Fun",
        "description": "Add single-digit and double-digit numbers together",
        "level_required": 1,
        "challenges": [
            {
                "id": "af_01",
                "title": "Adding Small Numbers",
                "type": "quiz",
                "question": "What is [bold yellow]4 + 3[/bold yellow]?",
                "lesson": "4 + 3 = [bold yellow]7[/bold yellow]. Start at 4 and count up 3 more: 5, 6, 7!",
                "options": ["6", "7", "8", "5"],
                "answer": "b",
                "hints": ["Start at 4 and count up 3 more!", "4... 5, 6, 7!"],
                "xp": 25,
            },
            {
                "id": "af_02",
                "title": "Adding to Ten",
                "type": "quiz",
                "question": "What is [bold yellow]6 + 4[/bold yellow]?",
                "lesson": "6 + 4 = [bold yellow]10[/bold yellow]. These two numbers are a perfect ten pair!",
                "options": ["9", "11", "10", "8"],
                "answer": "c",
                "hints": ["6 and 4 are a number pair that makes 10!", "Count up from 6: 7, 8, 9, 10!"],
                "xp": 25,
            },
            {
                "id": "af_03",
                "title": "Cookie Addition",
                "type": "quiz",
                "question": "You bake [bold yellow]5[/bold yellow] cookies in the morning and [bold yellow]7[/bold yellow] cookies after lunch. How many cookies do you have?",
                "lesson": "5 + 7 = [bold yellow]12[/bold yellow]. When you combine two groups, you add them together!",
                "options": ["11", "13", "10", "12"],
                "answer": "d",
                "hints": ["Start at 7 and count up 5 more!", "7... 8, 9, 10, 11, 12!"],
                "xp": 30,
            },
            {
                "id": "af_04",
                "title": "Double Digits",
                "type": "fill_blank",
                "question": "[bold white]14 + 5 = ?[/bold white]",
                "lesson": "14 + 5 = [bold yellow]19[/bold yellow]. Start at 14 and count up 5: 15, 16, 17, 18, 19!",
                "options": [],
                "answer": "19",
                "hints": ["Start at 14 and count up 5!", "14... 15, 16, 17, 18, 19!"],
                "xp": 30,
            },
            {
                "id": "af_05",
                "title": "Adding Tens",
                "type": "fill_blank",
                "question": "[bold white]30 + 40 = ?[/bold white]",
                "lesson": "3 tens + 4 tens = 7 tens = [bold yellow]70[/bold yellow]. Adding tens is like adding small numbers with a zero on the end!",
                "options": [],
                "answer": "70",
                "hints": ["3 + 4 = 7, so 30 + 40 = ?", "Think of it as 3 tens + 4 tens!"],
                "xp": 35,
            },
            {
                "id": "af_06",
                "title": "Two-Digit Addition",
                "type": "fill_blank",
                "question": "[bold white]23 + 15 = ?[/bold white]",
                "lesson": "Add ones first: 3 + 5 = 8. Then tens: 20 + 10 = 30. Together: [bold yellow]38[/bold yellow]!",
                "options": [],
                "answer": "38",
                "hints": ["Add the ones first (3+5), then the tens (20+10)!", "8 + 30 = 38!"],
                "xp": 35,
            },
            {
                "id": "af_07",
                "title": "Marble Addition",
                "type": "quiz",
                "question": "You have [bold yellow]16[/bold yellow] marbles and your friend gives you [bold yellow]9[/bold yellow] more. How many marbles do you have now?",
                "lesson": "16 + 9 = [bold yellow]25[/bold yellow]. Tip: 16 + 9 is the same as 16 + 10 - 1 = 25!",
                "options": ["24", "25", "26", "23"],
                "answer": "b",
                "hints": ["Try adding 10 first (16+10=26), then subtract 1!", "16 + 9 = 25!"],
                "xp": 40,
            },
            {
                "id": "af_boss",
                "title": "Big Addition Challenge",
                "type": "fill_blank",
                "question": "[bold white]47 + 36 = ?[/bold white]",
                "lesson": "Ones: 7 + 6 = 13 (write 3, carry 1). Tens: 4 + 3 + 1 = 8. Answer: [bold yellow]83[/bold yellow]!",
                "options": [],
                "answer": "83",
                "hints": ["Add the ones: 7+6=13. Write down 3 and carry the 1!", "40+30=70, plus the carried 1 ten = 80. 80+3=83!"],
                "xp": 60,
                "is_boss": True,
            },
        ],
    },

    "subtraction_station": {
        "id": "subtraction_station",
        "name": "Subtraction Station",
        "description": "Subtract numbers and find what's left",
        "level_required": 2,
        "challenges": [
            {
                "id": "ss_01",
                "title": "Simple Subtraction",
                "type": "quiz",
                "question": "What is [bold yellow]9 - 4[/bold yellow]?",
                "lesson": "9 - 4 = [bold yellow]5[/bold yellow]. Start at 9 and count back 4: 8, 7, 6, 5!",
                "options": ["4", "6", "5", "3"],
                "answer": "c",
                "hints": ["Start at 9 and count back 4!", "9... 8, 7, 6, 5!"],
                "xp": 25,
            },
            {
                "id": "ss_02",
                "title": "Pizza Slices",
                "type": "quiz",
                "question": "A pizza has [bold yellow]8[/bold yellow] slices. You eat [bold yellow]3[/bold yellow]. How many slices are left?",
                "lesson": "8 - 3 = [bold yellow]5[/bold yellow]. Subtraction tells us what's left over after taking some away!",
                "options": ["6", "4", "3", "5"],
                "answer": "d",
                "hints": ["Start with 8 slices, take away 3!", "8... 7, 6, 5. Five slices left!"],
                "xp": 30,
            },
            {
                "id": "ss_03",
                "title": "Subtracting from 10",
                "type": "fill_blank",
                "question": "[bold white]10 - 6 = ?[/bold white]",
                "lesson": "10 - 6 = [bold yellow]4[/bold yellow]. If 6 + 4 = 10, then 10 - 6 = 4. Addition and subtraction are opposites!",
                "options": [],
                "answer": "4",
                "hints": ["If 6 + ? = 10, what's the missing number?", "Count back from 10 six times!"],
                "xp": 30,
            },
            {
                "id": "ss_04",
                "title": "Subtracting Teens",
                "type": "fill_blank",
                "question": "[bold white]15 - 7 = ?[/bold white]",
                "lesson": "15 - 7 = [bold yellow]8[/bold yellow]. Take away 5 first to get 10, then take away 2 more to get 8!",
                "options": [],
                "answer": "8",
                "hints": ["15 - 5 = 10, then 10 - 2 = ?", "Count back from 15 seven times!"],
                "xp": 35,
            },
            {
                "id": "ss_05",
                "title": "Sticker Subtraction",
                "type": "quiz",
                "question": "You had [bold yellow]20[/bold yellow] stickers and gave [bold yellow]8[/bold yellow] to your friend. How many do you have left?",
                "lesson": "20 - 8 = [bold yellow]12[/bold yellow]. Take away 8 from 20: 20 - 10 = 10, then add 2 back!",
                "options": ["11", "14", "12", "10"],
                "answer": "c",
                "hints": ["20 - 10 = 10, but we only need to subtract 8, so add 2 back!", "20 - 8 = 12!"],
                "xp": 35,
            },
            {
                "id": "ss_06",
                "title": "Two-Digit Subtraction",
                "type": "fill_blank",
                "question": "[bold white]34 - 12 = ?[/bold white]",
                "lesson": "Ones: 4 - 2 = 2. Tens: 30 - 10 = 20. Together: [bold yellow]22[/bold yellow]!",
                "options": [],
                "answer": "22",
                "hints": ["Subtract the ones (4-2), then the tens (30-10)!", "2 + 20 = 22!"],
                "xp": 35,
            },
            {
                "id": "ss_07",
                "title": "Missing Number",
                "type": "fill_blank",
                "question": "What goes in the blank?\n[bold white]__ - 5 = 9[/bold white]",
                "lesson": "If something minus 5 equals 9, then that something is 9 + 5 = [bold yellow]14[/bold yellow]!",
                "options": [],
                "answer": "14",
                "hints": ["Turn it around: 9 + 5 = ?", "If you take 5 from the answer, you get 9. So the answer is 9 + 5!"],
                "xp": 40,
            },
            {
                "id": "ss_boss",
                "title": "Big Subtraction Challenge",
                "type": "fill_blank",
                "question": "[bold white]52 - 27 = ?[/bold white]",
                "lesson": "Ones: 12 - 7 = 5 (borrow from the tens). Tens: 4 - 2 = 2. Answer: [bold yellow]25[/bold yellow]!",
                "options": [],
                "answer": "25",
                "hints": ["You can't take 7 from 2, so borrow a ten! 12 - 7 = 5.", "40 - 20 = 20. 20 + 5 = 25!"],
                "xp": 60,
                "is_boss": True,
            },
        ],
    },

    "multiplication_tables": {
        "id": "multiplication_tables",
        "name": "Multiplication Tables",
        "description": "Learn times tables from 2x through 10x",
        "level_required": 3,
        "challenges": [
            {
                "id": "mt_01",
                "title": "What Is Multiplication?",
                "type": "quiz",
                "question": "Multiplication is a fast way to add. [bold yellow]3 x 2[/bold yellow] means 3 groups of 2. What is 3 x 2?",
                "lesson": "3 x 2 = 2 + 2 + 2 = [bold yellow]6[/bold yellow]. Multiplication is repeated addition!",
                "options": ["5", "6", "8", "4"],
                "answer": "b",
                "hints": ["3 groups of 2: 2 + 2 + 2!", "Count by 2s three times: 2, 4, 6!"],
                "xp": 25,
            },
            {
                "id": "mt_02",
                "title": "Times 5",
                "type": "quiz",
                "question": "What is [bold yellow]4 x 5[/bold yellow]?",
                "lesson": "4 x 5 = [bold yellow]20[/bold yellow]. The 5 times table always ends in 0 or 5!",
                "options": ["15", "25", "20", "10"],
                "answer": "c",
                "hints": ["Count by 5s four times: 5, 10, 15, 20!", "4 groups of 5!"],
                "xp": 30,
            },
            {
                "id": "mt_03",
                "title": "Times 3",
                "type": "fill_blank",
                "question": "[bold white]3 x 7 = ?[/bold white]",
                "lesson": "3 x 7 = [bold yellow]21[/bold yellow]. Count by 3s: 3, 6, 9, 12, 15, 18, 21!",
                "options": [],
                "answer": "21",
                "hints": ["Count by 3s seven times!", "3, 6, 9, 12, 15, 18, 21!"],
                "xp": 35,
            },
            {
                "id": "mt_04",
                "title": "Toy Cars",
                "type": "quiz",
                "question": "Each toy car has [bold yellow]4[/bold yellow] wheels. If you have [bold yellow]6[/bold yellow] toy cars, how many wheels is that?",
                "lesson": "6 x 4 = [bold yellow]24[/bold yellow] wheels. Multiplication helps us count equal groups quickly!",
                "options": ["20", "22", "24", "28"],
                "answer": "c",
                "hints": ["6 groups of 4 wheels each!", "Count by 4s: 4, 8, 12, 16, 20, 24!"],
                "xp": 35,
            },
            {
                "id": "mt_05",
                "title": "Times 8",
                "type": "fill_blank",
                "question": "[bold white]8 x 3 = ?[/bold white]",
                "lesson": "8 x 3 = [bold yellow]24[/bold yellow]. Fun trick: 8 x 3 is the same as 3 x 8. Multiplication works both ways!",
                "options": [],
                "answer": "24",
                "hints": ["3 groups of 8: 8 + 8 + 8!", "8, 16, 24!"],
                "xp": 35,
            },
            {
                "id": "mt_06",
                "title": "Times 9 Trick",
                "type": "quiz",
                "question": "What is [bold yellow]9 x 4[/bold yellow]? Hint: the digits of the answer always add up to 9!",
                "lesson": "9 x 4 = [bold yellow]36[/bold yellow]. Check: 3 + 6 = 9. The 9 times table has this magic pattern!",
                "options": ["27", "36", "45", "32"],
                "answer": "b",
                "hints": ["9 x 4: the tens digit is one less than 4, so it's 3. What plus 3 = 9?", "3 and 6 make 9... so 36!"],
                "xp": 40,
            },
            {
                "id": "mt_07",
                "title": "Times 10",
                "type": "fill_blank",
                "question": "[bold white]10 x 7 = ?[/bold white]",
                "lesson": "10 x 7 = [bold yellow]70[/bold yellow]. Multiplying by 10 is easy: just add a zero!",
                "options": [],
                "answer": "70",
                "hints": ["Multiplying by 10? Just add a zero to the other number!", "7 with a zero = 70!"],
                "xp": 30,
            },
            {
                "id": "mt_boss",
                "title": "Multiplication Master",
                "type": "fill_blank",
                "question": "[bold white]7 x 8 = ?[/bold white]",
                "lesson": "7 x 8 = [bold yellow]56[/bold yellow]. This is one of the trickiest times table facts. Remember: 5, 6, 7, 8 -> 56 = 7 x 8!",
                "options": [],
                "answer": "56",
                "hints": ["A fun way to remember: 56 = 7 x 8 has the numbers 5, 6, 7, 8 in order!", "Count by 7s: 7, 14, 21, 28, 35, 42, 49, 56!"],
                "xp": 60,
                "is_boss": True,
            },
        ],
    },

    "division_basics": {
        "id": "division_basics",
        "name": "Division Basics",
        "description": "Learn to share and divide equally",
        "level_required": 4,
        "challenges": [
            {
                "id": "db_01",
                "title": "What Is Division?",
                "type": "quiz",
                "question": "You have [bold yellow]6[/bold yellow] cookies and [bold yellow]2[/bold yellow] friends. If you share equally, how many cookies does each friend get?",
                "lesson": "6 / 2 = [bold yellow]3[/bold yellow]. Division means sharing equally. Each friend gets the same number!",
                "options": ["2", "3", "4", "6"],
                "answer": "b",
                "hints": ["Split 6 cookies into 2 equal groups!", "Give one to each, then another, then another... 3 each!"],
                "xp": 25,
            },
            {
                "id": "db_02",
                "title": "Dividing by 2",
                "type": "fill_blank",
                "question": "[bold white]10 / 2 = ?[/bold white]",
                "lesson": "10 / 2 = [bold yellow]5[/bold yellow]. Dividing by 2 is the same as finding half!",
                "options": [],
                "answer": "5",
                "hints": ["What is half of 10?", "Split 10 into 2 equal groups!"],
                "xp": 30,
            },
            {
                "id": "db_03",
                "title": "Sharing Crayons",
                "type": "quiz",
                "question": "You have [bold yellow]12[/bold yellow] crayons and [bold yellow]3[/bold yellow] boxes. How many crayons go in each box if you share equally?",
                "lesson": "12 / 3 = [bold yellow]4[/bold yellow]. Think: 3 x ? = 12. The answer is 4!",
                "options": ["3", "6", "4", "5"],
                "answer": "c",
                "hints": ["12 split into 3 equal groups!", "3 x 4 = 12, so 12 / 3 = 4!"],
                "xp": 30,
            },
            {
                "id": "db_04",
                "title": "Dividing by 5",
                "type": "fill_blank",
                "question": "[bold white]25 / 5 = ?[/bold white]",
                "lesson": "25 / 5 = [bold yellow]5[/bold yellow]. Think of it as: how many 5s fit into 25? Count by 5s: 5, 10, 15, 20, 25 — that's 5!",
                "options": [],
                "answer": "5",
                "hints": ["How many times does 5 go into 25?", "Count by 5s until you reach 25!"],
                "xp": 35,
            },
            {
                "id": "db_05",
                "title": "Multiplication Backwards",
                "type": "quiz",
                "question": "If [bold yellow]6 x 4 = 24[/bold yellow], then what is [bold yellow]24 / 6[/bold yellow]?",
                "lesson": "24 / 6 = [bold yellow]4[/bold yellow]. Division is the opposite of multiplication! If 6 x 4 = 24, then 24 / 6 = 4.",
                "options": ["3", "6", "4", "8"],
                "answer": "c",
                "hints": ["Division undoes multiplication!", "6 times WHAT equals 24?"],
                "xp": 35,
            },
            {
                "id": "db_06",
                "title": "Apple Sharing",
                "type": "fill_blank",
                "question": "You pick [bold yellow]32[/bold yellow] apples and put them into bags of [bold yellow]8[/bold yellow]. How many bags do you fill?\n[bold white]32 / 8 = ?[/bold white]",
                "lesson": "32 / 8 = [bold yellow]4[/bold yellow] bags. Count by 8s: 8, 16, 24, 32 — four groups!",
                "options": [],
                "answer": "4",
                "hints": ["How many 8s make 32?", "8, 16, 24, 32 — count the hops!"],
                "xp": 40,
            },
            {
                "id": "db_07",
                "title": "Dividing by 10",
                "type": "fill_blank",
                "question": "[bold white]90 / 10 = ?[/bold white]",
                "lesson": "90 / 10 = [bold yellow]9[/bold yellow]. Dividing by 10 removes the zero at the end!",
                "options": [],
                "answer": "9",
                "hints": ["Dividing by 10? Just remove the zero!", "How many 10s fit into 90?"],
                "xp": 30,
            },
            {
                "id": "db_boss",
                "title": "Division Champion",
                "type": "fill_blank",
                "question": "[bold white]56 / 7 = ?[/bold white]",
                "lesson": "56 / 7 = [bold yellow]8[/bold yellow]. Remember the times table: 7 x 8 = 56, so 56 / 7 = 8!",
                "options": [],
                "answer": "8",
                "hints": ["What times 7 equals 56?", "Think of the 7 times table: 7, 14, 21, 28, 35, 42, 49, 56!"],
                "xp": 60,
                "is_boss": True,
            },
        ],
    },

    "word_problems": {
        "id": "word_problems",
        "name": "Word Problems",
        "description": "Solve real-world math stories using addition, subtraction, multiplication, and division",
        "level_required": 5,
        "challenges": [
            {
                "id": "wp_01",
                "title": "Lemonade Stand",
                "type": "quiz",
                "question": "You sell [bold yellow]8[/bold yellow] cups of lemonade in the morning and [bold yellow]13[/bold yellow] in the afternoon. How many cups did you sell today?",
                "lesson": "8 + 13 = [bold yellow]21[/bold yellow] cups. When the problem says 'how many in total,' that's addition!",
                "options": ["19", "20", "21", "22"],
                "answer": "c",
                "hints": ["This is an addition problem — combine the two amounts!", "8 + 13 = ?"],
                "xp": 30,
            },
            {
                "id": "wp_02",
                "title": "Birthday Balloons",
                "type": "fill_blank",
                "question": "You brought [bold yellow]25[/bold yellow] balloons to the party. [bold yellow]9[/bold yellow] popped! How many balloons are left?\n[bold white]25 - 9 = ?[/bold white]",
                "lesson": "25 - 9 = [bold yellow]16[/bold yellow] balloons. When something is 'taken away' or 'lost,' that's subtraction!",
                "options": [],
                "answer": "16",
                "hints": ["Balloons popped means they're gone — subtract!", "25 - 10 = 15, then add 1 back: 16!"],
                "xp": 35,
            },
            {
                "id": "wp_03",
                "title": "Planting Flowers",
                "type": "quiz",
                "question": "You plant [bold yellow]5[/bold yellow] rows of flowers with [bold yellow]6[/bold yellow] flowers in each row. How many flowers did you plant?",
                "lesson": "5 x 6 = [bold yellow]30[/bold yellow] flowers. Equal groups in rows? That's multiplication!",
                "options": ["25", "11", "30", "35"],
                "answer": "c",
                "hints": ["5 rows, 6 in each row — that's 5 groups of 6!", "5 x 6 = ?"],
                "xp": 35,
            },
            {
                "id": "wp_04",
                "title": "Sharing Treasure",
                "type": "fill_blank",
                "question": "Four friends find [bold yellow]28[/bold yellow] gold coins. They share them equally. How many coins does each friend get?\n[bold white]28 / 4 = ?[/bold white]",
                "lesson": "28 / 4 = [bold yellow]7[/bold yellow] coins each. Sharing equally means dividing!",
                "options": [],
                "answer": "7",
                "hints": ["28 coins split into 4 equal piles!", "4 x ? = 28"],
                "xp": 35,
            },
            {
                "id": "wp_05",
                "title": "School Supplies",
                "type": "quiz",
                "question": "Pencils come in packs of [bold yellow]8[/bold yellow]. You buy [bold yellow]3[/bold yellow] packs. Then you give away [bold yellow]4[/bold yellow] pencils. How many do you have?",
                "lesson": "First multiply: 8 x 3 = 24 pencils. Then subtract: 24 - 4 = [bold yellow]20[/bold yellow]. Some problems need two steps!",
                "options": ["18", "20", "22", "24"],
                "answer": "b",
                "hints": ["First figure out how many pencils in 3 packs, then subtract 4!", "8 x 3 = 24, then 24 - 4 = ?"],
                "xp": 40,
            },
            {
                "id": "wp_06",
                "title": "Pizza Party",
                "type": "fill_blank",
                "question": "Each pizza has [bold yellow]8[/bold yellow] slices. You order [bold yellow]3[/bold yellow] pizzas and your friends eat [bold yellow]17[/bold yellow] slices. How many slices are left?\n[bold white](8 x 3) - 17 = ?[/bold white]",
                "lesson": "8 x 3 = 24 slices total. 24 - 17 = [bold yellow]7[/bold yellow] slices left. Two-step problems: multiply first, then subtract!",
                "options": [],
                "answer": "7",
                "hints": ["First find the total slices: 8 x 3 = 24!", "Then subtract what was eaten: 24 - 17 = ?"],
                "xp": 45,
            },
            {
                "id": "wp_07",
                "title": "Saving Coins",
                "type": "quiz",
                "question": "You save [bold yellow]5[/bold yellow] coins every day for [bold yellow]7[/bold yellow] days. Then you spend [bold yellow]10[/bold yellow] coins. How many coins do you have?",
                "lesson": "5 x 7 = 35 coins saved. 35 - 10 = [bold yellow]25[/bold yellow] coins left. Break word problems into steps!",
                "options": ["30", "25", "20", "35"],
                "answer": "b",
                "hints": ["First: how many coins after 7 days? 5 x 7!", "35 - 10 = ?"],
                "xp": 45,
            },
            {
                "id": "wp_boss",
                "title": "The Math Playground Champion",
                "type": "fill_blank",
                "question": "A toy store has [bold yellow]4[/bold yellow] shelves. Each shelf holds [bold yellow]9[/bold yellow] toys. If [bold yellow]15[/bold yellow] toys are sold, how many toys are still on the shelves?\n[bold white](4 x 9) - 15 = ?[/bold white]",
                "lesson": "4 x 9 = 36 toys total. 36 - 15 = [bold yellow]21[/bold yellow] toys remaining. You used multiplication AND subtraction — amazing!",
                "options": [],
                "answer": "21",
                "hints": ["Start by finding the total: 4 shelves x 9 toys each!", "36 - 15 = ?"],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },
}
