"""
zones.py — Daily Life zones and challenges for the Daily Life skill pack.

All challenges use "type": "quiz" with multiple-choice options.
Guided by 龙龙 (Lóng Lóng), a friendly dragon guide.
"""

ZONE_ORDER = [
    "morning_routine",
    "school_work",
    "hobbies",
    "weather",
    "shopping",
    "colors",
    "body_parts",
]

ZONES = {
    "morning_routine": {
        "id": "morning_routine",
        "name": "Rise and Shine",
        "description": "Learn the words for your morning routine",
        "level_required": 1,
        "challenges": [
            {
                "id": "morning_wake_up",
                "title": "Time to Wake Up",
                "type": "quiz",
                "question": "起床 (qǐchuáng) means...?",
                "options": ["Go to sleep", "Get up / wake up", "Take a shower", "Eat breakfast"],
                "answer": "b",
                "hints": [
                    "起 means 'to rise' and 床 means 'bed.'",
                    "Literally: 'rise from bed.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "起床 (qǐchuáng) = get up / wake up. 起 = rise, 床 = bed. The opposite is 上床 (shàngchuáng) = go to bed. 我每天七点起床 = 'I get up at 7 every day.'",
                "is_boss": False,
                "flavor": "龙龙 stretches its wings and yawns. 'Every day starts with 起床!'",
            },
            {
                "id": "morning_brush_teeth",
                "title": "Sparkle and Shine",
                "type": "quiz",
                "question": "刷牙 (shuā yá) literally means 'brush + teeth.' What action is it?",
                "options": ["Wash face", "Brush teeth", "Comb hair", "Take a bath"],
                "answer": "b",
                "hints": [
                    "刷 means 'to brush/scrub' and 牙 means 'tooth/teeth.'",
                    "A very literal compound — Chinese does this a lot!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "刷牙 (shuā yá) = brush teeth. Chinese morning routine words are wonderfully literal: verb + body part. 牙刷 (yáshuā) reverses the characters to mean 'toothbrush' — the tool!",
                "is_boss": False,
                "flavor": "龙龙 shows off a row of gleaming dragon teeth.",
            },
            {
                "id": "morning_wash_face",
                "title": "Fresh and Clean",
                "type": "quiz",
                "question": "洗脸 (xǐ liǎn) means...?",
                "options": ["Wash hands", "Wash face", "Wash hair", "Take a shower"],
                "answer": "b",
                "hints": [
                    "洗 means 'to wash' — it has the water radical 氵 on the left.",
                    "脸 means 'face.' Verb + body part again!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "洗脸 (xǐ liǎn) = wash face. 洗 (to wash) combines with many body parts: 洗手 (wash hands), 洗头 (wash hair), 洗澡 (take a bath/shower). The 氵radical means water!",
                "is_boss": False,
                "flavor": "龙龙 splashes water on its face with its tail.",
            },
            {
                "id": "morning_eat_breakfast",
                "title": "The First Meal",
                "type": "quiz",
                "question": "吃早饭 (chī zǎofàn) means 'eat breakfast.' What does 早 (zǎo) mean?",
                "options": ["Late", "Early / morning", "Noon", "Evening"],
                "answer": "b",
                "hints": [
                    "早 appears in 早上 (zǎoshang) meaning 'morning.'",
                    "早饭 literally means 'early meal / morning meal.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "吃早饭 (chī zǎofàn) = eat breakfast. The three meals: 早饭 (breakfast, morning meal), 午饭 (wǔfàn, lunch, noon meal), 晚饭 (wǎnfàn, dinner, evening meal). Simple and logical!",
                "is_boss": False,
                "flavor": "龙龙 munches on a steaming 包子 (bāozi, steamed bun).",
            },
            {
                "id": "morning_go_out",
                "title": "Out the Door",
                "type": "quiz",
                "question": "出门 (chūmén) means...?",
                "options": ["Come home", "Go out / leave the house", "Open the door", "Lock the door"],
                "answer": "b",
                "hints": [
                    "出 means 'to exit/go out' and 门 means 'door/gate.'",
                    "Literally: 'exit the door' = leave the house.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "出门 (chūmén) = go out / leave the house. 出 = exit, 门 = door. The opposite is 回家 (huíjiā) = go home / return home. 我八点出门 = 'I leave the house at 8.'",
                "is_boss": False,
                "flavor": "龙龙 pushes open a grand dragon-sized door.",
            },
            {
                "id": "morning_sequence",
                "title": "The Right Order",
                "type": "quiz",
                "question": "Put the morning routine in the correct order:",
                "options": [
                    "起床 → 刷牙 → 洗脸 → 吃早饭 → 出门",
                    "出门 → 起床 → 吃早饭 → 刷牙 → 洗脸",
                    "吃早饭 → 起床 → 出门 → 刷牙 → 洗脸",
                    "刷牙 → 洗脸 → 起床 → 出门 → 吃早饭",
                ],
                "answer": "a",
                "hints": [
                    "First you get out of bed (起床), last you leave the house (出门).",
                    "You brush teeth and wash face BEFORE eating breakfast.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A typical Chinese morning: 起床 → 刷牙 → 洗脸 → 吃早饭 → 出门. Learning vocabulary in sequences helps you remember the words AND use them in real life!",
                "is_boss": True,
                "flavor": "龙龙 acts out the entire morning routine at dragon speed.",
            },
        ],
    },
    "school_work": {
        "id": "school_work",
        "name": "School and Work",
        "description": "Learn words for school and work life",
        "level_required": 2,
        "challenges": [
            {
                "id": "sw_school",
                "title": "The Learning Place",
                "type": "quiz",
                "question": "学校 (xuéxiào) means...?",
                "options": ["Library", "Hospital", "School", "Office"],
                "answer": "c",
                "hints": [
                    "学 means 'to learn/study' and 校 means 'school/institution.'",
                    "The same 学 appears in 学生 (xuéshēng, student).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "学校 (xuéxiào) = school. 学 = learn, 校 = institution. Related words: 小学 (primary school), 中学 (middle school), 大学 (university). 上学 (shàngxué) = go to school.",
                "is_boss": False,
                "flavor": "龙龙 carries a tiny dragon-sized backpack.",
            },
            {
                "id": "sw_go_to_work",
                "title": "Off to the Office",
                "type": "quiz",
                "question": "上班 (shàngbān) means 'go to work.' What does 下班 (xiàbān) mean?",
                "options": ["Start work", "Get off work / finish work", "Skip work", "Work overtime"],
                "answer": "b",
                "hints": [
                    "上 means 'up/go to' and 下 means 'down/get off.' They're opposites!",
                    "Just like 上学/放学 (start school / finish school).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "上班 (shàngbān) = go to work. 下班 (xiàbān) = get off work. The 上/下 pattern is everywhere: 上课/下课 (start/end class), 上车/下车 (get on/off a vehicle).",
                "is_boss": False,
                "flavor": "龙龙 checks a tiny wristwatch. 'Time to 下班!'",
            },
            {
                "id": "sw_homework",
                "title": "After School",
                "type": "quiz",
                "question": "作业 (zuòyè) is something every student must do. What is it?",
                "options": ["Sports practice", "Homework", "Music class", "Field trip"],
                "answer": "b",
                "hints": [
                    "作 means 'to do/make' and 业 means 'work/task.'",
                    "做作业 (zuò zuòyè) = 'do homework.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "作业 (zuòyè) = homework. Chinese students are famous for doing lots of homework! 做作业 (zuò zuòyè) = do homework. 写作业 (xiě zuòyè) = write homework. A key daily activity.",
                "is_boss": False,
                "flavor": "龙龙 groans dramatically. 'Even dragons dislike 作业!'",
            },
            {
                "id": "sw_exam",
                "title": "The Big Test",
                "type": "quiz",
                "question": "考试 (kǎoshì) is a word that makes many students nervous. It means...?",
                "options": ["Vacation", "Exam / test", "Graduation", "Homework"],
                "answer": "b",
                "hints": [
                    "考 means 'to test/examine' and 试 means 'to try/test.'",
                    "China has a huge exam culture — the 高考 (gāokǎo) university entrance exam is legendary.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "考试 (kǎoshì) = exam/test. China has one of the world's oldest exam traditions — the imperial exam (科举, kējǔ) dates back 1,400 years! The modern 高考 (gāokǎo) is one of the most important exams in the world.",
                "is_boss": False,
                "flavor": "龙龙 nervously sharpens a pencil with its claw.",
            },
            {
                "id": "sw_work_life",
                "title": "The 996 Question",
                "type": "quiz",
                "question": "In China, '996' (九九六) refers to a controversial work schedule. What does it mean?",
                "options": [
                    "9am to 9pm, 6 days a week",
                    "9 hours a day, 9 months a year, 6 holidays",
                    "Working from age 9 to 96",
                    "9 tasks, 9 meetings, 6 reports",
                ],
                "answer": "a",
                "hints": [
                    "The three numbers stand for: start time, end time, days per week.",
                    "This intense work culture has been widely debated in China.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "996 (jiǔjiǔliù) = 9am to 9pm, 6 days a week — a grueling tech industry schedule. Jack Ma famously called it a 'blessing,' sparking massive debate. It was officially ruled illegal in 2021. Work-life balance (工作生活平衡) is now a hot topic.",
                "is_boss": True,
                "flavor": "龙龙 yawns. 'Even dragons need rest! 996 is too much!'",
            },
        ],
    },
    "hobbies": {
        "id": "hobbies",
        "name": "Fun and Free Time",
        "description": "Learn words for hobbies and leisure activities",
        "level_required": 3,
        "challenges": [
            {
                "id": "hobby_read",
                "title": "Lost in a Book",
                "type": "quiz",
                "question": "看书 (kàn shū) means...?",
                "options": ["Write a book", "Buy a book", "Read a book", "Return a book"],
                "answer": "c",
                "hints": [
                    "看 means 'to look/watch/read' and 书 means 'book.'",
                    "看 is versatile: 看电影 (watch a movie), 看电视 (watch TV), 看书 (read a book).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "看书 (kàn shū) = read a book. 看 is one of Chinese's most useful verbs — it covers 'look,' 'watch,' and 'read.' The character 书 (book) is a beautiful simplified form of the traditional 書.",
                "is_boss": False,
                "flavor": "龙龙 opens a giant book and peers inside.",
            },
            {
                "id": "hobby_music",
                "title": "Sweet Sounds",
                "type": "quiz",
                "question": "听音乐 (tīng yīnyuè) means 'listen to music.' What does 听 (tīng) mean?",
                "options": ["To play", "To listen", "To sing", "To dance"],
                "answer": "b",
                "hints": [
                    "听 is the verb for the ear — just as 看 is for the eye.",
                    "The simplified character 听 replaced the traditional 聽, which contained the ear radical 耳.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "听 (tīng) = to listen. 音乐 (yīnyuè) = music (sound + joy). 听音乐 = listen to music. Other listening phrases: 听歌 (listen to songs), 听话 (be obedient, literally 'listen to words').",
                "is_boss": False,
                "flavor": "龙龙 hums a melody, a bit off-key but enthusiastic.",
            },
            {
                "id": "hobby_sports",
                "title": "Get Moving!",
                "type": "quiz",
                "question": "运动 (yùndòng) means...?",
                "options": ["Rest", "Exercise / sports", "Travel", "Competition"],
                "answer": "b",
                "hints": [
                    "运 means 'to move/transport' and 动 means 'to move/act.'",
                    "运动会 (yùndònghuì) = sports meet / athletic competition.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "运动 (yùndòng) = exercise/sports. Popular sports in China: 乒乓球 (pīngpāngqiú, table tennis — China's national sport!), 篮球 (lánqiú, basketball), 足球 (zúqiú, soccer).",
                "is_boss": False,
                "flavor": "龙龙 does dragon push-ups. 'One... two... three...'",
            },
            {
                "id": "hobby_draw",
                "title": "Brush and Ink",
                "type": "quiz",
                "question": "画画 (huà huà) means...?",
                "options": ["Take photos", "Draw / paint", "Write calligraphy", "Do crafts"],
                "answer": "b",
                "hints": [
                    "画 means both 'to draw/paint' (verb) and 'painting' (noun).",
                    "Doubling the character makes it a casual, everyday expression.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "画画 (huà huà) = to draw/paint (casual). 画 alone can mean 'painting' (noun) or 'to paint' (verb). 中国画 (zhōngguóhuà) = Chinese painting. 油画 (yóuhuà) = oil painting.",
                "is_boss": False,
                "flavor": "龙龙 paints a self-portrait in ink — it's surprisingly good!",
            },
            {
                "id": "hobby_games",
                "title": "Let's Play!",
                "type": "quiz",
                "question": "玩游戏 (wán yóuxì) means 'play games.' What does 玩 (wán) mean?",
                "options": ["To work", "To play / have fun", "To compete", "To win"],
                "answer": "b",
                "hints": [
                    "玩 is the general verb for 'to play' or 'to have fun.'",
                    "It has the 王 (king/jade) radical — play was associated with jade toys!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "玩 (wán) = to play/have fun. 游戏 (yóuxì) = game. 电子游戏 (diànzǐ yóuxì) = video game. China has the world's largest gaming market! 好玩 (hǎowán) = fun/interesting.",
                "is_boss": False,
                "flavor": "龙龙 picks up a game controller with its claws — awkwardly, but determined.",
            },
            {
                "id": "hobby_ask",
                "title": "What's Your Hobby?",
                "type": "quiz",
                "question": "How do you ask 'What are your hobbies?' in Chinese?",
                "options": [
                    "你喜欢什么? (Nǐ xǐhuan shénme?)",
                    "你的爱好是什么? (Nǐ de àihào shì shénme?)",
                    "你做什么工作? (Nǐ zuò shénme gōngzuò?)",
                    "你想去哪里? (Nǐ xiǎng qù nǎlǐ?)",
                ],
                "answer": "b",
                "hints": [
                    "爱好 (àihào) means 'hobby/interest.' 是什么 means 'is what.'",
                    "你喜欢什么 works too but is more like 'What do you like?'",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "你的爱好是什么? (Nǐ de àihào shì shénme?) = 'What are your hobbies?' 爱好 = hobby (love + good). This is a classic getting-to-know-you question in Chinese conversation.",
                "is_boss": True,
                "flavor": "龙龙 counts on its claws. 'My 爱好: flying, breathing fire, and teaching Chinese!'",
            },
        ],
    },
    "weather": {
        "id": "weather",
        "name": "Wind, Rain, and Sun",
        "description": "Talk about the weather in Chinese",
        "level_required": 4,
        "challenges": [
            {
                "id": "weather_ask",
                "title": "The Universal Question",
                "type": "quiz",
                "question": "天气怎么样? (Tiānqì zěnmeyàng?) means...?",
                "options": [
                    "What time is it?",
                    "How's the weather?",
                    "Where are you going?",
                    "How are you?",
                ],
                "answer": "b",
                "hints": [
                    "天气 (tiānqì) = weather. 怎么样 (zěnmeyàng) = how is it?",
                    "天 = sky/day, 气 = air/atmosphere.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "天气怎么样? (Tiānqì zěnmeyàng?) = 'How's the weather?' 天气 = weather (sky + air). 怎么样 = 'how is it' — a pattern you can use for anything: 工作怎么样? (How's work?)",
                "is_boss": False,
                "flavor": "龙龙 looks up at the sky with a claw shading its eyes.",
            },
            {
                "id": "weather_hot",
                "title": "Scorching!",
                "type": "quiz",
                "question": "热 (rè) means...?",
                "options": ["Cold", "Hot", "Warm", "Cool"],
                "answer": "b",
                "hints": [
                    "热 has four dots at the bottom — the fire radical 灬!",
                    "rè — fourth tone, sharp and falling like heat hitting you.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "热 (rè) = hot. The fire radical 灬 at the bottom gives it away! 很热 = very hot. 热水 (rè shuǐ) = hot water — Chinese people believe in drinking hot water for health! 你要喝热水 is classic advice.",
                "is_boss": False,
                "flavor": "龙龙 breathes a flame. 'Hot? I know hot!'",
            },
            {
                "id": "weather_cold",
                "title": "Brrr!",
                "type": "quiz",
                "question": "The opposite of 热 (rè, hot) is...?",
                "options": ["冷 (lěng)", "暖 (nuǎn)", "凉 (liáng)", "闷 (mēn)"],
                "answer": "a",
                "hints": [
                    "冷 has the ice radical 冫on the left — two dots representing ice.",
                    "lěng — third tone, the dipping tone.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "冷 (lěng) = cold. The ice radical 冫tells you it's temperature-related. 好冷! = So cold! Temperature words: 热 (hot) → 暖和 (warm) → 凉快 (cool) → 冷 (cold).",
                "is_boss": False,
                "flavor": "龙龙 shivers. 'Even dragons feel the 冷!'",
            },
            {
                "id": "weather_rain",
                "title": "Drip Drop",
                "type": "quiz",
                "question": "下雨 (xià yǔ) means...?",
                "options": ["It's snowing", "It's raining", "It's windy", "It's cloudy"],
                "answer": "b",
                "hints": [
                    "下 means 'to fall/come down' and 雨 means 'rain.'",
                    "雨 is a beautiful pictograph — it shows rain falling from a cloud!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "下雨 (xià yǔ) = it's raining. 下 = to fall, 雨 = rain. The character 雨 is a pictograph showing rain falling from the sky. 雨 is also a radical that appears in many weather characters: 雪, 雷, 霜, 雾.",
                "is_boss": False,
                "flavor": "龙龙 opens an umbrella with its tail.",
            },
            {
                "id": "weather_snow",
                "title": "Winter Wonderland",
                "type": "quiz",
                "question": "下雪 (xià xuě) means 'it's snowing.' What does the character 雪 contain?",
                "options": [
                    "Rain radical (雨) on top",
                    "Fire radical (火) on top",
                    "Water radical (水) on the left",
                    "Ice radical (冫) on the left",
                ],
                "answer": "a",
                "hints": [
                    "Snow is frozen rain — so the rain radical 雨 sits on top.",
                    "Below the rain radical is 彐, adding to the meaning.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "雪 (xuě) = snow. It has 雨 (rain) on top because snow is a form of precipitation. Many weather characters share this radical: 雷 (léi, thunder), 霜 (shuāng, frost), 雾 (wù, fog). Chinese radicals tell stories!",
                "is_boss": False,
                "flavor": "龙龙 catches snowflakes on its tongue.",
            },
            {
                "id": "weather_sunny",
                "title": "Blue Skies",
                "type": "quiz",
                "question": "晴天 (qíngtiān) means...?",
                "options": ["Rainy day", "Cloudy day", "Sunny day / clear sky", "Foggy day"],
                "answer": "c",
                "hints": [
                    "晴 has the sun radical 日 on the left — indicating good weather.",
                    "天 means 'day' or 'sky.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "晴天 (qíngtiān) = sunny day. 晴 = clear/fine, 天 = day/sky. Weather vocabulary: 晴天 (sunny), 阴天 (yīntiān, cloudy), 雨天 (yǔtiān, rainy), 雪天 (xuětiān, snowy).",
                "is_boss": True,
                "flavor": "龙龙 basks in the warm sunshine, wings spread wide.",
            },
        ],
    },
    "shopping": {
        "id": "shopping",
        "name": "Let's Go Shopping!",
        "description": "Learn essential shopping vocabulary",
        "level_required": 5,
        "challenges": [
            {
                "id": "shop_buy",
                "title": "The Essential Verb",
                "type": "quiz",
                "question": "买东西 (mǎi dōngxi) means...?",
                "options": ["Sell things", "Buy things / go shopping", "Return things", "Make things"],
                "answer": "b",
                "hints": [
                    "买 (mǎi) means 'to buy.' 东西 (dōngxi) means 'things/stuff.'",
                    "Be careful: 买 (mǎi, buy, third tone) vs 卖 (mài, sell, fourth tone) — one stroke difference!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "买东西 (mǎi dōngxi) = buy things / go shopping. 买 (buy) and 卖 (sell) are near-identical — 卖 has an extra stroke on top. 东西 literally means 'east-west' but colloquially means 'stuff/things.'",
                "is_boss": False,
                "flavor": "龙龙 pulls out a coin purse from behind its scales.",
            },
            {
                "id": "shop_store",
                "title": "Where to Shop",
                "type": "quiz",
                "question": "商店 (shāngdiàn) means 'shop/store.' What does 超市 (chāoshì) mean?",
                "options": ["Mall", "Supermarket", "Market", "Convenience store"],
                "answer": "b",
                "hints": [
                    "超 means 'super/exceed' and 市 means 'market.'",
                    "超市 is a shortened form of 超级市场 (chāojí shìchǎng).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "商店 (shāngdiàn) = shop/store. 超市 (chāoshì) = supermarket (super + market). Other shopping places: 市场 (shìchǎng, market), 商场 (shāngchǎng, mall/shopping center), 便利店 (biànlìdiàn, convenience store).",
                "is_boss": False,
                "flavor": "龙龙 pushes a tiny shopping cart down the aisle.",
            },
            {
                "id": "shop_expensive",
                "title": "The Price Is...",
                "type": "quiz",
                "question": "贵 (guì) means 'expensive.' What is its opposite?",
                "options": ["便宜 (piányi)", "多 (duō)", "好 (hǎo)", "新 (xīn)"],
                "answer": "a",
                "hints": [
                    "便宜 literally means 'convenient + suitable' — things that are easy on the wallet.",
                    "太贵了! (Tài guì le!) = Too expensive! — the most useful haggling phrase.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "贵 (guì) = expensive. 便宜 (piányi) = cheap/inexpensive. 太贵了! (Tài guì le!) = Too expensive! 便宜一点 (piányi yìdiǎn) = A little cheaper please. Essential haggling vocabulary!",
                "is_boss": False,
                "flavor": "龙龙 examines a price tag and gasps dramatically. '太贵了!'",
            },
            {
                "id": "shop_discount",
                "title": "Bargain Hunter",
                "type": "quiz",
                "question": "打折 (dǎzhé) means 'to give a discount.' If something is 八折 (bā zhé), how much do you pay?",
                "options": ["8% of the price", "80% of the price (20% off)", "18% off", "8 yuan off"],
                "answer": "b",
                "hints": [
                    "Chinese discounts work differently from Western ones — 八折 means you pay 8/10 of the price.",
                    "七折 = 70% of the price = 30% off.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "打折 (dǎzhé) = discount. Chinese uses a '10-based' system: 八折 = pay 80% (20% off), 七折 = pay 70% (30% off), 五折 = pay 50% (half price!). This confuses many foreigners — remember, the number is what you PAY, not what you save!",
                "is_boss": False,
                "flavor": "龙龙 does quick math on an abacus. 'Chinese discounts — tricky but logical!'",
            },
            {
                "id": "shop_how_much",
                "title": "How Much?",
                "type": "quiz",
                "question": "多少钱? (Duōshao qián?) means...?",
                "options": [
                    "Do you have change?",
                    "How much money? / How much does it cost?",
                    "Can I pay by card?",
                    "Is this on sale?",
                ],
                "answer": "b",
                "hints": [
                    "多少 means 'how much/how many' and 钱 means 'money.'",
                    "This is THE most important phrase for any shopper in China!",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "多少钱? (Duōshao qián?) = How much does it cost? 多少 = how much, 钱 = money. In modern China, almost everyone pays with 微信支付 (WeChat Pay) or 支付宝 (Alipay) instead of cash!",
                "is_boss": True,
                "flavor": "龙龙 holds up a phone showing a QR code. '现在大家都用手机付款!' (Everyone pays by phone now!)",
            },
        ],
    },
    "colors": {
        "id": "colors",
        "name": "A World of Color",
        "description": "Learn the colors in Chinese",
        "level_required": 6,
        "challenges": [
            {
                "id": "color_red",
                "title": "The Luckiest Color",
                "type": "quiz",
                "question": "红 (hóng) is the most important color in Chinese culture. What color is it?",
                "options": ["Blue", "Yellow", "Red", "Gold"],
                "answer": "c",
                "hints": [
                    "This color dominates Chinese New Year, weddings, and celebrations.",
                    "红包 (hóngbāo) — red envelopes filled with money — use this color.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "红 (hóng) = red. Red is THE color of Chinese culture — it symbolizes luck, joy, and prosperity. 红包 (red envelope with money), 红灯笼 (red lanterns), and red wedding dresses all use this auspicious color.",
                "is_boss": False,
                "flavor": "龙龙 unfurls a red banner. 'Red is my favorite color — it means good luck!'",
            },
            {
                "id": "color_blue",
                "title": "Sky and Sea",
                "type": "quiz",
                "question": "蓝 (lán) means...?",
                "options": ["Green", "Blue", "Purple", "Gray"],
                "answer": "b",
                "hints": [
                    "蓝 has the grass radical 艹 on top — the color was originally derived from a plant dye.",
                    "蓝天 (lántiān) = blue sky.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "蓝 (lán) = blue. 蓝天白云 (lántiān báiyún) = 'blue sky, white clouds' — a phrase for perfect weather. The traditional blue dye came from the indigo plant, hence the grass radical 艹.",
                "is_boss": False,
                "flavor": "龙龙 gazes up at the endless blue sky.",
            },
            {
                "id": "color_green",
                "title": "Nature's Color",
                "type": "quiz",
                "question": "绿 (lǜ) means 'green.' Why should you NEVER give someone a green hat in China?",
                "options": [
                    "Green is considered unlucky",
                    "戴绿帽子 (wear a green hat) means your partner is cheating on you",
                    "Green hats are only for soldiers",
                    "Green is the color of sadness",
                ],
                "answer": "b",
                "hints": [
                    "戴绿帽子 (dài lǜ màozi) is a famous Chinese idiom about infidelity.",
                    "This cultural taboo makes green hats an extremely awkward gift!",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "绿 (lǜ) = green. Cultural warning: 戴绿帽子 (wearing a green hat) means your partner is unfaithful — never give a green hat as a gift in China! This idiom dates back centuries. 绿茶 (lǜchá) = green tea — that's fine!",
                "is_boss": False,
                "flavor": "龙龙 waves a green flag. 'Green is great — just not on hats!'",
            },
            {
                "id": "color_yellow",
                "title": "The Imperial Color",
                "type": "quiz",
                "question": "黄 (huáng) means 'yellow.' In ancient China, who was allowed to wear yellow?",
                "options": ["Everyone", "Only the emperor", "Only women", "Only soldiers"],
                "answer": "b",
                "hints": [
                    "Yellow was the imperial color — 黄帝 (Huángdì) means 'Yellow Emperor.'",
                    "The 黄河 (Yellow River) is called 'the cradle of Chinese civilization.'",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "黄 (huáng) = yellow. Yellow was reserved for the emperor — ordinary people wearing yellow could be executed! 黄帝 (Yellow Emperor) is the legendary ancestor of all Chinese. 黄河 (Yellow River) is China's mother river.",
                "is_boss": False,
                "flavor": "龙龙 dons a tiny imperial yellow robe. 'I'm the emperor dragon today!'",
            },
            {
                "id": "color_white_black",
                "title": "Light and Dark",
                "type": "quiz",
                "question": "白 (bái) means 'white.' In Chinese culture, white is the color of...?",
                "options": ["Weddings and joy", "Funerals and mourning", "Spring festivals", "Good luck"],
                "answer": "b",
                "hints": [
                    "This is the OPPOSITE of Western culture, where white = weddings!",
                    "Chinese funerals use white flowers and white clothing.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "白 (bái) = white. 黑 (hēi) = black. Cultural difference: white is the color of mourning in China (funerals), while red is for celebrations (weddings). This is opposite to Western culture! 黑白 (hēibái) = black and white.",
                "is_boss": False,
                "flavor": "龙龙 holds a yin-yang symbol — black and white in perfect balance.",
            },
            {
                "id": "color_pink",
                "title": "Blushing Pink",
                "type": "quiz",
                "question": "粉红 (fěnhóng) literally means 'powder + red.' What color is it?",
                "options": ["Orange", "Pink", "Maroon", "Peach"],
                "answer": "b",
                "hints": [
                    "粉 means 'powder' — think of pink as a powdery, lighter version of red.",
                    "粉红色 (fěnhóngsè) — adding 色 (sè, color) makes it a full color word.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "粉红 (fěnhóng) = pink. Literally 'powder red.' Chinese creates color variations logically: 深蓝 (shēnlán, dark blue), 浅绿 (qiǎnlǜ, light green), 粉红 (powder red = pink). Adding 色 (sè) makes any word a color.",
                "is_boss": True,
                "flavor": "龙龙 blows pink smoke rings. 'Colors carry meaning in every culture!'",
            },
        ],
    },
    "body_parts": {
        "id": "body_parts",
        "name": "Head, Shoulders, Knees, and Toes",
        "description": "Learn the words for body parts in Chinese",
        "level_required": 7,
        "challenges": [
            {
                "id": "body_head",
                "title": "The Top",
                "type": "quiz",
                "question": "头 (tóu) means...?",
                "options": ["Hand", "Head", "Heart", "Hair"],
                "answer": "b",
                "hints": [
                    "头 is also used as a measure word for large animals: 一头牛 (one cow).",
                    "头疼 (tóuténg) = headache.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "头 (tóu) = head. 头发 (tóufa) = hair. 头疼 (tóuténg) = headache. 点头 (diǎntóu) = nod (dot the head). Fun fact: 头 is also the measure word for cattle and other large animals!",
                "is_boss": False,
                "flavor": "龙龙 taps its horned head. 'The 头 carries the horns — the best part!'",
            },
            {
                "id": "body_hand",
                "title": "The Workers",
                "type": "quiz",
                "question": "手 (shǒu) means 'hand.' Which phrase uses 手?",
                "options": [
                    "手机 (shǒujī) — mobile phone",
                    "头发 (tóufa) — hair",
                    "眼睛 (yǎnjing) — eyes",
                    "耳朵 (ěrduo) — ears",
                ],
                "answer": "a",
                "hints": [
                    "手机 literally means 'hand + machine' — the machine you hold in your hand!",
                    "手 is a pictograph that looks like a hand with five fingers.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "手 (shǒu) = hand. 手机 (shǒujī) = mobile phone (hand machine). 握手 (wòshǒu) = handshake. 左手 (zuǒshǒu) = left hand. 右手 (yòushǒu) = right hand. The character is a simplified pictograph of a hand.",
                "is_boss": False,
                "flavor": "龙龙 waves its five-clawed dragon hand.",
            },
            {
                "id": "body_foot",
                "title": "The Foundation",
                "type": "quiz",
                "question": "脚 (jiǎo) means...?",
                "options": ["Knee", "Foot", "Leg", "Toe"],
                "answer": "b",
                "hints": [
                    "脚 has the flesh/body radical 月 on the left.",
                    "脚步 (jiǎobù) = footstep.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "脚 (jiǎo) = foot. 脚步 (jiǎobù) = footstep. 赤脚 (chìjiǎo) = barefoot. Many body part characters have the 月 radical (originally 肉, flesh): 脚, 脸, 胖, 脑.",
                "is_boss": False,
                "flavor": "龙龙 stomps its big dragon feet. 'Dragon 脚 are very big!'",
            },
            {
                "id": "body_eyes",
                "title": "The Windows",
                "type": "quiz",
                "question": "眼睛 (yǎnjing) means...?",
                "options": ["Mouth", "Nose", "Eyes", "Eyebrows"],
                "answer": "c",
                "hints": [
                    "Both characters contain 目 (mù), the eye radical.",
                    "眼 = eye (formal), 睛 = eyeball/pupil.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "眼睛 (yǎnjing) = eyes. 目 (mù) is the eye radical — it appears in many vision words: 看 (kàn, look), 睡 (shuì, sleep — eyes closed!), 盲 (máng, blind). 眼镜 (yǎnjìng) = glasses.",
                "is_boss": False,
                "flavor": "龙龙 blinks its big golden dragon eyes.",
            },
            {
                "id": "body_mouth",
                "title": "The Speaker",
                "type": "quiz",
                "question": "嘴巴 (zuǐba) means 'mouth.' The character 口 (kǒu) is a simpler word for mouth. Where else do you see 口?",
                "options": [
                    "Inside many characters as a radical meaning 'mouth/opening'",
                    "Only in the word 嘴巴",
                    "As a number",
                    "As a color word",
                ],
                "answer": "a",
                "hints": [
                    "口 is one of the most common radicals in Chinese.",
                    "Look at 吃 (eat), 喝 (drink), 唱 (sing) — they all have 口!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "嘴巴 (zuǐba) = mouth. 口 (kǒu) is the mouth radical — it appears in tons of characters: 吃 (chī, eat), 喝 (hē, drink), 唱 (chàng, sing), 呢 (ne), 吗 (ma). If a character has 口, it usually relates to the mouth!",
                "is_boss": False,
                "flavor": "龙龙 opens its mouth wide — revealing many, many teeth.",
            },
            {
                "id": "body_ears",
                "title": "The Listeners",
                "type": "quiz",
                "question": "耳朵 (ěrduo) means 'ears.' The radical 耳 appears in which of these words?",
                "options": [
                    "聪明 (cōngming) — smart/clever",
                    "漂亮 (piàoliang) — beautiful",
                    "高兴 (gāoxìng) — happy",
                    "便宜 (piányi) — cheap",
                ],
                "answer": "a",
                "hints": [
                    "聪 has 耳 on the left — being smart starts with good listening!",
                    "The ancient Chinese believed wisdom came through the ears.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "耳朵 (ěrduo) = ears. 耳 (ear) appears in 聪明 (cōngming, smart) — the Chinese believed a clever person listens well! 聪 = 耳 + 总 (ear + encompassing) = someone who hears and understands everything.",
                "is_boss": True,
                "flavor": "龙龙 cups a dragon ear. 'Big ears for big listening! That's how you learn Chinese!'",
            },
        ],
    },
}
