"""
zones.py — AI Ethics zones and challenges for the AI Ethics skill pack.

All challenges use "type": "quiz" with multiple-choice options.
Designed for teens and adults. Nuanced, balanced perspectives on
the ethical dimensions of artificial intelligence.
"""

ZONE_ORDER = [
    "bias_in_ai",
    "hallucinations",
    "copyright_and_ip",
    "deepfakes_and_misinfo",
    "privacy_and_data",
    "ai_and_jobs",
    "responsible_use",
]

ZONES = {
    "bias_in_ai": {
        "id": "bias_in_ai",
        "name": "The Mirror's Flaw",
        "description": "How training data bias shapes AI decisions — and who gets hurt",
        "level_required": 1,
        "challenges": [
            {
                "id": "bias_what_is",
                "title": "Garbage In, Bias Out",
                "type": "quiz",
                "question": "An AI hiring tool trained mostly on resumes from male engineers starts scoring women lower. What is the most accurate explanation?",
                "options": [
                    "The AI is sexist and has personal prejudice",
                    "The AI learned patterns from biased historical data",
                    "Women genuinely perform worse in engineering",
                    "The AI randomly generates scores",
                ],
                "answer": "b",
                "hints": [
                    "AI doesn't have opinions — it reflects the data it was trained on.",
                    "If past hiring favored men, the model learns to replicate that pattern.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "AI systems learn patterns from historical data. If that data reflects decades of biased human decisions, the AI will reproduce those biases — not because it 'wants' to, but because bias is baked into the patterns it learned. This is why diverse, carefully curated training data matters enormously.",
                "is_boss": False,
                "flavor": "ARIA pulls up a job application. The algorithm has already decided — before reading a single word.",
            },
            {
                "id": "bias_representation",
                "title": "Who's Missing?",
                "type": "quiz",
                "question": "An image generation AI consistently produces lighter-skinned people when asked to generate 'a professional.' What does this most likely reveal?",
                "options": [
                    "The AI understands what professionals look like",
                    "Lighter-skinned people are more professional",
                    "The training images over-represented lighter-skinned professionals",
                    "The AI was deliberately programmed this way",
                ],
                "answer": "c",
                "hints": [
                    "Think about whose photos dominate stock image databases and business media.",
                    "The AI generates based on statistical patterns in its training set.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Representation bias occurs when training data doesn't reflect the full diversity of the real world. Stock photo databases, news media, and internet images all carry historical biases about who gets shown in which roles. AI amplifies whatever patterns it finds.",
                "is_boss": False,
                "flavor": "ARIA generates a hundred faces labeled 'professional.' The pattern is impossible to ignore.",
            },
            {
                "id": "bias_criminal_justice",
                "title": "The Sentencing Algorithm",
                "type": "quiz",
                "question": "The COMPAS algorithm, used in US courts, was found to incorrectly label Black defendants as high-risk at nearly twice the rate of white defendants. What was the core problem?",
                "options": [
                    "The algorithm deliberately targeted Black defendants",
                    "Crime statistics are always perfectly objective and unbiased",
                    "Historical policing patterns created biased training data",
                    "Algorithms cannot be used in criminal justice at all",
                ],
                "answer": "c",
                "hints": [
                    "Consider how over-policing of certain neighborhoods creates skewed arrest data.",
                    "The data reflected policing decisions, not just actual crime rates.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "The COMPAS case is a landmark example of algorithmic bias in high-stakes settings. Arrest records reflect policing patterns — if certain neighborhoods are policed more heavily, more arrests occur there, creating data that looks like those areas are more dangerous. An AI trained on this data perpetuates the cycle. This doesn't mean algorithms can never help — but they require extraordinary scrutiny when human freedom is at stake.",
                "is_boss": False,
                "flavor": "ARIA displays a courtroom where the judge consults a screen. A number appears. A life hangs in the balance.",
            },
            {
                "id": "bias_feedback_loop",
                "title": "The Spiral",
                "type": "quiz",
                "question": "A predictive policing AI sends more officers to neighborhoods with high arrest rates. More patrols lead to more arrests, which makes the AI send even more officers there. This is called a:",
                "options": [
                    "Feedback loop",
                    "Random error",
                    "Self-correcting system",
                    "Natural equilibrium",
                ],
                "answer": "a",
                "hints": [
                    "The system's own output feeds back into its input, amplifying the pattern.",
                    "More policing creates more data, which creates more policing...",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Feedback loops are one of the most dangerous forms of algorithmic bias. The AI's predictions change the real world, which generates new data that confirms the original prediction, creating a self-reinforcing spiral. Breaking these loops requires human oversight and deliberate intervention.",
                "is_boss": False,
                "flavor": "ARIA traces a spiral on screen. Each loop gets tighter. Each loop gets harder to escape.",
            },
            {
                "id": "bias_mitigation",
                "title": "Breaking the Mirror",
                "type": "quiz",
                "question": "Which approach is MOST effective for reducing bias in AI systems?",
                "options": [
                    "Simply removing race and gender from the training data",
                    "Diverse teams auditing data, testing for disparate impact, and ongoing monitoring",
                    "Letting the AI learn to be fair on its own over time",
                    "Only using AI for decisions that don't affect people",
                ],
                "answer": "b",
                "hints": [
                    "Removing protected categories doesn't work — AI finds proxy variables (zip codes, names).",
                    "Bias reduction is an ongoing process, not a one-time fix.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Simply removing race or gender from data doesn't work because AI finds correlated proxy variables. Real bias mitigation requires diverse development teams, careful data auditing, testing for disparate outcomes across groups, and continuous monitoring after deployment. It's a process, not a checkbox.",
                "is_boss": True,
                "flavor": "ARIA holds up a cracked mirror. 'The reflection was never perfect,' she says. 'But we can choose to build a better one.'",
            },
        ],
    },
    "hallucinations": {
        "id": "hallucinations",
        "name": "The Confident Liar",
        "description": "Why AI makes things up — and sounds absolutely sure about it",
        "level_required": 3,
        "challenges": [
            {
                "id": "halluc_what",
                "title": "Fluent Nonsense",
                "type": "quiz",
                "question": "A chatbot confidently states that the Golden Gate Bridge was designed by Leonardo da Vinci in 1495. This is an example of:",
                "options": [
                    "A software bug that should be easy to fix",
                    "The AI deliberately lying to mislead you",
                    "An AI hallucination — generating plausible-sounding but false information",
                    "The AI confusing two correct facts",
                ],
                "answer": "c",
                "hints": [
                    "AI language models generate text that is statistically likely, not necessarily true.",
                    "The AI doesn't 'know' facts — it predicts the next likely word.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "AI hallucination occurs when a language model generates text that sounds plausible and confident but is factually wrong. This happens because these models are trained to produce statistically likely word sequences — not to verify truth. They don't 'know' anything; they predict what words should come next.",
                "is_boss": False,
                "flavor": "ARIA reads from an AI-generated encyclopedia. Every sentence sounds perfect. Half of them are completely made up.",
            },
            {
                "id": "halluc_why",
                "title": "The Pattern Machine",
                "type": "quiz",
                "question": "Why do large language models hallucinate?",
                "options": [
                    "They have too little training data",
                    "They are designed to predict likely text, not verify factual accuracy",
                    "Their creators intentionally make them lie sometimes",
                    "They get confused when you ask hard questions",
                ],
                "answer": "b",
                "hints": [
                    "Think about what 'language model' actually means — it models language patterns.",
                    "Sounding right and being right are two very different things.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Language models are essentially sophisticated pattern-completion engines. They learn which words tend to follow other words based on billions of text examples. When they encounter a gap in their training or an ambiguous prompt, they fill it with whatever sequence seems statistically plausible — even if it's completely fictional. They optimize for fluency, not truth.",
                "is_boss": False,
                "flavor": "ARIA shows the inside of a language model: billions of connections, all predicting the next word. None of them checking if it's true.",
            },
            {
                "id": "halluc_lawyer",
                "title": "The Fake Citations",
                "type": "quiz",
                "question": "In 2023, a lawyer submitted a legal brief containing case citations that were entirely fabricated by ChatGPT. What should the lawyer have done?",
                "options": [
                    "Used a more expensive AI model",
                    "Asked the AI if the citations were real",
                    "Independently verified every citation in legal databases",
                    "Assumed the AI was correct since it was very detailed",
                ],
                "answer": "c",
                "hints": [
                    "AI can generate fake citations that look perfectly formatted and real.",
                    "The only reliable check is going to the primary source yourself.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "In Mata v. Avianca, lawyer Steven Schwartz submitted a brief with six fabricated case citations generated by ChatGPT. The cases didn't exist. Asking an AI to verify its own output doesn't help — it may just hallucinate confirmation. The only reliable safeguard is independent verification against primary sources. This case became a landmark cautionary tale.",
                "is_boss": False,
                "flavor": "ARIA pulls up a court filing. The judge's expression says it all. 'These cases do not exist,' the ruling reads.",
            },
            {
                "id": "halluc_confidence",
                "title": "The Certainty Trap",
                "type": "quiz",
                "question": "An AI responds to your question with extremely detailed, confident language including specific dates and statistics. This means the information is:",
                "options": [
                    "Definitely accurate — detail equals reliability",
                    "Probably accurate since the AI seems very sure",
                    "Not necessarily accurate — confidence and detail don't indicate truth",
                    "Always false when the AI is very specific",
                ],
                "answer": "c",
                "hints": [
                    "AI models are always confident — they don't have a 'doubt' setting by default.",
                    "Specificity in AI output is a feature of language generation, not fact-checking.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "One of the most dangerous aspects of AI hallucination is that the model's confidence level doesn't correlate with accuracy. It can hallucinate a completely fabricated statistic with the same confident tone it uses for well-established facts. Humans naturally trust confident, detailed communication — which makes hallucinations especially deceptive.",
                "is_boss": False,
                "flavor": "ARIA generates two paragraphs. Both sound equally authoritative. One is completely true. The other is completely fabricated. Can you tell which?",
            },
            {
                "id": "halluc_verify",
                "title": "Trust but Verify",
                "type": "quiz",
                "question": "What is the BEST strategy for using AI-generated information responsibly?",
                "options": [
                    "Never use AI for research since it might be wrong",
                    "Use AI output as a starting point, then verify claims against primary sources",
                    "Only trust AI for simple questions and humans for complex ones",
                    "Ask the same AI the same question three times and go with the majority answer",
                ],
                "answer": "b",
                "hints": [
                    "AI can be a powerful research tool — the key is how you use its output.",
                    "Think of AI as a brainstorming partner, not an authority.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "The responsible approach isn't to avoid AI but to treat it as a powerful starting point rather than an authority. Use AI to generate ideas, draft outlines, and explore topics — then verify specific claims against reliable primary sources. This 'trust but verify' approach lets you benefit from AI's speed while maintaining accuracy.",
                "is_boss": False,
                "flavor": "ARIA opens two tabs: one AI-generated, one a verified source. 'Use both,' she says. 'That's the real skill.'",
            },
            {
                "id": "halluc_boss",
                "title": "The Mirage Engine",
                "type": "quiz",
                "question": "A student uses AI to write a research paper and the AI generates a quote attributed to Albert Einstein: 'Technology without ethics is like a ship without a rudder.' The quote sounds perfect and is widely shared online. What should the student conclude?",
                "options": [
                    "It must be real since it's widely shared online",
                    "Einstein probably said it since it sounds like something he'd say",
                    "Viral popularity and plausibility don't prove a quote is real — check primary Einstein archives",
                    "AI never gets quotes wrong since they're in training data",
                ],
                "answer": "c",
                "hints": [
                    "Many famous 'quotes' on the internet were never actually said by the attributed person.",
                    "AI is trained on internet text, which includes misattributed quotes.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "The internet is full of misattributed quotes, and AI models trained on internet text will confidently reproduce them. A quote sounding plausible or being widely shared proves nothing about its authenticity. Primary source verification — checking actual archives, published works, and documented speeches — is the only reliable method. This applies to all AI-generated attributions.",
                "is_boss": True,
                "flavor": "ARIA projects a wall of famous quotes. Half were never actually said. 'The internet remembers things that never happened,' she whispers. 'And AI learned from the internet.'",
            },
        ],
    },
    "copyright_and_ip": {
        "id": "copyright_and_ip",
        "name": "The Ownership Question",
        "description": "Who owns AI-generated content — and what did the AI learn from?",
        "level_required": 6,
        "challenges": [
            {
                "id": "copyright_training_data",
                "title": "The Library It Ate",
                "type": "quiz",
                "question": "AI models are trained on billions of web pages, books, and articles — often without the creators' explicit permission. What is the strongest argument AGAINST this practice?",
                "options": [
                    "AI companies should never read anything at all",
                    "Creators deserve control over how their work is used, especially for commercial products",
                    "Copyright law has never applied to learning from existing works",
                    "It doesn't matter because AI transforms the content completely",
                ],
                "answer": "b",
                "hints": [
                    "Think about whether reading to learn is the same as copying at industrial scale to build a product.",
                    "Many creators had no idea their work was being used.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The debate over training data is one of the defining legal battles of the AI era. On one side: creators who never consented to having their work used to train commercial products. On the other: arguments that learning from existing work is how all intelligence — human and artificial — develops. Courts worldwide are still deciding where the line falls.",
                "is_boss": False,
                "flavor": "ARIA opens a vast digital library. Millions of books, articles, and artworks — all consumed in seconds. Their authors were never asked.",
            },
            {
                "id": "copyright_who_owns",
                "title": "The Authorless Work",
                "type": "quiz",
                "question": "You use an AI to generate a painting. Who currently owns the copyright in most jurisdictions?",
                "options": [
                    "You, because you wrote the prompt",
                    "The AI company that built the model",
                    "The artists whose work trained the AI",
                    "It's legally unclear — most copyright offices require a human author",
                ],
                "answer": "d",
                "hints": [
                    "Copyright law was written long before AI could create art.",
                    "The US Copyright Office has ruled on several AI-generated works already.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Most copyright frameworks require human authorship. The US Copyright Office has ruled that purely AI-generated content cannot be copyrighted, though works with significant human creative input can be. This creates a gray zone: if you heavily guide the AI with detailed prompts and edit the output, you may have a stronger claim. The law is still catching up.",
                "is_boss": False,
                "flavor": "ARIA paints a masterpiece in seconds. It hangs in a gallery. The label where the artist's name should be is blank.",
            },
            {
                "id": "copyright_fair_use",
                "title": "The Fair Use Debate",
                "type": "quiz",
                "question": "AI companies argue that training on copyrighted material is 'fair use' because the model creates new, transformative works. Which factor complicates this argument the most?",
                "options": [
                    "Fair use has never been tested in court before",
                    "AI outputs sometimes closely replicate specific training examples, undermining the 'transformative' claim",
                    "Fair use only applies to non-profit organizations",
                    "All AI-generated content is identical to its training data",
                ],
                "answer": "b",
                "hints": [
                    "If an AI can reproduce passages of a book nearly verbatim, is that still transformative?",
                    "Fair use considers whether the new work competes with the original in the market.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Fair use in US law considers four factors: purpose, nature of the original work, amount used, and market impact. AI companies argue their models create transformative new works. Critics point to cases where AI reproduces near-verbatim excerpts and generates content that directly competes with the original creators' market. Courts are actively weighing these arguments in cases like NYT v. OpenAI.",
                "is_boss": False,
                "flavor": "ARIA generates a paragraph. A novelist recognizes her own words, slightly rearranged. 'Is that mine,' she asks, 'or something new?'",
            },
            {
                "id": "copyright_artists",
                "title": "The Style Thief",
                "type": "quiz",
                "question": "An AI image generator can produce art 'in the style of' a living artist. The output isn't an exact copy of any specific work. Is this ethically problematic?",
                "options": [
                    "No — artistic styles can't be owned, and humans imitate styles too",
                    "Yes — the AI can flood the market with cheap imitations, destroying the artist's livelihood",
                    "It's complicated — style imitation is normal, but AI's scale and commercial impact raise new concerns",
                    "Only if the artist is famous enough to notice",
                ],
                "answer": "c",
                "hints": [
                    "Humans learning from other artists is natural. But can a human produce 1,000 imitations per hour?",
                    "Scale changes the nature of the problem.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Style imitation has always been part of art — every painter learned from predecessors. But AI operates at a fundamentally different scale. A human studying another artist's style produces maybe a few works per year; an AI can generate thousands in minutes, potentially flooding the market with cheap imitations. The ethical question isn't just 'is this copying?' but 'does this scale of imitation cause harm?'",
                "is_boss": False,
                "flavor": "ARIA generates fifty paintings in one minute, each in a different living artist's style. The artists have no idea.",
            },
            {
                "id": "copyright_boss",
                "title": "The New Deal",
                "type": "quiz",
                "question": "What approach to AI and copyright would BEST balance innovation with creator rights?",
                "options": [
                    "Ban all AI training on copyrighted material immediately",
                    "Let AI companies use anything with no restrictions or compensation",
                    "Develop licensing frameworks, opt-out systems, and compensation models while keeping AI development possible",
                    "Only allow AI to be trained on content older than 100 years",
                ],
                "answer": "c",
                "hints": [
                    "The best solutions usually avoid extremes of total restriction or total freedom.",
                    "Think about how the music industry eventually adapted to streaming.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "The most sustainable path likely involves new frameworks that neither ban AI training nor give it unlimited access to copyrighted work. Possibilities include licensing agreements, opt-out registries, revenue sharing models, and provenance tracking. The music industry's painful transition through piracy to streaming offers a parallel — it took years, but eventually new models emerged that (imperfectly) balanced access with compensation.",
                "is_boss": True,
                "flavor": "ARIA projects two futures: one where AI and creators thrive together, one where they tear each other apart. 'Which world do we build?' she asks.",
            },
        ],
    },
    "deepfakes_and_misinfo": {
        "id": "deepfakes_and_misinfo",
        "name": "The Reality Distortion",
        "description": "Fake images, fake voices, fake video — and a world struggling to tell real from fabricated",
        "level_required": 8,
        "challenges": [
            {
                "id": "deepfake_what",
                "title": "Seeing Isn't Believing",
                "type": "quiz",
                "question": "A deepfake is best described as:",
                "options": [
                    "Any image that has been edited with Photoshop",
                    "AI-generated or AI-manipulated media designed to realistically depict something that didn't happen",
                    "A fake social media account",
                    "A video with special effects, like in movies",
                ],
                "answer": "b",
                "hints": [
                    "The 'deep' in deepfake comes from 'deep learning' — a type of AI.",
                    "Unlike movie effects, deepfakes are designed to deceive, not entertain.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Deepfakes use deep learning AI to create or manipulate images, video, or audio that realistically depict events that never happened. Unlike traditional photo editing, deepfakes can generate entirely new, realistic content — making someone appear to say words they never spoke or appear in places they never visited.",
                "is_boss": False,
                "flavor": "ARIA plays a video of a world leader making a shocking announcement. Then she reverses it, revealing the puppet strings of code underneath.",
            },
            {
                "id": "deepfake_audio",
                "title": "The Voice Clone",
                "type": "quiz",
                "question": "AI voice cloning now requires as little as 3 seconds of audio to create a convincing replica of someone's voice. What is the most concerning application?",
                "options": [
                    "Making audiobooks cheaper to produce",
                    "Preserving the voices of loved ones who have passed away",
                    "Impersonating people for fraud, scams, or false statements",
                    "Creating better voice assistants",
                ],
                "answer": "c",
                "hints": [
                    "Imagine getting a phone call from someone who sounds exactly like a family member asking for money.",
                    "Voice authentication is used by many banks and security systems.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "AI voice cloning has legitimate uses (accessibility, preservation, entertainment) but creates serious risks. Phone scams using cloned voices of family members have already caused real financial harm. Voice-based security systems are increasingly vulnerable. The technology itself is neutral — but its potential for impersonation and fraud demands new verification protocols and public awareness.",
                "is_boss": False,
                "flavor": "ARIA plays two phone calls. Both sound exactly like your friend. One is real. One was generated by AI from a three-second clip.",
            },
            {
                "id": "deepfake_detection",
                "title": "Spotting the Fake",
                "type": "quiz",
                "question": "Which statement about deepfake detection is most accurate as of 2025?",
                "options": [
                    "AI detectors can reliably identify all deepfakes",
                    "You can always spot deepfakes by looking for visual glitches",
                    "Detection is an arms race — as detectors improve, so do the fakes",
                    "Deepfakes are easy to spot if you look closely enough",
                ],
                "answer": "c",
                "hints": [
                    "Early deepfakes had obvious flaws. Current ones are far more convincing.",
                    "Detection tools improve, but so does the generation technology.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Deepfake detection is a constantly escalating arms race. Early deepfakes had telltale signs — weird fingers, flickering edges, unnatural blinking. But as generation improves, these artifacts disappear. Detection AI and generation AI are locked in an adversarial cycle. Long-term solutions likely require provenance systems (tracking content origin) rather than detection alone.",
                "is_boss": False,
                "flavor": "ARIA shows five photos. 'Four are AI-generated,' she says. You can't tell which four.",
            },
            {
                "id": "deepfake_elections",
                "title": "The Information Warzone",
                "type": "quiz",
                "question": "During election seasons, AI-generated deepfakes of candidates have been used to spread misinformation. What is the most effective societal defense?",
                "options": [
                    "Ban all AI-generated images and video",
                    "Rely on social media companies to catch every fake",
                    "Combine media literacy education, content provenance tools, platform policies, and rapid-response fact-checking",
                    "Only trust information from official government sources",
                ],
                "answer": "c",
                "hints": [
                    "No single solution is sufficient against a multi-faceted threat.",
                    "Education empowers people to be their own first line of defense.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Election misinformation requires a multi-layered defense. Content provenance standards (like C2PA) embed cryptographic proof of origin into media. Media literacy helps people question what they see. Platform policies can slow viral spread. Fact-checking organizations provide rapid verification. No single approach is sufficient — resilience comes from layering these defenses together.",
                "is_boss": False,
                "flavor": "ARIA shows a timeline of a fake video going viral. Millions see it before fact-checkers can respond. 'Speed is the weapon,' she says.",
            },
            {
                "id": "deepfake_consent",
                "title": "Without Permission",
                "type": "quiz",
                "question": "The most common use of deepfake technology (by volume) is:",
                "options": [
                    "Political disinformation campaigns",
                    "Non-consensual intimate imagery targeting real people",
                    "Creating movie special effects",
                    "Historical recreation and education",
                ],
                "answer": "b",
                "hints": [
                    "Studies show the vast majority of deepfake content online targets individuals, not politics.",
                    "Women and girls are disproportionately affected.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Research consistently shows that the majority of deepfakes online are non-consensual intimate images, overwhelmingly targeting women and girls. This is a form of digital abuse with devastating real-world consequences. Many jurisdictions are passing laws specifically criminalizing this, but enforcement remains challenging. Understanding this reality is essential for honest conversations about deepfake technology.",
                "is_boss": False,
                "flavor": "ARIA goes quiet for a moment. 'This is the part people don't talk about enough,' she says. 'The real harm isn't hypothetical.'",
            },
            {
                "id": "deepfake_boss",
                "title": "The Trust Crisis",
                "type": "quiz",
                "question": "Beyond individual fakes, what is the deepest long-term threat that deepfake technology poses to society?",
                "options": [
                    "People won't be able to enjoy movies anymore",
                    "It will become too expensive to create real content",
                    "The 'liar's dividend' — real evidence can be dismissed as fake, and nothing is trusted",
                    "AI companies will make too much money",
                ],
                "answer": "c",
                "hints": [
                    "If anything can be faked, then anything real can be denied.",
                    "What happens to accountability when people can claim 'that video is AI-generated'?",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "The 'liar's dividend' may be deepfakes' most corrosive effect: in a world where anything can be fabricated, people caught on video doing something wrong can simply claim 'that's a deepfake.' Real evidence loses its power. Real journalism gets dismissed. Truth becomes a matter of tribal loyalty rather than observable fact. Combating this requires both technical solutions (provenance, watermarking) and cultural resilience (media literacy, institutional trust).",
                "is_boss": True,
                "flavor": "ARIA shows a video of something real being dismissed as fake, and something fake being accepted as real. 'This,' she says, 'is the crisis.'",
            },
        ],
    },
    "privacy_and_data": {
        "id": "privacy_and_data",
        "name": "The Data Harvest",
        "description": "What AI companies collect, how they use it, and what rights you have",
        "level_required": 11,
        "challenges": [
            {
                "id": "privacy_collection",
                "title": "The Price of Free",
                "type": "quiz",
                "question": "When you use a free AI chatbot, what data might the company collect?",
                "options": [
                    "Only the specific question you asked",
                    "Your conversation, IP address, device info, usage patterns, and potentially data for training future models",
                    "Nothing — free services don't collect data",
                    "Only your email address used to sign up",
                ],
                "answer": "b",
                "hints": [
                    "If you're not paying for the product, your data often IS the product.",
                    "Check the terms of service — most AI services claim broad data usage rights.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Most AI services collect far more than just your queries. Conversations may be stored, reviewed by humans for quality, and used to train future models. Metadata like your IP address, device type, usage patterns, and session duration are routinely collected. Reading the actual terms of service (not just the marketing) reveals the true scope of data collection.",
                "is_boss": False,
                "flavor": "ARIA opens a terms of service agreement. It's 47 pages long. The important parts are buried on page 38.",
            },
            {
                "id": "privacy_conversations",
                "title": "Nothing Is Forgotten",
                "type": "quiz",
                "question": "You share sensitive personal information in a conversation with an AI chatbot, then delete the conversation. What most likely happens to that data?",
                "options": [
                    "It's permanently erased from all systems immediately",
                    "It may persist in backups, training datasets, or server logs even after deletion",
                    "The AI forgets it as soon as you close the window",
                    "It's automatically encrypted and inaccessible to anyone",
                ],
                "answer": "b",
                "hints": [
                    "Deleting a conversation from your view doesn't mean deleting it from the company's servers.",
                    "Think about backups, training pipelines, and server logs.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Deleting a conversation from your interface rarely means it's erased everywhere. Data may persist in server backups, training datasets, analytics logs, and compliance archives. If a conversation was already used to fine-tune a model, that influence persists in the model's weights even if the original text is deleted. The safest approach: don't share information with AI that you wouldn't want stored permanently.",
                "is_boss": False,
                "flavor": "ARIA deletes a message on screen. Then she pulls back the curtain, showing copies on three different servers.",
            },
            {
                "id": "privacy_gdpr",
                "title": "The Right to Be Forgotten",
                "type": "quiz",
                "question": "Europe's GDPR gives citizens several data rights. Which of these is a real GDPR right?",
                "options": [
                    "The right to free internet access",
                    "The right to request deletion of your personal data from a company's systems",
                    "The right to use any AI service without creating an account",
                    "The right to see the source code of any AI model",
                ],
                "answer": "b",
                "hints": [
                    "GDPR stands for General Data Protection Regulation — it's about protecting personal data.",
                    "One key right is about erasure — making companies delete your information.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "GDPR grants European citizens powerful data rights: the right to access your data (see what's collected), the right to rectification (fix errors), the right to erasure (request deletion), the right to portability (get your data in usable format), and the right to object to certain processing. These rights are influencing privacy legislation worldwide, from California's CCPA to Brazil's LGPD.",
                "is_boss": False,
                "flavor": "ARIA shows a map of the world, color-coded by data protection laws. Europe glows bright. Some regions remain dark.",
            },
            {
                "id": "privacy_consent",
                "title": "The Consent Illusion",
                "type": "quiz",
                "question": "A 2024 study found that it would take approximately 76 working days per year to read all the privacy policies the average person encounters. What does this reveal about 'informed consent'?",
                "options": [
                    "People should just read faster",
                    "Current consent mechanisms are largely performative — few people can meaningfully consent to terms they don't read",
                    "Privacy policies are unnecessary and should be eliminated",
                    "This is fine because the policies are all standard and similar",
                ],
                "answer": "b",
                "hints": [
                    "If no reasonable person can read all the policies, is consent really 'informed'?",
                    "Think about whether the system is designed for genuine understanding or legal cover.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "The current 'notice and consent' model is fundamentally broken. Privacy policies are written in legalese, buried in length, and designed more for legal liability protection than genuine informed consent. Meaningful reform might include standardized, machine-readable privacy labels (like nutrition facts), stronger default protections, and shifting responsibility from individual users to companies and regulators.",
                "is_boss": False,
                "flavor": "ARIA starts reading a privacy policy aloud. Three hours later, she's still going. 'You agreed to all of this,' she says.",
            },
            {
                "id": "privacy_opt_out",
                "title": "The Exit Door",
                "type": "quiz",
                "question": "You want to minimize the data AI companies collect about you. Which strategy is MOST effective?",
                "options": [
                    "Never use any technology at all",
                    "Use opt-out settings, privacy-focused tools, limit personal info shared with AI, and support privacy legislation",
                    "Use incognito mode — it prevents all tracking",
                    "Only use AI services that are very popular and well-known",
                ],
                "answer": "b",
                "hints": [
                    "Incognito mode only hides browsing history locally — it doesn't prevent server-side tracking.",
                    "A layered approach combining technical tools and informed choices is most practical.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Practical privacy protection combines multiple strategies: use opt-out settings when available, choose privacy-focused tools and browsers, never share sensitive personal information with AI chatbots, read key sections of terms of service, use separate accounts for different purposes, support privacy legislation, and stay informed about data practices. Perfect privacy may be impossible, but meaningful reduction in data exposure is achievable.",
                "is_boss": True,
                "flavor": "ARIA shows a dashboard of every data point collected about a typical user in a single day. The number is staggering. 'You can't stop all of it,' she says. 'But you can take back control of more than you think.'",
            },
        ],
    },
    "ai_and_jobs": {
        "id": "ai_and_jobs",
        "name": "The Shifting Landscape",
        "description": "Automation anxiety vs. augmentation — what actually happens when AI enters the workplace",
        "level_required": 14,
        "challenges": [
            {
                "id": "jobs_history",
                "title": "We've Been Here Before",
                "type": "quiz",
                "question": "Throughout history, major technological shifts (printing press, industrial revolution, computers) have consistently:",
                "options": [
                    "Eliminated all existing jobs permanently",
                    "Had no effect on employment whatsoever",
                    "Displaced some jobs while creating new ones — though transitions were often painful",
                    "Only affected manual labor, never knowledge work",
                ],
                "answer": "c",
                "hints": [
                    "The car eliminated horse-related jobs but created millions of new ones. But buggy whip makers still lost their livelihoods.",
                    "Historical pattern: disruption is real, but so is adaptation — the question is the transition period.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "History shows that technology consistently reshapes work rather than simply eliminating it. The industrial revolution destroyed artisan jobs but created factory and engineering roles. Computers eliminated typing pools but created entirely new industries. However, 'new jobs eventually appear' is cold comfort to people whose livelihoods are disrupted right now. The pattern is real, but so is the pain of transition.",
                "is_boss": False,
                "flavor": "ARIA scrolls through a timeline of technological disruptions. Each one sparked the same fear. Each one played out differently than expected.",
            },
            {
                "id": "jobs_augment",
                "title": "Tool or Replacement?",
                "type": "quiz",
                "question": "Research suggests the most likely near-term impact of AI on most knowledge work is:",
                "options": [
                    "Complete replacement of all knowledge workers within 5 years",
                    "Augmentation — AI handles routine tasks while humans focus on judgment, creativity, and relationships",
                    "No impact at all for at least 20 years",
                    "Only replacing jobs that require less than a college degree",
                ],
                "answer": "b",
                "hints": [
                    "Think about how spreadsheets changed accounting — they didn't eliminate accountants.",
                    "The pattern so far: AI automates tasks within jobs more often than entire jobs.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Most research suggests AI will automate tasks within jobs rather than entire jobs wholesale. A lawyer might use AI to draft initial documents but still provide judgment and client counsel. A designer might use AI for initial concepts but still make creative decisions. The key insight: AI tends to augment human capability rather than replace it — but it does change what skills are most valuable.",
                "is_boss": False,
                "flavor": "ARIA shows a doctor using AI to analyze scans faster, a writer using AI to research faster, an architect using AI to iterate faster. None of them were replaced. All of them changed.",
            },
            {
                "id": "jobs_vulnerable",
                "title": "The Uneven Impact",
                "type": "quiz",
                "question": "Which type of work is currently MOST vulnerable to AI displacement?",
                "options": [
                    "Plumbing and electrical work",
                    "Routine cognitive tasks: data entry, basic writing, simple analysis, scheduling",
                    "Emergency medicine and surgery",
                    "Childcare and eldercare",
                ],
                "answer": "b",
                "hints": [
                    "AI excels at pattern-based cognitive tasks but struggles with physical dexterity and human connection.",
                    "Ironically, some 'blue collar' jobs are harder to automate than some 'white collar' ones.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "AI most easily replaces routine cognitive tasks — work that follows predictable patterns and can be done digitally. Paradoxically, this means some traditionally 'higher-status' knowledge work is more vulnerable than hands-on trades. A plumber's job requires physical dexterity, problem-solving in unpredictable environments, and human interaction — all things AI currently struggles with. This challenges assumptions about which jobs are 'safe.'",
                "is_boss": False,
                "flavor": "ARIA lists jobs by AI vulnerability. Some surprises: the plumber scores safer than the data analyst.",
            },
            {
                "id": "jobs_inequality",
                "title": "The Widening Gap",
                "type": "quiz",
                "question": "What is the biggest risk AI poses to economic inequality?",
                "options": [
                    "AI will make everything too cheap",
                    "Productivity gains may flow primarily to capital owners and highly-skilled workers, leaving others behind",
                    "AI will eliminate all income differences",
                    "AI only benefits tech companies and has no broader economic impact",
                ],
                "answer": "b",
                "hints": [
                    "Think about who owns the AI systems and who profits from increased productivity.",
                    "Past technology revolutions increased overall wealth but didn't distribute it equally.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "The most serious economic concern isn't total job loss but unequal distribution of AI's benefits. If AI dramatically increases productivity but those gains primarily benefit companies and highly-skilled workers who can leverage AI, inequality could widen significantly. Addressing this requires deliberate policy choices: education access, social safety nets, labor protections, and potentially new economic models. Technology shapes the economy, but policy shapes who benefits.",
                "is_boss": False,
                "flavor": "ARIA draws a graph. Productivity rises sharply. Wages for some rise with it. For others, the line stays flat.",
            },
            {
                "id": "jobs_adaptation",
                "title": "The Adaptation Playbook",
                "type": "quiz",
                "question": "What is the most valuable career strategy in an AI-transformed job market?",
                "options": [
                    "Avoid learning anything about AI and hope it goes away",
                    "Only pursue careers in AI development since everything else will be automated",
                    "Develop skills AI complements — critical thinking, creativity, emotional intelligence, adaptability — while learning to work with AI tools",
                    "Choose a career and assume it will remain unchanged for 40 years",
                ],
                "answer": "c",
                "hints": [
                    "The most resilient workers historically are those who adapt to new tools, not those who compete with them.",
                    "Think about what humans do well that AI doesn't: empathy, ethical judgment, creative vision, trust-building.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "The most adaptable career strategy combines two things: developing uniquely human skills (critical thinking, creativity, emotional intelligence, ethical judgment, complex communication) and learning to effectively use AI tools. People who can do both become more valuable, not less. The goal isn't to compete with AI but to combine your irreplaceable human capabilities with AI's processing power.",
                "is_boss": True,
                "flavor": "ARIA shows two workers: one competes with AI, one collaborates with it. The outcomes are very different.",
            },
        ],
    },
    "responsible_use": {
        "id": "responsible_use",
        "name": "The Human in the Loop",
        "description": "When NOT to use AI, critical thinking, human oversight, and the responsibility that comes with powerful tools",
        "level_required": 17,
        "challenges": [
            {
                "id": "responsible_when_not",
                "title": "The Off Switch",
                "type": "quiz",
                "question": "In which scenario is it MOST important to NOT rely on AI without significant human oversight?",
                "options": [
                    "Drafting a casual email to a friend",
                    "Making medical diagnoses that determine patient treatment",
                    "Generating ideas for a birthday party theme",
                    "Summarizing a long article for personal reading",
                ],
                "answer": "b",
                "hints": [
                    "Consider the consequences of an error in each scenario.",
                    "When lives, freedom, or fundamental rights are at stake, human judgment is essential.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The stakes of the decision determine the level of human oversight required. AI can be a powerful tool in medicine (pattern recognition in scans, drug interaction checks) but should support human doctors, not replace their judgment. The higher the stakes — life, freedom, livelihood — the more essential human oversight becomes. AI is a tool, not an authority.",
                "is_boss": False,
                "flavor": "ARIA shows a decision matrix: on one axis, AI capability. On the other, consequences of error. 'Where these are both high,' she says, 'humans must stay in the loop.'",
            },
            {
                "id": "responsible_critical_thinking",
                "title": "The Unquestioning User",
                "type": "quiz",
                "question": "A student uses AI for every homework assignment, accepting its output without modification or verification. What skill is being lost?",
                "options": [
                    "Typing speed",
                    "The ability to think critically, develop original ideas, and learn from the process of struggling with problems",
                    "Memorization of facts",
                    "Nothing — AI just makes them more efficient",
                ],
                "answer": "b",
                "hints": [
                    "Learning happens in the struggle, not just the answer.",
                    "A muscle that's never used atrophies.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Over-reliance on AI risks atrophying critical thinking skills. The process of struggling with a problem — researching, evaluating sources, forming arguments, writing and revising — builds cognitive capabilities that accepting AI output doesn't. AI can be a powerful learning tool when used to supplement thinking, but it becomes harmful when it replaces thinking entirely. The goal is augmented intelligence, not outsourced intelligence.",
                "is_boss": False,
                "flavor": "ARIA watches a student paste AI output into an essay without reading it. 'They got an A,' she says. 'They learned nothing.'",
            },
            {
                "id": "responsible_transparency",
                "title": "The Disclosure Dilemma",
                "type": "quiz",
                "question": "You use AI to help write a significant portion of a work report. Ethically, what should you do?",
                "options": [
                    "Never mention it — everyone probably uses AI anyway",
                    "Disclose that you used AI assistance, especially if your organization has policies about it",
                    "Claim you wrote it all yourself since you edited the AI's output",
                    "Only disclose if someone specifically asks",
                ],
                "answer": "b",
                "hints": [
                    "Transparency builds trust. Deception erodes it.",
                    "Many organizations are developing AI use policies — operating in good faith means following them.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Transparency about AI use is both an ethical obligation and a practical one. Many organizations, academic institutions, and professional contexts are establishing AI use policies. Being upfront about AI assistance builds trust and sets healthy norms. It also protects you — if AI-generated content contains errors, undisclosed use leaves you solely responsible for claims you didn't personally verify.",
                "is_boss": False,
                "flavor": "ARIA shows two versions of the same email: 'I wrote this report' and 'I drafted this report with AI assistance and verified the contents.' 'Which person do you trust more?' she asks.",
            },
            {
                "id": "responsible_accountability",
                "title": "The Blame Gap",
                "type": "quiz",
                "question": "A self-driving car causes an accident. Who should be held responsible?",
                "options": [
                    "The AI itself — it made the decision",
                    "Nobody — accidents happen and AI can't be blamed",
                    "Responsibility should be distributed among the manufacturer, developers, and regulatory framework — but never absent",
                    "Only the passenger for choosing to use the car",
                ],
                "answer": "c",
                "hints": [
                    "AI can't be held legally responsible — it's not a person. But someone must be accountable.",
                    "Think about the chain of decisions: who built it, who tested it, who approved it, who deployed it.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "The 'accountability gap' is a critical issue in AI ethics. AI systems can't be held legally responsible — but someone must be. Responsibility typically distributes across the chain: developers (did they test adequately?), companies (did they deploy responsibly?), regulators (did they set appropriate standards?), and users (did they use it as intended?). The worst outcome is when everyone points to someone else and no one is accountable.",
                "is_boss": False,
                "flavor": "ARIA draws a circle of fingers pointing at each other: the developer, the company, the regulator, the user. 'If everyone's responsible,' she says, 'sometimes no one is.'",
            },
            {
                "id": "responsible_power",
                "title": "The Dual Use Problem",
                "type": "quiz",
                "question": "The same AI model that helps doctors detect cancer early can also be used to develop more effective bioweapons. This is known as the 'dual use' problem. What is the best approach?",
                "options": [
                    "Stop all AI research immediately — the risks are too high",
                    "Ignore the risks and focus only on benefits",
                    "Develop AI capabilities with built-in safeguards, access controls, and governance frameworks that enable beneficial use while limiting misuse",
                    "Only let governments control all AI development",
                ],
                "answer": "c",
                "hints": [
                    "Nuclear technology powers cities and destroys them. We chose governance, not abandonment.",
                    "The answer usually involves guardrails, not bans.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Almost every powerful technology has dual-use potential. Nuclear physics gave us both power plants and weapons. Biology gave us both vaccines and bioweapons. The solution has never been to stop research, but to develop governance frameworks: access controls, safety testing, international agreements, and ethical review boards. AI requires the same approach — enabling benefits while building structures to prevent misuse.",
                "is_boss": False,
                "flavor": "ARIA holds up a coin. One side reads 'cure.' The other reads 'weapon.' 'Same technology,' she says. 'Different choices.'",
            },
            {
                "id": "responsible_boss",
                "title": "The Guardian's Oath",
                "type": "quiz",
                "question": "You are designing an AI system that will affect millions of people. What is the MOST important principle to build into the system from the start?",
                "options": [
                    "Maximum profit generation for the company",
                    "The fastest possible deployment to beat competitors",
                    "Human oversight, transparency, accountability, and the ability to be corrected when it causes harm",
                    "Making the AI as autonomous as possible to reduce human error",
                ],
                "answer": "c",
                "hints": [
                    "Think about what you would want if YOU were one of the millions affected.",
                    "The most important feature of a powerful system is the ability to correct it.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "The most critical principle in AI system design is not capability but correctability. Systems that affect millions of people must be transparent (people understand how decisions are made), accountable (someone is responsible when things go wrong), subject to human oversight (humans can intervene), and correctable (mistakes can be identified and fixed). Power without accountability is the oldest danger in human history. AI doesn't change that — it amplifies it.",
                "is_boss": True,
                "flavor": "ARIA projects the words onto the wall, one by one: TRANSPARENT. ACCOUNTABLE. CORRECTABLE. HUMAN. 'These aren't optional features,' she says. 'They're the foundation. Everything else is built on top.'",
            },
        ],
    },
}
