"""
zones.py — Food zones and challenges.

All challenges use "type": "quiz" with multiple-choice options.
Guided by Sofia, a warm and encouraging Spanish teacher.
"""

ZONE_ORDER = [
    "fruits_vegetables",
    "drinks",
    "meals",
    "ordering",
    "cooking",
    "food_culture",
]

ZONES = {
    # -- Zone 1: Fruits & Vegetables --
    "fruits_vegetables": {
        "id": "fruits_vegetables",
        "name": "Fruits & Vegetables",
        "description": "Learn the names of common fruits and vegetables",
        "level_required": 1,
        "challenges": [
            {
                "id": "fv_manzana",
                "title": "La Manzana",
                "type": "quiz",
                "question": "What fruit is 'la manzana'?",
                "options": ["Banana", "Orange", "Apple", "Grape"],
                "answer": "c",
                "hints": ["Think of 'manzanilla' tea -- made from chamomile, but the word root relates to this fruit.", "It's the most iconic fruit, associated with teachers."],
                "xp": 25,
                "lesson": "'La manzana' = apple. One of the first food words every Spanish learner should know. 'Manzana' is feminine (la manzana). Fun fact: 'manzana' also means 'city block' in some Latin American countries!",
            },
            {
                "id": "fv_platano",
                "title": "El Platano",
                "type": "quiz",
                "question": "What is 'el platano' in English?",
                "options": ["Plantain/Banana", "Plate", "Peach", "Pear"],
                "answer": "a",
                "hints": ["It's a yellow, curved fruit.", "In some countries, 'banana' is also used."],
                "xp": 25,
                "lesson": "'El platano' = banana (also plantain in some regions). In Spain, 'platano' is banana. In many Latin American countries, 'banana' or 'banano' is also used, while 'platano' may refer specifically to plantains.",
            },
            {
                "id": "fv_tomate",
                "title": "El Tomate",
                "type": "quiz",
                "question": "'El tomate' is easy to guess! What is it?",
                "options": ["Potato", "Tomato", "Lettuce", "Carrot"],
                "answer": "b",
                "hints": ["It sounds almost identical to the English word.", "The English word actually comes from the Spanish!"],
                "xp": 25,
                "lesson": "'El tomate' = tomato. The English word 'tomato' actually comes from the Spanish 'tomate,' which came from the Nahuatl (Aztec) word 'tomatl.' Many food words traveled from the Americas to the world through Spanish!",
            },
            {
                "id": "fv_lechuga",
                "title": "La Lechuga",
                "type": "quiz",
                "question": "What vegetable is 'la lechuga'?",
                "options": ["Onion", "Carrot", "Lettuce", "Pepper"],
                "answer": "c",
                "hints": ["It's green and leafy.", "It's the base of most salads."],
                "xp": 25,
                "lesson": "'La lechuga' = lettuce. Other salad vegetables: el pepino (cucumber), la zanahoria (carrot), el pimiento (bell pepper). 'Una ensalada' = a salad.",
            },
            {
                "id": "fv_cebolla",
                "title": "La Cebolla",
                "type": "quiz",
                "question": "'La cebolla' is a vegetable that makes you cry when you cut it. What is it?",
                "options": ["Garlic", "Onion", "Pepper", "Radish"],
                "answer": "b",
                "hints": ["It has layers and a strong smell.", "It's a base ingredient in most Spanish cooking."],
                "xp": 25,
                "lesson": "'La cebolla' = onion. Essential cooking vocabulary: el ajo (garlic), la cebolla (onion), el pimiento (pepper), la papa/patata (potato -- 'papa' in Latin America, 'patata' in Spain).",
            },
            {
                "id": "fv_naranja",
                "title": "La Naranja",
                "type": "quiz",
                "question": "'La naranja' is both a fruit AND a color. What is it?",
                "options": ["Lemon", "Lime", "Orange", "Grapefruit"],
                "answer": "c",
                "hints": ["The color name in English actually comes from this Spanish/Arabic word.", "It's a citrus fruit and a warm color."],
                "xp": 30,
                "lesson": "'La naranja' = orange (both the fruit and the color). Other citrus: el limon (lemon/lime), la lima (lime, in some regions), la toronja (grapefruit). The English word 'orange' ultimately derives from the same root as 'naranja.'",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 2: Drinks --
    "drinks": {
        "id": "drinks",
        "name": "Drinks",
        "description": "Learn the names of common beverages",
        "level_required": 1,
        "challenges": [
            {
                "id": "dr_agua",
                "title": "El Agua",
                "type": "quiz",
                "question": "What is 'el agua'? (Note the masculine article with a feminine noun!)",
                "options": ["Juice", "Water", "Milk", "Tea"],
                "answer": "b",
                "hints": ["It's the most essential drink.", "'Agua' is actually feminine but uses 'el' because it starts with a stressed 'a'."],
                "xp": 25,
                "lesson": "'El agua' = water. Tricky grammar: 'agua' is feminine but uses 'el' (not 'la') because it starts with a stressed 'a' sound. But adjectives are still feminine: 'el agua fria' (the cold water). This rule prevents awkward sounds.",
            },
            {
                "id": "dr_cafe",
                "title": "El Cafe",
                "type": "quiz",
                "question": "'Un cafe con leche' is one of the most popular orders. What is it?",
                "options": ["Coffee with sugar", "Coffee with milk", "Coffee with cream", "Tea with milk"],
                "answer": "b",
                "hints": ["'Con' = with, 'leche' = milk.", "It's the classic Spanish breakfast drink."],
                "xp": 25,
                "lesson": "'El cafe' = coffee. 'Cafe con leche' = coffee with milk (the classic). 'Cafe solo' = black coffee. 'Cafe cortado' = espresso with a splash of milk. Coffee culture is huge in Spanish-speaking countries!",
            },
            {
                "id": "dr_leche",
                "title": "La Leche",
                "type": "quiz",
                "question": "What does 'la leche' mean?",
                "options": ["Coffee", "Tea", "Milk", "Juice"],
                "answer": "c",
                "hints": ["It comes from Latin 'lac' (milk).", "It's an essential ingredient in many Spanish drinks."],
                "xp": 25,
                "lesson": "'La leche' = milk. Found in many Spanish expressions: 'cafe con leche' (coffee with milk), 'arroz con leche' (rice pudding), 'dulce de leche' (caramelized milk). It's a staple of Spanish-speaking kitchens.",
            },
            {
                "id": "dr_jugo",
                "title": "El Jugo",
                "type": "quiz",
                "question": "'Jugo de naranja' means:",
                "options": ["Orange soda", "Orange juice", "Orange milk", "Orange tea"],
                "answer": "b",
                "hints": ["'Jugo' = juice, 'naranja' = orange.", "In Spain, they say 'zumo' instead of 'jugo'."],
                "xp": 25,
                "lesson": "'El jugo' = juice (Latin America) / 'el zumo' = juice (Spain). 'Jugo de naranja' = orange juice, 'jugo de manzana' = apple juice. This is a great example of regional vocabulary differences!",
            },
            {
                "id": "dr_cerveza",
                "title": "La Cerveza",
                "type": "quiz",
                "question": "What is 'la cerveza'?",
                "options": ["Wine", "Beer", "Whiskey", "Soda"],
                "answer": "b",
                "hints": ["It's the most popular alcoholic drink worldwide.", "Many Spanish-speaking countries have famous local brands."],
                "xp": 25,
                "lesson": "'La cerveza' = beer. 'El vino' = wine (tinto = red, blanco = white). 'Una copa de vino' = a glass of wine. 'Una cerveza, por favor' is one of the most useful phrases in any bar!",
            },
            {
                "id": "dr_ordering",
                "title": "Ordering a Drink",
                "type": "quiz",
                "question": "How would you order 'a glass of red wine, please'?",
                "options": ["Un vaso de vino rojo, por favor", "Una copa de vino tinto, por favor", "Un vino rojo, por favor", "La cerveza tinta, por favor"],
                "answer": "b",
                "hints": ["Red wine is 'vino tinto' (not rojo) in Spanish.", "'Copa' is used for wine glasses."],
                "xp": 30,
                "lesson": "'Una copa de vino tinto, por favor' = A glass of red wine, please. Note: red wine is 'vino tinto' (not 'rojo'). 'Copa' for wine glass, 'vaso' for regular glass, 'taza' for cup/mug. These distinctions matter!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 3: Meals --
    "meals": {
        "id": "meals",
        "name": "Meals of the Day",
        "description": "Understand the Spanish meal schedule",
        "level_required": 2,
        "challenges": [
            {
                "id": "meal_desayuno",
                "title": "El Desayuno",
                "type": "quiz",
                "question": "What meal is 'el desayuno'?",
                "options": ["Lunch", "Dinner", "Breakfast", "Snack"],
                "answer": "c",
                "hints": ["'Des-ayuno' literally means 'break-fast' (end the fast).", "It's the first meal of the day."],
                "xp": 25,
                "lesson": "'El desayuno' = breakfast. 'Desayunar' = to have breakfast. In many Spanish-speaking countries, breakfast is light -- coffee with toast, a pastry, or fruit. The word literally means 'un-fasting' (des + ayuno).",
            },
            {
                "id": "meal_almuerzo",
                "title": "El Almuerzo",
                "type": "quiz",
                "question": "'El almuerzo' is typically the biggest meal in many Spanish-speaking countries. What meal is it?",
                "options": ["Breakfast", "Lunch", "Dinner", "Snack"],
                "answer": "b",
                "hints": ["It happens in the middle of the day.", "In Spain, it can be as late as 2-3 PM."],
                "xp": 25,
                "lesson": "'El almuerzo' = lunch. In Spain and many Latin American countries, lunch is the main meal, often eaten between 1-3 PM. 'La comida' is also used for lunch in Mexico and Spain. It's typically the biggest meal of the day!",
            },
            {
                "id": "meal_cena",
                "title": "La Cena",
                "type": "quiz",
                "question": "What meal is 'la cena'?",
                "options": ["Breakfast", "Lunch", "Afternoon snack", "Dinner/Supper"],
                "answer": "d",
                "hints": ["It's the last meal of the day.", "In Spain, it can be as late as 9-10 PM."],
                "xp": 25,
                "lesson": "'La cena' = dinner/supper. 'Cenar' = to have dinner. In Spain, dinner is often light and late (9-10 PM). In Latin America, timing varies -- generally earlier than Spain but later than the US.",
            },
            {
                "id": "meal_merienda",
                "title": "La Merienda",
                "type": "quiz",
                "question": "'La merienda' is a meal that doesn't really exist in American culture. What is it?",
                "options": ["A second breakfast", "A midnight snack", "An afternoon snack between lunch and dinner", "A pre-lunch appetizer"],
                "answer": "c",
                "hints": ["It happens between almuerzo and cena.", "Think of British 'afternoon tea' -- similar concept."],
                "xp": 25,
                "lesson": "'La merienda' = afternoon snack (around 5-6 PM). Since lunch is late and dinner is even later, 'la merienda' fills the gap. Common meriendas: coffee and pastry, a sandwich, fruit, churros with chocolate.",
            },
            {
                "id": "meal_buen_provecho",
                "title": "Bon Appetit!",
                "type": "quiz",
                "question": "What do Spanish speakers say before eating, similar to 'Bon appetit'?",
                "options": ["Buena suerte", "Buen provecho", "Buenas noches", "Buena comida"],
                "answer": "b",
                "hints": ["'Provecho' relates to benefit/nourishment.", "You say it to people who are about to eat."],
                "xp": 25,
                "lesson": "'Buen provecho!' (Enjoy your meal!) is said before eating or to others who are eating. It's very common and considered polite. In restaurants, the waiter or other diners may say it to you.",
            },
            {
                "id": "meal_schedule",
                "title": "The Spanish Meal Schedule",
                "type": "quiz",
                "question": "In Spain, what is the typical order and timing of meals?",
                "options": ["Breakfast 7am, Lunch 12pm, Dinner 6pm", "Breakfast 8am, Lunch 2pm, Merienda 6pm, Dinner 9-10pm", "Breakfast 6am, Lunch 11am, Dinner 5pm", "Breakfast 10am, Dinner 4pm"],
                "answer": "b",
                "hints": ["Spanish mealtimes are later than in the US.", "Four meals, not three!"],
                "xp": 30,
                "lesson": "The Spanish meal schedule: Desayuno ~8am (light), Almuerzo ~2pm (biggest meal), Merienda ~6pm (snack), Cena ~9-10pm (lighter). This schedule is why many shops close for 'siesta' in the afternoon. Latin American schedules vary but share the late-lunch pattern.",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 4: Ordering Food --
    "ordering": {
        "id": "ordering",
        "name": "Ordering at a Restaurant",
        "description": "Learn to order food and navigate restaurant situations",
        "level_required": 2,
        "challenges": [
            {
                "id": "ord_quisiera",
                "title": "I Would Like...",
                "type": "quiz",
                "question": "The polite way to say 'I would like...' when ordering is:",
                "options": ["Quiero...", "Quisiera...", "Dame...", "Necesito..."],
                "answer": "b",
                "hints": ["It's the conditional form of 'querer' (to want).", "More polite than 'quiero' (I want)."],
                "xp": 25,
                "lesson": "'Quisiera...' (I would like...) is the polite ordering phrase. 'Quisiera un cafe' = I would like a coffee. You can also use 'Me gustaria...' (I would like...). 'Quiero' (I want) works but is less polite.",
            },
            {
                "id": "ord_la_cuenta",
                "title": "The Check, Please",
                "type": "quiz",
                "question": "How do you ask for the bill/check at a restaurant?",
                "options": ["El dinero, por favor", "La cuenta, por favor", "El precio, por favor", "El pago, por favor"],
                "answer": "b",
                "hints": ["'Cuenta' comes from 'contar' (to count).", "This is one of the most essential restaurant phrases."],
                "xp": 25,
                "lesson": "'La cuenta, por favor' (The check, please) is how you ask for the bill. In many Spanish-speaking countries, you have to actively ask -- the waiter won't bring it automatically, as it's considered rude to rush you.",
            },
            {
                "id": "ord_tiene",
                "title": "Do You Have...?",
                "type": "quiz",
                "question": "To ask a waiter 'Do you have vegetarian options?', you'd start with:",
                "options": ["Tiene opciones vegetarianas?", "Es vegetariano?", "Hay vegetariano?", "Both A and C work"],
                "answer": "d",
                "hints": ["'Tiene' = do you have, 'Hay' = is there/are there.", "Both are natural ways to ask about availability."],
                "xp": 25,
                "lesson": "'Tiene...?' (Do you have...?) and 'Hay...?' (Is there...?) both work for asking about menu items. 'Tiene wifi?' (Do you have wifi?), 'Hay postre?' (Is there dessert?). Essential restaurant vocabulary!",
            },
            {
                "id": "ord_para_mi",
                "title": "For Me...",
                "type": "quiz",
                "question": "When ordering for yourself at a table, you can say 'Para mi...' What does it mean?",
                "options": ["For him...", "For us...", "For me...", "For them..."],
                "answer": "c",
                "hints": ["'Para' = for, 'mi' = me.", "Used when a group is ordering and it's your turn."],
                "xp": 25,
                "lesson": "'Para mi...' (For me...) is perfect when ordering at a table. 'Para mi, la ensalada' (For me, the salad). For others: 'Para el/ella' (for him/her). This is very natural ordering language.",
            },
            {
                "id": "ord_allergies",
                "title": "Food Allergies",
                "type": "quiz",
                "question": "How do you say 'I am allergic to nuts'?",
                "options": ["Tengo alergia a las nueces", "Soy alergico a las nueces", "No como nueces", "Both A and B are correct"],
                "answer": "d",
                "hints": ["You can use 'tener alergia' or 'ser alergico'.", "Both constructions are commonly used."],
                "xp": 30,
                "lesson": "'Soy alergico/a a...' or 'Tengo alergia a...' both work for food allergies. Essential safety phrases: 'Tiene gluten?' (Does it have gluten?), 'Sin lactosa' (Without lactose), 'No puedo comer...' (I can't eat...).",
            },
            {
                "id": "ord_full_order",
                "title": "The Complete Order",
                "type": "quiz",
                "question": "Put these restaurant phrases in logical order: 1) La cuenta, por favor 2) Quisiera la paella 3) Una mesa para dos, por favor 4) De postre, el flan",
                "options": ["3, 2, 4, 1", "2, 3, 1, 4", "1, 2, 3, 4", "3, 1, 2, 4"],
                "answer": "a",
                "hints": ["First get a table, then order main, then dessert, then pay.", "The natural flow of a restaurant visit."],
                "xp": 35,
                "lesson": "Restaurant flow: 1) 'Una mesa para dos, por favor' (A table for two) 2) 'Quisiera la paella' (I'd like the paella) 3) 'De postre, el flan' (For dessert, the flan) 4) 'La cuenta, por favor' (The check). You can now handle a complete restaurant visit!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 5: Cooking --
    "cooking": {
        "id": "cooking",
        "name": "In the Kitchen",
        "description": "Learn cooking verbs and kitchen vocabulary",
        "level_required": 3,
        "challenges": [
            {
                "id": "cook_cocinar",
                "title": "To Cook",
                "type": "quiz",
                "question": "What does 'cocinar' mean?",
                "options": ["To eat", "To cook", "To buy", "To serve"],
                "answer": "b",
                "hints": ["Related to 'cocina' (kitchen).", "It's the general word for preparing food."],
                "xp": 25,
                "lesson": "'Cocinar' = to cook. 'La cocina' = the kitchen (also means 'cuisine'). 'El cocinero / la cocinera' = the cook/chef. 'Cocinar' is the general term for preparing food with heat.",
            },
            {
                "id": "cook_hervir",
                "title": "To Boil",
                "type": "quiz",
                "question": "What does 'hervir' mean?",
                "options": ["To fry", "To bake", "To boil", "To grill"],
                "answer": "c",
                "hints": ["Think of water bubbling on the stove.", "Used for pasta, eggs, soups."],
                "xp": 25,
                "lesson": "'Hervir' = to boil. 'Hervir agua' = to boil water. 'Hervir los huevos' = to boil the eggs. 'A fuego lento' = on low heat (simmer). Water-based cooking methods are common in Spanish cuisine.",
            },
            {
                "id": "cook_freir",
                "title": "To Fry",
                "type": "quiz",
                "question": "'Freir' means to fry. What are 'papas fritas'?",
                "options": ["Fried rice", "French fries/Fried potatoes", "Fried chicken", "Fried eggs"],
                "answer": "b",
                "hints": ["'Papas' = potatoes, 'fritas' = fried.", "A beloved side dish worldwide."],
                "xp": 25,
                "lesson": "'Freir' = to fry. 'Papas fritas' = French fries/fried potatoes. 'Huevos fritos' = fried eggs. 'Pollo frito' = fried chicken. The past participle 'frito/frita' means 'fried.'",
            },
            {
                "id": "cook_cortar",
                "title": "To Cut",
                "type": "quiz",
                "question": "What does 'cortar' mean?",
                "options": ["To mix", "To pour", "To cut", "To wash"],
                "answer": "c",
                "hints": ["Think of 'court' -- to cut short.", "You do this with a knife (cuchillo)."],
                "xp": 25,
                "lesson": "'Cortar' = to cut. 'Cortar la cebolla' = to cut the onion. 'El cuchillo' = knife. 'Picar' = to chop/mince (cut into small pieces). 'Rebanar' = to slice. Cutting is the first step in most recipes!",
            },
            {
                "id": "cook_mezclar",
                "title": "To Mix",
                "type": "quiz",
                "question": "What does 'mezclar' mean?",
                "options": ["To measure", "To mix", "To melt", "To peel"],
                "answer": "b",
                "hints": ["Think of 'mezcla' = mixture.", "Combining ingredients together."],
                "xp": 25,
                "lesson": "'Mezclar' = to mix. 'Mezclar los ingredientes' = mix the ingredients. 'La mezcla' = the mixture. Other useful verbs: 'batir' (to beat/whisk), 'remover' (to stir), 'anadir' (to add).",
            },
            {
                "id": "cook_recipe",
                "title": "Reading a Recipe",
                "type": "quiz",
                "question": "A recipe says 'Cortar las cebollas, freir en aceite, y mezclar con los tomates.' What should you do?",
                "options": ["Boil the onions, bake in oil, and mix with tomatoes", "Cut the onions, fry in oil, and mix with the tomatoes", "Wash the onions, grill in oil, and serve with tomatoes", "Peel the onions, steam in oil, and blend with tomatoes"],
                "answer": "b",
                "hints": ["Cortar = cut, freir = fry, mezclar = mix.", "Aceite = oil, cebollas = onions, tomates = tomatoes."],
                "xp": 35,
                "lesson": "'Cortar las cebollas, freir en aceite, y mezclar con los tomates' = Cut the onions, fry in oil, and mix with the tomatoes. You can now read basic Spanish recipes! Key words: aceite (oil), sal (salt), pimienta (pepper), azucar (sugar).",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 6: Food Culture --
    "food_culture": {
        "id": "food_culture",
        "name": "Food Culture",
        "description": "Explore culinary traditions across the Spanish-speaking world",
        "level_required": 3,
        "challenges": [
            {
                "id": "fc_tapas",
                "title": "Tapas",
                "type": "quiz",
                "question": "What are 'tapas' in Spanish food culture?",
                "options": ["A type of soup", "Small dishes/appetizers shared among friends", "A dessert tradition", "A breakfast meal"],
                "answer": "b",
                "hints": ["They originated in Spain.", "'Tapa' means 'lid' or 'cover' -- legend says they started as covers for drinks."],
                "xp": 25,
                "lesson": "'Tapas' are small dishes shared among friends, originating in Spain. The word 'tapa' means 'lid' -- legend says bartenders placed bread over drinks to keep flies out, then started adding toppings. Now tapas culture is an art form!",
            },
            {
                "id": "fc_paella",
                "title": "Paella",
                "type": "quiz",
                "question": "Paella is one of Spain's most famous dishes. Where does it originate?",
                "options": ["Madrid", "Barcelona", "Valencia", "Seville"],
                "answer": "c",
                "hints": ["It's from Spain's eastern coast.", "The region is known for rice cultivation."],
                "xp": 25,
                "lesson": "Paella originated in Valencia, Spain. Traditional paella Valenciana uses rice, saffron, rabbit, chicken, and vegetables. 'Paella de mariscos' (seafood paella) is also popular. The name comes from the pan it's cooked in!",
            },
            {
                "id": "fc_tacos",
                "title": "Tacos",
                "type": "quiz",
                "question": "Tacos are the iconic food of which Spanish-speaking country?",
                "options": ["Spain", "Argentina", "Colombia", "Mexico"],
                "answer": "d",
                "hints": ["This country is north of Central America.", "Think of tortillas, salsa, and guacamole."],
                "xp": 25,
                "lesson": "Tacos are Mexico's iconic food -- tortillas filled with meat, vegetables, salsa, and toppings. 'Taco al pastor' (shepherd-style), 'taco de carnitas' (slow-cooked pork), 'taco de pescado' (fish taco). Mexican cuisine is UNESCO World Heritage!",
            },
            {
                "id": "fc_empanadas",
                "title": "Empanadas",
                "type": "quiz",
                "question": "Empanadas are popular across Latin America. What are they?",
                "options": ["A type of soup", "Stuffed pastries/turnovers", "A rice dish", "A grilled meat"],
                "answer": "b",
                "hints": ["'Empanar' means 'to bread' or 'to wrap in bread'.", "They're filled with meat, cheese, or vegetables."],
                "xp": 25,
                "lesson": "Empanadas are stuffed pastries found throughout Latin America. Argentina is famous for them. Fillings vary: carne (beef), pollo (chicken), jamon y queso (ham and cheese). Each country has its own style!",
            },
            {
                "id": "fc_churros",
                "title": "Churros",
                "type": "quiz",
                "question": "Churros con chocolate is a classic Spanish treat. What are churros?",
                "options": ["Chocolate cookies", "Fried dough sticks dipped in thick chocolate", "Chocolate-filled pastries", "Chocolate cake slices"],
                "answer": "b",
                "hints": ["They're long, ridged, and fried.", "The chocolate is thick and rich -- for dipping."],
                "xp": 25,
                "lesson": "Churros are fried dough sticks, crispy outside and soft inside, traditionally dipped in thick hot chocolate. 'Churros con chocolate' is a beloved breakfast and snack in Spain. In Latin America, churros are often filled with dulce de leche!",
            },
            {
                "id": "fc_match_country",
                "title": "Match the Dish",
                "type": "quiz",
                "question": "Which pairing is CORRECT?",
                "options": ["Ceviche - Argentina", "Pupusas - El Salvador", "Tacos - Spain", "Paella - Mexico"],
                "answer": "b",
                "hints": ["Pupusas are thick corn tortillas stuffed with cheese, beans, or meat.", "They're the national dish of a small Central American country."],
                "xp": 35,
                "lesson": "Dish-country pairings: Pupusas - El Salvador, Ceviche - Peru, Tacos - Mexico, Paella - Spain, Empanadas - Argentina, Gallo pinto - Costa Rica, Bandeja paisa - Colombia, Asado - Argentina/Uruguay. Every country has its culinary identity!",
                "is_boss": True,
            },
        ],
    },
}
