"""
zones.py — Food & Drink zones and challenges.

All challenges use "type": "quiz" with multiple-choice options.
Guided by 先生 (Sensei), a wise, patient Japanese teacher.
"""

ZONE_ORDER = [
    "common_foods",
    "drinks",
    "ordering",
    "tastes",
    "chopstick_etiquette",
    "food_culture",
]

ZONES = {
    # -- Zone 1: Common Foods ------------------------------------------------
    "common_foods": {
        "id": "common_foods",
        "name": "Common Foods",
        "description": "Learn staple Japanese foods: ごはん, ラーメン, すし, てんぷら",
        "level_required": 1,
        "challenges": [
            {
                "id": "food_gohan",
                "title": "Rice",
                "type": "quiz",
                "question": "ごはん (gohan) means: (Romaji: gohan)",
                "options": ["Bread", "Cooked rice / meal", "Noodles", "Soup"],
                "answer": "b",
                "hints": [
                    "ごはん is the most fundamental Japanese food.",
                    "It can mean both 'cooked rice' and 'meal' in general.",
                ],
                "xp": 25,
                "lesson": "ごはん (gohan) = cooked rice / meal. Rice is central to Japanese cuisine. あさごはん = breakfast, ひるごはん = lunch, ばんごはん = dinner.",
                "is_boss": False,
                "flavor": "Sensei scoops steaming rice into a bowl.",
            },
            {
                "id": "food_ramen",
                "title": "Ramen",
                "type": "quiz",
                "question": "ラーメン (raamen) is written in katakana because: (Romaji: raamen)",
                "options": ["It's a traditional Japanese word", "It originally came from China", "It's a brand name", "It's slang"],
                "answer": "b",
                "hints": [
                    "Katakana is used for foreign-origin words.",
                    "Ramen has Chinese roots -- the noodles came from China.",
                ],
                "xp": 25,
                "lesson": "ラーメン (raamen) = ramen noodle soup. Written in katakana because it originated from Chinese cuisine. Major styles: しょうゆ (soy sauce), みそ (miso), しお (salt), とんこつ (pork bone).",
                "is_boss": False,
                "flavor": "Sensei slurps noodles loudly -- that's polite in Japan!",
            },
            {
                "id": "food_sushi",
                "title": "Sushi",
                "type": "quiz",
                "question": "すし (sushi) traditionally refers to: (Romaji: sushi)",
                "options": ["Raw fish only", "Vinegared rice with toppings", "Any seafood dish", "Fried fish"],
                "answer": "b",
                "hints": [
                    "The key ingredient is actually the rice, not the fish.",
                    "すし rice is seasoned with vinegar, sugar, and salt.",
                ],
                "xp": 25,
                "lesson": "すし (sushi) = vinegared rice with toppings/fillings. Types: にぎり (nigiri, hand-pressed), まき (maki, rolled), さしみ (sashimi) is raw fish WITHOUT rice.",
                "is_boss": False,
                "flavor": "Sensei places a perfect piece of にぎり on a wooden board.",
            },
            {
                "id": "food_tempura",
                "title": "Tempura",
                "type": "quiz",
                "question": "てんぷら (tenpura) is: (Romaji: tenpura)",
                "options": ["Grilled meat", "Lightly battered and deep-fried food", "Steamed vegetables", "Pickled fish"],
                "answer": "b",
                "hints": [
                    "てんぷら uses a light, crispy batter.",
                    "Common items: えび (shrimp), なす (eggplant), さつまいも (sweet potato).",
                ],
                "xp": 25,
                "lesson": "てんぷら (tenpura) = lightly battered, deep-fried food. Originally influenced by Portuguese missionaries. Common ingredients: えび (shrimp), やさい (vegetables).",
                "is_boss": False,
                "flavor": "Sensei holds up a golden piece of えびてんぷら.",
            },
            {
                "id": "food_niku_sakana",
                "title": "Meat & Fish",
                "type": "quiz",
                "question": "にく (niku) means meat. What is さかな (sakana)? (Romaji: niku / sakana)",
                "options": ["Vegetable", "Fruit", "Fish", "Chicken"],
                "answer": "c",
                "hints": [
                    "さかな is a staple of Japanese island cuisine.",
                    "Japan is surrounded by ocean -- seafood is fundamental.",
                ],
                "xp": 25,
                "lesson": "にく (niku) = meat. さかな (sakana) = fish. Types of meat: ぎゅうにく (beef), ぶたにく (pork), とりにく (chicken). さかな is broadly 'fish/seafood'.",
                "is_boss": False,
                "flavor": "Sensei shows a display of fresh fish at Tsukiji market.",
            },
            {
                "id": "food_common_boss",
                "title": "Menu Reader",
                "type": "quiz",
                "question": "You see ぎゅうどん (gyuudon) on a menu. ぎゅう means beef, どん is short for どんぶり (rice bowl). What is it?",
                "options": ["Beef soup", "Beef rice bowl", "Beef sushi", "Grilled beef"],
                "answer": "b",
                "hints": [
                    "どんぶり (donburi) = a large bowl of rice with toppings.",
                    "ぎゅう = beef + どん = rice bowl.",
                ],
                "xp": 35,
                "lesson": "どんぶり/どん = rice bowl dish. ぎゅうどん (beef bowl), かつどん (cutlet bowl), おやこどん (chicken & egg bowl -- おやこ means 'parent and child'!).",
                "is_boss": True,
                "flavor": "Sensei tests your ability to decode a Japanese menu.",
            },
        ],
    },

    # -- Zone 2: Drinks -------------------------------------------------------
    "drinks": {
        "id": "drinks",
        "name": "Drinks",
        "description": "Learn Japanese drink vocabulary: おちゃ, みず, ビール, コーヒー",
        "level_required": 2,
        "challenges": [
            {
                "id": "drink_ocha",
                "title": "Japanese Tea",
                "type": "quiz",
                "question": "おちゃ (ocha) means: (Romaji: ocha)",
                "options": ["Coffee", "Tea (especially green tea)", "Juice", "Milk"],
                "answer": "b",
                "hints": [
                    "おちゃ is the default tea in Japan -- green tea.",
                    "お is an honorific prefix showing respect for this beloved drink.",
                ],
                "xp": 25,
                "lesson": "おちゃ (ocha) = tea, especially green tea. Types: りょくちゃ (green tea), むぎちゃ (barley tea), こうちゃ (black tea -- literally 'red tea').",
                "is_boss": False,
                "flavor": "Sensei pours a cup of steaming green tea.",
            },
            {
                "id": "drink_mizu",
                "title": "Water",
                "type": "quiz",
                "question": "みず (mizu) means: (Romaji: mizu)",
                "options": ["Juice", "Milk", "Water", "Soda"],
                "answer": "c",
                "hints": [
                    "みず is the most basic drink vocabulary.",
                    "In Japanese restaurants, water is usually served free.",
                ],
                "xp": 25,
                "lesson": "みず (mizu) = water. おみず (omizu) is the polite form. In Japan, restaurants serve free water (おひや, ohiya = cold water) automatically.",
                "is_boss": False,
                "flavor": "Sensei reminds you that Japan's tap water is safe to drink.",
            },
            {
                "id": "drink_biiru",
                "title": "Beer",
                "type": "quiz",
                "question": "ビール (biiru) is written in katakana because: (Romaji: biiru)",
                "options": ["It's a Japanese invention", "It's a foreign loanword (from Dutch/English)", "It's informal", "It's a brand name"],
                "answer": "b",
                "hints": [
                    "Katakana is used for words borrowed from other languages.",
                    "ビール comes from the Dutch/English word 'beer'.",
                ],
                "xp": 25,
                "lesson": "ビール (biiru) = beer. A loanword, hence katakana. Drinking culture: とりあえずビール (toriaezu biiru) = 'beer for now' -- the standard first order at izakayas.",
                "is_boss": False,
                "flavor": "Sensei explains the famous 'first round is always beer' custom.",
            },
            {
                "id": "drink_koohii",
                "title": "Coffee",
                "type": "quiz",
                "question": "コーヒー (koohii) is: (Romaji: koohii)",
                "options": ["Tea", "Coffee", "Hot chocolate", "Soda"],
                "answer": "b",
                "hints": [
                    "This katakana word sounds like the English 'coffee'.",
                    "Japan has a thriving coffee culture with kissaten (old-style cafes).",
                ],
                "xp": 25,
                "lesson": "コーヒー (koohii) = coffee. Japan has an enormous coffee culture. きっさてん (kissaten) = traditional Japanese coffee shops. コンビニコーヒー = convenience store coffee.",
                "is_boss": False,
                "flavor": "Sensei takes you to a quiet kissaten for a hand-dripped cup.",
            },
            {
                "id": "drink_sake_juice",
                "title": "Sake & Juice",
                "type": "quiz",
                "question": "にほんしゅ (nihonshu) refers to: (Romaji: nihonshu)",
                "options": ["Japanese whiskey", "Japanese rice wine (sake)", "Japanese beer", "Japanese soda"],
                "answer": "b",
                "hints": [
                    "にほん = Japan, しゅ = alcohol/liquor.",
                    "What foreigners call 'sake' is にほんしゅ in Japan.",
                ],
                "xp": 30,
                "lesson": "にほんしゅ (nihonshu) = Japanese sake (rice wine). Note: さけ (sake) in Japanese just means 'alcohol' in general. ジュース (juusu) = juice, ぎゅうにゅう (gyuunyuu) = milk.",
                "is_boss": False,
                "flavor": "Sensei explains the difference between sake and さけ.",
            },
            {
                "id": "drinks_boss",
                "title": "Drink Order Challenge",
                "type": "quiz",
                "question": "At an izakaya, the group shouts とりあえずビール! What does this mean?",
                "options": ["No more beer!", "Beer for everyone, to start!", "The beer is expensive!", "Bring the food first!"],
                "answer": "b",
                "hints": [
                    "とりあえず (toriaezu) = for now / to start with.",
                    "This is the most common first order at any Japanese drinking spot.",
                ],
                "xp": 35,
                "lesson": "とりあえずビール (toriaezu biiru) = beer for now / beer to start. This phrase is a cultural institution -- at izakayas, everyone orders beer first while deciding on food.",
                "is_boss": True,
                "flavor": "Sensei tests your izakaya cultural knowledge.",
            },
        ],
    },

    # -- Zone 3: Ordering Food ------------------------------------------------
    "ordering": {
        "id": "ordering",
        "name": "Ordering Food",
        "description": "Learn to order: ください, おねがいします, メニュー",
        "level_required": 3,
        "challenges": [
            {
                "id": "order_kudasai",
                "title": "Please Give Me",
                "type": "quiz",
                "question": "ラーメンをください (raamen o kudasai) means: (Romaji: raamen o kudasai)",
                "options": ["I like ramen", "Ramen, please / Please give me ramen", "Is there ramen?", "No ramen for me"],
                "answer": "b",
                "hints": [
                    "を (o) marks the object, ください (kudasai) = please give me.",
                    "Pattern: [item] を ください = [item], please.",
                ],
                "xp": 25,
                "lesson": "...をください (...o kudasai) = please give me... This is the most basic ordering pattern. を marks what you want, ください is 'please give me'.",
                "is_boss": False,
                "flavor": "Sensei orders ramen with perfect form.",
            },
            {
                "id": "order_onegai",
                "title": "I'd Like...",
                "type": "quiz",
                "question": "おみずをおねがいします (omizu o onegaishimasu) means: (Romaji: omizu o onegaishimasu)",
                "options": ["Where is the water?", "Water, please (polite)", "I don't want water", "Is this water?"],
                "answer": "b",
                "hints": [
                    "おねがいします is more polite than ください.",
                    "おみず = water (polite), おねがいします = I humbly request.",
                ],
                "xp": 25,
                "lesson": "...をおねがいします = I'd like... (very polite). More formal than ください. Use in nicer restaurants or when speaking to elders.",
                "is_boss": False,
                "flavor": "Sensei demonstrates the polite ordering style.",
            },
            {
                "id": "order_menu",
                "title": "The Menu",
                "type": "quiz",
                "question": "メニューをみせてください (menyuu o misete kudasai) means: (Romaji: menyuu o misete kudasai)",
                "options": ["Please show me the menu", "Please take the menu", "I don't need a menu", "Is this the menu?"],
                "answer": "a",
                "hints": [
                    "メニュー (menyuu) = menu, みせて (misete) = show me.",
                    "ください makes it a polite request.",
                ],
                "xp": 25,
                "lesson": "メニューをみせてください = please show me the menu. Also useful: おすすめはなんですか (osusume wa nan desu ka) = what do you recommend?",
                "is_boss": False,
                "flavor": "Sensei shows you how to ask for the menu politely.",
            },
            {
                "id": "order_kore",
                "title": "This One, Please",
                "type": "quiz",
                "question": "これをください (kore o kudasai) means: (Romaji: kore o kudasai)",
                "options": ["What is this?", "This one, please", "Not this one", "I don't want this"],
                "answer": "b",
                "hints": [
                    "これ (kore) = this (thing near me).",
                    "Pointing at a menu item and saying これをください always works!",
                ],
                "xp": 25,
                "lesson": "これをください = this one, please. これ = this, それ = that (near you), あれ = that (over there). Point and say これをください -- the universal ordering hack!",
                "is_boss": False,
                "flavor": "Sensei reveals the simplest way to order anywhere in Japan.",
            },
            {
                "id": "order_okaikei",
                "title": "The Check, Please",
                "type": "quiz",
                "question": "おかいけいをおねがいします (okaikei o onegaishimasu) means: (Romaji: okaikei o onegaishimasu)",
                "options": ["More food, please", "The check/bill, please", "A receipt, please", "Change, please"],
                "answer": "b",
                "hints": [
                    "おかいけい (okaikei) = the check/bill.",
                    "Also commonly heard: おかんじょう (okanjou) = the bill.",
                ],
                "xp": 30,
                "lesson": "おかいけいをおねがいします = the check, please. Also: おかんじょう (okanjou) = bill. In Japan, you usually pay at the register near the exit, not at your table.",
                "is_boss": False,
                "flavor": "Sensei shows you how to wrap up a meal politely.",
            },
            {
                "id": "ordering_boss",
                "title": "Restaurant Role Play",
                "type": "quiz",
                "question": "The waiter says ごちゅうもんはおきまりですか (go-chuumon wa okimari desu ka). What are they asking?",
                "options": ["Is everything okay?", "Are you ready to order?", "Would you like dessert?", "How would you like to pay?"],
                "answer": "b",
                "hints": [
                    "ちゅうもん (chuumon) = order, きまり (kimari) = decided.",
                    "This is the standard phrase waiters use to take your order.",
                ],
                "xp": 35,
                "lesson": "ごちゅうもんはおきまりですか = have you decided on your order? Reply: はい、[item]をください。Or: もうすこしまってください (mou sukoshi matte kudasai) = please wait a moment.",
                "is_boss": True,
                "flavor": "Sensei tests your real-world restaurant Japanese.",
            },
        ],
    },

    # -- Zone 4: Tastes -------------------------------------------------------
    "tastes": {
        "id": "tastes",
        "name": "Tastes & Flavors",
        "description": "Describe flavors: おいしい, からい, あまい, しょっぱい",
        "level_required": 4,
        "challenges": [
            {
                "id": "taste_oishii",
                "title": "Delicious!",
                "type": "quiz",
                "question": "おいしい (oishii) means: (Romaji: oishii)",
                "options": ["Terrible", "Delicious / tasty", "Spicy", "Sour"],
                "answer": "b",
                "hints": [
                    "This is the most important food compliment in Japanese.",
                    "Say it after eating and the cook will be thrilled.",
                ],
                "xp": 25,
                "lesson": "おいしい (oishii) = delicious / tasty. The most useful food word. Also: うまい (umai) = delicious (casual, masculine). おいしくない = not delicious.",
                "is_boss": False,
                "flavor": "Sensei takes a bite and beams -- おいしい!",
            },
            {
                "id": "taste_karai",
                "title": "Spicy",
                "type": "quiz",
                "question": "からい (karai) means: (Romaji: karai)",
                "options": ["Sweet", "Salty", "Spicy / hot", "Bitter"],
                "answer": "c",
                "hints": [
                    "からい describes the heat/spiciness of food.",
                    "Be careful: からい can also mean 'salty' in some dialects.",
                ],
                "xp": 25,
                "lesson": "からい (karai) = spicy/hot. Be aware: historically, からい could mean salty too. To be specific about salty, use しょっぱい (shoppai).",
                "is_boss": False,
                "flavor": "Sensei fans their mouth after a bite of wasabi.",
            },
            {
                "id": "taste_amai",
                "title": "Sweet",
                "type": "quiz",
                "question": "あまい (amai) means: (Romaji: amai)",
                "options": ["Sour", "Sweet", "Bitter", "Savory"],
                "answer": "b",
                "hints": [
                    "Japanese sweets (わがし) are known for being あまい.",
                    "あまい can also mean 'naive/lenient' about a person.",
                ],
                "xp": 25,
                "lesson": "あまい (amai) = sweet. Japanese desserts: わがし (wagashi, traditional sweets), もち (mochi, rice cakes), だんご (dango, sweet dumplings).",
                "is_boss": False,
                "flavor": "Sensei offers you a piece of sweet もち.",
            },
            {
                "id": "taste_shoppai",
                "title": "Salty",
                "type": "quiz",
                "question": "しょっぱい (shoppai) means: (Romaji: shoppai)",
                "options": ["Sweet", "Spicy", "Salty", "Sour"],
                "answer": "c",
                "hints": [
                    "しょっぱい specifically means salty.",
                    "しお (shio) = salt, and しょっぱい derives from it.",
                ],
                "xp": 25,
                "lesson": "しょっぱい (shoppai) = salty. Related: しお (shio) = salt. Japanese cuisine uses soy sauce (しょうゆ, shouyu) and miso, both quite salty.",
                "is_boss": False,
                "flavor": "Sensei sprinkles salt on a rice ball -- おにぎり.",
            },
            {
                "id": "taste_nigai_suppai",
                "title": "Bitter & Sour",
                "type": "quiz",
                "question": "にがい (nigai) means bitter. What does すっぱい (suppai) mean? (Romaji: nigai / suppai)",
                "options": ["Sweet", "Spicy", "Bland", "Sour"],
                "answer": "d",
                "hints": [
                    "すっぱい describes the taste of lemon or vinegar.",
                    "うめぼし (umeboshi, pickled plum) is famously すっぱい.",
                ],
                "xp": 30,
                "lesson": "にがい (nigai) = bitter. すっぱい (suppai) = sour. The five basic tastes in Japanese: あまい (sweet), からい (spicy), しょっぱい (salty), にがい (bitter), すっぱい (sour).",
                "is_boss": False,
                "flavor": "Sensei puckers at the sourness of an umeboshi.",
            },
            {
                "id": "tastes_boss",
                "title": "Flavor Master",
                "type": "quiz",
                "question": "You bite into わさび (wasabi). Your mouth is on fire. Which word describes this?",
                "options": ["あまい (amai)", "すっぱい (suppai)", "からい (karai)", "にがい (nigai)"],
                "answer": "c",
                "hints": [
                    "Wasabi creates a burning, spicy sensation.",
                    "からい covers both chili-spicy and wasabi-spicy.",
                ],
                "xp": 35,
                "lesson": "Wasabi is からい -- intensely so! Japanese has no separate word for 'pungent' vs 'chili hot' -- からい covers both. You might hear ぴりからい (pirikarai) for 'mildly spicy'.",
                "is_boss": True,
                "flavor": "Sensei watches your reaction to the wasabi test.",
            },
        ],
    },

    # -- Zone 5: Chopstick Etiquette ------------------------------------------
    "chopstick_etiquette": {
        "id": "chopstick_etiquette",
        "name": "Chopstick Etiquette",
        "description": "Learn proper おはし manners and taboo actions",
        "level_required": 5,
        "challenges": [
            {
                "id": "chop_ohashi",
                "title": "Chopsticks",
                "type": "quiz",
                "question": "おはし (ohashi) means: (Romaji: ohashi)",
                "options": ["Spoon", "Fork", "Chopsticks", "Knife"],
                "answer": "c",
                "hints": [
                    "はし (hashi) = chopsticks, お is the polite prefix.",
                    "The primary eating utensil in Japan.",
                ],
                "xp": 25,
                "lesson": "おはし (ohashi) = chopsticks. はし without the お is casual. わりばし (waribashi) = disposable wooden chopsticks (the kind you snap apart).",
                "is_boss": False,
                "flavor": "Sensei places a pair of lacquered chopsticks before you.",
            },
            {
                "id": "chop_tate",
                "title": "Standing Chopsticks Taboo",
                "type": "quiz",
                "question": "たてばし (tatebashi) -- sticking chopsticks upright in rice -- is taboo because: (Romaji: tatebashi)",
                "options": ["It's considered lazy", "It resembles a funeral ritual for the dead", "It wastes rice", "It's bad for the chopsticks"],
                "answer": "b",
                "hints": [
                    "At Buddhist funerals, incense sticks are placed upright.",
                    "Rice with upright chopsticks is offered to the deceased.",
                ],
                "xp": 30,
                "lesson": "たてばし (tatebashi) = standing chopsticks in rice. This mimics offerings to the dead at Buddhist funerals. Never do this -- it's one of the strongest food taboos in Japan.",
                "is_boss": False,
                "flavor": "Sensei's expression turns serious -- this is important.",
            },
            {
                "id": "chop_watashi",
                "title": "Passing Food Taboo",
                "type": "quiz",
                "question": "うつしばし (utsushibashi) -- passing food chopstick-to-chopstick -- is taboo because: (Romaji: utsushibashi)",
                "options": ["It's unhygienic", "It mirrors how bones are handled at funerals", "It's considered greedy", "It makes noise"],
                "answer": "b",
                "hints": [
                    "After cremation, family members pass bones this way.",
                    "This is the ONLY other time chopstick-to-chopstick passing occurs.",
                ],
                "xp": 30,
                "lesson": "うつしばし (utsushibashi) = passing food between chopsticks. This mirrors the ritual of passing cremated bones at funerals. Instead, place food on a shared plate.",
                "is_boss": False,
                "flavor": "Sensei explains a deeply ingrained cultural taboo.",
            },
            {
                "id": "chop_hashioki",
                "title": "Chopstick Rest",
                "type": "quiz",
                "question": "はしおき (hashioki) is: (Romaji: hashioki)",
                "options": ["A type of food", "A chopstick rest", "A napkin", "A sauce dish"],
                "answer": "b",
                "hints": [
                    "はし = chopsticks, おき comes from おく = to place.",
                    "A small object where you rest your chopsticks when not eating.",
                ],
                "xp": 25,
                "lesson": "はしおき (hashioki) = chopstick rest. When not eating, place chopsticks on the はしおき, not across your bowl or sticking out. It shows refinement.",
                "is_boss": False,
                "flavor": "Sensei places their chopsticks neatly on a ceramic rest.",
            },
            {
                "id": "chop_manners",
                "title": "Good Chopstick Manners",
                "type": "quiz",
                "question": "Which of these is GOOD chopstick manners in Japan?",
                "options": ["Pointing at people with chopsticks", "Stabbing food with chopsticks", "Picking up food cleanly from a shared plate", "Licking your chopsticks clean"],
                "answer": "c",
                "hints": [
                    "Pointing, stabbing, and licking are all considered rude.",
                    "Good manners means using chopsticks with precision and care.",
                ],
                "xp": 25,
                "lesson": "Good manners: pick up food cleanly, don't hover over dishes (まよいばし), don't point (さしばし), don't stab (さしばし), don't lick (ねぶりばし).",
                "is_boss": False,
                "flavor": "Sensei demonstrates graceful chopstick technique.",
            },
            {
                "id": "chopstick_boss",
                "title": "Etiquette Challenge",
                "type": "quiz",
                "question": "Your friend sticks their chopsticks upright in a bowl of rice and passes food to you chopstick-to-chopstick. How many taboos did they break?",
                "options": ["Zero -- these are fine", "One -- only the passing is bad", "Two -- both are funeral-related taboos", "Three -- there's a third hidden taboo"],
                "answer": "c",
                "hints": [
                    "たてばし (upright in rice) and うつしばし (passing between chopsticks).",
                    "Both actions are associated with Japanese funeral rituals.",
                ],
                "xp": 35,
                "lesson": "Two major taboos: たてばし (upright chopsticks = funeral offering) and うつしばし (chopstick passing = bone ceremony). Both are deeply offensive at the dinner table.",
                "is_boss": True,
                "flavor": "Sensei tests your understanding of chopstick taboos.",
            },
        ],
    },

    # -- Zone 6: Food Culture -------------------------------------------------
    "food_culture": {
        "id": "food_culture",
        "name": "Food Culture",
        "description": "Japanese dining rituals: いただきます, ごちそうさま, and more",
        "level_required": 6,
        "challenges": [
            {
                "id": "culture_itadakimasu",
                "title": "Before Eating",
                "type": "quiz",
                "question": "いただきます (itadakimasu) is said: (Romaji: itadakimasu)",
                "options": ["After eating", "Before eating", "When cooking", "When ordering"],
                "answer": "b",
                "hints": [
                    "いただく means 'to humbly receive'.",
                    "Said with hands pressed together before the first bite.",
                ],
                "xp": 25,
                "lesson": "いただきます (itadakimasu) = I humbly receive (said before eating). It expresses gratitude to the cook, the farmers, and the food itself. Hands together, slight bow.",
                "is_boss": False,
                "flavor": "Sensei presses their hands together -- いただきます!",
            },
            {
                "id": "culture_gochisousama",
                "title": "After Eating",
                "type": "quiz",
                "question": "ごちそうさまでした (gochisousama deshita) is said: (Romaji: gochisousama deshita)",
                "options": ["Before eating", "When ordering", "After finishing a meal", "When entering a restaurant"],
                "answer": "c",
                "hints": [
                    "ごちそう means 'feast/treat', さま is an honorific.",
                    "It thanks everyone involved in the meal.",
                ],
                "xp": 25,
                "lesson": "ごちそうさまでした (gochisousama deshita) = it was a feast / thank you for the meal (said after eating). Casual: ごちそうさま. Always say this -- even at fast food restaurants!",
                "is_boss": False,
                "flavor": "Sensei puts down their chopsticks and speaks with gratitude.",
            },
            {
                "id": "culture_slurp",
                "title": "Slurping Noodles",
                "type": "quiz",
                "question": "In Japan, slurping noodles loudly is: (Romaji: susuru = to slurp)",
                "options": ["Extremely rude", "Perfectly acceptable and even polite", "Only okay for children", "Only at home"],
                "answer": "b",
                "hints": [
                    "Slurping noodles cools them down and enhances flavor.",
                    "This is the opposite of Western table manners!",
                ],
                "xp": 25,
                "lesson": "Slurping (すする, susuru) noodles is polite in Japan! It cools the noodles, enhances flavor, and shows you're enjoying the meal. This applies to ramen, soba, and udon.",
                "is_boss": False,
                "flavor": "Sensei demonstrates a magnificent slurp.",
            },
            {
                "id": "culture_oshibori",
                "title": "The Hot Towel",
                "type": "quiz",
                "question": "おしぼり (oshibori) given at restaurants is for: (Romaji: oshibori)",
                "options": ["Wiping your face and neck", "Cleaning your hands before eating", "Cleaning the table", "Drying your hair"],
                "answer": "b",
                "hints": [
                    "おしぼり is a wet towel, either hot or cold.",
                    "It's meant for your hands -- not your face (at formal places).",
                ],
                "xp": 25,
                "lesson": "おしぼり (oshibori) = wet hand towel. Used to clean hands before eating. At casual places, wiping your face is fine. At formal restaurants, hands only.",
                "is_boss": False,
                "flavor": "Sensei hands you a steaming おしぼり.",
            },
            {
                "id": "culture_kampai",
                "title": "Cheers!",
                "type": "quiz",
                "question": "かんぱい (kampai) means: (Romaji: kampai)",
                "options": ["Goodbye", "Cheers! (drinking toast)", "Bon appetit", "Thank you"],
                "answer": "b",
                "hints": [
                    "かん = dry, ぱい = glass/cup -- literally 'dry your cup'.",
                    "Said when everyone raises their glasses together.",
                ],
                "xp": 30,
                "lesson": "かんぱい (kampai) = cheers! Literally 'dry cup.' Essential at any drinking gathering. Everyone raises their glass, says かんぱい, and takes the first sip together.",
                "is_boss": False,
                "flavor": "Sensei raises a glass -- かんぱい!",
            },
            {
                "id": "food_culture_boss",
                "title": "Dining Ritual Master",
                "type": "quiz",
                "question": "Put the dining ritual in order: you sit down, receive food, eat, finish eating.",
                "options": [
                    "おしぼり → いただきます → おいしい! → ごちそうさまでした",
                    "ごちそうさまでした → いただきます → おいしい! → おしぼり",
                    "いただきます → おしぼり → ごちそうさまでした → おいしい!",
                    "おいしい! → ごちそうさまでした → おしぼり → いただきます"
                ],
                "answer": "a",
                "hints": [
                    "First clean your hands, then express gratitude before eating.",
                    "ごちそうさまでした always comes at the very end.",
                ],
                "xp": 35,
                "lesson": "The full dining ritual: 1) おしぼり (clean hands), 2) いただきます (before eating), 3) Enjoy and praise the food, 4) ごちそうさまでした (after eating). This is second nature to every Japanese person.",
                "is_boss": True,
                "flavor": "Sensei tests your understanding of the complete dining experience.",
            },
        ],
    },
}
