"""
zones.py — Katakana zones and challenges.

All challenges use "type": "quiz" with multiple-choice options.
Guided by 先生 (Sensei), a wise, patient Japanese teacher.
"""

ZONE_ORDER = [
    "vowels_kata",
    "ka_sa_rows",
    "ta_na_rows",
    "ha_ma_rows",
    "ya_ra_wa_n",
    "long_vowels_special",
    "reading_loanwords",
]

ZONES = {
    # ── Zone 1: Katakana Vowels アイウエオ ────────────────────────────
    "vowels_kata": {
        "id": "vowels_kata",
        "name": "Katakana Vowels",
        "description": "Learn the five katakana vowels: アイウエオ (a i u e o)",
        "level_required": 1,
        "challenges": [
            {
                "id": "kata_a",
                "title": "ア — The First Katakana",
                "type": "quiz",
                "question": "What sound does ア make? (Romaji: a)",
                "options": ["a — same as hiragana あ", "i — same as hiragana い", "u — same as hiragana う", "ka — like hiragana か"],
                "answer": "a",
                "hints": [
                    "Katakana and hiragana share the same sounds.",
                    "ア is the katakana version of あ.",
                ],
                "xp": 25,
                "lesson": "ア (a) is the katakana form of あ. Same sound 'ah', but angular shape. Katakana characters were derived from parts of kanji characters.",
                "is_boss": False,
                "flavor": "Sensei draws ア with sharp, decisive strokes -- no curves here.",
            },
            {
                "id": "kata_i",
                "title": "イ — Angular I",
                "type": "quiz",
                "question": "Which katakana character represents 'i' (ee)? (Romaji: i)",
                "options": ["ア", "イ", "ウ", "エ"],
                "answer": "b",
                "hints": [
                    "It looks like two strokes forming an angle.",
                    "Same sound as hiragana い.",
                ],
                "xp": 25,
                "lesson": "イ (i) is the katakana 'ee' sound. Example: イギリス (igirisu) = 'England/Britain'.",
                "is_boss": False,
                "flavor": "Sensei draws イ -- two bold angular strokes.",
            },
            {
                "id": "kata_u",
                "title": "ウ — The Third Vowel",
                "type": "quiz",
                "question": "How is ウ pronounced? (Romaji: u)",
                "options": ["a", "i", "u — like 'oo' in 'food'", "e"],
                "answer": "c",
                "hints": [
                    "Same 'oo' sound as hiragana う.",
                    "Think of ウイスキー (uisukii) = whisky.",
                ],
                "xp": 25,
                "lesson": "ウ (u) is the katakana 'oo' sound. Example: ウイスキー (uisukii) = 'whisky'. Note the long vowel mark ー.",
                "is_boss": False,
                "flavor": "Sensei draws ウ with a top stroke and two downward marks.",
            },
            {
                "id": "kata_e",
                "title": "エ — The Fourth Vowel",
                "type": "quiz",
                "question": "What is the reading of エ? (Romaji: e)",
                "options": ["a", "i", "u", "e — as in 'pet'"],
                "answer": "d",
                "hints": [
                    "Same 'eh' sound as hiragana え.",
                    "Think of エレベーター (erebeetaa) = elevator.",
                ],
                "xp": 25,
                "lesson": "エ (e) is the katakana 'eh' sound. Example: エレベーター (erebeetaa) = 'elevator'.",
                "is_boss": False,
                "flavor": "Sensei draws エ -- like the letter 'I' rotated sideways.",
            },
            {
                "id": "kata_o",
                "title": "オ — The Fifth Vowel",
                "type": "quiz",
                "question": "Which sound does オ represent? (Romaji: o)",
                "options": ["a", "u", "e", "o — as in 'go'"],
                "answer": "d",
                "hints": [
                    "Same 'oh' sound as hiragana お.",
                    "Think of オレンジ (orenji) = orange.",
                ],
                "xp": 25,
                "lesson": "オ (o) is the katakana 'oh' sound. Example: オレンジ (orenji) = 'orange'.",
                "is_boss": False,
                "flavor": "Sensei completes the five katakana vowels.",
            },
            {
                "id": "vowels_kata_boss",
                "title": "Katakana vs Hiragana Vowels",
                "type": "quiz",
                "question": "Match the pair: あ = ア, い = イ, う = ウ, え = エ, お = ?",
                "options": ["カ", "コ", "オ", "ホ"],
                "answer": "c",
                "hints": [
                    "The katakana partner of お is...",
                    "It looks like a cross with a curved tail.",
                ],
                "xp": 30,
                "lesson": "The five katakana vowels match their hiragana counterparts: あ=ア, い=イ, う=ウ, え=エ, お=オ. Same sounds, different scripts!",
                "is_boss": True,
                "flavor": "Sensei holds up both scripts side by side -- same sounds, new shapes.",
            },
        ],
    },

    # ── Zone 2: Ka-row & Sa-row ──────────────────────────────────────
    "ka_sa_rows": {
        "id": "ka_sa_rows",
        "name": "Ka-Row & Sa-Row",
        "description": "Learn カキクケコ (ka ki ku ke ko) and サシスセソ (sa shi su se so)",
        "level_required": 2,
        "challenges": [
            {
                "id": "kata_ka",
                "title": "カ — Ka",
                "type": "quiz",
                "question": "What sound does カ make? (Romaji: ka)",
                "options": ["ka", "sa", "ta", "na"],
                "answer": "a",
                "hints": [
                    "It's the katakana version of か.",
                    "Think of カメラ (kamera) = camera.",
                ],
                "xp": 25,
                "lesson": "カ (ka) is katakana 'ka'. Example: カメラ (kamera) = 'camera'. Notice how the loanword adapts the English word.",
                "is_boss": False,
                "flavor": "Sensei draws カ with two sharp angular strokes.",
            },
            {
                "id": "kata_ki_ku_ke_ko",
                "title": "Ki, Ku, Ke, Ko",
                "type": "quiz",
                "question": "Which katakana is キ (ki)? (Romaji: ki)",
                "options": ["カ — two strokes, angular", "キ — horizontal strokes with a vertical", "ク — an angular curve", "ケ — tall with a side stroke"],
                "answer": "b",
                "hints": [
                    "キ looks similar to hiragana き but more angular.",
                    "Think of the 'ki' in キロ (kiro) = kilo.",
                ],
                "xp": 25,
                "lesson": "キ (ki), ク (ku), ケ (ke), コ (ko) complete the ka-row. Examples: キロ (kiro) = kilo, クラス (kurasu) = class.",
                "is_boss": False,
                "flavor": "Sensei writes the ka-row characters in quick succession.",
            },
            {
                "id": "kata_sa",
                "title": "サ — Sa",
                "type": "quiz",
                "question": "What is the reading of サ? (Romaji: sa)",
                "options": ["ka", "sa — as in 'saw'", "ta", "ha"],
                "answer": "b",
                "hints": [
                    "It's the katakana version of さ.",
                    "Think of サッカー (sakkaa) = soccer.",
                ],
                "xp": 25,
                "lesson": "サ (sa) is katakana 'sa'. Example: サッカー (sakkaa) = 'soccer'. The ッ (small tsu) doubles the consonant.",
                "is_boss": False,
                "flavor": "Sensei draws サ -- three clean strokes.",
            },
            {
                "id": "kata_shi_vs_tsu",
                "title": "シ vs ツ — The Trickiest Pair",
                "type": "quiz",
                "question": "シ (shi) and ツ (tsu) look very similar. How do you tell them apart? (Romaji: shi / tsu)",
                "options": ["シ has dots going ↗ upward-right, strokes lean LEFT; ツ has dots going ↘ downward-right, strokes lean RIGHT", "They are identical", "シ is bigger than ツ", "ツ has a circle, シ doesn't"],
                "answer": "a",
                "hints": [
                    "Look at the direction of the two small strokes (dots).",
                    "シ: dots go upward (like a smiley face). ツ: dots go to the right.",
                ],
                "xp": 35,
                "lesson": "シ (shi) vs ツ (tsu): In シ, the two small strokes point upward (↗) and the long stroke sweeps left. In ツ, the two strokes point right (→) and the long stroke sweeps down. Think: シ = smiley face, ツ = drops of rain.",
                "is_boss": False,
                "flavor": "Sensei draws both side by side -- this is THE classic katakana trap.",
            },
            {
                "id": "kata_su_se_so",
                "title": "Su, Se, So",
                "type": "quiz",
                "question": "Which katakana is ス (su)? (Romaji: su)",
                "options": ["サ — three strokes with a horizontal top", "ス — an angular stroke going down-right", "セ — looks like a stretched katakana", "ソ — two quick strokes"],
                "answer": "b",
                "hints": [
                    "ス looks like an angular swoosh.",
                    "Think of スーパー (suupaa) = supermarket.",
                ],
                "xp": 25,
                "lesson": "ス (su), セ (se), ソ (so) complete the sa-row. Examples: スーパー (suupaa) = supermarket, ソフト (sofuto) = soft(ware).",
                "is_boss": False,
                "flavor": "Sensei writes the remaining sa-row characters.",
            },
            {
                "id": "kata_so_vs_n",
                "title": "ソ vs ン — Another Tricky Pair",
                "type": "quiz",
                "question": "ソ (so) and ン (n) look similar. Which description helps tell them apart? (Romaji: so / n)",
                "options": ["ソ has steeper strokes going right; ン has a flatter first stroke going left", "They are the same character", "ソ is always at the end of words", "ン has three strokes, ソ has two"],
                "answer": "a",
                "hints": [
                    "Like シ vs ツ, it's about the angle and direction of the strokes.",
                    "ソ strokes point right/down; ン first stroke is flatter, sweeping left.",
                ],
                "xp": 30,
                "lesson": "ソ (so) vs ン (n): ソ has two strokes angled steeply to the right. ン has a flatter first stroke that sweeps from right to left. Context also helps -- ン never starts a word.",
                "is_boss": False,
                "flavor": "Sensei reveals the second notorious katakana look-alike pair.",
            },
            {
                "id": "ka_sa_boss",
                "title": "Ka-Sa Row Challenge",
                "type": "quiz",
                "question": "Read this katakana word: カラオケ (Romaji: karaoke). What is it?",
                "options": ["Karate", "Karaoke", "Calendar", "Chocolate"],
                "answer": "b",
                "hints": [
                    "カ(ka) + ラ(ra) + オ(o) + ケ(ke) = karaoke.",
                    "This is actually a Japanese word that English borrowed!",
                ],
                "xp": 35,
                "lesson": "カラオケ (karaoke) is actually a Japanese-origin word! カラ (kara) = empty + オケ (oke) = orchestra. 'Empty orchestra' -- singing without a live band. Japanese exports words too!",
                "is_boss": True,
                "flavor": "Sensei reveals that karaoke is originally Japanese -- a fun twist!",
            },
        ],
    },

    # ── Zone 3: Ta-row & Na-row ──────────────────────────────────────
    "ta_na_rows": {
        "id": "ta_na_rows",
        "name": "Ta-Row & Na-Row",
        "description": "Learn タチツテト (ta chi tsu te to) and ナニヌネノ (na ni nu ne no)",
        "level_required": 3,
        "challenges": [
            {
                "id": "kata_ta",
                "title": "タ — Ta",
                "type": "quiz",
                "question": "What sound does タ make? (Romaji: ta)",
                "options": ["ta — as in 'top'", "ka", "sa", "na"],
                "answer": "a",
                "hints": [
                    "It's the katakana version of た.",
                    "Think of タクシー (takushii) = taxi.",
                ],
                "xp": 25,
                "lesson": "タ (ta) is katakana 'ta'. Example: タクシー (takushii) = 'taxi'.",
                "is_boss": False,
                "flavor": "Sensei draws タ -- sharp and angular like all katakana.",
            },
            {
                "id": "kata_chi_tsu",
                "title": "チ and ツ — Irregulars",
                "type": "quiz",
                "question": "チ and ツ are irregular, just like in hiragana. Their readings are: (Romaji: chi, tsu)",
                "options": ["ti and tu", "chi and tsu", "shi and su", "ki and ku"],
                "answer": "b",
                "hints": [
                    "Same irregular readings as hiragana ち and つ.",
                    "チ = chi (like 'cheese'), ツ = tsu (like 'cats').",
                ],
                "xp": 30,
                "lesson": "チ (chi) and ツ (tsu) keep their irregular readings. Examples: チーズ (chiizu) = cheese, ツアー (tsuaa) = tour.",
                "is_boss": False,
                "flavor": "Sensei emphasizes the same irregulars from hiragana appear here.",
            },
            {
                "id": "kata_te_to",
                "title": "テ and ト",
                "type": "quiz",
                "question": "Read: テスト (Romaji: tesuto). What English word is this? (Romaji: te, to)",
                "options": ["Toast", "Test", "Text", "Taste"],
                "answer": "b",
                "hints": [
                    "テ(te) + ス(su) + ト(to) = tesuto.",
                    "A common word in schools everywhere.",
                ],
                "xp": 25,
                "lesson": "テ (te) and ト (to) are regular readings. テスト (tesuto) = 'test'. Notice how Japanese adds vowels to make English consonant clusters pronounceable.",
                "is_boss": False,
                "flavor": "Sensei writes テスト -- a word every Japanese student knows well.",
            },
            {
                "id": "kata_na_ni",
                "title": "ナ and ニ",
                "type": "quiz",
                "question": "Which katakana is ナ (na)? (Romaji: na)",
                "options": ["ナ — looks like a cross with an extra stroke", "ニ — two horizontal lines", "ヌ — a crossed stroke", "ネ — multiple strokes"],
                "answer": "a",
                "hints": [
                    "ナ looks somewhat like the English letters 'na'.",
                    "Think of ナイフ (naifu) = knife.",
                ],
                "xp": 25,
                "lesson": "ナ (na) and ニ (ni) start the na-row. ニ looks like the number 2 in horizontal strokes. Examples: ナイフ (naifu) = knife, ニュース (nyuusu) = news.",
                "is_boss": False,
                "flavor": "Sensei draws ナ and ニ side by side.",
            },
            {
                "id": "kata_nu_ne_no",
                "title": "ヌ, ネ, ノ",
                "type": "quiz",
                "question": "ノ (no) is one of the simplest katakana. How many strokes does it have? (Romaji: no)",
                "options": ["One — a single diagonal stroke", "Two", "Three", "Four"],
                "answer": "a",
                "hints": [
                    "ノ is literally just one diagonal line.",
                    "It looks like a slash: /",
                ],
                "xp": 25,
                "lesson": "ノ (no) is a single diagonal stroke -- the simplest katakana. ヌ (nu) and ネ (ne) are more complex. Example: ノート (nooto) = notebook.",
                "is_boss": False,
                "flavor": "Sensei draws ノ in one swift motion -- simplicity itself.",
            },
            {
                "id": "ta_na_boss",
                "title": "Ta-Na Reading Challenge",
                "type": "quiz",
                "question": "Read: チョコレート (Romaji: chokoreeto). What is it?",
                "options": ["Character", "Chocolate", "Chopsticks", "Champion"],
                "answer": "b",
                "hints": [
                    "チョ(cho) + コ(ko) + レー(ree) + ト(to).",
                    "A sweet treat loved worldwide.",
                ],
                "xp": 35,
                "lesson": "チョコレート (chokoreeto) = chocolate. Note: チョ is a combination character (chi + small yo = cho). The ー extends the 'e' vowel sound.",
                "is_boss": True,
                "flavor": "Sensei unwraps a piece of chocolate to celebrate your progress.",
            },
        ],
    },

    # ── Zone 4: Ha-row & Ma-row ──────────────────────────────────────
    "ha_ma_rows": {
        "id": "ha_ma_rows",
        "name": "Ha-Row & Ma-Row",
        "description": "Learn ハヒフヘホ (ha hi fu he ho) and マミムメモ (ma mi mu me mo)",
        "level_required": 4,
        "challenges": [
            {
                "id": "kata_ha",
                "title": "ハ — Ha",
                "type": "quiz",
                "question": "What sound does ハ make? (Romaji: ha)",
                "options": ["ha", "ba", "pa", "ka"],
                "answer": "a",
                "hints": [
                    "Same as hiragana は (when not a particle).",
                    "Think of ハンバーガー (hanbaagaa) = hamburger.",
                ],
                "xp": 25,
                "lesson": "ハ (ha) is katakana 'ha'. Example: ハンバーガー (hanbaagaa) = hamburger. With dakuten: バ (ba). With handakuten: パ (pa).",
                "is_boss": False,
                "flavor": "Sensei draws ハ -- two diverging strokes, like an open gate.",
            },
            {
                "id": "kata_hi_fu",
                "title": "ヒ and フ",
                "type": "quiz",
                "question": "フ (fu) appears in many loanwords. Read: フランス (Romaji: furansu). What country is this?",
                "options": ["Finland", "France", "Philippines", "Fiji"],
                "answer": "b",
                "hints": [
                    "フ(fu) + ラ(ra) + ン(n) + ス(su) = furansu.",
                    "A European country famous for food and fashion.",
                ],
                "xp": 25,
                "lesson": "ヒ (hi) and フ (fu) continue the ha-row. フランス (furansu) = France. Japanese adapts foreign country names into katakana.",
                "is_boss": False,
                "flavor": "Sensei draws フ -- a simple, elegant character.",
            },
            {
                "id": "kata_he_ho",
                "title": "ヘ and ホ",
                "type": "quiz",
                "question": "ヘ looks identical to the hiragana へ. How do you tell them apart? (Romaji: he)",
                "options": ["By context -- katakana is used for loanwords", "ヘ is bigger", "ヘ is always red", "You cannot tell them apart at all"],
                "answer": "a",
                "hints": [
                    "ヘ and へ look the same -- context tells you which script is being used.",
                    "If the surrounding characters are katakana, it's katakana ヘ.",
                ],
                "xp": 30,
                "lesson": "ヘ (he) and hiragana へ look identical -- context determines the reading. ホ (ho) = katakana 'ho'. Example: ホテル (hoteru) = hotel.",
                "is_boss": False,
                "flavor": "Sensei points out that ヘ is the one katakana identical to its hiragana form.",
            },
            {
                "id": "kata_ma_mi",
                "title": "マ and ミ",
                "type": "quiz",
                "question": "Read: マクドナルド (Romaji: makudonarudo). What is it?",
                "options": ["McDonald's", "Magazine", "Macaron", "Marathon"],
                "answer": "a",
                "hints": [
                    "マ(ma) + ク(ku) + ド(do) + ナ(na) + ル(ru) + ド(do).",
                    "A famous fast-food restaurant chain.",
                ],
                "xp": 25,
                "lesson": "マ (ma) and ミ (mi) begin the ma-row. マクドナルド (makudonarudo) = McDonald's. Japanese people often shorten it to マック (makku) or マクド (makudo).",
                "is_boss": False,
                "flavor": "Sensei chuckles -- even fast food gets the katakana treatment.",
            },
            {
                "id": "kata_mu_me_mo",
                "title": "ム, メ, モ",
                "type": "quiz",
                "question": "Which katakana is メ (me)? (Romaji: me)",
                "options": ["マ — angular with a horizontal top", "ミ — three horizontal strokes", "ム — angular with a point", "メ — an X-like crossing"],
                "answer": "d",
                "hints": [
                    "メ looks like a tilted X.",
                    "Think of メニュー (menyuu) = menu.",
                ],
                "xp": 25,
                "lesson": "ム (mu), メ (me), モ (mo) complete the ma-row. Examples: メニュー (menyuu) = menu, モデル (moderu) = model.",
                "is_boss": False,
                "flavor": "Sensei writes the final three ma-row characters.",
            },
            {
                "id": "ha_ma_boss",
                "title": "Ha-Ma Reading Challenge",
                "type": "quiz",
                "question": "Read: ハンバーガー (Romaji: hanbaagaa). What is it?",
                "options": ["Hamburg (city)", "Hamburger", "Handbag", "Hanger"],
                "answer": "b",
                "hints": [
                    "ハ(ha) + ン(n) + バ(ba) + ー(long) + ガ(ga) + ー(long).",
                    "A popular food at fast-food restaurants.",
                ],
                "xp": 35,
                "lesson": "ハンバーガー (hanbaagaa) = hamburger. Note: バ (ba) is ハ with dakuten, ガ (ga) is カ with dakuten. The ー marks extend the vowels.",
                "is_boss": True,
                "flavor": "Sensei quizzes you on one of Japan's favorite borrowed foods.",
            },
        ],
    },

    # ── Zone 5: Ya-row, Ra-row, Wa & N ──────────────────────────────
    "ya_ra_wa_n": {
        "id": "ya_ra_wa_n",
        "name": "Ya-Row, Ra-Row, Wa & N",
        "description": "Learn ヤユヨ, ラリルレロ, ワヲ, and ン",
        "level_required": 5,
        "challenges": [
            {
                "id": "kata_ya_yu_yo",
                "title": "ヤ, ユ, ヨ",
                "type": "quiz",
                "question": "The ya-row has only three katakana. Which are they? (Romaji: ya yu yo)",
                "options": ["ヤ (ya), ユ (yu), ヨ (yo)", "ヤ (ya), イ (yi), ヨ (yo)", "ヤ (ya), ユ (yu), ワ (wa)", "ラ (ra), ユ (yu), ヨ (yo)"],
                "answer": "a",
                "hints": [
                    "Same as hiragana -- only ya, yu, yo exist.",
                    "No 'yi' or 'ye' in modern Japanese.",
                ],
                "xp": 25,
                "lesson": "ヤ (ya), ユ (yu), ヨ (yo) are the katakana ya-row. Example: ユーチューブ (yuuchuubu) = YouTube.",
                "is_boss": False,
                "flavor": "Sensei writes the compact three-character ya-row.",
            },
            {
                "id": "kata_ra_ri",
                "title": "ラ and リ",
                "type": "quiz",
                "question": "Read: ラーメン (Romaji: raamen). What is this famous Japanese dish?",
                "options": ["Ramen noodles", "Lemon", "Salmon", "Rice ball"],
                "answer": "a",
                "hints": [
                    "ラ(ra) + ー(long vowel) + メ(me) + ン(n).",
                    "A beloved noodle soup from Japan.",
                ],
                "xp": 25,
                "lesson": "ラ (ra) and リ (ri) begin the ra-row. ラーメン (raamen) = ramen. Though now associated with Japan, ramen originally came from China.",
                "is_boss": False,
                "flavor": "Sensei draws ラ and リ -- the ra-row with its unique Japanese 'r' sound.",
            },
            {
                "id": "kata_ru_re_ro",
                "title": "ル, レ, ロ",
                "type": "quiz",
                "question": "Read: ホテル (Romaji: hoteru). What is it?",
                "options": ["Hotel", "Hostel", "House", "Hospital"],
                "answer": "a",
                "hints": [
                    "ホ(ho) + テ(te) + ル(ru) = hoteru.",
                    "A place where travelers sleep.",
                ],
                "xp": 25,
                "lesson": "ル (ru), レ (re), ロ (ro) complete the ra-row. ホテル (hoteru) = hotel. レストラン (resutoran) = restaurant.",
                "is_boss": False,
                "flavor": "Sensei writes the final three ra-row characters.",
            },
            {
                "id": "kata_wa_wo_n",
                "title": "ワ, ヲ, and ン",
                "type": "quiz",
                "question": "ン is the katakana version of ん. What makes it special? (Romaji: n)",
                "options": ["It's the only katakana that is a vowel", "It's the only katakana that is a standalone consonant", "It always starts words", "It's silent"],
                "answer": "b",
                "hints": [
                    "Just like hiragana ん, it's a consonant without a vowel.",
                    "It appears in many loanwords: ン at the end or middle.",
                ],
                "xp": 30,
                "lesson": "ワ (wa), ヲ (wo), and ン (n) complete the chart. ン is the standalone consonant, used heavily in loanwords. Example: パン (pan) = bread, ラーメン (raamen) = ramen.",
                "is_boss": False,
                "flavor": "Sensei draws the final characters of the katakana chart.",
            },
            {
                "id": "kata_full_chart",
                "title": "The Complete Chart",
                "type": "quiz",
                "question": "How many basic katakana characters are there?",
                "options": ["26", "46 — same as hiragana", "50", "72"],
                "answer": "b",
                "hints": [
                    "Katakana mirrors hiragana exactly in number.",
                    "Same 46 characters, different shapes.",
                ],
                "xp": 25,
                "lesson": "There are 46 basic katakana characters -- exactly the same count as hiragana. Together, hiragana and katakana are called 'kana'.",
                "is_boss": False,
                "flavor": "Sensei displays both complete charts -- hiragana and katakana, 46 each.",
            },
            {
                "id": "ya_ra_wa_n_boss",
                "title": "Full Chart Challenge",
                "type": "quiz",
                "question": "Read: アメリカ (Romaji: amerika). What country is this?",
                "options": ["America (USA)", "Africa", "Armenia", "Argentina"],
                "answer": "a",
                "hints": [
                    "ア(a) + メ(me) + リ(ri) + カ(ka) = amerika.",
                    "A large country in North America.",
                ],
                "xp": 35,
                "lesson": "アメリカ (amerika) = America/USA. Country names are written in katakana. Other examples: イギリス (igirisu) = England, フランス (furansu) = France.",
                "is_boss": True,
                "flavor": "Sensei tests your ability to decode country names in katakana.",
            },
        ],
    },

    # ── Zone 6: Long Vowels & Special Sounds ────────────────────────
    "long_vowels_special": {
        "id": "long_vowels_special",
        "name": "Long Vowels & Special Sounds",
        "description": "Master the ー mark, double consonants (ッ), and extended katakana",
        "level_required": 6,
        "challenges": [
            {
                "id": "kata_long_vowel",
                "title": "The Long Vowel Mark ー",
                "type": "quiz",
                "question": "In katakana, ー extends the previous vowel sound. What does コーヒー (koohii) mean? (Romaji: koohii)",
                "options": ["Cookie", "Coffee", "Copy", "Coin"],
                "answer": "b",
                "hints": [
                    "コ(ko) + ー(long o) + ヒ(hi) + ー(long i) = koohii.",
                    "A popular hot drink.",
                ],
                "xp": 25,
                "lesson": "The ー mark extends the previous vowel. コーヒー = koohii (coffee). In hiragana, long vowels use extra kana; in katakana, just add ー.",
                "is_boss": False,
                "flavor": "Sensei demonstrates the long vowel mark with Japan's favorite hot drink.",
            },
            {
                "id": "kata_double_consonant",
                "title": "ッ — The Double Consonant",
                "type": "quiz",
                "question": "A small ッ (small tsu) doubles the following consonant. How is ロッカー pronounced? (Romaji: rokkaa)",
                "options": ["rokaa (single k)", "rokkaa (double k, with a pause)", "rotukaa", "roshikaa"],
                "answer": "b",
                "hints": [
                    "ッ creates a brief pause before the next consonant, doubling it.",
                    "Think of how 'locker' has a 'ck' -- ロッカー does the same.",
                ],
                "xp": 30,
                "lesson": "ッ (small tsu) doubles the following consonant, creating a brief pause. ロッカー (rokkaa) = locker. サッカー (sakkaa) = soccer. ベッド (beddo) = bed.",
                "is_boss": False,
                "flavor": "Sensei explains the small ッ -- tiny but powerful.",
            },
            {
                "id": "kata_combo_sounds",
                "title": "Combination Sounds",
                "type": "quiz",
                "question": "Small ヤユヨ combine with other katakana. What sound does シャ make? (Romaji: sha)",
                "options": ["sa", "sha — like 'shadow'", "shiya", "sya"],
                "answer": "b",
                "hints": [
                    "シ (shi) + small ャ (ya) = シャ (sha).",
                    "The small ヤ modifies the previous character.",
                ],
                "xp": 30,
                "lesson": "Small ヤユヨ create combination sounds: シャ(sha) シュ(shu) ショ(sho), チャ(cha) チュ(chu) チョ(cho), etc. Example: シャワー (shawaa) = shower.",
                "is_boss": False,
                "flavor": "Sensei shows how small characters modify their neighbors.",
            },
            {
                "id": "kata_extended_fa",
                "title": "Extended Katakana — ファ, ティ, ヴ",
                "type": "quiz",
                "question": "Modern katakana can represent foreign sounds. ファ (fa) is used in loanwords. What is ファイル? (Romaji: fairu)",
                "options": ["File", "Fail", "Fire", "Fair"],
                "answer": "a",
                "hints": [
                    "ファ(fa) + イ(i) + ル(ru) = fairu.",
                    "A common computer/office term.",
                ],
                "xp": 30,
                "lesson": "Extended katakana represents sounds not native to Japanese: ファ(fa) フィ(fi) フェ(fe) フォ(fo), ティ(ti), ディ(di), ヴァ(va). Example: ファイル (fairu) = file.",
                "is_boss": False,
                "flavor": "Sensei reveals how katakana adapts to represent new sounds.",
            },
            {
                "id": "kata_small_vowels",
                "title": "Small Vowels",
                "type": "quiz",
                "question": "Small vowel characters (ァィゥェォ) appear in extended katakana. What does ウィキペディア (wikipedia) mean? (Romaji: wikipedia)",
                "options": ["Wikipedia", "Widget", "Window", "Wizard"],
                "answer": "a",
                "hints": [
                    "ウィ(wi) + キ(ki) + ペ(pe) + ディ(di) + ア(a) = wikipedia.",
                    "The free online encyclopedia.",
                ],
                "xp": 30,
                "lesson": "Small vowels create non-standard sounds: ウィ(wi), ウェ(we), ウォ(wo), ティ(ti), ディ(di). These let katakana more closely match foreign pronunciation.",
                "is_boss": False,
                "flavor": "Sensei shows the modern extensions that keep katakana evolving.",
            },
            {
                "id": "long_vowels_boss",
                "title": "Special Sounds Master",
                "type": "quiz",
                "question": "Read: コンピューター (Romaji: konpyuutaa). What is it?",
                "options": ["Competitor", "Computer", "Conductor", "Commuter"],
                "answer": "b",
                "hints": [
                    "コ(ko) + ン(n) + ピュー(pyuu) + ター(taa).",
                    "The device you might be using right now.",
                ],
                "xp": 35,
                "lesson": "コンピューター (konpyuutaa) = computer. This word uses: ン (standalone n), ピュ (combination sound), ー (long vowels), and ター (ta + long vowel). All special features combined!",
                "is_boss": True,
                "flavor": "Sensei presents the ultimate special-sounds challenge.",
            },
        ],
    },

    # ── Zone 7: Reading Loanwords ────────────────────────────────────
    "reading_loanwords": {
        "id": "reading_loanwords",
        "name": "Reading Loanwords",
        "description": "Decode real loanwords from English and other languages",
        "level_required": 7,
        "challenges": [
            {
                "id": "loan_terebi",
                "title": "Television",
                "type": "quiz",
                "question": "Read: テレビ (Romaji: terebi). What is it?",
                "options": ["Telephone", "Television / TV", "Terrible", "Territory"],
                "answer": "b",
                "hints": [
                    "テ(te) + レ(re) + ビ(bi) = terebi.",
                    "A device you watch shows on.",
                ],
                "xp": 25,
                "lesson": "テレビ (terebi) = television/TV. It's shortened from テレビジョン (terebijon). Japanese often shortens loanwords.",
                "is_boss": False,
                "flavor": "Sensei points to an imaginary TV screen.",
            },
            {
                "id": "loan_sumaatofon",
                "title": "Smartphone",
                "type": "quiz",
                "question": "Read: スマートフォン (Romaji: sumaatofon). What is it?",
                "options": ["Smart phone", "Smart phone case", "Small phone", "Satellite phone"],
                "answer": "a",
                "hints": [
                    "スマート(sumaato) + フォン(fon).",
                    "The device in almost everyone's pocket.",
                ],
                "xp": 25,
                "lesson": "スマートフォン (sumaatofon) = smartphone. Often shortened to スマホ (sumaho). Japanese loves abbreviating loanwords!",
                "is_boss": False,
                "flavor": "Sensei holds up a phone -- katakana is everywhere on the screen.",
            },
            {
                "id": "loan_aisu_kuriimu",
                "title": "A Sweet Treat",
                "type": "quiz",
                "question": "Read: アイスクリーム (Romaji: aisukuriimu). What is it?",
                "options": ["Ice cream", "Iced coffee", "Ice skating", "Icing sugar"],
                "answer": "a",
                "hints": [
                    "アイス(aisu) + クリーム(kuriimu).",
                    "A frozen dessert everyone loves.",
                ],
                "xp": 25,
                "lesson": "アイスクリーム (aisukuriimu) = ice cream. Often shortened to アイス (aisu). Japanese food menus are full of katakana!",
                "is_boss": False,
                "flavor": "Sensei smiles at this delicious vocabulary word.",
            },
            {
                "id": "loan_non_english",
                "title": "Not Just English",
                "type": "quiz",
                "question": "Read: パン (Romaji: pan). This loanword comes from Portuguese, not English. What does it mean?",
                "options": ["Pan (cooking)", "Bread", "Pants", "Panda"],
                "answer": "b",
                "hints": [
                    "Portuguese 'pao' became パン in Japanese.",
                    "Japan borrowed this word centuries ago from Portuguese traders.",
                ],
                "xp": 30,
                "lesson": "パン (pan) = bread, from Portuguese 'pao'. Not all loanwords come from English! アルバイト (arubaito) = part-time job, from German 'Arbeit'.",
                "is_boss": False,
                "flavor": "Sensei reveals that Japan has borrowed words from many languages.",
            },
            {
                "id": "loan_mixed_reading",
                "title": "Menu Reading",
                "type": "quiz",
                "question": "Read this restaurant menu item: サラダ (Romaji: sarada). What is it?",
                "options": ["Sardine", "Salad", "Salmon", "Sandwich"],
                "answer": "b",
                "hints": [
                    "サ(sa) + ラ(ra) + ダ(da) = sarada.",
                    "A healthy dish of vegetables.",
                ],
                "xp": 25,
                "lesson": "サラダ (sarada) = salad. Other menu items: サンドイッチ (sandoicchi) = sandwich, ピザ (piza) = pizza, ステーキ (suteeki) = steak.",
                "is_boss": False,
                "flavor": "Sensei quizzes you with a restaurant menu.",
            },
            {
                "id": "loanwords_boss",
                "title": "Loanword Master",
                "type": "quiz",
                "question": "Read: インターネット (Romaji: intaanetto). What is it?",
                "options": ["International", "Internet", "Interview", "Interest"],
                "answer": "b",
                "hints": [
                    "イン(in) + ター(taa) + ネッ(ne+double) + ト(to).",
                    "The global network connecting computers.",
                ],
                "xp": 35,
                "lesson": "インターネット (intaanetto) = internet. This word uses many katakana features: ン, ー, ッ. You can now decode katakana loanwords in the real world!",
                "is_boss": True,
                "flavor": "Sensei bows -- you have mastered the art of reading katakana loanwords.",
            },
        ],
    },
}
