"""
zones.py — School & Education zones and challenges.

5 zones × 8 challenges = 40 total.
Mix of quiz and text types. Guided by 龙龙 (Lóng Lóng).
"""

ZONE_ORDER = [
    "school_subjects",
    "classroom_objects",
    "school_actions",
    "talking_about_school",
    "school_life",
]

ZONES = {
    "school_subjects": {
        "id": "school_subjects",
        "name": "The Scholar's Subjects",
        "description": "Learn the names of school subjects in Chinese",
        "level_required": 1,
        "challenges": [
            {
                "id": "subject_math",
                "title": "The Language of Numbers",
                "type": "quiz",
                "question": "数学 (shùxué) means...?",
                "options": ["Science", "Mathematics", "History", "English"],
                "answer": "b",
                "hints": [
                    "数 means 'number' and 学 means 'study/learning.'",
                    "Literally: 'the study of numbers.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "数学 (shùxué) = mathematics. 数 = number/count, 学 = study. The 学 character appears in many subject names — it means 'the study of' something. 我喜欢数学 = 'I like math.'",
                "is_boss": False,
                "flavor": "龙龙 scratches equations into the stone floor with a claw.",
            },
            {
                "id": "subject_english",
                "title": "The Foreign Tongue",
                "type": "quiz",
                "question": "英语 (Yīngyǔ) means 'English.' What does 语 (yǔ) mean?",
                "options": ["Country", "Language", "People", "Writing"],
                "answer": "b",
                "hints": [
                    "语 appears in 中文/汉语 (Chinese) and 法语 (French) too.",
                    "It's the character for 'language' or 'speech.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "英语 (Yīngyǔ) = English. 语 = language. Other languages follow the same pattern: 法语 (French), 日语 (Japanese), 中文/汉语 (Chinese). 英 originally referred to England.",
                "is_boss": False,
                "flavor": "龙龙 attempts to say 'hello' in a posh English accent.",
            },
            {
                "id": "subject_science",
                "title": "Secrets of Nature",
                "type": "quiz",
                "question": "科学 (kēxué) means...?",
                "options": ["History", "Geography", "Science", "Art"],
                "answer": "c",
                "hints": [
                    "科 means 'branch of study' and 学 means 'learning.'",
                    "This is the broadest academic term for 'science.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "科学 (kēxué) = science. 科 = branch/subject, 学 = study. Related: 科学家 (kēxuéjiā) = scientist (add 家 = 'expert/specialist'). 科学很有趣 = 'Science is interesting.'",
                "is_boss": False,
                "flavor": "龙龙 breathes a careful flame to demonstrate combustion.",
            },
            {
                "id": "subject_history",
                "title": "Tales of the Past",
                "type": "quiz",
                "question": "历史 (lìshǐ) means...?",
                "options": ["Mathematics", "Geography", "Literature", "History"],
                "answer": "d",
                "hints": [
                    "历 means 'to experience/pass through' and 史 means 'history/records.'",
                    "Think of it as 'the record of what has passed.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "历史 (lìshǐ) = history. 史 alone means 'history' and appears in 历史学家 (historian). Chinese history spans over 5,000 years — 中国历史 (Zhōngguó lìshǐ) is one of the longest in the world!",
                "is_boss": False,
                "flavor": "龙龙 unrolls an ancient scroll and blows dust off it dramatically.",
            },
            {
                "id": "subject_pe",
                "title": "Move Your Body",
                "type": "quiz",
                "question": "体育 (tǐyù) means...?",
                "options": ["Music", "Art", "Physical education / PE", "Biology"],
                "answer": "c",
                "hints": [
                    "体 means 'body' and 育 means 'to nurture/educate.'",
                    "Literally: 'body education' — i.e., physical education.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "体育 (tǐyù) = physical education / PE / sports. 体 = body, 育 = nurture. 体育课 (tǐyù kè) = PE class. 体育老师 (tǐyù lǎoshī) = PE teacher. Many students say 我最喜欢体育课!",
                "is_boss": False,
                "flavor": "龙龙 attempts a push-up but its wings get in the way.",
            },
            {
                "id": "subject_pattern",
                "title": "The 学 Pattern",
                "type": "text",
                "question": "Notice how 学 (xué) appears in 数学, 科学, 化学 (chemistry), 文学 (literature). What does 学 tell you about a word?",
                "options": ["It's a place", "It's the study/science of something", "It's a person", "It's an action"],
                "answer": "b",
                "hints": [
                    "学 means 'to study' or 'the study of.'",
                    "When attached to another character, it creates a subject name.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "学 (xué) = study/learning. It turns any topic into an academic subject: 数学 (math), 科学 (science), 化学 (chemistry), 文学 (literature), 医学 (medicine). Recognizing 学 instantly tells you 'this is a field of study.'",
                "is_boss": False,
                "flavor": "龙龙 writes 学 in the air with a glowing claw. 'One character, endless knowledge!'",
            },
            {
                "id": "subject_favorite",
                "title": "What's Your Favorite?",
                "type": "quiz",
                "question": "你最喜欢什么课? (Nǐ zuì xǐhuan shénme kè?) means...?",
                "options": [
                    "What class do you have today?",
                    "What is your favorite subject?",
                    "Do you like school?",
                    "What time is class?",
                ],
                "answer": "b",
                "hints": [
                    "最喜欢 = most like = favorite.",
                    "什么课 = what class/subject.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "你最喜欢什么课? = What is your favorite subject? 最 (zuì) = most, 喜欢 (xǐhuan) = like, 课 (kè) = class/subject. Answer with: 我最喜欢___课 = 'My favorite subject is ___.'",
                "is_boss": False,
                "flavor": "龙龙 grins. 'My favorite? 火术课 — Fire-breathing class, of course!'",
            },
            {
                "id": "subject_boss",
                "title": "Subject Master",
                "type": "quiz",
                "question": "Match them all: 数学, 英语, 科学, 历史, 体育. Which list is correct?",
                "options": [
                    "Math, English, Science, History, PE",
                    "Science, English, Math, PE, History",
                    "English, Math, History, Science, PE",
                    "Math, Science, English, PE, History",
                ],
                "answer": "a",
                "hints": [
                    "Go in order: 数 = numbers, 英 = England, 科 = branch, 历 = past, 体 = body.",
                    "数学 starts with 'number,' so it's math.",
                ],
                "xp": 50,
                "difficulty": "hard",
                "lesson": "Full review: 数学 (math), 英语 (English), 科学 (science), 历史 (history), 体育 (PE). These five subjects cover most school schedules. You now know them all in Chinese!",
                "is_boss": True,
                "flavor": "龙龙 holds up a scroll listing every subject. 'A true scholar knows them all!'",
            },
        ],
    },
    "classroom_objects": {
        "id": "classroom_objects",
        "name": "The Enchanted Classroom",
        "description": "Learn the names of everyday classroom objects",
        "level_required": 3,
        "challenges": [
            {
                "id": "object_book",
                "title": "The Written Word",
                "type": "quiz",
                "question": "书 (shū) means...?",
                "options": ["Pen", "Book", "Paper", "Desk"],
                "answer": "b",
                "hints": [
                    "书 is one of the most common characters in Chinese.",
                    "图书馆 (library) contains 书 — a place full of these!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "书 (shū) = book. One of the first characters every student learns. Related words: 书包 (shūbāo) = schoolbag (book + bag), 图书馆 (túshūguǎn) = library, 书店 (shūdiàn) = bookshop. 我的书在哪儿? = 'Where is my book?'",
                "is_boss": False,
                "flavor": "龙龙 cradles a leather-bound tome. 'In my hoard, books are worth more than gold!'",
            },
            {
                "id": "object_pen",
                "title": "Mightier Than the Sword",
                "type": "quiz",
                "question": "笔 (bǐ) means...?",
                "options": ["Ruler", "Eraser", "Pen / writing instrument", "Pencil case"],
                "answer": "c",
                "hints": [
                    "The top part 竹 is the bamboo radical — ancient pens were bamboo.",
                    "铅笔 (pencil) and 毛笔 (brush pen) both end with 笔.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "笔 (bǐ) = pen / writing instrument. The 竹 radical on top tells you it was originally bamboo. Types: 铅笔 (qiānbǐ) = pencil, 毛笔 (máobǐ) = calligraphy brush, 钢笔 (gāngbǐ) = fountain pen. 你有笔吗? = 'Do you have a pen?'",
                "is_boss": False,
                "flavor": "龙龙 dips a claw in ink and writes a perfect character.",
            },
            {
                "id": "object_notebook",
                "title": "Pages of Potential",
                "type": "quiz",
                "question": "本子 (běnzi) means...?",
                "options": ["Textbook", "Notebook / exercise book", "Dictionary", "Folder"],
                "answer": "b",
                "hints": [
                    "本 means 'root/origin' but also serves as a measure word for books.",
                    "本子 is the small notebook students write in every day.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "本子 (běnzi) = notebook / exercise book. 本 can mean 'root' or 'origin' and is also the measure word for books (一本书 = one book). 笔记本 (bǐjìběn) = notebook (note-record-book). 作业本 = homework book.",
                "is_boss": False,
                "flavor": "龙龙 flips through a notebook filled with tiny dragon doodles.",
            },
            {
                "id": "object_computer",
                "title": "The Electric Brain",
                "type": "text",
                "question": "电脑 (diànnǎo) literally means 'electric brain.' What is it?",
                "options": ["Television", "Computer", "Robot", "Calculator"],
                "answer": "b",
                "hints": [
                    "电 = electric/electricity, 脑 = brain.",
                    "Think about what modern device acts like an 'electric brain.'",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "电脑 (diànnǎo) = computer. Literally 'electric brain' — one of the most poetic Chinese words! Related 电 words: 电话 (phone = electric speech), 电视 (TV = electric vision), 电影 (movie = electric shadow). Chinese word-building is beautiful!",
                "is_boss": False,
                "flavor": "龙龙 taps at a keyboard with its claws, accidentally typing 'rrrrrr.'",
            },
            {
                "id": "object_blackboard",
                "title": "The Dark Canvas",
                "type": "quiz",
                "question": "黑板 (hēibǎn) literally means 'black board.' What is it?",
                "options": ["Desk", "Blackboard / chalkboard", "Bookshelf", "Window"],
                "answer": "b",
                "hints": [
                    "黑 = black, 板 = board/plank.",
                    "It's exactly what it sounds like!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "黑板 (hēibǎn) = blackboard / chalkboard. 黑 = black, 板 = board. Chinese compound words are often delightfully literal. The teacher writes on the 黑板 with 粉笔 (fěnbǐ) = chalk (powder-pen). 看黑板! = 'Look at the blackboard!'",
                "is_boss": False,
                "flavor": "龙龙 writes '龙' on the blackboard with a flourish of chalk.",
            },
            {
                "id": "object_electric_pattern",
                "title": "The Electric Family",
                "type": "text",
                "question": "电脑 (computer), 电话 (phone), 电视 (TV), 电影 (movie). What does the 电 pattern tell you?",
                "options": [
                    "These are all old inventions",
                    "These all use electricity",
                    "These are all toys",
                    "These are all at school",
                ],
                "answer": "b",
                "hints": [
                    "电 means 'electricity' or 'electric.'",
                    "Each word pairs 电 with something poetic.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The 电 (diàn) family: 电脑 (computer = electric brain), 电话 (phone = electric speech), 电视 (TV = electric vision), 电影 (movie = electric shadow). Chinese builds modern tech words from ancient characters!",
                "is_boss": False,
                "flavor": "龙龙 sparks electricity between its horns. 'I was the original 电 source!'",
            },
            {
                "id": "object_schoolbag",
                "title": "Pack Your Bag",
                "type": "quiz",
                "question": "书包 (shūbāo) means 'schoolbag.' What two things make up the word?",
                "options": [
                    "Book + bag",
                    "School + pack",
                    "Study + box",
                    "Paper + pouch",
                ],
                "answer": "a",
                "hints": [
                    "书 = book (you just learned this!), 包 = bag/package.",
                    "A bag for carrying books = schoolbag.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "书包 (shūbāo) = schoolbag. 书 = book, 包 = bag. Simple and logical! 包 appears in other bag words too: 钱包 (wallet = money bag), 背包 (backpack = back bag). 你的书包里有什么? = 'What's in your schoolbag?'",
                "is_boss": False,
                "flavor": "龙龙 opens a comically oversized schoolbag full of scrolls and gemstones.",
            },
            {
                "id": "object_boss",
                "title": "Classroom Inspector",
                "type": "quiz",
                "question": "Your teacher says: 请打开书，拿出笔和本子。What should you do?",
                "options": [
                    "Open your book, take out pen and notebook",
                    "Close your book and put away your pen",
                    "Turn on the computer and sit down",
                    "Look at the blackboard and listen",
                ],
                "answer": "a",
                "hints": [
                    "打开 = open, 拿出 = take out.",
                    "书 = book, 笔 = pen, 本子 = notebook — all words you've learned!",
                ],
                "xp": 50,
                "difficulty": "hard",
                "lesson": "请打开书，拿出笔和本子 = Please open your book, take out your pen and notebook. 打开 (dǎkāi) = open, 拿出 (náchū) = take out. This is a sentence you'll hear in every Chinese classroom!",
                "is_boss": True,
                "flavor": "龙龙 plays teacher, wearing tiny spectacles. 'Classroom inspection time!'",
            },
        ],
    },
    "school_actions": {
        "id": "school_actions",
        "name": "The Daily Grind",
        "description": "Learn the actions that fill a school day",
        "level_required": 5,
        "challenges": [
            {
                "id": "action_study",
                "title": "The Core Mission",
                "type": "quiz",
                "question": "学习 (xuéxí) means...?",
                "options": ["To teach", "To study / to learn", "To read", "To write"],
                "answer": "b",
                "hints": [
                    "学 = to learn, 习 = to practice/review.",
                    "Together: learn + practice = study.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "学习 (xuéxí) = to study / to learn. 学 = learn, 习 = practice. Chinese sees studying as both learning AND practicing — wisdom baked into the word! 好好学习，天天向上 = 'Study hard, improve every day' (a famous motto).",
                "is_boss": False,
                "flavor": "龙龙 opens a massive textbook. 'A dragon never stops learning!'",
            },
            {
                "id": "action_exam",
                "title": "The Ultimate Test",
                "type": "quiz",
                "question": "考试 (kǎoshì) means...?",
                "options": ["Homework", "Exam / test", "Class", "Grade"],
                "answer": "b",
                "hints": [
                    "考 = to test/examine, 试 = to try/attempt.",
                    "The dreaded word every student knows!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "考试 (kǎoshì) = exam / test. 考 = to test, 试 = to try. Related: 考试成绩 (kǎoshì chéngjì) = test score, 期中考试 (qīzhōng kǎoshì) = midterm, 期末考试 (qīmò kǎoshì) = final exam. 明天有考试! = 'There's an exam tomorrow!'",
                "is_boss": False,
                "flavor": "龙龙 shudders. 'Even dragons fear the final exam!'",
            },
            {
                "id": "action_homework",
                "title": "The Nightly Ritual",
                "type": "quiz",
                "question": "做作业 (zuò zuòyè) means...?",
                "options": ["Take a test", "Do homework", "Go to class", "Read a book"],
                "answer": "b",
                "hints": [
                    "做 = to do/make, 作业 = homework/assignment.",
                    "做作业 is what students do every evening!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "做作业 (zuò zuòyè) = do homework. 做 = to do, 作业 = homework/assignment. 写作业 (xiě zuòyè) also works (write homework). 你做完作业了吗? = 'Have you finished your homework?' — every parent's favorite question!",
                "is_boss": False,
                "flavor": "龙龙 groans. 'I have three scrolls of homework to finish tonight...'",
            },
            {
                "id": "action_attend_class",
                "title": "Class Begins",
                "type": "quiz",
                "question": "上课 (shàngkè) means...?",
                "options": ["Skip class", "Attend class / class starts", "After class", "Study hall"],
                "answer": "b",
                "hints": [
                    "上 = up/go to, 课 = class/lesson.",
                    "上课 marks when a lesson begins.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "上课 (shàngkè) = attend class / class starts. 上 = up/begin, 课 = class. The 上/下 pattern is huge in Chinese: 上课 (class starts) ↔ 下课 (class ends), 上班 (start work) ↔ 下班 (finish work). Master this pattern!",
                "is_boss": False,
                "flavor": "A bell rings through the castle. 龙龙 says, '上课了! Class is starting!'",
            },
            {
                "id": "action_end_class",
                "title": "Freedom Rings",
                "type": "quiz",
                "question": "下课 (xiàkè) means...?",
                "options": ["Class starts", "Class ends / after class", "Homework time", "Recess"],
                "answer": "b",
                "hints": [
                    "下 = down/end, the opposite of 上.",
                    "If 上课 starts class, 下课 must...?",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "下课 (xiàkè) = class ends / class dismissed. 下 = down/end. The 上/下 pair: 上课/下课 (class starts/ends), 上学/放学 (go to school/leave school), 上车/下车 (get on/off a vehicle). One pattern, endless uses!",
                "is_boss": False,
                "flavor": "龙龙 leaps into the air. 'The sweetest words in any language: 下课了!'",
            },
            {
                "id": "action_up_down_pattern",
                "title": "The Up-Down Pattern",
                "type": "text",
                "question": "上课/下课, 上班/下班, 上车/下车. The 上/下 pattern means...?",
                "options": [
                    "Big / small",
                    "Begin / end (or get on / get off)",
                    "Good / bad",
                    "Fast / slow",
                ],
                "answer": "b",
                "hints": [
                    "上 = up, begin, get on. 下 = down, end, get off.",
                    "This is one of the most useful patterns in Chinese!",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "The 上/下 (shàng/xià) pattern is one of Chinese's most powerful: 上 = begin/get on, 下 = end/get off. 上课↔下课, 上班↔下班, 上车↔下车, 上网 (go online). Once you know this pattern, you unlock dozens of phrases!",
                "is_boss": False,
                "flavor": "龙龙 draws 上 and 下 in the air, arrows pointing up and down.",
            },
            {
                "id": "action_schedule",
                "title": "A Full Day",
                "type": "quiz",
                "question": "A student says: 我先上课，然后做作业，最后复习考试。What's the order?",
                "options": [
                    "Homework → class → review",
                    "Class → homework → review for exam",
                    "Exam → class → homework",
                    "Review → homework → class",
                ],
                "answer": "b",
                "hints": [
                    "先 = first, 然后 = then, 最后 = finally.",
                    "上课 = attend class, 做作业 = do homework, 复习考试 = review for exam.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "先...然后...最后... = first...then...finally... A great way to describe sequences. 复习 (fùxí) = to review. 复习考试 = review/study for an exam. This sentence structure is used constantly in daily Chinese!",
                "is_boss": False,
                "flavor": "龙龙 checks off a to-do list carved into stone tablets.",
            },
            {
                "id": "action_boss",
                "title": "The School Day Gauntlet",
                "type": "quiz",
                "question": "Put the school day in order: 上课 → ___ → 下课 → ___ → 考试",
                "options": [
                    "学习, 做作业",
                    "做作业, 学习",
                    "下课, 上课",
                    "考试, 学习",
                ],
                "answer": "a",
                "hints": [
                    "During class you 学习 (study), after class you 做作业 (do homework).",
                    "The logical flow: attend → study → dismiss → homework → test.",
                ],
                "xp": 50,
                "difficulty": "hard",
                "lesson": "The school day flow: 上课 (class starts) → 学习 (study) → 下课 (class ends) → 做作业 (do homework) → 考试 (take the exam). You now know every key action in a Chinese school day!",
                "is_boss": True,
                "flavor": "龙龙 rings a massive bell. 'From first bell to final exam — you know it all!'",
            },
        ],
    },
    "talking_about_school": {
        "id": "talking_about_school",
        "name": "Scholars' Conversations",
        "description": "Learn to talk about school, preferences, and difficulty",
        "level_required": 7,
        "challenges": [
            {
                "id": "talk_what_study",
                "title": "What Do You Study?",
                "type": "quiz",
                "question": "你学什么? (Nǐ xué shénme?) means...?",
                "options": [
                    "Where do you study?",
                    "What do you study?",
                    "When do you study?",
                    "How do you study?",
                ],
                "answer": "b",
                "hints": [
                    "你 = you, 学 = study, 什么 = what.",
                    "什么 (shénme) is the question word for 'what.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "你学什么? (Nǐ xué shénme?) = What do you study? 什么 = what. Answer: 我学___ = 'I study ___.' For example: 我学中文 = 'I study Chinese.' Simple and direct!",
                "is_boss": False,
                "flavor": "龙龙 peers over your shoulder curiously. 'So, what ARE you studying?'",
            },
            {
                "id": "talk_favorite",
                "title": "My Favorite!",
                "type": "quiz",
                "question": "我最喜欢数学 (Wǒ zuì xǐhuan shùxué) means...?",
                "options": [
                    "I hate math",
                    "I study math",
                    "My favorite is math",
                    "Math is hard",
                ],
                "answer": "c",
                "hints": [
                    "最 = most, 喜欢 = like. 最喜欢 = like the most = favorite.",
                    "我 = I, 数学 = math.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "我最喜欢___ = My favorite is ___ / I like ___ the most. 最 (zuì) = most. You can use this pattern for anything: 我最喜欢吃饺子 (I love dumplings the most), 我最喜欢蓝色 (My favorite color is blue).",
                "is_boss": False,
                "flavor": "龙龙 strikes a dramatic pose. 'My favorite? 飞行课 — Flying class!'",
            },
            {
                "id": "talk_difficult",
                "title": "That's Hard!",
                "type": "quiz",
                "question": "难 (nán) means...?",
                "options": ["Easy", "Difficult / hard", "Fun", "Boring"],
                "answer": "b",
                "hints": [
                    "Every student has said this about at least one subject!",
                    "The opposite of 容易 (easy).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "难 (nán) = difficult / hard. 很难 = very difficult. 数学很难 = 'Math is very hard.' The opposite is 容易 (róngyì) = easy. 太难了! = 'That's too hard!' — a phrase every student uses!",
                "is_boss": False,
                "flavor": "龙龙 scratches its head over a puzzle. '这个太难了!'",
            },
            {
                "id": "talk_easy",
                "title": "Piece of Cake",
                "type": "quiz",
                "question": "容易 (róngyì) means...?",
                "options": ["Difficult", "Interesting", "Easy", "Important"],
                "answer": "c",
                "hints": [
                    "It's the opposite of 难 (nán).",
                    "Two characters that together mean 'easy.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "容易 (róngyì) = easy. 很容易 = very easy. 英语很容易 = 'English is very easy.' Pair with 难: 数学难，体育容易 = 'Math is hard, PE is easy.' 简单 (jiǎndān) is a synonym meaning 'simple.'",
                "is_boss": False,
                "flavor": "龙龙 yawns. 'Fire-breathing? 很容易! Algebra? 很难!'",
            },
            {
                "id": "talk_interesting",
                "title": "How Interesting!",
                "type": "text",
                "question": "有意思 (yǒu yìsi) literally means 'has meaning.' What does it actually mean?",
                "options": ["Boring", "Meaningful", "Interesting / fun", "Confusing"],
                "answer": "c",
                "hints": [
                    "有 = have, 意思 = meaning. But as a phrase it means something more!",
                    "Used when something catches your interest or amuses you.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "有意思 (yǒu yìsi) = interesting / fun. Literally 'has meaning' but used like 'interesting.' 没有意思 or 没意思 = boring (no meaning). 历史课很有意思 = 'History class is really interesting.' 意思 alone means 'meaning.'",
                "is_boss": False,
                "flavor": "龙龙's eyes light up. 'Chinese characters? 很有意思!'",
            },
            {
                "id": "talk_not_like",
                "title": "Not a Fan",
                "type": "quiz",
                "question": "我不喜欢考试 (Wǒ bù xǐhuan kǎoshì) means...?",
                "options": [
                    "I like exams",
                    "I don't like exams",
                    "I passed the exam",
                    "I failed the exam",
                ],
                "answer": "b",
                "hints": [
                    "不 (bù) = not — it negates the verb.",
                    "不喜欢 = don't like.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "不 (bù) negates verbs: 不喜欢 = don't like, 不难 = not hard, 不容易 = not easy. 我不喜欢考试 = 'I don't like exams.' Combine with what you know: 我不喜欢数学，因为很难 = 'I don't like math because it's hard.'",
                "is_boss": False,
                "flavor": "龙龙 crosses its arms. '我不喜欢早起! I don't like waking up early!'",
            },
            {
                "id": "talk_because",
                "title": "Give a Reason",
                "type": "quiz",
                "question": "我喜欢体育课，因为很有意思。What does 因为 (yīnwèi) mean?",
                "options": ["But", "Because", "Although", "So"],
                "answer": "b",
                "hints": [
                    "因 = cause/reason, 为 = for/because of.",
                    "因为 connects a statement to its reason.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "因为 (yīnwèi) = because. 我喜欢体育课，因为很有意思 = 'I like PE because it's interesting.' Pattern: statement + 因为 + reason. 因为...所以... = 'Because...therefore...' is also very common.",
                "is_boss": False,
                "flavor": "龙龙 nods sagely. 'Every opinion deserves a 因为!'",
            },
            {
                "id": "talk_boss",
                "title": "The Opinion Master",
                "type": "quiz",
                "question": "Translate: 我最喜欢科学课，因为很有意思，不太难。",
                "options": [
                    "I like science the most because it's interesting and not too hard.",
                    "Science is my worst subject because it's hard.",
                    "I don't like science because it's boring.",
                    "Science is easy but not interesting.",
                ],
                "answer": "a",
                "hints": [
                    "最喜欢 = like the most, 因为 = because, 有意思 = interesting.",
                    "不太难 = not too difficult. 太 = too.",
                ],
                "xp": 50,
                "difficulty": "hard",
                "lesson": "Full sentence breakdown: 我 (I) 最喜欢 (like most) 科学课 (science class), 因为 (because) 很有意思 (very interesting), 不太难 (not too hard). You can now give opinions about school subjects with reasons — a real conversation!",
                "is_boss": True,
                "flavor": "龙龙 applauds. 'A full opinion in Chinese! You're a true scholar now!'",
            },
        ],
    },
    "school_life": {
        "id": "school_life",
        "name": "Castle Academy Life",
        "description": "Learn about the people and places of school life",
        "level_required": 9,
        "challenges": [
            {
                "id": "life_classmate",
                "title": "Fellow Scholars",
                "type": "quiz",
                "question": "同学 (tóngxué) means...?",
                "options": ["Teacher", "Classmate / schoolmate", "Friend", "Parent"],
                "answer": "b",
                "hints": [
                    "同 = same, 学 = study. Someone who studies with you.",
                    "同 means 'same/together' — you share the same classes.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "同学 (tóngxué) = classmate / schoolmate. 同 = same, 学 = study. Literally 'same-study.' The 同 pattern: 同事 (tóngshì) = colleague (same work), 同学 = classmate (same study). 他是我的同学 = 'He is my classmate.'",
                "is_boss": False,
                "flavor": "龙龙 gestures to a group of young dragons. 'My 同学 from dragon academy!'",
            },
            {
                "id": "life_teacher",
                "title": "The Master",
                "type": "quiz",
                "question": "老师 (lǎoshī) means...?",
                "options": ["Student", "Principal", "Teacher", "Professor"],
                "answer": "c",
                "hints": [
                    "老 can mean 'old' or 'respected' and 师 means 'master/teacher.'",
                    "老师 is how students address their teachers in China.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "老师 (lǎoshī) = teacher. 老 = old/respected, 师 = master. In Chinese culture, teachers are deeply respected — 一日为师，终身为父 = 'One day as your teacher, a lifetime as your father.' Students call out '老师好!' (Hello, teacher!) at the start of every class.",
                "is_boss": False,
                "flavor": "龙龙 bows respectfully. 'In the dragon world, 老师 is the highest honor.'",
            },
            {
                "id": "life_library",
                "title": "The Great Library",
                "type": "quiz",
                "question": "图书馆 (túshūguǎn) means...?",
                "options": ["Bookshop", "Library", "Museum", "Classroom"],
                "answer": "b",
                "hints": [
                    "图书 = books/library books, 馆 = building/hall.",
                    "You already know 书 = book!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "图书馆 (túshūguǎn) = library. 图书 = books, 馆 = hall/building. The 馆 character appears in many places: 博物馆 (museum), 体育馆 (gym/stadium), 餐馆 (restaurant). 我在图书馆学习 = 'I study at the library.'",
                "is_boss": False,
                "flavor": "龙龙 gazes in wonder at towering shelves of books. 'Paradise!'",
            },
            {
                "id": "life_cafeteria",
                "title": "The Feast Hall",
                "type": "quiz",
                "question": "食堂 (shítáng) means...?",
                "options": ["Kitchen", "Cafeteria / dining hall", "Convenience store", "Food court"],
                "answer": "b",
                "hints": [
                    "食 = food/eat, 堂 = hall.",
                    "The place in school where everyone eats together.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "食堂 (shítáng) = cafeteria / dining hall. 食 = food, 堂 = hall. 学校食堂 = school cafeteria. In China, school cafeterias serve hot meals: rice, stir-fry, soup. 食堂的饭很便宜 = 'Cafeteria food is very cheap.'",
                "is_boss": False,
                "flavor": "龙龙 sniffs the air. 'The castle 食堂 serves roasted mutton today!'",
            },
            {
                "id": "life_playground",
                "title": "The Training Grounds",
                "type": "text",
                "question": "操场 (cāochǎng) means 'playground / sports field.' 操 means 'exercise' and 场 means...?",
                "options": ["House", "Field / ground", "Game", "Ball"],
                "answer": "b",
                "hints": [
                    "场 appears in 机场 (airport = machine field) too.",
                    "It's an open area or ground for activities.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "操场 (cāochǎng) = playground / sports field. 操 = exercise, 场 = field/ground. The 场 pattern: 操场 (sports field), 机场 (airport), 广场 (plaza/square), 停车场 (parking lot). 同学们在操场上跑步 = 'Students run on the sports field.'",
                "is_boss": False,
                "flavor": "龙龙 does laps around the training grounds, wings tucked in.",
            },
            {
                "id": "life_guan_pattern",
                "title": "The 馆 Family",
                "type": "text",
                "question": "图书馆 (library), 博物馆 (museum), 体育馆 (gym). What does 馆 (guǎn) mean?",
                "options": [
                    "A type of room",
                    "A public building or hall",
                    "A small shop",
                    "A school",
                ],
                "answer": "b",
                "hints": [
                    "馆 originally meant a large hall or official building.",
                    "All three are large public buildings.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "馆 (guǎn) = hall / public building. 图书馆 (library), 博物馆 (museum), 体育馆 (gym/stadium), 餐馆 (restaurant), 大使馆 (embassy). Once you spot 馆, you know it's a building with a specific purpose!",
                "is_boss": False,
                "flavor": "龙龙 sketches a map marking every 馆 in the kingdom.",
            },
            {
                "id": "life_school_day",
                "title": "A Day at School",
                "type": "quiz",
                "question": "我和同学在图书馆学习，然后去食堂吃饭。What happens?",
                "options": [
                    "I study alone, then go home",
                    "I study with classmates at the library, then go to the cafeteria to eat",
                    "I eat at the library with my teacher",
                    "My classmates and I go to the playground",
                ],
                "answer": "b",
                "hints": [
                    "和 = with/and, 同学 = classmates, 图书馆 = library.",
                    "然后 = then, 去 = go to, 食堂 = cafeteria, 吃饭 = eat.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "我和同学在图书馆学习，然后去食堂吃饭 = 'My classmates and I study at the library, then go to the cafeteria to eat.' You can understand a full Chinese sentence about school life now!",
                "is_boss": False,
                "flavor": "龙龙 links arms with a fellow dragon. 'School is better with 同学!'",
            },
            {
                "id": "life_boss",
                "title": "School Life Master",
                "type": "quiz",
                "question": "Match all: 同学 = classmate, 老师 = teacher, 图书馆 = library, 食堂 = cafeteria. Which sentence means 'The teacher is in the library'?",
                "options": [
                    "同学在食堂",
                    "老师在图书馆",
                    "老师在食堂",
                    "同学在图书馆",
                ],
                "answer": "b",
                "hints": [
                    "老师 = teacher, 在 = is at/in, 图书馆 = library.",
                    "在 (zài) marks location — 'is at' or 'is in.'",
                ],
                "xp": 50,
                "difficulty": "hard",
                "lesson": "老师在图书馆 = The teacher is in the library. 在 (zài) = is at / is in. This simple pattern (person + 在 + place) lets you say where anyone is. 同学在食堂 = Classmates are in the cafeteria. 我在学校 = I'm at school.",
                "is_boss": True,
                "flavor": "龙龙 surveys the entire academy. 'You know every corner of school life now!'",
            },
        ],
    },
}
