"""
zones.py — Music zones and challenges for the Music skill pack.

All challenges use "type": "quiz" with multiple-choice options.
Designed for ages 7-10, guided warmly by Puck.
"""

ZONE_ORDER = [
    "musical_notes",
    "rhythm_and_beat",
    "instruments_orchestra",
    "singing_and_voice",
    "music_around_world",
    "famous_composers",
    "music_and_feelings",
    "making_music",
]

ZONES = {
    "musical_notes": {
        "id": "musical_notes",
        "name": "The Language of Notes",
        "description": "Learn note names, the treble clef, staff lines, and note lengths",
        "level_required": 1,
        "challenges": [
            {
                "id": "note_names",
                "title": "The Musical Alphabet",
                "type": "quiz",
                "question": "Music uses a special alphabet for note names. How many letter names are there in the musical alphabet?",
                "options": ["5", "7", "10", "26"],
                "answer": "b",
                "hints": [
                    "The musical alphabet doesn't go all the way to Z!",
                    "It starts at A and only goes up to G, then starts over.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The musical alphabet has just seven letters: A, B, C, D, E, F, and G. After G, it starts over again at A, but higher! These seven notes repeat over and over across a piano keyboard.",
                "is_boss": False,
                "flavor": "Puck hums softly, and seven glowing letters float up from the page: A B C D E F G.",
            },
            {
                "id": "treble_clef",
                "title": "The Curly Symbol",
                "type": "quiz",
                "question": "At the beginning of most sheet music, there is a fancy curly symbol that tells you which notes go on which lines. What is this symbol called?",
                "options": ["A sharp sign", "A treble clef", "A music stamp", "A note key"],
                "answer": "b",
                "hints": [
                    "Its name has the word 'clef' in it, which means 'key' in French.",
                    "It looks like a fancy, swirly letter S with a line through it.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The treble clef is the most common clef in music. It curls around the second line of the staff to show that line is the note G. That's why it is also called the G clef! Most melodies you sing are written in treble clef.",
                "is_boss": False,
                "flavor": "Puck draws a curly shape in the air with one glowing finger. It shimmers and stays.",
            },
            {
                "id": "staff_lines",
                "title": "Five Lines and Four Spaces",
                "type": "quiz",
                "question": "Musical notes are written on a set of horizontal lines called a staff. How many lines does a musical staff have?",
                "options": ["3", "4", "5", "6"],
                "answer": "c",
                "hints": [
                    "It's more than four but fewer than six.",
                    "Think of the fingers on one hand!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A musical staff has five lines and four spaces between them. Notes sit either on the lines or in the spaces. The higher up on the staff a note is, the higher it sounds! A helpful trick: the spaces in treble clef spell F-A-C-E.",
                "is_boss": False,
                "flavor": "Five glowing lines stretch across the page. Puck walks along them like a tightrope.",
            },
            {
                "id": "whole_note",
                "title": "The Longest Note",
                "type": "quiz",
                "question": "Which type of note is held for the longest time — four full beats?",
                "options": ["Quarter note", "Half note", "Whole note", "Eighth note"],
                "answer": "c",
                "hints": [
                    "Its name means 'all' or 'entire' — it takes up a whole measure in common time.",
                    "It looks like an empty oval with no stem sticking out.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A whole note lasts for four beats. It looks like a hollow oval (no filled-in center, no stem). A half note gets 2 beats, a quarter note gets 1 beat, and an eighth note gets half a beat. The names tell you the fraction of a whole note each one is!",
                "is_boss": False,
                "flavor": "Puck holds a single glowing note and counts slowly: one... two... three... four!",
            },
            {
                "id": "quarter_note_look",
                "title": "The Walking Note",
                "type": "quiz",
                "question": "A quarter note lasts for one beat — like one step when you walk. What does a quarter note look like?",
                "options": [
                    "A hollow oval with no stem",
                    "A filled-in oval with a stem",
                    "A filled-in oval with a stem and a flag",
                    "Two notes connected by a beam",
                ],
                "answer": "b",
                "hints": [
                    "It has a black (filled-in) note head, not a hollow one.",
                    "It has a straight line (a stem) going up or down, but no little flag on it.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A quarter note has a filled-in (black) oval and a straight stem. It gets one beat — like a steady walking pace. If you add a little flag to the stem, it becomes an eighth note (half a beat). Musicians often call quarter notes the 'heartbeat' of music!",
                "is_boss": False,
                "flavor": "Puck marches in place — left, right, left, right — one step per beat.",
            },
            {
                "id": "face_spaces",
                "title": "The Magic Word",
                "type": "quiz",
                "question": "There is a famous trick for remembering the notes in the spaces of the treble clef staff. The notes in the spaces, from bottom to top, spell which word?",
                "options": ["FACE", "EDGE", "CAGE", "BEAD"],
                "answer": "a",
                "hints": [
                    "It is a four-letter word — one letter for each of the four spaces.",
                    "The first space is F, the second space is A...",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "The four spaces of the treble clef staff, from bottom to top, hold the notes F, A, C, and E — spelling FACE! For the five lines, a common phrase is 'Every Good Boy Does Fine' (E, G, B, D, F). These memory tricks help musicians read notes quickly.",
                "is_boss": True,
                "flavor": "Puck grins and points to the four glowing spaces between the staff lines. Letters appear one by one...",
            },
        ],
    },
    "rhythm_and_beat": {
        "id": "rhythm_and_beat",
        "name": "The Pulse of Music",
        "description": "Learn about beat, tempo, time signatures, and rhythm patterns",
        "level_required": 2,
        "challenges": [
            {
                "id": "what_is_beat",
                "title": "The Heartbeat of a Song",
                "type": "quiz",
                "question": "When you tap your foot to a song, you are tapping along with something. What is it called?",
                "options": ["The melody", "The beat", "The lyrics", "The harmony"],
                "answer": "b",
                "hints": [
                    "It's the steady pulse you feel in music, like a heartbeat.",
                    "It's what a drummer keeps steady for the whole band.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The beat is the steady pulse in music — like a heartbeat that keeps going. When you clap along to a song, you're clapping to the beat! Every piece of music has a beat, even if it's very fast or very slow.",
                "is_boss": False,
                "flavor": "Puck taps a tiny foot. Tap. Tap. Tap. Tap. Steady and sure, like a heartbeat.",
            },
            {
                "id": "tempo_meaning",
                "title": "Fast and Slow",
                "type": "quiz",
                "question": "The speed of the beat in music has a special name. What is it called?",
                "options": ["Volume", "Tempo", "Pitch", "Rhythm"],
                "answer": "b",
                "hints": [
                    "It comes from an Italian word meaning 'time'.",
                    "A lullaby has a slow one; a dance song has a fast one.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Tempo means the speed of the beat. A slow tempo makes music feel calm and gentle (like a lullaby). A fast tempo makes music feel exciting and energetic (like a dance song). Musicians measure tempo in BPM — beats per minute!",
                "is_boss": False,
                "flavor": "Puck flies slowly... then suddenly zooms! 'See? That's tempo!'",
            },
            {
                "id": "time_signature_44",
                "title": "The Magic Numbers",
                "type": "quiz",
                "question": "At the start of a piece of music, you often see two numbers stacked like a fraction — like 4/4. What are these numbers called?",
                "options": ["The speed mark", "The time signature", "The volume sign", "The note counter"],
                "answer": "b",
                "hints": [
                    "It tells you how many beats are in each group (measure) of music.",
                    "The top number says how many beats; the bottom says what kind of note gets one beat.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A time signature is two numbers at the start of a piece. In 4/4 time, there are 4 beats per measure, and a quarter note gets 1 beat. This is the most common time signature — almost every pop song uses it! It is sometimes called 'common time'.",
                "is_boss": False,
                "flavor": "Puck holds up four tiny fingers. 'One, two, three, four — then start again!'",
            },
            {
                "id": "waltz_time",
                "title": "The Dancing Count",
                "type": "quiz",
                "question": "A waltz has a special time signature that makes you want to sway: ONE-two-three, ONE-two-three. What time signature is a waltz?",
                "options": ["2/4", "3/4", "4/4", "6/8"],
                "answer": "b",
                "hints": [
                    "Count the beats: ONE two three, ONE two three. How many beats is that per group?",
                    "The top number tells you the beats per measure. A waltz has three.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A waltz is in 3/4 time — three beats per measure, with the first beat strong. This gives music a graceful, swaying feel. Many beautiful dances and famous pieces by composers like Strauss and Tchaikovsky are written in waltz time!",
                "is_boss": False,
                "flavor": "Puck spins in slow circles — one-two-three, one-two-three — wings tracing light.",
            },
            {
                "id": "rhythm_vs_beat",
                "title": "Rhythm's Secret",
                "type": "quiz",
                "question": "Beat is the steady pulse. But what is rhythm?",
                "options": [
                    "The same thing as beat",
                    "The pattern of long and short sounds over the beat",
                    "How loud or soft the music is",
                    "The name of the song",
                ],
                "answer": "b",
                "hints": [
                    "Beat stays steady, but this can change — some sounds are long, some are short.",
                    "Think of it as the interesting pattern that sits on top of the steady beat.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Rhythm is the pattern of long and short sounds in music. The beat stays steady (like a clock ticking), but rhythm dances on top of it with interesting patterns. When you clap the pattern of a song's words, you are clapping the rhythm!",
                "is_boss": False,
                "flavor": "Puck claps a pattern: clap-clap-clapclapclap. 'That's a rhythm! Different from the steady beat.'",
            },
            {
                "id": "rest_silence",
                "title": "The Sound of Silence",
                "type": "quiz",
                "question": "In music, silence is just as important as sound. What is a moment of planned silence in music called?",
                "options": ["A break", "A rest", "A pause", "A blank"],
                "answer": "b",
                "hints": [
                    "It has its own special symbols written on the staff, just like notes do.",
                    "A whole ___ lasts four beats of silence, just like a whole note lasts four beats of sound.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "A rest is a symbol for silence in music. Just like notes, rests come in different lengths: whole rest (4 beats of silence), half rest (2 beats), and quarter rest (1 beat). Great composers use rests to create suspense and surprise!",
                "is_boss": True,
                "flavor": "Puck puts a finger to lips. Shh! The page goes perfectly still for four whole beats.",
            },
        ],
    },
    "instruments_orchestra": {
        "id": "instruments_orchestra",
        "name": "The Instrument Families",
        "description": "Discover the four families of the orchestra and famous instruments",
        "level_required": 3,
        "challenges": [
            {
                "id": "four_families",
                "title": "The Four Families",
                "type": "quiz",
                "question": "An orchestra is divided into four instrument families. Which of these is one of the four families?",
                "options": ["Strings", "Keyboards", "Guitars", "Electronics"],
                "answer": "a",
                "hints": [
                    "Think of instruments with strings that you play with a bow.",
                    "Violins, violas, cellos, and double basses all belong to this family.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The four families of the orchestra are: Strings (violin, viola, cello, double bass), Woodwinds (flute, clarinet, oboe, bassoon), Brass (trumpet, trombone, French horn, tuba), and Percussion (drums, cymbals, timpani, xylophone). Together they can make incredible music!",
                "is_boss": False,
                "flavor": "Puck gestures to four glowing corners of the page. Each one holds a different kind of instrument.",
            },
            {
                "id": "violin_family",
                "title": "The Queen of Strings",
                "type": "quiz",
                "question": "This is the smallest and highest-sounding member of the string family. An orchestra usually has more of these than any other instrument. What is it?",
                "options": ["Cello", "Double bass", "Viola", "Violin"],
                "answer": "d",
                "hints": [
                    "It is held under the chin and played with a bow.",
                    "Its name sounds like 'violence' but means something beautiful in Italian.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The violin is the smallest and highest-pitched string instrument in the orchestra. A full orchestra can have over 30 violins! The violin was invented in Italy around 500 years ago. Some famous violins made by Antonio Stradivari are worth millions of dollars.",
                "is_boss": False,
                "flavor": "A tiny violin appears on the page. Puck draws a bow across its strings and a bright, singing sound fills the air.",
            },
            {
                "id": "brass_trumpet",
                "title": "The Shining Brass",
                "type": "quiz",
                "question": "Brass instruments are played by buzzing your lips into a mouthpiece. Which of these is a brass instrument?",
                "options": ["Flute", "Clarinet", "Trumpet", "Drum"],
                "answer": "c",
                "hints": [
                    "It is shiny and golden, and played by blowing into a small cup-shaped mouthpiece.",
                    "It is famous for playing fanfares and jazz solos!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The trumpet is a brass instrument played by buzzing the lips into a mouthpiece. It is one of the oldest instruments in the world — ancient Egyptians had trumpets! Modern trumpets have three valves that let you play different notes. Louis Armstrong was one of the most famous trumpet players ever.",
                "is_boss": False,
                "flavor": "Puck puffs out tiny cheeks and pretends to play a trumpet. A golden fanfare rings out!",
            },
            {
                "id": "woodwind_flute",
                "title": "The Woodwind Puzzle",
                "type": "quiz",
                "question": "The flute is in the woodwind family, even though modern flutes are made of metal. Why is it still called a woodwind?",
                "options": [
                    "Because it sounds like wind in the trees",
                    "Because early flutes were made of wood",
                    "Because it is painted to look like wood",
                    "Because wood makes the best music",
                ],
                "answer": "b",
                "hints": [
                    "Think about what flutes were made of hundreds of years ago.",
                    "The family is named after the material of the original instruments.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The flute is a woodwind because the earliest flutes were carved from wood. Some of the oldest flutes ever found are over 40,000 years old, made from bird bones! Other woodwinds include the clarinet, oboe, and bassoon — most of which still use a wooden reed to make sound.",
                "is_boss": False,
                "flavor": "Puck blows across the top of a tiny silver tube. A clear, bird-like sound floats up.",
            },
            {
                "id": "percussion_family",
                "title": "Hit, Shake, and Scrape",
                "type": "quiz",
                "question": "The percussion family includes instruments you hit, shake, or scrape. Which of these is a percussion instrument?",
                "options": ["Tuba", "Oboe", "Xylophone", "Harp"],
                "answer": "c",
                "hints": [
                    "This instrument has wooden bars arranged like piano keys that you strike with mallets.",
                    "Its name comes from Greek words meaning 'wood' and 'sound'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The xylophone is a percussion instrument with wooden bars that you hit with mallets. Percussion is the oldest family of instruments — people have been hitting drums and shaking rattles since the very beginning of human history! The word 'percussion' comes from Latin, meaning 'to strike'.",
                "is_boss": False,
                "flavor": "Puck taps a row of colorful wooden bars. Each one rings a different note — ding, dong, ding!",
            },
            {
                "id": "conductor_role",
                "title": "The Leader of the Orchestra",
                "type": "quiz",
                "question": "In an orchestra, one person stands at the front and waves a thin stick called a baton. What is this person called?",
                "options": ["The soloist", "The conductor", "The composer", "The drummer"],
                "answer": "b",
                "hints": [
                    "This person does not play an instrument — they lead all the other players.",
                    "They use hand movements and a baton to show tempo, volume, and expression.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "The conductor leads the orchestra. They use a baton and hand gestures to set the tempo, show when instruments should come in, and shape the music's expression. A great conductor can make 80 musicians play as one! Famous conductors include Leonard Bernstein and Gustavo Dudamel.",
                "is_boss": True,
                "flavor": "Puck picks up a toothpick-sized baton and waves it grandly. All the instruments on the page begin to play at once!",
            },
        ],
    },
    "singing_and_voice": {
        "id": "singing_and_voice",
        "name": "The Human Instrument",
        "description": "Learn how your voice works, pitch, harmony, and famous singers",
        "level_required": 5,
        "challenges": [
            {
                "id": "vocal_cords",
                "title": "The Strings Inside You",
                "type": "quiz",
                "question": "When you sing or speak, tiny parts inside your throat vibrate to make sound. What are these called?",
                "options": ["Vocal cords", "Throat strings", "Sound tubes", "Voice bones"],
                "answer": "a",
                "hints": [
                    "They are thin flaps that open and close very fast as air passes through.",
                    "The word 'vocal' means 'related to the voice'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Your vocal cords (also called vocal folds) are two small flaps of tissue in your throat. When you push air past them, they vibrate — up to 1,000 times per second for high notes! Everyone's vocal cords are a slightly different size, which is why every person's voice sounds unique.",
                "is_boss": False,
                "flavor": "Puck points to a tiny glowing throat on the page. 'Your very own instrument — built right in!'",
            },
            {
                "id": "pitch_high_low",
                "title": "High and Low",
                "type": "quiz",
                "question": "When a sound is very high (like a bird chirping) or very low (like a bear growling), we are describing its what?",
                "options": ["Volume", "Pitch", "Tempo", "Rhythm"],
                "answer": "b",
                "hints": [
                    "A piccolo plays very high; a tuba plays very low. What word describes this difference?",
                    "It is not about loud or soft — it is about high or low.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Pitch is how high or low a sound is. A bird singing is high-pitched; thunder rumbling is low-pitched. Pitch depends on how fast something vibrates — fast vibrations make high sounds, slow vibrations make low sounds. Singers train to control their pitch perfectly!",
                "is_boss": False,
                "flavor": "Puck sings a note that starts low and slides up high, wings rising with the pitch.",
            },
            {
                "id": "harmony_meaning",
                "title": "Singing Together",
                "type": "quiz",
                "question": "When two or more notes are sung at the same time and sound beautiful together, what is that called?",
                "options": ["A solo", "A rhythm", "Harmony", "A tempo"],
                "answer": "c",
                "hints": [
                    "Think of a choir singing different notes at the same time that blend perfectly.",
                    "This word also means 'agreement' or 'things going well together' in everyday language.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Harmony is when two or more different notes sound at the same time and blend beautifully. When a choir sings in harmony, different people sing different notes that fit together like puzzle pieces. Harmony can make music sound rich, full, and deeply moving.",
                "is_boss": False,
                "flavor": "Puck opens tiny wings and two notes shimmer in the air, blending into something even more beautiful.",
            },
            {
                "id": "soprano_alto",
                "title": "Voice Types",
                "type": "quiz",
                "question": "The highest female singing voice type is called soprano. What is the name for the lowest male singing voice?",
                "options": ["Tenor", "Alto", "Bass", "Baritone"],
                "answer": "c",
                "hints": [
                    "This word also means 'the bottom' or 'the lowest part' in music.",
                    "Think of a bass guitar — it plays the lowest notes. This voice does the same!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "There are four main voice types. From highest to lowest: soprano (high female), alto (low female), tenor (high male), and bass (low male). Some children can sing in the soprano range before their voices change! The word 'bass' comes from the Italian word 'basso', meaning 'low'.",
                "is_boss": False,
                "flavor": "Puck shows four singers on the page, each glowing a different color, each singing a different note.",
            },
            {
                "id": "choir_boss",
                "title": "The Power of Many Voices",
                "type": "quiz",
                "question": "A large group of singers who perform together is called a what?",
                "options": ["A band", "A choir", "A duet", "An orchestra"],
                "answer": "b",
                "hints": [
                    "You might hear one of these singing in a church, a school, or a concert hall.",
                    "The word rhymes with 'fire'.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "A choir (also spelled 'quire' in old English) is a group of singers performing together. Choirs can have dozens or even hundreds of members! They often split into sections — soprano, alto, tenor, and bass — to create beautiful harmonies. The oldest choirs in the world are over 1,000 years old.",
                "is_boss": True,
                "flavor": "Puck waves both arms and dozens of tiny glowing voices rise from the page, singing together in perfect harmony.",
            },
        ],
    },
    "music_around_world": {
        "id": "music_around_world",
        "name": "Songs of Every Land",
        "description": "Explore music from Africa, India, Japan, Ireland, the Caribbean, and beyond",
        "level_required": 7,
        "challenges": [
            {
                "id": "african_drums",
                "title": "The Talking Drums of Africa",
                "type": "quiz",
                "question": "In West Africa, there is a special drum held under the arm that can be squeezed to change its pitch, almost like it is 'talking'. What is it called?",
                "options": ["A bongo", "A talking drum", "A steel drum", "A tabla"],
                "answer": "b",
                "hints": [
                    "Its nickname is exactly what it sounds like — a drum that 'speaks'!",
                    "The player squeezes the strings on its sides to make it go higher or lower.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The talking drum (called 'dundun' in Yoruba) is an hourglass-shaped drum from West Africa. By squeezing the strings that connect its two drumheads, the player can change the pitch to mimic the tones of spoken language! Drummers can actually send messages across villages with it.",
                "is_boss": False,
                "flavor": "Puck holds a tiny hourglass-shaped drum and squeezes it. The drum seems to say 'hello!'",
            },
            {
                "id": "indian_sitar",
                "title": "The Shimmering Strings of India",
                "type": "quiz",
                "question": "The sitar is a famous stringed instrument from India with a long neck and a round body. How many strings can a sitar have?",
                "options": ["6, like a guitar", "Up to 20 or more", "Only 2", "Exactly 10"],
                "answer": "b",
                "hints": [
                    "A sitar has many more strings than a guitar!",
                    "Some strings are played directly, and others vibrate on their own to create a shimmering sound.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The sitar can have 18 to 21 strings or even more! Only some are played directly — the rest are 'sympathetic strings' that vibrate on their own, giving the sitar its magical, shimmering sound. Ravi Shankar made the sitar famous around the world and even taught a Beatle to play it!",
                "is_boss": False,
                "flavor": "Puck plucks a string on a long-necked instrument. The sound shimmers and seems to go on forever.",
            },
            {
                "id": "japanese_koto",
                "title": "The Elegant Koto of Japan",
                "type": "quiz",
                "question": "The koto is a traditional Japanese stringed instrument that is placed flat on the floor to be played. How long is a koto?",
                "options": [
                    "About 30 centimeters (1 foot)",
                    "About 1 meter (3 feet)",
                    "About 1.8 meters (6 feet)",
                    "About 4 meters (13 feet)",
                ],
                "answer": "c",
                "hints": [
                    "It is much longer than a guitar — almost as long as a grown-up is tall!",
                    "It has 13 strings and you sit on the floor to play it.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The koto is about 1.8 meters (6 feet) long, with 13 silk strings stretched over movable bridges. Players wear finger picks and pluck the strings to create elegant, flowing melodies. The koto is over 1,000 years old and is considered the national instrument of Japan!",
                "is_boss": False,
                "flavor": "A beautiful long instrument appears on the page. Puck kneels beside it and plucks — the sound is like water flowing over smooth stones.",
            },
            {
                "id": "irish_fiddle",
                "title": "The Irish Fiddle",
                "type": "quiz",
                "question": "In Irish traditional music, a violin played in a lively folk style has a different name. What is it called?",
                "options": ["A banjo", "A fiddle", "A lute", "A harmonica"],
                "answer": "b",
                "hints": [
                    "It is the exact same instrument as a violin, just played in a different style!",
                    "The word rhymes with 'middle'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A fiddle and a violin are the same instrument! The difference is in how it is played. Fiddle music is usually lively and danceable — think of Irish jigs and reels. Fiddle playing is found in Irish, Scottish, American country, and many other folk music traditions around the world.",
                "is_boss": False,
                "flavor": "Puck starts dancing an Irish jig as a lively fiddle tune pours off the page!",
            },
            {
                "id": "steel_drums_caribbean",
                "title": "The Steel Pans of the Caribbean",
                "type": "quiz",
                "question": "Steel drums (also called steel pans) were invented on the Caribbean island of Trinidad. What were the very first steel drums made from?",
                "options": ["Tin cans", "Old oil barrels", "Metal trash cans", "Car parts"],
                "answer": "b",
                "hints": [
                    "These large metal containers were left behind by oil companies.",
                    "People discovered that different dents in the metal made different musical notes!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Steel pans were invented in Trinidad in the 1930s. Clever musicians discovered that hammering dents into the tops of old oil barrels created different notes! Today, steel pan is the national instrument of Trinidad and Tobago. A single pan can play a full melody — and a steel band can have dozens of pans!",
                "is_boss": False,
                "flavor": "Puck taps the curved surface of a shimmering metal drum. Bright, sunny notes ring out like island bells!",
            },
            {
                "id": "world_music_boss",
                "title": "The Universal Language",
                "type": "quiz",
                "question": "Music is found in every culture on Earth. Why do researchers believe music might be a 'universal language'?",
                "options": [
                    "Because everyone speaks the same words when they sing",
                    "Because every culture in history has created some form of music",
                    "Because all countries use the same instruments",
                    "Because music was invented by one culture and copied by others",
                ],
                "answer": "b",
                "hints": [
                    "Even cultures that had no contact with each other all developed music independently.",
                    "From ancient cave dwellers to modern cities — music is everywhere humans are.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Every human culture ever studied — from ancient civilizations to remote tribes — has created music. Scientists have found bone flutes that are over 40,000 years old! While languages and customs differ, the human desire to make music appears to be built into who we are. Music truly connects us all.",
                "is_boss": True,
                "flavor": "Puck spins slowly as instruments from every corner of the world play together in one beautiful, swirling melody.",
            },
        ],
    },
    "famous_composers": {
        "id": "famous_composers",
        "name": "The Great Composers",
        "description": "Meet Mozart, Beethoven, Bach, and Tchaikovsky",
        "level_required": 9,
        "challenges": [
            {
                "id": "mozart_prodigy",
                "title": "The Boy Wonder",
                "type": "quiz",
                "question": "Wolfgang Amadeus Mozart started composing music at an incredibly young age. How old was he when he wrote his first piece?",
                "options": ["3 years old", "5 years old", "10 years old", "15 years old"],
                "answer": "b",
                "hints": [
                    "He was younger than most kids are when they start school!",
                    "By age 6, he was already performing for kings and queens across Europe.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Mozart composed his first piece at age 5 and performed for royalty at age 6! He went on to write over 600 pieces of music including operas, symphonies, and concertos. Born in Salzburg, Austria, in 1756, Mozart is considered one of the greatest musical geniuses who ever lived.",
                "is_boss": False,
                "flavor": "Puck shows a tiny boy sitting at a harpsichord, his feet not even reaching the pedals, writing music.",
            },
            {
                "id": "beethoven_deaf",
                "title": "Music in Silence",
                "type": "quiz",
                "question": "Ludwig van Beethoven continued composing some of the greatest music ever written even after he became what?",
                "options": ["Blind", "Deaf", "Unable to walk", "Very old"],
                "answer": "b",
                "hints": [
                    "He lost the ability to hear, but he could still feel the vibrations and imagine the music.",
                    "He once sawed the legs off his piano so he could feel it vibrate through the floor.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Beethoven began losing his hearing in his late twenties and was almost completely deaf by age 44. Yet he kept composing! His Ninth Symphony, with its famous 'Ode to Joy' melody, was written when he could barely hear a sound. He felt the vibrations and heard the music in his brilliant mind.",
                "is_boss": False,
                "flavor": "Puck closes both ears with tiny hands and then, with fierce determination, begins to conduct an invisible orchestra.",
            },
            {
                "id": "bach_family",
                "title": "The Musical Family",
                "type": "quiz",
                "question": "Johann Sebastian Bach came from a very musical family. How many of Bach's own children also became well-known musicians?",
                "options": ["None", "2", "4", "All 20 of them"],
                "answer": "c",
                "hints": [
                    "Bach had 20 children! Not all became musicians, but several did.",
                    "Four of his sons became famous composers in their own right.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Bach had 20 children, and four of them became famous composers! The Bach family was so musical that in their region of Germany, the word 'Bach' was almost a synonym for 'musician.' Johann Sebastian Bach is now considered the father of Western classical music, famous for pieces like the Brandenburg Concertos.",
                "is_boss": False,
                "flavor": "Puck shows a family portrait with twenty children — and nearly everyone is holding an instrument!",
            },
            {
                "id": "tchaikovsky_ballet",
                "title": "The Dance Master",
                "type": "quiz",
                "question": "Tchaikovsky wrote the music for one of the most famous ballets in the world, performed every December. Which ballet is it?",
                "options": ["Swan Lake", "Sleeping Beauty", "The Nutcracker", "Cinderella"],
                "answer": "c",
                "hints": [
                    "This ballet features a magical Christmas Eve, a battle with a mouse king, and a land of sweets.",
                    "The 'Dance of the Sugar Plum Fairy' is one of its most famous melodies.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The Nutcracker, composed by Pyotr Ilyich Tchaikovsky in 1892, is performed around the world every December. Fun fact: Tchaikovsky used a brand-new instrument called the celesta (which sounds like magical bells) for the Dance of the Sugar Plum Fairy. He also wrote Swan Lake and Sleeping Beauty!",
                "is_boss": False,
                "flavor": "Puck pirouettes as tiny sugar plum fairies dance across the page, each one trailing sparkles of light.",
            },
            {
                "id": "ode_to_joy",
                "title": "A Song for the Whole World",
                "type": "quiz",
                "question": "Beethoven's Ninth Symphony includes a famous melody called 'Ode to Joy.' This melody was later chosen as the anthem of what?",
                "options": [
                    "The United States",
                    "The European Union",
                    "The Olympic Games",
                    "The United Nations",
                ],
                "answer": "b",
                "hints": [
                    "It became the anthem of a group of countries that work together in Europe.",
                    "Beethoven's message was about all people being brothers and sisters — fitting for a union of nations.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Beethoven's 'Ode to Joy' from his Ninth Symphony was adopted as the anthem of the European Union in 1985. Beethoven wrote it as a celebration of the unity of all humankind. The Ninth Symphony was revolutionary — it was the first major symphony to include a choir singing words alongside the orchestra!",
                "is_boss": True,
                "flavor": "Puck's wings glow bright as the most famous melody in classical music begins to play, note by glorious note.",
            },
        ],
    },
    "music_and_feelings": {
        "id": "music_and_feelings",
        "name": "How Music Makes You Feel",
        "description": "Explore how music expresses emotions through major and minor keys and dynamics",
        "level_required": 11,
        "challenges": [
            {
                "id": "major_key_mood",
                "title": "The Happy Key",
                "type": "quiz",
                "question": "When a song is written in a major key, it usually sounds what?",
                "options": ["Sad and dark", "Happy and bright", "Scary and tense", "Sleepy and slow"],
                "answer": "b",
                "hints": [
                    "Think of 'Happy Birthday' or 'Twinkle Twinkle Little Star' — both are in a major key.",
                    "Major keys tend to sound cheerful, bright, and uplifting.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Major keys tend to sound happy, bright, and confident. Most cheerful songs — like 'Happy Birthday', 'Jingle Bells', and 'Twinkle Twinkle Little Star' — are in major keys. The word 'major' comes from Latin meaning 'greater.' It is the most common key in popular music!",
                "is_boss": False,
                "flavor": "Puck plays a bright, bouncy chord. The whole page seems to smile.",
            },
            {
                "id": "minor_key_mood",
                "title": "The Mysterious Key",
                "type": "quiz",
                "question": "When a song is written in a minor key, it usually sounds what?",
                "options": [
                    "Loud and bold",
                    "Sad, mysterious, or dramatic",
                    "Fast and silly",
                    "Exactly the same as major",
                ],
                "answer": "b",
                "hints": [
                    "Many movie villain themes and spooky Halloween songs are in minor keys.",
                    "Minor keys make music feel darker, more emotional, or more serious.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Minor keys tend to sound sad, mysterious, dramatic, or thoughtful. Many beautiful and powerful pieces are in minor keys — including Beethoven's 'Moonlight Sonata' and 'Fur Elise.' The difference between major and minor is just one or two notes changed, but it transforms the whole feeling!",
                "is_boss": False,
                "flavor": "Puck plays the same chord, but shifts one note down. The page turns shadowy and mysterious.",
            },
            {
                "id": "dynamics_loud_soft",
                "title": "Whisper and Roar",
                "type": "quiz",
                "question": "In music, the word for how loud or soft the music is played has a special name. What is it called?",
                "options": ["Tempo", "Dynamics", "Pitch", "Timbre"],
                "answer": "b",
                "hints": [
                    "It describes the difference between a whisper and a shout in music.",
                    "The Italian words 'piano' (soft) and 'forte' (loud) are part of this system.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Dynamics describe how loud or soft music is played. Musicians use Italian words: 'piano' (p) means soft, 'forte' (f) means loud, 'mezzo' means medium. Fun fact: the piano (the instrument) got its full name 'pianoforte' because it was the first keyboard that could play both soft AND loud!",
                "is_boss": False,
                "flavor": "Puck whispers... then SHOUTS! 'That's dynamics!'",
            },
            {
                "id": "crescendo",
                "title": "The Big Build-Up",
                "type": "quiz",
                "question": "When music gradually gets louder and louder, building up from soft to strong, what is this called?",
                "options": ["Diminuendo", "Crescendo", "Fortissimo", "Staccato"],
                "answer": "b",
                "hints": [
                    "This Italian word means 'growing' — the sound is growing bigger!",
                    "It is the opposite of getting softer (which is called diminuendo).",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A crescendo is when music gradually gets louder. The word comes from Italian, meaning 'growing.' Its opposite is diminuendo (or decrescendo), meaning 'getting softer.' Composers use crescendos to build excitement and drama — imagine a movie scene building to a thrilling moment!",
                "is_boss": False,
                "flavor": "The music on the page starts as a whisper and builds... and builds... until the whole page vibrates with sound!",
            },
            {
                "id": "music_emotions_science",
                "title": "Why Music Makes Us Feel",
                "type": "quiz",
                "question": "Scientists have discovered that listening to music you love causes your brain to release a special chemical that makes you feel happy. What is this chemical called?",
                "options": ["Adrenaline", "Oxygen", "Dopamine", "Calcium"],
                "answer": "c",
                "hints": [
                    "It is the same chemical your brain releases when you eat your favorite food or get a hug.",
                    "It starts with the letter D and is sometimes called the 'feel-good chemical.'",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "When you listen to music you love, your brain releases dopamine — the same 'reward chemical' that makes you feel happy when eating delicious food or getting a warm hug. This is why music can give you goosebumps or make you want to dance! Scientists believe music has affected human brains for hundreds of thousands of years.",
                "is_boss": True,
                "flavor": "Puck touches the page and a warm glow spreads outward. 'That tingly feeling when your favorite song plays? That's your brain saying THANK YOU.'",
            },
        ],
    },
    "making_music": {
        "id": "making_music",
        "name": "Your Musical Journey Begins",
        "description": "Learn how to start making music, practice tips, beginner instruments, and reading simple music",
        "level_required": 13,
        "challenges": [
            {
                "id": "beginner_instrument",
                "title": "The Best First Instrument",
                "type": "quiz",
                "question": "Many music teachers say this instrument is one of the best for beginners because it is affordable, portable, and teaches melody and breath control. What is it?",
                "options": ["Drum kit", "Recorder", "Electric guitar", "Grand piano"],
                "answer": "b",
                "hints": [
                    "You might have played one in school! It is a small wind instrument made of plastic or wood.",
                    "It is a simple type of flute — you blow into one end and cover holes with your fingers.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The recorder is one of the best first instruments! It is inexpensive, easy to hold, and teaches you important skills: reading notes, controlling your breath, and coordinating your fingers. The recorder is actually an ancient instrument — it was popular in Europe over 700 years ago. Even Henry VIII played one!",
                "is_boss": False,
                "flavor": "Puck pulls out a tiny recorder and plays a clear, sweet note. 'Everyone starts somewhere!'",
            },
            {
                "id": "practice_makes",
                "title": "The Secret to Getting Better",
                "type": "quiz",
                "question": "What is the single most important thing you can do to get better at playing an instrument?",
                "options": [
                    "Buy the most expensive instrument",
                    "Practice regularly, even a little each day",
                    "Only play songs you already know",
                    "Watch other people play without trying yourself",
                ],
                "answer": "b",
                "hints": [
                    "Even 15 minutes a day makes a huge difference over time!",
                    "The key word is 'regularly' — a little bit every day is better than a lot once a week.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Regular practice is the key to musical growth. Even 15 minutes a day is better than two hours once a week! Your brain builds connections each time you practice, and those connections get stronger with repetition. Every great musician in history became great through dedicated, patient practice.",
                "is_boss": False,
                "flavor": "Puck holds up a tiny calendar with a gold star on every day. 'A little every day — that's the real magic.'",
            },
            {
                "id": "reading_music_first",
                "title": "Your First Notes",
                "type": "quiz",
                "question": "When learning to read music, what is the very first thing most teachers have you learn?",
                "options": [
                    "How to write a symphony",
                    "How to play very fast",
                    "The names of the notes on the staff",
                    "How to conduct an orchestra",
                ],
                "answer": "c",
                "hints": [
                    "Before you can play the notes, you need to know what each one is called!",
                    "Remember FACE for the spaces and 'Every Good Boy Does Fine' for the lines?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Learning to read music starts with learning note names on the staff! You already know the tricks: spaces spell FACE, and lines are Every Good Boy Does Fine. Once you can name notes quickly, you can start playing simple melodies. Reading music is like reading a language — it gets easier and faster with practice!",
                "is_boss": False,
                "flavor": "Puck opens a beginner music book. The notes glow softly, each one whispering its name.",
            },
            {
                "id": "ukulele_strings",
                "title": "The Little Guitar",
                "type": "quiz",
                "question": "The ukulele is a small, cheerful instrument that is great for beginners. How many strings does a standard ukulele have?",
                "options": ["3", "4", "5", "6"],
                "answer": "b",
                "hints": [
                    "It has fewer strings than a guitar (which has 6).",
                    "You can count them on one hand — but you wouldn't use your thumb or pinky!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A standard ukulele has 4 strings, which makes it simpler than a guitar (6 strings). The ukulele came from Portugal but became famous in Hawaii. Its name means 'jumping flea' in Hawaiian — because the player's fingers look like jumping fleas on the strings! It is one of the easiest stringed instruments to learn.",
                "is_boss": False,
                "flavor": "Puck strums a tiny four-stringed instrument and a warm, sunny sound fills the page.",
            },
            {
                "id": "music_is_for_everyone",
                "title": "Anyone Can Make Music",
                "type": "quiz",
                "question": "Which of these statements about learning music is TRUE?",
                "options": [
                    "You have to be born with talent or you can never learn",
                    "You must start before age 5 or it is too late",
                    "Anyone can learn to play music at any age with practice",
                    "Only people with perfect pitch can become musicians",
                ],
                "answer": "c",
                "hints": [
                    "Many famous musicians started learning later in life!",
                    "The most important ingredient is not talent — it is wanting to learn and being willing to practice.",
                ],
                "xp": 35,
                "difficulty": "easy",
                "lesson": "Anyone can learn music at any age! While starting young has some advantages, people have become wonderful musicians starting at 8, 18, 38, or even 80. The most important things are curiosity, patience, and regular practice. Your musical journey can begin right now — no matter who you are or how old you are.",
                "is_boss": True,
                "flavor": "Puck's wings glow warm gold. 'The best time to start making music? Today. Right now. The Music Room will always be here for you.'",
            },
        ],
    },
}
