"""
zones.py — Directions & Places zones and challenges.

All challenges use "type": "quiz" (multiple-choice) or "type": "text" (free input).
Guided by Umi (海), a calm ocean guide who teaches through the rhythm of tides and navigation.
"""

ZONE_ORDER = [
    "basic_directions",
    "places_in_town",
    "asking_for_directions",
    "transportation",
    "describing_locations",
]

ZONES = {
    # -- Zone 1: Basic Directions -----------------------------------------------
    "basic_directions": {
        "id": "basic_directions",
        "name": "Basic Directions",
        "description": "Learn fundamental direction words: 右, 左, まっすぐ, 曲がる",
        "level_required": 1,
        "challenges": [
            {
                "id": "dir_migi",
                "title": "Right",
                "type": "quiz",
                "question": "右 (みぎ / migi) means what?",
                "options": ["Left", "Right", "Straight", "Turn"],
                "answer": "b",
                "hints": [
                    "This is one of the two basic lateral directions.",
                    "Think of the hand you write with (if right-handed).",
                ],
                "xp": 25,
                "lesson": "右 (みぎ / migi) = right. Example: 右に曲がってください (migi ni magatte kudasai) = Please turn right. 右側 (migigawa) = right side.",
                "is_boss": False,
                "flavor": "Umi points toward a lighthouse on the right side of the harbor.",
            },
            {
                "id": "dir_hidari",
                "title": "Left",
                "type": "quiz",
                "question": "左 (ひだり / hidari) means what?",
                "options": ["Right", "Straight", "Left", "Behind"],
                "answer": "c",
                "hints": [
                    "This is the opposite of 右 (migi).",
                    "It starts with 'hi' in romaji.",
                ],
                "xp": 25,
                "lesson": "左 (ひだり / hidari) = left. Example: 左に曲がってください (hidari ni magatte kudasai) = Please turn left. 左側 (hidarigawa) = left side.",
                "is_boss": False,
                "flavor": "Umi gestures toward a row of boats docked on the left.",
            },
            {
                "id": "dir_massugu",
                "title": "Straight Ahead",
                "type": "text",
                "question": "Type the romaji for まっすぐ (straight ahead):",
                "options": [],
                "answer": "massugu",
                "hints": [
                    "It has a double 's' sound in the middle.",
                    "Think: ma-ssu-gu.",
                ],
                "xp": 30,
                "lesson": "まっすぐ (massugu) = straight ahead. Example: まっすぐ行ってください (massugu itte kudasai) = Please go straight. The っ creates a double consonant pause.",
                "is_boss": False,
                "flavor": "Umi walks along a straight wooden pier extending into the sea.",
            },
            {
                "id": "dir_magaru",
                "title": "To Turn",
                "type": "quiz",
                "question": "曲がる (まがる / magaru) means what?",
                "options": ["To stop", "To turn", "To walk", "To cross"],
                "answer": "b",
                "hints": [
                    "This verb describes changing direction.",
                    "You do this at a corner or intersection.",
                ],
                "xp": 25,
                "lesson": "曲がる (まがる / magaru) = to turn. Te-form: 曲がって (magatte). Example: 角を右に曲がってください (kado wo migi ni magatte kudasai) = Please turn right at the corner.",
                "is_boss": False,
                "flavor": "Umi follows a winding path along the cliffside.",
            },
            {
                "id": "dir_kado",
                "title": "Corner",
                "type": "quiz",
                "question": "角 (かど / kado) means what?",
                "options": ["Street", "Bridge", "Corner", "Intersection"],
                "answer": "c",
                "hints": [
                    "This is the point where two roads meet at an angle.",
                    "You turn at this spot.",
                ],
                "xp": 25,
                "lesson": "角 (かど / kado) = corner. Example: 次の角を左に曲がってください (tsugi no kado wo hidari ni magatte kudasai) = Please turn left at the next corner.",
                "is_boss": False,
                "flavor": "Umi pauses at a stone corner where the harbor road bends.",
            },
            {
                "id": "dir_kosaten",
                "title": "Intersection",
                "type": "text",
                "question": "Type the romaji for 交差点 (intersection):",
                "options": [],
                "answer": "kousaten",
                "hints": [
                    "交差 means 'crossing' and 点 means 'point'.",
                    "Think: kou-sa-ten.",
                ],
                "xp": 30,
                "lesson": "交差点 (こうさてん / kousaten) = intersection / crossroads. Example: 交差点をまっすぐ行ってください (kousaten wo massugu itte kudasai) = Please go straight through the intersection.",
                "is_boss": False,
                "flavor": "Umi stands at a crossroads where four paths meet near the shore.",
            },
            {
                "id": "dir_wataru",
                "title": "To Cross",
                "type": "quiz",
                "question": "渡る (わたる / wataru) means what?",
                "options": ["To turn", "To stop", "To cross", "To enter"],
                "answer": "c",
                "hints": [
                    "You do this to get to the other side of a street or bridge.",
                    "The kanji 渡 contains the water radical (氵).",
                ],
                "xp": 25,
                "lesson": "渡る (わたる / wataru) = to cross. Example: 橋を渡ってください (hashi wo watatte kudasai) = Please cross the bridge. Te-form: 渡って (watatte).",
                "is_boss": False,
                "flavor": "Umi crosses a small wooden bridge over a tidal stream.",
            },
            {
                "id": "basic_directions_boss",
                "title": "Direction Master",
                "type": "quiz",
                "question": "How do you say 'Please go straight and turn right at the corner'?",
                "options": [
                    "まっすぐ行って、角を右に曲がってください (massugu itte, kado wo migi ni magatte kudasai)",
                    "右に行って、まっすぐ曲がってください (migi ni itte, massugu magatte kudasai)",
                    "角をまっすぐ、左に曲がってください (kado wo massugu, hidari ni magatte kudasai)",
                    "曲がって、右にまっすぐ行ってください (magatte, migi ni massugu itte kudasai)",
                ],
                "answer": "a",
                "hints": [
                    "First action: go straight (まっすぐ行って). Second action: turn right at the corner.",
                    "The te-form connects two sequential actions.",
                ],
                "xp": 35,
                "lesson": "まっすぐ行って、角を右に曲がってください combines two directions using the te-form. The pattern is: [action 1 te-form], [action 2 kudasai]. This is how Japanese naturally chains direction instructions.",
                "is_boss": True,
                "flavor": "Umi draws a map in the sand with a stick, tracing the route.",
            },
        ],
    },

    # -- Zone 2: Places in Town -------------------------------------------------
    "places_in_town": {
        "id": "places_in_town",
        "name": "Places in Town",
        "description": "Learn place names: 駅, 病院, 銀行, 郵便局, 学校, and more",
        "level_required": 5,
        "challenges": [
            {
                "id": "place_eki",
                "title": "Station",
                "type": "quiz",
                "question": "駅 (えき / eki) means what?",
                "options": ["Hospital", "Station", "School", "Post office"],
                "answer": "b",
                "hints": [
                    "This is where trains stop.",
                    "Every Japanese city has at least one of these.",
                ],
                "xp": 25,
                "lesson": "駅 (えき / eki) = station (train station). Example: 東京駅 (Toukyou-eki) = Tokyo Station. 駅前 (ekimae) = in front of the station -- a common meeting point.",
                "is_boss": False,
                "flavor": "Umi points to a seaside station where a train waits on the platform.",
            },
            {
                "id": "place_byouin",
                "title": "Hospital",
                "type": "text",
                "question": "Type the romaji for 病院 (hospital):",
                "options": [],
                "answer": "byouin",
                "hints": [
                    "病 means 'sick' and 院 means 'institution'.",
                    "Think: byou-in.",
                ],
                "xp": 30,
                "lesson": "病院 (びょういん / byouin) = hospital. 病気 (byouki) = illness. Example: 病院はどこですか (byouin wa doko desu ka) = Where is the hospital?",
                "is_boss": False,
                "flavor": "Umi nods toward a white building with a red cross near the harbor.",
            },
            {
                "id": "place_ginkou",
                "title": "Bank",
                "type": "quiz",
                "question": "銀行 (ぎんこう / ginkou) means what?",
                "options": ["Post office", "Bank", "Police station", "Library"],
                "answer": "b",
                "hints": [
                    "銀 means 'silver' and 行 means 'go/institution'.",
                    "This is where you exchange money.",
                ],
                "xp": 25,
                "lesson": "銀行 (ぎんこう / ginkou) = bank. 銀 means silver (precious metal connections to finance). Example: 銀行は駅の近くです (ginkou wa eki no chikaku desu) = The bank is near the station.",
                "is_boss": False,
                "flavor": "Umi passes a building with a vault-like door near the town center.",
            },
            {
                "id": "place_yuubinkyoku",
                "title": "Post Office",
                "type": "text",
                "question": "Type the romaji for 郵便局 (post office):",
                "options": [],
                "answer": "yuubinkyoku",
                "hints": [
                    "郵便 means 'mail' and 局 means 'bureau/office'.",
                    "Think: yuu-bin-kyoku.",
                ],
                "xp": 30,
                "lesson": "郵便局 (ゆうびんきょく / yuubinkyoku) = post office. You can send letters, packages, and even use the ATM. Look for the 〒 symbol -- the Japanese postal mark.",
                "is_boss": False,
                "flavor": "Umi stops at a red mailbox shaped like a pillar near the waterfront.",
            },
            {
                "id": "place_gakkou",
                "title": "School",
                "type": "quiz",
                "question": "学校 (がっこう / gakkou) means what?",
                "options": ["Library", "Museum", "School", "Park"],
                "answer": "c",
                "hints": [
                    "学 means 'learn/study' and 校 means 'school building'.",
                    "Children go here every day.",
                ],
                "xp": 25,
                "lesson": "学校 (がっこう / gakkou) = school. Note the double 'k' from っ. Related: 小学校 (shougakkou) = elementary school, 中学校 (chuugakkou) = middle school, 高校 (koukou) = high school.",
                "is_boss": False,
                "flavor": "Umi waves to children walking past a school overlooking the bay.",
            },
            {
                "id": "place_koban",
                "title": "Police Box",
                "type": "quiz",
                "question": "交番 (こうばん / kouban) means what?",
                "options": ["Fire station", "Police box", "Convenience store", "City hall"],
                "answer": "b",
                "hints": [
                    "These small stations are found on many street corners in Japan.",
                    "Police officers staff them to help with directions and safety.",
                ],
                "xp": 25,
                "lesson": "交番 (こうばん / kouban) = police box (small neighborhood police station). Unique to Japan, koubans are found throughout cities. Officers there often help lost people with directions!",
                "is_boss": False,
                "flavor": "Umi points to a small blue-roofed station on the corner.",
            },
            {
                "id": "place_conbini",
                "title": "Convenience Store",
                "type": "text",
                "question": "Type the romaji for コンビニ (convenience store):",
                "options": [],
                "answer": "konbini",
                "hints": [
                    "This is a shortened loanword from English 'convenience'.",
                    "Think: kon-bi-ni.",
                ],
                "xp": 30,
                "lesson": "コンビニ (konbini) = convenience store. Shortened from コンビニエンスストア. Japan's konbini (7-Eleven, Lawson, FamilyMart) are legendary -- open 24/7 with food, ATMs, and more.",
                "is_boss": False,
                "flavor": "Umi ducks into a brightly lit store for an onigiri.",
            },
            {
                "id": "places_in_town_boss",
                "title": "Town Navigator",
                "type": "quiz",
                "question": "Match the correct place: 'I need to send a letter. Where should I go?'",
                "options": [
                    "銀行 (ginkou)",
                    "郵便局 (yuubinkyoku)",
                    "交番 (kouban)",
                    "病院 (byouin)",
                ],
                "answer": "b",
                "hints": [
                    "Letters and packages are handled at the postal service.",
                    "Look for the 〒 symbol.",
                ],
                "xp": 35,
                "lesson": "郵便局 (yuubinkyoku) is where you send letters (手紙 / tegami) and packages (荷物 / nimotsu). Japanese post offices also offer savings accounts and insurance -- they're more than just mail!",
                "is_boss": True,
                "flavor": "Umi holds up a postcard addressed to a friend across the sea.",
            },
        ],
    },

    # -- Zone 3: Asking for Directions ------------------------------------------
    "asking_for_directions": {
        "id": "asking_for_directions",
        "name": "Asking for Directions",
        "description": "Learn to ask where things are: すみません、〜はどこですか",
        "level_required": 9,
        "challenges": [
            {
                "id": "ask_sumimasen",
                "title": "Excuse Me",
                "type": "quiz",
                "question": "すみません (sumimasen) is used for what?",
                "options": ["Saying goodbye", "Getting attention / apologizing", "Ordering food", "Saying thank you"],
                "answer": "b",
                "hints": [
                    "You say this before asking a stranger for help.",
                    "It can mean both 'excuse me' and 'I'm sorry'.",
                ],
                "xp": 25,
                "lesson": "すみません (sumimasen) = excuse me / I'm sorry. This is the essential phrase for approaching strangers. Always start with すみません before asking for directions -- it's polite and gets attention.",
                "is_boss": False,
                "flavor": "Umi approaches a fisherman mending nets on the dock.",
            },
            {
                "id": "ask_doko",
                "title": "Where?",
                "type": "text",
                "question": "Type the romaji for どこ (where):",
                "options": [],
                "answer": "doko",
                "hints": [
                    "This is a two-syllable question word.",
                    "Think: do-ko.",
                ],
                "xp": 30,
                "lesson": "どこ (doko) = where. The core question word for locations. Pattern: [place] はどこですか ([place] wa doko desu ka) = Where is [place]? Example: 駅はどこですか (eki wa doko desu ka) = Where is the station?",
                "is_boss": False,
                "flavor": "Umi scans the horizon, looking for the right path.",
            },
            {
                "id": "ask_wa_doko_desu_ka",
                "title": "Where Is...?",
                "type": "quiz",
                "question": "How do you say 'Where is the hospital?'",
                "options": [
                    "病院はどこですか (byouin wa doko desu ka)",
                    "どこは病院ですか (doko wa byouin desu ka)",
                    "病院はなんですか (byouin wa nan desu ka)",
                    "病院にいきます (byouin ni ikimasu)",
                ],
                "answer": "a",
                "hints": [
                    "The pattern is: [place] は どこ ですか.",
                    "The topic marker は comes after the place name.",
                ],
                "xp": 25,
                "lesson": "[Place] はどこですか is the standard pattern for asking 'Where is [place]?' The は (wa) marks the topic and どこですか (doko desu ka) asks 'where is it?' This works for any location.",
                "is_boss": False,
                "flavor": "Umi rehearses the phrase, gesturing toward the town.",
            },
            {
                "id": "ask_ikitai",
                "title": "I Want to Go",
                "type": "quiz",
                "question": "〜に行きたいです (~ ni ikitai desu) means what?",
                "options": ["I came from ~", "I want to go to ~", "I live near ~", "I passed by ~"],
                "answer": "b",
                "hints": [
                    "行く (iku) means 'to go'. The たい (tai) ending expresses desire.",
                    "に marks the destination.",
                ],
                "xp": 25,
                "lesson": "〜に行きたいです (~ ni ikitai desu) = I want to go to ~. Example: 駅に行きたいです (eki ni ikitai desu) = I want to go to the station. This is a polite way to tell someone your destination.",
                "is_boss": False,
                "flavor": "Umi checks a hand-drawn map, planning the next destination.",
            },
            {
                "id": "ask_koko",
                "title": "Here, There, Over There",
                "type": "quiz",
                "question": "What are the three location words: here, there, over there?",
                "options": [
                    "ここ、そこ、あそこ (koko, soko, asoko)",
                    "これ、それ、あれ (kore, sore, are)",
                    "この、その、あの (kono, sono, ano)",
                    "こう、そう、ああ (kou, sou, aa)",
                ],
                "answer": "a",
                "hints": [
                    "These are the 'ko-so-a' location words, not object words.",
                    "ここ = here (near me), そこ = there (near you), あそこ = over there.",
                ],
                "xp": 25,
                "lesson": "ここ (koko) = here, そこ (soko) = there (near listener), あそこ (asoko) = over there (far from both). Part of the ko-so-a-do system: ここ, そこ, あそこ, どこ. Essential for understanding directions!",
                "is_boss": False,
                "flavor": "Umi points near, mid-distance, and far across the bay.",
            },
            {
                "id": "ask_michi",
                "title": "Road / Way",
                "type": "text",
                "question": "Type the romaji for 道 (road / way):",
                "options": [],
                "answer": "michi",
                "hints": [
                    "This is a common word you'll see on street signs.",
                    "Think: mi-chi.",
                ],
                "xp": 30,
                "lesson": "道 (みち / michi) = road, way, path. Example: この道をまっすぐ行ってください (kono michi wo massugu itte kudasai) = Please go straight on this road. 道に迷いました (michi ni mayoimashita) = I'm lost.",
                "is_boss": False,
                "flavor": "Umi follows a sandy path winding between coastal houses.",
            },
            {
                "id": "ask_mayou",
                "title": "I'm Lost",
                "type": "quiz",
                "question": "How do you say 'I'm lost' in Japanese?",
                "options": [
                    "道に迷いました (michi ni mayoimashita)",
                    "道が分かりません (michi ga wakarimasen)",
                    "道を歩きました (michi wo arukimashita)",
                    "道に帰りました (michi ni kaerimashita)",
                ],
                "answer": "a",
                "hints": [
                    "迷う (mayou) means 'to get lost/confused'.",
                    "The past form (ました) shows it already happened.",
                ],
                "xp": 25,
                "lesson": "道に迷いました (michi ni mayoimashita) = I'm lost (lit. 'I have become lost on the road'). A crucial survival phrase! Pair it with すみません for a polite request: すみません、道に迷いました (sumimasen, michi ni mayoimashita).",
                "is_boss": False,
                "flavor": "Umi pretends to be lost among the harbor alleys, then winks.",
            },
            {
                "id": "asking_for_directions_boss",
                "title": "Direction Seeker",
                "type": "quiz",
                "question": "You're lost and need to find the station. What's the best full phrase?",
                "options": [
                    "すみません、駅はどこですか (sumimasen, eki wa doko desu ka)",
                    "駅！駅！ (eki! eki!)",
                    "駅に迷いました (eki ni mayoimashita)",
                    "どこですか、すみません (doko desu ka, sumimasen)",
                ],
                "answer": "a",
                "hints": [
                    "Start politely with すみません, then ask the question.",
                    "Use the standard pattern: [place] はどこですか.",
                ],
                "xp": 35,
                "lesson": "すみません、駅はどこですか is the complete, polite way to ask for directions. The pattern: すみません (get attention) + [place] はどこですか (where is [place]?). This works for any location in Japan!",
                "is_boss": True,
                "flavor": "Umi approaches a kind stranger and demonstrates the perfect question.",
            },
        ],
    },

    # -- Zone 4: Transportation -------------------------------------------------
    "transportation": {
        "id": "transportation",
        "name": "Transportation",
        "description": "Learn transport words: 電車, バス, タクシー, 歩いて and travel phrases",
        "level_required": 13,
        "challenges": [
            {
                "id": "trans_densha",
                "title": "Train",
                "type": "quiz",
                "question": "電車 (でんしゃ / densha) means what?",
                "options": ["Bus", "Taxi", "Train", "Bicycle"],
                "answer": "c",
                "hints": [
                    "電 means 'electric' and 車 means 'vehicle'.",
                    "This runs on rails and is the most popular transport in Japan.",
                ],
                "xp": 25,
                "lesson": "電車 (でんしゃ / densha) = train (electric train). Japan's trains are legendary for punctuality. Related: 新幹線 (shinkansen) = bullet train, 地下鉄 (chikatetsu) = subway.",
                "is_boss": False,
                "flavor": "Umi watches a sleek train glide along the coastal tracks.",
            },
            {
                "id": "trans_basu",
                "title": "Bus",
                "type": "text",
                "question": "Type the romaji for バス (bus):",
                "options": [],
                "answer": "basu",
                "hints": [
                    "This is a loanword from English written in katakana.",
                    "Think: ba-su.",
                ],
                "xp": 30,
                "lesson": "バス (basu) = bus. A loanword from English. バス停 (basutei) = bus stop. バスに乗る (basu ni noru) = to ride the bus. In rural Japan, buses are often the main public transport.",
                "is_boss": False,
                "flavor": "Umi flags down a bus heading along the seaside road.",
            },
            {
                "id": "trans_takushii",
                "title": "Taxi",
                "type": "quiz",
                "question": "タクシー (takushii) means what?",
                "options": ["Bicycle", "Taxi", "Airplane", "Ferry"],
                "answer": "b",
                "hints": [
                    "This is another English loanword in katakana.",
                    "The doors open automatically in Japan!",
                ],
                "xp": 25,
                "lesson": "タクシー (takushii) = taxi. Fun fact: Japanese taxi doors open and close automatically -- don't touch them! タクシー乗り場 (takushii noriba) = taxi stand. 〜までお願いします (~made onegaishimasu) = To ~ please.",
                "is_boss": False,
                "flavor": "A white-gloved taxi driver opens the door automatically.",
            },
            {
                "id": "trans_aruite",
                "title": "On Foot",
                "type": "text",
                "question": "Type the romaji for 歩いて (on foot / walking):",
                "options": [],
                "answer": "aruite",
                "hints": [
                    "歩く (aruku) means 'to walk'. This is the te-form.",
                    "Think: a-ru-i-te.",
                ],
                "xp": 30,
                "lesson": "歩いて (あるいて / aruite) = on foot / by walking. Te-form of 歩く (aruku). Example: 歩いて十分です (aruite juppun desu) = It's ten minutes on foot. 歩いて行けますか (aruite ikemasu ka) = Can I walk there?",
                "is_boss": False,
                "flavor": "Umi sets off on foot along a coastal trail.",
            },
            {
                "id": "trans_noru",
                "title": "To Ride / Board",
                "type": "quiz",
                "question": "乗る (のる / noru) means what?",
                "options": ["To walk", "To ride / board", "To arrive", "To depart"],
                "answer": "b",
                "hints": [
                    "You do this to get on a train, bus, or taxi.",
                    "The particle に is used: バスに乗る.",
                ],
                "xp": 25,
                "lesson": "乗る (のる / noru) = to ride, to board, to get on. Pattern: [transport] に乗る. Example: 電車に乗ります (densha ni norimasu) = I'll ride the train. Opposite: 降りる (oriru) = to get off.",
                "is_boss": False,
                "flavor": "Umi hops aboard a ferry heading across the bay.",
            },
            {
                "id": "trans_jikan",
                "title": "How Long?",
                "type": "quiz",
                "question": "どのくらいかかりますか (dono kurai kakarimasu ka) means what?",
                "options": ["How much does it cost?", "How long does it take?", "How far is it?", "What time is it?"],
                "answer": "b",
                "hints": [
                    "かかる (kakaru) can mean 'to take (time)' or 'to cost'.",
                    "どのくらい asks 'how much/how long'.",
                ],
                "xp": 25,
                "lesson": "どのくらいかかりますか (dono kurai kakarimasu ka) = How long does it take? A vital travel question. Answer pattern: [time] くらいかかります. Example: 三十分くらいかかります (sanjuppun kurai kakarimasu) = It takes about 30 minutes.",
                "is_boss": False,
                "flavor": "Umi checks a tide chart, calculating travel time.",
            },
            {
                "id": "trans_made",
                "title": "To / Until",
                "type": "quiz",
                "question": "〜まで (~made) means what?",
                "options": ["From ~", "To / Until ~", "Near ~", "Around ~"],
                "answer": "b",
                "hints": [
                    "This particle marks the endpoint of a journey.",
                    "Pair it with から (kara = from) for 'from ~ to ~'.",
                ],
                "xp": 25,
                "lesson": "まで (made) = to, until, as far as. Example: 駅までお願いします (eki made onegaishimasu) = To the station, please (in a taxi). Pair: 〜から〜まで (kara ~ made) = from ~ to ~.",
                "is_boss": False,
                "flavor": "Umi traces a route on the map from harbor to station.",
            },
            {
                "id": "transportation_boss",
                "title": "Travel Planner",
                "type": "quiz",
                "question": "How do you say 'How long does it take to the station by train?'",
                "options": [
                    "駅まで電車でどのくらいかかりますか (eki made densha de dono kurai kakarimasu ka)",
                    "電車は駅にどこですか (densha wa eki ni doko desu ka)",
                    "駅から電車に乗りますか (eki kara densha ni norimasu ka)",
                    "電車で駅までいくらですか (densha de eki made ikura desu ka)",
                ],
                "answer": "a",
                "hints": [
                    "まで = to (destination), で = by (means of transport), どのくらいかかりますか = how long does it take.",
                    "Pattern: [destination] まで [transport] で どのくらいかかりますか.",
                ],
                "xp": 35,
                "lesson": "駅まで電車でどのくらいかかりますか combines destination (まで), transport method (で), and the time question. Pattern: [place] まで [method] で どのくらいかかりますか. Master this and you can plan any trip in Japan!",
                "is_boss": True,
                "flavor": "Umi stands at the platform, timetable in hand, ready for departure.",
            },
        ],
    },

    # -- Zone 5: Describing Locations -------------------------------------------
    "describing_locations": {
        "id": "describing_locations",
        "name": "Describing Locations",
        "description": "Learn position words: 隣, 前, 後ろ, 近く, 遠い and spatial descriptions",
        "level_required": 17,
        "challenges": [
            {
                "id": "loc_tonari",
                "title": "Next To",
                "type": "quiz",
                "question": "隣 (となり / tonari) means what?",
                "options": ["In front of", "Next to / beside", "Behind", "Inside"],
                "answer": "b",
                "hints": [
                    "This describes something right beside something else.",
                    "Think of neighbors -- 隣 is also used in お隣さん (neighbor).",
                ],
                "xp": 25,
                "lesson": "隣 (となり / tonari) = next to, beside, neighboring. Example: 銀行は郵便局の隣です (ginkou wa yuubinkyoku no tonari desu) = The bank is next to the post office. Pattern: A は B の隣です.",
                "is_boss": False,
                "flavor": "Umi stands between two seaside shops, arms stretched wide.",
            },
            {
                "id": "loc_mae",
                "title": "In Front Of",
                "type": "text",
                "question": "Type the romaji for 前 (in front of / before):",
                "options": [],
                "answer": "mae",
                "hints": [
                    "This is a single syllable word: ma-e.",
                    "駅前 (ekimae) means 'in front of the station'.",
                ],
                "xp": 30,
                "lesson": "前 (まえ / mae) = in front of, before. Example: 駅の前にバス停があります (eki no mae ni basutei ga arimasu) = There's a bus stop in front of the station. 駅前 (ekimae) = station front area.",
                "is_boss": False,
                "flavor": "Umi stands at the front of a lighthouse, facing the open sea.",
            },
            {
                "id": "loc_ushiro",
                "title": "Behind",
                "type": "quiz",
                "question": "後ろ (うしろ / ushiro) means what?",
                "options": ["Above", "Below", "Behind", "Between"],
                "answer": "c",
                "hints": [
                    "This is the opposite of 前 (mae / in front).",
                    "Think of what's at your back.",
                ],
                "xp": 25,
                "lesson": "後ろ (うしろ / ushiro) = behind, back. Example: 学校の後ろに公園があります (gakkou no ushiro ni kouen ga arimasu) = There's a park behind the school. Pattern: A の後ろに B があります.",
                "is_boss": False,
                "flavor": "Umi peeks behind a sand dune to find a hidden cove.",
            },
            {
                "id": "loc_chikaku",
                "title": "Nearby",
                "type": "text",
                "question": "Type the romaji for 近く (nearby):",
                "options": [],
                "answer": "chikaku",
                "hints": [
                    "近い (chikai) means 'close/near'. This is the noun form.",
                    "Think: chi-ka-ku.",
                ],
                "xp": 30,
                "lesson": "近く (ちかく / chikaku) = nearby, vicinity. From 近い (chikai) = near/close. Example: この近くにコンビニはありますか (kono chikaku ni konbini wa arimasu ka) = Is there a convenience store nearby?",
                "is_boss": False,
                "flavor": "Umi notices a cafe just steps away from the harbor wall.",
            },
            {
                "id": "loc_tooi",
                "title": "Far",
                "type": "quiz",
                "question": "遠い (とおい / tooi) means what?",
                "options": ["Near", "Far", "Wide", "Deep"],
                "answer": "b",
                "hints": [
                    "This is the opposite of 近い (chikai / near).",
                    "The double 'o' makes it a long vowel: too-i.",
                ],
                "xp": 25,
                "lesson": "遠い (とおい / tooi) = far, distant. Opposite of 近い (chikai). Example: 空港は遠いですか (kuukou wa tooi desu ka) = Is the airport far? 遠くない (tooku nai) = not far.",
                "is_boss": False,
                "flavor": "Umi gazes at a distant island shimmering on the horizon.",
            },
            {
                "id": "loc_arimasu",
                "title": "There Is / Exists",
                "type": "quiz",
                "question": "あります (arimasu) is used for what?",
                "options": ["Existence of living things", "Existence of non-living things", "Actions", "Descriptions"],
                "answer": "b",
                "hints": [
                    "For living things (people, animals), you use います (imasu) instead.",
                    "Buildings, objects, and places use this verb.",
                ],
                "xp": 25,
                "lesson": "あります (arimasu) = there is / exists (for non-living things). For living things: います (imasu). Example: 銀行は駅の隣にあります (ginkou wa eki no tonari ni arimasu) = The bank is next to the station.",
                "is_boss": False,
                "flavor": "Umi points out all the landmarks visible from the hilltop.",
            },
            {
                "id": "loc_aida",
                "title": "Between",
                "type": "text",
                "question": "Type the romaji for 間 (between / interval):",
                "options": [],
                "answer": "aida",
                "hints": [
                    "This kanji also reads as 'ma' in other words like 時間 (jikan).",
                    "Think: a-i-da.",
                ],
                "xp": 30,
                "lesson": "間 (あいだ / aida) = between, interval. Example: 銀行は郵便局と病院の間にあります (ginkou wa yuubinkyoku to byouin no aida ni arimasu) = The bank is between the post office and the hospital.",
                "is_boss": False,
                "flavor": "Umi stands in the gap between two tall rocks on the beach.",
            },
            {
                "id": "describing_locations_boss",
                "title": "Location Describer",
                "type": "quiz",
                "question": "How do you say 'The bank is next to the station, in front of the park'?",
                "options": [
                    "銀行は駅の隣で、公園の前にあります (ginkou wa eki no tonari de, kouen no mae ni arimasu)",
                    "駅は銀行の前で、公園の隣です (eki wa ginkou no mae de, kouen no tonari desu)",
                    "公園の後ろに銀行と駅があります (kouen no ushiro ni ginkou to eki ga arimasu)",
                    "銀行は遠くて、駅の近くにあります (ginkou wa tookute, eki no chikaku ni arimasu)",
                ],
                "answer": "a",
                "hints": [
                    "銀行 is the topic. It's next to (隣) the station and in front of (前) the park.",
                    "The で connects two location descriptions.",
                ],
                "xp": 35,
                "lesson": "銀行は駅の隣で、公園の前にあります combines two positional descriptions. The pattern [A の隣で, B の前にあります] elegantly describes a location relative to two landmarks. This is how Japanese people naturally give location descriptions!",
                "is_boss": True,
                "flavor": "Umi draws a detailed map of the town, marking every landmark with care.",
            },
        ],
    },
}
