"""
zones.py — Colors & Clothing zones and challenges.

Mix of quiz and text challenges covering colors, shades, clothing items,
describing outfits, and shopping for clothes in Spanish.
Guided by Carmen, a stylish personal shopper in a vibrant Spanish market.
"""

ZONE_ORDER = [
    "basic_colors",
    "more_colors_shades",
    "clothing_items",
    "describing_what_you_wear",
    "shopping_for_clothes",
]

ZONES = {
    # -- Zone 1: Basic Colors --
    "basic_colors": {
        "id": "basic_colors",
        "name": "Basic Colors",
        "description": "Learn the essential colors in Spanish",
        "level_required": 1,
        "challenges": [
            {
                "id": "color_rojo",
                "title": "Red",
                "type": "quiz",
                "question": "What is the Spanish word for 'red'?",
                "options": ["Azul", "Rojo", "Verde", "Amarillo"],
                "answer": "b",
                "hints": ["Think of the color of roses and fire.", "It starts with 'R'."],
                "xp": 25,
                "lesson": "'Rojo' means red. Like all Spanish color adjectives, it changes with gender: 'rojo' (masculine) and 'roja' (feminine). El coche rojo (the red car), la rosa roja (the red rose).",
            },
            {
                "id": "color_azul",
                "title": "Blue",
                "type": "quiz",
                "question": "How do you say 'blue' in Spanish?",
                "options": ["Azul", "Blanco", "Negro", "Verde"],
                "answer": "a",
                "hints": ["It sounds a bit like the English word 'azure'.", "The sky and ocean share this color."],
                "xp": 25,
                "lesson": "'Azul' means blue. Unlike most adjectives, 'azul' does NOT change for gender -- it's 'azul' for both masculine and feminine: el cielo azul (the blue sky), la camisa azul (the blue shirt). The plural is 'azules'.",
            },
            {
                "id": "color_verde",
                "title": "Green",
                "type": "quiz",
                "question": "The Spanish word for 'green' is:",
                "options": ["Rojo", "Amarillo", "Verde", "Blanco"],
                "answer": "c",
                "hints": ["Think of grass, trees, and nature.", "It's the same root as 'verdant' in English."],
                "xp": 25,
                "lesson": "'Verde' means green. Like 'azul', it does not change for gender: el arbol verde (the green tree), la rana verde (the green frog). Fun fact: 'verde' can also informally mean 'unripe' when talking about fruit!",
            },
            {
                "id": "color_amarillo",
                "title": "Yellow",
                "type": "quiz",
                "question": "What color is 'amarillo' in English?",
                "options": ["Orange", "Yellow", "Brown", "Gold"],
                "answer": "b",
                "hints": ["Think of the sun and sunflowers.", "It's a bright, warm color."],
                "xp": 25,
                "lesson": "'Amarillo' means yellow. It changes with gender: 'amarillo' (masculine), 'amarilla' (feminine). El sol amarillo (the yellow sun), la flor amarilla (the yellow flower). Remember the double 'l' is pronounced like a 'y' sound!",
            },
            {
                "id": "color_blanco",
                "title": "White",
                "type": "text",
                "question": "Type the Spanish word for 'white':",
                "options": [],
                "answer": "blanco",
                "hints": ["Think of 'blank' in English -- they share the same root.", "Snow and clouds are this color."],
                "xp": 25,
                "lesson": "'Blanco' means white. It changes with gender: 'blanco' (masculine), 'blanca' (feminine). Casablanca literally means 'white house'! El gato blanco (the white cat), la nieve blanca (the white snow).",
            },
            {
                "id": "color_negro",
                "title": "Black",
                "type": "quiz",
                "question": "How do you say 'the black cat' in Spanish?",
                "options": ["El gato blanco", "El gato negro", "El gato rojo", "El gato azul"],
                "answer": "b",
                "hints": ["'Negro' means black.", "In Spanish, the adjective comes AFTER the noun."],
                "xp": 25,
                "lesson": "'Negro' means black. Like 'rojo', it changes: 'negro' (masculine), 'negra' (feminine). El cafe negro (black coffee), la noche negra (the black night). Note: In Spanish, color adjectives typically follow the noun.",
            },
            {
                "id": "color_adjective_placement",
                "title": "Where Colors Go",
                "type": "quiz",
                "question": "In Spanish, where do color adjectives usually go relative to the noun?",
                "options": ["Before the noun", "After the noun", "Either position", "They replace the noun"],
                "answer": "b",
                "hints": ["Unlike English, Spanish puts descriptions after what they describe.", "'The red car' becomes 'the car red' in Spanish word order."],
                "xp": 30,
                "lesson": "In Spanish, color adjectives come AFTER the noun: 'el coche rojo' (the red car), not 'el rojo coche.' This is the opposite of English! Most adjectives in Spanish follow the noun. Remember: Noun first, color second.",
            },
            {
                "id": "color_gender_agreement",
                "title": "Colors Must Agree",
                "type": "quiz",
                "question": "'La casa ___' -- which form of 'white' correctly completes this phrase?",
                "options": ["blanco", "blanca", "blancos", "blancas"],
                "answer": "b",
                "hints": ["'Casa' is feminine (la casa).", "The color must match the gender of the noun."],
                "xp": 35,
                "lesson": "Colors ending in -o change to -a for feminine nouns: rojo/roja, blanco/blanca, negro/negra, amarillo/amarilla. Colors ending in -e or a consonant (verde, azul, gris) stay the same for both genders. Gender agreement is key!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 2: More Colors & Shades --
    "more_colors_shades": {
        "id": "more_colors_shades",
        "name": "More Colors & Shades",
        "description": "Expand your palette with more colors and learn light/dark",
        "level_required": 1,
        "challenges": [
            {
                "id": "color_morado",
                "title": "Purple",
                "type": "quiz",
                "question": "What is the Spanish word for 'purple'?",
                "options": ["Morado", "Naranja", "Rosa", "Gris"],
                "answer": "a",
                "hints": ["Think of 'mora' which means blackberry in Spanish.", "Grapes and eggplants are this color."],
                "xp": 25,
                "lesson": "'Morado' means purple. It comes from 'mora' (blackberry/mulberry). It changes with gender: morado/morada. You may also hear 'purpura' or 'violeta', but 'morado' is the most common in everyday speech.",
            },
            {
                "id": "color_naranja",
                "title": "Orange",
                "type": "quiz",
                "question": "'Naranja' in Spanish refers to both the color orange and:",
                "options": ["The sunset", "The fruit orange", "A type of flower", "A spice"],
                "answer": "b",
                "hints": ["The color is named after a fruit.", "You can eat it and drink its juice."],
                "xp": 25,
                "lesson": "'Naranja' means both the color orange and the fruit orange! As a color, it often does NOT change for gender: la camisa naranja, el coche naranja. Some speakers do say 'anaranjado/anaranjada' as the adjective form.",
            },
            {
                "id": "color_rosa",
                "title": "Pink",
                "type": "text",
                "question": "Type the Spanish word for 'pink':",
                "options": [],
                "answer": "rosa",
                "hints": ["It's the same as the word for a certain flower.", "Think of the flower known for Valentine's Day."],
                "xp": 25,
                "lesson": "'Rosa' means pink (and also 'rose' the flower). As a color, it typically does NOT change for gender: el vestido rosa, la falda rosa. For emphasis, you can say 'rosado/rosada' which does change with gender.",
            },
            {
                "id": "color_gris",
                "title": "Gray",
                "type": "quiz",
                "question": "On a cloudy day, the sky is 'gris.' What color is that?",
                "options": ["Blue", "White", "Gray", "Silver"],
                "answer": "c",
                "hints": ["Think of clouds on a rainy day.", "It's between black and white."],
                "xp": 25,
                "lesson": "'Gris' means gray. Like 'azul', it does not change for gender: el gato gris, la pared gris. The plural is 'grises'. Fun fact: 'pelo gris' (gray hair) is sometimes called 'canas' in everyday Spanish.",
            },
            {
                "id": "color_oscuro",
                "title": "Dark Shades",
                "type": "quiz",
                "question": "How do you say 'dark blue' in Spanish?",
                "options": ["Azul claro", "Azul oscuro", "Azul fuerte", "Azul grande"],
                "answer": "b",
                "hints": ["'Oscuro' means dark.", "The color comes first, then the shade modifier."],
                "xp": 30,
                "lesson": "'Oscuro' means dark. Place it after the color: azul oscuro (dark blue), verde oscuro (dark green), rojo oscuro (dark red). The pattern is always [color] + oscuro. 'Oscuro' can also mean 'dark' in general, as in 'una noche oscura' (a dark night).",
            },
            {
                "id": "color_claro",
                "title": "Light Shades",
                "type": "text",
                "question": "How do you say 'light green' in Spanish? (two words)",
                "options": [],
                "answer": "verde claro",
                "hints": ["'Claro' means light or clear.", "The color word comes first."],
                "xp": 30,
                "lesson": "'Claro' means light (as in a shade) or clear. Verde claro (light green), azul claro (light blue), rosa claro (light pink). When used with colors, 'claro' and 'oscuro' do not change for gender: la camisa verde claro, el pantalon azul claro.",
            },
            {
                "id": "color_marron",
                "title": "Brown",
                "type": "quiz",
                "question": "What is the most common Spanish word for the color 'brown'?",
                "options": ["Cafe", "Marron", "Castano", "All of the above are used"],
                "answer": "d",
                "hints": ["Spanish has several words for brown depending on the region.", "Think of coffee, chestnuts, and chocolate."],
                "xp": 30,
                "lesson": "Brown has multiple words in Spanish! 'Marron' is common in Spain, 'cafe' in Latin America, and 'castano' specifically for hair and eyes. All are correct! 'Marron' and 'cafe' don't change for gender. Ojos castanos = brown eyes.",
            },
            {
                "id": "color_shades_boss",
                "title": "Describe the Rainbow",
                "type": "quiz",
                "question": "Which of these correctly describes a 'light purple shirt' in Spanish?",
                "options": ["Una camisa morado claro", "Una camisa morada clara", "Una camisa morada claro", "Una camisa claro morada"],
                "answer": "a",
                "hints": ["When a color has a modifier like 'claro' or 'oscuro', the whole phrase becomes invariable.", "The color + modifier combination does not change for gender."],
                "xp": 35,
                "lesson": "Important rule: When a color is modified by 'claro' or 'oscuro', the entire color phrase becomes invariable (does not change for gender or number). So it's 'una camisa morado claro' NOT 'morada clara.' This applies to all compound color descriptions!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 3: Clothing Items --
    "clothing_items": {
        "id": "clothing_items",
        "name": "Clothing Items",
        "description": "Learn the names of common clothing in Spanish",
        "level_required": 2,
        "challenges": [
            {
                "id": "cloth_camisa",
                "title": "Shirt",
                "type": "quiz",
                "question": "What is the Spanish word for 'shirt'?",
                "options": ["Pantalon", "Camisa", "Vestido", "Falda"],
                "answer": "b",
                "hints": ["It's a cognate -- it sounds similar to an English word.", "Think of 'camisole' in English."],
                "xp": 25,
                "lesson": "'La camisa' means shirt. It's feminine (la camisa). A T-shirt is 'la camiseta.' Fun fact: 'camisa' and the English 'chemise' share the same Latin root! Una camisa blanca = a white shirt.",
            },
            {
                "id": "cloth_pantalon",
                "title": "Pants",
                "type": "text",
                "question": "Type the Spanish word for 'pants' (singular form, include the accent):",
                "options": [],
                "answer": "pantalon",
                "hints": ["It sounds like 'pantaloon' in English.", "Don't forget -- it has an accent on the last syllable."],
                "xp": 25,
                "lesson": "'El pantalon' means pants (singular in Spanish, unlike English!). The plural 'los pantalones' is also commonly used. It's masculine: el pantalon negro (the black pants). 'Pantalones cortos' = shorts, 'pantalones vaqueros' or 'jeans' = jeans.",
            },
            {
                "id": "cloth_vestido",
                "title": "Dress",
                "type": "quiz",
                "question": "'El vestido' means:",
                "options": ["Vest", "Dress", "Suit", "Skirt"],
                "answer": "b",
                "hints": ["It comes from 'vestir' meaning 'to dress/to wear'.", "It's NOT the same as the English 'vest'."],
                "xp": 25,
                "lesson": "'El vestido' means dress (the garment). It comes from the verb 'vestir' (to dress). Be careful: it's a false friend -- it does NOT mean 'vest'! A vest is 'un chaleco' in Spanish. Un vestido rojo = a red dress.",
            },
            {
                "id": "cloth_zapatos",
                "title": "Shoes",
                "type": "quiz",
                "question": "You're going shoe shopping. What are you looking for?",
                "options": ["Sombreros", "Zapatos", "Guantes", "Calcetines"],
                "answer": "b",
                "hints": ["'Zapatero' is a shoemaker.", "Think of 'zapateado' -- a style of dance focused on footwork."],
                "xp": 25,
                "lesson": "'Los zapatos' means shoes. One shoe = 'el zapato.' Related vocabulary: zapatillas (sneakers/slippers), botas (boots), sandalias (sandals), tacones (heels), zapatos de tenis (tennis shoes). Un par de zapatos = a pair of shoes.",
            },
            {
                "id": "cloth_sombrero",
                "title": "Hat",
                "type": "quiz",
                "question": "'Sombrero' literally relates to the word 'sombra.' What does 'sombra' mean?",
                "options": ["Head", "Sun", "Shadow/shade", "Style"],
                "answer": "c",
                "hints": ["A sombrero protects you from the sun by creating...", "Think about what a hat does on a sunny day."],
                "xp": 25,
                "lesson": "'El sombrero' means hat. It comes from 'sombra' (shadow/shade) because a hat creates shade! Other headwear: gorra (cap/baseball hat), boina (beret). 'Sombrero' in English refers to a specific wide-brimmed hat, but in Spanish it means any hat.",
            },
            {
                "id": "cloth_falda_chaqueta",
                "title": "Skirt & Jacket",
                "type": "quiz",
                "question": "Match: 'la falda' and 'la chaqueta' are:",
                "options": ["Skirt and jacket", "Dress and coat", "Blouse and scarf", "Belt and tie"],
                "answer": "a",
                "hints": ["'Falda' also means 'hillside' in some contexts.", "'Chaqueta' sounds like 'jacket'."],
                "xp": 30,
                "lesson": "'La falda' = skirt, 'la chaqueta' = jacket. More clothing: el abrigo (coat), la bufanda (scarf), los guantes (gloves), los calcetines (socks), la corbata (tie), el cinturon (belt), la blusa (blouse).",
            },
            {
                "id": "cloth_ropa",
                "title": "Clothes / Clothing",
                "type": "text",
                "question": "What is the general Spanish word for 'clothes' or 'clothing'?",
                "options": [],
                "answer": "ropa",
                "hints": ["It's a short, simple word.", "A clothing store is a 'tienda de ___'."],
                "xp": 25,
                "lesson": "'La ropa' means clothes/clothing (always singular in Spanish!). 'Tienda de ropa' = clothing store. 'Ropa interior' = underwear. 'Ropa de cama' = bedding. Unlike English, 'ropa' is never pluralized -- you say 'la ropa' not 'las ropas.'",
            },
            {
                "id": "cloth_items_boss",
                "title": "Getting Dressed",
                "type": "quiz",
                "question": "Which list contains ONLY clothing items in Spanish?",
                "options": ["camisa, zapatos, mesa, sombrero", "pantalon, vestido, falda, chaqueta", "rojo, azul, verde, amarillo", "sombrero, camisa, cuchara, zapatos"],
                "answer": "b",
                "hints": ["Look for a list with no non-clothing words.", "'Mesa' means table and 'cuchara' means spoon."],
                "xp": 35,
                "lesson": "Your clothing vocabulary so far: camisa (shirt), camiseta (T-shirt), pantalon (pants), vestido (dress), zapatos (shoes), sombrero (hat), falda (skirt), chaqueta (jacket), abrigo (coat), calcetines (socks). You're ready to describe any outfit!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 4: Describing What You Wear --
    "describing_what_you_wear": {
        "id": "describing_what_you_wear",
        "name": "Describing What You Wear",
        "description": "Use llevar and poner with adjective agreement to describe outfits",
        "level_required": 2,
        "challenges": [
            {
                "id": "desc_llevar",
                "title": "Llevar = To Wear",
                "type": "quiz",
                "question": "'Ella lleva una camisa azul' means:",
                "options": ["She carries a blue shirt", "She wears a blue shirt", "She buys a blue shirt", "She wants a blue shirt"],
                "answer": "b",
                "hints": ["'Llevar' has multiple meanings including 'to carry' and 'to wear'.", "In the context of clothing, it means to wear."],
                "xp": 25,
                "lesson": "'Llevar' means 'to wear' when talking about clothing. Yo llevo (I wear), tu llevas (you wear), el/ella lleva (he/she wears). 'Llevar' also means 'to carry' or 'to take,' but with clothing it always means 'to wear.'",
            },
            {
                "id": "desc_ponerse",
                "title": "Ponerse = To Put On",
                "type": "quiz",
                "question": "'Me pongo la chaqueta' means:",
                "options": ["I take off the jacket", "I buy the jacket", "I put on the jacket", "I like the jacket"],
                "answer": "c",
                "hints": ["'Poner' means 'to put.' 'Ponerse' is reflexive -- to put on oneself.", "'Me pongo' = I put on (myself)."],
                "xp": 25,
                "lesson": "'Ponerse' (reflexive) means 'to put on' clothing. Me pongo (I put on), te pones (you put on), se pone (he/she puts on). The opposite is 'quitarse' (to take off): 'Me quito los zapatos' (I take off my shoes).",
            },
            {
                "id": "desc_agreement_masc",
                "title": "Masculine Agreement",
                "type": "text",
                "question": "Complete: 'El sombrero ___' (the black hat). Type just the color word:",
                "options": [],
                "answer": "negro",
                "hints": ["'Sombrero' is masculine (el sombrero).", "The masculine form of black ends in -o."],
                "xp": 25,
                "lesson": "With masculine nouns, use the masculine color form: el sombrero negro (the black hat), el vestido rojo (the red dress -- vestido is masculine!), el pantalon blanco (the white pants). Always check the noun's gender, not the item's stereotype!",
            },
            {
                "id": "desc_agreement_fem",
                "title": "Feminine Agreement",
                "type": "quiz",
                "question": "How do you say 'the white blouse'?",
                "options": ["La blusa blanco", "La blusa blanca", "El blusa blanco", "La blusa blancos"],
                "answer": "b",
                "hints": ["'Blusa' is feminine (la blusa).", "The color must match: feminine singular."],
                "xp": 25,
                "lesson": "With feminine nouns, colors ending in -o change to -a: la blusa blanca (the white blouse), la falda roja (the red skirt), la chaqueta negra (the black jacket). Colors like azul, verde, gris stay the same: la camisa azul.",
            },
            {
                "id": "desc_agreement_plural",
                "title": "Plural Colors",
                "type": "quiz",
                "question": "How do you say 'the red shoes'?",
                "options": ["Los zapatos rojo", "Los zapatos rojas", "Los zapatos rojos", "Los zapatos roja"],
                "answer": "c",
                "hints": ["'Zapatos' is masculine plural (los zapatos).", "The color must be masculine plural too."],
                "xp": 30,
                "lesson": "For plural nouns, colors become plural too: los zapatos rojos (red shoes), las camisas blancas (white shirts), los calcetines grises (gray socks), las faldas azules (blue skirts). Match both gender AND number!",
            },
            {
                "id": "desc_full_outfit",
                "title": "Describe a Full Outfit",
                "type": "quiz",
                "question": "Which sentence correctly describes someone's outfit?",
                "options": ["Llevo una camisa blanco y pantalones negro.", "Llevo una camisa blanca y pantalones negros.", "Llevo un camisa blanca y pantalon negros.", "Llevo una camisa blancos y pantalones negras."],
                "answer": "b",
                "hints": ["'Camisa' is feminine, 'pantalones' is masculine plural.", "Each color must agree with its own noun."],
                "xp": 30,
                "lesson": "'Llevo una camisa blanca y pantalones negros' -- each adjective agrees with its own noun independently. Camisa (fem.) -> blanca. Pantalones (masc. pl.) -> negros. Always check each noun-adjective pair separately!",
            },
            {
                "id": "desc_tener_puesto",
                "title": "Another Way to Say 'Wearing'",
                "type": "quiz",
                "question": "'Tengo puesto un vestido verde' means:",
                "options": ["I have a green dress", "I'm wearing a green dress", "I want a green dress", "I bought a green dress"],
                "answer": "b",
                "hints": ["'Tener puesto' is another way to express wearing clothes.", "'Puesto' comes from 'poner' (to put)."],
                "xp": 30,
                "lesson": "'Tener puesto' is another way to say 'to be wearing' -- literally 'to have put on.' 'Tengo puesto un vestido verde' = I'm wearing a green dress. Three ways to say 'wearing': llevar, tener puesto, vestir. 'Llevar' is the most common.",
            },
            {
                "id": "desc_outfit_boss",
                "title": "Fashion Show",
                "type": "text",
                "question": "Translate to Spanish: 'She wears a red dress' (start with 'Ella lleva'):",
                "options": [],
                "answer": "Ella lleva un vestido rojo",
                "hints": ["'Vestido' is masculine (el vestido).", "The color must agree with vestido, not with 'ella'."],
                "xp": 35,
                "lesson": "'Ella lleva un vestido rojo' -- even though 'ella' is feminine, 'vestido' is masculine, so the color stays 'rojo' not 'roja.' The color always agrees with the NOUN it describes, not the person wearing it. This is a very common mistake!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 5: Shopping for Clothes --
    "shopping_for_clothes": {
        "id": "shopping_for_clothes",
        "name": "Shopping for Clothes",
        "description": "Buy clothes in Spanish -- prices, sizes, and trying things on",
        "level_required": 3,
        "challenges": [
            {
                "id": "shop_cuanto_cuesta",
                "title": "How Much Does It Cost?",
                "type": "quiz",
                "question": "To ask 'How much does it cost?' in Spanish, you say:",
                "options": ["Donde esta?", "Cuanto cuesta?", "Que es esto?", "Como se llama?"],
                "answer": "b",
                "hints": ["'Cuanto' means 'how much', 'cuesta' means 'it costs'.", "This is the most essential shopping phrase."],
                "xp": 25,
                "lesson": "'Cuanto cuesta?' (How much does it cost?) is your #1 shopping phrase. For multiple items: 'Cuanto cuestan?' (How much do they cost?). The verb 'costar' means 'to cost' -- it's a stem-changing verb: cuesta/cuestan.",
            },
            {
                "id": "shop_cuanto_cuestan",
                "title": "How Much Do They Cost?",
                "type": "text",
                "question": "You want to ask the price of multiple shoes. Type the question in Spanish (include the question marks: Cuanto...):",
                "options": [],
                "answer": "Cuanto cuestan?",
                "hints": ["For plural items, 'cuesta' becomes 'cuestan'.", "Start with 'Cuanto' and use the plural verb form."],
                "xp": 25,
                "lesson": "'Cuanto cuestan?' uses the plural form for multiple items. 'Cuanto cuesta la camisa?' (How much does the shirt cost?) vs 'Cuanto cuestan los zapatos?' (How much do the shoes cost?). Match the verb to singular or plural!",
            },
            {
                "id": "shop_talla",
                "title": "What's Your Size?",
                "type": "quiz",
                "question": "'Que talla usa?' means:",
                "options": ["What color do you want?", "What size do you wear?", "What style do you prefer?", "What brand is it?"],
                "answer": "b",
                "hints": ["'Talla' means size (for clothing).", "'Usa' comes from 'usar' (to use/wear)."],
                "xp": 25,
                "lesson": "'La talla' is the clothing size. 'Que talla usa/usas?' = What size do you wear? Common responses: talla pequena (small), talla mediana (medium), talla grande (large). You can also say 'Soy talla M' (I'm a size M). For shoes, use 'numero' instead: 'Que numero calza?'",
            },
            {
                "id": "shop_probarse",
                "title": "Can I Try It On?",
                "type": "quiz",
                "question": "'Puedo probarme esto?' means:",
                "options": ["Can I buy this?", "Can I try this on?", "Can I return this?", "Can I see this?"],
                "answer": "b",
                "hints": ["'Probarse' means 'to try on' (reflexive).", "'Puedo' = Can I."],
                "xp": 30,
                "lesson": "'Probarse' means 'to try on.' 'Puedo probarme esto?' (Can I try this on?). 'El probador' or 'el vestidor' = the fitting room. 'Donde esta el probador?' (Where is the fitting room?). Essential shopping vocabulary!",
            },
            {
                "id": "shop_queda",
                "title": "How Does It Fit?",
                "type": "quiz",
                "question": "'Me queda grande' means:",
                "options": ["I like it a lot", "It fits me perfectly", "It's too big on me", "It looks great on me"],
                "answer": "c",
                "hints": ["'Quedar' means 'to fit' when talking about clothes.", "'Grande' means big/large."],
                "xp": 30,
                "lesson": "'Quedar' describes how clothes fit: 'Me queda grande' (It's too big on me), 'Me queda pequeno' (It's too small), 'Me queda bien' (It fits well), 'Me queda perfecto' (It fits perfectly). 'Quedar' is like 'gustar' -- it uses indirect object pronouns.",
            },
            {
                "id": "shop_lo_llevo",
                "title": "I'll Take It!",
                "type": "quiz",
                "question": "You've found the perfect shirt. To say 'I'll take it!' you say:",
                "options": ["Lo quiero!", "Me lo llevo!", "Lo compro!", "All of these work"],
                "answer": "d",
                "hints": ["There are several ways to express this in Spanish.", "All three options are commonly used when buying something."],
                "xp": 25,
                "lesson": "To say you'll buy something: 'Me lo llevo!' (I'll take it! -- most common), 'Lo compro' (I'll buy it), 'Lo quiero' (I want it). For feminine items: 'Me la llevo!' For plural: 'Me los/las llevo!' Match the pronoun to the item.",
            },
            {
                "id": "shop_regatear",
                "title": "Bargaining",
                "type": "quiz",
                "question": "'Me puede hacer un descuento?' means:",
                "options": ["Can you wrap it for me?", "Can you give me a discount?", "Can you show me another one?", "Can you hold it for me?"],
                "answer": "b",
                "hints": ["'Descuento' means discount.", "'Hacer un descuento' = to give a discount."],
                "xp": 30,
                "lesson": "'Me puede hacer un descuento?' (Can you give me a discount?) is useful in markets and small shops. Other useful phrases: 'Es muy caro' (It's very expensive), 'Tiene algo mas barato?' (Do you have something cheaper?), 'Es mi ultima oferta' (It's my final offer).",
            },
            {
                "id": "shop_boss",
                "title": "At the Tienda de Ropa",
                "type": "quiz",
                "question": "Put this shopping conversation in order: 1) Me lo llevo! 2) Cuanto cuesta esta camisa? 3) Puedo probarme la talla mediana? 4) Cuesta veinte euros.",
                "options": ["2, 4, 3, 1", "1, 2, 3, 4", "3, 2, 4, 1", "2, 3, 4, 1"],
                "answer": "a",
                "hints": ["First ask the price, then hear the answer, then try it on, then buy.", "The natural flow of a shopping interaction."],
                "xp": 35,
                "lesson": "A natural shopping conversation: Ask the price (Cuanto cuesta?) -> Hear the price (Cuesta...) -> Try it on (Puedo probarme...?) -> Buy it (Me lo llevo!). You now have all the phrases to shop for clothes in any Spanish-speaking country!",
                "is_boss": True,
            },
        ],
    },
}
