"""
zones.py — Pinyin zones and challenges.

All challenges use "type": "quiz" with multiple-choice options.
Guided by Long Long (龙龙), a friendly dragon.
"""

ZONE_ORDER = [
    "tones",
    "initials",
    "finals",
    "pinyin_reading",
    "common_sounds",
    "tones_in_context",
    "pinyin_typing",
    "pinyin_vs_english",
]

ZONES = {
    # ── Zone 1: Tones ───────────────────────────────────────────────
    "tones": {
        "id": "tones",
        "name": "The Four Tones",
        "description": "Master the four tones of Mandarin plus the neutral tone",
        "level_required": 1,
        "challenges": [
            {
                "id": "tone_first",
                "title": "The High Flat Tone",
                "type": "quiz",
                "question": "The first tone (ˉ) in Mandarin is described as:",
                "options": ["Rising from low to high", "High and flat, like singing a steady note", "Falling from high to low", "Dipping down then rising"],
                "answer": "b",
                "hints": [
                    "Think of holding one musical note without going up or down.",
                    "It stays at the top of your vocal range the entire time.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The first tone (ˉ) is high and flat. Your voice stays at a steady high pitch, like singing and holding one note. Example: mā (妈) means 'mother'. The tone mark is a flat line above the vowel.",
                "is_boss": False,
                "flavor": "Long Long hums a single, steady, high note. Smoke rings float out in a perfectly straight line.",
            },
            {
                "id": "tone_second",
                "title": "The Rising Tone",
                "type": "quiz",
                "question": "Which tone rises from middle pitch to high pitch, like asking a surprised 'what?!' in English?",
                "options": ["First tone", "Second tone", "Third tone", "Fourth tone"],
                "answer": "b",
                "hints": [
                    "Think of how your voice goes UP when you ask 'Really?' in English.",
                    "The tone mark for this one looks like a rising slash: /",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The second tone (/) rises from middle to high, like asking a surprised question in English. Example: má (麻) means 'hemp/numb'. The tone mark looks like a slash going upward.",
                "is_boss": False,
                "flavor": "Long Long's voice swoops upward like a bird taking flight.",
            },
            {
                "id": "tone_third",
                "title": "The Dipping Tone",
                "type": "quiz",
                "question": "The third tone in Mandarin:",
                "options": ["Stays high and flat", "Rises sharply", "Dips down then rises back up", "Drops from high to low"],
                "answer": "c",
                "hints": [
                    "This tone goes DOWN first, then comes back UP -- like a little valley.",
                    "The tone mark looks like a check mark or a small v shape.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The third tone (v) dips down to a low pitch then rises back up. It's the longest tone. Example: mǎ (马) means 'horse'. The tone mark looks like a v or a small curved dip.",
                "is_boss": False,
                "flavor": "Long Long's voice dips down into a valley, then climbs back up the other side.",
            },
            {
                "id": "tone_fourth",
                "title": "The Falling Tone",
                "type": "quiz",
                "question": "Which tone falls sharply from high to low, like giving a firm command?",
                "options": ["First tone", "Second tone", "Third tone", "Fourth tone"],
                "answer": "d",
                "hints": [
                    "Think of how you say 'Stop!' or 'No!' -- your voice drops quickly.",
                    "The tone mark looks like a falling slash: \\",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The fourth tone (\\) falls sharply from high to low, like a stern command. Example: mà (骂) means 'to scold'. It's short and decisive. The tone mark looks like a downward slash.",
                "is_boss": False,
                "flavor": "Long Long barks a sharp, commanding sound. Even the scroll flinches!",
            },
            {
                "id": "tone_neutral",
                "title": "The Quiet Tone",
                "type": "quiz",
                "question": "The neutral tone (also called the fifth tone or light tone) is:",
                "options": ["Always the loudest syllable", "Short, light, and unstressed", "Always rising", "Used only in questions"],
                "answer": "b",
                "hints": [
                    "It has no tone mark above it in pinyin.",
                    "Think of the second syllable in 'mama' -- it's soft and quick.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The neutral tone is short, light, and unstressed. It has no tone mark. Example: ma (吗) is a question particle. In māma (妈妈, 'mom'), the second ma is neutral -- soft and quick after the strong first tone.",
                "is_boss": False,
                "flavor": "Long Long whispers so softly you have to lean in to hear.",
            },
            {
                "id": "tone_ma_meaning",
                "title": "The Four Ma's",
                "type": "quiz",
                "question": "The syllable 'ma' with the THIRD tone (mǎ) means:",
                "options": ["Mother", "Hemp/numb", "Horse", "To scold"],
                "answer": "c",
                "hints": [
                    "mā = mother, má = hemp, mǎ = ?, mà = scold",
                    "This animal is something you can ride!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The four tones of 'ma' show why tones matter: mā (妈) = mother, má (麻) = hemp/numb, mǎ (马) = horse, mà (骂) = to scold. Same consonant and vowel, completely different meanings!",
                "is_boss": False,
                "flavor": "Long Long lines up four characters that all sound like 'ma' -- but each means something wildly different.",
            },
            {
                "id": "tone_marks_placement",
                "title": "Where Does the Mark Go?",
                "type": "quiz",
                "question": "In pinyin, tone marks are placed above:",
                "options": ["The first letter", "The consonant", "The main vowel", "The last letter"],
                "answer": "c",
                "hints": [
                    "In 'hǎo', the mark is on the a, not the o.",
                    "There's a rule: a and e always get the mark. Otherwise, it goes on the second vowel.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Tone marks go above the main vowel. The rule: if there's an 'a' or 'e', it always gets the mark. Otherwise, the mark goes on the last vowel. So: hǎo (mark on a), méi (mark on e), liú (mark on u).",
                "is_boss": False,
                "flavor": "Long Long carefully places a tiny glowing tone mark above just the right letter.",
            },
            {
                "id": "tone_boss",
                "title": "Tone Master Challenge",
                "type": "quiz",
                "question": "Which pair shows a second tone (rising) followed by a fourth tone (falling)?",
                "options": ["māmā", "máma", "mámà", "mǎmà"],
                "answer": "c",
                "hints": [
                    "Second tone mark is / (rising slash). Fourth tone mark is \\ (falling slash).",
                    "Look for the combination: rising then falling.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Reading tone marks fluently is essential. má (rising /) + mà (falling \\) = mámà. Being able to quickly identify tone marks in sequence is a key skill for reading pinyin text.",
                "is_boss": True,
                "flavor": "Long Long's eyes glow gold. 'Show me you can read tone marks at a glance!'",
            },
        ],
    },

    # ── Zone 2: Initials ────────────────────────────────────────────
    "initials": {
        "id": "initials",
        "name": "The Opening Sounds",
        "description": "Learn every initial consonant in Mandarin",
        "level_required": 2,
        "challenges": [
            {
                "id": "initials_bpmf",
                "title": "The Lip Sounds",
                "type": "quiz",
                "question": "Which group of Mandarin initials are all made with the lips?",
                "options": ["d, t, n, l", "b, p, m, f", "g, k, h", "j, q, x"],
                "answer": "b",
                "hints": [
                    "Try saying each one -- which group uses your lips?",
                    "These are called labial sounds. They're similar to English.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "b, p, m, f are labial initials (made with the lips). They're very similar to English: b as in 'boy', p as in 'pie', m as in 'mom', f as in 'fun'. These are the easiest initials for English speakers!",
                "is_boss": False,
                "flavor": "Long Long puffs four little smoke letters from between dragon lips: b, p, m, f.",
            },
            {
                "id": "initials_dtnl",
                "title": "The Tongue-Tip Sounds",
                "type": "quiz",
                "question": "The initials d, t, n, l are made with:",
                "options": ["The lips", "The tip of the tongue touching behind the upper teeth", "The back of the tongue", "The sides of the tongue"],
                "answer": "b",
                "hints": [
                    "Say 'd' slowly. Where does your tongue touch?",
                    "These are similar to the English sounds d, t, n, l.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "d, t, n, l are tongue-tip initials. Your tongue tip touches the ridge behind your upper teeth. They sound close to English: d as in 'done', t as in 'top', n as in 'no', l as in 'love'.",
                "is_boss": False,
                "flavor": "Long Long flicks a forked tongue against tiny teeth to demonstrate: d, t, n, l.",
            },
            {
                "id": "initials_gkh",
                "title": "The Back-of-Throat Sounds",
                "type": "quiz",
                "question": "The Mandarin initial 'h' is different from English 'h' because it's:",
                "options": ["Silent", "Stronger and more guttural, made in the back of the throat", "Exactly the same as English h", "Made with the lips"],
                "answer": "b",
                "hints": [
                    "Think of a stronger, scratchier h sound.",
                    "It's made further back in the throat than the English h.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "g, k, h are velar initials (back of the throat). g and k are similar to English, but Mandarin 'h' is rougher and more guttural than English h -- more like the 'ch' in Scottish 'loch' or German 'Bach'.",
                "is_boss": False,
                "flavor": "Long Long makes a gravelly sound deep in the dragon's throat. 'Like this -- from way back!'",
            },
            {
                "id": "initials_jqx",
                "title": "The Palatal Sounds",
                "type": "quiz",
                "question": "The Mandarin 'q' is pronounced most similarly to:",
                "options": ["English 'k' as in 'queen'", "English 'ch' as in 'cheese' but lighter", "English 'g' as in 'go'", "English 'sh' as in 'shoe'"],
                "answer": "b",
                "hints": [
                    "Forget everything you know about the letter q from English!",
                    "It's a light, breathy 'ch' sound with the tongue near the palate.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "j, q, x are palatal initials -- unique to Chinese! j sounds like 'j' in 'jeep' but softer. q sounds like 'ch' in 'cheese' but lighter and breathier. x sounds like 'sh' in 'she' but with the tongue more forward. These only pair with i and u with umlaut.",
                "is_boss": False,
                "flavor": "Long Long makes three delicate sounds, tongue pressed flat against the roof of the mouth.",
            },
            {
                "id": "initials_zhchshr",
                "title": "The Retroflex Sounds",
                "type": "quiz",
                "question": "What makes zh, ch, sh, r 'retroflex' sounds?",
                "options": ["The tongue curls backward", "They are whispered", "They use the lips", "They are nasal sounds"],
                "answer": "a",
                "hints": [
                    "The word 'retroflex' literally means 'bent backward'.",
                    "Your tongue tip curls up and back toward the roof of your mouth.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "zh, ch, sh, r are retroflex initials -- your tongue curls backward. zh is like 'j' in 'judge' with a curled tongue. ch is like 'ch' in 'church' with a curled tongue. sh is like 'sh' in 'shirt'. r is unique -- like a mix of English 'r' and 'zh'.",
                "is_boss": False,
                "flavor": "Long Long curls the dragon tongue backward in an exaggerated demonstration.",
            },
            {
                "id": "initials_zcs",
                "title": "The Flat Tongue Sounds",
                "type": "quiz",
                "question": "How do z, c, s differ from zh, ch, sh?",
                "options": ["They are louder", "The tongue is flat and forward, not curled back", "They are the same sounds", "They use the lips"],
                "answer": "b",
                "hints": [
                    "z, c, s are called 'flat tongue' while zh, ch, sh are 'curled tongue'.",
                    "For z, c, s your tongue tip touches behind your lower teeth.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "z, c, s are flat-tongue (dental) initials. Unlike zh, ch, sh (where the tongue curls back), for z, c, s the tongue stays flat and forward. z sounds like 'dz' in 'kids'. c sounds like 'ts' in 'cats'. s is like English 's'.",
                "is_boss": False,
                "flavor": "Long Long places the tongue flat. 'No curling! Keep it forward!'",
            },
            {
                "id": "initials_boss",
                "title": "Initial Sounds Boss",
                "type": "quiz",
                "question": "Which initial does NOT exist in Mandarin Chinese?",
                "options": ["zh", "v", "q", "x"],
                "answer": "b",
                "hints": [
                    "Think about which letter is never used as a Mandarin initial.",
                    "Mandarin has 21 initials. This letter is used in pinyin only for foreign words.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Mandarin has 21 initials: b, p, m, f, d, t, n, l, g, k, h, j, q, x, zh, ch, sh, r, z, c, s. The letter 'v' is NOT a Mandarin initial -- it's sometimes used on keyboards as a shortcut for u with umlaut, but it's not an official initial.",
                "is_boss": True,
                "flavor": "Long Long arranges all 21 initials in a glowing circle. 'One of these options is an impostor!'",
            },
        ],
    },

    # ── Zone 3: Finals ──────────────────────────────────────────────
    "finals": {
        "id": "finals",
        "name": "The Vowel Melodies",
        "description": "Learn simple, compound, and nasal finals",
        "level_required": 3,
        "challenges": [
            {
                "id": "finals_simple_a",
                "title": "The Open Mouth Sound",
                "type": "quiz",
                "question": "The Mandarin final 'a' is pronounced like:",
                "options": ["'a' in 'cat'", "'a' in 'father' -- open and wide", "'a' in 'cake'", "'a' in 'about'"],
                "answer": "b",
                "hints": [
                    "Open your mouth wide, like a doctor asking you to say 'aah'.",
                    "It's a broad, open vowel -- not short like in 'cat'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Mandarin 'a' sounds like the 'a' in 'father' -- mouth open wide, tongue flat. It's one of the six simple finals: a, o, e, i, u, u with umlaut. Each one is a pure, clean vowel sound.",
                "is_boss": False,
                "flavor": "Long Long opens wide: 'Ahhh! Like the doctor says!'",
            },
            {
                "id": "finals_special_e",
                "title": "The Strange E",
                "type": "quiz",
                "question": "The Mandarin 'e' (when alone, not in a combination) sounds most like:",
                "options": ["English 'e' in 'bed'", "English 'a' in 'above'", "A sound like 'uh' with the mouth half-open, unrounded", "English 'ee' in 'see'"],
                "answer": "c",
                "hints": [
                    "It's NOT like any common English 'e' sound.",
                    "Try saying 'uh' but with your mouth more open and your tongue pulled back.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Mandarin 'e' alone is tricky! It's like a deep 'uh' sound with the mouth half-open. Your lips are NOT rounded. It sounds a bit like the 'u' in English 'but' but more open. This trips up many English speakers!",
                "is_boss": False,
                "flavor": "Long Long makes a sound that's not quite any English vowel. 'This one takes practice!'",
            },
            {
                "id": "finals_u_umlaut",
                "title": "The Mysterious U with Dots",
                "type": "quiz",
                "question": "How do you pronounce the Mandarin u with umlaut (the u with two dots above it)?",
                "options": ["Same as English 'oo' in 'food'", "Say 'ee' but round your lips like 'oo'", "Same as 'u' in 'but'", "Same as 'ew' in 'few'"],
                "answer": "b",
                "hints": [
                    "Try saying 'ee' (as in 'see') and then, without changing your tongue, round your lips into an 'oo' shape.",
                    "It exists in French (the 'u' in 'tu') and German (the 'u' with umlaut in 'uber').",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The u with umlaut is made by saying 'ee' (tongue position for 'ee') while rounding your lips (lip position for 'oo'). It's like French 'tu' or German 'uber'. It appears after j, q, x, and l/n. After j, q, x the dots are dropped: ju, qu, xu.",
                "is_boss": False,
                "flavor": "Long Long purses dragon lips into a perfect circle while making an 'ee' sound inside.",
            },
            {
                "id": "finals_compound_ai_ei",
                "title": "The Gliding Vowels",
                "type": "quiz",
                "question": "The compound final 'ai' sounds like:",
                "options": ["'ai' in 'air'", "'i' in 'ice' -- like English 'eye'", "'ay' in 'say'", "'a' in 'about'"],
                "answer": "b",
                "hints": [
                    "It starts with an 'a' sound and glides into an 'i' sound.",
                    "Think of the English word 'eye' or 'I'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Compound finals combine two vowels into a smooth glide. 'ai' sounds like 'eye' (a glides to i). 'ei' sounds like 'ay' in 'say' (e glides to i). These are common in everyday words like mai (buy) and mei (beautiful).",
                "is_boss": False,
                "flavor": "Long Long lets two vowel sounds slide together smoothly, like colors blending.",
            },
            {
                "id": "finals_compound_ao_ou",
                "title": "The Round Glides",
                "type": "quiz",
                "question": "The compound final 'ou' sounds like:",
                "options": ["'ou' in 'out'", "'oo' in 'food'", "'oh' in 'go' -- like English 'o'", "'ow' in 'cow'"],
                "answer": "c",
                "hints": [
                    "It starts with 'o' and glides toward 'u'.",
                    "Think of the 'o' sound in 'boat' or 'go'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "'ao' sounds like 'ow' in 'how' (a glides to o). 'ou' sounds like 'oh' in 'go' (o glides to u). Examples: hao (good), dou (all/both). Notice that 'ao' has the 'ow' sound, NOT 'ou'!",
                "is_boss": False,
                "flavor": "Long Long rounds the dragon mouth, letting the sound glide from open to closed.",
            },
            {
                "id": "finals_nasal_an_en",
                "title": "The -n Endings",
                "type": "quiz",
                "question": "What's the difference between the finals 'an' and 'ang'?",
                "options": ["They sound exactly the same", "'an' ends with tongue tip on the ridge behind teeth; 'ang' ends with the back of the tongue raised", "'an' is louder than 'ang'", "'ang' is always in the fourth tone"],
                "answer": "b",
                "hints": [
                    "Say 'an' slowly -- where does your tongue end up? Now say 'ang'.",
                    "'an' has a front nasal ending (tongue tip up). 'ang' has a back nasal ending (tongue back up).",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Nasal finals end in -n (front nasal: tongue tip touches the ridge) or -ng (back nasal: back of tongue rises). This distinction is crucial! an vs ang, en vs eng, in vs ing all mean different things. Example: wan (ten thousand) vs wang (king).",
                "is_boss": False,
                "flavor": "Long Long hums, alternating between a front 'nnn' and a back 'nggg'. 'Feel the difference!'",
            },
            {
                "id": "finals_boss",
                "title": "Finals Master Challenge",
                "type": "quiz",
                "question": "How many simple finals (single vowels) does Mandarin have?",
                "options": ["4", "5", "6", "7"],
                "answer": "c",
                "hints": [
                    "Count them: a, o, e, i, u, and one more special one...",
                    "Don't forget the u with umlaut!",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Mandarin has 6 simple finals: a, o, e, i, u, and u with umlaut. These combine to form compound finals (ai, ei, ao, ou, etc.) and nasal finals (an, en, ang, eng, etc.). Together there are about 36 finals in standard Mandarin.",
                "is_boss": True,
                "flavor": "Long Long arranges six glowing vowels in a circle. 'The foundation of every Chinese syllable!'",
            },
        ],
    },

    # ── Zone 4: Pinyin Reading ──────────────────────────────────────
    "pinyin_reading": {
        "id": "pinyin_reading",
        "name": "Reading Pinyin",
        "description": "Combine initials + finals + tones into complete syllables",
        "level_required": 4,
        "challenges": [
            {
                "id": "reading_structure",
                "title": "The Shape of a Syllable",
                "type": "quiz",
                "question": "A complete Mandarin pinyin syllable consists of:",
                "options": ["Only a consonant", "Only a vowel", "An optional initial + a final + a tone", "Three consonants"],
                "answer": "c",
                "hints": [
                    "Some syllables have no initial (like 'ai'), but all have a final and a tone.",
                    "The structure is: (initial) + final + tone.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A Mandarin syllable = optional initial + required final + tone. For example: 'ma' has initial 'm' + final 'a' + a tone. Some syllables have no initial: 'ai' (love) is just a final + tone. Every syllable must have a tone!",
                "is_boss": False,
                "flavor": "Long Long draws a diagram in smoke: [initial] + [final] + [tone] = one syllable.",
            },
            {
                "id": "reading_nihao",
                "title": "Your First Word",
                "type": "quiz",
                "question": "The pinyin 'ni hao' (你好) is made up of how many syllables?",
                "options": ["One", "Two", "Three", "Four"],
                "answer": "b",
                "hints": [
                    "Each Chinese character corresponds to one syllable.",
                    "ni = one syllable, hao = one syllable.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "In Chinese, each character is exactly one syllable. 'ni hao' (你好, hello) has two characters, so two syllables: ni (you) + hao (good). Spaces in pinyin separate words, not syllables. Multi-character words are written together: nihao.",
                "is_boss": False,
                "flavor": "Long Long carefully separates the two syllables with a claw. 'ni... hao. Two beats!'",
            },
            {
                "id": "reading_boundaries",
                "title": "Where Syllables Split",
                "type": "quiz",
                "question": "In 'xi'an' (西安, the city Xi'an), what is the apostrophe for?",
                "options": ["It's a decoration", "It shows where one syllable ends and the next begins", "It means the word is a name", "It indicates a tone change"],
                "answer": "b",
                "hints": [
                    "Without the apostrophe, 'xian' would be read as one syllable.",
                    "The apostrophe separates 'xi' and 'an' into two distinct syllables.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The apostrophe in pinyin separates syllables that could be misread. 'xian' = one syllable (meaning 'first'). 'xi'an' = two syllables (the city name). The apostrophe appears before a, o, e when they start a new syllable after another syllable.",
                "is_boss": False,
                "flavor": "Long Long points to the tiny mark. 'Small but mighty -- this apostrophe changes everything!'",
            },
            {
                "id": "reading_no_initial",
                "title": "Syllables Without Initials",
                "type": "quiz",
                "question": "Some pinyin syllables start with a vowel (no initial). Which of these has NO initial consonant?",
                "options": ["hao", "mai", "ai", "lai"],
                "answer": "c",
                "hints": [
                    "An initial is a consonant at the start. Which option starts with a vowel?",
                    "'ai' starts directly with the vowel 'a'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Some syllables have no initial -- they start directly with a vowel. Examples: ai (love), ou (Europe), en (grace). When written, some get a 'y' or 'w' added: i becomes yi, u becomes wu, u with umlaut becomes yu. This is a spelling convention, not a new sound.",
                "is_boss": False,
                "flavor": "Long Long points to the bare vowel. 'No consonant needed -- the vowel stands alone!'",
            },
            {
                "id": "reading_yi_wu_yu",
                "title": "The Y and W Rule",
                "type": "quiz",
                "question": "When the final 'i' appears as a syllable by itself (no initial), it's written as:",
                "options": ["Just 'i'", "yi", "wi", "hi"],
                "answer": "b",
                "hints": [
                    "A 'y' is added to the front when 'i' stands alone.",
                    "Similarly, 'u' alone becomes 'wu'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When certain finals stand alone, y or w is added: i -> yi, in -> yin, u -> wu. When u with umlaut stands alone, it becomes yu (and the dots are dropped). These are spelling rules only -- the actual sound doesn't change.",
                "is_boss": False,
                "flavor": "Long Long puts a little 'y' hat on the letter 'i'. 'Now it can go out on its own!'",
            },
            {
                "id": "reading_boss",
                "title": "Pinyin Reading Boss",
                "type": "quiz",
                "question": "How would you break 'zhuangshi' into syllables?",
                "options": ["zhu-ang-shi", "zhuan-gshi", "zhuang-shi", "zh-uang-shi"],
                "answer": "c",
                "hints": [
                    "Each syllable starts with an initial and ends with a complete final.",
                    "'zhuang' is initial 'zh' + final 'uang'. 'shi' is initial 'sh' + final 'i'.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Breaking pinyin into syllables: identify the initial, then the complete final. 'zhuangshi' = zhuang (zh + uang) + shi (sh + i). The key is recognizing valid finals: 'uang' is a real final, so 'zhuang' is one syllable. Practice makes this automatic!",
                "is_boss": True,
                "flavor": "Long Long presents a long pinyin string. 'Cut it into syllables -- like slicing a dragon roll!'",
            },
        ],
    },

    # ── Zone 5: Common Sounds ───────────────────────────────────────
    "common_sounds": {
        "id": "common_sounds",
        "name": "High-Frequency Sounds",
        "description": "Practice the most useful syllables in everyday Chinese",
        "level_required": 5,
        "challenges": [
            {
                "id": "common_shi",
                "title": "The Versatile Shi",
                "type": "quiz",
                "question": "The syllable 'shi' appears in many common words. Which of these does 'shi' (是, fourth tone) mean?",
                "options": ["Ten", "To be / is / am / are", "Stone", "To eat"],
                "answer": "b",
                "hints": [
                    "This is one of the most common words in Chinese -- used in almost every sentence.",
                    "It's similar to the English verb 'to be'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "shi (是, fourth tone) means 'to be' and is one of the most common Chinese words. But 'shi' with different tones gives different meanings: shi (十, second tone) = ten, shi (石, second tone) = stone, shi (事, fourth tone) = matter/thing. Tones matter!",
                "is_boss": False,
                "flavor": "Long Long writes one syllable that means dozens of different things. 'Tones are everything!'",
            },
            {
                "id": "common_de",
                "title": "The Little Word De",
                "type": "quiz",
                "question": "The particle 'de' (的) is the single most common syllable in Chinese. What does it do?",
                "options": ["It means 'the'", "It shows possession, like English 's or 'of'", "It means 'and'", "It means 'not'"],
                "answer": "b",
                "hints": [
                    "wo de = my (literally 'I + de'). It connects a possessor to what they possess.",
                    "Think of it like the English word 'of' or the apostrophe-s.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "的 (de, neutral tone) is the most common word in Chinese. It shows possession: wo de (我的) = my/mine, ni de (你的) = your/yours. It also links descriptions to nouns: hong de hua (红的花) = red flower. You'll see it everywhere!",
                "is_boss": False,
                "flavor": "Long Long holds up the tiniest, most common character in all of Chinese.",
            },
            {
                "id": "common_bu",
                "title": "The Negator Bu",
                "type": "quiz",
                "question": "What does 'bu' (不) mean in Chinese?",
                "options": ["Yes", "Not / no (negation)", "And", "But"],
                "answer": "b",
                "hints": [
                    "Put it before a verb to negate it: bu shi = is not.",
                    "It's the most basic way to say 'no' or 'not' in Chinese.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "不 (bu, fourth tone normally) means 'not'. Place it before verbs or adjectives to negate them: bu shi (不是) = is not, bu hao (不好) = not good, bu yao (不要) = don't want. It's one of the first words every Chinese learner needs.",
                "is_boss": False,
                "flavor": "Long Long shakes the dragon head. 'Bu! Bu! The power of saying no!'",
            },
            {
                "id": "common_le",
                "title": "The Change Marker Le",
                "type": "quiz",
                "question": "The particle 'le' (了) is used to indicate:",
                "options": ["A question", "A completed action or change of state", "Possession", "Politeness"],
                "answer": "b",
                "hints": [
                    "wo chi le = I ate (the eating is completed).",
                    "It signals that something has changed or been completed.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "了 (le, neutral tone) is a particle that marks completed actions or changes in state. 'wo chi le' (我吃了) = I ate. 'xia yu le' (下雨了) = it started raining (change of state). Le is tricky even for advanced learners -- but learning its basics early helps a lot.",
                "is_boss": False,
                "flavor": "Long Long snaps a claw. 'Done! Finished! Changed! That's what le tells you.'",
            },
            {
                "id": "common_ren",
                "title": "People and Person",
                "type": "quiz",
                "question": "The syllable 'ren' (人, second tone) means:",
                "options": ["Hot", "Person / people", "Sun", "Day"],
                "answer": "b",
                "hints": [
                    "This character looks like a person walking -- two legs spread apart.",
                    "Zhongguo ren = Chinese person.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "人 (ren, second tone) means 'person' or 'people'. It appears in many compound words: Zhongguo ren (中国人) = Chinese person, da ren (大人) = adult, ren men (人们) = people (plural). The character 人 is one of the simplest -- just two strokes like a walking figure.",
                "is_boss": False,
                "flavor": "Long Long traces the character 人 in the air -- two simple strokes like tiny legs.",
            },
            {
                "id": "common_boss",
                "title": "Common Sounds Boss",
                "type": "quiz",
                "question": "Which syllable is the most frequently occurring in Mandarin Chinese text?",
                "options": ["shi", "de", "ren", "bu"],
                "answer": "b",
                "hints": [
                    "This particle appears in almost every sentence.",
                    "It shows possession and links descriptions to nouns.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "的 (de) is statistically the most common syllable/word in Chinese, appearing in roughly 4% of all text. It's followed by words like 是 (shi), 不 (bu), 了 (le), and 我 (wo). Mastering these high-frequency words gives you a huge head start in reading Chinese!",
                "is_boss": True,
                "flavor": "Long Long displays a frequency chart. 'Know the common words and you understand half of everything!'",
            },
        ],
    },

    # ── Zone 6: Tones in Context ────────────────────────────────────
    "tones_in_context": {
        "id": "tones_in_context",
        "name": "Tone Sandhi",
        "description": "How tones change when syllables meet",
        "level_required": 6,
        "challenges": [
            {
                "id": "sandhi_third_third",
                "title": "The Third Tone Rule",
                "type": "quiz",
                "question": "When two third tones appear in a row, the first one changes to:",
                "options": ["First tone", "Second tone", "Fourth tone", "Neutral tone"],
                "answer": "b",
                "hints": [
                    "ni + hao: both are third tone. But you don't actually say two dipping tones.",
                    "The first syllable rises instead of dipping -- it sounds like a second tone.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Third tone sandhi: when two third tones meet, the first becomes a second tone. ni (3rd) + hao (3rd) is pronounced as ni (2nd) + hao (3rd). But the pinyin still writes 'ni hao' with third tone marks! The change is in speech only, not in writing.",
                "is_boss": False,
                "flavor": "Long Long demonstrates: two dipping tones in a row sounds awkward. 'So Chinese fixes it automatically!'",
            },
            {
                "id": "sandhi_bu_rule",
                "title": "The Bu Rule",
                "type": "quiz",
                "question": "不 (bu) is normally fourth tone, but changes to second tone when followed by:",
                "options": ["A first tone", "A second tone", "A third tone", "Another fourth tone"],
                "answer": "d",
                "hints": [
                    "Two falling tones in a row is hard to say.",
                    "bu + a fourth tone word = bu changes to second tone.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "不 (bu) is normally fourth tone (bu). But before another fourth tone, it changes to second tone: bu shi (不是) is actually pronounced bu (2nd) shi (4th). Before tones 1, 2, and 3, bu stays fourth tone. This is the bu tone sandhi rule.",
                "is_boss": False,
                "flavor": "Long Long says 'bu' in two different tones. 'Hear how it changes before a falling tone?'",
            },
            {
                "id": "sandhi_yi_rule",
                "title": "The Yi Rule",
                "type": "quiz",
                "question": "一 (yi, normally first tone) changes to which tone before a fourth tone word?",
                "options": ["Stays first tone", "Second tone", "Third tone", "Neutral tone"],
                "answer": "b",
                "hints": [
                    "The yi rule is similar to the bu rule before fourth tones.",
                    "yi + fourth tone = yi changes to second tone.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "一 (yi, 'one') has special tone rules: before a 4th tone, yi becomes 2nd tone (yi ge). Before 1st, 2nd, or 3rd tones, yi becomes 4th tone (yi tian). When counting or at the end of a word, yi stays 1st tone. It's the most tone-changeable word in Chinese!",
                "is_boss": False,
                "flavor": "Long Long holds up one claw. 'One little number, three different tones depending on context!'",
            },
            {
                "id": "sandhi_yi_before_others",
                "title": "Yi Before Other Tones",
                "type": "quiz",
                "question": "What tone does 一 (yi) become before a FIRST tone word (like tian, meaning sky)?",
                "options": ["First tone", "Second tone", "Third tone", "Fourth tone"],
                "answer": "d",
                "hints": [
                    "Before first, second, and third tones, yi changes the same way.",
                    "Before tones 1, 2, 3: yi becomes fourth tone. Before tone 4: yi becomes second tone.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Full yi tone rules: yi + 4th tone -> yi (2nd tone). yi + 1st/2nd/3rd tone -> yi (4th tone). yi alone or when counting -> yi (1st tone). Example: yi tian (一天, one day) = yi (4th) tian (1st). yi ge (一个, one [measure word]) = yi (2nd) ge (4th).",
                "is_boss": False,
                "flavor": "Long Long writes out a rule table in golden flame.",
            },
            {
                "id": "sandhi_three_thirds",
                "title": "Three Third Tones in a Row",
                "type": "quiz",
                "question": "When three third tones appear in a row (like 'wo xiang mai'), how do the tones change?",
                "options": ["All stay third tone", "All become second tone", "The first two become second tone, the last stays third", "Only the middle one changes"],
                "answer": "c",
                "hints": [
                    "The rule applies in sequence: the last third tone 'anchors' and the ones before it shift.",
                    "Think of it as: 2-2-3 when speaking naturally.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "With three consecutive third tones, typically the first two change to second tone: wo (2nd) xiang (2nd) mai (3rd). But grouping matters -- in longer phrases, meaning and phrasing determine which tones change. Context is king in tone sandhi!",
                "is_boss": False,
                "flavor": "Long Long lines up three dipping tones. 'Watch what happens when they meet...'",
            },
            {
                "id": "sandhi_boss",
                "title": "Tone Sandhi Boss",
                "type": "quiz",
                "question": "In the phrase 'bu hao' (不好, not good), what tones are actually spoken?",
                "options": ["bu (4th) hao (3rd) -- no change", "bu (2nd) hao (3rd) -- bu changes before 3rd tone", "bu (4th) hao (2nd) -- hao changes", "bu (2nd) hao (2nd) -- both change"],
                "answer": "a",
                "hints": [
                    "Bu only changes before FOURTH tones specifically.",
                    "Hao is third tone, not fourth tone. So does bu change?",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Trick question! Bu only changes to second tone before fourth tones. Since hao (好) is third tone, bu stays as fourth tone. 'bu hao' is pronounced bu (4th) hao (3rd) -- no tone sandhi here! Knowing when rules DON'T apply is just as important as knowing when they do.",
                "is_boss": True,
                "flavor": "Long Long grins. 'Not every tone changes! Knowing the exceptions is true mastery.'",
            },
        ],
    },

    # ── Zone 7: Pinyin Typing ───────────────────────────────────────
    "pinyin_typing": {
        "id": "pinyin_typing",
        "name": "Typing Chinese",
        "description": "How to type pinyin on phones and computers",
        "level_required": 7,
        "challenges": [
            {
                "id": "typing_basics",
                "title": "How Pinyin Input Works",
                "type": "quiz",
                "question": "When typing Chinese with pinyin input, you:",
                "options": ["Draw characters on screen", "Type pinyin letters and choose from character suggestions", "Use a special Chinese keyboard with 3000 keys", "Speak into the microphone only"],
                "answer": "b",
                "hints": [
                    "You use a regular keyboard -- the same one you use for English.",
                    "Type the sounds, then pick the right character from a list.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Pinyin input is the most common way to type Chinese. You type pinyin on a regular keyboard (e.g., type 'nihao') and the computer/phone shows a list of matching characters (你好). You pick the right one. No special keyboard needed!",
                "is_boss": False,
                "flavor": "Long Long taps regular keyboard keys. 'Same keyboard, totally different language!'",
            },
            {
                "id": "typing_phone",
                "title": "Typing on a Phone",
                "type": "quiz",
                "question": "On most smartphones, to type Chinese you need to:",
                "options": ["Buy a special Chinese phone", "Add a Chinese (Pinyin) keyboard in your phone's settings", "Download a special app", "Chinese phones use a different operating system"],
                "answer": "b",
                "hints": [
                    "Both iPhone and Android have built-in Chinese keyboard support.",
                    "Go to Settings > Keyboard > Add Keyboard > Chinese (Pinyin).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Adding Chinese typing to your phone is easy: go to Settings > Keyboard > Add Keyboard > Chinese Simplified (Pinyin). Both iOS and Android support this natively. Once added, you can switch between English and Chinese keyboards with one tap.",
                "is_boss": False,
                "flavor": "Long Long swipes across a tiny glowing phone screen. 'Three taps in Settings and you're ready!'",
            },
            {
                "id": "typing_tones_optional",
                "title": "Do You Need to Type Tones?",
                "type": "quiz",
                "question": "When typing Chinese with pinyin input, do you need to type the tone marks?",
                "options": ["Yes, always", "No -- the system figures out the right character from context", "Only on computers, not phones", "Only for rare characters"],
                "answer": "b",
                "hints": [
                    "Most people just type the letters without any tone marks.",
                    "The input system is smart enough to suggest the right characters.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "You do NOT need to type tone marks! Just type the letters (e.g., 'ma') and the system shows all matching characters (妈, 马, 吗, etc.). You pick the right one. The system also learns your habits and puts your most-used characters first.",
                "is_boss": False,
                "flavor": "Long Long breathes a sigh of relief. 'No tone marks needed when typing -- the computer is smart!'",
            },
            {
                "id": "typing_shortcuts",
                "title": "Typing Shortcuts",
                "type": "quiz",
                "question": "What does typing just the first letter of each syllable (like 'nh' for 'nihao') do in most Chinese input methods?",
                "options": ["It causes an error", "It suggests words that match those initials -- a speed shortcut", "It types in English", "It adds tone marks"],
                "answer": "b",
                "hints": [
                    "This is called 'fuzzy input' or 'abbreviated pinyin'.",
                    "Experienced Chinese typists use this to type much faster.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Most pinyin input methods support abbreviations: type just the first letters of each syllable. 'nh' suggests 你好, 'bkq' suggests 不客气. This lets experienced users type incredibly fast. Combined with predictive text, Chinese typing can be faster than English!",
                "is_boss": False,
                "flavor": "Long Long types two letters and a whole sentence appears. 'Speed comes with practice!'",
            },
            {
                "id": "typing_v_for_u",
                "title": "The V Trick",
                "type": "quiz",
                "question": "When typing pinyin on a standard keyboard, how do you input the u with umlaut (as in 'lv' for 'green')?",
                "options": ["Type 'uu'", "Type 'v' -- it represents u with umlaut on keyboards", "Type 'u' with Shift", "You can't type it"],
                "answer": "b",
                "hints": [
                    "Since 'v' is not used in standard pinyin, keyboards repurpose it.",
                    "To type lu with umlaut (green), you type 'lv'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "On keyboards, 'v' stands in for the u with umlaut since v isn't used in pinyin. To type lu with umlaut (绿, green), type 'lv'. To type nu with umlaut (女, woman), type 'nv'. After j, q, x, just type 'u' -- the system knows it means u with umlaut.",
                "is_boss": False,
                "flavor": "Long Long presses the V key with a claw. 'The secret key for that tricky vowel!'",
            },
            {
                "id": "typing_boss",
                "title": "Typing Boss Challenge",
                "type": "quiz",
                "question": "Which of these is NOT a common Chinese text input method?",
                "options": ["Pinyin input", "Handwriting recognition", "Voice input", "Morse code input"],
                "answer": "d",
                "hints": [
                    "Three of these are widely used on Chinese phones and computers.",
                    "The odd one out is a very old communication system using dots and dashes.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Common Chinese input methods: Pinyin input (most popular), handwriting recognition (draw characters on screen), voice input (dictation), Wubi (shape-based, used by fast typists), and stroke input (enter strokes in order). Morse code is not used for Chinese text input!",
                "is_boss": True,
                "flavor": "Long Long presents four input methods. 'Which one doesn't belong in the modern Chinese toolkit?'",
            },
        ],
    },

    # ── Zone 8: Pinyin vs English ───────────────────────────────────
    "pinyin_vs_english": {
        "id": "pinyin_vs_english",
        "name": "False Friends",
        "description": "Sounds that trick English speakers",
        "level_required": 8,
        "challenges": [
            {
                "id": "false_c",
                "title": "C is Not C",
                "type": "quiz",
                "question": "The Mandarin initial 'c' is pronounced like:",
                "options": ["English 'k' as in 'cat'", "English 's' as in 'city'", "'ts' as in 'cats' -- a sharp hissing sound", "English 'ch' as in 'chair'"],
                "answer": "c",
                "hints": [
                    "Say the word 'cats' and focus on the 'ts' at the end.",
                    "Mandarin c is NEVER like the c in 'cat' or 'city'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Mandarin 'c' = 'ts' sound (like the end of 'cats'). This is one of the biggest false friends! When you see 'cai' in pinyin, say 'tsai', not 'kai' or 'sai'. Other examples: ci = tsuh, cao = tsao, cong = tsoong.",
                "is_boss": False,
                "flavor": "Long Long shakes a claw. 'Forget everything English taught you about the letter C!'",
            },
            {
                "id": "false_q",
                "title": "Q Without U",
                "type": "quiz",
                "question": "In Mandarin pinyin, 'q' sounds most like:",
                "options": ["English 'kw' as in 'queen'", "English 'k' as in 'quick'", "A light 'ch' sound, like 'cheese' said softly", "English 'g' as in 'go'"],
                "answer": "c",
                "hints": [
                    "There is NO 'kw' sound in Mandarin. Forget 'queen'!",
                    "Think of a soft, breathy version of 'ch' in 'cheap'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Mandarin 'q' sounds like a soft, breathy 'ch' (as in 'cheese'). It's NOTHING like English 'q' (which is 'kw'). Examples: qi (chee) = seven, qian (chien) = money/thousand, qu (choo with u umlaut) = go. Q only pairs with i and u with umlaut.",
                "is_boss": False,
                "flavor": "Long Long holds up the letter Q. 'No 'kw' sound here. Throw that English rule away!'",
            },
            {
                "id": "false_x",
                "title": "X Marks the Spot",
                "type": "quiz",
                "question": "The Mandarin initial 'x' sounds like:",
                "options": ["English 'ks' as in 'box'", "English 'z' as in 'xylophone'", "A 'sh' sound but with the tongue more forward, like 'she' said lightly", "English 'h' as in 'hat'"],
                "answer": "c",
                "hints": [
                    "It's similar to 'sh' but lighter and more forward in the mouth.",
                    "Like whispering 'she' very softly.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Mandarin 'x' is like a soft, forward 'sh' -- tongue flat behind the lower teeth, air hissing over it. It's not 'ks' (as in 'box') or 'z' (as in 'xylophone'). Examples: xie (shee-eh) = thanks, xiao (shee-ao) = small, xue (shoo-eh with u umlaut) = study.",
                "is_boss": False,
                "flavor": "Long Long makes a gentle hissing sound. 'Soft as a whisper, not sharp like English x!'",
            },
            {
                "id": "false_r",
                "title": "R is Not R",
                "type": "quiz",
                "question": "The Mandarin initial 'r' differs from English 'r' because:",
                "options": ["It's completely silent", "It's made with the tongue curled back and has a buzzing quality, like a mix of 'r' and 'zh'", "It sounds like 'l'", "It's identical to English r"],
                "answer": "b",
                "hints": [
                    "Curl your tongue back (retroflex position) and make a voiced buzzing sound.",
                    "Some describe it as halfway between English 'r' and French 'j' (as in 'je').",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Mandarin 'r' is retroflex: tongue curled back with a buzzing quality. It sounds like a mix of English 'r' and the 'zh' sound. Some say it's like the 's' in 'measure' or 'pleasure'. Examples: ren (person), ri (day/sun), rou (meat).",
                "is_boss": False,
                "flavor": "Long Long curls that dragon tongue way back. 'Buzz it! Not the English r you know!'",
            },
            {
                "id": "false_iu_ui",
                "title": "IU vs UI",
                "type": "quiz",
                "question": "In Mandarin pinyin, 'iu' (as in 'liu') and 'ui' (as in 'dui') are:",
                "options": ["The same sound", "Different sounds -- iu ends on 'u' sound, ui ends on 'i' sound", "Both pronounced like English 'oo'", "Both pronounced like English 'ee'"],
                "answer": "b",
                "hints": [
                    "Listen to the ENDING of each one. 'iu' ends rounded (u). 'ui' ends sharp (i).",
                    "iu is actually i-o-u (the o is hidden). ui is actually u-e-i (the e is hidden).",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "iu and ui are different! 'iu' (as in liu = six) actually sounds like 'ee-oh-oo' (the o is hidden in spelling). 'ui' (as in dui = correct) actually sounds like 'oo-ay' (the e is hidden). Pay attention to hidden vowels in pinyin!",
                "is_boss": False,
                "flavor": "Long Long swaps two vowels around. 'Order matters! iu and ui are NOT the same!'",
            },
            {
                "id": "false_boss",
                "title": "False Friends Boss",
                "type": "quiz",
                "question": "Which Mandarin pinyin letter is CLOSEST to its English pronunciation?",
                "options": ["c (as in 'ci')", "q (as in 'qi')", "x (as in 'xi')", "s (as in 'si')"],
                "answer": "d",
                "hints": [
                    "Three of these are drastically different from English. One is pretty close.",
                    "Think about which consonant sounds basically the same in both languages.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Mandarin 's' is very close to English 's' -- both are a simple hissing sound. But c (= ts), q (= soft ch), and x (= soft sh) are all drastically different from their English counterparts. When reading pinyin, always remember: the letters look familiar, but the sounds may not be!",
                "is_boss": True,
                "flavor": "Long Long lines up four letters. 'Only one of these sounds like you'd expect from English!'",
            },
        ],
    },
}
