"""
zones.py -- The Puzzle Palace zones and challenges for the Logic skill pack.

5 zones, 8 challenges each (40 total):
  1. Pattern Recognition
  2. Number Sequences
  3. True or False Logic
  4. If-Then Thinking
  5. Brain Teasers

Options are lists; answer letters map to index positions (a=0, b=1, c=2, d=3).
Designed for ages 5-12, guided by Puck.
"""

ZONE_ORDER = [
    "pattern_recognition",
    "number_sequences",
    "true_or_false_logic",
    "if_then_thinking",
    "brain_teasers",
]

ZONES = {
    # ==================================================================
    # ZONE 1 -- Pattern Recognition
    # ==================================================================
    "pattern_recognition": {
        "id": "pattern_recognition",
        "name": "The Pattern Workshop",
        "description": "Spot shapes, colors, and repeating patterns all around you",
        "level_required": 1,
        "challenges": [
            {
                "id": "pr_shape_repeat",
                "title": "Shape Parade",
                "type": "quiz",
                "question": "What comes next? Circle, Square, Circle, Square, Circle, ___",
                "options": [
                    "Triangle",
                    "Square",
                    "Circle",
                    "Star",
                ],
                "answer": "b",
                "hints": [
                    "Two shapes are taking turns.",
                    "After Circle, whose turn is it?",
                ],
                "xp": 20,
                "difficulty": "easy",
                "lesson": "This is an AB repeating pattern. The two shapes take turns: Circle, Square, Circle, Square. After Circle, it is always Square's turn!",
                "is_boss": False,
                "flavor": "Puck juggles a tiny circle and a tiny square. They spin in a perfect loop.",
            },
            {
                "id": "pr_color_pattern",
                "title": "Rainbow Repeat",
                "type": "quiz",
                "question": "Red, Blue, Green, Red, Blue, Green, Red, ___. What color comes next?",
                "options": [
                    "Red",
                    "Green",
                    "Blue",
                    "Yellow",
                ],
                "answer": "c",
                "hints": [
                    "Three colors are repeating in a loop.",
                    "After Red, the pattern starts over: what color is first in the group?",
                ],
                "xp": 20,
                "difficulty": "easy",
                "lesson": "This is an ABC pattern that repeats every three items. After Red the cycle starts over: Blue comes next, then Green, then Red again.",
                "is_boss": False,
                "flavor": "The Primer's page shimmers with bands of Red, Blue, and Green light.",
            },
            {
                "id": "pr_odd_one_out",
                "title": "Odd One Out",
                "type": "quiz",
                "question": "Which one does NOT belong? Apple, Banana, Carrot, Grape",
                "options": [
                    "Apple",
                    "Banana",
                    "Carrot",
                    "Grape",
                ],
                "answer": "c",
                "hints": [
                    "Three of these grow on trees or vines. One grows underground.",
                    "What do Apple, Banana, and Grape have in common?",
                ],
                "xp": 20,
                "difficulty": "easy",
                "lesson": "Apple, Banana, and Grape are all fruits. Carrot is a vegetable, so it does not belong in a group of fruits. Finding the odd one out means looking at what the others have in common.",
                "is_boss": False,
                "flavor": "Puck holds up four tiny illustrations. One of them glows a different color.",
            },
            {
                "id": "pr_mirror_image",
                "title": "Mirror Mirror",
                "type": "quiz",
                "question": "If you fold a butterfly drawing right down the middle, the left wing matches the right wing. What is that called?",
                "options": [
                    "Rotation",
                    "Symmetry",
                    "Repetition",
                    "Translation",
                ],
                "answer": "b",
                "hints": [
                    "Think about what you see in a mirror -- one side matches the other.",
                    "This word starts with S and means 'balanced on both sides.'",
                ],
                "xp": 25,
                "difficulty": "medium",
                "lesson": "Symmetry means one side is a mirror image of the other. Butterflies, leaves, and even your own face are nearly symmetrical!",
                "is_boss": False,
                "flavor": "A butterfly opens its wings on the page. Both sides are perfectly matched.",
            },
            {
                "id": "pr_growing_pattern",
                "title": "Dot Climb",
                "type": "quiz",
                "question": "How many dots come next? 1 dot, 3 dots, 5 dots, 7 dots, ___",
                "options": [
                    "8",
                    "9",
                    "10",
                    "11",
                ],
                "answer": "b",
                "hints": [
                    "Look at how much the number increases each time.",
                    "Each step adds 2 more dots. 7 + 2 = ?",
                ],
                "xp": 25,
                "difficulty": "medium",
                "lesson": "Each step adds 2 more dots than before: 1, 3, 5, 7... so the next number is 7 + 2 = 9. These are called odd numbers, and they form a pattern that grows by 2 every time.",
                "is_boss": False,
                "flavor": "Glowing dots appear on the page, climbing upward like tiny fireflies.",
            },
            {
                "id": "pr_shape_series",
                "title": "Triple Time",
                "type": "quiz",
                "question": "Triangle, Triangle, Square, Triangle, Triangle, Square, Triangle, Triangle, ___",
                "options": [
                    "Triangle",
                    "Circle",
                    "Square",
                    "Star",
                ],
                "answer": "c",
                "hints": [
                    "Count how many shapes appear before the pattern repeats.",
                    "The pattern goes in groups of three: two Triangles and then...",
                ],
                "xp": 25,
                "difficulty": "medium",
                "lesson": "The pattern repeats in groups of three: Triangle, Triangle, Square. After two Triangles, it is always Square's turn. Recognizing the group size is the key!",
                "is_boss": False,
                "flavor": "Shapes march across the page in a neat little parade. Puck conducts them.",
            },
            {
                "id": "pr_letter_pattern",
                "title": "Alphabet Hop",
                "type": "text",
                "question": "What letter comes next? A, C, E, G, ___",
                "options": None,
                "answer": "I",
                "hints": [
                    "Say the alphabet out loud. Which letters are being skipped?",
                    "We are skipping every other letter: A, skip B, C, skip D, E...",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "We are skipping every other letter in the alphabet: A (skip B), C (skip D), E (skip F), G (skip H), I. The pattern adds 2 letters each time.",
                "is_boss": False,
                "flavor": "Letters float off the page and rearrange themselves. Puck chases the missing ones.",
            },
            {
                "id": "pr_complex_pattern",
                "title": "Double Weave",
                "type": "text",
                "question": "Look at this pattern: 1, A, 2, B, 3, C, 4, ___. What comes next?",
                "options": None,
                "answer": "D",
                "hints": [
                    "There are two separate patterns woven together.",
                    "Numbers count up: 1, 2, 3, 4... Letters go in order: A, B, C...",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Two patterns are woven together! The numbers count up (1, 2, 3, 4...) and the letters go in alphabet order (A, B, C, D...). They take turns. After the number 4, the next letter is D.",
                "is_boss": True,
                "flavor": "Numbers and letters dance together on the page, weaving in and out like a braid of gold.",
            },
        ],
    },

    # ==================================================================
    # ZONE 2 -- Number Sequences
    # ==================================================================
    "number_sequences": {
        "id": "number_sequences",
        "name": "The Sequence Staircase",
        "description": "Climb the staircase by cracking number codes and sequences",
        "level_required": 3,
        "challenges": [
            {
                "id": "ns_count_by_three",
                "title": "Skip Counting",
                "type": "quiz",
                "question": "What comes next? 3, 6, 9, 12, ___",
                "options": [
                    "13",
                    "14",
                    "15",
                    "16",
                ],
                "answer": "c",
                "hints": [
                    "How much do you add each time?",
                    "Each number is 3 more than the last. 12 + 3 = ?",
                ],
                "xp": 20,
                "difficulty": "easy",
                "lesson": "This is counting by threes. Each number is 3 more than the one before. You can use this to count groups of things quickly: 3 cookies per plate means 3, 6, 9, 12, 15...",
                "is_boss": False,
                "flavor": "Steps appear on the page, each one three blocks higher than the last.",
            },
            {
                "id": "ns_doubles",
                "title": "Double Trouble",
                "type": "quiz",
                "question": "Each number doubles! 2, 4, 8, 16, ___",
                "options": [
                    "24",
                    "32",
                    "18",
                    "20",
                ],
                "answer": "b",
                "hints": [
                    "Doubling means multiplying by 2.",
                    "16 times 2 equals...?",
                ],
                "xp": 25,
                "difficulty": "medium",
                "lesson": "Doubling means multiplying by 2. 16 x 2 = 32. Doubling grows very fast -- if you folded a piece of paper in half 42 times, it would reach the Moon!",
                "is_boss": False,
                "flavor": "Numbers on the page swell and split, each one birthing a twin.",
            },
            {
                "id": "ns_subtract_pattern",
                "title": "Downward Slide",
                "type": "quiz",
                "question": "What comes next? 50, 45, 40, 35, ___",
                "options": [
                    "25",
                    "32",
                    "30",
                    "28",
                ],
                "answer": "c",
                "hints": [
                    "The numbers are getting smaller. By how much each time?",
                    "Each number goes down by 5. 35 minus 5 = ?",
                ],
                "xp": 25,
                "difficulty": "medium",
                "lesson": "This sequence goes DOWN by 5 each time. Patterns can shrink as well as grow! 35 minus 5 equals 30.",
                "is_boss": False,
                "flavor": "The staircase reverses -- now the numbers slide downward, step by step.",
            },
            {
                "id": "ns_add_increasing",
                "title": "Growing Gaps",
                "type": "quiz",
                "question": "Each time we add one more: 1, 2, 4, 7, 11, ___. What comes next?",
                "options": [
                    "14",
                    "15",
                    "16",
                    "17",
                ],
                "answer": "c",
                "hints": [
                    "Look at the gaps between numbers: 1, 2, 3, 4...",
                    "The gaps keep growing by 1. The next gap is 5, so 11 + 5 = ?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The gap between numbers keeps growing: +1, +2, +3, +4... so the next gap is +5. 11 + 5 = 16. When the rule itself changes each step, look at the differences!",
                "is_boss": False,
                "flavor": "Puck stretches a rubber band between numbers. Each gap is wider than the last.",
            },
            {
                "id": "ns_square_numbers",
                "title": "Perfect Squares",
                "type": "quiz",
                "question": "1, 4, 9, 16, 25, ___. What comes next?",
                "options": [
                    "30",
                    "35",
                    "36",
                    "49",
                ],
                "answer": "c",
                "hints": [
                    "Each number is something times itself: 1x1, 2x2, 3x3...",
                    "5 times 5 is 25. What is 6 times 6?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "These are square numbers! 1x1=1, 2x2=4, 3x3=9, 4x4=16, 5x5=25, 6x6=36. They are called 'square' because you can arrange that many dots into a perfect square shape.",
                "is_boss": False,
                "flavor": "Dots on the page arrange themselves into perfect squares -- bigger and bigger.",
            },
            {
                "id": "ns_fibonacci_easy",
                "title": "Nature's Number",
                "type": "text",
                "question": "Each number is the sum of the two before it: 1, 1, 2, 3, 5, 8, ___",
                "options": None,
                "answer": "13",
                "hints": [
                    "Add the last two numbers together.",
                    "5 + 8 = ?",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "This is the Fibonacci sequence! 5 + 8 = 13. This pattern shows up in sunflower spirals, pinecone bumps, and seashell curves. Nature loves this sequence!",
                "is_boss": False,
                "flavor": "A sunflower blooms on the page. Puck counts its spirals -- they follow the pattern perfectly.",
            },
            {
                "id": "ns_alternating",
                "title": "Two Tracks",
                "type": "text",
                "question": "What comes next? 2, 5, 3, 6, 4, 7, 5, ___",
                "options": None,
                "answer": "8",
                "hints": [
                    "Try looking at every other number separately.",
                    "Odd positions: 2, 3, 4, 5. Even positions: 5, 6, 7, ?",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "There are two sequences woven together! The odd positions go 2, 3, 4, 5 (adding 1) and the even positions go 5, 6, 7, 8 (also adding 1). The next even-position number is 8.",
                "is_boss": False,
                "flavor": "Two lines of numbers march side by side, weaving together like railroad tracks.",
            },
            {
                "id": "ns_times_table_gap",
                "title": "Missing Step",
                "type": "text",
                "question": "Fill in the missing number: 7, 14, ___, 28, 35",
                "options": None,
                "answer": "21",
                "hints": [
                    "Each number is the same amount more than the last.",
                    "These are all multiples of 7. What is 7 times 3?",
                ],
                "xp": 30,
                "difficulty": "hard",
                "lesson": "This is the 7 times table! 7, 14, 21, 28, 35. Each number is 7 more than the last. Recognizing times tables hidden in sequences is a powerful math skill.",
                "is_boss": True,
                "flavor": "A gap yawns in the staircase. Puck peers into the hole. 'What number fills this step?'",
            },
        ],
    },

    # ==================================================================
    # ZONE 3 -- True or False Logic
    # ==================================================================
    "true_or_false_logic": {
        "id": "true_or_false_logic",
        "name": "The Truth Tower",
        "description": "Test statements and discover what is true, false, or tricky",
        "level_required": 5,
        "challenges": [
            {
                "id": "tf_basic_true",
                "title": "Simple Truth",
                "type": "quiz",
                "question": "True or False: All dogs are animals.",
                "options": [
                    "True",
                    "False",
                    "Sometimes",
                    "It depends",
                ],
                "answer": "a",
                "hints": [
                    "Think about every dog you have ever seen. Were any of them NOT animals?",
                    "A dog is always an animal. There are no exceptions.",
                ],
                "xp": 20,
                "difficulty": "easy",
                "lesson": "This is TRUE. Every single dog is an animal. When we say 'all,' we mean every single one with no exceptions. If even one dog were not an animal, the statement would be false.",
                "is_boss": False,
                "flavor": "Puck nods firmly. 'True is true -- no wiggle room!'",
            },
            {
                "id": "tf_basic_false",
                "title": "Not So Fast",
                "type": "quiz",
                "question": "True or False: All birds can fly.",
                "options": [
                    "True",
                    "False",
                    "Only big birds",
                    "Only small birds",
                ],
                "answer": "b",
                "hints": [
                    "Can you think of a bird that cannot fly?",
                    "Penguins are birds. Can penguins fly?",
                ],
                "xp": 20,
                "difficulty": "easy",
                "lesson": "This is FALSE! Penguins, ostriches, and kiwis are all birds that cannot fly. When a statement says 'all,' you only need ONE exception to prove it false.",
                "is_boss": False,
                "flavor": "A penguin waddles across the page. Puck giggles. 'Definitely not flying.'",
            },
            {
                "id": "tf_tricky_some",
                "title": "The Power of Some",
                "type": "quiz",
                "question": "True or False: Some fish live in fresh water.",
                "options": [
                    "True",
                    "False",
                    "All fish do",
                    "No fish do",
                ],
                "answer": "a",
                "hints": [
                    "The word 'some' means 'at least one.'",
                    "Goldfish live in bowls of fresh water. That counts!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "TRUE! The word 'some' is important. It means 'at least one.' Goldfish and trout live in fresh water, so 'some fish live in fresh water' is true, even though other fish live in salt water.",
                "is_boss": False,
                "flavor": "Puck holds up a tiny goldfish. 'Some means at least one. And this little guy counts!'",
            },
            {
                "id": "tf_negation",
                "title": "The NOT Switch",
                "type": "quiz",
                "question": "If 'The sky is blue' is TRUE, what about 'The sky is NOT blue'?",
                "options": [
                    "Also true",
                    "False",
                    "Sometimes true",
                    "We cannot tell",
                ],
                "answer": "b",
                "hints": [
                    "Adding NOT flips the truth value.",
                    "If something is true, its opposite must be...",
                ],
                "xp": 25,
                "difficulty": "medium",
                "lesson": "When a statement is TRUE, its opposite (the negation) is FALSE. Adding 'NOT' flips the truth value. True becomes false, and false becomes true. This is the foundation of logic!",
                "is_boss": False,
                "flavor": "Puck flips a coin. 'True... NOT true... they are always opposites!'",
            },
            {
                "id": "tf_and_logic",
                "title": "The AND Gate",
                "type": "quiz",
                "question": "Is this statement true? 'Cats have fur AND the Moon is made of cheese.'",
                "options": [
                    "True",
                    "False",
                    "Half true",
                    "Depends on the cat",
                ],
                "answer": "b",
                "hints": [
                    "With AND, both parts must be true.",
                    "Is the Moon really made of cheese?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "With AND, BOTH parts must be true for the whole thing to be true. Cats do have fur (true!), but the Moon is NOT made of cheese (false!). True AND False = False.",
                "is_boss": False,
                "flavor": "Puck draws two switches on the page. 'Both must be ON for AND to work!'",
            },
            {
                "id": "tf_or_logic",
                "title": "The OR Gate",
                "type": "quiz",
                "question": "True or False: 'Fish live in water OR fish live on the Moon.'",
                "options": [
                    "True",
                    "False",
                    "Both parts are true",
                    "Neither part is true",
                ],
                "answer": "a",
                "hints": [
                    "With OR, only one part needs to be true.",
                    "Fish DO live in water -- does it matter if the other part is false?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "With OR, only ONE part needs to be true. Fish DO live in water (true!), so the whole statement is true even though fish do NOT live on the Moon. True OR False = True.",
                "is_boss": False,
                "flavor": "Puck draws two switches again. 'With OR, just ONE switch is enough!'",
            },
            {
                "id": "tf_always_never",
                "title": "Always vs. Sometimes",
                "type": "text",
                "question": "Which word makes a statement harder to prove true: 'always' or 'sometimes'?",
                "options": None,
                "answer": "always",
                "hints": [
                    "If you say 'always,' how many exceptions can there be?",
                    "'Sometimes' only needs one example. 'Always' needs every single case.",
                ],
                "xp": 30,
                "difficulty": "hard",
                "lesson": "'Always' means every single time with zero exceptions, so you need to check every case. 'Sometimes' only needs one example to be true. That is why scientists are careful with the word 'always'!",
                "is_boss": False,
                "flavor": "Puck underlines the word 'always' in red. 'This word is very, very heavy.'",
            },
            {
                "id": "tf_contrapositive",
                "title": "The Flip Rule",
                "type": "quiz",
                "question": "If 'All apples are fruits' is true, which of these must also be true?",
                "options": [
                    "All fruits are apples",
                    "If something is not a fruit, it is not an apple",
                    "Some apples are not fruits",
                    "No fruits are apples",
                ],
                "answer": "b",
                "hints": [
                    "If every apple IS a fruit, what about something that is NOT a fruit?",
                    "Could something be an apple without being a fruit? The rule says no.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "This is called the contrapositive. If ALL apples are fruits, then anything that is NOT a fruit cannot be an apple. But careful: all fruits are NOT necessarily apples -- oranges are fruits too!",
                "is_boss": True,
                "flavor": "Puck flips the statement upside down. 'The mirror version is always true!'",
            },
        ],
    },

    # ==================================================================
    # ZONE 4 -- If-Then Thinking
    # ==================================================================
    "if_then_thinking": {
        "id": "if_then_thinking",
        "name": "The Cause & Effect Lab",
        "description": "Explore what happens when one thing leads to another",
        "level_required": 8,
        "challenges": [
            {
                "id": "it_basic_cause",
                "title": "Rain Rule",
                "type": "quiz",
                "question": "IF it rains, THEN the ground gets wet. It rained today. What do we know?",
                "options": [
                    "The ground is wet",
                    "The ground is dry",
                    "It might be wet",
                    "We cannot tell",
                ],
                "answer": "a",
                "hints": [
                    "The IF part happened. What does the THEN part say?",
                    "Rain happened, so the result must follow.",
                ],
                "xp": 20,
                "difficulty": "easy",
                "lesson": "This is a simple if-then rule. The IF part happened (it rained), so the THEN part must happen (the ground gets wet). When the condition is met, the result follows!",
                "is_boss": False,
                "flavor": "Rain falls on the page. The ground below it glistens. Cause and effect!",
            },
            {
                "id": "it_condition_not_met",
                "title": "Button Mystery",
                "type": "quiz",
                "question": "IF you press the button, THEN the light turns on. You did NOT press the button. Is the light on?",
                "options": [
                    "Yes, the light is on",
                    "No, the light is off",
                    "We cannot be sure",
                    "The light is broken",
                ],
                "answer": "c",
                "hints": [
                    "We know what happens IF you press it. But what if you don't?",
                    "Could someone else have turned the light on a different way?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Tricky! We only know what happens IF you press the button. Maybe the light is on for a different reason (someone else pressed it, or it has a timer). When the IF part does not happen, we cannot be sure about the THEN part.",
                "is_boss": False,
                "flavor": "A big red button glows on the page. Puck hovers over it. 'Should we press it?'",
            },
            {
                "id": "it_chain_reaction",
                "title": "Domino Chain",
                "type": "quiz",
                "question": "IF it snows, THEN school is canceled. IF school is canceled, THEN you play outside. It snowed! What happens?",
                "options": [
                    "You go to school",
                    "You play outside",
                    "Nothing happens",
                    "It stops snowing",
                ],
                "answer": "b",
                "hints": [
                    "Follow the chain step by step.",
                    "Snow causes no school. No school causes playing outside.",
                ],
                "xp": 25,
                "difficulty": "medium",
                "lesson": "This is a chain of if-then rules! Snow leads to no school, and no school leads to playing outside. Each step triggers the next, like a row of dominoes falling.",
                "is_boss": False,
                "flavor": "Dominoes line up across the page. Puck tips the first one. Click-click-click!",
            },
            {
                "id": "it_reverse_error",
                "title": "Backward Trap",
                "type": "quiz",
                "question": "IF an animal is a dog, THEN it has four legs. Fluffy has four legs. Is Fluffy definitely a dog?",
                "options": [
                    "Yes, Fluffy must be a dog",
                    "No, Fluffy could be another animal",
                    "Only if Fluffy barks",
                    "Yes, all four-legged animals are dogs",
                ],
                "answer": "b",
                "hints": [
                    "Dogs have four legs, but are dogs the ONLY animals with four legs?",
                    "Cats, horses, and rabbits also have four legs.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Be careful! Just because dogs have four legs does not mean everything with four legs is a dog. Cats, horses, and tables have four legs too! This mistake is called 'affirming the consequent.'",
                "is_boss": False,
                "flavor": "A mysterious silhouette with four legs appears. Is it a dog? A cat? A table?",
            },
            {
                "id": "it_everyday_rule",
                "title": "Dessert Detective",
                "type": "quiz",
                "question": "IF you eat your vegetables, THEN you get dessert. You did not get dessert. What do we know?",
                "options": [
                    "You ate your vegetables",
                    "You did not eat your vegetables",
                    "The dessert was gone",
                    "We cannot tell",
                ],
                "answer": "b",
                "hints": [
                    "If you HAD eaten your vegetables, what would have happened?",
                    "No dessert means the condition was not met.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "If the THEN part did not happen (no dessert), the IF part could not have happened either (you did not eat vegetables). This is called 'modus tollens' -- working backwards from the result!",
                "is_boss": False,
                "flavor": "An empty dessert plate sits on the page. Puck looks very disappointed.",
            },
            {
                "id": "it_two_conditions",
                "title": "Double Check",
                "type": "quiz",
                "question": "IF it is Saturday AND sunny, THEN we go to the park. Today is Saturday but it is raining. Do we go to the park?",
                "options": [
                    "Yes",
                    "No",
                    "Only in the morning",
                    "We go somewhere else",
                ],
                "answer": "b",
                "hints": [
                    "Both conditions need to be true for AND to work.",
                    "It IS Saturday, but it is NOT sunny. Does that satisfy both conditions?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When a rule has AND, ALL conditions must be true. It is Saturday (yes!) but NOT sunny (no!). Since both must be true and one is false, we do not go to the park.",
                "is_boss": False,
                "flavor": "A checklist appears: Saturday? Check! Sunny? Rain pours over the checkbox.",
            },
            {
                "id": "it_predict_outcome",
                "title": "Chain of Pride",
                "type": "text",
                "question": "IF you study hard, THEN you do well on the test. IF you do well on the test, THEN you feel proud. You studied hard. How do you feel?",
                "options": None,
                "answer": "proud",
                "hints": [
                    "Follow each if-then step forward.",
                    "Studying leads to doing well. Doing well leads to feeling...",
                ],
                "xp": 30,
                "difficulty": "hard",
                "lesson": "Following the chain: studying leads to doing well, and doing well leads to feeling proud. If-then chains help us predict the future by following causes to their effects, step by step.",
                "is_boss": False,
                "flavor": "Puck traces a golden arrow from a book to a test to a smiling face.",
            },
            {
                "id": "it_robot_commands",
                "title": "Robot Rules",
                "type": "text",
                "question": "A robot follows these rules: IF it sees red, THEN stop. IF it sees green, THEN go. IF it sees yellow, THEN slow down. The robot sees yellow then green. What does it do?",
                "options": None,
                "answer": "slow down then go",
                "hints": [
                    "The robot follows each rule one at a time, in order.",
                    "Yellow means slow down. Then green means go.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "The robot follows each rule in order. First it sees yellow, so it slows down. Then it sees green, so it goes. Computers and robots follow if-then rules just like this -- that is how programs work!",
                "is_boss": True,
                "flavor": "A little robot rolls across the page, scanning colored lights with its sensors.",
            },
        ],
    },

    # ==================================================================
    # ZONE 5 -- Brain Teasers
    # ==================================================================
    "brain_teasers": {
        "id": "brain_teasers",
        "name": "The Riddle Vault",
        "description": "Put all your logic skills together to solve tricky brain teasers",
        "level_required": 10,
        "challenges": [
            {
                "id": "bt_coin_flip",
                "title": "Tricky Coins",
                "type": "quiz",
                "question": "I have two coins that add up to 30 cents. One of them is NOT a nickel. What are the two coins?",
                "options": [
                    "Two dimes",
                    "A quarter and a nickel",
                    "A dime and two nickels",
                    "A penny and a quarter",
                ],
                "answer": "b",
                "hints": [
                    "Read carefully: ONE of them is not a nickel. What about the other?",
                    "25 + 5 = 30. The quarter is not a nickel. The nickel IS a nickel.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The trick is the word 'one of them.' ONE coin is not a nickel -- that is the quarter! But the OTHER coin IS a nickel. The puzzle never said NEITHER coin is a nickel. Read carefully!",
                "is_boss": False,
                "flavor": "Two coins spin on the page. Puck winks. 'Words can be tricky!'",
            },
            {
                "id": "bt_farmer_crossing",
                "title": "River Crossing",
                "type": "quiz",
                "question": "A farmer has a fox, a chicken, and corn. He must cross a river but can only carry one at a time. The fox will eat the chicken if left alone, and the chicken will eat the corn. What should he take first?",
                "options": [
                    "The fox",
                    "The corn",
                    "The chicken",
                    "It is impossible",
                ],
                "answer": "c",
                "hints": [
                    "Which animal causes trouble on BOTH sides?",
                    "If the chicken is left with the fox OR the corn, something gets eaten.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Take the chicken first! The fox will not eat the corn, so they are safe together. Then come back, take the fox across, but bring the chicken BACK. Then take the corn across, and finally the chicken again.",
                "is_boss": False,
                "flavor": "A tiny river flows across the page. A fox, a chicken, and an ear of corn wait at the shore.",
            },
            {
                "id": "bt_ages_riddle",
                "title": "Age Gap",
                "type": "quiz",
                "question": "Sam is 4 years old. His big sister is twice his age. When Sam is 10, how old will his sister be?",
                "options": [
                    "20",
                    "16",
                    "14",
                    "12",
                ],
                "answer": "c",
                "hints": [
                    "How old is Sam's sister right now? What is the age difference?",
                    "The age GAP between them never changes, even as they grow.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Right now Sam is 4 and his sister is 8 (twice 4). The age GAP between them is always 4 years. When Sam is 10, his sister will be 10 + 4 = 14. The gap stays the same even though the ratio changes!",
                "is_boss": False,
                "flavor": "Two children grow taller on the page. The gap between their heights stays the same.",
            },
            {
                "id": "bt_socks_drawer",
                "title": "Sock Surprise",
                "type": "quiz",
                "question": "You have a drawer with 10 red socks and 10 blue socks, all mixed up. It is dark and you cannot see. What is the fewest socks you must grab to be SURE you have a matching pair?",
                "options": [
                    "2",
                    "3",
                    "10",
                    "11",
                ],
                "answer": "b",
                "hints": [
                    "What is the worst case? Could you grab two different colors?",
                    "If the first two are different, the third one MUST match one of them.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "You only need 3 socks! The first two might be different colors (one red, one blue). But the third sock MUST match one of them -- there are only two colors. This is the pigeonhole principle!",
                "is_boss": False,
                "flavor": "Puck reaches into a dark drawer and pulls out socks one by one.",
            },
            {
                "id": "bt_lily_pad",
                "title": "Lily Pad Puzzle",
                "type": "quiz",
                "question": "A lily pad doubles in size every day. On day 20 it covers the whole pond. On what day did it cover HALF the pond?",
                "options": [
                    "Day 10",
                    "Day 15",
                    "Day 18",
                    "Day 19",
                ],
                "answer": "d",
                "hints": [
                    "If it doubles each day, what was it the day BEFORE it was full?",
                    "Half of 'the whole pond' is one doubling away from full.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Since it DOUBLES each day, on day 19 it was half the size it is on day 20. Many people guess day 10 because half of 20 is 10, but doubling does not work that way. Exponential growth is surprising!",
                "is_boss": False,
                "flavor": "A lily pad grows on the page, doubling and doubling until the whole pond is green.",
            },
            {
                "id": "bt_birthday_candles",
                "title": "Digit Hunt",
                "type": "text",
                "question": "How many times does the digit 1 appear when you write all the numbers from 1 to 20?",
                "options": None,
                "answer": "12",
                "hints": [
                    "Write out all the numbers and count every 1 you see.",
                    "Don't forget that 11 has TWO ones!",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Let's count! The 1 appears in: 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19. That is 1 (once) + 10 (once) + 11 (twice!) + 12 through 19 (once each = 8). Total: 1 + 1 + 2 + 8 = 12.",
                "is_boss": False,
                "flavor": "Numbers from 1 to 20 light up on the page. Every digit 1 glows gold.",
            },
            {
                "id": "bt_handshake",
                "title": "Handshake Count",
                "type": "text",
                "question": "Four friends meet and every person shakes hands with every other person exactly once. How many handshakes happen in total?",
                "options": None,
                "answer": "6",
                "hints": [
                    "Person 1 shakes with 3 others. Person 2 shakes with 2 remaining...",
                    "Be careful not to count the same handshake twice!",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Person 1 shakes with 3 others. Person 2 shakes with 2 remaining. Person 3 shakes with 1 remaining. Person 4 has already shaken with everyone. 3 + 2 + 1 = 6. The formula is n(n-1)/2!",
                "is_boss": False,
                "flavor": "Four tiny figures appear on the page and start shaking hands. Puck counts each one.",
            },
            {
                "id": "bt_weighing_puzzle",
                "title": "The Heavy Ball",
                "type": "quiz",
                "question": "You have 8 identical-looking balls. One is slightly heavier. Using a balance scale, what is the fewest number of weighings needed to ALWAYS find the heavy one?",
                "options": [
                    "1",
                    "2",
                    "3",
                    "4",
                ],
                "answer": "b",
                "hints": [
                    "You don't have to weigh them one at a time. Try groups!",
                    "Split into groups of 3, 3, and 2. What happens when you weigh the two groups of 3?",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "Split into groups of 3, 3, and 2. Weigh the two groups of 3. If they balance, the heavy ball is in the group of 2 (one more weighing). If they do not, take the heavier group of 3 and weigh 1 vs 1. Two weighings always works!",
                "is_boss": True,
                "flavor": "Eight golden balls sit on the page. A balance scale gleams beside them. Puck whispers, 'Think in groups.'",
            },
        ],
    },
}
