"""
zones.py — Emotions & Mindfulness zones and challenges.

All challenges use "type": "quiz" with multiple-choice options.
Designed for ages 7-10, guided warmly by Puck.
"""

ZONE_ORDER = [
    "naming_feelings",
    "big_emotions",
    "empathy",
    "mindful_breathing",
    "gratitude",
    "friendship_skills",
    "self_confidence",
]

ZONES = {
    "naming_feelings": {
        "id": "naming_feelings",
        "name": "The Feeling Finder",
        "description": "Learn to name and identify your emotions",
        "level_required": 1,
        "challenges": [
            {
                "id": "what_is_happy",
                "title": "Sunshine Inside",
                "type": "quiz",
                "question": "You just got a surprise birthday party with all your friends! What emotion are you most likely feeling?",
                "options": ["Angry", "Happy", "Scared", "Disgusted"],
                "answer": "b",
                "hints": [
                    "This feeling makes you smile and want to laugh!",
                    "It's the warm, bubbly feeling you get when something wonderful happens.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Happiness is a warm, light feeling we get when something good happens. Our face relaxes, we smile, and we might even laugh or jump around. Everyone deserves to feel happy!",
                "is_boss": False,
                "flavor": "Puck twirls in the air, grinning so wide that little sparkles fly off.",
            },
            {
                "id": "what_is_sad",
                "title": "Rainy Days",
                "type": "quiz",
                "question": "Your best friend is moving far away and you won't see them every day anymore. What feeling is this?",
                "options": ["Surprised", "Angry", "Sad", "Happy"],
                "answer": "c",
                "hints": [
                    "This feeling might make your eyes sting with tears.",
                    "It's the heavy feeling you get when you lose something you care about.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Sadness is a heavy, quiet feeling we get when we lose something or someone we care about. It's okay to feel sad — it means you loved something. Crying is the body's way of letting sadness out.",
                "is_boss": False,
                "flavor": "Puck sits quietly, wings folded. A soft rain falls across the page.",
            },
            {
                "id": "what_is_angry",
                "title": "The Rumble Inside",
                "type": "quiz",
                "question": "Someone broke your favourite toy on purpose and laughed about it. What emotion might you feel?",
                "options": ["Surprised", "Happy", "Scared", "Angry"],
                "answer": "d",
                "hints": [
                    "This feeling makes your fists clench and your face feel hot.",
                    "It happens when something feels really unfair.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Anger is a strong, hot feeling we get when something feels unfair or when someone hurts us. It's a normal emotion — everyone feels angry sometimes. What matters is what we do with it.",
                "is_boss": False,
                "flavor": "Puck puffs up and tiny sparks crackle around those small fists. Then Puck takes a deep breath.",
            },
            {
                "id": "what_is_scared",
                "title": "Shadows and Shivers",
                "type": "quiz",
                "question": "You hear a loud crash of thunder in the dark and your heart starts beating really fast. What are you feeling?",
                "options": ["Happy", "Disgusted", "Scared", "Angry"],
                "answer": "c",
                "hints": [
                    "This feeling makes your heart pound and your body want to run or hide.",
                    "It's the alarm bell your body rings when it thinks there might be danger.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Fear is your body's alarm system. When you sense danger, your heart beats faster and your muscles get ready to run or hide. Fear keeps us safe — but sometimes it rings when there's no real danger, and that's okay too.",
                "is_boss": False,
                "flavor": "Puck hides behind the page, then peeks out with one eye. The Primer's edges glow a protective gold.",
            },
            {
                "id": "what_is_surprised",
                "title": "The Big Gasp",
                "type": "quiz",
                "question": "You open a box expecting socks, but inside is a puppy! Your eyes go wide and your mouth drops open. What emotion is this?",
                "options": ["Sad", "Surprised", "Angry", "Disgusted"],
                "answer": "b",
                "hints": [
                    "This feeling happens when something you didn't expect occurs.",
                    "Your eyebrows shoot up and you might gasp!",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Surprise happens when something we didn't expect occurs. Our eyes go wide, our mouth opens, and we gasp. Surprise can be good (a present!) or bad (a loud noise), but it always means something unexpected happened.",
                "is_boss": False,
                "flavor": "Puck's eyes go round as saucers and a little 'oh!' pops out in a speech bubble.",
            },
            {
                "id": "mixed_feelings",
                "title": "The Feelings Mix-Up",
                "type": "quiz",
                "question": "Can a person feel more than one emotion at the same time?",
                "options": [
                    "No, you can only feel one thing at a time",
                    "Yes, but only two at once",
                    "Yes! You can feel many emotions at the same time",
                    "No, feelings always come one after another",
                ],
                "answer": "c",
                "hints": [
                    "Think about starting at a new school — you might feel excited AND nervous!",
                    "Feelings can blend together, like colours mixing on a page.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "We can absolutely feel many emotions at once! You might feel happy AND nervous on your first day of school, or sad AND grateful when saying goodbye. Mixed feelings are completely normal and a sign of a rich, deep heart.",
                "is_boss": True,
                "flavor": "Puck holds up a little glass jar swirling with many colours — red, blue, gold, green — all mixing together beautifully.",
            },
        ],
    },
    "big_emotions": {
        "id": "big_emotions",
        "name": "The Storm Room",
        "description": "Learn what to do when feelings get really big",
        "level_required": 3,
        "challenges": [
            {
                "id": "when_angry_do",
                "title": "The Anger Volcano",
                "type": "quiz",
                "question": "You're SO angry you want to scream and throw things. What's the BEST first thing to do?",
                "options": [
                    "Throw a pillow at the wall",
                    "Yell at whoever made you angry",
                    "Take five slow, deep breaths before doing anything",
                    "Pretend you're not angry at all",
                ],
                "answer": "c",
                "hints": [
                    "When anger is really big, slowing your body down helps your brain think clearly again.",
                    "Breathing gives your body time to calm the alarm bells.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When anger gets really big, our thinking brain shuts down and our 'alarm brain' takes over. Taking slow, deep breaths tells your body: 'I'm safe. I can think now.' Once you're calmer, you can decide what to do next.",
                "is_boss": False,
                "flavor": "Puck blows a long, slow breath and a little volcano on the page stops rumbling.",
            },
            {
                "id": "when_sad_do",
                "title": "The Puddle of Sadness",
                "type": "quiz",
                "question": "You feel really sad and your eyes are full of tears. What is the healthiest thing to do?",
                "options": [
                    "Hold the tears in — crying is for babies",
                    "Let yourself cry, and talk to someone you trust about how you feel",
                    "Eat lots of sweets to feel better",
                    "Pretend everything is fine",
                ],
                "answer": "b",
                "hints": [
                    "Tears are the body's natural way of releasing sadness.",
                    "Sharing your feelings with a trusted person helps lighten the heavy feeling.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Crying is not a weakness — it's the body's way of releasing sadness. Talking to someone you trust (a parent, teacher, or friend) helps too. When we share our feelings, they become lighter. You never have to carry sadness alone.",
                "is_boss": False,
                "flavor": "Puck gently offers a tiny handkerchief. The puddle on the page slowly becomes a small, peaceful pond.",
            },
            {
                "id": "when_scared_do",
                "title": "The Shadow Monster",
                "type": "quiz",
                "question": "You're scared of the dark and can't sleep. What's a good way to help yourself feel safe?",
                "options": [
                    "Stay up all night being scared",
                    "Tell yourself your feelings are silly",
                    "Talk to a grown-up, use a nightlight, and take slow breaths",
                    "Scream really loudly",
                ],
                "answer": "c",
                "hints": [
                    "There are real steps you can take: changing what you see, slowing your breathing, and asking for help.",
                    "Being brave doesn't mean not being scared — it means asking for help when you need it.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Fear is real and valid — never tell yourself your feelings are silly. When you're scared, try these steps: talk to a trusted grown-up, change something in your environment (a nightlight!), and take slow, deep breaths. Being brave means facing fear with help, not alone.",
                "is_boss": False,
                "flavor": "Puck lights a tiny lantern. The shadows on the page shrink away to the corners.",
            },
            {
                "id": "calm_down_corner",
                "title": "The Calm-Down Corner",
                "type": "quiz",
                "question": "A 'calm-down corner' is a quiet place where you can go when feelings get too big. Which of these belongs in a calm-down corner?",
                "options": [
                    "A video game controller",
                    "A soft blanket, a stuffed animal, and a feelings chart",
                    "A pile of homework",
                    "Nothing at all — it should be empty",
                ],
                "answer": "b",
                "hints": [
                    "The calm-down corner should have soft, comforting things.",
                    "A feelings chart helps you name what you're experiencing.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A calm-down corner is a safe, quiet spot with comforting things — a soft blanket, a stuffed toy, maybe a feelings chart or a jar of glitter to watch settle. It's not a punishment place! It's where you go to give your brain time to calm down.",
                "is_boss": False,
                "flavor": "Puck arranges a tiny corner of the page with a cushion, a blanket, and a little glitter jar.",
            },
            {
                "id": "feelings_thermometer",
                "title": "The Feelings Thermometer",
                "type": "quiz",
                "question": "A 'feelings thermometer' helps you measure how BIG an emotion is, from 1 (tiny) to 10 (huge). Why is this helpful?",
                "options": [
                    "So you can compete with friends about who feels more",
                    "So you can know when to ask for help and what coping tool to use",
                    "So you never feel anything above a 3",
                    "It's not helpful at all",
                ],
                "answer": "b",
                "hints": [
                    "A small feeling (level 2) might just need a deep breath. A big feeling (level 8) might need a trusted adult.",
                    "Knowing HOW big your feeling is helps you choose the RIGHT tool.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "A feelings thermometer helps you notice HOW strong an emotion is. A level-2 frustration might just need a deep breath. A level-8 fury might need a calm-down corner, a walk, and a talk with someone you trust. Matching the tool to the size of the feeling is a superpower!",
                "is_boss": True,
                "flavor": "Puck holds up a little thermometer that glows from cool blue at the bottom to fiery red at the top.",
            },
        ],
    },
    "empathy": {
        "id": "empathy",
        "name": "The Mirror Room",
        "description": "Learn to understand how others feel",
        "level_required": 5,
        "challenges": [
            {
                "id": "what_is_empathy",
                "title": "Walking in Someone Else's Shoes",
                "type": "quiz",
                "question": "Empathy means:",
                "options": [
                    "Telling someone to stop being sad",
                    "Understanding and sharing how another person feels",
                    "Always agreeing with everyone",
                    "Feeling nothing at all",
                ],
                "answer": "b",
                "hints": [
                    "It's like imagining yourself in another person's situation.",
                    "It's about understanding, not fixing.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Empathy is the ability to understand and share another person's feelings — to imagine what it's like to be them. You don't have to fix their problem. Just understanding how they feel is one of the kindest things you can do.",
                "is_boss": False,
                "flavor": "Puck holds up a tiny mirror, and instead of a reflection, it shows another person's face.",
            },
            {
                "id": "reading_faces",
                "title": "The Face Detective",
                "type": "quiz",
                "question": "Your friend's eyebrows are pushed down, their lips are pressed tight, and their arms are crossed. How are they probably feeling?",
                "options": ["Happy", "Angry or frustrated", "Surprised", "Sleepy"],
                "answer": "b",
                "hints": [
                    "Tight lips and crossed arms are 'closed' body language.",
                    "Pushed-down eyebrows often mean frustration or anger.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Our faces and bodies show how we feel even when we don't say a word. Tight lips, crossed arms, and furrowed eyebrows often mean anger or frustration. Learning to read these signs helps you understand people better.",
                "is_boss": False,
                "flavor": "Puck makes a series of faces — happy, sad, angry, surprised — each one clear as a picture.",
            },
            {
                "id": "body_language_sad",
                "title": "The Slumped Shoulders",
                "type": "quiz",
                "question": "A classmate is sitting alone at lunch with slumped shoulders, looking down at the table. They might be feeling:",
                "options": [
                    "Excited about a game",
                    "Sad or lonely",
                    "Angry at the teacher",
                    "Hungry for pizza",
                ],
                "answer": "b",
                "hints": [
                    "Slumped shoulders and looking down are signs the body is feeling heavy.",
                    "Being alone at lunch when others are together can feel lonely.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Body language tells a story. Slumped shoulders, a bowed head, and sitting alone often mean someone is feeling sad or lonely. Noticing these signs is the first step to showing kindness — even a smile or a 'want to sit with us?' can change someone's whole day.",
                "is_boss": False,
                "flavor": "Puck looks at the lonely figure on the page, then flies over and sits beside them.",
            },
            {
                "id": "empathy_vs_sympathy",
                "title": "Feeling WITH, Not Just FOR",
                "type": "quiz",
                "question": "Your friend's dog passed away and they're crying. Which response shows the MOST empathy?",
                "options": [
                    "\"Don't cry, you can get a new dog!\"",
                    "\"That's so sad. I'm really sorry. I'm here if you want to talk or just sit together.\"",
                    "\"My dog is still alive, so I feel fine.\"",
                    "\"Stop being sad, it's just an animal.\"",
                ],
                "answer": "b",
                "hints": [
                    "Empathy means being WITH someone in their pain, not rushing them out of it.",
                    "The best response shows you understand their feelings and you're there for them.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Empathy means being WITH someone in their feelings — not trying to rush them out of it or make it about yourself. Saying 'I'm sorry, I'm here for you' is powerful because it tells the other person: you are not alone.",
                "is_boss": False,
                "flavor": "Puck sits quietly beside a crying figure, not saying a word, just being there. A warm glow surrounds them both.",
            },
            {
                "id": "perspective_taking",
                "title": "The Other Side of the Story",
                "type": "quiz",
                "question": "A new student joins your class and doesn't talk to anyone. Some kids say the new student is 'stuck-up'. What might REALLY be going on?",
                "options": [
                    "The new student definitely thinks they're better than everyone",
                    "The new student might be shy, scared, or nervous about being new",
                    "The new student doesn't like anyone in the class",
                    "The new student is just being rude",
                ],
                "answer": "b",
                "hints": [
                    "Imagine being the new person — everything is unfamiliar!",
                    "Sometimes what looks like unfriendliness is actually fear.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Perspective-taking means imagining what life looks like from someone else's point of view. A quiet new student might not be 'stuck-up' — they might be terrified! Before judging, always ask yourself: 'What might they be feeling right now?'",
                "is_boss": True,
                "flavor": "Puck flips the page around so you see the classroom from the new student's eyes — all those unfamiliar faces staring.",
            },
        ],
    },
    "mindful_breathing": {
        "id": "mindful_breathing",
        "name": "The Breathing Garden",
        "description": "Learn breathing and calming techniques",
        "level_required": 8,
        "challenges": [
            {
                "id": "why_breathe",
                "title": "The Magic of Breathing",
                "type": "quiz",
                "question": "Why does taking slow, deep breaths help you calm down?",
                "options": [
                    "It makes you dizzy so you forget what upset you",
                    "It tells your brain and body that you are safe, so the alarm system turns off",
                    "It doesn't actually help at all",
                    "It makes time go backwards",
                ],
                "answer": "b",
                "hints": [
                    "Your body has a built-in alarm system. Deep breathing is like pressing the 'off' button.",
                    "Slow breaths send a signal from your lungs to your brain: 'Everything is okay.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "When you're upset, your body activates its alarm system (called 'fight or flight'). Slow, deep breaths send a signal to your brain that says: 'I'm safe.' This turns off the alarm and lets your thinking brain take charge again. It's like a superpower you carry everywhere!",
                "is_boss": False,
                "flavor": "Puck breathes in slowly… and out. A tiny garden on the page blooms with each breath.",
            },
            {
                "id": "belly_breathing",
                "title": "The Balloon Belly",
                "type": "quiz",
                "question": "In belly breathing (also called diaphragm breathing), what should happen when you breathe IN?",
                "options": [
                    "Your shoulders should go up really high",
                    "Your belly should puff out like a balloon filling with air",
                    "You should hold your breath as long as possible",
                    "You should breathe as fast as you can",
                ],
                "answer": "b",
                "hints": [
                    "Imagine a balloon inside your belly — breathe in and fill it up!",
                    "Your belly pushes out, not your chest or shoulders.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Belly breathing means breathing deep into your belly, not just your chest. When you breathe in, your belly puffs out like a balloon. When you breathe out, it deflates. This kind of deep breathing is the most calming kind there is!",
                "is_boss": False,
                "flavor": "Puck places both hands on a round little belly and breathes in — it puffs out like a balloon! Then slowly deflates.",
            },
            {
                "id": "counting_breaths",
                "title": "The Counting Calm",
                "type": "quiz",
                "question": "In the '4-4-4' breathing technique, you breathe in for 4 seconds, hold for 4 seconds, and breathe out for 4 seconds. Why does counting help?",
                "options": [
                    "Because counting is boring and boredom calms you down",
                    "Because it gives your mind something to focus on besides the worry",
                    "Because the number 4 is magical",
                    "It doesn't help — you should breathe as fast as possible",
                ],
                "answer": "b",
                "hints": [
                    "When you're worried, your mind races. Counting gives it a steady focus.",
                    "Focusing on numbers pulls your attention away from the scary thoughts.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Counting your breaths gives your busy, worried mind something calm and steady to focus on. Instead of racing through scary thoughts, your brain focuses on: 1… 2… 3… 4. This is called 'mindful breathing' — and it works every single time you practise it.",
                "is_boss": False,
                "flavor": "Puck counts slowly — one, two, three, four — and little numbered bubbles float up from the page.",
            },
            {
                "id": "five_senses_grounding",
                "title": "The Five-Senses Anchor",
                "type": "quiz",
                "question": "The 5-4-3-2-1 grounding technique asks you to notice 5 things you can SEE, 4 you can TOUCH, 3 you can HEAR, 2 you can SMELL, and 1 you can TASTE. Why does this help when you're anxious?",
                "options": [
                    "It makes you hungry",
                    "It brings your attention back to the present moment and out of your worried thoughts",
                    "It gives you a list of things to buy at the shop",
                    "It doesn't help at all",
                ],
                "answer": "b",
                "hints": [
                    "Anxiety pulls your mind into the future (what if, what if!). This brings you back to NOW.",
                    "Noticing real things around you reminds your brain: I am HERE, I am SAFE.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When anxiety takes over, your mind races into the future with 'what if' thoughts. The 5-4-3-2-1 technique anchors you back to the present moment by focusing on what's real and right in front of you. It's like dropping an anchor when your mind is a boat in a storm.",
                "is_boss": False,
                "flavor": "Puck looks around the page: 'I see a flower, a cloud, a star, a butterfly, and you!'",
            },
            {
                "id": "mindful_listening",
                "title": "The Listening Leaf",
                "type": "quiz",
                "question": "Mindfulness means paying attention to the present moment on purpose and without judgment. Which of these is an example of being mindful?",
                "options": [
                    "Thinking about yesterday's argument while eating dinner",
                    "Worrying about tomorrow's test while brushing your teeth",
                    "Noticing the taste of each bite of your apple as you eat it",
                    "Doing three things at once while watching TV",
                ],
                "answer": "c",
                "hints": [
                    "Mindfulness means being fully HERE — in this moment — not somewhere else in your mind.",
                    "It means paying attention to what you're doing RIGHT NOW.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Mindfulness is the practice of paying full attention to what's happening right now — the taste of your food, the sound of birds, the feeling of your feet on the ground. When you're mindful, worries about the past and future fade, and you feel calmer and more present.",
                "is_boss": True,
                "flavor": "Puck closes both eyes, listens, and a smile slowly spreads. Every tiny sound on the page becomes visible — birdsong, rustling leaves, a heartbeat.",
            },
        ],
    },
    "gratitude": {
        "id": "gratitude",
        "name": "The Thankfulness Tree",
        "description": "Learn to notice and appreciate the good things in life",
        "level_required": 11,
        "challenges": [
            {
                "id": "what_is_gratitude",
                "title": "The Warm Glow",
                "type": "quiz",
                "question": "Gratitude means:",
                "options": [
                    "Wanting more things all the time",
                    "Noticing and being thankful for the good things in your life",
                    "Saying 'thank you' only when someone gives you a present",
                    "Pretending everything is perfect",
                ],
                "answer": "b",
                "hints": [
                    "Gratitude is about noticing, not just about saying words.",
                    "It's a feeling of warmth and thankfulness for what you already have.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Gratitude is the practice of noticing and being thankful for the good things in your life — big and small. It could be a sunny day, a hug from someone you love, or even just a good sandwich. Practising gratitude makes your brain happier over time!",
                "is_boss": False,
                "flavor": "Puck sits beneath a glowing tree. Every leaf shimmers with a tiny picture of something beautiful — a sunset, a friend, a warm meal.",
            },
            {
                "id": "gratitude_journal",
                "title": "Three Good Things",
                "type": "quiz",
                "question": "Scientists found that writing down three things you're grateful for every day can make you happier. Why does this work?",
                "options": [
                    "Because writing is good handwriting practice",
                    "Because it trains your brain to notice the good things instead of only the bad",
                    "Because it makes the bad things disappear",
                    "It doesn't actually work",
                ],
                "answer": "b",
                "hints": [
                    "Your brain gets better at whatever it practises — including noticing good things!",
                    "It doesn't remove bad things; it helps you see the good ones too.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Our brains have a 'negativity bias' — they naturally notice bad things more than good things. Writing down three good things every day trains your brain to notice the positive too. Over time, this makes you feel happier, sleep better, and even be kinder to others!",
                "is_boss": False,
                "flavor": "Puck pulls out a tiny notebook and writes: '1. Sunshine. 2. A friend who laughed at my joke. 3. This adventure!'",
            },
            {
                "id": "little_things",
                "title": "The Tiny Treasures",
                "type": "quiz",
                "question": "Which of these is something you could feel grateful for?",
                "options": [
                    "Only expensive gifts and big holidays",
                    "A warm bed, a kind word, or a pretty cloud",
                    "Nothing — life is always terrible",
                    "Only things other people give you",
                ],
                "answer": "b",
                "hints": [
                    "Gratitude is often about the small, everyday things we take for granted.",
                    "A warm bed, food to eat, someone who smiles at you — these are treasures.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Some of the best things to be grateful for are tiny, everyday things: a warm bed, a glass of cold water on a hot day, a friend's laugh, a bird singing outside. The more small things you notice, the richer your life feels.",
                "is_boss": False,
                "flavor": "Puck picks up tiny glowing things from the page — a leaf, a star, a dewdrop — and each one shines like gold.",
            },
            {
                "id": "gratitude_to_others",
                "title": "The Thank-You Bridge",
                "type": "quiz",
                "question": "What happens when you tell someone WHY you're grateful for them (not just 'thanks', but 'thank you for helping me when I was sad')?",
                "options": [
                    "Nothing special — words don't matter",
                    "It makes them feel embarrassed, so you shouldn't do it",
                    "It makes both of you feel happier and strengthens your friendship",
                    "It only helps the other person, not you",
                ],
                "answer": "c",
                "hints": [
                    "Specific, heartfelt gratitude makes BOTH people feel wonderful.",
                    "It builds a bridge between two hearts.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When you tell someone specifically WHY you appreciate them, it creates a powerful moment of connection. They feel seen and valued, and you feel the warmth of gratitude. It strengthens friendships and makes both people happier. Try it today!",
                "is_boss": False,
                "flavor": "Puck writes a tiny note and hands it to a friend on the page. They both start glowing.",
            },
            {
                "id": "gratitude_hard_times",
                "title": "Silver Linings",
                "type": "quiz",
                "question": "Can you practise gratitude even when you're going through a hard time?",
                "options": [
                    "No — you can only be grateful when everything is perfect",
                    "Yes — you can feel sad AND still notice small good things at the same time",
                    "No — being grateful during hard times means you're ignoring your real feelings",
                    "Yes — but only if you completely stop being sad first",
                ],
                "answer": "b",
                "hints": [
                    "Remember: you can feel more than one emotion at the same time!",
                    "Gratitude during hard times doesn't replace sadness — it sits beside it.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Gratitude during hard times doesn't mean pretending everything is fine. It means: 'Things are hard right now AND I still have some good things.' You can be sad about a loss AND grateful for the people who love you. Both feelings are real. Both matter.",
                "is_boss": True,
                "flavor": "Puck sits in the rain, looking up. Between the dark clouds, a single star shines through. Puck smiles at it.",
            },
        ],
    },
    "friendship_skills": {
        "id": "friendship_skills",
        "name": "The Friendship Forge",
        "description": "Learn how to be a good friend and resolve conflicts",
        "level_required": 14,
        "challenges": [
            {
                "id": "good_friend",
                "title": "The Golden Rule of Friendship",
                "type": "quiz",
                "question": "Which of these is the MOST important quality of a good friend?",
                "options": [
                    "They always let you win at games",
                    "They are kind, listen to you, and are honest — even when it's hard",
                    "They give you presents every week",
                    "They agree with everything you say",
                ],
                "answer": "b",
                "hints": [
                    "Good friendship is about how someone treats you, not what they give you.",
                    "Kindness, listening, and honesty are the three pillars.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A good friend is kind, listens when you talk, and tells the truth even when it's hard. They don't have to agree with everything you say or give you presents. Real friendship is built on trust, respect, and showing up when it matters.",
                "is_boss": False,
                "flavor": "Puck links arms with a friend on the page. A tiny golden thread connects their hearts.",
            },
            {
                "id": "sharing_and_turns",
                "title": "The Sharing Circle",
                "type": "quiz",
                "question": "You and a friend both want to play with the same toy. What's the best solution?",
                "options": [
                    "Grab it first and don't let go",
                    "Tell a teacher so they pick who gets it",
                    "Take turns — decide together who goes first and for how long",
                    "Walk away and never play with that friend again",
                ],
                "answer": "c",
                "hints": [
                    "The best solutions are ones you figure out TOGETHER.",
                    "Taking turns means both people get what they want — just not at the exact same time.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Taking turns is one of the most important social skills there is. When you figure out a fair solution together — who goes first, how long each turn lasts — both people feel respected. It's a small act of teamwork that builds big trust.",
                "is_boss": False,
                "flavor": "Puck and a friend pass a shiny marble back and forth, each one smiling on their turn.",
            },
            {
                "id": "resolving_conflict",
                "title": "The Peace Bridge",
                "type": "quiz",
                "question": "You and a friend had a big argument. What's the best first step to fix things?",
                "options": [
                    "Ignore them forever",
                    "Tell everyone in class that they were wrong",
                    "Wait until you're both calm, then talk about how you EACH felt using 'I' statements",
                    "Send someone else to tell them you're mad",
                ],
                "answer": "c",
                "hints": [
                    "You can't solve a conflict while emotions are still boiling. Cool down first.",
                    "'I felt hurt when...' works much better than 'You always...'",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "'I' statements are magical conflict-solvers. Instead of 'You were mean!', try 'I felt hurt when that happened.' It tells the other person how you feel without attacking them. And always wait until both people are calm before talking it out.",
                "is_boss": False,
                "flavor": "Puck builds a tiny bridge between two figures standing on opposite sides of a crack in the page.",
            },
            {
                "id": "saying_sorry",
                "title": "The Real Apology",
                "type": "quiz",
                "question": "Which of these is a REAL, meaningful apology?",
                "options": [
                    "\"Sorry! (but I didn't do anything wrong)\"",
                    "\"I'm sorry I hurt your feelings when I said that. I won't do it again.\"",
                    "\"Sorry, OKAY?! Can we just move on?!\"",
                    "\"My mum said I have to say sorry, so… sorry.\"",
                ],
                "answer": "b",
                "hints": [
                    "A real apology names what you did, shows you understand the hurt, and promises to do better.",
                    "It's not just the word 'sorry' — it's the meaning behind it.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A real apology has three parts: 1) Say what you did wrong ('I'm sorry I said that'). 2) Show you understand the hurt ('It must have made you feel bad'). 3) Promise to try to do better ('I'll be more careful with my words'). A real apology heals. A fake one doesn't.",
                "is_boss": False,
                "flavor": "Puck holds out a tiny heart-shaped note that reads: 'I'm sorry. I'll do better.' The other figure's frown softens.",
            },
            {
                "id": "including_others",
                "title": "The Open Circle",
                "type": "quiz",
                "question": "You see a classmate sitting alone at recess every day. They look like they want to join in but don't know how. What could you do?",
                "options": [
                    "Nothing — it's not your problem",
                    "Talk about them behind their back",
                    "Walk over and invite them to play with you and your friends",
                    "Wait for a teacher to notice",
                ],
                "answer": "c",
                "hints": [
                    "Sometimes all it takes is one person being brave enough to say 'come join us!'",
                    "Being left out is one of the loneliest feelings. You have the power to change that.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Including someone who is left out is one of the bravest, kindest things you can do. It only takes a moment — 'Hey, want to play with us?' — but it can change someone's whole day, week, or even year. Be the person who opens the circle wider.",
                "is_boss": False,
                "flavor": "Puck flies over to a lonely figure at the edge of the page and gently leads them into a circle of laughing friends.",
            },
            {
                "id": "boundaries",
                "title": "The Kindness Fence",
                "type": "quiz",
                "question": "Your friend wants you to do something that makes you uncomfortable. Being a good friend means:",
                "options": [
                    "Always doing what your friend wants, even if it feels wrong",
                    "Saying 'no' respectfully — real friends respect your boundaries",
                    "Ending the friendship immediately",
                    "Doing it but being angry about it later",
                ],
                "answer": "b",
                "hints": [
                    "A true friend respects your 'no'.",
                    "Boundaries are like fences — they protect you while keeping the friendship safe.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Boundaries are the limits you set to protect yourself. Saying 'no' to something that feels wrong is not mean — it's healthy. A real friend will respect your boundary. If someone pressures you after you say no, that's not friendship — that's pressure.",
                "is_boss": True,
                "flavor": "Puck draws a gentle golden fence around themselves — not to keep others out, but to keep their own heart safe. A true friend waves from the other side, smiling.",
            },
        ],
    },
    "self_confidence": {
        "id": "self_confidence",
        "name": "The Mirror of Strength",
        "description": "Learn positive self-talk, growth mindset, and celebrating effort",
        "level_required": 17,
        "challenges": [
            {
                "id": "positive_self_talk",
                "title": "The Voice Inside",
                "type": "quiz",
                "question": "You made a mistake on a test. Which thought is an example of POSITIVE self-talk?",
                "options": [
                    "\"I'm so stupid. I'll never get anything right.\"",
                    "\"That test was dumb anyway, who cares.\"",
                    "\"I made a mistake, but I can learn from it and do better next time.\"",
                    "\"I should just give up trying.\"",
                ],
                "answer": "c",
                "hints": [
                    "Positive self-talk is honest but kind — it doesn't ignore the mistake, but it doesn't crush you either.",
                    "It looks forward: 'What can I learn? What can I try next?'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The voice inside your head matters more than almost any other voice. Positive self-talk doesn't mean lying to yourself — it means being honest AND kind. 'I made a mistake AND I can learn from it' is both true and empowering.",
                "is_boss": False,
                "flavor": "Puck whispers into a tiny mirror, and the reflection smiles back warmly and gives a thumbs up.",
            },
            {
                "id": "growth_mindset",
                "title": "The Growing Brain",
                "type": "quiz",
                "question": "A 'growth mindset' means believing:",
                "options": [
                    "You're either smart or you're not — it can't change",
                    "Only talented people succeed",
                    "Your brain can grow and get better at things through practice and effort",
                    "Mistakes are proof you're not good enough",
                ],
                "answer": "c",
                "hints": [
                    "Your brain is like a muscle — it gets stronger every time you practise!",
                    "Every expert was once a beginner who kept going.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A growth mindset means believing your brain can grow and change. Every time you struggle with something hard, your brain builds new connections — like a muscle getting stronger. People with a growth mindset see challenges as opportunities, not threats.",
                "is_boss": False,
                "flavor": "Puck holds up a tiny brain that glows brighter with every challenge — sprouting new branches like a tree.",
            },
            {
                "id": "power_of_yet",
                "title": "The Magic Word: YET",
                "type": "quiz",
                "question": "Instead of saying 'I can't do maths', what could you say?",
                "options": [
                    "\"I can't do maths and I never will.\"",
                    "\"I can't do maths YET — but I'm learning!\"",
                    "\"Maths is stupid anyway.\"",
                    "\"Only some people are maths people.\"",
                ],
                "answer": "b",
                "hints": [
                    "One tiny word turns a dead end into a path forward.",
                    "YET means: 'I'm not there, but I'm on my way.'",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "The word YET is one of the most powerful words in the English language. 'I can't ride a bike' is a wall. 'I can't ride a bike YET' is a door. It reminds you that learning takes time — and you're on your way.",
                "is_boss": False,
                "flavor": "Puck hangs a glowing three-letter sign on the page: Y-E-T. It pulses with golden light.",
            },
            {
                "id": "celebrate_effort",
                "title": "The Effort Trophy",
                "type": "quiz",
                "question": "Which should you be MOST proud of?",
                "options": [
                    "Getting a perfect score on something really easy",
                    "Working really hard on something difficult, even if you didn't get it perfect",
                    "Being naturally good at something without trying",
                    "Avoiding hard things so you never fail",
                ],
                "answer": "b",
                "hints": [
                    "The proudest moments come from hard work, not easy wins.",
                    "Effort is what builds your brain and your character.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Effort deserves celebration! Getting a perfect score on something easy doesn't grow your brain. But struggling with something hard, making mistakes, and keeping going — THAT is where real growth happens. Celebrate the effort, not just the result.",
                "is_boss": False,
                "flavor": "Puck holds up a tiny golden trophy. On it is written not 'WINNER' but 'KEPT GOING'.",
            },
            {
                "id": "mistakes_are_teachers",
                "title": "The Beautiful Mistake",
                "type": "quiz",
                "question": "Famous inventor Thomas Edison failed over 1,000 times before creating the light bulb. What does this teach us?",
                "options": [
                    "Thomas Edison wasn't very smart",
                    "You should quit after the first failure",
                    "Mistakes and failures are part of learning — every 'failure' teaches you something",
                    "Only inventors need to try more than once",
                ],
                "answer": "c",
                "hints": [
                    "Edison said: 'I didn't fail. I found 1,000 ways that don't work.'",
                    "Every mistake teaches you something that gets you closer to success.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Every mistake is a lesson in disguise. Edison's 1,000 'failures' weren't wasted — each one taught him something. Scientists, artists, athletes — everyone who ever got great at something failed many times first. Mistakes are not the opposite of success. They're the path TO it.",
                "is_boss": False,
                "flavor": "Puck holds up a cracked, glued-together pot. Through every crack, golden light pours out — more beautiful than a perfect pot.",
            },
            {
                "id": "you_are_enough",
                "title": "The Enough Mirror",
                "type": "quiz",
                "question": "Self-confidence means:",
                "options": [
                    "Thinking you're better than everyone else",
                    "Never making mistakes",
                    "Believing in your own worth and abilities, even when things are hard",
                    "Being loud and always talking about yourself",
                ],
                "answer": "c",
                "hints": [
                    "Confidence isn't about being perfect — it's about trusting yourself.",
                    "It's a quiet inner voice that says: 'I can handle this.'",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Self-confidence doesn't mean thinking you're perfect or better than others. It means trusting yourself — knowing that you can handle hard things, learn from mistakes, and keep growing. You are enough, exactly as you are, AND you can always keep growing. Both are true.",
                "is_boss": True,
                "flavor": "Puck holds up a mirror. In it, you see yourself — glowing, strong, and enough. Puck whispers: 'That's you. That's always been you.'",
            },
        ],
    },
}
