"""
zones.py — German Basics zones and challenges.

All challenges use "type": "quiz" with multiple-choice options.
Guided by Ritter Wolf, guardian of the Sprachburg.
"""

ZONE_ORDER = [
    "alphabet_pronunciation",
    "articles",
    "personal_pronouns",
    "sein_haben",
    "word_order",
]

ZONES = {
    # ── Zone 1: Alphabet & Pronunciation ─────────────────────────────
    "alphabet_pronunciation": {
        "id": "alphabet_pronunciation",
        "name": "Alphabet & Pronunciation",
        "description": "German sounds, umlauts, and the Eszett",
        "level_required": 1,
        "challenges": [
            {
                "id": "umlaut_a",
                "title": "The Mysterious Ä",
                "type": "quiz",
                "question": "How is the German letter 'ä' pronounced?",
                "options": ["Like 'ah' in 'father'", "Like 'e' in 'bed'", "Like 'ee' in 'see'", "Like 'oo' in 'food'"],
                "answer": "b",
                "hints": [
                    "Think of a sound between 'a' and 'e'.",
                    "Mädchen (girl) -- the ä sounds like the 'e' in 'bed'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The umlaut ä is pronounced like the 'e' in 'bed'. It changes the base vowel 'a' to a front vowel. Examples: Mädchen (girl), Käse (cheese), Bär (bear). The umlaut dots are not decoration -- they fundamentally change the sound!",
                "is_boss": False,
                "flavor": "Ritter Wolf traces the two dots above the A on the stone wall. 'These tiny dots change everything!'",
            },
            {
                "id": "umlaut_o",
                "title": "The Round Ö",
                "type": "quiz",
                "question": "Which English sound is closest to the German 'ö'?",
                "options": ["The 'o' in 'go'", "The 'u' in 'fur' (with rounded lips)", "The 'oo' in 'moon'", "The 'aw' in 'law'"],
                "answer": "b",
                "hints": [
                    "Say 'e' as in 'bed' but round your lips like saying 'o'.",
                    "Think of the sound in the English word 'fur' or 'bird'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The umlaut ö is made by saying 'e' (as in 'bed') with rounded lips. The closest English equivalent is the vowel in 'fur' or 'bird'. Examples: schön (beautiful), Löwe (lion), böse (angry/evil).",
                "is_boss": False,
                "flavor": "Ritter Wolf purses his lips into a circle. 'Round your lips, knight! Schööön!'",
            },
            {
                "id": "umlaut_u",
                "title": "The Tricky Ü",
                "type": "quiz",
                "question": "How do you produce the German 'ü' sound?",
                "options": ["Say 'oo' with spread lips", "Say 'ee' with rounded lips", "Say 'ah' with closed teeth", "Say 'oh' with open mouth"],
                "answer": "b",
                "hints": [
                    "Start with the 'ee' sound and change only your lip shape.",
                    "Keep your tongue in the 'ee' position but round your lips.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The umlaut ü is produced by saying 'ee' (as in 'see') with rounded lips. It has no exact English equivalent. Examples: über (over/about), grün (green), Tür (door), fünf (five). Practice: say 'ee' and slowly round your lips without moving your tongue.",
                "is_boss": False,
                "flavor": "Ritter Wolf demonstrates the lip position. 'Grüüün! The color of the forest!'",
            },
            {
                "id": "eszett",
                "title": "The Sharp ß",
                "type": "quiz",
                "question": "What sound does the German letter 'ß' (Eszett) make?",
                "options": ["A 'b' sound", "A 'z' sound", "A sharp 's' sound (like 'ss')", "A 'sh' sound"],
                "answer": "c",
                "hints": [
                    "It looks unique but sounds familiar -- like a hissing snake.",
                    "Straße (street) -- the ß sounds like a double 's'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The Eszett (ß) represents a sharp, voiceless 's' sound, like 'ss'. It appears after long vowels and diphthongs. Examples: Straße (street), groß (big), weiß (white), heißen (to be called). In Switzerland, 'ss' is always used instead of ß.",
                "is_boss": False,
                "flavor": "Ritter Wolf points to a street sign on the castle wall: Burgstraße. 'The ß -- uniquely German!'",
            },
            {
                "id": "ch_sound",
                "title": "The German CH",
                "type": "quiz",
                "question": "German has two 'ch' sounds. After 'a, o, u' it is a guttural sound (like clearing your throat). After 'e, i' it sounds more like...?",
                "options": ["The 'sh' in 'ship'", "The 'h' in 'huge'", "The 'k' in 'king'", "The 'ch' in 'church'"],
                "answer": "b",
                "hints": [
                    "Think of the breathy sound at the start of 'huge' or 'human'.",
                    "ich (I) -- the ch is soft, like a whispered 'h' with friction.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "German 'ch' has two variants: after a/o/u it is the 'ach-Laut' (guttural, like Scottish 'loch'). After e/i/consonants it is the 'ich-Laut' (soft, like the 'h' in 'huge'). Examples: Buch (book, guttural), ich (I, soft), Nacht (night, guttural), Licht (light, soft).",
                "is_boss": False,
                "flavor": "Ritter Wolf growls softly. 'Two sounds, one spelling. The ch is a shapeshifter!'",
            },
            {
                "id": "w_v_sounds",
                "title": "W and V Swap",
                "type": "quiz",
                "question": "How is the German letter 'w' pronounced?",
                "options": ["Like English 'w' in 'water'", "Like English 'v' in 'vine'", "Like English 'f' in 'fun'", "It is silent"],
                "answer": "b",
                "hints": [
                    "German w and English v are friends.",
                    "Wasser (water) is pronounced 'Vasser'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "In German, 'w' is pronounced like English 'v'. So 'Wasser' (water) sounds like 'Vasser', and 'wo' (where) sounds like 'vo'. Meanwhile, German 'v' often sounds like English 'f' (Vater = 'Fahter'). This swap trips up many English speakers!",
                "is_boss": False,
                "flavor": "Ritter Wolf pours a goblet of Wasser. 'Vasser! Not Watter! The W betrays English speakers!'",
            },
            {
                "id": "z_sound",
                "title": "The German Z",
                "type": "quiz",
                "question": "How is the letter 'z' pronounced in German?",
                "options": ["Like English 'z' in 'zoo'", "Like 'ts' in 'cats'", "Like 'th' in 'the'", "Like 's' in 'sun'"],
                "answer": "b",
                "hints": [
                    "Zeit (time) -- say it out loud. It starts with a 'ts' sound.",
                    "Think of the 'ts' at the end of 'cats' but at the beginning.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "German 'z' is always pronounced 'ts' (like the end of 'cats'). Examples: Zeit (time) = 'Tsait', zehn (ten) = 'Tsehn', Zimmer (room) = 'Tsimmer', zusammen (together) = 'Tsu-zammen'. Never a buzzing 'zzz' like in English!",
                "is_boss": False,
                "flavor": "Ritter Wolf checks the castle clock. 'Die Zeit! Tsait! Every Z is a TS in German!'",
            },
            {
                "id": "alphabet_boss",
                "title": "Sound Master",
                "type": "quiz",
                "question": "Which word contains ALL THREE German umlauts (ä, ö, ü)?",
                "options": ["Überraschung (surprise)", "Gewöhnlich (usual)", "Ausübung (exercise)", "Natürlich schön, Mädchen"],
                "answer": "d",
                "hints": [
                    "You need ä AND ö AND ü in one phrase.",
                    "Only one option contains all three umlaut letters.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "The three German umlauts are ä (as in Mädchen), ö (as in schön), and ü (as in natürlich). 'Natürlich schön, Mädchen' (naturally beautiful, girl) contains all three. Umlauts are not optional -- they change meaning: schon (already) vs. schön (beautiful), schwul (humid) vs. schwül (muggy).",
                "is_boss": True,
                "flavor": "Ritter Wolf's eyes gleam in the torchlight. 'Find all three umlauts! A true sound master misses nothing!'",
            },
        ],
    },

    # ── Zone 2: Articles (der/die/das) ───────────────────────────────
    "articles": {
        "id": "articles",
        "name": "Articles: Der, Die, Das",
        "description": "German grammatical gender and definite articles",
        "level_required": 2,
        "challenges": [
            {
                "id": "der_basics",
                "title": "The Masculine Article",
                "type": "quiz",
                "question": "Which article goes with 'Mann' (man)?",
                "options": ["der Mann", "die Mann", "das Mann", "dem Mann"],
                "answer": "a",
                "hints": [
                    "Mann (man) is masculine -- and the masculine article is...",
                    "der = masculine, die = feminine, das = neuter.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "'Der' is the masculine definite article ('the'). der Mann (the man), der Hund (the dog), der Tisch (the table). Many words for male people/animals are masculine, but grammatical gender doesn't always match natural gender!",
                "is_boss": False,
                "flavor": "Ritter Wolf holds up a blue shield. 'Der! The mark of the masculine!'",
            },
            {
                "id": "die_basics",
                "title": "The Feminine Article",
                "type": "quiz",
                "question": "Which article goes with 'Frau' (woman)?",
                "options": ["der Frau", "die Frau", "das Frau", "den Frau"],
                "answer": "b",
                "hints": [
                    "Frau (woman) is feminine -- and the feminine article is...",
                    "die is for feminine nouns.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "'Die' is the feminine definite article. die Frau (the woman), die Katze (the cat), die Blume (the flower). Fun fact: 'die' is also used for ALL plural nouns regardless of gender: die Männer (the men), die Frauen (the women), die Kinder (the children).",
                "is_boss": False,
                "flavor": "Ritter Wolf holds up a red banner. 'Die! Feminine and plural -- a dual-purpose article!'",
            },
            {
                "id": "das_basics",
                "title": "The Neuter Article",
                "type": "quiz",
                "question": "Which article goes with 'Kind' (child)?",
                "options": ["der Kind", "die Kind", "das Kind", "den Kind"],
                "answer": "c",
                "hints": [
                    "Kind (child) is neuter in German.",
                    "das = neuter. Yes, a child is grammatically neuter in German!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "'Das' is the neuter definite article. das Kind (the child), das Buch (the book), das Haus (the house). German neuter doesn't mean 'no gender' -- it's a third grammatical category. das Mädchen (the girl) is neuter because of the -chen diminutive ending!",
                "is_boss": False,
                "flavor": "Ritter Wolf holds up a golden banner. 'Das! The neuter -- expect the unexpected!'",
            },
            {
                "id": "gender_hints",
                "title": "Gender Patterns",
                "type": "quiz",
                "question": "Words ending in '-ung' (like Zeitung, newspaper) are almost always which gender?",
                "options": ["Masculine (der)", "Feminine (die)", "Neuter (das)", "It varies"],
                "answer": "b",
                "hints": [
                    "Die Zeitung, die Übung, die Wohnung...",
                    "The -ung ending is one of the most reliable feminine markers.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Helpful patterns: Feminine (die): -ung (Zeitung), -heit (Freiheit), -keit (Möglichkeit), -schaft (Freundschaft), -tion (Nation). Masculine (der): -er (Computer), -ling (Frühling). Neuter (das): -chen (Mädchen), -lein (Fräulein), -um (Museum).",
                "is_boss": False,
                "flavor": "Ritter Wolf unfurls a scroll of patterns. 'Rules in the chaos! Endings reveal the gender!'",
            },
            {
                "id": "ein_eine",
                "title": "Indefinite Articles",
                "type": "quiz",
                "question": "How do you say 'a dog' in German? (Hund is masculine)",
                "options": ["ein Hund", "eine Hund", "einer Hund", "eines Hund"],
                "answer": "a",
                "hints": [
                    "The indefinite article for masculine and neuter is 'ein'.",
                    "ein = masculine/neuter, eine = feminine.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Indefinite articles ('a/an'): ein for masculine (ein Hund), eine for feminine (eine Katze), ein for neuter (ein Buch). Notice: masculine and neuter share 'ein'! The negative is kein/keine: kein Hund (no dog), keine Katze (no cat).",
                "is_boss": False,
                "flavor": "Ritter Wolf presents a single shield. 'Ein -- the article of the unknown. A knight, not THE knight!'",
            },
            {
                "id": "plural_die",
                "title": "Plural: Always Die",
                "type": "quiz",
                "question": "What is the plural article for ALL German nouns, regardless of gender?",
                "options": ["der", "die", "das", "den"],
                "answer": "b",
                "hints": [
                    "One article rules them all in the plural.",
                    "Even der Hund becomes die Hunde in plural.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "In the plural, ALL German nouns use 'die' as their definite article, regardless of their singular gender. der Hund -> die Hunde, das Kind -> die Kinder, die Frau -> die Frauen. The plural forms of nouns themselves vary wildly (-e, -er, -en, -s, umlaut changes), but the article is always die.",
                "is_boss": False,
                "flavor": "Ritter Wolf lines up his troops. 'In the plural, all genders unite under one banner: die!'",
            },
            {
                "id": "tricky_genders",
                "title": "Surprising Genders",
                "type": "quiz",
                "question": "What is the correct article for 'Mädchen' (girl)?",
                "options": ["der Mädchen", "die Mädchen", "das Mädchen", "dem Mädchen"],
                "answer": "c",
                "hints": [
                    "The -chen ending makes ANY noun neuter.",
                    "Grammar beats biology here -- the diminutive wins!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "'Das Mädchen' (the girl) is neuter because the -chen diminutive ending ALWAYS makes a noun neuter. Similarly: das Brötchen (the bread roll), das Häuschen (the little house). In German, grammatical gender follows morphology, not biology!",
                "is_boss": False,
                "flavor": "Ritter Wolf raises an eyebrow. 'A girl is das? Grammar has its own logic, knight!'",
            },
            {
                "id": "articles_boss",
                "title": "Article Master",
                "type": "quiz",
                "question": "Which set of articles is correct? 'I see ___ Frau, ___ Kind, und ___ Hund.'",
                "options": ["der, das, die", "die, das, der", "die, das, den", "die, den, das"],
                "answer": "c",
                "hints": [
                    "After 'sehen' (to see), the accusative case applies.",
                    "In accusative, masculine 'der' changes to 'den'. Feminine and neuter stay the same.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "In the accusative case (direct object), only the masculine article changes: der -> den. Feminine (die) and neuter (das) stay the same. 'Ich sehe die Frau, das Kind, und den Hund.' This is your first taste of German cases -- more to come!",
                "is_boss": True,
                "flavor": "Ritter Wolf arranges three shields in a row. 'The accusative changes one article. Which one? Show me you know!'",
            },
        ],
    },

    # ── Zone 3: Personal Pronouns ────────────────────────────────────
    "personal_pronouns": {
        "id": "personal_pronouns",
        "name": "Personal Pronouns",
        "description": "Ich, du, er, sie, es and beyond",
        "level_required": 3,
        "challenges": [
            {
                "id": "ich_du",
                "title": "I and You",
                "type": "quiz",
                "question": "What are the German words for 'I' and 'you' (informal singular)?",
                "options": ["ich / du", "ich / Sie", "wir / ihr", "er / sie"],
                "answer": "a",
                "hints": [
                    "'Ich' is one of the most common words in any language.",
                    "'du' is the informal 'you' -- used with friends, family, children.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "'Ich' = I, 'du' = you (informal singular). 'Du' is used with friends, family, children, and peers. Note: 'ich' is only capitalized at the start of a sentence (unlike English 'I'). In German, 'du' implies closeness and familiarity.",
                "is_boss": False,
                "flavor": "Ritter Wolf points to himself, then to you. 'Ich und du -- the foundation of every conversation!'",
            },
            {
                "id": "er_sie_es",
                "title": "He, She, It",
                "type": "quiz",
                "question": "What are the German pronouns for 'he', 'she', and 'it'?",
                "options": ["er, sie, es", "er, ihr, es", "ihm, sie, das", "der, die, das"],
                "answer": "a",
                "hints": [
                    "These match the articles: der->er, die->sie, das->es.",
                    "'sie' means both 'she' and 'they' -- context tells you which!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "'Er' = he, 'sie' = she, 'es' = it. These correspond to grammatical gender: der Tisch (the table) -> er (he/it), die Lampe (the lamp) -> sie (she/it), das Buch (the book) -> es (it). A table is 'he' and a lamp is 'she' in German!",
                "is_boss": False,
                "flavor": "Ritter Wolf introduces three squires: 'Er, sie, und es -- every noun becomes one of these!'",
            },
            {
                "id": "wir_ihr",
                "title": "We and You (Plural)",
                "type": "quiz",
                "question": "How do you say 'we' and 'you all' (informal plural) in German?",
                "options": ["wir / ihr", "uns / euch", "wir / Sie", "sie / ihr"],
                "answer": "a",
                "hints": [
                    "'Wir' is the first person plural.",
                    "'Ihr' is like saying 'you guys' or 'y'all'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "'Wir' = we, 'ihr' = you all (informal plural). 'Ihr' is used when addressing a group of people you'd individually call 'du'. Example: 'Ihr seid meine Freunde' (You all are my friends). In southern Germany, 'ihr' is used very frequently.",
                "is_boss": False,
                "flavor": "Ritter Wolf gathers the knights together. 'Wir -- together! Ihr -- all of you!'",
            },
            {
                "id": "sie_formal",
                "title": "The Formal You",
                "type": "quiz",
                "question": "How is the formal 'you' written in German?",
                "options": ["sie (lowercase)", "Sie (capitalized)", "Du (capitalized)", "Ihr (capitalized)"],
                "answer": "b",
                "hints": [
                    "The formal 'you' is always capitalized, even mid-sentence.",
                    "It looks exactly like 'they' but with a capital S.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "'Sie' (capital S) = formal 'you' (singular AND plural). It's always capitalized to distinguish it from 'sie' (she/they). Use 'Sie' with strangers, elders, in professional settings. 'Sie' uses the same verb forms as 'sie' (they): 'Sie sind' = you are (formal) = they are.",
                "is_boss": False,
                "flavor": "Ritter Wolf stands at attention. 'Sie! The pronoun of respect. Always capitalized, always formal!'",
            },
            {
                "id": "sie_triple",
                "title": "The Three Sies",
                "type": "quiz",
                "question": "'sie' can mean three different things in German. Which is NOT one of them?",
                "options": ["she", "they", "you (formal)", "we"],
                "answer": "d",
                "hints": [
                    "'sie' (lowercase) = she or they. 'Sie' (capital) = formal you.",
                    "'We' is 'wir' in German.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The word 'sie/Sie' has three meanings: 1) sie = she (singular, lowercase), 2) sie = they (plural, lowercase), 3) Sie = you formal (capitalized). Context and verb conjugation help: sie ist (she is), sie sind (they are), Sie sind (you are, formal). 'We' = wir, not sie!",
                "is_boss": False,
                "flavor": "Ritter Wolf holds up three identical flags. 'One word, three meanings! Only in German!'",
            },
            {
                "id": "man_pronoun",
                "title": "The Impersonal Man",
                "type": "quiz",
                "question": "What does the German pronoun 'man' mean?",
                "options": ["A male person", "One / people in general", "We", "Someone specific"],
                "answer": "b",
                "hints": [
                    "'Man sagt...' = One says... / People say...",
                    "It's not about men -- it's impersonal, like 'one' in English.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "'Man' is an impersonal pronoun meaning 'one/people in general'. 'Man spricht Deutsch hier' = One speaks German here / German is spoken here. It conjugates like er/sie/es (third person singular). Not to be confused with 'der Mann' (the man)!",
                "is_boss": False,
                "flavor": "Ritter Wolf gestures broadly. 'Man sagt -- it is said! The voice of everyone and no one!'",
            },
            {
                "id": "pronoun_chart",
                "title": "Complete the Chart",
                "type": "quiz",
                "question": "Fill in the missing pronoun: ich, du, er/sie/es, wir, ___, sie/Sie",
                "options": ["uns", "ihr", "euch", "man"],
                "answer": "b",
                "hints": [
                    "This is the second person plural -- 'you all'.",
                    "It comes after 'wir' (we) in the pronoun chart.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The full German pronoun chart: ich (I), du (you informal), er/sie/es (he/she/it), wir (we), ihr (you all informal), sie/Sie (they / you formal). Six slots, but 'sie' pulls triple duty. Master this chart and you're ready for verb conjugation!",
                "is_boss": False,
                "flavor": "Ritter Wolf taps an empty slot on the round table. 'One seat remains! Who sits here?'",
            },
            {
                "id": "pronouns_boss",
                "title": "Pronoun Master",
                "type": "quiz",
                "question": "In the sentence 'Haben Sie einen Moment?', what does 'Sie' mean?",
                "options": ["She", "They", "You (formal)", "It"],
                "answer": "c",
                "hints": [
                    "Notice the capital S -- that's a key clue.",
                    "This is a polite question: 'Do you have a moment?'",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "'Haben Sie einen Moment?' = 'Do you have a moment?' (formal). The capital 'S' in 'Sie' indicates formal address. If it were 'Haben sie einen Moment?' (lowercase), it would mean 'Do they have a moment?' Capitalization matters in German -- it changes meaning!",
                "is_boss": True,
                "flavor": "Ritter Wolf approaches with a formal bow. 'Capital or lowercase? The fate of meaning hangs on a single letter!'",
            },
        ],
    },

    # ── Zone 4: Sein & Haben ─────────────────────────────────────────
    "sein_haben": {
        "id": "sein_haben",
        "name": "Sein & Haben",
        "description": "The two most important German verbs",
        "level_required": 4,
        "challenges": [
            {
                "id": "sein_meaning",
                "title": "To Be",
                "type": "quiz",
                "question": "What does the German verb 'sein' mean?",
                "options": ["To have", "To be", "To go", "To do"],
                "answer": "b",
                "hints": [
                    "Ich bin, du bist, er ist...",
                    "'To be or not to be' -- Sein oder Nichtsein!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "'Sein' = to be. It's the most important verb in German and completely irregular. 'Sein oder Nichtsein, das ist hier die Frage' -- To be or not to be, that is the question (Shakespeare in German). You'll use it in almost every sentence.",
                "is_boss": False,
                "flavor": "Ritter Wolf stands tall. 'Sein! To be! The verb that defines existence itself!'",
            },
            {
                "id": "sein_ich_du",
                "title": "Ich bin, du bist",
                "type": "quiz",
                "question": "Complete: 'Ich ___ müde. Du ___ stark.' (I am tired. You are strong.)",
                "options": ["bin / bist", "bist / bin", "ist / sind", "sind / seid"],
                "answer": "a",
                "hints": [
                    "ich -> bin, du -> bist.",
                    "'Bin' goes with 'ich', 'bist' goes with 'du'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Sein conjugation (present): ich bin (I am), du bist (you are). These are the first two forms to memorize. 'Ich bin müde' = I am tired. 'Du bist stark' = You are strong. Notice how different they are from the infinitive 'sein' -- completely irregular!",
                "is_boss": False,
                "flavor": "Ritter Wolf flexes an arm. 'Ich bin stark! Du bist auch stark! Conjugate with me!'",
            },
            {
                "id": "sein_er_wir",
                "title": "Er ist, wir sind",
                "type": "quiz",
                "question": "What is the correct conjugation: 'Er ___ ein Ritter. Wir ___ Freunde.'",
                "options": ["ist / sind", "bin / seid", "bist / sind", "sind / ist"],
                "answer": "a",
                "hints": [
                    "er/sie/es -> ist, wir -> sind.",
                    "'ist' is the third person singular form.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Sein conjugation continued: er/sie/es ist (he/she/it is), wir sind (we are), ihr seid (you all are), sie/Sie sind (they are / you formal are). Full chart: ich bin, du bist, er ist, wir sind, ihr seid, sie sind. Notice: 'wir' and 'sie/Sie' share 'sind'!",
                "is_boss": False,
                "flavor": "Ritter Wolf draws the full chart on a shield. 'Er ist, wir sind -- the forms multiply!'",
            },
            {
                "id": "haben_meaning",
                "title": "To Have",
                "type": "quiz",
                "question": "What does the German verb 'haben' mean?",
                "options": ["To be", "To have", "To give", "To want"],
                "answer": "b",
                "hints": [
                    "Ich habe, du hast, er hat...",
                    "It sounds a bit like English 'have'!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "'Haben' = to have. Along with 'sein', it's one of the two most essential German verbs. It's used for possession ('Ich habe ein Buch' = I have a book) and as a helper verb for past tense ('Ich habe gegessen' = I have eaten). Slightly irregular but predictable.",
                "is_boss": False,
                "flavor": "Ritter Wolf holds up a treasure chest. 'Haben! To have! What treasures do you possess?'",
            },
            {
                "id": "haben_conjugation",
                "title": "Haben Forms",
                "type": "quiz",
                "question": "Complete: 'Du ___ Hunger. Er ___ Durst.' (You are hungry. He is thirsty.)",
                "options": ["hast / hat", "habe / hast", "hat / hast", "haben / hat"],
                "answer": "a",
                "hints": [
                    "du -> hast, er -> hat.",
                    "Notice the 'b' from 'haben' disappears in some forms.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Haben conjugation: ich habe, du hast, er/sie/es hat, wir haben, ihr habt, sie/Sie haben. Note: German says 'Hunger haben' (to have hunger) not 'to be hungry'. Similarly: Durst haben (to be thirsty), Angst haben (to be afraid), Recht haben (to be right).",
                "is_boss": False,
                "flavor": "Ritter Wolf clutches his stomach. 'Ich habe Hunger! Germans HAVE hunger -- they don't ARE hungry!'",
            },
            {
                "id": "sein_vs_haben",
                "title": "Sein or Haben?",
                "type": "quiz",
                "question": "Which sentence is correct?",
                "options": ["Ich bin 25 Jahre alt", "Ich habe 25 Jahre alt", "Ich bin 25 Jahre haben", "Ich habe 25 alt"],
                "answer": "a",
                "hints": [
                    "German uses 'sein' (to be) for age, unlike some other languages.",
                    "'Ich bin... Jahre alt' = I am... years old.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "For age, German uses 'sein' (to be): 'Ich bin 25 Jahre alt' = I am 25 years old. But for feelings, German often uses 'haben': 'Ich habe Angst' = I am afraid (literally 'I have fear'). Knowing when to use sein vs. haben is a key German skill!",
                "is_boss": False,
                "flavor": "Ritter Wolf strokes his beard. 'Am I 25? Or do I have 25? In German, you ARE your age!'",
            },
            {
                "id": "negation_nicht",
                "title": "Nicht: Negating Sein",
                "type": "quiz",
                "question": "How do you say 'I am not tired' in German?",
                "options": ["Ich bin nicht müde", "Ich nicht bin müde", "Ich bin kein müde", "Nicht ich bin müde"],
                "answer": "a",
                "hints": [
                    "'Nicht' (not) goes after the verb 'bin'.",
                    "For adjectives, use 'nicht', not 'kein'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "To negate with sein + adjective, place 'nicht' after the verb: 'Ich bin nicht müde' (I am not tired). For haben + noun, use 'kein': 'Ich habe keinen Hund' (I don't have a dog). nicht = not (for verbs/adjectives), kein = no/not a (for nouns).",
                "is_boss": False,
                "flavor": "Ritter Wolf shakes his head. 'Nicht! The word that reverses everything!'",
            },
            {
                "id": "sein_haben_boss",
                "title": "Verb Forge Master",
                "type": "quiz",
                "question": "Which sentence correctly uses both sein AND haben? 'We are friends and we have time.'",
                "options": [
                    "Wir sind Freunde und wir haben Zeit.",
                    "Wir bin Freunde und wir habe Zeit.",
                    "Wir ist Freunde und wir hat Zeit.",
                    "Wir seid Freunde und wir habt Zeit.",
                ],
                "answer": "a",
                "hints": [
                    "'Wir' takes 'sind' (sein) and 'haben' (haben).",
                    "Both verbs need the 'wir' conjugation.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "'Wir sind Freunde und wir haben Zeit.' Both verbs use the 'wir' form: sind (from sein) and haben (from haben). Full wir forms: wir sind, wir haben, wir gehen, wir machen. The 'wir' form always matches the infinitive for regular verbs!",
                "is_boss": True,
                "flavor": "Ritter Wolf crosses two swords. 'Sein AND haben in one sentence! Only a true verb warrior can wield both!'",
            },
        ],
    },

    # ── Zone 5: Word Order ───────────────────────────────────────────
    "word_order": {
        "id": "word_order",
        "name": "Word Order",
        "description": "The iron laws of German sentence structure",
        "level_required": 5,
        "challenges": [
            {
                "id": "verb_second",
                "title": "The V2 Rule",
                "type": "quiz",
                "question": "In a German statement, where does the conjugated verb always go?",
                "options": ["First position", "Second position", "Last position", "Any position"],
                "answer": "b",
                "hints": [
                    "This is the most fundamental rule of German word order.",
                    "V2 = Verb Second. The verb claims position two.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The V2 (Verb Second) rule: in German statements, the conjugated verb ALWAYS goes in the second position. 'Ich spiele Tennis' (I play tennis). 'Heute spiele ich Tennis' (Today I play tennis) -- even when another element comes first, the verb stays second!",
                "is_boss": False,
                "flavor": "Ritter Wolf plants a flag in the second position. 'The verb always claims this spot. Always!'",
            },
            {
                "id": "inversion",
                "title": "Subject-Verb Inversion",
                "type": "quiz",
                "question": "'Morgen gehe ich ins Kino.' Why does 'ich' come AFTER 'gehe'?",
                "options": [
                    "It's a question",
                    "Because 'Morgen' took first position, so verb stays second and subject moves to third",
                    "It's a command",
                    "It's a mistake",
                ],
                "answer": "b",
                "hints": [
                    "When something other than the subject starts the sentence...",
                    "The verb must stay in position 2, so the subject gets bumped.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When a non-subject element (time, place, etc.) takes first position, the subject and verb invert to keep the verb in position 2. Normal: 'Ich gehe morgen ins Kino.' Inverted: 'Morgen gehe ich ins Kino.' Both mean the same thing -- the verb never moves from position 2!",
                "is_boss": False,
                "flavor": "Ritter Wolf swaps two knights' positions. 'The verb holds its ground -- everything else must move around it!'",
            },
            {
                "id": "questions_v1",
                "title": "Yes/No Questions",
                "type": "quiz",
                "question": "How do you form a yes/no question in German?",
                "options": [
                    "Add 'do' like in English",
                    "Put the verb in FIRST position",
                    "Add a question mark only",
                    "Use a special question word",
                ],
                "answer": "b",
                "hints": [
                    "German doesn't use 'do' as a helper verb.",
                    "'Spielst du Tennis?' -- the verb comes first!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Yes/no questions put the verb in FIRST position (V1). Statement: 'Du spielst Tennis.' (You play tennis.) Question: 'Spielst du Tennis?' (Do you play tennis?) No 'do/does' needed -- just move the verb to the front! W-questions (wer, was, wo) keep V2 order.",
                "is_boss": False,
                "flavor": "Ritter Wolf flips the verb to the front. 'To ask, move the verb forward! No do, no does!'",
            },
            {
                "id": "time_manner_place",
                "title": "Time-Manner-Place",
                "type": "quiz",
                "question": "What is the correct order of information in a German sentence? (TMP rule)",
                "options": [
                    "Place - Time - Manner",
                    "Manner - Place - Time",
                    "Time - Manner - Place",
                    "Place - Manner - Time",
                ],
                "answer": "c",
                "hints": [
                    "TMP: think of the German postal system -- when, how, where.",
                    "Time first, then how, then where.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "German follows the TMP rule: Time - Manner - Place. 'Ich fahre morgen (time) schnell (manner) nach Berlin (place).' English often puts place before time, but German insists on TMP. Remember: WANN (when), WIE (how), WO (where).",
                "is_boss": False,
                "flavor": "Ritter Wolf arranges three banners: WANN, WIE, WO. 'Time, then manner, then place -- the German way!'",
            },
            {
                "id": "verb_final_sub",
                "title": "Verb-Final in Subclauses",
                "type": "quiz",
                "question": "In the subclause 'weil ich müde bin' (because I am tired), where is the verb?",
                "options": ["First position", "Second position", "Third position", "Last position"],
                "answer": "d",
                "hints": [
                    "Subordinating conjunctions (weil, dass, wenn) send the verb to the end.",
                    "'...weil ich müde BIN' -- the verb is kicked to the very end!",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "In subclauses introduced by subordinating conjunctions (weil, dass, wenn, ob, als), the conjugated verb goes to the LAST position. 'Ich bin müde, weil ich nicht geschlafen habe.' (I am tired because I have not slept.) Main clause: V2. Subclause: verb-final. This is a defining feature of German!",
                "is_boss": False,
                "flavor": "Ritter Wolf sends the verb to the back of the line. 'In subclauses, the verb retreats to the very end!'",
            },
            {
                "id": "nicht_position",
                "title": "Where Does Nicht Go?",
                "type": "quiz",
                "question": "Where does 'nicht' go in 'Ich spiele nicht Tennis'?",
                "options": [
                    "Before the verb",
                    "After the verb, before the object it negates",
                    "At the very end",
                    "At the very beginning",
                ],
                "answer": "b",
                "hints": [
                    "'Nicht' goes before the element it negates.",
                    "Here it negates 'Tennis' -- so it goes right before it.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "'Nicht' placement depends on what it negates. Before a specific element: 'Ich spiele nicht Tennis' (I don't play tennis -- emphasis on not tennis). At the end for general negation: 'Ich spiele heute nicht' (I'm not playing today). Before adjectives: 'Das ist nicht gut' (That is not good).",
                "is_boss": False,
                "flavor": "Ritter Wolf places a stone marked 'NICHT' carefully in the sentence. 'Where nicht goes changes what you deny!'",
            },
            {
                "id": "und_oder_aber",
                "title": "Coordinating Conjunctions",
                "type": "quiz",
                "question": "Do 'und' (and), 'oder' (or), 'aber' (but) change the word order?",
                "options": [
                    "Yes, verb goes to the end",
                    "Yes, verb goes first",
                    "No, word order stays normal (V2 in both clauses)",
                    "Only 'aber' changes the order",
                ],
                "answer": "c",
                "hints": [
                    "Coordinating conjunctions connect two main clauses.",
                    "Both clauses keep their normal V2 word order.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Coordinating conjunctions (und, oder, aber, denn, sondern) do NOT change word order. Both clauses stay V2. 'Ich lese und er schreibt.' BUT subordinating conjunctions (weil, dass, wenn) send the verb to the end. This distinction is crucial in German grammar!",
                "is_boss": False,
                "flavor": "Ritter Wolf links two chains. 'Und, oder, aber -- they join without disrupting! The verb stays in position two!'",
            },
            {
                "id": "word_order_boss",
                "title": "Sentence Architect",
                "type": "quiz",
                "question": "Which sentence has correct German word order? 'I play tennis tomorrow because I have time.'",
                "options": [
                    "Ich spiele morgen Tennis, weil ich habe Zeit.",
                    "Ich spiele morgen Tennis, weil ich Zeit habe.",
                    "Morgen ich spiele Tennis, weil ich Zeit habe.",
                    "Ich morgen spiele Tennis, weil habe ich Zeit.",
                ],
                "answer": "b",
                "hints": [
                    "Main clause: V2 rule. Subclause (weil): verb-final.",
                    "In the main clause the verb 'spiele' is in second position. In the weil-clause, 'habe' goes to the end.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "'Ich spiele morgen Tennis, weil ich Zeit habe.' Main clause: V2 (spiele in position 2). Subclause: verb-final (habe at the end). Option C fails because 'Morgen' takes position 1, so the verb must be position 2: 'Morgen spiele ich Tennis...' Word order is the skeleton of German!",
                "is_boss": True,
                "flavor": "Ritter Wolf scatters tiles across the floor. 'Main clause AND subclause! Arrange every word perfectly!'",
            },
        ],
    },
}
