"""
zones.py — Daily Life zones and challenges.

All challenges use "type": "quiz" with multiple-choice options.
Guided by Sofia, a warm and encouraging Spanish teacher.
"""

ZONE_ORDER = [
    "morning_routine",
    "school_work",
    "hobbies",
    "weather",
    "shopping",
    "body_health",
]

ZONES = {
    # -- Zone 1: Morning Routine --
    "morning_routine": {
        "id": "morning_routine",
        "name": "Morning Routine",
        "description": "Learn reflexive verbs and daily routine vocabulary",
        "level_required": 1,
        "challenges": [
            {
                "id": "morn_levantarse",
                "title": "Levantarse - To Get Up",
                "type": "quiz",
                "question": "'Me levanto a las siete' means:",
                "options": ["I go to bed at seven", "I get up at seven", "I eat at seven", "I leave at seven"],
                "answer": "b",
                "hints": ["'Levantarse' = to get up/rise.", "'Me levanto' = I get up (reflexive)."],
                "xp": 25,
                "lesson": "'Levantarse' = to get up. 'Me levanto' = I get up. This is a reflexive verb -- the action is done to yourself. 'Se' at the end of an infinitive signals reflexive. 'Me levanto a las siete' = I get up at 7:00.",
            },
            {
                "id": "morn_ducharse",
                "title": "Ducharse - To Shower",
                "type": "quiz",
                "question": "What does 'ducharse' mean?",
                "options": ["To eat breakfast", "To get dressed", "To take a shower", "To brush teeth"],
                "answer": "c",
                "hints": ["'La ducha' = the shower.", "Another reflexive verb."],
                "xp": 25,
                "lesson": "'Ducharse' = to shower. 'Me ducho' = I shower. 'Banarse' = to bathe. Other bathroom reflexives: 'lavarse los dientes' (to brush teeth), 'lavarse la cara' (to wash face), 'peinarse' (to comb hair).",
            },
            {
                "id": "morn_vestirse",
                "title": "Vestirse - To Get Dressed",
                "type": "quiz",
                "question": "'Me visto despues de ducharme' means:",
                "options": ["I shower after getting dressed", "I get dressed after showering", "I eat after showering", "I leave after getting dressed"],
                "answer": "b",
                "hints": ["'Vestirse' = to get dressed.", "'Despues de' = after."],
                "xp": 25,
                "lesson": "'Vestirse' = to get dressed. 'Me visto' = I get dressed. 'La ropa' = clothes. 'Desvestirse' = to get undressed. 'Ponerse' = to put on (a specific item). 'Me pongo la chaqueta' = I put on my jacket.",
            },
            {
                "id": "morn_desayunar",
                "title": "Desayunar - To Have Breakfast",
                "type": "quiz",
                "question": "What does 'desayunar' mean?",
                "options": ["To have lunch", "To have breakfast", "To have dinner", "To cook"],
                "answer": "b",
                "hints": ["'Des-ayuno' = break the fast.", "It's the first meal of the day."],
                "xp": 25,
                "lesson": "'Desayunar' = to have breakfast (NOT reflexive). 'Desayuno a las ocho' = I have breakfast at 8:00. 'El desayuno' = breakfast (the noun). Common breakfast items: cafe con leche, tostadas (toast), fruta, cereales.",
            },
            {
                "id": "morn_acostarse",
                "title": "Acostarse - To Go to Bed",
                "type": "quiz",
                "question": "'Me acuesto a las once' means:",
                "options": ["I wake up at eleven", "I go to bed at eleven", "I eat at eleven", "I shower at eleven"],
                "answer": "b",
                "hints": ["'Acostarse' = to lie down/go to bed.", "It's the opposite of 'levantarse'."],
                "xp": 25,
                "lesson": "'Acostarse' = to go to bed. 'Me acuesto' = I go to bed. Note the stem change: o->ue. 'Dormirse' = to fall asleep. 'Me acuesto a las once y me duermo a las once y media' = I go to bed at 11 and fall asleep at 11:30.",
            },
            {
                "id": "morn_full_routine",
                "title": "My Full Routine",
                "type": "quiz",
                "question": "Put in correct morning order: 1) Me visto 2) Me levanto 3) Desayuno 4) Me ducho",
                "options": ["2, 4, 1, 3", "2, 1, 4, 3", "4, 2, 1, 3", "1, 2, 3, 4"],
                "answer": "a",
                "hints": ["Get up first, then shower, then dress, then eat.", "Logical morning flow."],
                "xp": 30,
                "lesson": "Typical morning: Me levanto (I get up) -> Me ducho (I shower) -> Me visto (I get dressed) -> Desayuno (I have breakfast). Then: 'Salgo de casa' (I leave the house). You can now describe a complete morning routine!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 2: School & Work --
    "school_work": {
        "id": "school_work",
        "name": "School & Work",
        "description": "Learn vocabulary for education and the workplace",
        "level_required": 1,
        "challenges": [
            {
                "id": "sw_escuela",
                "title": "La Escuela",
                "type": "quiz",
                "question": "What does 'la escuela' mean?",
                "options": ["The library", "The school", "The office", "The university"],
                "answer": "b",
                "hints": ["Think of 'school' -- same Latin root.", "Where children learn."],
                "xp": 25,
                "lesson": "'La escuela' = school. 'El colegio' = school (also common). 'La universidad' = university. 'El instituto' = high school (Spain). 'El/la maestro/a' = teacher (elementary). 'El/la profesor/a' = teacher/professor.",
            },
            {
                "id": "sw_trabajo",
                "title": "El Trabajo",
                "type": "quiz",
                "question": "What does 'trabajar' mean?",
                "options": ["To study", "To work", "To travel", "To teach"],
                "answer": "b",
                "hints": ["'El trabajo' = work/job.", "Related to English 'travail'."],
                "xp": 25,
                "lesson": "'Trabajar' = to work. 'El trabajo' = work/job. 'La oficina' = office. 'El/la jefe/a' = boss. 'El/la colega' = colleague. 'Trabajo de lunes a viernes' = I work Monday to Friday.",
            },
            {
                "id": "sw_estudiar",
                "title": "Estudiar - To Study",
                "type": "quiz",
                "question": "'Estudio espanol todos los dias' means:",
                "options": ["I speak Spanish every day", "I study Spanish every day", "I teach Spanish every day", "I read Spanish every day"],
                "answer": "b",
                "hints": ["'Estudiar' = to study.", "'Todos los dias' = every day."],
                "xp": 25,
                "lesson": "'Estudiar' = to study. 'Estudio espanol' = I study Spanish. 'El/la estudiante' = student. School subjects: matematicas (math), ciencias (science), historia (history), ingles (English), arte (art), musica (music).",
            },
            {
                "id": "sw_aprender",
                "title": "Aprender - To Learn",
                "type": "quiz",
                "question": "What's the difference between 'estudiar' and 'aprender'?",
                "options": ["No difference", "Estudiar = to study (the process), aprender = to learn (the result)", "Estudiar is formal, aprender is informal", "Estudiar is for school, aprender is for work"],
                "answer": "b",
                "hints": ["You study (put in effort) and then you learn (gain knowledge).", "'Aprendo mucho' = I learn a lot."],
                "xp": 25,
                "lesson": "'Estudiar' = to study (the effort). 'Aprender' = to learn (the result). 'Estudio todos los dias y aprendo mucho' = I study every day and learn a lot. 'Ensenar' = to teach. 'El profesor ensena y los estudiantes aprenden.'",
            },
            {
                "id": "sw_clase",
                "title": "La Clase",
                "type": "quiz",
                "question": "'Tengo clase a las nueve' means:",
                "options": ["I have class at nine", "I have a meeting at nine", "I teach a class at nine", "I finish class at nine"],
                "answer": "a",
                "hints": ["'Tengo' = I have, 'clase' = class.", "'A las nueve' = at nine."],
                "xp": 25,
                "lesson": "'La clase' = class. 'Tengo clase' = I have class. 'La tarea' = homework. 'El examen' = exam/test. 'La nota' = grade. 'Sacar buenas notas' = to get good grades. 'El horario' = schedule.",
            },
            {
                "id": "sw_profession",
                "title": "What Do You Do?",
                "type": "quiz",
                "question": "How do you ask 'What do you do for work?' in Spanish?",
                "options": ["Que haces?", "A que te dedicas?", "En que trabajas?", "All of these work"],
                "answer": "d",
                "hints": ["There are several natural ways to ask.", "'Dedicarse a' = to dedicate oneself to."],
                "xp": 30,
                "lesson": "Ways to ask about work: 'A que te dedicas?' (What do you do? -- most natural), 'En que trabajas?' (What do you work in?), 'Cual es tu profesion?' (What's your profession?). Answer: 'Soy ingeniero/a' (I'm an engineer), 'Trabajo en un banco' (I work in a bank).",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 3: Hobbies --
    "hobbies": {
        "id": "hobbies",
        "name": "Hobbies & Free Time",
        "description": "Talk about what you enjoy doing",
        "level_required": 2,
        "challenges": [
            {
                "id": "hob_leer",
                "title": "Leer - To Read",
                "type": "quiz",
                "question": "'Me gusta leer' means:",
                "options": ["I like to write", "I like to read", "I like to learn", "I like to listen"],
                "answer": "b",
                "hints": ["'Leer' = to read.", "'Me gusta' = I like (literally 'it pleases me')."],
                "xp": 25,
                "lesson": "'Leer' = to read. 'Me gusta leer' = I like to read. 'El libro' = book. 'La revista' = magazine. 'El periodico' = newspaper. 'Me gusta' + infinitive is the key pattern for talking about hobbies.",
            },
            {
                "id": "hob_bailar",
                "title": "Bailar - To Dance",
                "type": "quiz",
                "question": "What does 'bailar' mean?",
                "options": ["To sing", "To dance", "To play", "To paint"],
                "answer": "b",
                "hints": ["Think of a 'baile' (dance/ball).", "Salsa, flamenco, tango -- all involve this verb!"],
                "xp": 25,
                "lesson": "'Bailar' = to dance. 'El baile' = the dance. 'Cantar' = to sing. 'La musica' = music. Dancing is central to Spanish-speaking cultures -- from salsa to flamenco to tango to cumbia.",
            },
            {
                "id": "hob_jugar",
                "title": "Jugar - To Play",
                "type": "quiz",
                "question": "'Jugar al futbol' means:",
                "options": ["To watch soccer", "To play soccer", "To coach soccer", "To like soccer"],
                "answer": "b",
                "hints": ["'Jugar' = to play (a game/sport).", "'Futbol' = soccer (in most Spanish-speaking countries)."],
                "xp": 25,
                "lesson": "'Jugar' = to play (games/sports). 'Jugar al futbol' = to play soccer. Note: 'jugar a' + sport. 'Tocar' = to play (an instrument). 'Tocar la guitarra' = to play guitar. Different verbs for different types of play!",
            },
            {
                "id": "hob_nadar",
                "title": "Nadar - To Swim",
                "type": "quiz",
                "question": "What does 'nadar' mean?",
                "options": ["To run", "To swim", "To jump", "To climb"],
                "answer": "b",
                "hints": ["Think of a swimming pool or the ocean.", "Related to activities in water."],
                "xp": 25,
                "lesson": "'Nadar' = to swim. 'La piscina' = swimming pool. 'La playa' = beach. More sports/exercise: 'correr' (to run), 'caminar' (to walk), 'montar en bicicleta' (to ride a bike), 'hacer ejercicio' (to exercise).",
            },
            {
                "id": "hob_me_gusta",
                "title": "Me Gusta - I Like",
                "type": "quiz",
                "question": "How do you say 'I like to cook' using 'gustar'?",
                "options": ["Yo gusto cocinar", "Me gusta cocinar", "Gusto a cocinar", "Mi gusta cocinar"],
                "answer": "b",
                "hints": ["'Gustar' works backwards from English -- the thing pleases you.", "'Me gusta' + infinitive = I like to..."],
                "xp": 30,
                "lesson": "'Me gusta cocinar' = I like to cook. 'Gustar' works differently: ME gusta (I like), TE gusta (you like), LE gusta (he/she likes), NOS gusta (we like). The thing you like is the subject! 'Me gustan los libros' (I like books -- plural!).",
            },
            {
                "id": "hob_weekend",
                "title": "What Do You Do on Weekends?",
                "type": "quiz",
                "question": "'Que haces los fines de semana?' -- How do you answer 'I like to read and swim'?",
                "options": ["Me gustan leer y nadar", "Me gusta leer y nadar", "Yo gusto leer y nadar", "Gusto de leer y nadar"],
                "answer": "b",
                "hints": ["Two infinitives connected by 'y' (and).", "'Me gusta' stays singular because the subject is the activity."],
                "xp": 30,
                "lesson": "'Me gusta leer y nadar' = I like to read and swim. When listing hobbies, 'me gusta' stays singular before infinitives. Full exchange: 'Que haces los fines de semana?' 'Me gusta leer, nadar, y cocinar.' Natural conversation!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 4: Weather --
    "weather": {
        "id": "weather",
        "name": "The Weather",
        "description": "Talk about weather conditions and seasons",
        "level_required": 2,
        "challenges": [
            {
                "id": "wx_que_tiempo",
                "title": "What's the Weather Like?",
                "type": "quiz",
                "question": "How do you ask 'What's the weather like?' in Spanish?",
                "options": ["Que hora es?", "Que tiempo hace?", "Como esta el dia?", "Both B and C work"],
                "answer": "d",
                "hints": ["'Tiempo' can mean weather or time.", "'Hacer' is used for most weather expressions."],
                "xp": 25,
                "lesson": "'Que tiempo hace?' = What's the weather like? (Most standard). 'Como esta el dia?' also works. Note: 'tiempo' means both 'weather' and 'time' -- context tells you which. Spanish uses 'hacer' (to do/make) for weather!",
            },
            {
                "id": "wx_hace_calor",
                "title": "It's Hot",
                "type": "quiz",
                "question": "'Hace calor' literally means 'It makes heat.' What does it really mean?",
                "options": ["It's cold", "It's windy", "It's hot", "It's raining"],
                "answer": "c",
                "hints": ["'Calor' = heat.", "'Hace' + noun = weather expression."],
                "xp": 25,
                "lesson": "'Hace calor' = It's hot. 'Hace mucho calor' = It's very hot. 'Tengo calor' = I'm hot (personally). Note the difference: 'hace calor' (the weather is hot) vs 'tengo calor' (I feel hot). Spanish uses 'tener' for personal sensations!",
            },
            {
                "id": "wx_hace_frio",
                "title": "It's Cold",
                "type": "quiz",
                "question": "How do you say 'It's cold outside'?",
                "options": ["Hace frio afuera", "Esta frio afuera", "Tiene frio afuera", "Es frio afuera"],
                "answer": "a",
                "hints": ["Weather uses 'hacer' -- 'hace frio'.", "'Afuera' = outside."],
                "xp": 25,
                "lesson": "'Hace frio' = It's cold (weather). 'Hace fresco' = It's cool/chilly. 'Hace viento' = It's windy. 'Hace sol' = It's sunny. 'Hace buen tiempo' = The weather is nice. 'Hace mal tiempo' = The weather is bad.",
            },
            {
                "id": "wx_llueve",
                "title": "It's Raining",
                "type": "quiz",
                "question": "Which is correct for 'It's raining'?",
                "options": ["Hace lluvia", "Llueve", "Esta lloviendo", "Both B and C are correct"],
                "answer": "d",
                "hints": ["Rain and snow use their own verbs, not 'hacer'.", "'Llover' = to rain, 'nevar' = to snow."],
                "xp": 25,
                "lesson": "'Llueve' (It rains/It's raining) or 'Esta lloviendo' (It's raining right now). Rain and snow get their own verbs instead of 'hacer': 'llover' (to rain), 'nevar' (to snow). 'Llueve mucho' = It rains a lot. 'Nieva en invierno' = It snows in winter.",
            },
            {
                "id": "wx_nieva",
                "title": "It's Snowing",
                "type": "quiz",
                "question": "What does 'Nieva en las montanas' mean?",
                "options": ["It's raining in the mountains", "It's snowing in the mountains", "It's windy in the mountains", "It's cold in the mountains"],
                "answer": "b",
                "hints": ["'Nevar' = to snow, 'nieva' = it snows.", "'Las montanas' = the mountains."],
                "xp": 25,
                "lesson": "'Nieva' = It snows/It's snowing. 'La nieve' = snow. 'Nieva en las montanas' = It snows in the mountains. Fun fact: several Spanish-speaking countries have snow in their mountains -- the Andes, the Sierra Nevada in Spain, and more.",
            },
            {
                "id": "wx_forecast",
                "title": "The Weather Report",
                "type": "quiz",
                "question": "'Manana va a hacer sol y calor, con temperaturas de 30 grados.' What's tomorrow's forecast?",
                "options": ["Cold and rainy, 30 degrees", "Sunny and hot, 30 degrees", "Cloudy and cool, 30 degrees", "Snowy and windy, 30 degrees"],
                "answer": "b",
                "hints": ["'Sol' = sun, 'calor' = heat.", "30 grados Celsius = about 86F."],
                "xp": 30,
                "lesson": "'Manana va a hacer sol y calor' = Tomorrow it will be sunny and hot. 'Va a' + infinitive = going to (future). Remember: Spanish-speaking countries use Celsius! 30C = 86F. 'Los grados' = degrees. 'El pronostico' = the forecast.",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 5: Shopping --
    "shopping": {
        "id": "shopping",
        "name": "Shopping",
        "description": "Navigate stores, ask prices, and make purchases",
        "level_required": 3,
        "challenges": [
            {
                "id": "shop_tienda",
                "title": "La Tienda",
                "type": "quiz",
                "question": "What does 'la tienda' mean?",
                "options": ["The tent", "The store/shop", "The market", "The mall"],
                "answer": "b",
                "hints": ["It can also mean 'tent' in some contexts.", "It's the general word for a shop."],
                "xp": 25,
                "lesson": "'La tienda' = store/shop. Types: 'la tienda de ropa' (clothing store), 'la tienda de zapatos' (shoe store), 'el supermercado' (supermarket), 'el mercado' (market), 'el centro comercial' (mall/shopping center).",
            },
            {
                "id": "shop_comprar",
                "title": "Comprar - To Buy",
                "type": "quiz",
                "question": "What does 'comprar' mean?",
                "options": ["To sell", "To buy", "To compare", "To count"],
                "answer": "b",
                "hints": ["Think of 'compras' (purchases/shopping).", "'Ir de compras' = to go shopping."],
                "xp": 25,
                "lesson": "'Comprar' = to buy. 'Vender' = to sell. 'Ir de compras' = to go shopping. 'Las compras' = purchases/shopping. 'Quiero comprar...' = I want to buy... 'Donde puedo comprar...?' = Where can I buy...?",
            },
            {
                "id": "shop_cuanto_cuesta",
                "title": "How Much Does It Cost?",
                "type": "quiz",
                "question": "How do you ask 'How much does it cost?'",
                "options": ["Que precio?", "Cuanto cuesta?", "Cuanto es?", "Both B and C work"],
                "answer": "d",
                "hints": ["'Cuanto' = how much, 'cuesta' = it costs.", "'Cuanto es?' is more informal but equally common."],
                "xp": 25,
                "lesson": "'Cuanto cuesta?' or 'Cuanto es?' = How much does it cost? For plural: 'Cuanto cuestan?' (How much do they cost?). 'Cuesta 10 euros' = It costs 10 euros. This is the #1 shopping phrase!",
            },
            {
                "id": "shop_barato_caro",
                "title": "Cheap & Expensive",
                "type": "quiz",
                "question": "If something is 'caro,' it is:",
                "options": ["Cheap", "Free", "Expensive", "On sale"],
                "answer": "c",
                "hints": ["The opposite of 'barato' (cheap).", "You might say 'Es muy caro!' when negotiating."],
                "xp": 25,
                "lesson": "'Caro' = expensive, 'barato' = cheap. 'Es muy caro!' (It's too expensive!), 'Es bastante barato' (It's pretty cheap). 'Tiene algo mas barato?' = Do you have something cheaper? 'Esta en oferta' = It's on sale. 'Gratis' = free.",
            },
            {
                "id": "shop_sizes",
                "title": "Sizes & Trying On",
                "type": "quiz",
                "question": "How do you ask 'Can I try it on?' at a clothing store?",
                "options": ["Puedo comprarlo?", "Puedo probarmelo?", "Puedo verlo?", "Puedo tocarlo?"],
                "answer": "b",
                "hints": ["'Probar' = to try, 'probarse' = to try on (reflexive).", "Essential in clothing stores."],
                "xp": 30,
                "lesson": "'Puedo probarmelo?' = Can I try it on? 'El probador' = fitting room. Sizes: 'pequeno' (small), 'mediano' (medium), 'grande' (large). 'Tiene una talla mas grande/pequena?' = Do you have a bigger/smaller size?",
            },
            {
                "id": "shop_transaction",
                "title": "Making the Purchase",
                "type": "quiz",
                "question": "You want to buy something. 'Me lo llevo' means:",
                "options": ["I'll leave it", "I'll take it", "I'll return it", "I'll think about it"],
                "answer": "b",
                "hints": ["'Llevar' = to take/carry.", "'Me lo llevo' = I'll take it (for myself)."],
                "xp": 30,
                "lesson": "'Me lo llevo' = I'll take it. 'Puede pagar en efectivo o con tarjeta' = You can pay in cash or by card. 'El efectivo' = cash. 'La tarjeta' = card. 'El recibo' = receipt. 'La bolsa' = bag. Complete shopping vocabulary!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 6: Body & Health --
    "body_health": {
        "id": "body_health",
        "name": "Body & Health",
        "description": "Learn body parts, symptoms, and health vocabulary",
        "level_required": 3,
        "challenges": [
            {
                "id": "bh_cabeza",
                "title": "La Cabeza",
                "type": "quiz",
                "question": "What is 'la cabeza'?",
                "options": ["The hand", "The foot", "The head", "The arm"],
                "answer": "c",
                "hints": ["Think of the English phrase 'from head to toe' -- 'cabeza' is the first one.", "'Dolor de cabeza' = headache."],
                "xp": 25,
                "lesson": "'La cabeza' = head. 'La cara' = face. 'El pelo/cabello' = hair. 'La frente' = forehead. 'Me duele la cabeza' = My head hurts (I have a headache). Body parts use the definite article (la/el), not possessive (mi).",
            },
            {
                "id": "bh_mano_pie",
                "title": "Hands & Feet",
                "type": "quiz",
                "question": "What is 'la mano'?",
                "options": ["The foot", "The hand", "The finger", "The arm"],
                "answer": "b",
                "hints": ["Think of 'manual' or 'manipulate' in English.", "Fun fact: 'mano' ends in -o but is feminine!"],
                "xp": 25,
                "lesson": "'La mano' = hand (feminine despite ending in -o!). 'El pie' = foot. 'El dedo' = finger/toe. 'El dedo del pie' = toe. 'El brazo' = arm. 'La pierna' = leg. 'La mano' is one of the tricky gender exceptions!",
            },
            {
                "id": "bh_ojo",
                "title": "Eyes, Ears, Mouth",
                "type": "quiz",
                "question": "Match: 'el ojo' = eye. What is 'la boca'?",
                "options": ["Ear", "Nose", "Mouth", "Chin"],
                "answer": "c",
                "hints": ["Think of the English 'vocal' -- related to the mouth.", "It's where you eat and speak."],
                "xp": 25,
                "lesson": "Face parts: 'el ojo' (eye), 'la nariz' (nose), 'la boca' (mouth), 'la oreja/el oido' (ear -- oreja is outer, oido is inner), 'los dientes' (teeth), 'la lengua' (tongue). 'Ojo!' is also used as 'Watch out!'",
            },
            {
                "id": "bh_me_duele",
                "title": "It Hurts!",
                "type": "quiz",
                "question": "How do you say 'My stomach hurts'?",
                "options": ["Mi estomago es mal", "Me duele el estomago", "Estoy estomago dolor", "Tengo mal estomago"],
                "answer": "b",
                "hints": ["'Doler' works like 'gustar' -- the body part is the subject.", "'Me duele' = it hurts me."],
                "xp": 25,
                "lesson": "'Me duele el estomago' = My stomach hurts. 'Doler' works like 'gustar': 'Me duele la cabeza' (my head hurts), 'Me duelen los pies' (my feet hurt -- plural!). Use 'duele' for singular, 'duelen' for plural body parts.",
            },
            {
                "id": "bh_estoy_enfermo",
                "title": "I'm Sick",
                "type": "quiz",
                "question": "How do you say 'I am sick'?",
                "options": ["Soy enfermo", "Estoy enfermo/a", "Tengo enfermo", "Hago enfermo"],
                "answer": "b",
                "hints": ["Being sick is temporary, so use 'estar' not 'ser'.", "Add -a for feminine: enferma."],
                "xp": 30,
                "lesson": "'Estoy enfermo/a' = I'm sick (temporary state = estar). 'Tengo fiebre' = I have a fever. 'Tengo tos' = I have a cough. 'Estoy resfriado/a' = I have a cold. 'Tengo gripe' = I have the flu. Health uses a mix of 'estar' and 'tener.'",
            },
            {
                "id": "bh_doctor_visit",
                "title": "At the Doctor",
                "type": "quiz",
                "question": "The doctor asks 'Que le pasa?' (What's wrong?). Which is a complete answer?",
                "options": ["Me duele la cabeza y tengo fiebre", "Soy cabeza dolor", "Mi dolor es fiebre", "Estar enfermo cabeza"],
                "answer": "a",
                "hints": ["Combine 'me duele' with 'tengo' for symptoms.", "My head hurts AND I have a fever."],
                "xp": 35,
                "lesson": "'Me duele la cabeza y tengo fiebre' = My head hurts and I have a fever. At the doctor: 'Que le pasa?' (What's wrong?), 'Desde cuando?' (Since when?), 'Tome esta medicina' (Take this medicine), 'Descanse' (Rest). You can now handle a doctor visit!",
                "is_boss": True,
            },
        ],
    },
}
