"""
zones.py — Ocean Explorers zones and challenges for the Oceans skill pack.

All challenges use "type": "quiz" with multiple-choice options.
Designed for ages 7-10, guided warmly by Puck.
"""

ZONE_ORDER = [
    "ocean_zones",
    "marine_mammals",
    "coral_reefs",
    "deep_sea",
    "ocean_currents",
    "sharks_and_rays",
    "ocean_conservation",
]

ZONES = {
    "ocean_zones": {
        "id": "ocean_zones",
        "name": "Layers of the Sea",
        "description": "Discover what lives in each layer of the ocean, from sunlit surface to pitch-black abyss",
        "level_required": 1,
        "challenges": [
            {
                "id": "sunlight_zone",
                "title": "Where the Sun Shines",
                "type": "quiz",
                "question": "The top layer of the ocean is called the sunlight zone. Why is it given that name?",
                "options": [
                    "It is the warmest zone",
                    "Sunlight can reach it, so plants and algae can grow there",
                    "It is the only zone with waves",
                    "It glows yellow at night",
                ],
                "answer": "b",
                "hints": [
                    "Think about what plants need to grow — they need light!",
                    "This zone goes down to about 200 metres, where sunlight can still reach.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The sunlight zone (also called the epipelagic zone) is the top 200 metres of the ocean. Sunlight reaches here, so phytoplankton and seaweed can photosynthesise. About 90% of all ocean life lives in this zone!",
                "is_boss": False,
                "flavor": "Puck peers through the submarine window at sparkling blue water full of tiny fish.",
            },
            {
                "id": "twilight_zone",
                "title": "The Fading Light",
                "type": "quiz",
                "question": "The twilight zone sits below the sunlight zone. What is special about the light there?",
                "options": [
                    "It is completely dark — no light at all",
                    "Only dim, bluish light reaches it — not enough for plants to grow",
                    "It is brighter than the sunlight zone",
                    "Red light fills the water",
                ],
                "answer": "b",
                "hints": [
                    "Think of twilight on land — the sky isn't fully dark yet, but the sun has set.",
                    "Some light gets through, but not enough for photosynthesis.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The twilight zone (mesopelagic zone) stretches from 200 to 1,000 metres deep. Only faint blue light filters down. No plants grow here, but many animals — like lanternfish and jellyfish — live in this dim world.",
                "is_boss": False,
                "flavor": "The submarine sinks deeper. The water turns from blue to dusky purple.",
            },
            {
                "id": "midnight_zone",
                "title": "Total Darkness",
                "type": "quiz",
                "question": "The midnight zone is completely dark. How do some animals see in this zone?",
                "options": [
                    "They use echolocation like bats",
                    "Their eyes adjust to the dark over time",
                    "Some animals make their own light — called bioluminescence",
                    "They cannot see at all and never move",
                ],
                "answer": "c",
                "hints": [
                    "Some deep-sea creatures glow! They carry their own tiny lanterns.",
                    "The word 'bio' means life, and 'luminescence' means light.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The midnight zone (bathypelagic zone) is 1,000 to 4,000 metres deep. No sunlight reaches here at all. Many creatures produce bioluminescence — their own living light — to hunt, communicate, or scare predators.",
                "is_boss": False,
                "flavor": "Puck flicks off the submarine lights. In the darkness, tiny blue and green sparks drift past the window.",
            },
            {
                "id": "abyssal_zone",
                "title": "The Abyss",
                "type": "quiz",
                "question": "The abyssal zone is one of the deepest parts of the ocean. What is the water pressure like down there?",
                "options": [
                    "Very low — almost like outer space",
                    "The same as on the surface",
                    "Extremely high — it would crush a human without protection",
                    "There is no water pressure in the deep ocean",
                ],
                "answer": "c",
                "hints": [
                    "All the water above pushes down on everything below it.",
                    "Special submarines need super-strong hulls to survive down there.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The abyssal zone (4,000 to 6,000 metres deep) has crushing pressure — over 400 times the pressure at the surface. The water is near freezing and pitch black. Yet life still exists here: sea cucumbers, small squid, and strange worms.",
                "is_boss": False,
                "flavor": "The submarine creaks under the pressure. Puck pats the hull reassuringly.",
            },
            {
                "id": "most_life_zone",
                "title": "Where Life Thrives",
                "type": "quiz",
                "question": "Which ocean zone contains the most marine life?",
                "options": [
                    "The midnight zone",
                    "The abyssal zone",
                    "The twilight zone",
                    "The sunlight zone",
                ],
                "answer": "d",
                "hints": [
                    "Plants need light to grow, and tiny plants are the base of the food chain.",
                    "This is the shallowest zone — the top 200 metres.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The sunlight zone holds about 90% of all ocean life. Sunlight powers phytoplankton, which feed tiny animals, which feed fish, which feed larger predators. It all starts with the sun reaching the water.",
                "is_boss": False,
                "flavor": "Schools of colourful fish swirl past the submarine. Puck grins. \"Life loves the light!\"",
            },
            {
                "id": "zone_order_boss",
                "title": "Name That Layer",
                "type": "quiz",
                "question": "Starting from the surface and going down, what is the correct order of ocean zones?",
                "options": [
                    "Twilight, Sunlight, Midnight, Abyssal",
                    "Sunlight, Twilight, Midnight, Abyssal",
                    "Midnight, Abyssal, Sunlight, Twilight",
                    "Abyssal, Midnight, Twilight, Sunlight",
                ],
                "answer": "b",
                "hints": [
                    "The sunniest zone is on top. Then the light fades, then disappears.",
                    "Think: bright, dim, dark, crushing deep.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "From the surface down: Sunlight (0-200m), Twilight (200-1,000m), Midnight (1,000-4,000m), Abyssal (4,000-6,000m). Below the abyss lies the hadal zone in the deepest ocean trenches!",
                "is_boss": True,
                "flavor": "Puck draws a tall diagram on the submarine wall — four layers, each darker than the last.",
            },
        ],
    },
    "marine_mammals": {
        "id": "marine_mammals",
        "name": "Warm Hearts, Cold Water",
        "description": "Meet the warm-blooded animals that call the ocean home",
        "level_required": 3,
        "challenges": [
            {
                "id": "whale_breathing",
                "title": "Coming Up for Air",
                "type": "quiz",
                "question": "Whales live in the ocean, but they are mammals. What must they do that fish never need to?",
                "options": [
                    "Drink salt water",
                    "Come to the surface to breathe air",
                    "Sleep on land every night",
                    "Eat seaweed to survive",
                ],
                "answer": "b",
                "hints": [
                    "Mammals breathe air with lungs — not gills.",
                    "Whales have a blowhole on top of their heads for this reason.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Whales are mammals, not fish. They breathe air through a blowhole on top of their head. Some whales, like sperm whales, can hold their breath for over an hour before surfacing!",
                "is_boss": False,
                "flavor": "A great spray of mist shoots up ahead. Puck claps. \"There she blows!\"",
            },
            {
                "id": "dolphin_intelligence",
                "title": "Clever Swimmers",
                "type": "quiz",
                "question": "Dolphins are known for being very intelligent. Which of these is something dolphins actually do?",
                "options": [
                    "They use tools — pushing sponges on their noses to protect them while hunting",
                    "They build underwater nests from coral",
                    "They can read human writing",
                    "They hibernate during winter",
                ],
                "answer": "a",
                "hints": [
                    "Some dolphins in Australia have been seen doing this clever trick.",
                    "They put something soft on their snout to avoid getting scratched on the sea floor.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Bottlenose dolphins in Shark Bay, Australia, use sea sponges as tools! They put sponges on their snouts to protect themselves while digging in the sandy sea floor for fish. Dolphins also have names — each dolphin has a unique whistle that other dolphins use to call it.",
                "is_boss": False,
                "flavor": "A pod of dolphins races alongside the submarine, clicking and whistling.",
            },
            {
                "id": "seal_vs_sea_lion",
                "title": "Seals and Sea Lions",
                "type": "quiz",
                "question": "What is one easy way to tell a seal apart from a sea lion?",
                "options": [
                    "Seals are always bigger than sea lions",
                    "Sea lions have visible ear flaps; seals just have tiny ear holes",
                    "Seals live only in fresh water",
                    "Sea lions cannot swim",
                ],
                "answer": "b",
                "hints": [
                    "Look at the sides of their heads — one has flaps, the other doesn't.",
                    "Sea lions can also walk on their flippers, while seals scoot on their bellies.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Sea lions have small ear flaps you can see, and they can rotate their back flippers to walk on land. Seals have only tiny ear holes, and they wriggle on their bellies because their back flippers point backward. Both are pinnipeds — fin-footed mammals!",
                "is_boss": False,
                "flavor": "A whiskered face pops up beside the submarine and stares right at Puck.",
            },
            {
                "id": "sea_otter_tool",
                "title": "The Floating Toolmaker",
                "type": "quiz",
                "question": "Sea otters use rocks as tools. What do they use them for?",
                "options": [
                    "Building dams in rivers",
                    "Cracking open shellfish like clams and sea urchins",
                    "Digging burrows on the ocean floor",
                    "Sharpening their claws",
                ],
                "answer": "b",
                "hints": [
                    "They float on their backs and smash something against the rock.",
                    "Their favourite foods have hard shells that need breaking open.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Sea otters float on their backs and place a rock on their chest, then smash shellfish against it to crack them open. They are one of the few animals that use tools! Sea otters also wrap themselves in kelp while sleeping so they don't drift away.",
                "is_boss": False,
                "flavor": "Puck watches a furry otter floating on its back, tapping away at a clam. \"Clever little engineer!\"",
            },
            {
                "id": "blue_whale_size",
                "title": "The Biggest Animal Ever",
                "type": "quiz",
                "question": "The blue whale is the largest animal that has ever lived on Earth. How long can a blue whale grow?",
                "options": [
                    "About 10 metres — the length of a school bus",
                    "About 30 metres — longer than two school buses end to end",
                    "About 5 metres — the length of a car",
                    "About 100 metres — the length of a football field",
                ],
                "answer": "b",
                "hints": [
                    "It's longer than any dinosaur that ever lived.",
                    "Its heart alone is the size of a small car!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Blue whales can grow up to 30 metres long and weigh as much as 200 tonnes. Their hearts are the size of a small car, and a child could crawl through their largest arteries. They are bigger than any dinosaur that ever existed!",
                "is_boss": False,
                "flavor": "A vast blue shadow glides beneath the submarine. Puck's eyes go wide. \"That's... really, really big.\"",
            },
            {
                "id": "warm_blooded_boss",
                "title": "Warm Blood in Cold Seas",
                "type": "quiz",
                "question": "Marine mammals are warm-blooded, but the deep ocean is freezing cold. What helps most marine mammals stay warm?",
                "options": [
                    "They shiver constantly to generate heat",
                    "A thick layer of fat called blubber insulates their bodies",
                    "They only live in tropical waters",
                    "They wear shells like sea turtles",
                ],
                "answer": "b",
                "hints": [
                    "It's a layer of something under their skin — like a built-in wetsuit.",
                    "Whale blubber can be up to 30 centimetres thick!",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Blubber is a thick layer of fat beneath the skin that acts as insulation, keeping body heat in and cold water out. Whales, seals, and walruses all have blubber. Sea otters are different — they have the densest fur of any animal instead!",
                "is_boss": True,
                "flavor": "Puck wraps a tiny blanket around their shoulders. \"Blubber is basically the ocean's best winter coat.\"",
            },
        ],
    },
    "coral_reefs": {
        "id": "coral_reefs",
        "name": "Cities of the Sea",
        "description": "Explore the colourful world of coral reefs and the creatures that depend on them",
        "level_required": 5,
        "challenges": [
            {
                "id": "what_is_coral",
                "title": "Rock, Plant, or Animal?",
                "type": "quiz",
                "question": "Coral looks like colourful rock or a plant, but what is it really?",
                "options": [
                    "A type of underwater rock",
                    "A colony of tiny animals called polyps",
                    "A type of seaweed that turns hard",
                    "A mineral that grows on the sea floor",
                ],
                "answer": "b",
                "hints": [
                    "Each little piece of coral is actually a living creature!",
                    "They are related to jellyfish and sea anemones.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Coral is made up of thousands of tiny animals called polyps. Each polyp is soft-bodied, like a tiny sea anemone, and builds a hard skeleton of calcium carbonate around itself. Over time, millions of these skeletons build up into a reef!",
                "is_boss": False,
                "flavor": "Puck lands on what looks like a colourful rock and jumps back. \"It's alive!\"",
            },
            {
                "id": "zooxanthellae",
                "title": "A Colourful Partnership",
                "type": "quiz",
                "question": "Coral gets its beautiful colours from tiny algae that live inside it. What do the algae give the coral in return for a home?",
                "options": [
                    "Protection from predators",
                    "Food — the algae make food from sunlight and share it",
                    "A harder skeleton",
                    "The ability to move around the reef",
                ],
                "answer": "b",
                "hints": [
                    "The algae do something with sunlight — just like plants on land.",
                    "This partnership gives coral up to 90% of the energy it needs.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Tiny algae called zooxanthellae live inside coral polyps. They use sunlight to make food through photosynthesis and share it with the coral — providing up to 90% of the coral's energy. In return, the coral gives the algae a safe home. This is called a symbiotic relationship!",
                "is_boss": False,
                "flavor": "Puck zooms in on a coral polyp. Inside, tiny golden-green algae glow like jewels.",
            },
            {
                "id": "reef_biodiversity",
                "title": "Underwater Rainforests",
                "type": "quiz",
                "question": "Coral reefs cover less than 1% of the ocean floor, but how much of all ocean species do they support?",
                "options": [
                    "About 1% — just a tiny fraction",
                    "About 10% — a small share",
                    "About 25% — a quarter of all ocean species",
                    "About 75% — almost everything in the sea",
                ],
                "answer": "c",
                "hints": [
                    "Reefs are often called the rainforests of the sea — and rainforests are known for incredible biodiversity.",
                    "It's much more than you might expect from such a small area!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Coral reefs support roughly 25% of all marine species despite covering less than 1% of the ocean floor. They are home to fish, sea turtles, octopuses, seahorses, eels, shrimp, and thousands more. That is why they are called the rainforests of the sea!",
                "is_boss": False,
                "flavor": "Puck counts fish species swimming past: \"One, two, five, twelve, twenty... I've lost count!\"",
            },
            {
                "id": "great_barrier_reef",
                "title": "The World's Biggest Reef",
                "type": "quiz",
                "question": "The Great Barrier Reef is the largest coral reef system on Earth. Where is it located?",
                "options": [
                    "Off the coast of Brazil",
                    "In the Caribbean Sea near Florida",
                    "Off the northeast coast of Australia",
                    "In the Red Sea near Egypt",
                ],
                "answer": "c",
                "hints": [
                    "This reef is so big it can be seen from space!",
                    "It lies near a continent that is also a country in the Southern Hemisphere.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The Great Barrier Reef stretches over 2,300 kilometres along the northeast coast of Australia. It is made up of nearly 3,000 individual reef systems and is home to 1,500 species of fish. It is so large it can be seen from outer space!",
                "is_boss": False,
                "flavor": "The submarine rises over an endless garden of coral. Puck gasps. \"It just... keeps going!\"",
            },
            {
                "id": "coral_bleaching_boss",
                "title": "When Coral Turns White",
                "type": "quiz",
                "question": "Sometimes coral turns completely white — this is called coral bleaching. What causes it?",
                "options": [
                    "Too much salt in the water",
                    "Sharks bumping into the reef",
                    "The water gets too warm, and the coral expels its algae",
                    "Fishermen painting the coral",
                ],
                "answer": "c",
                "hints": [
                    "Remember the tiny algae that give coral its colour and food?",
                    "When the ocean temperature rises even a little, the coral gets stressed.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "When ocean water gets too warm, coral becomes stressed and pushes out the zooxanthellae algae that give it colour and food. The coral turns ghostly white — bleached. If the water stays warm too long, the coral can starve and die. Rising ocean temperatures from climate change are the biggest cause of mass bleaching events.",
                "is_boss": True,
                "flavor": "Puck touches a white coral branch sadly. \"It's still alive — but it's hungry and scared. It needs the water to cool down.\"",
            },
        ],
    },
    "deep_sea": {
        "id": "deep_sea",
        "name": "Into the Abyss",
        "description": "Explore the strangest creatures and places in the deep ocean",
        "level_required": 7,
        "challenges": [
            {
                "id": "anglerfish_lure",
                "title": "The Lantern Hunter",
                "type": "quiz",
                "question": "The anglerfish has a glowing lure dangling from its head. What does it use this lure for?",
                "options": [
                    "To light its way through the dark water",
                    "To attract prey close enough to catch",
                    "To signal to other anglerfish during mating season",
                    "To scare away predators",
                ],
                "answer": "b",
                "hints": [
                    "In the pitch-black deep sea, other animals are drawn to any light they see.",
                    "The anglerfish sits very still and waits for curious prey to come close.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The anglerfish uses bioluminescence — light produced by bacteria in its lure — to attract prey in the pitch-dark deep ocean. When a curious fish swims close to investigate the glow, the anglerfish snaps it up with its enormous jaws!",
                "is_boss": False,
                "flavor": "A tiny blue light bobs in the darkness ahead. Puck whispers, \"Don't swim toward it...\"",
            },
            {
                "id": "giant_squid",
                "title": "The Kraken's Cousin",
                "type": "quiz",
                "question": "The giant squid is one of the largest invertebrates on Earth. How big can its eyes grow?",
                "options": [
                    "As big as a marble",
                    "As big as a tennis ball",
                    "As big as a dinner plate — about 25 centimetres across",
                    "As big as a car tyre",
                ],
                "answer": "c",
                "hints": [
                    "It has the largest eyes of any animal alive today.",
                    "Big eyes help it catch every tiny bit of light in the deep, dark water.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Giant squid can grow up to 13 metres long and have the largest eyes in the animal kingdom — up to 25 cm (10 inches) across, about the size of a dinner plate! These huge eyes help them detect faint bioluminescent light in the deep ocean.",
                "is_boss": False,
                "flavor": "Two enormous eyes catch the submarine's lights. Puck hides behind a seat.",
            },
            {
                "id": "hydrothermal_vents",
                "title": "Underwater Chimneys",
                "type": "quiz",
                "question": "Hydrothermal vents are cracks in the ocean floor that shoot out super-heated water. What is surprising about these vents?",
                "options": [
                    "The water is ice cold",
                    "Nothing can live anywhere near them",
                    "Entire ecosystems of strange creatures thrive around them without sunlight",
                    "They only exist in shallow water",
                ],
                "answer": "c",
                "hints": [
                    "These vents are in total darkness on the deep sea floor, yet life surrounds them.",
                    "Instead of sunlight, these creatures use chemicals from the vents for energy.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Hydrothermal vents blast water heated to over 400 degrees Celsius from cracks in the ocean floor. Despite the extreme heat, darkness, and pressure, whole ecosystems thrive here — giant tube worms, eyeless shrimp, and strange bacteria that use chemical energy instead of sunlight. This is called chemosynthesis!",
                "is_boss": False,
                "flavor": "Black smoke billows from a crack in the sea floor. Strange white worms wave gently around it. Puck stares. \"Life finds a way.\"",
            },
            {
                "id": "bioluminescence_purpose",
                "title": "Living Light Show",
                "type": "quiz",
                "question": "Many deep-sea creatures produce their own light — bioluminescence. Which of these is NOT a reason animals use bioluminescence?",
                "options": [
                    "To attract prey toward them",
                    "To communicate with others of their species",
                    "To warm up the cold deep-sea water around them",
                    "To startle or confuse predators",
                ],
                "answer": "c",
                "hints": [
                    "Bioluminescence produces light but almost no heat at all.",
                    "Three of these answers are real uses. One is made up — which one seems wrong?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Bioluminescence is used for three main purposes: hunting (attracting or spotting prey), communication (finding mates), and defence (startling predators or creating a smokescreen of light). It produces almost no heat — it is called 'cold light.' Over 90% of deep-sea animals are bioluminescent!",
                "is_boss": False,
                "flavor": "Puck dims the submarine lights. The water erupts in blue, green, and purple sparks. \"It's like the ocean has its own stars!\"",
            },
            {
                "id": "mariana_trench",
                "title": "The Deepest Place on Earth",
                "type": "quiz",
                "question": "The Mariana Trench is the deepest point in any ocean. How deep is its lowest point, the Challenger Deep?",
                "options": [
                    "About 1,000 metres — deeper than any building is tall",
                    "About 5,000 metres — deeper than most mountains are high",
                    "About 11,000 metres — deeper than Mount Everest is tall",
                    "About 20,000 metres — twice the height of Mount Everest",
                ],
                "answer": "c",
                "hints": [
                    "If you put Mount Everest at the bottom of this trench, its peak would still be underwater.",
                    "It is nearly 11 kilometres below the surface.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "The Challenger Deep in the Mariana Trench is about 10,935 metres (nearly 11 km) below the surface — the deepest known point in any ocean. If Mount Everest (8,849m) were placed at the bottom, its summit would still be more than 2 km underwater!",
                "is_boss": True,
                "flavor": "The depth gauge ticks past 10,000 metres. Puck whispers, \"We're deeper than Everest is tall. Nobody said exploring was easy.\"",
            },
        ],
    },
    "ocean_currents": {
        "id": "ocean_currents",
        "name": "The River in the Sea",
        "description": "Learn how invisible rivers flow through the ocean, shaping weather and life around the world",
        "level_required": 10,
        "challenges": [
            {
                "id": "what_are_currents",
                "title": "Rivers Without Banks",
                "type": "quiz",
                "question": "Ocean currents are like giant rivers flowing through the sea. What is the main force that drives surface currents?",
                "options": [
                    "The Moon's gravity",
                    "Wind blowing across the ocean surface",
                    "Fish swimming in large groups",
                    "Underwater volcanoes pushing water",
                ],
                "answer": "b",
                "hints": [
                    "The same force that makes waves also pushes water across great distances.",
                    "Steady global winds push water in predictable patterns.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Surface ocean currents are mainly driven by wind. Global wind patterns push water across the ocean surface in great loops called gyres. Other factors — like the Earth's rotation, temperature, and salinity — also play a role. Deep-water currents are driven by temperature and salt differences.",
                "is_boss": False,
                "flavor": "Puck drops a tiny paper boat on the water. It sails away without any wind. \"The ocean has its own highways!\"",
            },
            {
                "id": "gulf_stream",
                "title": "The Warm Highway",
                "type": "quiz",
                "question": "The Gulf Stream is a powerful, warm ocean current. Where does it flow?",
                "options": [
                    "From the Arctic down to Africa",
                    "From the Gulf of Mexico up along the east coast of North America toward Europe",
                    "Around Antarctica in a circle",
                    "From Australia to South America",
                ],
                "answer": "b",
                "hints": [
                    "Its name gives a clue — it starts near the Gulf of Mexico.",
                    "It carries warm water northeast, keeping parts of Europe warmer than you'd expect.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The Gulf Stream carries warm water from the Gulf of Mexico northward along the US east coast, then across the Atlantic toward Europe. It moves 30 times more water than all the world's rivers combined! It keeps western Europe much warmer than it would otherwise be at that latitude.",
                "is_boss": False,
                "flavor": "The submarine catches a warm current. Puck rolls up tiny sleeves. \"It's like a warm river in the middle of the cold sea!\"",
            },
            {
                "id": "currents_and_climate",
                "title": "The Ocean Thermostat",
                "type": "quiz",
                "question": "Ocean currents help regulate the Earth's climate. How do they do this?",
                "options": [
                    "They block storms from forming",
                    "They carry warm water from the tropics to colder regions and cold water back",
                    "They absorb all the sunlight so land stays cool",
                    "They freeze water at the equator",
                ],
                "answer": "b",
                "hints": [
                    "Think of currents as a giant conveyor belt moving heat around the planet.",
                    "Without them, the tropics would be much hotter and the poles much colder.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Ocean currents act like a global heat conveyor belt. Warm currents carry tropical heat toward the poles, while cold currents bring cool water back toward the equator. This distributes heat around the planet and keeps temperature differences between regions smaller than they would be otherwise.",
                "is_boss": False,
                "flavor": "Puck draws arrows on the globe — red for warm, blue for cold. \"The ocean is the world's thermostat!\"",
            },
            {
                "id": "upwelling",
                "title": "Food From the Deep",
                "type": "quiz",
                "question": "Upwelling is when cold, nutrient-rich water rises from the deep ocean to the surface. Why is this so important for marine life?",
                "options": [
                    "It makes the water taste better for fish",
                    "It brings nutrients that feed phytoplankton, which feed everything else",
                    "It keeps the water warm enough for coral to grow",
                    "It pushes dangerous predators to the bottom",
                ],
                "answer": "b",
                "hints": [
                    "Nutrients are like fertiliser for tiny ocean plants.",
                    "Areas with upwelling are some of the richest fishing grounds in the world.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Upwelling brings cold, nutrient-rich water from the deep to the sunlit surface, where those nutrients feed massive blooms of phytoplankton. These tiny organisms are the base of the ocean food web. The world's most productive fisheries — like those off Peru and California — are found in upwelling zones.",
                "is_boss": False,
                "flavor": "The water around the submarine turns green with life. Fish swarm everywhere. \"Upwelling zones are like ocean buffets!\" Puck says.",
            },
            {
                "id": "conveyor_belt_boss",
                "title": "The Great Ocean Conveyor",
                "type": "quiz",
                "question": "The global ocean conveyor belt is a system of deep and surface currents that circulates water around the entire planet. How long does it take water to complete one full loop?",
                "options": [
                    "About 1 year",
                    "About 10 years",
                    "About 100 years",
                    "About 1,000 years",
                ],
                "answer": "d",
                "hints": [
                    "This is an incredibly slow journey — much slower than surface currents.",
                    "A drop of water that sinks in the Arctic won't return for many centuries.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "The thermohaline circulation — also called the global ocean conveyor belt — takes roughly 1,000 years for water to complete one full cycle. Cold, salty water sinks near the poles, travels along the deep ocean floor, eventually rises in warmer regions, and flows back as surface currents. It is one of the most important systems regulating Earth's climate.",
                "is_boss": True,
                "flavor": "Puck traces a looping line around the whole globe. \"A thousand years for one trip. The ocean is the most patient traveller in the world.\"",
            },
        ],
    },
    "sharks_and_rays": {
        "id": "sharks_and_rays",
        "name": "Teeth and Wings",
        "description": "Meet the sharks and rays — ancient predators and graceful gliders of the sea",
        "level_required": 13,
        "challenges": [
            {
                "id": "shark_skeleton",
                "title": "Boneless Hunters",
                "type": "quiz",
                "question": "What are shark skeletons made of?",
                "options": [
                    "Strong bone, like human skeletons",
                    "Cartilage — the same flexible material in your nose and ears",
                    "Hard coral-like shell",
                    "They have no skeleton at all",
                ],
                "answer": "b",
                "hints": [
                    "Touch the tip of your nose — it bends! That's the same material.",
                    "This makes sharks lighter and more flexible than bony fish.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Sharks are cartilaginous fish — their entire skeleton is made of cartilage, not bone. Cartilage is lighter and more flexible than bone (feel your nose or ears!). This makes sharks agile swimmers. Sharks have been around for over 400 million years — they're older than dinosaurs!",
                "is_boss": False,
                "flavor": "Puck bends the tip of their nose. \"Your ears, your nose — same stuff as a shark skeleton!\"",
            },
            {
                "id": "shark_senses",
                "title": "The Sixth Sense",
                "type": "quiz",
                "question": "Sharks have a special sense that most animals don't. What can they detect?",
                "options": [
                    "Colours that humans cannot see",
                    "Tiny electrical signals given off by other animals' muscles",
                    "Sounds from outer space",
                    "The temperature of nearby rocks",
                ],
                "answer": "b",
                "hints": [
                    "Every living creature produces a tiny electrical field when its muscles move.",
                    "Sharks have special organs called ampullae of Lorenzini on their snouts.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Sharks have electroreception — the ability to detect tiny electrical fields produced by the muscles and nerves of other animals. Special pores on their snouts, called ampullae of Lorenzini, pick up these signals. This helps sharks find prey even when it's hidden in sand or murky water!",
                "is_boss": False,
                "flavor": "A shark glides past, snout sweeping left and right. Puck whispers, \"It can sense your heartbeat.\"",
            },
            {
                "id": "whale_shark",
                "title": "The Gentle Giant",
                "type": "quiz",
                "question": "The whale shark is the largest fish in the ocean. What does it eat?",
                "options": [
                    "Large fish and seals",
                    "Tiny plankton and small fish — filtered from the water",
                    "Seaweed and kelp",
                    "Other sharks",
                ],
                "answer": "b",
                "hints": [
                    "Despite being enormous, it eats some of the smallest things in the ocean.",
                    "It swims with its huge mouth open, filtering water — like some whales do.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Whale sharks can grow up to 12 metres long, but they are gentle filter feeders. They swim with their enormous mouths open, filtering plankton, fish eggs, and small fish from the water. Despite their size, they are completely harmless to humans!",
                "is_boss": False,
                "flavor": "An enormous spotted shape drifts slowly past. Its mouth is wide enough to swallow a kayak — but it only wants plankton.",
            },
            {
                "id": "manta_ray_flight",
                "title": "Wings Beneath the Waves",
                "type": "quiz",
                "question": "Manta rays look like they're flying through the water. How wide can the largest manta rays get from wingtip to wingtip?",
                "options": [
                    "About 1 metre — the width of a door",
                    "About 3 metres — the width of a small car",
                    "About 7 metres — wider than a giraffe is tall",
                    "About 15 metres — wider than a tennis court",
                ],
                "answer": "c",
                "hints": [
                    "They are one of the largest fish in the ocean — but not quite as big as a whale shark.",
                    "Their wingspan is impressive — wider than most rooms in your house.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Giant oceanic manta rays can reach a wingspan of 7 metres — wider than many rooms! Like whale sharks, they are gentle filter feeders. Manta rays are also remarkably intelligent — they are one of the few fish that can recognise themselves in a mirror.",
                "is_boss": False,
                "flavor": "A great dark wing sweeps overhead like a living blanket. Puck floats alongside it, mesmerised.",
            },
            {
                "id": "shark_teeth_boss",
                "title": "A Lifetime of Teeth",
                "type": "quiz",
                "question": "Sharks lose and replace teeth throughout their lives. How many teeth can a single shark go through in its lifetime?",
                "options": [
                    "About 50 — roughly the same as a human",
                    "About 500 — ten times more than a human",
                    "About 5,000 — they lose several per week",
                    "Over 20,000 — they have rows of replacement teeth ready",
                ],
                "answer": "d",
                "hints": [
                    "Behind each front tooth are rows of backup teeth, like a conveyor belt.",
                    "Some sharks lose a tooth almost every day!",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Sharks have multiple rows of teeth behind the front row, like a conveyor belt. When a tooth falls out, a new one moves forward to replace it. Some species go through over 20,000 teeth in a lifetime! Humans only get two sets. No wonder shark teeth are the most common fossils found on beaches.",
                "is_boss": True,
                "flavor": "Puck holds up a single shark tooth, then looks at the rows and rows of replacements behind it. \"They never run out!\"",
            },
        ],
    },
    "ocean_conservation": {
        "id": "ocean_conservation",
        "name": "Guardians of the Deep",
        "description": "Learn about the threats facing our oceans and what we can do to protect them",
        "level_required": 16,
        "challenges": [
            {
                "id": "plastic_pollution",
                "title": "The Plastic Problem",
                "type": "quiz",
                "question": "About how much plastic enters the world's oceans every year?",
                "options": [
                    "About 1,000 kilograms — one tonne",
                    "About 1 million kilograms — a thousand tonnes",
                    "About 8 million tonnes — enough to fill a rubbish truck every minute",
                    "About 1 billion tonnes",
                ],
                "answer": "c",
                "hints": [
                    "It's a staggering amount — imagine a rubbish truck dumping plastic into the sea every single minute.",
                    "It's millions of tonnes, not thousands or billions.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Approximately 8 million tonnes of plastic enter the oceans every year — that's like dumping a full rubbish truck of plastic into the sea every minute. Plastic doesn't dissolve; it breaks into smaller and smaller pieces called microplastics, which are eaten by fish, turtles, and seabirds.",
                "is_boss": False,
                "flavor": "The submarine passes a floating tangle of plastic bags and bottles. Puck's face falls. \"This doesn't belong here.\"",
            },
            {
                "id": "overfishing",
                "title": "Too Many Nets",
                "type": "quiz",
                "question": "Overfishing means catching fish faster than they can reproduce. What fraction of the world's fish stocks are now overfished?",
                "options": [
                    "About one-tenth",
                    "About one-quarter",
                    "About one-third",
                    "About three-quarters",
                ],
                "answer": "c",
                "hints": [
                    "It's a significant fraction — more than a quarter but less than half.",
                    "The United Nations tracks this closely and is very concerned.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "About one-third of the world's fish stocks are overfished — caught faster than they can breed and recover. Overfishing disrupts entire ocean food webs. Sustainable fishing practices, catch limits, and marine protected areas can help fish populations recover.",
                "is_boss": False,
                "flavor": "Puck watches a huge net sweep through the water, scooping up everything in its path. \"If we take too much, there won't be any left.\"",
            },
            {
                "id": "marine_protected_areas",
                "title": "Safe Zones for the Sea",
                "type": "quiz",
                "question": "Marine Protected Areas (MPAs) are zones where human activities like fishing and drilling are limited. What happens to ocean life inside well-managed MPAs?",
                "options": [
                    "Fish and coral disappear because boats stop visiting",
                    "Nothing changes — the ocean stays exactly the same",
                    "Fish populations grow larger and healthier, and coral recovers",
                    "Only sharks benefit — everything else stays the same",
                ],
                "answer": "c",
                "hints": [
                    "Think of it like giving the ocean a rest — a chance to heal.",
                    "When fishing stops in an area, what do you think happens to the fish?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When parts of the ocean are protected, fish populations can grow up to 670% larger! Coral reefs recover, biodiversity increases, and the benefits spill over into surrounding waters. Scientists recommend protecting at least 30% of the ocean by 2030 — a goal called '30 by 30.'",
                "is_boss": False,
                "flavor": "The submarine crosses an invisible boundary. Suddenly, the reef explodes with colour and life. \"This is what 'protected' looks like,\" Puck says softly.",
            },
            {
                "id": "ocean_acidification",
                "title": "The Other CO2 Problem",
                "type": "quiz",
                "question": "The ocean absorbs about 30% of the carbon dioxide (CO2) humans release. What does this extra CO2 do to seawater?",
                "options": [
                    "It makes the water warmer",
                    "It makes the water more acidic, which harms shells and coral",
                    "It makes the water cleaner",
                    "It turns the water green",
                ],
                "answer": "b",
                "hints": [
                    "CO2 dissolves in water and creates a weak acid.",
                    "Animals that build shells or skeletons from calcium carbonate are most affected.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When CO2 dissolves in seawater, it forms carbonic acid, making the ocean more acidic. This is called ocean acidification. More acidic water makes it harder for corals, shellfish, and plankton to build their calcium carbonate shells and skeletons. The ocean is now 30% more acidic than before the Industrial Revolution.",
                "is_boss": False,
                "flavor": "Puck holds up a thin, fragile-looking shell. \"CO2 is making it harder for sea creatures to build their armour.\"",
            },
            {
                "id": "what_kids_can_do",
                "title": "Your Ocean, Your Future",
                "type": "quiz",
                "question": "Which of these actions can kids take RIGHT NOW to help protect the oceans?",
                "options": [
                    "Drive a boat out to sea and collect all the plastic",
                    "Reduce single-use plastic, pick up litter, and eat sustainably sourced seafood",
                    "Stop drinking water so there's more for the ocean",
                    "Wait until you're an adult — kids can't make a difference yet",
                ],
                "answer": "b",
                "hints": [
                    "You don't need to be a scientist or a grown-up to make a difference.",
                    "Small everyday choices — like using a reusable water bottle — add up!",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Every person can help protect the oceans! Use reusable bottles and bags, pick up litter (especially near water), learn about where your seafood comes from, spread the word about ocean conservation, and support marine protected areas. Small actions by millions of people add up to enormous change.",
                "is_boss": False,
                "flavor": "Puck pulls out a tiny reusable bottle and grins. \"Every choice matters. Even the small ones.\"",
            },
            {
                "id": "ocean_guardian_boss",
                "title": "The Ocean's Future",
                "type": "quiz",
                "question": "Scientists say we need to protect at least what percentage of the ocean by 2030 to keep marine ecosystems healthy?",
                "options": [
                    "5%",
                    "10%",
                    "30%",
                    "50%",
                ],
                "answer": "c",
                "hints": [
                    "This goal has a catchy name: '30 by 30.'",
                    "It means thirty percent by the year 2030.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "The '30 by 30' initiative, supported by over 100 countries, aims to protect at least 30% of the world's ocean by 2030. Currently, only about 8% is protected. Meeting this goal would help fish populations recover, protect coral reefs, fight climate change, and preserve ocean biodiversity for future generations — including yours!",
                "is_boss": True,
                "flavor": "Puck looks through the submarine window at the vast blue world outside. \"This is all worth saving. And you — yes, you — are part of how we save it.\"",
            },
        ],
    },
}
