"""
zones.py — Numbers zones and challenges.

All challenges use "type": "quiz" with multiple-choice options.
Guided by Long Long (龙龙), a friendly dragon.
"""

ZONE_ORDER = [
    "numbers_1_10",
    "numbers_11_99",
    "numbers_100_plus",
    "counting_words",
    "money",
    "time",
    "dates",
]

ZONES = {
    # ── Zone 1: Numbers 1-10 ────────────────────────────────────────
    "numbers_1_10": {
        "id": "numbers_1_10",
        "name": "One to Ten",
        "description": "The ten building blocks of Chinese numbers",
        "level_required": 1,
        "challenges": [
            {
                "id": "num_yi",
                "title": "Number One",
                "type": "quiz",
                "question": "What is the Chinese word for the number 1?",
                "options": ["er (二)", "yi (一)", "san (三)", "si (四)"],
                "answer": "b",
                "hints": [
                    "The character is the simplest possible: just one horizontal line.",
                    "It sounds like 'ee' in English.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "一 (yi, first tone) = 1. The character is beautifully simple: one horizontal stroke. yi is one of the most common words in Chinese. Remember: yi has special tone sandhi rules -- it changes tone depending on what follows it!",
                "is_boss": False,
                "flavor": "Long Long draws one perfect line in the air. 'Yi! The simplest character in Chinese!'",
            },
            {
                "id": "num_er",
                "title": "Number Two",
                "type": "quiz",
                "question": "The number 2 in Chinese is 'er' (二). Its character has:",
                "options": ["One horizontal line", "Two horizontal lines", "Three horizontal lines", "A cross shape"],
                "answer": "b",
                "hints": [
                    "One = one line. Two = two lines. See the pattern?",
                    "一 = 1, 二 = 2, and the pattern continues for 3...",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "二 (er, fourth tone) = 2. Two horizontal lines, stacked. The first three numbers follow a beautiful visual pattern: 一 (1 line), 二 (2 lines), 三 (3 lines). Note: when counting objects, you often use 'liang' (两) instead of 'er' -- more on that in measure words!",
                "is_boss": False,
                "flavor": "Long Long draws two parallel lines. 'Er! Two lines for two!'",
            },
            {
                "id": "num_1_to_5",
                "title": "The First Five",
                "type": "quiz",
                "question": "Put these in order from 1 to 5: san (三), yi (一), wu (五), er (二), si (四)",
                "options": ["yi, er, san, si, wu", "yi, san, er, wu, si", "er, yi, san, wu, si", "wu, si, san, er, yi"],
                "answer": "a",
                "hints": [
                    "yi = 1, er = 2, san = 3, si = 4, wu = 5.",
                    "The order sounds like: ee, are, sahn, suh, woo.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "一二三四五 (yi er san si wu) = 1, 2, 3, 4, 5. Notice that si (四, 4) is considered unlucky in Chinese culture because it sounds like si (死, death). Many buildings skip the 4th floor! Conversely, ba (八, 8) is lucky because it sounds like fa (发, prosperity).",
                "is_boss": False,
                "flavor": "Long Long counts on dragon claws: 'Yi, er, san, si, wu!'",
            },
            {
                "id": "num_6_to_10",
                "title": "The Second Five",
                "type": "quiz",
                "question": "What is the Chinese word for 8?",
                "options": ["liu (六)", "qi (七)", "ba (八)", "jiu (九)"],
                "answer": "c",
                "hints": [
                    "This number is considered very lucky in Chinese culture.",
                    "The Beijing Olympics started on 08/08/2008 at 8:08 PM because of this number!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "六七八九十 (liu qi ba jiu shi) = 6, 7, 8, 9, 10. ba (八, 8) is the luckiest number in Chinese culture because it sounds like fa (发) in fa cai (发财, get rich). Phone numbers and license plates with many 8s are sold for premium prices!",
                "is_boss": False,
                "flavor": "Long Long holds up eight claws. 'Ba! The luckiest number in China!'",
            },
            {
                "id": "num_hand_signals",
                "title": "Counting on One Hand",
                "type": "quiz",
                "question": "Chinese people can count to 10 on one hand. How is the number 6 shown?",
                "options": [
                    "Six fingers (using both hands)",
                    "Thumb and pinky extended, other fingers closed (like a phone gesture)",
                    "A closed fist",
                    "All five fingers plus a head nod"
                ],
                "answer": "b",
                "hints": [
                    "6 through 10 use special one-hand gestures unique to Chinese culture.",
                    "The gesture for 6 looks like you're making a 'call me' sign.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Chinese hand signals for 6-10 (one hand): 6 = thumb + pinky out (phone gesture), 7 = thumb + index + middle fingertips together, 8 = thumb + index extended (like a gun), 9 = index finger hooked, 10 = fist or crossed index fingers. These are used daily in markets and restaurants!",
                "is_boss": False,
                "flavor": "Long Long makes each hand gesture. 'One hand, ten numbers! Very useful in noisy markets!'",
            },
            {
                "id": "num_1_10_boss",
                "title": "Numbers 1-10 Boss",
                "type": "quiz",
                "question": "Which number is considered UNLUCKY in Chinese culture and is often skipped in building floors?",
                "options": ["san (三, 3)", "si (四, 4)", "liu (六, 6)", "qi (七, 7)"],
                "answer": "b",
                "hints": [
                    "This number sounds like another word with a very negative meaning.",
                    "si (四, 4) sounds like si (死, death).",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "四 (si, 4) is unlucky because it sounds like 死 (si, death). Many buildings have no 4th, 14th, or 24th floor. Phone numbers and addresses avoid 4. Meanwhile, 八 (ba, 8) is lucky (sounds like 'prosperity'), and 六 (liu, 6) means 'smooth/flowing'. Numbers carry deep cultural meaning in China!",
                "is_boss": True,
                "flavor": "Long Long looks superstitious. 'Never give four of something as a gift!'",
            },
        ],
    },

    # ── Zone 2: Numbers 11-99 ───────────────────────────────────────
    "numbers_11_99": {
        "id": "numbers_11_99",
        "name": "Double Digits",
        "description": "Build any number from 11 to 99",
        "level_required": 2,
        "challenges": [
            {
                "id": "num_11",
                "title": "Eleven the Logical Way",
                "type": "quiz",
                "question": "How do you say 11 in Chinese?",
                "options": ["yi yi (一一)", "shi yi (十一)", "yi shi (一十)", "shi shi (十十)"],
                "answer": "b",
                "hints": [
                    "11 = 10 + 1. In Chinese: ten-one.",
                    "shi (十) = 10, yi (一) = 1. So 11 = shi yi.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "十一 (shi yi) = 11, literally 'ten-one'. Chinese numbers are perfectly logical: 12 = shi er (十二, ten-two), 13 = shi san (十三, ten-three), etc. No irregular words like English 'eleven' or 'twelve' -- just ten plus the ones digit!",
                "is_boss": False,
                "flavor": "Long Long clicks one bead in the tens column, one in the ones. 'Shi yi! Ten-one!'",
            },
            {
                "id": "num_20",
                "title": "Twenty and Beyond",
                "type": "quiz",
                "question": "How do you say 20 in Chinese?",
                "options": ["er shi (二十)", "shi er (十二)", "liang shi (两十)", "er er (二二)"],
                "answer": "a",
                "hints": [
                    "20 = 2 x 10. In Chinese: two-ten.",
                    "er (二) = 2, shi (十) = 10. So 20 = er shi.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "二十 (er shi) = 20, literally 'two-ten'. The pattern: 30 = san shi (三十, three-ten), 40 = si shi (四十, four-ten), 50 = wu shi (五十, five-ten), up to 90 = jiu shi (九十, nine-ten). Perfectly regular!",
                "is_boss": False,
                "flavor": "Long Long slides two beads in the tens column. 'Er shi! Two-tens!'",
            },
            {
                "id": "num_compound",
                "title": "Building Any Number",
                "type": "quiz",
                "question": "How do you say 47 in Chinese?",
                "options": ["si qi (四七)", "si shi qi (四十七)", "qi shi si (七十四)", "shi si qi (十四七)"],
                "answer": "b",
                "hints": [
                    "47 = 4 tens + 7. In Chinese: four-ten-seven.",
                    "si (四) = 4, shi (十) = 10, qi (七) = 7.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "四十七 (si shi qi) = 47, literally 'four-ten-seven'. The formula: [tens digit] + shi (十) + [ones digit]. So 63 = liu shi san (六十三), 85 = ba shi wu (八十五), 99 = jiu shi jiu (九十九). Once you know 1-10, you can say any number up to 99!",
                "is_boss": False,
                "flavor": "Long Long builds the number on an abacus. 'Four tens, seven ones. Si shi qi!'",
            },
            {
                "id": "num_recognize",
                "title": "Hearing Numbers",
                "type": "quiz",
                "question": "Someone says 'ba shi san' (八十三). What number is this?",
                "options": ["38", "83", "813", "308"],
                "answer": "b",
                "hints": [
                    "ba (八) = 8, shi (十) = ten, san (三) = 3.",
                    "Eight-ten-three = 8 tens and 3 ones = 83.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "八十三 (ba shi san) = 83. Breaking it down: ba (8) + shi (ten) + san (3) = 8 × 10 + 3 = 83. Practice hearing these quickly: liu shi jiu (69), qi shi er (72), wu shi ba (58). Speed comes with practice!",
                "is_boss": False,
                "flavor": "Long Long speaks a number. 'Quick! What number did I say?'",
            },
            {
                "id": "num_teens",
                "title": "The Teens",
                "type": "quiz",
                "question": "How is 19 different from 90 in Chinese?",
                "options": [
                    "19 = shi jiu (十九, ten-nine); 90 = jiu shi (九十, nine-ten)",
                    "They sound the same",
                    "19 = jiu shi (九十); 90 = shi jiu (十九)",
                    "19 = yi jiu (一九); 90 = jiu ling (九零)"
                ],
                "answer": "a",
                "hints": [
                    "In the teens (11-19), shi comes FIRST: shi + digit.",
                    "For multiples of ten (20-90), the digit comes first: digit + shi.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Key distinction: teens have shi FIRST (shi yi = 11, shi jiu = 19). Multiples of ten have shi LAST (er shi = 20, jiu shi = 90). So shi jiu (十九) = 19, but jiu shi (九十) = 90. The order completely changes the number!",
                "is_boss": False,
                "flavor": "Long Long switches two abacus beads. 'Order matters! Shi jiu vs jiu shi!'",
            },
            {
                "id": "num_11_99_boss",
                "title": "Double Digits Boss",
                "type": "quiz",
                "question": "What is the Chinese for 99?",
                "options": ["shi jiu jiu (十九九)", "jiu shi jiu (九十九)", "jiu jiu (九九)", "jiu bai jiu (九百九)"],
                "answer": "b",
                "hints": [
                    "99 = 9 tens + 9. Nine-ten-nine.",
                    "jiu (九) = 9, shi (十) = ten.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "九十九 (jiu shi jiu) = 99, literally 'nine-ten-nine'. This is the largest two-digit number and follows the same perfect pattern. Fun fact: 99 (jiu jiu) sounds like 'long long' (久久, a long time) and symbolizes enduring love -- it's a popular number for weddings!",
                "is_boss": True,
                "flavor": "Long Long writes the biggest double-digit number. 'Jiu shi jiu! Love this number!'",
            },
        ],
    },

    # ── Zone 3: Numbers 100+ ────────────────────────────────────────
    "numbers_100_plus": {
        "id": "numbers_100_plus",
        "name": "Big Numbers",
        "description": "Hundreds, thousands, and the wan system",
        "level_required": 3,
        "challenges": [
            {
                "id": "num_100",
                "title": "One Hundred",
                "type": "quiz",
                "question": "How do you say 100 in Chinese?",
                "options": ["yi shi (一十)", "yi bai (一百)", "yi qian (一千)", "shi shi (十十)"],
                "answer": "b",
                "hints": [
                    "bai (百) is the word for 'hundred'.",
                    "100 = one hundred = yi bai.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "一百 (yi bai) = 100. bai (百) = hundred. 200 = er bai (二百) or liang bai (两百). 350 = san bai wu shi (三百五十, three-hundred-five-ten). For numbers like 101 where there's a zero in the middle, you say: yi bai ling yi (一百零一).",
                "is_boss": False,
                "flavor": "Long Long pushes the abacus into the hundreds. 'Yi bai! A new column!'",
            },
            {
                "id": "num_1000",
                "title": "One Thousand",
                "type": "quiz",
                "question": "What is 'yi qian' (一千)?",
                "options": ["100", "1,000", "10,000", "100,000"],
                "answer": "b",
                "hints": [
                    "qian (千) = thousand.",
                    "yi (一) + qian (千) = one thousand = 1,000.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "一千 (yi qian) = 1,000. qian (千) = thousand. 2,000 = liang qian (两千). 5,500 = wu qian wu bai (五千五百). So far the system is the same as English: hundred (bai) and thousand (qian). But the next level is where Chinese and English diverge...",
                "is_boss": False,
                "flavor": "Long Long expands the abacus further. 'Yi qian! Getting into big numbers!'",
            },
            {
                "id": "num_wan",
                "title": "The Mighty Wan",
                "type": "quiz",
                "question": "Chinese has a unique number unit 'wan' (万). What does it equal?",
                "options": ["1,000", "10,000", "100,000", "1,000,000"],
                "answer": "b",
                "hints": [
                    "English groups numbers in thousands (thousand, million, billion).",
                    "Chinese adds an extra grouping: wan = ten thousand, before you get to yi (亿, hundred million).",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "万 (wan) = 10,000 (ten thousand). This is THE key difference between Chinese and English numbers. English: thousand -> million. Chinese: qian (千, thousand) -> wan (万, ten-thousand) -> yi (亿, hundred-million). So 50,000 = wu wan (五万, five wan), NOT wu shi qian!",
                "is_boss": False,
                "flavor": "Long Long reveals a number that has no English equivalent. 'Wan! The ten-thousand unit!'",
            },
            {
                "id": "num_wan_system",
                "title": "Thinking in Wan",
                "type": "quiz",
                "question": "How would you say 30,000 in Chinese?",
                "options": ["san shi qian (三十千)", "san wan (三万)", "san bai wan (三百万)", "san qian (三千)"],
                "answer": "b",
                "hints": [
                    "30,000 = 3 × 10,000 = 3 wan.",
                    "In Chinese, you don't say 'thirty thousand' -- you say 'three wan'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "三万 (san wan) = 30,000 (three ten-thousands). The wan system: 10,000 = yi wan (一万), 100,000 = shi wan (十万, ten wan), 1,000,000 = yi bai wan (一百万, one-hundred wan). You count wan like you count anything else -- with ones, tens, hundreds before it!",
                "is_boss": False,
                "flavor": "Long Long restructures the abacus for the wan column. 'Think in groups of ten-thousand!'",
            },
            {
                "id": "num_ling",
                "title": "The Zero Placeholder",
                "type": "quiz",
                "question": "How do you say 205 in Chinese?",
                "options": ["er bai wu (二百五)", "er bai ling wu (二百零五)", "er ling wu (二零五)", "er wu (二五)"],
                "answer": "b",
                "hints": [
                    "When there's a zero in the middle of a number, you say 'ling' (零).",
                    "205 = two hundred, zero, five = er bai ling wu.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "零 (ling) = zero. When zeros appear in the middle of a number, say 'ling' once: 205 = er bai ling wu (二百零五), 1,008 = yi qian ling ba (一千零八). Only one 'ling' is needed even if there are multiple zeros: 3,005 = san qian ling wu. Caution: er bai wu (二百五) without ling means 250, which is slang for 'foolish'!",
                "is_boss": False,
                "flavor": "Long Long carefully places a zero bead. 'Ling is small but important -- don't skip it!'",
            },
            {
                "id": "num_100_boss",
                "title": "Big Numbers Boss",
                "type": "quiz",
                "question": "How do you say 1,000,000 (one million) in Chinese?",
                "options": ["yi wan (一万)", "yi bai wan (一百万)", "yi qian wan (一千万)", "yi yi (一亿)"],
                "answer": "b",
                "hints": [
                    "1,000,000 = 100 × 10,000 = one hundred wan.",
                    "yi bai (一百, one hundred) + wan (万, ten-thousand) = one million.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "一百万 (yi bai wan) = 1,000,000 (one million). In Chinese: one-hundred ten-thousands. The full scale: wan (万) = 10,000, shi wan (十万) = 100,000, bai wan (百万) = 1,000,000, qian wan (千万) = 10,000,000, yi (亿) = 100,000,000. Thinking in wan takes practice but becomes natural!",
                "is_boss": True,
                "flavor": "Long Long challenges you with the biggest number yet. 'Convert between English and Chinese number thinking!'",
            },
        ],
    },

    # ── Zone 4: Counting/Measure Words ──────────────────────────────
    "counting_words": {
        "id": "counting_words",
        "name": "Measure Words",
        "description": "The words that go between numbers and nouns",
        "level_required": 4,
        "challenges": [
            {
                "id": "mw_ge",
                "title": "The Universal Ge",
                "type": "quiz",
                "question": "What is the most common measure word in Chinese, used as a default for almost anything?",
                "options": ["zhi (只)", "tiao (条)", "ge (个)", "ben (本)"],
                "answer": "c",
                "hints": [
                    "If you don't know the specific measure word, you can usually use this one.",
                    "yi ge ren (一个人) = one person. yi ge pingguo (一个苹果) = one apple.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "个 (ge) is the universal measure word -- it works for most things. yi ge ren (一个人) = one person, liang ge pingguo (两个苹果) = two apples, san ge wenti (三个问题) = three questions. When in doubt, use ge! Native speakers will understand even if a more specific word exists.",
                "is_boss": False,
                "flavor": "Long Long holds up the most versatile character in counting. 'Ge -- your best friend when counting!'",
            },
            {
                "id": "mw_zhi",
                "title": "Measure Word for Animals",
                "type": "quiz",
                "question": "Which measure word is commonly used for small animals like cats and birds?",
                "options": ["ge (个)", "tiao (条)", "zhi (只)", "ben (本)"],
                "answer": "c",
                "hints": [
                    "yi zhi mao (一只猫) = one cat. yi zhi niao (一只鸟) = one bird.",
                    "This measure word is used for most animals, especially smaller ones.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "只 (zhi) is the measure word for most animals: yi zhi mao (一只猫) = one cat, yi zhi gou (一只狗) = one dog, yi zhi niao (一只鸟) = one bird. However, long/thin animals like fish and snakes use tiao (条), and large animals like horses and cows use pi (匹) or tou (头).",
                "is_boss": False,
                "flavor": "Long Long counts the animals in the scene. 'Yi zhi, liang zhi, san zhi...'",
            },
            {
                "id": "mw_tiao",
                "title": "Measure Word for Long Things",
                "type": "quiz",
                "question": "条 (tiao) is the measure word for long, thin things. Which of these would use 'tiao'?",
                "options": ["A book", "A fish", "A person", "A cup"],
                "answer": "b",
                "hints": [
                    "Think of things that are long and narrow: rivers, roads, fish, snakes, pants...",
                    "yi tiao yu (一条鱼) = one fish. yi tiao lu (一条路) = one road.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "条 (tiao) is for long, thin, or strip-like things: yi tiao yu (一条鱼) = one fish, yi tiao lu (一条路) = one road, yi tiao he (一条河) = one river, yi tiao kuzi (一条裤子) = one pair of pants, yi tiao she (一条蛇) = one snake. If it's long and narrow, think tiao!",
                "is_boss": False,
                "flavor": "Long Long gestures along something long and thin. 'Tiao -- for anything you could stretch out!'",
            },
            {
                "id": "mw_ben",
                "title": "Measure Word for Books",
                "type": "quiz",
                "question": "Which measure word do you use for books and magazines?",
                "options": ["zhang (张)", "ben (本)", "bei (杯)", "kuai (块)"],
                "answer": "b",
                "hints": [
                    "yi ben shu (一本书) = one book.",
                    "ben relates to bound volumes -- anything with pages bound together.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "本 (ben) is for books and bound materials: yi ben shu (一本书) = one book, yi ben zazhi (一本杂志) = one magazine, yi ben cidian (一本词典) = one dictionary. The character 本 originally meant 'root' or 'origin' and came to mean a bound volume.",
                "is_boss": False,
                "flavor": "Long Long holds up a book. 'Yi ben shu! Ben for anything with a binding!'",
            },
            {
                "id": "mw_bei",
                "title": "Measure Word for Cups",
                "type": "quiz",
                "question": "How do you say 'one cup of tea' in Chinese?",
                "options": ["yi ge cha (一个茶)", "yi bei cha (一杯茶)", "yi ping cha (一瓶茶)", "yi wan cha (一碗茶)"],
                "answer": "b",
                "hints": [
                    "bei (杯) means 'cup' or 'glass'.",
                    "It's the measure word for any drink served in a cup or glass.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "杯 (bei) is the measure word for cups/glasses of drinks: yi bei cha (一杯茶) = one cup of tea, yi bei kafei (一杯咖啡) = one cup of coffee, yi bei shui (一杯水) = one glass of water. Related: ping (瓶) = bottle, wan (碗) = bowl.",
                "is_boss": False,
                "flavor": "Long Long lifts a steaming cup. 'Yi bei cha -- the most civilized measure word!'",
            },
            {
                "id": "mw_liang",
                "title": "Liang vs Er",
                "type": "quiz",
                "question": "When counting objects (with measure words), you say 'liang' (两) instead of 'er' (二) for 2. Which is correct?",
                "options": ["er ge ren (二个人)", "liang ge ren (两个人)", "er ren (二人)", "liang ren (两人)"],
                "answer": "b",
                "hints": [
                    "Before measure words, 'two' is always liang (两), not er (二).",
                    "er is used for the number 2 in sequences (phone numbers, math), but liang is for counting things.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Two key rule: before measure words, use liang (两), not er (二). liang ge ren (两个人) = two people (correct). er ge ren (二个人) = wrong! Use er for: the number itself (2), sequences (di er = second), and large numbers (er shi = 20). Use liang for: counting things with measure words.",
                "is_boss": False,
                "flavor": "Long Long holds up two claws. 'Liang! Not er! This trips up every beginner!'",
            },
            {
                "id": "mw_boss",
                "title": "Measure Words Boss",
                "type": "quiz",
                "question": "Which measure word is used for flat, thin objects like paper, tickets, and tables?",
                "options": ["ben (本)", "tiao (条)", "zhang (张)", "ge (个)"],
                "answer": "c",
                "hints": [
                    "yi zhang zhi (一张纸) = one piece of paper. yi zhang piao (一张票) = one ticket.",
                    "Think of flat, spread-out surfaces.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "张 (zhang) is for flat things: yi zhang zhi (一张纸) = one piece of paper, yi zhang piao (一张票) = one ticket, yi zhang zhuozi (一张桌子) = one table, yi zhang chuang (一张床) = one bed, yi zhang lian (一张脸) = one face. If it's flat and spread out, use zhang!",
                "is_boss": True,
                "flavor": "Long Long lays out flat objects. 'Zhang -- for anything flat you could spread out!'",
            },
        ],
    },

    # ── Zone 5: Money ───────────────────────────────────────────────
    "money": {
        "id": "money",
        "name": "Money Talk",
        "description": "Currency, prices, and shopping in Chinese",
        "level_required": 5,
        "challenges": [
            {
                "id": "money_yuan",
                "title": "Yuan and Kuai",
                "type": "quiz",
                "question": "The basic unit of Chinese currency is the yuan (元). In casual speech, people say:",
                "options": ["fen (分)", "jiao (角)", "kuai (块)", "bi (币)"],
                "answer": "c",
                "hints": [
                    "It's like the difference between 'dollar' (formal) and 'buck' (casual).",
                    "kuai (块) literally means 'piece' or 'lump' and is used for money casually.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Chinese currency: the formal unit is yuan (元), but everyone says kuai (块) in daily life. 10 yuan = shi kuai (十块). kuai literally means 'piece/lump'. The currency is officially called Renminbi (人民币, RMB, 'people's currency'). Symbol: Y with two lines.",
                "is_boss": False,
                "flavor": "Long Long jingles some coins. 'Yuan on paper, kuai in the street!'",
            },
            {
                "id": "money_jiao_mao",
                "title": "Smaller Units",
                "type": "quiz",
                "question": "1 yuan (元) = 10 jiao (角). In casual speech, jiao is called:",
                "options": ["kuai (块)", "mao (毛)", "fen (分)", "qian (钱)"],
                "answer": "b",
                "hints": [
                    "Just as yuan -> kuai (formal -> casual), jiao -> ???",
                    "mao (毛) literally means 'hair/fur' but is used for the 1/10 yuan unit.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Currency units: 1 yuan (元/kuai 块) = 10 jiao (角/mao 毛) = 100 fen (分). In daily life: yuan -> kuai, jiao -> mao. Fen (cents) are rarely used today. So 3.50 yuan = san kuai wu mao (三块五毛) or just san kuai wu (三块五, dropping the mao).",
                "is_boss": False,
                "flavor": "Long Long lines up coins of decreasing size. 'Kuai, mao, fen -- big to small!'",
            },
            {
                "id": "money_asking_price",
                "title": "How Much Is It?",
                "type": "quiz",
                "question": "You point at something in a shop. How do you ask 'How much is this one?'",
                "options": [
                    "zhe ge shi shenme? (这个是什么?)",
                    "zhe ge duo shao qian? (这个多少钱?)",
                    "wo yao zhe ge (我要这个)",
                    "zhe ge hao ma? (这个好吗?)"
                ],
                "answer": "b",
                "hints": [
                    "zhe ge (这个) = this one. duo shao qian (多少钱) = how much money.",
                    "Point and ask: 'This one how much money?'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "这个多少钱? (zhe ge duo shao qian?) = 'How much is this?' zhe ge (这个) = this one, duo shao (多少) = how much, qian (钱) = money. For a specific item: [item] duo shao qian? For bargaining: tai gui le! (太贵了! Too expensive!) pian yi dian! (便宜点! Cheaper please!)",
                "is_boss": False,
                "flavor": "Long Long picks up a jade figurine. 'Zhe ge duo shao qian? Essential market Chinese!'",
            },
            {
                "id": "money_saying_prices",
                "title": "Saying Prices",
                "type": "quiz",
                "question": "A vendor says 'er shi wu kuai' (二十五块). How much is the item?",
                "options": ["2.50 yuan", "25 yuan", "250 yuan", "2,500 yuan"],
                "answer": "b",
                "hints": [
                    "er shi wu (二十五) = 25. kuai (块) = yuan.",
                    "Twenty-five kuai = 25 yuan.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Reading prices: listen for the number + kuai/yuan. er shi wu kuai (二十五块) = 25 yuan. yi bai kuai (一百块) = 100 yuan. san kuai wu (三块五) = 3.50 yuan (the mao/jiao is implied). As of recent years, most payments in China use WeChat Pay or Alipay rather than cash!",
                "is_boss": False,
                "flavor": "Long Long holds up price tags. 'Listen for the number, then kuai!'",
            },
            {
                "id": "money_too_expensive",
                "title": "Too Expensive!",
                "type": "quiz",
                "question": "How do you say 'too expensive!' in Chinese?",
                "options": ["hen hao (很好)", "tai gui le! (太贵了!)", "duo shao qian (多少钱)", "wo yao (我要)"],
                "answer": "b",
                "hints": [
                    "tai (太) = too, gui (贵) = expensive, le (了) = emphasis particle.",
                    "Literally: 'too expensive!'",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "太贵了! (tai gui le!) = 'Too expensive!' tai (太) = too, gui (贵) = expensive. Useful shopping phrases: pian yi dian (便宜点) = cheaper please, keyi pian yi ma? (可以便宜吗?) = can you make it cheaper?, zui di duo shao? (最低多少?) = what's the lowest price?",
                "is_boss": False,
                "flavor": "Long Long dramatically recoils at a price tag. 'Tai gui le! Time to bargain!'",
            },
            {
                "id": "money_boss",
                "title": "Money Boss",
                "type": "quiz",
                "question": "A vendor says 'yi bai er shi kuai wu' (一百二十块五). What's the exact price?",
                "options": ["120.50 yuan", "125 yuan", "1,205 yuan", "120.05 yuan"],
                "answer": "a",
                "hints": [
                    "yi bai er shi kuai = 120 kuai/yuan. wu = 5 (the mao is implied).",
                    "When only a number follows kuai without saying 'mao', it means that many mao (tenths of a yuan).",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "一百二十块五 (yi bai er shi kuai wu) = 120.50 yuan. The 'wu' after kuai means 5 mao (0.50 yuan) -- the word mao is dropped. Full form: yi bai er shi kuai wu mao. This shortening is very common: san kuai wu (三块五) = 3.50, not 3.05!",
                "is_boss": True,
                "flavor": "Long Long presents a complex price. 'Parse this like a real Chinese shopper!'",
            },
        ],
    },

    # ── Zone 6: Time ────────────────────────────────────────────────
    "time": {
        "id": "time",
        "name": "Telling Time",
        "description": "Hours, minutes, and time of day",
        "level_required": 6,
        "challenges": [
            {
                "id": "time_dian",
                "title": "O'Clock",
                "type": "quiz",
                "question": "How do you say '3 o'clock' in Chinese?",
                "options": ["san shi (三十)", "san dian (三点)", "san fen (三分)", "san ke (三刻)"],
                "answer": "b",
                "hints": [
                    "dian (点) is the word for 'o'clock' or 'point'.",
                    "Number + dian = that o'clock. San + dian = 3 o'clock.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "三点 (san dian) = 3 o'clock. dian (点) = o'clock/point. The pattern: yi dian (一点) = 1:00, liang dian (两点) = 2:00 (note: liang, not er!), wu dian (五点) = 5:00, shi er dian (十二点) = 12:00. To ask the time: ji dian le? (几点了? What time is it?)",
                "is_boss": False,
                "flavor": "Long Long points to a clock face. 'San dian! Easy as counting!'",
            },
            {
                "id": "time_fen",
                "title": "Minutes",
                "type": "quiz",
                "question": "How do you say 3:15 (three fifteen) in Chinese?",
                "options": ["san dian shi wu (三点十五)", "san dian yi wu (三点一五)", "san dian shi wu fen (三点十五分)", "shi wu dian san (十五点三)"],
                "answer": "c",
                "hints": [
                    "fen (分) = minutes. shi wu (十五) = 15.",
                    "3:15 = three o'clock fifteen minutes = san dian shi wu fen.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "三点十五分 (san dian shi wu fen) = 3:15. fen (分) = minutes. The pattern: [hour] dian [minutes] fen. San dian san shi fen (三点三十分) = 3:30. In casual speech, fen can be dropped: san dian shi wu (三点十五) = 3:15.",
                "is_boss": False,
                "flavor": "Long Long adds minute markings to the clock. 'Dian for hours, fen for minutes!'",
            },
            {
                "id": "time_ban",
                "title": "Half Past",
                "type": "quiz",
                "question": "How do you say 'half past seven' (7:30) in Chinese?",
                "options": ["qi dian ban (七点半)", "qi dian san shi (七点三十)", "ban qi dian (半七点)", "Both a and b are correct"],
                "answer": "d",
                "hints": [
                    "ban (半) = half. qi dian ban = seven o'clock half.",
                    "You can also say the full minutes: qi dian san shi fen.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "七点半 (qi dian ban) = 7:30. ban (半) = half. Both qi dian ban and qi dian san shi fen (七点三十分) are correct, but qi dian ban is more natural in conversation. ban is ONLY used for 30 minutes (half hour), not for other 'halves'.",
                "is_boss": False,
                "flavor": "Long Long splits a clock in half. 'Ban! The halfway point!'",
            },
            {
                "id": "time_am_pm",
                "title": "Morning and Afternoon",
                "type": "quiz",
                "question": "In Chinese, 'AM' and 'PM' are expressed using words that come:",
                "options": ["After the time", "Before the time", "There's no AM/PM in Chinese", "Using numbers 1-24 only"],
                "answer": "b",
                "hints": [
                    "shangwu (上午, morning) and xiawu (下午, afternoon) come before the time.",
                    "Example: shangwu jiu dian = morning 9 o'clock = 9 AM.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Time periods come BEFORE the time: shangwu jiu dian (上午九点) = 9 AM (morning 9 o'clock). xiawu san dian (下午三点) = 3 PM (afternoon 3 o'clock). Time periods: zaoshang (早上, early morning), shangwu (上午, AM), zhongwu (中午, noon), xiawu (下午, PM), wanshang (晚上, evening).",
                "is_boss": False,
                "flavor": "Long Long points to the sun's position. 'In Chinese, the time period comes first!'",
            },
            {
                "id": "time_ke",
                "title": "Quarter Hours",
                "type": "quiz",
                "question": "What does 'cha yi ke si dian' (差一刻四点) mean?",
                "options": ["4:15", "4:45", "3:45 (a quarter to four)", "3:15"],
                "answer": "c",
                "hints": [
                    "cha (差) = lacking/short of. yi ke (一刻) = one quarter (15 min). si dian (四点) = 4 o'clock.",
                    "Lacking one quarter of four o'clock = 3:45.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "刻 (ke) = quarter (15 minutes). yi ke (一刻) = 15 min. Three ways to say 3:45: san dian si shi wu fen (三点四十五分), san dian san ke (三点三刻, three quarters past three), or cha yi ke si dian (差一刻四点, a quarter to four). The cha pattern works like 'to' in English.",
                "is_boss": False,
                "flavor": "Long Long slices the clock into quarters. 'Ke -- quarter hours for precise timekeeping!'",
            },
            {
                "id": "time_boss",
                "title": "Time Boss",
                "type": "quiz",
                "question": "How would you say 'The meeting is at 2:30 PM' using natural Chinese word order?",
                "options": [
                    "hui yi xiawu liang dian ban (会议下午两点半)",
                    "xiawu liang dian ban kai hui (下午两点半开会)",
                    "liang dian ban xiawu kai hui (两点半下午开会)",
                    "kai hui liang dian ban xiawu (开会两点半下午)"
                ],
                "answer": "b",
                "hints": [
                    "Chinese word order for time: time period + specific time + action.",
                    "Time expressions come BEFORE the verb in Chinese.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Natural Chinese time order: [time period] + [specific time] + [verb/action]. xiawu liang dian ban kai hui (下午两点半开会) = 'afternoon two-thirty have meeting'. In Chinese, time ALWAYS comes before the verb -- opposite of English 'The meeting is at 2:30'!",
                "is_boss": True,
                "flavor": "Long Long checks a schedule. 'Time before action -- that's the Chinese way!'",
            },
        ],
    },

    # ── Zone 7: Dates ───────────────────────────────────────────────
    "dates": {
        "id": "dates",
        "name": "Calendar & Dates",
        "description": "Years, months, days of the week, and full dates",
        "level_required": 7,
        "challenges": [
            {
                "id": "date_months",
                "title": "Months Are Just Numbers",
                "type": "quiz",
                "question": "How do you say 'March' in Chinese?",
                "options": ["chun tian (春天)", "san yue (三月)", "di san (第三)", "san tian (三天)"],
                "answer": "b",
                "hints": [
                    "yue (月) = month. Chinese months are just numbers + yue.",
                    "January = yi yue (一月), February = er yue (二月), March = san yue...",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Chinese months are beautifully simple: number + 月 (yue, month). yi yue (一月) = January, er yue (二月) = February, san yue (三月) = March... shi er yue (十二月) = December. No 'January, February' to memorize -- just count! yue (月) also means 'moon'.",
                "is_boss": False,
                "flavor": "Long Long counts moons. 'San yue! Third moon! So logical!'",
            },
            {
                "id": "date_days_week",
                "title": "Days of the Week",
                "type": "quiz",
                "question": "Monday in Chinese is 'xingqi yi' (星期一). What does this literally mean?",
                "options": ["Moon day", "Week one", "Star period one", "First day"],
                "answer": "c",
                "hints": [
                    "xing (星) = star, qi (期) = period, yi (一) = one.",
                    "The days are: xingqi yi (1), xingqi er (2)... xingqi liu (6), then Sunday is special.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Days of the week: xingqi (星期, 'star period') + number. xingqi yi (星期一) = Monday (week-1), xingqi er (星期二) = Tuesday (week-2)... xingqi liu (星期六) = Saturday (week-6). Sunday is special: xingqi tian (星期天) or xingqi ri (星期日), using 'sky/day' instead of 7.",
                "is_boss": False,
                "flavor": "Long Long counts the days on dragon claws. 'Week-one, week-two... so easy!'",
            },
            {
                "id": "date_ri",
                "title": "Day of the Month",
                "type": "quiz",
                "question": "How do you say 'the 15th' (of a month) in Chinese?",
                "options": ["shi wu ri (十五日) or shi wu hao (十五号)", "di shi wu (第十五)", "shi wu tian (十五天)", "shi wu yue (十五月)"],
                "answer": "a",
                "hints": [
                    "ri (日) = day (formal). hao (号) = day/number (casual).",
                    "Number + ri or hao = that day of the month.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Day of the month: number + 日 (ri, formal) or 号 (hao, casual). shi wu ri (十五日) or shi wu hao (十五号) = the 15th. ri is used in writing and formal contexts. hao is used in speech. yi hao (一号) = the 1st, er shi hao (二十号) = the 20th.",
                "is_boss": False,
                "flavor": "Long Long circles a date on the calendar. 'Ri for formal, hao for chat!'",
            },
            {
                "id": "date_year",
                "title": "Saying the Year",
                "type": "quiz",
                "question": "How do you say the year 2025 in Chinese?",
                "options": [
                    "er qian er shi wu nian (二千二十五年)",
                    "liang ling er wu nian (两零二五年)",
                    "er ling er wu nian (二零二五年)",
                    "er shi er wu nian (二十二五年)"
                ],
                "answer": "c",
                "hints": [
                    "Years are read digit by digit: 2-0-2-5.",
                    "nian (年) = year. Each digit is read individually.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Years are read digit by digit + nian (年, year): 2025 = er ling er wu nian (二零二五年) -- 'two-zero-two-five year'. NOT 'two thousand twenty-five'! ling (零) = zero. 1998 = yi jiu jiu ba nian (一九九八年). This digit-by-digit reading is unique to years.",
                "is_boss": False,
                "flavor": "Long Long reads each digit. 'Year by year, digit by digit!'",
            },
            {
                "id": "date_order",
                "title": "Date Order: Big to Small",
                "type": "quiz",
                "question": "Chinese dates go in the order:",
                "options": [
                    "Month / Day / Year (like American English)",
                    "Day / Month / Year (like British English)",
                    "Year / Month / Day (biggest to smallest)",
                    "There's no fixed order"
                ],
                "answer": "c",
                "hints": [
                    "Chinese goes from the largest unit to the smallest.",
                    "Year (年) first, then month (月), then day (日).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Chinese date order: Year (年) -> Month (月) -> Day (日), biggest to smallest. Example: 2025 nian san yue shi wu ri (2025年3月15日) = March 15, 2025. This is also the ISO standard date format! Days of the week come after the date: ... xingqi liu (星期六, Saturday).",
                "is_boss": False,
                "flavor": "Long Long arranges blocks from largest to smallest. 'Big to small! Year, month, day!'",
            },
            {
                "id": "date_today",
                "title": "Today, Tomorrow, Yesterday",
                "type": "quiz",
                "question": "What does 'ming tian' (明天) mean?",
                "options": ["Yesterday", "Today", "Tomorrow", "Next week"],
                "answer": "c",
                "hints": [
                    "ming (明) = bright/next. tian (天) = day.",
                    "Tomorrow = 'bright day' -- the coming bright day.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Time words: jin tian (今天) = today, ming tian (明天) = tomorrow (bright day), zuo tian (昨天) = yesterday. Also: hou tian (后天) = day after tomorrow, qian tian (前天) = day before yesterday. Chinese regularly uses 'day after/before' in ways English doesn't!",
                "is_boss": False,
                "flavor": "Long Long looks toward the sunrise. 'Ming tian! The bright day ahead!'",
            },
            {
                "id": "date_boss",
                "title": "Dates Boss",
                "type": "quiz",
                "question": "How would you say 'Wednesday, October 1st, 2025' in Chinese?",
                "options": [
                    "xingqi san, shi yue yi ri, er ling er wu nian",
                    "er ling er wu nian shi yue yi ri xingqi san (二零二五年十月一日星期三)",
                    "shi yue yi ri er ling er wu nian xingqi san",
                    "2025, October 1, Wednesday"
                ],
                "answer": "b",
                "hints": [
                    "Biggest to smallest: year, month, day, day of week.",
                    "Year (年) + Month (月) + Day (日) + Day of week (星期).",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Full date in Chinese: er ling er wu nian shi yue yi ri xingqi san (二零二五年十月一日星期三) = Wednesday, October 1, 2025. Order: Year-Month-Day-Weekday. Fun fact: October 1st is China's National Day (国庆节, guoqing jie) -- the biggest holiday along with Chinese New Year!",
                "is_boss": True,
                "flavor": "Long Long presents the ultimate date challenge. 'Full date, Chinese order, no mistakes!'",
            },
        ],
    },
}
