"""
zones.py — Astronomy zones and challenges for The Star Observatory skill pack.

All challenges use "type": "quiz" or "type": "text".
Designed for ages 5-12, guided warmly by Puck.
Covers stars, the Moon, galaxies, space exploration, and astronaut life.
"""

ZONE_ORDER = [
    "stars_constellations",
    "the_moon",
    "galaxies_universe",
    "space_exploration",
    "astronauts_space_life",
]

ZONES = {
    # ── Zone 1: Stars & Constellations ────────────────────────────────
    "stars_constellations": {
        "id": "stars_constellations",
        "name": "Stars & Constellations",
        "description": "Discover the different types of stars and the patterns they make in the sky",
        "level_required": 1,
        "challenges": [
            {
                "id": "sc_what_is_star",
                "title": "What Is a Star?",
                "type": "quiz",
                "question": "Stars shine because something incredible is happening inside them. What makes a star glow?",
                "options": [
                    "Stars are on fire like a campfire",
                    "Stars are powered by nuclear fusion — smashing hydrogen atoms together",
                    "Stars reflect light from the Sun",
                    "Stars are made of glowing metal",
                ],
                "answer": "b",
                "hints": [
                    "It's not regular fire — it's something much more powerful happening deep inside.",
                    "Think about atoms being pushed together so hard they combine and release energy.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Stars shine because of nuclear fusion! Deep inside a star, hydrogen atoms are squeezed together so tightly they fuse into helium, releasing enormous amounts of energy as light and heat. Our Sun does this 600 million tons of hydrogen every second!",
                "is_boss": False,
                "flavor": "Puck opens the observatory dome. A thousand stars blaze overhead.",
            },
            {
                "id": "sc_star_colors",
                "title": "The Colour of Stars",
                "type": "quiz",
                "question": "Stars come in different colours. A blue star and a red star are in the sky — which one is hotter?",
                "options": [
                    "The red star — red means hot",
                    "The blue star — blue stars are the hottest",
                    "They are the same temperature",
                    "Neither — colour has nothing to do with temperature",
                ],
                "answer": "b",
                "hints": [
                    "Think about a flame — the blue part is hotter than the orange part.",
                    "Red stars are actually the coolest stars, and blue stars are the hottest!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Star colours tell us their temperature! Red stars are the coolest (around 3,000°C), yellow stars like our Sun are medium (about 5,500°C), and blue stars are the hottest (over 30,000°C). The hotter the star, the bluer it looks!",
                "is_boss": False,
                "flavor": "Puck points out a blue-white star and a deep red one. 'Which one would you rather stand next to?'",
            },
            {
                "id": "sc_our_sun",
                "title": "Our Very Own Star",
                "type": "quiz",
                "question": "Our Sun is a star! What type of star is it?",
                "options": [
                    "A red giant — one of the biggest",
                    "A yellow dwarf — a medium-sized main sequence star",
                    "A blue supergiant — the hottest kind",
                    "A white dwarf — a tiny, dying star",
                ],
                "answer": "b",
                "hints": [
                    "Look at the colour of the Sun — it's yellow-ish.",
                    "It's not the biggest or smallest. It's a very ordinary, middle-of-the-road star.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Our Sun is a yellow dwarf star — a medium-sized star in the middle of its life. It's about 4.6 billion years old and will keep shining for another 5 billion years. Even though we call it 'dwarf,' it's still over a million times bigger than Earth!",
                "is_boss": False,
                "flavor": "Puck shields his eyes playfully. 'Our Sun — the most important star in the whole sky!'",
            },
            {
                "id": "sc_big_dipper",
                "title": "The Big Dipper",
                "type": "quiz",
                "question": "The Big Dipper is one of the most famous star patterns in the night sky. What is it part of?",
                "options": [
                    "The constellation Orion",
                    "The constellation Ursa Major (the Great Bear)",
                    "The constellation Cassiopeia",
                    "The Milky Way's center",
                ],
                "answer": "b",
                "hints": [
                    "The Big Dipper looks like a ladle or a cup with a long handle.",
                    "It's part of a bigger constellation shaped like a bear!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The Big Dipper is part of Ursa Major — the Great Bear! The seven bright stars of the Dipper form the bear's back and tail. Two stars at the end of the 'cup' point straight to Polaris, the North Star, which has helped travellers find their way for thousands of years.",
                "is_boss": False,
                "flavor": "Puck traces the ladle shape with a glowing finger. 'See the cup? Follow those two stars at the end...'",
            },
            {
                "id": "sc_orion",
                "title": "Orion the Hunter",
                "type": "text",
                "question": "Orion is one of the easiest constellations to spot. It has three stars in a row that form Orion's Belt. Can you name one of the two very bright stars in Orion — one is red and one is blue?",
                "options": [],
                "answer": "betelgeuse",
                "hints": [
                    "The red star is in Orion's shoulder. Its name starts with 'B'.",
                    "The blue star is in Orion's foot. Its name starts with 'R'. Either name counts!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Orion's two brightest stars are Betelgeuse (a red supergiant in his shoulder) and Rigel (a blue supergiant in his foot). Betelgeuse is so enormous that if it replaced our Sun, it would swallow Mars! Rigel is one of the brightest stars in our sky.",
                "is_boss": False,
                "flavor": "Puck strikes a heroic pose. 'Orion the Hunter — belt, sword, bow, and all!'",
            },
            {
                "id": "sc_life_cycle",
                "title": "A Star Is Born",
                "type": "quiz",
                "question": "Stars are born inside giant clouds of gas and dust in space. What are these stellar nurseries called?",
                "options": [
                    "Black holes",
                    "Nebulae",
                    "Asteroids",
                    "Comets",
                ],
                "answer": "b",
                "hints": [
                    "These clouds are some of the most beautiful objects in space — full of colour.",
                    "The word comes from the Latin word for 'cloud.'",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Stars are born inside nebulae — enormous clouds of gas and dust. Gravity pulls the gas together into clumps that get hotter and denser until nuclear fusion ignites and a new star is born! The Eagle Nebula and Orion Nebula are famous star nurseries.",
                "is_boss": False,
                "flavor": "Puck gasps. The telescope reveals a glowing cloud of pink and purple — a nebula!",
            },
            {
                "id": "sc_star_death",
                "title": "How Stars Die",
                "type": "quiz",
                "question": "When a massive star runs out of fuel, it explodes in a spectacular blast. What is this explosion called?",
                "options": [
                    "A solar flare",
                    "A meteor shower",
                    "A supernova",
                    "A comet tail",
                ],
                "answer": "c",
                "hints": [
                    "'Super' means big, and 'nova' means new — because it looks like a bright new star appearing.",
                    "These explosions are so bright they can outshine an entire galaxy!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A supernova is the explosive death of a massive star. For a few weeks, it can outshine billions of stars! Supernovae scatter elements like iron, gold, and carbon into space — the very atoms that make up your body were forged in ancient supernovae. You are literally made of star stuff!",
                "is_boss": False,
                "flavor": "Puck's eyes go wide as the telescope shows an ancient supernova remnant — a glowing shell of gas.",
            },
            {
                "id": "sc_polaris",
                "title": "The North Star",
                "type": "text",
                "question": "For centuries, sailors and travellers used a special star to find north. What is the name of the North Star?",
                "options": [],
                "answer": "polaris",
                "hints": [
                    "Its name starts with 'P' and sounds like 'polar.'",
                    "You can find it by following the two pointer stars at the end of the Big Dipper's cup.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Polaris, the North Star, sits almost exactly above Earth's North Pole. Because of this, it barely moves while all the other stars appear to spin around it. For thousands of years, people have used Polaris to navigate — if you can find it, you know which way is north!",
                "is_boss": True,
                "flavor": "Puck points straight up. One star holds perfectly still while all the others wheel around it.",
            },
        ],
    },

    # ── Zone 2: The Moon ──────────────────────────────────────────────
    "the_moon": {
        "id": "the_moon",
        "name": "The Moon",
        "description": "Explore the Moon's phases, eclipses, and its pull on Earth's tides",
        "level_required": 3,
        "challenges": [
            {
                "id": "moon_phases_intro",
                "title": "Why the Moon Changes Shape",
                "type": "quiz",
                "question": "The Moon seems to change shape throughout the month. Why does this happen?",
                "options": [
                    "The Moon actually changes its shape",
                    "Earth's shadow falls on different parts of the Moon",
                    "We see different amounts of the Moon's sunlit side as it orbits Earth",
                    "Clouds cover parts of the Moon",
                ],
                "answer": "c",
                "hints": [
                    "The Moon doesn't make its own light — it reflects sunlight.",
                    "As the Moon moves around Earth, we see it from different angles.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The Moon doesn't change shape — we just see different amounts of its sunlit half as it orbits Earth! When the Moon is between Earth and the Sun, the lit side faces away (new moon). When Earth is between the Moon and the Sun, we see the full lit side (full moon).",
                "is_boss": False,
                "flavor": "Puck holds up a ball and a lantern. 'Watch — I'll show you why the Moon changes!'",
            },
            {
                "id": "moon_phase_names",
                "title": "Name That Phase",
                "type": "quiz",
                "question": "When exactly half of the Moon's face is lit up (the right half, getting bigger), what is this phase called?",
                "options": [
                    "Full moon",
                    "New moon",
                    "First quarter",
                    "Waning crescent",
                ],
                "answer": "c",
                "hints": [
                    "It's called 'quarter' because the Moon is one quarter of the way through its cycle.",
                    "It's the 'first' one because it happens before the full moon.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The first quarter moon shows exactly half the Moon's face lit up. It's called 'quarter' because the Moon is one quarter through its monthly cycle! The phases go: new moon, waxing crescent, first quarter, waxing gibbous, full moon, waning gibbous, third quarter, waning crescent.",
                "is_boss": False,
                "flavor": "Puck draws a half-circle of light. 'Halfway there — getting bigger every night!'",
            },
            {
                "id": "moon_solar_eclipse",
                "title": "When the Sun Disappears",
                "type": "quiz",
                "question": "During a solar eclipse, the sky goes dark in the middle of the day. What causes a solar eclipse?",
                "options": [
                    "The Earth moves in front of the Sun",
                    "The Moon passes between the Earth and the Sun, blocking the sunlight",
                    "The Sun turns off for a few minutes",
                    "A large planet moves in front of the Sun",
                ],
                "answer": "b",
                "hints": [
                    "Something much closer to us blocks our view of the Sun.",
                    "It's amazing that the Moon is exactly the right size and distance to cover the Sun!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A solar eclipse happens when the Moon passes directly between Earth and the Sun, casting a shadow on Earth. Even though the Sun is 400 times bigger than the Moon, it's also about 400 times farther away — so they look the same size in our sky. What a cosmic coincidence!",
                "is_boss": False,
                "flavor": "Puck puts on tiny eclipse glasses. 'Never look at an eclipse without protection!'",
            },
            {
                "id": "moon_lunar_eclipse",
                "title": "The Blood Moon",
                "type": "quiz",
                "question": "During a lunar eclipse, the Moon turns a spooky reddish colour. Why does it look red instead of just going dark?",
                "options": [
                    "The Moon is made of red rock",
                    "Earth's atmosphere bends red light onto the Moon",
                    "Mars reflects its red colour onto the Moon",
                    "The Sun turns red during an eclipse",
                ],
                "answer": "b",
                "hints": [
                    "Think about why sunsets are red — it's the same thing, but on a bigger scale.",
                    "Earth's atmosphere acts like a filter, bending certain colours of light around it.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "During a lunar eclipse, Earth blocks direct sunlight from reaching the Moon. But Earth's atmosphere bends red and orange light around the edges — like a global sunset projected onto the Moon! That's why it's called a 'blood moon.' If you stood on the Moon during a lunar eclipse, you'd see a red ring around Earth!",
                "is_boss": False,
                "flavor": "The Moon in the telescope turns a deep, coppery red. Puck whispers, 'A blood moon!'",
            },
            {
                "id": "moon_tides",
                "title": "The Moon Pulls the Sea",
                "type": "quiz",
                "question": "The Moon's gravity causes tides on Earth — the ocean rises and falls each day. How many high tides does most of the coastline experience in a day?",
                "options": [
                    "One",
                    "Two",
                    "Four",
                    "Seven",
                ],
                "answer": "b",
                "hints": [
                    "There's a bulge of water on the side nearest the Moon AND on the opposite side.",
                    "As Earth rotates, each coast passes through both bulges.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Most coastlines get two high tides and two low tides each day! The Moon's gravity pulls water toward it, creating a bulge. There's also a bulge on the opposite side of Earth because of inertia. As Earth spins, each coast rotates through both bulges — giving us two high tides about 12 hours apart.",
                "is_boss": False,
                "flavor": "Puck makes a tugging motion toward the telescope. 'The Moon is pulling the ocean right now!'",
            },
            {
                "id": "moon_craters",
                "title": "The Moon's Scars",
                "type": "text",
                "question": "The Moon's surface is covered in round dents called craters. What caused all these craters? Type your answer.",
                "options": [],
                "answer": "asteroid",
                "hints": [
                    "Things from space crashed into the Moon long ago.",
                    "Asteroids and meteorites slammed into the surface over billions of years.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The Moon's craters were made by asteroids and meteorites smashing into its surface over billions of years. Earth gets hit too, but wind, rain, and plants erase most of our craters. The Moon has no atmosphere, no weather, and no life — so its craters last forever!",
                "is_boss": False,
                "flavor": "Puck zooms the telescope in on the Moon's surface. Craters everywhere — big and small!",
            },
            {
                "id": "moon_far_side",
                "title": "The Hidden Side",
                "type": "quiz",
                "question": "We always see the same side of the Moon from Earth. Why can't we see the other side?",
                "options": [
                    "The other side is always in darkness",
                    "The Moon rotates at the same rate it orbits Earth — so one face always points toward us",
                    "Earth's gravity prevents the Moon from spinning",
                    "The other side is invisible",
                ],
                "answer": "b",
                "hints": [
                    "The Moon DOES spin — but very slowly. One spin takes the same time as one orbit.",
                    "This is called 'tidal locking.' Walk in a circle around a chair while always facing it — that's what the Moon does!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The Moon is 'tidally locked' to Earth — it rotates on its axis in exactly the same time it takes to orbit Earth (about 27 days). So the same face always points toward us! The far side was a total mystery until 1959, when a Soviet spacecraft flew around and photographed it for the first time.",
                "is_boss": False,
                "flavor": "Puck walks in a circle around the telescope, always keeping his face pointed at it. 'See? Like this!'",
            },
            {
                "id": "moon_distance",
                "title": "How Far Is the Moon?",
                "type": "quiz",
                "question": "The Moon is the closest thing to Earth in space. About how far away is it?",
                "options": [
                    "About 1,000 kilometres",
                    "About 384,000 kilometres",
                    "About 5 million kilometres",
                    "About 150 million kilometres",
                ],
                "answer": "b",
                "hints": [
                    "It takes light about 1.3 seconds to travel from the Moon to Earth.",
                    "You could fit about 30 Earths side by side in the gap between Earth and the Moon.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "The Moon is about 384,400 km from Earth — close enough that light takes only 1.3 seconds to make the trip! You could fit all the other planets in our solar system in the gap between Earth and the Moon. Apollo astronauts took about 3 days to travel there.",
                "is_boss": True,
                "flavor": "Puck stretches a measuring tape from the telescope to the Moon. 'Closer than you think — but still very, very far!'",
            },
        ],
    },

    # ── Zone 3: Galaxies & the Universe ───────────────────────────────
    "galaxies_universe": {
        "id": "galaxies_universe",
        "name": "Galaxies & the Universe",
        "description": "Explore the Milky Way, different types of galaxies, and the vastness of the cosmos",
        "level_required": 5,
        "challenges": [
            {
                "id": "gu_milky_way",
                "title": "Our Home Galaxy",
                "type": "quiz",
                "question": "Our solar system is inside a galaxy called the Milky Way. What shape is it?",
                "options": [
                    "A perfect sphere",
                    "A spiral with curving arms",
                    "A cube",
                    "A long, thin line",
                ],
                "answer": "b",
                "hints": [
                    "If you could see it from above, it would look like a pinwheel.",
                    "It has long, curved arms spinning out from the center.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The Milky Way is a barred spiral galaxy — it has a bright center with a bar-shaped core and long, curving arms spiraling outward. It contains between 100 billion and 400 billion stars! Our Sun is about two-thirds of the way out from the center, in one of the spiral arms.",
                "is_boss": False,
                "flavor": "Puck dims the observatory lights. A glowing band of stars stretches across the ceiling.",
            },
            {
                "id": "gu_milky_way_name",
                "title": "Why 'Milky Way'?",
                "type": "text",
                "question": "On a very dark night, you can see a pale, glowing band stretching across the sky — that's our galaxy seen from the inside. The ancient Greeks had a name for this band. What does 'galaxy' come from? (Hint: it's a Greek word for a white liquid.)",
                "options": [],
                "answer": "milk",
                "hints": [
                    "The word 'galaxy' comes from the Greek word 'galaktos.'",
                    "Galaktos means milk! The glowing band looked like spilled milk across the sky.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The word 'galaxy' comes from the Greek word 'galaktos,' meaning milk! The ancient Greeks thought the pale band of light across the sky looked like a river of milk. We now know that band is actually billions of distant stars in our own Milky Way galaxy, seen from the inside!",
                "is_boss": False,
                "flavor": "Puck pours a glass of milk and holds it up to the sky. 'See the resemblance?'",
            },
            {
                "id": "gu_galaxy_types",
                "title": "Galaxy Shapes",
                "type": "quiz",
                "question": "Galaxies come in different shapes. Which of these is NOT a real type of galaxy?",
                "options": [
                    "Spiral galaxy",
                    "Elliptical galaxy",
                    "Irregular galaxy",
                    "Triangular galaxy",
                ],
                "answer": "d",
                "hints": [
                    "Three of these are real types that astronomers use. One is made up.",
                    "Real galaxies can be swirly, blobby, or lumpy — but not perfectly geometric.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The three main types of galaxies are spiral (like our Milky Way, with swirling arms), elliptical (smooth, rounded blobs of old stars), and irregular (no particular shape at all). There is no such thing as a 'triangular galaxy' — gravity doesn't make triangle shapes!",
                "is_boss": False,
                "flavor": "Puck draws three galaxy shapes in the air — a spiral, a blob, and a squiggly mess.",
            },
            {
                "id": "gu_andromeda",
                "title": "Our Nearest Big Neighbour",
                "type": "quiz",
                "question": "The closest large galaxy to the Milky Way is on a collision course with us! What is its name?",
                "options": [
                    "The Andromeda Galaxy",
                    "The Whirlpool Galaxy",
                    "The Sombrero Galaxy",
                    "The Pinwheel Galaxy",
                ],
                "answer": "a",
                "hints": [
                    "It's named after a princess from Greek mythology.",
                    "You can actually see it with your naked eye on a dark night — a faint smudge of light.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The Andromeda Galaxy is our nearest large galactic neighbour, about 2.5 million light-years away. It's heading toward us at 110 km per second! In about 4.5 billion years, the Milky Way and Andromeda will collide and merge into one giant galaxy. Don't worry — the stars are so far apart that almost nothing will actually crash.",
                "is_boss": False,
                "flavor": "Puck looks nervous. 'It's heading right for us!' Then grins. 'But not for a few billion years.'",
            },
            {
                "id": "gu_light_year",
                "title": "What Is a Light-Year?",
                "type": "quiz",
                "question": "Astronomers measure huge distances in 'light-years.' What exactly is a light-year?",
                "options": [
                    "The time it takes light to travel across the Sun",
                    "The distance light travels in one year",
                    "The amount of light a star makes in one year",
                    "The age of a beam of light",
                ],
                "answer": "b",
                "hints": [
                    "It has 'year' in the name, but it's actually a measure of distance, not time.",
                    "Light is the fastest thing in the universe — about 300,000 km per second. In a whole year, it covers an incredible distance!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A light-year is the distance that light travels in one year — about 9.46 trillion kilometres! Light moves at 300,000 km per second, so in a whole year it covers a truly enormous distance. The nearest star to our Sun, Proxima Centauri, is about 4.2 light-years away.",
                "is_boss": False,
                "flavor": "Puck flicks on a torch. 'Imagine this beam running for a whole year without stopping!'",
            },
            {
                "id": "gu_looking_back",
                "title": "Looking Back in Time",
                "type": "quiz",
                "question": "When we look at a star that is 100 light-years away, we are actually seeing it as it was 100 years ago. Why?",
                "options": [
                    "Telescopes slow down time",
                    "Because the light took 100 years to reach us",
                    "Stars only send light every 100 years",
                    "Our eyes process light slowly",
                ],
                "answer": "b",
                "hints": [
                    "Light is fast, but it's not instant. It takes time to travel across space.",
                    "The farther away something is, the older the light is by the time it reaches our eyes.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Light takes time to travel. When you look at a star 100 light-years away, the light hitting your eyes left that star 100 years ago! Telescopes like James Webb can see galaxies so far away that their light has been travelling for over 13 billion years — we see them as they were near the beginning of the universe.",
                "is_boss": False,
                "flavor": "Puck taps his chin. 'Every time you look at a star, you're a time traveller.'",
            },
            {
                "id": "gu_how_many_stars",
                "title": "Counting the Uncountable",
                "type": "quiz",
                "question": "There are more stars in the observable universe than... what?",
                "options": [
                    "Grains of sand on all of Earth's beaches",
                    "Drops of water in the ocean",
                    "Leaves on all the trees in the world",
                    "All of the above — there are more stars than any of these",
                ],
                "answer": "a",
                "hints": [
                    "Scientists estimate there are about 200 sextillion stars — that's a 2 followed by 23 zeros!",
                    "The classic comparison is to something you find at the seaside.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "There are roughly 200 sextillion (200,000,000,000,000,000,000,000) stars in the observable universe — more than all the grains of sand on every beach on Earth! Each galaxy contains billions of stars, and there are at least 2 trillion galaxies. The universe is unimaginably vast.",
                "is_boss": False,
                "flavor": "Puck tries to count stars with his fingers. He gives up after five.",
            },
            {
                "id": "gu_big_bang",
                "title": "The Beginning of Everything",
                "type": "quiz",
                "question": "Scientists believe the universe began about 13.8 billion years ago with a rapid expansion from an incredibly tiny, hot point. What is this event called?",
                "options": [
                    "The Great Explosion",
                    "The Big Bang",
                    "The Star Burst",
                    "The Cosmic Crack",
                ],
                "answer": "b",
                "hints": [
                    "It's a very famous name — two simple words.",
                    "The name suggests something loud and sudden — 'Big' and...",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "The Big Bang is the scientific theory that the universe began as an incredibly tiny, hot, dense point about 13.8 billion years ago and has been expanding ever since. Everything — all matter, energy, space, and even time itself — started in that moment. The universe is still expanding today!",
                "is_boss": True,
                "flavor": "Puck clutches the observatory railing. 'Everything — every star, every atom, every one of us — started from one unimaginably tiny point.'",
            },
        ],
    },

    # ── Zone 4: Space Exploration ─────────────────────────────────────
    "space_exploration": {
        "id": "space_exploration",
        "name": "Space Exploration",
        "description": "Discover the amazing spacecraft, telescopes, and missions that explore the cosmos",
        "level_required": 7,
        "challenges": [
            {
                "id": "se_iss",
                "title": "A Home in Space",
                "type": "quiz",
                "question": "The International Space Station (ISS) orbits Earth with astronauts living on board. How fast does it travel?",
                "options": [
                    "About 500 km/h — like a fast airplane",
                    "About 5,000 km/h — like a jet fighter",
                    "About 28,000 km/h — it circles Earth every 90 minutes",
                    "About 100,000 km/h — almost the speed of light",
                ],
                "answer": "c",
                "hints": [
                    "It goes fast enough to circle the entire Earth in about an hour and a half.",
                    "That means the astronauts on board see 16 sunrises every single day!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The ISS zooms around Earth at about 28,000 km/h — fast enough to orbit the planet every 90 minutes! That means astronauts on board see 16 sunrises and 16 sunsets every day. The station has been continuously occupied since November 2000 — people have been living in space for over 25 years!",
                "is_boss": False,
                "flavor": "Puck spots a bright dot moving steadily across the sky. 'There it is — people live up there!'",
            },
            {
                "id": "se_hubble",
                "title": "The Eye Above the Clouds",
                "type": "quiz",
                "question": "The Hubble Space Telescope was launched in 1990 and has taken stunning pictures of the universe. Why is it in space instead of on the ground?",
                "options": [
                    "It needs to be closer to the stars",
                    "Earth's atmosphere blurs and distorts light — space gives a clearer view",
                    "There is no room for it on Earth",
                    "It runs on solar power that only works in space",
                ],
                "answer": "b",
                "hints": [
                    "Stars twinkle because of something between us and them.",
                    "Earth's atmosphere bends and distorts the light from stars — getting above it fixes that.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Earth's atmosphere makes stars twinkle — it bends and blurs their light. By putting Hubble above the atmosphere, astronomers get crystal-clear images. Hubble has taken over 1.5 million observations, discovered new moons, watched stars being born, and shown us galaxies 13 billion light-years away!",
                "is_boss": False,
                "flavor": "Puck opens a book of Hubble's greatest photos. Galaxies and nebulae glow on every page.",
            },
            {
                "id": "se_jwst",
                "title": "The Golden Eye",
                "type": "quiz",
                "question": "The James Webb Space Telescope (JWST) launched in 2021. It sees the universe in a type of light our eyes cannot see. What kind of light does it detect?",
                "options": [
                    "Ultraviolet light",
                    "X-ray light",
                    "Infrared light — heat radiation",
                    "Radio waves",
                ],
                "answer": "c",
                "hints": [
                    "The oldest, most distant galaxies have had their light stretched into a longer wavelength that we feel as warmth.",
                    "James Webb is kept extremely cold — just 50 degrees above absolute zero — so its own heat doesn't interfere.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "James Webb sees in infrared — light that our eyes perceive as heat. This lets it peer through dusty clouds where stars are born and see the most distant galaxies, whose light has been stretched into infrared by the expanding universe. Its golden mirror is 6.5 metres wide and sits 1.5 million km from Earth!",
                "is_boss": False,
                "flavor": "Puck holds up a golden hexagonal mirror. 'Eighteen segments, folded up like origami, unfolded in space!'",
            },
            {
                "id": "se_rovers",
                "title": "Robots on Mars",
                "type": "text",
                "question": "NASA has sent several rovers to drive around on Mars. One rover that landed in 2021 is collecting rock samples to send back to Earth someday. What is its name?",
                "options": [],
                "answer": "perseverance",
                "hints": [
                    "Its name means to keep going even when things are hard.",
                    "It starts with the letter 'P' and was named by a student in a naming contest!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Perseverance landed on Mars in February 2021. It explores Jezero Crater, which was once a lake, and collects rock samples that a future mission will return to Earth. It also carried Ingenuity, the first helicopter to fly on another planet! Its name was chosen by seventh-grader Alexander Mather.",
                "is_boss": False,
                "flavor": "Puck makes a little rover out of Primer pages and drives it across the desk. 'Vroom — on Mars!'",
            },
            {
                "id": "se_voyager",
                "title": "The Farthest Traveller",
                "type": "quiz",
                "question": "Voyager 1, launched in 1977, is the most distant human-made object in space. It carries a golden record with sounds and images from Earth. Why?",
                "options": [
                    "To test if records work in space",
                    "In case an alien civilization finds it and wants to learn about Earth",
                    "To play music for the astronauts on board",
                    "To record sounds from outer space",
                ],
                "answer": "b",
                "hints": [
                    "Voyager has no astronauts on board — it's a robotic probe.",
                    "The record is a message in a bottle — a cosmic 'hello' from humanity.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Voyager 1's Golden Record contains greetings in 55 languages, sounds of nature, music from around the world, and 115 images of life on Earth. Carl Sagan helped choose the contents. It's a cosmic message in a bottle! Voyager 1 is now over 24 billion km from Earth and still sending back data.",
                "is_boss": False,
                "flavor": "Puck holds up a tiny golden disc. 'A message from all of humanity — sailing through the stars.'",
            },
            {
                "id": "se_apollo11",
                "title": "One Giant Leap",
                "type": "quiz",
                "question": "In 1969, Apollo 11 made history. What did it achieve?",
                "options": [
                    "First satellite to orbit Earth",
                    "First humans to walk on the Moon",
                    "First spacecraft to leave the solar system",
                    "First telescope launched into space",
                ],
                "answer": "b",
                "hints": [
                    "Neil Armstrong said some very famous words when he stepped out of the spacecraft.",
                    "'That's one small step for man, one giant leap for mankind.'",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "On July 20, 1969, Apollo 11 astronauts Neil Armstrong and Buzz Aldrin became the first humans to walk on the Moon, while Michael Collins orbited above. About 600 million people watched on TV — one of the biggest audiences in history. They spent about 2 hours on the surface and brought back 22 kg of Moon rocks!",
                "is_boss": False,
                "flavor": "Puck plants a tiny flag on top of the telescope. 'One small step!'",
            },
            {
                "id": "se_artemis",
                "title": "Return to the Moon",
                "type": "quiz",
                "question": "NASA's Artemis program aims to send humans back to the Moon. What makes Artemis different from Apollo?",
                "options": [
                    "Artemis will build a space station orbiting the Moon called Gateway",
                    "Artemis will only send robots, not humans",
                    "Artemis will fly to the Sun instead",
                    "Artemis uses the same 1960s rockets as Apollo",
                ],
                "answer": "a",
                "hints": [
                    "Artemis doesn't just want to visit — it wants to stay.",
                    "Think about having a base in orbit around the Moon as a stepping stone.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The Artemis program plans to establish a long-term human presence on and around the Moon. The Gateway station will orbit the Moon, serving as a waypoint for missions to the surface and eventually to Mars! Artemis also aims to land the first woman and first person of colour on the Moon.",
                "is_boss": False,
                "flavor": "Puck draws a little space station orbiting the Moon. 'This time, we're not just visiting.'",
            },
            {
                "id": "se_future_mars",
                "title": "The Next Giant Leap",
                "type": "text",
                "question": "Many people believe the next great destination for human explorers is a planet in our solar system. Which planet do most space agencies plan to send humans to next?",
                "options": [],
                "answer": "mars",
                "hints": [
                    "It's the Red Planet — our closest neighbour that has a solid surface.",
                    "NASA, SpaceX, and other agencies are all working on plans to get humans there.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Mars is the next great goal for human space exploration! It has a solid surface, a thin atmosphere, water ice at its poles, and a day almost the same length as Earth's. Getting there takes about 7 months. NASA, SpaceX, ESA, and China are all working on plans to send humans to Mars, possibly in the 2030s or 2040s.",
                "is_boss": True,
                "flavor": "Puck gazes at a red dot in the sky. 'Someday — maybe in YOUR lifetime — humans will walk on that world.'",
            },
        ],
    },

    # ── Zone 5: Astronauts & Space Life ───────────────────────────────
    "astronauts_space_life": {
        "id": "astronauts_space_life",
        "name": "Astronauts & Space Life",
        "description": "Discover what it takes to become an astronaut and what life is like in space",
        "level_required": 9,
        "challenges": [
            {
                "id": "al_becoming_astronaut",
                "title": "How to Become an Astronaut",
                "type": "quiz",
                "question": "Becoming an astronaut is extremely competitive. When NASA opens applications, how many people typically apply for just a handful of spots?",
                "options": [
                    "About 50 people",
                    "About 500 people",
                    "About 18,000 people",
                    "About 1 million people",
                ],
                "answer": "c",
                "hints": [
                    "It's harder to get in than almost any university!",
                    "In 2017, over 18,000 people applied and only 12 were selected.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "In NASA's 2017 astronaut class, over 18,300 people applied and only 12 were selected — a 0.065% acceptance rate! Astronaut candidates need a degree in science, engineering, or maths, plus years of professional experience. Then they train for 2 years before they're even eligible for a mission.",
                "is_boss": False,
                "flavor": "Puck holds up a tiny application form. 'Ready to apply? It's the hardest job interview on — or off — Earth!'",
            },
            {
                "id": "al_space_suits",
                "title": "Your Personal Spaceship",
                "type": "quiz",
                "question": "A spacesuit is like a personal spaceship. What does it protect astronauts from during a spacewalk?",
                "options": [
                    "Only cold temperatures",
                    "Only the vacuum of space",
                    "Extreme temperatures, radiation, micrometeorites, and the vacuum of space",
                    "Only floating away",
                ],
                "answer": "c",
                "hints": [
                    "Space is a very dangerous place — there are many threats at once.",
                    "A suit has to handle extreme cold AND extreme heat, plus protect from tiny rocks and harmful rays.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A spacesuit is a wearable spacecraft! It provides oxygen, removes carbon dioxide, maintains air pressure, shields against radiation, protects against micrometeoroids, and regulates temperature (from -157°C in shadow to 121°C in sunlight). Each suit costs about $12 million and weighs about 130 kg on Earth!",
                "is_boss": False,
                "flavor": "Puck tries on an imaginary helmet. 'Fourteen layers of protection between you and the void!'",
            },
            {
                "id": "al_eating_space",
                "title": "Space Food",
                "type": "quiz",
                "question": "Eating in space is tricky because everything floats. How do astronauts keep their food from floating away?",
                "options": [
                    "They eat only pills instead of real food",
                    "Food is sticky, squeezable, or has Velcro packaging to attach to surfaces",
                    "They eat while spinning to create gravity",
                    "A robot holds their food for them",
                ],
                "answer": "b",
                "hints": [
                    "Some foods are in squeezable pouches (like toothpaste tubes), and trays can stick to surfaces.",
                    "Crumbly food is avoided because crumbs float into equipment!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Space food comes in special packaging — squeezable pouches, cans, and dehydrated packets that astronauts add water to. Tortillas are preferred over bread because bread makes floating crumbs that could damage equipment! Food trays have Velcro and magnets to stick to surfaces. Astronauts can even eat fresh fruit when supply ships arrive.",
                "is_boss": False,
                "flavor": "Puck chases a floating blob of orange juice through the observatory. 'Catch it before it hits the computer!'",
            },
            {
                "id": "al_sleeping_space",
                "title": "Sleeping Without Gravity",
                "type": "text",
                "question": "In space, there is no up or down, and astronauts float while they sleep. What do astronauts sleep in to keep from drifting around the station? Type your answer.",
                "options": [],
                "answer": "sleeping bag",
                "hints": [
                    "They strap themselves into something soft that's attached to the wall.",
                    "It's like a bag you'd take camping, but attached to the space station wall!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Astronauts sleep in sleeping bags that are strapped to the wall of the space station! Without these, they'd float around and bump into things. They can sleep in any direction — there's no 'up' in space. Most astronauts say it's incredibly comfortable once you get used to the floating feeling!",
                "is_boss": False,
                "flavor": "Puck zips himself into a sleeping bag on the observatory wall and pretends to snore.",
            },
            {
                "id": "al_exercise",
                "title": "Working Out in Space",
                "type": "quiz",
                "question": "Astronauts on the ISS must exercise for about 2 hours every day. Why is exercise so important in space?",
                "options": [
                    "To generate electricity for the station",
                    "Because without gravity, muscles and bones weaken quickly",
                    "To make the station spin for artificial gravity",
                    "To stay warm because the station has no heating",
                ],
                "answer": "b",
                "hints": [
                    "On Earth, gravity makes your muscles and bones work all the time just to hold you up.",
                    "Without that constant effort, your body starts to lose muscle and bone density.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "In microgravity, the body doesn't need to work against gravity, so muscles shrink and bones lose density — up to 1-2% of bone mass per month! Astronauts exercise 2 hours daily on special treadmills, bikes, and resistance machines to stay healthy. Even so, they need months of rehabilitation after returning to Earth.",
                "is_boss": False,
                "flavor": "Puck does floating push-ups. 'These are way easier without gravity — and that's the problem!'",
            },
            {
                "id": "al_water_space",
                "title": "Every Drop Counts",
                "type": "quiz",
                "question": "Water is heavy and expensive to launch into space. How does the ISS get most of its water?",
                "options": [
                    "Water is delivered fresh every week by rockets",
                    "The station collects passing comets",
                    "It recycles almost all water — including from astronauts' sweat and breath",
                    "Astronauts don't need water in space",
                ],
                "answer": "c",
                "hints": [
                    "Launching 1 kg to the ISS costs thousands of dollars, so they reuse everything they can.",
                    "The station has very advanced recycling systems that recover water from surprising places!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The ISS recycles about 90% of all water on board! The Water Recovery System purifies water from humidity in the air (sweat and breath), from the hygiene system, and even from urine. Astronauts joke that 'yesterday's coffee is tomorrow's coffee.' It's actually cleaner than most tap water on Earth!",
                "is_boss": False,
                "flavor": "Puck makes a face. 'Recycled from WHAT? ...Actually, don't tell me.'",
            },
            {
                "id": "al_spacewalk",
                "title": "Walking in the Void",
                "type": "quiz",
                "question": "During a spacewalk (EVA), astronauts work outside the space station. What is the biggest danger they face from tiny objects?",
                "options": [
                    "Space dust makes them sneeze",
                    "Micrometeorites and debris travelling at thousands of km/h can puncture suits",
                    "Floating tools block their view",
                    "Paint chips make the station ugly",
                ],
                "answer": "b",
                "hints": [
                    "Even a tiny fleck of paint can be dangerous when it's moving at extreme speed.",
                    "At orbital speeds, even a 1 cm piece of debris hits with the force of a hand grenade!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Space debris is a serious threat! There are millions of pieces of junk orbiting Earth — from old satellites to tiny paint flecks. At orbital speeds of 28,000 km/h, even a 1 cm piece can cause serious damage. Spacesuits have multiple protective layers, and the ISS regularly manoeuvres to dodge tracked debris.",
                "is_boss": False,
                "flavor": "Puck ducks as a tiny dot zips past. 'That paint chip was going 10 times faster than a bullet!'",
            },
            {
                "id": "al_training",
                "title": "The Ultimate Training",
                "type": "quiz",
                "question": "Astronauts train underwater in a giant pool to prepare for spacewalks. How does being underwater help?",
                "options": [
                    "Water is exactly like outer space",
                    "Buoyancy underwater simulates the feeling of weightlessness in space",
                    "Astronauts need to learn to swim in their spacesuits",
                    "The pool is actually in space",
                ],
                "answer": "b",
                "hints": [
                    "When you float in water, you feel lighter — that's similar to how space feels.",
                    "NASA's pool is called the Neutral Buoyancy Laboratory and holds 23 million litres!",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "NASA's Neutral Buoyancy Laboratory is a massive pool that holds 23 million litres of water and contains full-size replicas of ISS modules! Astronauts wear their spacesuits and are weighted to be neutrally buoyant — neither floating up nor sinking — which feels similar to weightlessness. They train for 7 hours underwater for every 1 hour of actual spacewalk time.",
                "is_boss": True,
                "flavor": "Puck cannonballs into an imaginary pool wearing a tiny spacesuit. 'Seven hours of practice for every one hour in space!'",
            },
        ],
    },
}
