"""
zones.py — Human Body & Health zones and challenges for the Body Explorer skill pack.

All challenges use "type": "quiz" with multiple-choice options.
Designed for ages 7-10, guided warmly by Puck.
"""

ZONE_ORDER = [
    "bones_and_muscles",
    "heart_and_blood",
    "lungs_and_breathing",
    "brain_and_nerves",
    "digestion",
    "exercise_and_fitness",
    "germs_and_immunity",
    "growing_up",
]

ZONES = {
    # ── Zone 1: Bones & Muscles ──────────────────────────────────────
    "bones_and_muscles": {
        "id": "bones_and_muscles",
        "name": "The Skeleton Crew",
        "description": "Discover the bones and muscles that hold you up and help you move",
        "level_required": 1,
        "challenges": [
            {
                "id": "how_many_bones",
                "title": "Counting Bones",
                "type": "quiz",
                "question": "How many bones does an adult human body have?",
                "options": ["106", "206", "306", "406"],
                "answer": "b",
                "hints": [
                    "It's more than 200 but less than 210.",
                    "Babies are actually born with about 270 bones that fuse together as they grow!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "An adult human has 206 bones. Babies are born with around 270, but many of them fuse together as you grow. Your skeleton gives your body its shape and protects your organs.",
                "is_boss": False,
                "flavor": "Puck taps a tiny skeleton on the page. It waves.",
            },
            {
                "id": "biggest_bone",
                "title": "The Longest Bone",
                "type": "quiz",
                "question": "What is the longest bone in your body?",
                "options": ["Your spine", "Your arm bone (humerus)", "Your thigh bone (femur)", "Your shin bone (tibia)"],
                "answer": "c",
                "hints": [
                    "It's in your leg, between your hip and your knee.",
                    "Its scientific name is the femur.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The femur (thigh bone) is the longest and strongest bone in your body. It runs from your hip to your knee and has to support your whole body weight when you walk, run, and jump!",
                "is_boss": False,
                "flavor": "Puck stretches a leg and points at it proudly.",
            },
            {
                "id": "smallest_bone",
                "title": "Tiny But Mighty",
                "type": "quiz",
                "question": "Where is the smallest bone in your body found?",
                "options": ["In your toe", "In your ear", "In your finger", "In your nose"],
                "answer": "b",
                "hints": [
                    "This bone helps you hear sounds.",
                    "It's called the stirrup bone (stapes) and it's only about 3mm long!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The smallest bone in your body is the stapes (stirrup bone) inside your ear. It's only about 3 millimeters long — smaller than a grain of rice! It vibrates to help carry sound to your brain.",
                "is_boss": False,
                "flavor": "Puck cups a hand to one ear and whispers, 'Can you hear that tiny bone working?'",
            },
            {
                "id": "joints_work",
                "title": "Bending and Twisting",
                "type": "quiz",
                "question": "What do we call the places where two bones meet and allow your body to bend?",
                "options": ["Muscles", "Joints", "Tendons", "Ribs"],
                "answer": "b",
                "hints": [
                    "Your knee and elbow both have one of these.",
                    "Without these, your skeleton would be completely stiff!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Joints are the places where two bones meet. They let your body bend, twist, and move. Your knee is a hinge joint (like a door), while your shoulder is a ball-and-socket joint that can rotate in many directions.",
                "is_boss": False,
                "flavor": "Puck bends an elbow and a knee, then spins a shoulder around in a circle.",
            },
            {
                "id": "spine_purpose",
                "title": "Your Body's Tower",
                "type": "quiz",
                "question": "What does your spine (backbone) protect?",
                "options": ["Your lungs", "Your stomach", "Your spinal cord", "Your heart"],
                "answer": "c",
                "hints": [
                    "The thing it protects carries messages between your brain and body.",
                    "Your spine is made of 33 small bones called vertebrae, stacked like a tower.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Your spine is a column of 33 bones called vertebrae. It protects your spinal cord — the information highway that carries messages between your brain and the rest of your body. Without it, you couldn't move a finger!",
                "is_boss": False,
                "flavor": "Puck traces a glowing line down the skeleton's back. It lights up like a highway.",
            },
            {
                "id": "muscles_work",
                "title": "The Muscle Machine",
                "type": "quiz",
                "question": "How do muscles make your bones move?",
                "options": [
                    "They push the bones apart",
                    "They pull on the bones by contracting (getting shorter)",
                    "They spin the bones around",
                    "They pump air into the bones",
                ],
                "answer": "b",
                "hints": [
                    "When you flex your arm, feel your bicep get shorter and harder.",
                    "Muscles can pull but they can't push — that's why they work in pairs!",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Muscles move your bones by contracting — getting shorter and pulling. They always work in pairs: when your bicep contracts to bend your arm, your tricep relaxes. Then they swap to straighten it. You have over 600 muscles in your body!",
                "is_boss": True,
                "flavor": "Puck flexes a tiny arm. The skeleton on the page flexes too!",
            },
        ],
    },

    # ── Zone 2: Heart & Blood ────────────────────────────────────────
    "heart_and_blood": {
        "id": "heart_and_blood",
        "name": "The Beating Engine",
        "description": "Follow the blood as it flows through your heart and body",
        "level_required": 3,
        "challenges": [
            {
                "id": "heart_job",
                "title": "The Heart's Job",
                "type": "quiz",
                "question": "What is the main job of your heart?",
                "options": [
                    "To digest food",
                    "To pump blood around your body",
                    "To breathe in air",
                    "To store memories",
                ],
                "answer": "b",
                "hints": [
                    "Put your hand on your chest — can you feel it working right now?",
                    "It beats about 100,000 times every single day!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Your heart is a muscle about the size of your fist that pumps blood around your entire body. It beats about 100,000 times a day — that's over 35 million times a year! Blood carries oxygen and nutrients to every cell.",
                "is_boss": False,
                "flavor": "Puck places a tiny hand on the page. A heartbeat sound pulses through the Primer: thump-thump, thump-thump.",
            },
            {
                "id": "heart_chambers",
                "title": "Four Rooms",
                "type": "quiz",
                "question": "How many chambers (rooms) does the human heart have?",
                "options": ["Two", "Three", "Four", "Six"],
                "answer": "c",
                "hints": [
                    "There are two on top (atria) and two on the bottom (ventricles).",
                    "The right side sends blood to the lungs; the left side sends it to the body.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Your heart has four chambers: two atria on top that receive blood, and two ventricles on the bottom that pump it out. The right side sends blood to your lungs to get oxygen, and the left side pumps that oxygen-rich blood to the rest of your body.",
                "is_boss": False,
                "flavor": "The Primer shows a glowing heart with four rooms, each one pulsing with light.",
            },
            {
                "id": "arteries_veins",
                "title": "Red Roads and Blue Highways",
                "type": "quiz",
                "question": "What is the difference between arteries and veins?",
                "options": [
                    "Arteries carry blood away from the heart; veins carry blood back to it",
                    "Arteries are in your arms; veins are in your legs",
                    "Arteries carry water; veins carry blood",
                    "There is no difference — they are the same thing",
                ],
                "answer": "a",
                "hints": [
                    "Think: Arteries carry blood AWAY (both start with 'A').",
                    "Veins bring used blood back to the heart to get more oxygen.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Arteries carry oxygen-rich blood AWAY from your heart to your body. Veins carry blood BACK to the heart after the oxygen has been used up. A handy trick: Arteries = Away, both start with 'A'!",
                "is_boss": False,
                "flavor": "Red and blue rivers of light branch across the body on the page — arteries in red, veins in blue.",
            },
            {
                "id": "blood_cells",
                "title": "Tiny Workers in the Blood",
                "type": "quiz",
                "question": "Which type of blood cell carries oxygen around your body?",
                "options": ["White blood cells", "Platelets", "Red blood cells", "Plasma"],
                "answer": "c",
                "hints": [
                    "They are the reason blood looks red!",
                    "They pick up oxygen in your lungs and deliver it everywhere else.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Red blood cells carry oxygen from your lungs to every part of your body. They get their red colour from a protein called haemoglobin. You have about 25 trillion red blood cells — and your body makes 2 million new ones every second!",
                "is_boss": False,
                "flavor": "Tiny red discs float through a river of light on the page, each carrying a sparkle of oxygen.",
            },
            {
                "id": "find_pulse",
                "title": "Feel the Beat",
                "type": "quiz",
                "question": "When you press two fingers on the inside of your wrist, what are you feeling?",
                "options": [
                    "Your muscles contracting",
                    "Your pulse — your heartbeat pushing blood through an artery",
                    "Air moving under your skin",
                    "Your bones vibrating",
                ],
                "answer": "b",
                "hints": [
                    "Try it right now! Press gently on the inside of your wrist near your thumb.",
                    "Each little beat you feel matches one heartbeat.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Your pulse is the rhythmic push of blood through your arteries each time your heart beats. You can feel it at your wrist or neck. A normal resting heart rate for kids is about 70-100 beats per minute.",
                "is_boss": False,
                "flavor": "Puck presses two fingers to the page. A gentle rhythm appears: beat… beat… beat…",
            },
            {
                "id": "heart_size",
                "title": "How Big Is Your Heart?",
                "type": "quiz",
                "question": "Your heart is roughly the same size as what?",
                "options": ["A watermelon", "Your fist", "A pea", "A football"],
                "answer": "b",
                "hints": [
                    "Make a fist right now — that's about the right size!",
                    "It grows as you grow. An adult's heart is bigger than a child's heart.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Your heart is roughly the size of your fist! As you grow, your heart grows too. Even though it's not very big, it's incredibly strong — powerful enough to pump blood through 100,000 kilometres of blood vessels.",
                "is_boss": True,
                "flavor": "Puck holds up a fist next to a glowing heart on the page. They're the same size!",
            },
        ],
    },

    # ── Zone 3: Lungs & Breathing ────────────────────────────────────
    "lungs_and_breathing": {
        "id": "lungs_and_breathing",
        "name": "The Breath of Life",
        "description": "Discover how your lungs fill with air and keep you alive",
        "level_required": 5,
        "challenges": [
            {
                "id": "lungs_job",
                "title": "What Lungs Do",
                "type": "quiz",
                "question": "What is the main job of your lungs?",
                "options": [
                    "To pump blood",
                    "To take in oxygen and get rid of carbon dioxide",
                    "To digest food",
                    "To filter water",
                ],
                "answer": "b",
                "hints": [
                    "You use them every time you breathe in and out.",
                    "They swap a gas your body needs (oxygen) for one it doesn't (carbon dioxide).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Your lungs bring fresh oxygen into your body when you breathe in, and push out waste carbon dioxide when you breathe out. Oxygen is fuel for every cell in your body — you can't live without it for more than a few minutes.",
                "is_boss": False,
                "flavor": "Puck takes a deep breath. The two lungs on the page expand and glow pink.",
            },
            {
                "id": "how_many_lungs",
                "title": "A Pair of Air Bags",
                "type": "quiz",
                "question": "How many lungs do you have, and are they the same size?",
                "options": [
                    "One large lung in the center",
                    "Two lungs — the left one is slightly smaller to make room for the heart",
                    "Two lungs — both exactly the same size",
                    "Three lungs — two on the right, one on the left",
                ],
                "answer": "b",
                "hints": [
                    "You have two, but one is a little smaller than the other.",
                    "Your heart sits slightly to the left, so it needs extra room on that side.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "You have two lungs, but they are not quite the same size. Your left lung is slightly smaller because your heart sits in the left side of your chest and needs room. Your right lung has three lobes (sections) while your left lung has only two.",
                "is_boss": False,
                "flavor": "Puck points to the heart sitting snugly next to the smaller left lung. 'They're sharing space!'",
            },
            {
                "id": "diaphragm_role",
                "title": "The Hidden Muscle",
                "type": "quiz",
                "question": "Which muscle sits below your lungs and helps you breathe?",
                "options": ["Your bicep", "Your diaphragm", "Your heart", "Your abs"],
                "answer": "b",
                "hints": [
                    "It's a dome-shaped muscle that flattens when you breathe in.",
                    "When it moves down, your lungs expand and air rushes in.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The diaphragm is a large, dome-shaped muscle just below your lungs. When you breathe in, it contracts and flattens, pulling your lungs down so they fill with air. When you breathe out, it relaxes back into a dome shape and air is pushed out.",
                "is_boss": False,
                "flavor": "A dome-shaped muscle glows below the lungs. It flattens — air rushes in. It rises — air flows out.",
            },
            {
                "id": "oxygen_co2",
                "title": "The Great Gas Swap",
                "type": "quiz",
                "question": "In your lungs, oxygen passes into your blood. What gas passes OUT of your blood into your lungs to be breathed out?",
                "options": ["Nitrogen", "Helium", "Carbon dioxide", "Hydrogen"],
                "answer": "c",
                "hints": [
                    "It's the same gas that makes fizzy bubbles in soda!",
                    "Your cells make it as waste when they use oxygen for energy.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Inside your lungs, tiny air sacs called alveoli swap gases with your blood: oxygen goes IN and carbon dioxide comes OUT. Carbon dioxide is a waste gas your cells make when they use oxygen. You breathe it out with every single breath!",
                "is_boss": False,
                "flavor": "Tiny blue and red bubbles swap places in the glowing lung on the page. In goes oxygen, out goes CO2.",
            },
            {
                "id": "hiccups_cause",
                "title": "Hic! Hic! Hic!",
                "type": "quiz",
                "question": "What causes hiccups?",
                "options": [
                    "Your heart skipping a beat",
                    "Your diaphragm twitching or spasming suddenly",
                    "Your lungs sneezing inside your chest",
                    "Your brain forgetting to breathe",
                ],
                "answer": "b",
                "hints": [
                    "Remember that dome-shaped breathing muscle? Sometimes it gets a bit twitchy!",
                    "The 'hic' sound comes from your vocal cords snapping shut when air rushes in suddenly.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Hiccups happen when your diaphragm suddenly twitches or spasms. This makes you gulp in air very quickly, and your vocal cords snap shut — that's the 'hic' sound! Hiccups are harmless and usually stop on their own.",
                "is_boss": True,
                "flavor": "Puck hiccups on the page. Hic! Hic! The whole Primer shakes with each one.",
            },
        ],
    },

    # ── Zone 4: Brain & Nerves ───────────────────────────────────────
    "brain_and_nerves": {
        "id": "brain_and_nerves",
        "name": "Mission Control",
        "description": "Explore the brain, the nerves, and how you think, feel, and sense the world",
        "level_required": 7,
        "challenges": [
            {
                "id": "brain_job",
                "title": "The Boss of Your Body",
                "type": "quiz",
                "question": "What is the brain's main job?",
                "options": [
                    "To pump blood",
                    "To control everything your body does — thinking, moving, feeling, remembering",
                    "To digest food",
                    "To keep your bones strong",
                ],
                "answer": "b",
                "hints": [
                    "It's the reason you can read this question right now!",
                    "Without it, you couldn't think, move, breathe, or even dream.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Your brain is the command center of your entire body. It controls every thought, every movement, every memory, and every feeling. It even keeps your heart beating and your lungs breathing while you sleep!",
                "is_boss": False,
                "flavor": "Puck taps the top of the tiny body on the page. The brain lights up like a city at night.",
            },
            {
                "id": "neurons_message",
                "title": "Lightning Messengers",
                "type": "quiz",
                "question": "What are neurons?",
                "options": [
                    "Tiny bones inside the brain",
                    "Special cells that carry electrical messages through your body",
                    "Red blood cells inside your head",
                    "Muscles that help you think",
                ],
                "answer": "b",
                "hints": [
                    "Your brain has about 86 billion of them!",
                    "They send messages using tiny electrical signals — like a living internet.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Neurons are special cells that carry electrical messages through your body at amazing speeds — up to 270 miles per hour! Your brain alone has about 86 billion neurons, all connected to each other in a vast network.",
                "is_boss": False,
                "flavor": "Sparks of light race along tiny branching paths inside the brain. Puck watches in wonder.",
            },
            {
                "id": "five_senses",
                "title": "The Five Senses",
                "type": "quiz",
                "question": "Which of these is NOT one of the five main senses?",
                "options": ["Sight", "Balance", "Taste", "Touch"],
                "answer": "b",
                "hints": [
                    "The five senses are: sight, hearing, taste, smell, and touch.",
                    "Balance is actually a bonus sense (controlled by your inner ear), but it's not one of the classic five!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The five main senses are sight, hearing, taste, smell, and touch. Each one sends signals to your brain through special sensory neurons. Fun fact: you actually have MORE than five senses — balance and temperature-sensing are bonus ones!",
                "is_boss": False,
                "flavor": "Five glowing icons appear: an eye, an ear, a tongue, a nose, and a hand.",
            },
            {
                "id": "reflexes_work",
                "title": "Faster Than Thinking",
                "type": "quiz",
                "question": "When you touch something hot and pull your hand away instantly, what is that called?",
                "options": ["A habit", "A reflex", "A guess", "A dream"],
                "answer": "b",
                "hints": [
                    "It happens so fast you don't even think about it!",
                    "Your spinal cord handles it before the message even reaches your brain.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "A reflex is an automatic response that happens before your brain even has time to think. When you touch something hot, the message goes to your spinal cord, which sends an instant command to pull away. This speed protects you from injury!",
                "is_boss": False,
                "flavor": "A tiny hand touches a flame on the page and snaps back in a flash. Puck grins: 'Your body is faster than your brain!'",
            },
            {
                "id": "brain_protection",
                "title": "The Brain's Armor",
                "type": "quiz",
                "question": "What protects your brain from bumps and injuries?",
                "options": [
                    "Your hair",
                    "Your skull (a hard bone) and fluid that cushions the brain inside",
                    "A layer of muscle wrapped around it",
                    "Nothing — the brain is very tough on its own",
                ],
                "answer": "b",
                "hints": [
                    "Your brain is actually quite soft — like firm jelly! It needs hard protection.",
                    "There's a hard shell of bone AND a layer of liquid cushioning.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Your brain is protected by your skull — a hard shell of bone — and by cerebrospinal fluid that surrounds the brain like a liquid cushion. The brain itself is soft, about the texture of firm tofu, so it needs all that protection!",
                "is_boss": False,
                "flavor": "Puck knocks on the skull. It's rock-solid! Inside, the brain floats gently in clear fluid.",
            },
            {
                "id": "brain_halves",
                "title": "Two Halves, One Brain",
                "type": "quiz",
                "question": "The brain is divided into two halves (hemispheres). What connects them so they can talk to each other?",
                "options": [
                    "A blood vessel",
                    "A thick bundle of nerve fibers called the corpus callosum",
                    "A small bone",
                    "They don't connect — each half works alone",
                ],
                "answer": "b",
                "hints": [
                    "The two halves need a 'bridge' made of millions of nerve fibers.",
                    "It's called the corpus callosum — like a super-highway between left and right brain.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Your brain has two halves called hemispheres, connected by the corpus callosum — a thick bridge of about 200 million nerve fibers. The left hemisphere mostly controls the right side of your body, and the right hemisphere controls the left side!",
                "is_boss": True,
                "flavor": "The brain on the page splits gently into two glowing halves, joined by a shimmering bridge of light.",
            },
        ],
    },

    # ── Zone 5: Digestion ────────────────────────────────────────────
    "digestion": {
        "id": "digestion",
        "name": "The Food Factory",
        "description": "Follow your food on an incredible journey from mouth to fuel",
        "level_required": 9,
        "challenges": [
            {
                "id": "digestion_start",
                "title": "Where Digestion Begins",
                "type": "quiz",
                "question": "Where does digestion first begin?",
                "options": ["In the stomach", "In the mouth", "In the intestines", "In the throat"],
                "answer": "b",
                "hints": [
                    "Think about what happens the moment you take a bite of food.",
                    "Your teeth break food into pieces and saliva starts dissolving it.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Digestion starts in your mouth! Your teeth chop and grind food into smaller pieces, and your saliva (spit) contains enzymes that start breaking down starches right away. By the time you swallow, digestion is already underway.",
                "is_boss": False,
                "flavor": "Puck takes a bite of a tiny apple on the page. 'It's already starting!'",
            },
            {
                "id": "stomach_acid",
                "title": "The Acid Pool",
                "type": "quiz",
                "question": "What does your stomach use to break down food?",
                "options": [
                    "Water and nothing else",
                    "Strong acid and special chemicals called enzymes",
                    "Tiny teeth inside the stomach",
                    "Heat from your body",
                ],
                "answer": "b",
                "hints": [
                    "Your stomach is like a churning pool of powerful chemicals.",
                    "The acid is so strong it could dissolve metal — but your stomach lining protects you!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Your stomach produces hydrochloric acid and enzymes that break food into a soupy mixture. The acid is incredibly strong — but your stomach has a special mucus lining that protects it. Food stays in your stomach for 2-4 hours.",
                "is_boss": False,
                "flavor": "The stomach on the page churns and bubbles. Puck peers in carefully: 'Don't fall in!'",
            },
            {
                "id": "small_intestine_job",
                "title": "The Nutrient Catcher",
                "type": "quiz",
                "question": "Which organ absorbs most of the nutrients (vitamins, minerals, energy) from your food?",
                "options": ["The stomach", "The mouth", "The small intestine", "The large intestine"],
                "answer": "c",
                "hints": [
                    "Despite its name, it's actually very long — about 6 meters!",
                    "Its walls are covered in tiny finger-like bumps called villi that grab nutrients.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The small intestine is where most nutrient absorption happens. It's about 6 meters (20 feet) long and lined with millions of tiny finger-like bumps called villi. These villi grab vitamins, minerals, and energy from your food and pass them into your blood.",
                "is_boss": False,
                "flavor": "A long, winding tube uncoils on the page. Tiny glowing villi wave like sea anemones, catching nutrients.",
            },
            {
                "id": "teeth_types",
                "title": "Types of Teeth",
                "type": "quiz",
                "question": "What are your sharp, pointy teeth (next to your front teeth) called, and what do they do?",
                "options": [
                    "Molars — they bite things in half",
                    "Canines — they tear and rip food",
                    "Incisors — they grind food flat",
                    "Wisdom teeth — they chew slowly",
                ],
                "answer": "b",
                "hints": [
                    "They're named after dogs (canines) because they look like fangs!",
                    "You have four of them — two on top, two on bottom.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "You have four types of teeth: incisors (front teeth for cutting), canines (pointy teeth for tearing), premolars (for crushing), and molars (flat back teeth for grinding). Together they break food into tiny pieces so your stomach can handle it.",
                "is_boss": False,
                "flavor": "A set of teeth appears on the page, each type glowing a different color. Puck points to the pointy ones.",
            },
            {
                "id": "food_journey_time",
                "title": "The Long Journey",
                "type": "quiz",
                "question": "Roughly how long does it take for food to travel all the way through your digestive system?",
                "options": ["About 1 hour", "About 6 hours", "About 24 to 72 hours", "About 1 week"],
                "answer": "c",
                "hints": [
                    "It's much longer than most people think!",
                    "The small and large intestines are very long, and food moves slowly through them.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Food takes about 24 to 72 hours to travel through your entire digestive system! It spends 2-4 hours in the stomach, 4-6 hours in the small intestine, and up to 36 hours in the large intestine. The whole tube from mouth to end is about 9 meters long!",
                "is_boss": True,
                "flavor": "Puck traces the entire winding path on the page, from mouth all the way to the end. 'That's a long road!'",
            },
        ],
    },

    # ── Zone 6: Exercise & Fitness ───────────────────────────────────
    "exercise_and_fitness": {
        "id": "exercise_and_fitness",
        "name": "Move, Stretch, Grow!",
        "description": "Learn why exercise, sleep, and staying active keep your body strong",
        "level_required": 11,
        "challenges": [
            {
                "id": "why_exercise",
                "title": "Why Move?",
                "type": "quiz",
                "question": "Why is regular exercise important for kids?",
                "options": [
                    "It only matters for adults, not children",
                    "It makes bones and muscles stronger, helps your heart, and boosts your mood",
                    "It's only important if you want to be a professional athlete",
                    "It helps you grow taller but nothing else",
                ],
                "answer": "b",
                "hints": [
                    "Exercise helps almost every part of your body — not just your muscles!",
                    "It even helps your brain work better and makes you feel happier.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Exercise makes your bones stronger, your muscles more powerful, your heart healthier, and your brain sharper. It also releases chemicals called endorphins that make you feel happy! Kids should aim for at least 60 minutes of active play every day.",
                "is_boss": False,
                "flavor": "Puck does jumping jacks on the page, grinning the whole time.",
            },
            {
                "id": "cardio_exercise",
                "title": "Heart-Pumping Fun",
                "type": "quiz",
                "question": "Running, swimming, and cycling are all examples of what type of exercise?",
                "options": ["Flexibility exercise", "Strength exercise", "Cardio (aerobic) exercise", "Balance exercise"],
                "answer": "c",
                "hints": [
                    "These exercises make your heart beat faster and your lungs work harder.",
                    "'Cardio' comes from the Greek word for heart!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Cardio (aerobic) exercise is any activity that gets your heart pumping faster and your lungs breathing harder. Running, swimming, cycling, and dancing all count! Cardio makes your heart stronger and gives your body more endurance.",
                "is_boss": False,
                "flavor": "A tiny runner, swimmer, and cyclist race across the page. Their hearts glow brighter with every stride.",
            },
            {
                "id": "strength_exercise",
                "title": "Muscle Builders",
                "type": "quiz",
                "question": "Which activity is a good example of strength exercise?",
                "options": ["Reading a book", "Climbing on monkey bars", "Walking slowly", "Sleeping"],
                "answer": "b",
                "hints": [
                    "Strength exercises make your muscles work hard against resistance.",
                    "Think about activities where you push, pull, climb, or lift.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Strength exercises make your muscles work hard. For kids, this includes climbing, push-ups, carrying things, and playground activities like monkey bars. Strong muscles protect your joints and help you do everyday activities more easily.",
                "is_boss": False,
                "flavor": "Puck hangs from a tiny set of monkey bars, then does a pull-up. 'I'm getting stronger!'",
            },
            {
                "id": "flexibility_stretch",
                "title": "Bend Don't Break",
                "type": "quiz",
                "question": "What does flexibility mean for your body?",
                "options": [
                    "How fast you can run",
                    "How far your muscles and joints can stretch and move",
                    "How many push-ups you can do",
                    "How long you can hold your breath",
                ],
                "answer": "b",
                "hints": [
                    "Think about touching your toes or doing the splits.",
                    "Stretching and yoga help improve this!",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Flexibility is how far your muscles and joints can stretch and move. Good flexibility helps prevent injuries and makes movement easier. Stretching, yoga, and gymnastics all improve flexibility. Always stretch gently — never bounce!",
                "is_boss": False,
                "flavor": "Puck stretches into a perfect yoga pose on the page. 'Ahhhh, that feels nice!'",
            },
            {
                "id": "sleep_importance",
                "title": "The Power of Sleep",
                "type": "quiz",
                "question": "How many hours of sleep do kids aged 6-12 need each night?",
                "options": ["4-5 hours", "6-7 hours", "9-12 hours", "14-16 hours"],
                "answer": "c",
                "hints": [
                    "Kids need more sleep than adults!",
                    "During sleep, your body repairs itself and your brain organizes memories.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Kids aged 6-12 need 9-12 hours of sleep every night. While you sleep, your body repairs muscles, grows bones, and fights off germs. Your brain sorts through everything you learned that day and stores important memories. Sleep is a superpower!",
                "is_boss": False,
                "flavor": "Puck yawns and curls up on the page with a tiny blanket. Zzz…",
            },
            {
                "id": "exercise_minutes",
                "title": "The Daily Goal",
                "type": "quiz",
                "question": "How many minutes of physical activity should kids get every day?",
                "options": ["At least 10 minutes", "At least 30 minutes", "At least 60 minutes", "At least 120 minutes"],
                "answer": "c",
                "hints": [
                    "It's a full hour — but it doesn't have to be all at once!",
                    "Playing tag, riding a bike, or dancing all count.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Kids should get at least 60 minutes (one hour) of physical activity every day. It doesn't have to be all at once — playing at recess, walking to school, and dancing in your room all add up! The key is to move your body and have fun doing it.",
                "is_boss": True,
                "flavor": "A clock on the page fills up minute by minute as Puck runs, jumps, dances, and plays.",
            },
        ],
    },

    # ── Zone 7: Germs & Immunity ─────────────────────────────────────
    "germs_and_immunity": {
        "id": "germs_and_immunity",
        "name": "The Invisible Battle",
        "description": "Meet the tiny invaders and the amazing army that protects you",
        "level_required": 13,
        "challenges": [
            {
                "id": "bacteria_vs_viruses",
                "title": "Two Kinds of Tiny",
                "type": "quiz",
                "question": "What is one key difference between bacteria and viruses?",
                "options": [
                    "Bacteria are always harmful; viruses are always helpful",
                    "Bacteria are living cells; viruses are not truly alive and need a host cell to copy themselves",
                    "Viruses are bigger than bacteria",
                    "There is no difference between them",
                ],
                "answer": "b",
                "hints": [
                    "Bacteria are tiny single-celled creatures. Some are helpful (like gut bacteria)!",
                    "Viruses can't do anything on their own — they hijack your cells to make copies of themselves.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Bacteria are tiny living cells — some are helpful (gut bacteria help you digest food!) and some cause illness. Viruses are even smaller and are not truly alive. They need to invade your cells and hijack them to make more viruses. Colds and flu are caused by viruses.",
                "is_boss": False,
                "flavor": "On the page, a round bacterium wiggles happily. Next to it, a spiky virus floats menacingly.",
            },
            {
                "id": "white_blood_cells",
                "title": "Your Body's Soldiers",
                "type": "quiz",
                "question": "Which cells in your blood fight off germs and infections?",
                "options": ["Red blood cells", "White blood cells", "Platelets", "Skin cells"],
                "answer": "b",
                "hints": [
                    "They patrol your blood looking for invaders.",
                    "They can surround and destroy bacteria and viruses!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "White blood cells are your body's defence army. They patrol your blood and tissues, searching for germs. When they find an invader, they surround and destroy it. Some white blood cells remember old enemies so they can fight them faster next time!",
                "is_boss": False,
                "flavor": "A squad of glowing white cells marches across the page, surrounding a group of bacteria.",
            },
            {
                "id": "vaccines_work",
                "title": "Training the Army",
                "type": "quiz",
                "question": "How do vaccines help protect you from disease?",
                "options": [
                    "They kill all the germs already in your body",
                    "They teach your immune system to recognise a germ BEFORE you get sick",
                    "They make your skin thicker so germs can't get in",
                    "They add extra blood to your body",
                ],
                "answer": "b",
                "hints": [
                    "A vaccine is like a training exercise for your immune system.",
                    "It shows your body a harmless version of the germ so it can learn to fight the real thing.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Vaccines contain a harmless piece or weakened version of a germ. Your immune system learns to recognise it and builds defences. If the real germ ever shows up, your body already knows how to fight it — fast! Vaccines have saved millions of lives.",
                "is_boss": False,
                "flavor": "White blood cells study a tiny 'wanted poster' of a germ, then nod confidently. 'We'll know that one anywhere!'",
            },
            {
                "id": "hand_washing",
                "title": "The 20-Second Shield",
                "type": "quiz",
                "question": "How long should you wash your hands with soap and water to properly get rid of germs?",
                "options": ["3 seconds", "At least 20 seconds", "Exactly 2 minutes", "10 minutes"],
                "answer": "b",
                "hints": [
                    "Try singing 'Happy Birthday' twice — that's about the right amount of time!",
                    "Soap breaks apart the oily layer that germs hide in.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "You should wash your hands with soap and water for at least 20 seconds — about the time it takes to sing 'Happy Birthday' twice. Soap doesn't just rinse germs away; it actually breaks apart the outer layer of many germs and destroys them!",
                "is_boss": False,
                "flavor": "Puck scrubs tiny hands under running water, singing a little song. Germs wash away in the stream.",
            },
            {
                "id": "fever_purpose",
                "title": "The Heat Defence",
                "type": "quiz",
                "question": "When you get a fever (your body temperature rises), what is your body actually doing?",
                "options": [
                    "Overheating by accident — a fever is a mistake",
                    "Raising its temperature on purpose to help fight the infection",
                    "Trying to cool down",
                    "Burning up food for extra energy",
                ],
                "answer": "b",
                "hints": [
                    "A fever is actually your body's clever strategy!",
                    "Many germs can't survive well at higher temperatures.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A fever is your body's smart defence! When it detects an infection, it raises your temperature on purpose. The extra heat makes it harder for germs to survive and helps your white blood cells work faster. That's why you feel hot when you're fighting a cold.",
                "is_boss": False,
                "flavor": "A thermometer on the page rises. The germs look unhappy in the heat. 'Too warm for us!'",
            },
            {
                "id": "first_line_defence",
                "title": "The First Wall",
                "type": "quiz",
                "question": "What is your body's FIRST line of defence against germs — before white blood cells even get involved?",
                "options": [
                    "Your skin — it acts as a barrier that keeps most germs out",
                    "Your bones",
                    "Your muscles",
                    "Your hair",
                ],
                "answer": "a",
                "hints": [
                    "Think about what covers your entire body on the outside.",
                    "As long as this barrier isn't broken, most germs can't get in!",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Your skin is your body's first and biggest defence against germs. It acts as a wall that keeps invaders out. Tears, saliva, and mucus also trap germs. Stomach acid destroys germs in food. Only when germs get past all of these do white blood cells step in!",
                "is_boss": True,
                "flavor": "The skin glows like a golden shield around the body on the page. Germs bounce off it. 'Can't get through!'",
            },
        ],
    },

    # ── Zone 8: Growing Up ───────────────────────────────────────────
    "growing_up": {
        "id": "growing_up",
        "name": "The Amazing You",
        "description": "Discover how your body grows, changes, and becomes uniquely yours",
        "level_required": 15,
        "challenges": [
            {
                "id": "growth_spurts",
                "title": "Growing Fast",
                "type": "quiz",
                "question": "What is a 'growth spurt'?",
                "options": [
                    "When you suddenly get very hungry",
                    "A period when you grow taller faster than usual",
                    "When your hair grows really quickly",
                    "When you learn a new skill very fast",
                ],
                "answer": "b",
                "hints": [
                    "Have you ever noticed your trousers getting too short really quickly?",
                    "These happen a lot during childhood and again during the teen years.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A growth spurt is a period when you grow taller faster than usual. Kids often have growth spurts between ages 6-8 and again in their teens. During a big spurt, you might grow several centimeters in just a few months! That's why you sometimes outgrow clothes so fast.",
                "is_boss": False,
                "flavor": "The child on the page grows taller right before your eyes. Puck measures with a tiny ruler.",
            },
            {
                "id": "baby_vs_adult_teeth",
                "title": "Two Sets of Teeth",
                "type": "quiz",
                "question": "How many baby teeth do children have, and how many adult teeth will replace them?",
                "options": [
                    "10 baby teeth, 20 adult teeth",
                    "20 baby teeth, 32 adult teeth",
                    "32 baby teeth, 32 adult teeth",
                    "20 baby teeth, 20 adult teeth",
                ],
                "answer": "b",
                "hints": [
                    "You start with fewer teeth and end up with more!",
                    "Baby teeth: 20. Adult teeth: 32 (including wisdom teeth).",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Children have 20 baby (primary) teeth that start falling out around age 6. They are replaced by 32 adult (permanent) teeth. The last ones to come in are wisdom teeth, usually in your late teens. Take care of your adult teeth — they're the only set you'll get!",
                "is_boss": False,
                "flavor": "A tooth wiggles loose on the page and pops out. A bigger, shinier one grows in its place!",
            },
            {
                "id": "bones_grow",
                "title": "Bones That Grow",
                "type": "quiz",
                "question": "Babies have about 270 bones, but adults have only 206. Why?",
                "options": [
                    "Some bones disappear as you age",
                    "Many small bones fuse (join together) into bigger bones as you grow",
                    "Adults lose bones from not drinking enough milk",
                    "Doctors remove extra bones when you're young",
                ],
                "answer": "b",
                "hints": [
                    "The bones don't vanish — they merge together!",
                    "Your skull, for example, starts as several separate plates that slowly fuse.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Babies are born with about 270 bones, many made of soft cartilage. As you grow, many of these small bones fuse together into larger, harder bones. For example, a baby's skull has several separate plates that gradually fuse into one solid skull. By adulthood, you have 206 bones.",
                "is_boss": False,
                "flavor": "Tiny bones on the page slowly drift together and merge, glowing as they fuse. 'Growing up means growing together!'",
            },
            {
                "id": "healthy_habits",
                "title": "Everyday Superpowers",
                "type": "quiz",
                "question": "Which combination of habits helps keep a growing body healthy?",
                "options": [
                    "Eating only sweets, skipping sleep, and staying indoors",
                    "Eating a variety of foods, getting enough sleep, exercising, and drinking water",
                    "Eating one big meal a day and watching TV all evening",
                    "Only exercising and nothing else matters",
                ],
                "answer": "b",
                "hints": [
                    "There's no single magic trick — it's a combination of good habits!",
                    "Your body needs good fuel, rest, movement, and hydration.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A healthy body needs a mix of good habits: eat a variety of nutritious foods, drink plenty of water, get 9-12 hours of sleep, exercise for at least 60 minutes daily, and wash your hands regularly. No single thing does it all — it's the combination that matters!",
                "is_boss": False,
                "flavor": "Icons appear on the page: a plate of food, a glass of water, a bed, running shoes. Together they form a glowing shield.",
            },
            {
                "id": "puberty_basics",
                "title": "The Big Change",
                "type": "quiz",
                "question": "Puberty is a time when your body changes as you grow from a child into a young adult. When does it usually start?",
                "options": [
                    "At age 2-3",
                    "Between ages 8 and 13, depending on the person",
                    "Exactly on your 16th birthday",
                    "It happens overnight without any warning",
                ],
                "answer": "b",
                "hints": [
                    "It starts at different ages for different people — and that's completely normal!",
                    "Special chemicals called hormones tell your body it's time to start changing.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Puberty usually begins between ages 8 and 13 and is when your body starts changing into a young adult body. Everyone goes through it at their own pace — starting earlier or later is completely normal. Hormones (chemical messengers) trigger all the changes.",
                "is_boss": False,
                "flavor": "A timeline stretches across the page, showing a child gradually growing into a young adult. Puck smiles warmly.",
            },
            {
                "id": "unique_body",
                "title": "One of a Kind",
                "type": "quiz",
                "question": "Why do people grow to different heights and body shapes?",
                "options": [
                    "Everyone is supposed to be exactly the same height",
                    "Only the food you eat determines your height",
                    "A combination of your genes (from your parents), nutrition, sleep, and exercise",
                    "It's completely random with no pattern at all",
                ],
                "answer": "c",
                "hints": [
                    "Your genes (the instructions you inherit from your parents) play a big role.",
                    "But good nutrition, sleep, and exercise also help you grow to your full potential!",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Your height and body shape come from a mix of genetics (traits inherited from your parents) and lifestyle (nutrition, sleep, exercise). Everyone's body is different, and that's a wonderful thing. There is no 'right' body shape — every healthy body is a good body!",
                "is_boss": True,
                "flavor": "Children of all different heights and shapes appear on the page, each one glowing. Puck beams: 'Every single one of you is amazing.'",
            },
        ],
    },
}
