"""
zones.py — Weather & Time zones and challenges.

Teaches Chinese weather vocabulary, seasons, telling time,
days and months, and making plans. Guided by Long Long the dragon.
"""

ZONE_ORDER = [
    "weather_words",
    "seasons",
    "telling_time",
    "days_months",
    "making_plans",
]

ZONES = {
    # ── Zone 1: Weather Words ────────────────────────────────────────
    "weather_words": {
        "id": "weather_words",
        "name": "Weather Words",
        "description": "Essential weather vocabulary in Chinese",
        "level_required": 1,
        "challenges": [
            {
                "id": "tianqi_weather",
                "title": "What's the Weather?",
                "type": "quiz",
                "question": "What does 'tian qi' (天气) mean?",
                "options": ["Temperature", "Weather", "Sky", "Air"],
                "answer": "b",
                "hints": [
                    "tian (天) means 'sky/day' and qi (气) means 'air/energy'.",
                    "Together they describe what's happening in the sky.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "天气 (tian qi) means 'weather'. 天 (tian) = sky/heaven and 气 (qi) = air/energy. To ask about weather: 天气怎么样? (tian qi zen me yang?) = 'How's the weather?' This is one of the most common daily conversation starters in Chinese.",
                "is_boss": False,
                "flavor": "Long Long peers up at the clouds. 'Tian qi -- the mood of the heavens!'",
            },
            {
                "id": "re_hot",
                "title": "The Heat of Summer",
                "type": "quiz",
                "question": "How do you say 'hot' in Chinese?",
                "options": ["leng (冷)", "re (热)", "nuan (暖)", "liang (凉)"],
                "answer": "b",
                "hints": [
                    "This word has a fourth tone and sounds like 'ruh'.",
                    "Think of the heat radiating from a dragon's breath.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "热 (re, fourth tone) means 'hot'. 今天很热 (jin tian hen re) = 'Today is very hot.' The character 热 has four dots at the bottom representing fire (灬). hen (很) = 'very' is almost always used with adjectives in Chinese.",
                "is_boss": False,
                "flavor": "Long Long fans himself with a wing. 'Tai re le! It's too hot!'",
            },
            {
                "id": "leng_cold",
                "title": "The Chill of Winter",
                "type": "quiz",
                "question": "What does 'leng' (冷) mean?",
                "options": ["Hot", "Warm", "Cold", "Cool"],
                "answer": "c",
                "hints": [
                    "This is the opposite of re (热).",
                    "The ice radical (冫) on the left side is a clue.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "冷 (leng, third tone) means 'cold'. The character has the ice radical (冫) on the left. 今天很冷 (jin tian hen leng) = 'Today is very cold.' 冷水 (leng shui) = cold water. Notice that re and leng are opposites, just like hot and cold.",
                "is_boss": False,
                "flavor": "Long Long shivers and breathes a warm cloud. 'Leng! Even dragons feel the cold!'",
            },
            {
                "id": "xia_yu_rain",
                "title": "The Falling Rain",
                "type": "quiz",
                "question": "What does 'xia yu' (下雨) mean?",
                "options": ["It's snowing", "It's raining", "It's windy", "It's cloudy"],
                "answer": "b",
                "hints": [
                    "xia (下) means 'to fall/down' and yu (雨) means 'rain'.",
                    "Look at the character 雨 -- it looks like rain falling from a cloud.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "下雨 (xia yu) means 'to rain' (literally 'falling rain'). 雨 (yu) = rain -- the character pictures raindrops falling from a cloud. 今天下雨了 (jin tian xia yu le) = 'It's raining today.' 雨伞 (yu san) = umbrella (rain umbrella).",
                "is_boss": False,
                "flavor": "Long Long opens a wing like an umbrella. 'Xia yu le! Quick, find shelter!'",
            },
            {
                "id": "xia_xue_snow",
                "title": "The First Snow",
                "type": "quiz",
                "question": "How do you say 'to snow' in Chinese?",
                "options": ["xia yu (下雨)", "xia xue (下雪)", "xia bing (下冰)", "xia shuang (下霜)"],
                "answer": "b",
                "hints": [
                    "xia means 'to fall' -- what falls in winter?",
                    "xue (雪) has the rain radical on top.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "下雪 (xia xue) means 'to snow' (literally 'falling snow'). 雪 (xue, third tone) = snow. Notice the pattern: 下雨 (raining), 下雪 (snowing) -- both use 下 (xia, to fall). 雪人 (xue ren) = snowman (snow person). 雪花 (xue hua) = snowflake (snow flower).",
                "is_boss": False,
                "flavor": "Long Long catches snowflakes on his tongue. 'Xia xue le! Beautiful!'",
            },
            {
                "id": "qing_tian_sunny",
                "title": "Clear Skies",
                "type": "quiz",
                "question": "What does 'qing tian' (晴天) mean?",
                "options": ["Rainy day", "Cloudy day", "Sunny day", "Snowy day"],
                "answer": "c",
                "hints": [
                    "qing (晴) has the sun radical (日) on the left.",
                    "tian (天) means 'day/sky'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "晴天 (qing tian) means 'sunny day / clear day'. 晴 (qing) = clear/sunny -- notice the sun radical 日 on the left. 今天是晴天 (jin tian shi qing tian) = 'Today is a sunny day.' The opposite is 阴天 (yin tian) = cloudy/overcast day.",
                "is_boss": False,
                "flavor": "Long Long basks in the sunlight. 'Qing tian! A perfect day to fly!'",
            },
            {
                "id": "weather_text_review",
                "title": "Weather Recall",
                "type": "text",
                "question": "Type the pinyin for 'weather' (two syllables, no tones):",
                "options": [],
                "answer": "tian qi",
                "hints": [
                    "The first word means 'sky' or 'heaven'.",
                    "The second word means 'air' or 'energy'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "天气 (tian qi) = weather. Remember the key weather words: tian qi (天气) weather, re (热) hot, leng (冷) cold, xia yu (下雨) raining, xia xue (下雪) snowing, qing tian (晴天) sunny day.",
                "is_boss": False,
                "flavor": "Long Long nods approvingly. 'You remember the voice of the sky!'",
            },
            {
                "id": "weather_boss",
                "title": "Weather Master",
                "type": "quiz",
                "question": "How would you say 'Today is very cold' in Chinese?",
                "options": [
                    "jin tian hen re (今天很热)",
                    "jin tian hen leng (今天很冷)",
                    "jin tian xia yu (今天下雨)",
                    "jin tian qing tian (今天晴天)",
                ],
                "answer": "b",
                "hints": [
                    "jin tian = today, hen = very, and what's the word for cold?",
                    "leng (冷) means cold.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "今天很冷 (jin tian hen leng) = 'Today is very cold.' Pattern: 今天 (today) + 很 (very) + adjective. You can swap the adjective: 今天很热 (very hot), 今天很冷 (very cold). For weather events: 今天下雨了 (it's raining today).",
                "is_boss": True,
                "flavor": "Long Long roars with pride. 'You command the language of the skies!'",
            },
        ],
    },

    # ── Zone 2: Seasons ──────────────────────────────────────────────
    "seasons": {
        "id": "seasons",
        "name": "Seasons",
        "description": "The four seasons and seasonal vocabulary",
        "level_required": 3,
        "challenges": [
            {
                "id": "chun_spring",
                "title": "The Awakening Season",
                "type": "quiz",
                "question": "What does 'chun tian' (春天) mean?",
                "options": ["Summer", "Autumn", "Winter", "Spring"],
                "answer": "d",
                "hints": [
                    "chun (春) is the season when flowers bloom.",
                    "The Spring Festival (春节) is Chinese New Year.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "春天 (chun tian) means 'spring'. 春 (chun, first tone) = spring. Adding 天 (tian) makes it 'spring season/days'. 春节 (Chun Jie) = Spring Festival (Chinese New Year) -- the most important holiday in China. 春天来了 (chun tian lai le) = Spring has come!",
                "is_boss": False,
                "flavor": "Long Long smells cherry blossoms on the wind. 'Chun tian -- the world wakes up!'",
            },
            {
                "id": "xia_summer",
                "title": "The Blazing Season",
                "type": "quiz",
                "question": "How do you say 'summer' in Chinese?",
                "options": ["chun tian (春天)", "xia tian (夏天)", "qiu tian (秋天)", "dong tian (冬天)"],
                "answer": "b",
                "hints": [
                    "This season is when it's re (热).",
                    "xia (夏) is also used in the name for the Xia Dynasty.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "夏天 (xia tian) means 'summer'. 夏 (xia, fourth tone) = summer. 夏天很热 (xia tian hen re) = 'Summer is very hot.' Chinese summers, especially in cities like Wuhan, Chongqing, and Nanjing (the 'three furnaces'), are famously scorching.",
                "is_boss": False,
                "flavor": "Long Long wipes sweat from his brow. 'Xia tian -- even dragons seek shade!'",
            },
            {
                "id": "qiu_autumn",
                "title": "The Golden Season",
                "type": "quiz",
                "question": "What season is 'qiu tian' (秋天)?",
                "options": ["Spring", "Summer", "Autumn", "Winter"],
                "answer": "c",
                "hints": [
                    "This is the harvest season, when leaves turn golden.",
                    "The Mid-Autumn Festival (中秋节) happens in this season.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "秋天 (qiu tian) means 'autumn/fall'. 秋 (qiu, first tone) = autumn. The character 秋 combines 禾 (grain) and 火 (fire) -- grain drying in autumn heat. 中秋节 (Zhong Qiu Jie) = Mid-Autumn Festival, when families gather to eat mooncakes and admire the moon.",
                "is_boss": False,
                "flavor": "Long Long watches golden leaves swirl. 'Qiu tian -- the world turns to gold!'",
            },
            {
                "id": "dong_winter",
                "title": "The Sleeping Season",
                "type": "quiz",
                "question": "What does 'dong tian' (冬天) mean?",
                "options": ["Winter", "Summer", "Spring", "Autumn"],
                "answer": "a",
                "hints": [
                    "This is when it's leng (冷) and might xia xue (下雪).",
                    "dong (冬) has the ice radical dots at the bottom.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "冬天 (dong tian) means 'winter'. 冬 (dong, first tone) = winter. 冬天很冷 (dong tian hen leng) = 'Winter is very cold.' 冬至 (Dong Zhi) = Winter Solstice, a traditional festival when families eat dumplings in the north and tangyuan in the south.",
                "is_boss": False,
                "flavor": "Long Long curls around a warm hearth. 'Dong tian -- time for hot soup and stories!'",
            },
            {
                "id": "season_weather_link",
                "title": "Seasons and Weather",
                "type": "quiz",
                "question": "Which sentence means 'Spring is very warm'?",
                "options": [
                    "chun tian hen re (春天很热)",
                    "chun tian hen nuan huo (春天很暖和)",
                    "chun tian hen leng (春天很冷)",
                    "chun tian xia xue (春天下雪)",
                ],
                "answer": "b",
                "hints": [
                    "nuan huo (暖和) means 'warm' -- not as hot as re.",
                    "Spring is the warm season, not hot, cold, or snowy.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "春天很暖和 (chun tian hen nuan huo) = 'Spring is very warm.' nuan huo (暖和) means 'warm' -- gentler than re (热, hot). Weather-season pairings: 春天暖和 (spring is warm), 夏天热 (summer is hot), 秋天凉快 (autumn is cool), 冬天冷 (winter is cold).",
                "is_boss": False,
                "flavor": "Long Long feels the gentle spring breeze. 'Nuan huo -- just right for flying!'",
            },
            {
                "id": "season_text_spring",
                "title": "Spring Recall",
                "type": "text",
                "question": "Type the pinyin for 'spring' (two syllables, no tones):",
                "options": [],
                "answer": "chun tian",
                "hints": [
                    "The first syllable is the season itself.",
                    "The second syllable means 'day' or 'sky'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "春天 (chun tian) = spring. The four seasons pattern: chun tian (春天) spring, xia tian (夏天) summer, qiu tian (秋天) autumn, dong tian (冬天) winter. All use tian (天) as the second character.",
                "is_boss": False,
                "flavor": "Long Long smiles. 'The season of new beginnings!'",
            },
            {
                "id": "season_text_winter",
                "title": "Winter Recall",
                "type": "text",
                "question": "Type the pinyin for 'winter' (two syllables, no tones):",
                "options": [],
                "answer": "dong tian",
                "hints": [
                    "The first syllable starts with 'd'.",
                    "It rhymes with 'gong'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "冬天 (dong tian) = winter. Quick season review: chun (春) spring, xia (夏) summer, qiu (秋) autumn, dong (冬) winter. Each pairs with tian (天) for the full season name.",
                "is_boss": False,
                "flavor": "Long Long breathes frost. 'The season of rest and reflection!'",
            },
            {
                "id": "seasons_boss",
                "title": "Season Commander",
                "type": "quiz",
                "question": "Put the seasons in order starting from spring: chun, ___, qiu, ___",
                "options": [
                    "xia, dong",
                    "dong, xia",
                    "qiu, xia",
                    "dong, qiu",
                ],
                "answer": "a",
                "hints": [
                    "Spring, summer, autumn, winter -- the natural order.",
                    "xia (夏) = summer comes after spring, dong (冬) = winter comes after autumn.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "The four seasons in order: 春 (chun) spring, 夏 (xia) summer, 秋 (qiu) autumn, 冬 (dong) winter. This order follows the natural cycle. In Chinese poetry, seasons are deeply symbolic: spring = hope, summer = passion, autumn = melancholy, winter = endurance.",
                "is_boss": True,
                "flavor": "Long Long roars across all four winds. 'You command the cycle of the year!'",
            },
        ],
    },

    # ── Zone 3: Telling Time ─────────────────────────────────────────
    "telling_time": {
        "id": "telling_time",
        "name": "Telling Time",
        "description": "Hours, minutes, and asking the time in Chinese",
        "level_required": 5,
        "challenges": [
            {
                "id": "ji_dian_what_time",
                "title": "What Time Is It?",
                "type": "quiz",
                "question": "How do you ask 'What time is it?' in Chinese?",
                "options": [
                    "ji dian le? (几点了?)",
                    "shen me shi hou? (什么时候?)",
                    "duo shao qian? (多少钱?)",
                    "zen me yang? (怎么样?)",
                ],
                "answer": "a",
                "hints": [
                    "ji (几) means 'how many' and dian (点) means 'o'clock'.",
                    "le (了) at the end indicates the current moment.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "几点了? (ji dian le?) = 'What time is it?' ji (几) = how many, dian (点) = o'clock/point. 现在几点? (xian zai ji dian?) = 'What time is it now?' To answer: 现在三点 (xian zai san dian) = 'It's three o'clock now.'",
                "is_boss": False,
                "flavor": "Long Long taps the sundial. 'Ji dian le? A dragon must keep his schedule!'",
            },
            {
                "id": "xiao_shi_hour",
                "title": "Counting Hours",
                "type": "quiz",
                "question": "What does 'xiao shi' (小时) mean?",
                "options": ["Minute", "Second", "Hour", "Day"],
                "answer": "c",
                "hints": [
                    "xiao (小) means 'small' and shi (时) means 'time'.",
                    "One xiao shi is 60 minutes.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "小时 (xiao shi) means 'hour'. Literally 'small time'. 一个小时 (yi ge xiao shi) = one hour. 两个小时 (liang ge xiao shi) = two hours. Note: use 两 (liang) instead of 二 (er) before measure words. 半个小时 (ban ge xiao shi) = half an hour.",
                "is_boss": False,
                "flavor": "Long Long watches the shadow of the sundial move. 'Yi ge xiao shi -- gone in a flash!'",
            },
            {
                "id": "fen_zhong_minute",
                "title": "Every Minute Counts",
                "type": "quiz",
                "question": "How do you say 'minute' in Chinese?",
                "options": ["xiao shi (小时)", "fen zhong (分钟)", "miao (秒)", "tian (天)"],
                "answer": "b",
                "hints": [
                    "fen (分) means 'divide/part' and zhong (钟) means 'clock'.",
                    "There are 60 of these in an hour.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "分钟 (fen zhong) means 'minute'. fen (分) = divide/minute, zhong (钟) = clock. When telling time, you can just say fen: 三点十五分 (san dian shi wu fen) = 3:15. 五分钟 (wu fen zhong) = five minutes.",
                "is_boss": False,
                "flavor": "Long Long counts sand grains in an hourglass. 'Fen zhong -- treasure each one!'",
            },
            {
                "id": "telling_three_oclock",
                "title": "On the Hour",
                "type": "quiz",
                "question": "How do you say 'three o'clock' in Chinese?",
                "options": ["san shi (三时)", "san dian (三点)", "san ge (三个)", "di san (第三)"],
                "answer": "b",
                "hints": [
                    "dian (点) is the word for o'clock.",
                    "Just put the number before dian.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "三点 (san dian) = three o'clock. The pattern is simple: number + 点 (dian). 一点 (yi dian) = 1:00, 五点 (wu dian) = 5:00, 十二点 (shi er dian) = 12:00. For half past: 三点半 (san dian ban) = 3:30. ban (半) = half.",
                "is_boss": False,
                "flavor": "Long Long adjusts the castle clock. 'San dian! Time for afternoon tea!'",
            },
            {
                "id": "time_with_minutes",
                "title": "Minutes Past",
                "type": "quiz",
                "question": "How do you say '7:15' in Chinese?",
                "options": [
                    "qi dian yi ke (七点一刻)",
                    "qi dian shi wu (七点十五)",
                    "qi dian ban (七点半)",
                    "Both A and B are correct",
                ],
                "answer": "d",
                "hints": [
                    "yi ke (一刻) means 'a quarter' and shi wu (十五) means '15'.",
                    "Chinese has two ways to say quarter past.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "7:15 can be said two ways: 七点十五分 (qi dian shi wu fen) or 七点一刻 (qi dian yi ke). ke (刻) = quarter hour. Three common time phrases: 一刻 (yi ke) = quarter past, 半 (ban) = half past, 三刻 (san ke) = quarter to.",
                "is_boss": False,
                "flavor": "Long Long grins. 'Two ways to say it -- both correct!'",
            },
            {
                "id": "time_text_ask",
                "title": "Ask the Time",
                "type": "text",
                "question": "Type the pinyin for 'What time is it?' (three syllables: ji ___ ___?):",
                "options": [],
                "answer": "ji dian le",
                "hints": [
                    "ji means 'how many', then the word for o'clock, then le.",
                    "dian = o'clock, le = indicates current state.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "几点了 (ji dian le) = What time is it? This is the most natural way to ask time in daily conversation. More formal: 现在几点? (xian zai ji dian?) = What time is it now?",
                "is_boss": False,
                "flavor": "Long Long nods. 'Now you can ask anyone the time!'",
            },
            {
                "id": "time_text_hour",
                "title": "Hour Recall",
                "type": "text",
                "question": "Type the pinyin for 'hour' (two syllables, no tones):",
                "options": [],
                "answer": "xiao shi",
                "hints": [
                    "Literally 'small time'.",
                    "xiao means 'small'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "小时 (xiao shi) = hour. Time units: 小时 (xiao shi) hour, 分钟 (fen zhong) minute, 秒 (miao) second. 一个小时 = one hour, 三十分钟 = thirty minutes.",
                "is_boss": False,
                "flavor": "Long Long marks another hour on the sundial. 'Well recalled!'",
            },
            {
                "id": "telling_time_boss",
                "title": "Time Lord",
                "type": "quiz",
                "question": "Which is the correct way to say '9:30' in Chinese?",
                "options": [
                    "jiu dian ban (九点半)",
                    "jiu dian san shi (九点三十)",
                    "jiu ban dian (九半点)",
                    "Both A and B are correct",
                ],
                "answer": "d",
                "hints": [
                    "ban (半) = half, san shi (三十) = thirty.",
                    "Both 'half past' and 'thirty minutes' work in Chinese.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "9:30 = 九点半 (jiu dian ban) or 九点三十分 (jiu dian san shi fen). Both are correct! ban (半) after dian (点) always means :30. Pattern: number + 点 + 半/minutes + 分. You now have full command of telling time in Chinese!",
                "is_boss": True,
                "flavor": "Long Long strikes the great bell. 'You are master of time itself!'",
            },
        ],
    },

    # ── Zone 4: Days & Months ────────────────────────────────────────
    "days_months": {
        "id": "days_months",
        "name": "Days & Months",
        "description": "Days of the week, months, and years in Chinese",
        "level_required": 7,
        "challenges": [
            {
                "id": "xing_qi_week",
                "title": "The Weekly Cycle",
                "type": "quiz",
                "question": "What does 'xing qi' (星期) mean?",
                "options": ["Month", "Year", "Week", "Day"],
                "answer": "c",
                "hints": [
                    "xing (星) means 'star' and qi (期) means 'period'.",
                    "There are seven days in a xing qi.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "星期 (xing qi) means 'week'. Days of the week use xing qi + number: 星期一 (xing qi yi) = Monday (week-one), 星期二 = Tuesday, ... 星期六 = Saturday. Sunday is special: 星期天 (xing qi tian) or 星期日 (xing qi ri). zhou (周) is also used: 周一, 周二, etc.",
                "is_boss": False,
                "flavor": "Long Long unfurls a scroll calendar. 'Xing qi -- the rhythm of our days!'",
            },
            {
                "id": "xing_qi_yi_monday",
                "title": "The First Day",
                "type": "quiz",
                "question": "How do you say 'Monday' in Chinese?",
                "options": [
                    "xing qi tian (星期天)",
                    "xing qi yi (星期一)",
                    "xing qi er (星期二)",
                    "xing qi liu (星期六)",
                ],
                "answer": "b",
                "hints": [
                    "yi (一) means 'one' -- the first day of the work week.",
                    "xing qi + the number of the day.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "星期一 (xing qi yi) = Monday. The system is beautifully logical: Monday = week-1, Tuesday = week-2, Wednesday = week-3, Thursday = week-4, Friday = week-5, Saturday = week-6. Only Sunday breaks the pattern: 星期天 or 星期日.",
                "is_boss": False,
                "flavor": "Long Long ticks off the first day. 'Xing qi yi -- a fresh start!'",
            },
            {
                "id": "yue_month",
                "title": "The Twelve Months",
                "type": "quiz",
                "question": "How do you say 'January' in Chinese?",
                "options": [
                    "yi yue (一月)",
                    "yi tian (一天)",
                    "yi nian (一年)",
                    "yi zhou (一周)",
                ],
                "answer": "a",
                "hints": [
                    "yue (月) means 'month' and also 'moon'.",
                    "January is simply 'month one'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "一月 (yi yue) = January. Months are just number + 月 (yue, month/moon): 一月 January, 二月 February, ... 十二月 December. The character 月 originally pictured the crescent moon -- months follow the lunar cycle. 这个月 (zhe ge yue) = this month.",
                "is_boss": False,
                "flavor": "Long Long gazes at the moon. 'Yi yue -- the first moon of the year!'",
            },
            {
                "id": "nian_year",
                "title": "The Passing Year",
                "type": "quiz",
                "question": "What does 'nian' (年) mean?",
                "options": ["Day", "Week", "Month", "Year"],
                "answer": "d",
                "hints": [
                    "The Nian monster comes once every... what?",
                    "jin nian (今年) means 'this year'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "年 (nian, second tone) = year. 今年 (jin nian) = this year, 去年 (qu nian) = last year, 明年 (ming nian) = next year. Fun fact: the character 年 comes from the legend of the Nian monster that appears once a year -- people scare it away with firecrackers and red decorations!",
                "is_boss": False,
                "flavor": "Long Long recalls ancient tales. 'Nian -- each year brings new adventures!'",
            },
            {
                "id": "jin_tian_today",
                "title": "Today, Yesterday, Tomorrow",
                "type": "quiz",
                "question": "Match the words: jin tian (今天), zuo tian (昨天), ming tian (明天). Which is 'yesterday'?",
                "options": ["jin tian (今天)", "zuo tian (昨天)", "ming tian (明天)", "hou tian (后天)"],
                "answer": "b",
                "hints": [
                    "zuo (昨) specifically refers to the past.",
                    "jin = now/present, zuo = past/yesterday, ming = bright/tomorrow.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "昨天 (zuo tian) = yesterday. The time words: 前天 (qian tian) day before yesterday, 昨天 (zuo tian) yesterday, 今天 (jin tian) today, 明天 (ming tian) tomorrow, 后天 (hou tian) day after tomorrow. Chinese has single words for 'day before yesterday' and 'day after tomorrow'!",
                "is_boss": False,
                "flavor": "Long Long traces a timeline in the dust. 'Zuo tian is behind us, ming tian awaits!'",
            },
            {
                "id": "days_text_sunday",
                "title": "Sunday Recall",
                "type": "text",
                "question": "Type the pinyin for 'Sunday' using tian (three syllables, no tones):",
                "options": [],
                "answer": "xing qi tian",
                "hints": [
                    "xing qi = week, then the special word for Sunday.",
                    "Sunday uses tian (天) instead of a number.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "星期天 (xing qi tian) = Sunday. Remember: Monday through Saturday use numbers (yi through liu), but Sunday uses tian (天) or ri (日) instead. 星期天 is more colloquial, 星期日 is more formal.",
                "is_boss": False,
                "flavor": "Long Long stretches lazily. 'Xing qi tian -- a day of rest!'",
            },
            {
                "id": "days_text_month",
                "title": "Month Recall",
                "type": "text",
                "question": "Type the pinyin for 'March' (two syllables, no tones):",
                "options": [],
                "answer": "san yue",
                "hints": [
                    "san (三) means three, and which word means month?",
                    "yue (月) means month.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "三月 (san yue) = March. All twelve months follow this pattern: number + 月. 三月 is the third month. This is much simpler than English, where every month has a unique name!",
                "is_boss": False,
                "flavor": "Long Long nods. 'San yue -- when spring truly arrives!'",
            },
            {
                "id": "days_months_boss",
                "title": "Calendar Commander",
                "type": "quiz",
                "question": "How would you say 'next Wednesday' in Chinese?",
                "options": [
                    "xia ge xing qi san (下个星期三)",
                    "ming tian xing qi san (明天星期三)",
                    "shang ge xing qi san (上个星期三)",
                    "zhe ge xing qi san (这个星期三)",
                ],
                "answer": "a",
                "hints": [
                    "xia ge (下个) means 'next' for time periods.",
                    "Wednesday = xing qi san (week-three).",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "下个星期三 (xia ge xing qi san) = next Wednesday. Pattern: 上个 (shang ge) = last, 这个 (zhe ge) = this, 下个 (xia ge) = next. Works for weeks, months, and years: 下个月 (xia ge yue) = next month, 下个星期 (xia ge xing qi) = next week.",
                "is_boss": True,
                "flavor": "Long Long stamps the royal calendar. 'You command the days and months!'",
            },
        ],
    },

    # ── Zone 5: Making Plans ─────────────────────────────────────────
    "making_plans": {
        "id": "making_plans",
        "name": "Making Plans",
        "description": "Combine weather and time to make plans in Chinese",
        "level_required": 9,
        "challenges": [
            {
                "id": "ming_tian_tomorrow",
                "title": "Looking Ahead",
                "type": "quiz",
                "question": "What does 'ming tian' (明天) mean?",
                "options": ["Yesterday", "Today", "Tomorrow", "Next week"],
                "answer": "c",
                "hints": [
                    "ming (明) means 'bright' -- the bright day ahead.",
                    "The opposite of zuo tian (昨天, yesterday).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "明天 (ming tian) = tomorrow. ming (明) combines sun (日) and moon (月) = 'bright'. The bright day ahead is tomorrow! 明天见 (ming tian jian) = 'See you tomorrow!' -- a very common parting phrase in Chinese.",
                "is_boss": False,
                "flavor": "Long Long points toward the sunrise. 'Ming tian -- a bright day awaits!'",
            },
            {
                "id": "hou_tian_day_after",
                "title": "The Day Beyond",
                "type": "quiz",
                "question": "What does 'hou tian' (后天) mean?",
                "options": ["Yesterday", "The day before yesterday", "Tomorrow", "The day after tomorrow"],
                "answer": "d",
                "hints": [
                    "hou (后) means 'after/behind' in time.",
                    "If ming tian is tomorrow, hou tian is one day further.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "后天 (hou tian) = the day after tomorrow. Chinese has a single word for this! Time sequence: 前天 (qian tian) = day before yesterday, 昨天 (zuo tian) = yesterday, 今天 (jin tian) = today, 明天 (ming tian) = tomorrow, 后天 (hou tian) = day after tomorrow.",
                "is_boss": False,
                "flavor": "Long Long looks past the horizon. 'Hou tian -- planning ahead like a wise dragon!'",
            },
            {
                "id": "zhou_mo_weekend",
                "title": "The Weekend",
                "type": "quiz",
                "question": "How do you say 'weekend' in Chinese?",
                "options": ["xing qi (星期)", "zhou mo (周末)", "jia qi (假期)", "xiu xi (休息)"],
                "answer": "b",
                "hints": [
                    "zhou (周) means 'week' and mo (末) means 'end'.",
                    "Literally: the end of the week.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "周末 (zhou mo) = weekend. zhou (周) = week, mo (末) = end. 这个周末 (zhe ge zhou mo) = this weekend. 周末你做什么? (zhou mo ni zuo shen me?) = 'What are you doing this weekend?' -- a great conversation starter!",
                "is_boss": False,
                "flavor": "Long Long grins. 'Zhou mo -- every dragon's favorite time!'",
            },
            {
                "id": "weather_plan_rain",
                "title": "Rain Check",
                "type": "quiz",
                "question": "What does 'ming tian xia yu, wo men bu qu' (明天下雨，我们不去) mean?",
                "options": [
                    "Tomorrow is sunny, we will go",
                    "Tomorrow it rains, we won't go",
                    "Yesterday it rained, we didn't go",
                    "Today is rainy, let's go",
                ],
                "answer": "b",
                "hints": [
                    "ming tian = tomorrow, xia yu = rain, bu = not, qu = go.",
                    "wo men = we, bu qu = won't go.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "明天下雨，我们不去 = 'Tomorrow it rains, we won't go.' Breaking it down: 明天 (tomorrow) + 下雨 (rain), 我们 (we) + 不 (not) + 去 (go). In Chinese, weather conditions can be stated as fact without 'if' -- context makes the conditional meaning clear.",
                "is_boss": False,
                "flavor": "Long Long folds his wings. 'No flying in the rain -- smart planning!'",
            },
            {
                "id": "weather_plan_sunny",
                "title": "Good Weather Plans",
                "type": "quiz",
                "question": "How would you say 'If tomorrow is sunny, let's go to the park'?",
                "options": [
                    "ming tian qing tian, wo men qu gong yuan ba (明天晴天，我们去公园吧)",
                    "ming tian xia yu, wo men qu gong yuan (明天下雨，我们去公园)",
                    "jin tian qing tian, wo men bu qu (今天晴天，我们不去)",
                    "zuo tian qing tian, wo men qu le (昨天晴天，我们去了)",
                ],
                "answer": "a",
                "hints": [
                    "qing tian = sunny, gong yuan = park, ba = suggestion particle.",
                    "ming tian = tomorrow, wo men = we, qu = go.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "明天晴天，我们去公园吧 = 'If tomorrow is sunny, let's go to the park.' ba (吧) at the end makes it a suggestion. gong yuan (公园) = park. This pattern -- time + weather + plan -- is how Chinese speakers naturally make weather-dependent plans.",
                "is_boss": False,
                "flavor": "Long Long claps his claws. 'Now you're planning like a local!'",
            },
            {
                "id": "plans_text_tomorrow",
                "title": "Tomorrow Recall",
                "type": "text",
                "question": "Type the pinyin for 'tomorrow' (two syllables, no tones):",
                "options": [],
                "answer": "ming tian",
                "hints": [
                    "The first syllable means 'bright'.",
                    "The second syllable means 'day'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "明天 (ming tian) = tomorrow. Remember the time words: 今天 (jin tian) today, 明天 (ming tian) tomorrow, 后天 (hou tian) day after tomorrow. ming (明) = bright -- tomorrow is the bright day ahead!",
                "is_boss": False,
                "flavor": "Long Long smiles warmly. 'The bright day ahead!'",
            },
            {
                "id": "plans_text_weekend",
                "title": "Weekend Recall",
                "type": "text",
                "question": "Type the pinyin for 'weekend' (two syllables, no tones):",
                "options": [],
                "answer": "zhou mo",
                "hints": [
                    "The first syllable means 'week'.",
                    "The second syllable means 'end'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "周末 (zhou mo) = weekend. zhou (周) week + mo (末) end. You can now make plans: 这个周末我们去哪里? (zhe ge zhou mo wo men qu na li?) = Where shall we go this weekend?",
                "is_boss": False,
                "flavor": "Long Long stretches his wings. 'Zhou mo -- time for adventure!'",
            },
            {
                "id": "making_plans_boss",
                "title": "Master Planner",
                "type": "quiz",
                "question": "Which sentence correctly says 'This weekend if it doesn't rain, let's go hiking'?",
                "options": [
                    "zhe ge zhou mo bu xia yu, wo men qu pa shan ba (这个周末不下雨，我们去爬山吧)",
                    "ming tian xia yu, wo men qu pa shan (明天下雨，我们去爬山)",
                    "zhou mo xia yu le, wo men bu qu (周末下雨了，我们不去)",
                    "jin tian bu xia yu, wo men qu pa shan le (今天不下雨，我们去爬山了)",
                ],
                "answer": "a",
                "hints": [
                    "zhe ge zhou mo = this weekend, bu xia yu = doesn't rain.",
                    "pa shan (爬山) = hike/climb mountain, ba (吧) = suggestion.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "这个周末不下雨，我们去爬山吧 = 'This weekend if it doesn't rain, let's go hiking.' You combined: time (这个周末) + weather condition (不下雨) + plan (去爬山) + suggestion (吧). pa shan (爬山) = climb mountain / go hiking. You've mastered weather-based planning in Chinese!",
                "is_boss": True,
                "flavor": "Long Long roars triumphantly! 'You weave time, weather, and plans like a true sage!'",
            },
        ],
    },
}
