"""
zones.py — Economics zones and challenges for The Market Square skill pack.

All challenges use "type": "quiz" or "type": "text".
Designed for ages 7-10, guided warmly by Puck.
"""

ZONE_ORDER = [
    "wants_vs_needs",
    "supply_and_demand",
    "jobs_and_careers",
    "saving_and_budgeting",
    "trading_and_global",
]

ZONES = {
    "wants_vs_needs": {
        "id": "wants_vs_needs",
        "name": "Wants vs Needs",
        "description": "Learn the difference between things you need and things you want",
        "level_required": 1,
        "challenges": [
            {
                "id": "wn_what_is_need",
                "title": "What Is a Need?",
                "type": "quiz",
                "question": "Which of these is something you truly NEED to survive?",
                "options": [
                    "A video game",
                    "Clean drinking water",
                    "A brand-new bicycle",
                    "A bag of candy",
                ],
                "answer": "b",
                "hints": [
                    "Think about what your body can't live without.",
                    "You could go weeks without the other three, but not without this one!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A need is something you must have to survive — like food, water, shelter, and clothing. Without these basics, life would be very difficult or even dangerous. Everything else is a want!",
                "is_boss": False,
                "flavor": "Puck holds up a glass of sparkling water. 'This little glass keeps you alive. Never underestimate the basics!'",
            },
            {
                "id": "wn_what_is_want",
                "title": "What Is a Want?",
                "type": "quiz",
                "question": "Which of these is a WANT and not a need?",
                "options": [
                    "A warm winter coat when it's snowing",
                    "A meal when you're hungry",
                    "The latest toy from a TV commercial",
                    "A safe place to sleep",
                ],
                "answer": "c",
                "hints": [
                    "Three of these keep you safe, warm, or fed. One is just for fun.",
                    "Commercials are designed to make you WANT things!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A want is something nice to have but not necessary for survival. Toys, games, fancy clothes, and treats are all wants. There's nothing wrong with wants — but smart people take care of their needs first!",
                "is_boss": False,
                "flavor": "Puck flips through a toy catalog, eyes wide, then catches himself. 'Wants are fun — but needs come first!'",
            },
            {
                "id": "wn_tricky_or_not",
                "title": "Tricky Decisions",
                "type": "quiz",
                "question": "A family has $50 left for the week. Their fridge is almost empty, and their child wants a new toy that costs $40. What should they do?",
                "options": [
                    "Buy the toy — the child really wants it",
                    "Buy groceries first — food is a need",
                    "Buy half a toy and half groceries",
                    "Don't spend anything at all",
                ],
                "answer": "b",
                "hints": [
                    "When money is tight, which comes first — needs or wants?",
                    "An empty fridge means the family needs food to eat this week.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When you have limited money, needs must come first. Groceries keep the family fed and healthy. The toy is a want — it can wait until there's extra money. Making this choice is called prioritizing, and it's one of the most important life skills!",
                "is_boss": False,
                "flavor": "Puck puts a basket of food on one side of a scale and a toy on the other. The food side sinks down. 'Needs are heavier — they matter more!'",
            },
            {
                "id": "wn_luxury_or_necessity",
                "title": "Luxury or Necessity?",
                "type": "text",
                "question": "A family needs a way to get to work and school. They could buy a basic used car for $5,000 or a fancy sports car for $80,000. Which is the smarter choice and why? Type your answer.",
                "options": [],
                "answer": "used car because it meets the need without wasting money",
                "hints": [
                    "Both cars can drive you to work and school. What's the difference?",
                    "A need can be met simply. Spending more than necessary turns a need into a luxury.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Transportation can be a need, but HOW you meet that need matters. A basic car gets you where you need to go. A sports car adds luxury on top. Smart decision-makers meet their needs affordably and save the rest!",
                "is_boss": False,
                "flavor": "Puck drives a tiny cardboard car across the page. 'It's not fancy, but it gets me there!'",
            },
            {
                "id": "wn_changing_needs",
                "title": "Needs Can Change",
                "type": "quiz",
                "question": "In summer you don't need a heavy coat. In winter you do. What does this teach us about needs?",
                "options": [
                    "Needs never change",
                    "Needs can change depending on the situation",
                    "Winter coats are always wants",
                    "You should buy everything just in case",
                ],
                "answer": "b",
                "hints": [
                    "Think about how the seasons change what you truly require.",
                    "Something that's a want in July might become a need in January!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Needs aren't fixed — they change with the season, your age, where you live, and your situation. A winter coat is a need in Alaska but a want in Hawaii. Smart thinkers consider context when deciding what they truly need!",
                "is_boss": False,
                "flavor": "Puck shivers in a snowstorm, then snaps his fingers and a warm coat appears. 'Context matters!'",
            },
            {
                "id": "wn_advertising_tricks",
                "title": "Advertising Tricks",
                "type": "quiz",
                "question": "A TV commercial says 'You NEED this amazing new backpack!' Is that true?",
                "options": [
                    "Yes — if it's on TV, it must be a real need",
                    "No — commercials try to make wants FEEL like needs",
                    "Yes — everyone needs the newest backpack",
                    "No — nobody ever needs a backpack",
                ],
                "answer": "b",
                "hints": [
                    "Commercials are paid for by companies that want you to buy their stuff.",
                    "The word 'need' in advertising doesn't mean the same as a real need!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Advertisers use powerful tricks to make you feel like you NEED their product. They use exciting music, bright colors, and persuasive words. But a real need is about survival — food, water, shelter, clothing. Learning to spot these tricks makes you a smarter consumer!",
                "is_boss": False,
                "flavor": "Puck puts on a flashy hat and shouts like a salesman: 'You NEED this hat!' Then he winks. 'Or do you just want it?'",
            },
            {
                "id": "wn_sorting_challenge",
                "title": "The Sorting Challenge",
                "type": "text",
                "question": "Sort these into needs and wants: a sandwich, a skateboard, a doctor visit, a movie ticket, warm shoes, and a comic book. Type the needs first, then the wants.",
                "options": [],
                "answer": "needs sandwich doctor visit warm shoes wants skateboard movie ticket comic book",
                "hints": [
                    "Which of these keep you alive, healthy, or safe?",
                    "Food, healthcare, and footwear protect your body. The others are for fun!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Needs: a sandwich (food), a doctor visit (health), warm shoes (protection). Wants: a skateboard, a movie ticket, a comic book (all fun but not necessary). Sorting things this way helps you make wise choices with your money!",
                "is_boss": False,
                "flavor": "Puck draws two columns on the page — NEEDS and WANTS — and starts tossing items into each one.",
            },
            {
                "id": "wn_boss_decision",
                "title": "The Big Decision",
                "type": "quiz",
                "question": "You have $20. You need new socks ($8) and want a toy ($15). You can only pick one. A wise shopper would:",
                "options": [
                    "Buy the toy because it's more fun",
                    "Buy the socks because needs come before wants",
                    "Buy neither and save all the money",
                    "Borrow more money to buy both",
                ],
                "answer": "b",
                "hints": [
                    "One of these is something you truly need. The other is something you want.",
                    "Smart spenders always handle needs first — then save up for wants!",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "The wise choice is to buy the socks (a need) and save the remaining $12 toward the toy. Needs always come first. And here's the bonus: after buying your socks, you still have $12 saved toward that toy! Patience and priorities — the keys to smart spending.",
                "is_boss": True,
                "flavor": "Puck sets up a tiny market stall with socks on one side and toys on the other. 'Choose wisely — this is the real test!'",
            },
        ],
    },
    "supply_and_demand": {
        "id": "supply_and_demand",
        "name": "Supply & Demand",
        "description": "Discover how prices are set and why things cost what they do",
        "level_required": 1,
        "challenges": [
            {
                "id": "sd_what_is_supply",
                "title": "What Is Supply?",
                "type": "quiz",
                "question": "A farmer grows 100 watermelons to sell at the market. What do we call the amount of something available to buy?",
                "options": [
                    "Demand",
                    "Supply",
                    "Profit",
                    "Tax",
                ],
                "answer": "b",
                "hints": [
                    "It's the amount of a product that sellers have ready to offer.",
                    "Think of it as what's being SUPPLIED to the market.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Supply is the total amount of a product or service that sellers are willing and able to offer. If the farmer has 100 watermelons, that's the supply. When supply is high, there's plenty for everyone!",
                "is_boss": False,
                "flavor": "Puck stacks tiny watermelons into a huge pyramid at a market stall. 'Look at all this supply!'",
            },
            {
                "id": "sd_what_is_demand",
                "title": "What Is Demand?",
                "type": "quiz",
                "question": "On a hot day, 200 people want to buy cold lemonade, but the stand only has 50 cups. What do we call how much people want something?",
                "options": [
                    "Supply",
                    "Demand",
                    "Savings",
                    "Budget",
                ],
                "answer": "b",
                "hints": [
                    "It's about how much people WANT or need something.",
                    "When lots of people want the same thing, this goes up!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Demand is how much people want to buy something. When it's hot and everyone wants lemonade, demand is HIGH. When nobody wants something, demand is LOW. Demand is one half of what determines a price!",
                "is_boss": False,
                "flavor": "Puck fans himself on a scorching day, eyeing the lemonade stand with a long line. 'That's high demand!'",
            },
            {
                "id": "sd_price_goes_up",
                "title": "When Prices Rise",
                "type": "quiz",
                "question": "Only 10 umbrellas are left at the store and a big rainstorm is coming. What will probably happen to the price?",
                "options": [
                    "The price will go down",
                    "The price will stay the same",
                    "The price will go up",
                    "Umbrellas will become free",
                ],
                "answer": "c",
                "hints": [
                    "Lots of people want umbrellas (high demand) but there aren't many left (low supply).",
                    "When demand is high and supply is low, sellers can charge more.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When supply is low and demand is high, prices go up. This is the basic law of supply and demand. The store has few umbrellas but everyone wants one — so the store can charge more because people are willing to pay!",
                "is_boss": False,
                "flavor": "Puck stands in the rain holding a tiny umbrella with a price tag that keeps climbing higher and higher.",
            },
            {
                "id": "sd_price_goes_down",
                "title": "When Prices Drop",
                "type": "text",
                "question": "A toy store has 500 stuffed bears but almost nobody wants to buy them. What do you think will happen to the price, and why? Type your answer.",
                "options": [],
                "answer": "price will go down because supply is high and demand is low",
                "hints": [
                    "The store has WAY more bears than people want. They need to get rid of them!",
                    "When stores have too much of something, they put it on... (think of the word!)",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "When supply is high and demand is low, prices drop. The store has too many bears and not enough buyers, so they'll lower the price (a sale!) to attract customers. This is why stores have clearance sales — to reduce excess supply!",
                "is_boss": False,
                "flavor": "Puck sits in a mountain of stuffed bears, putting SALE stickers on each one. 'Too many bears, not enough buyers!'",
            },
            {
                "id": "sd_scarcity",
                "title": "What Is Scarcity?",
                "type": "quiz",
                "question": "There's only one signed baseball card in the whole world. Why is it worth so much money?",
                "options": [
                    "Because baseballs are heavy",
                    "Because it's scarce — there's only one and many people want it",
                    "Because cards are made of paper",
                    "Because the store set the price high",
                ],
                "answer": "b",
                "hints": [
                    "When something is extremely rare but lots of people want it, the value skyrockets.",
                    "Scarcity means there isn't enough for everyone who wants it.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Scarcity means there isn't enough of something for everyone who wants it. When something is scarce AND people want it badly, its value goes way up. Diamonds are expensive because they're rare. Water is cheap because (in most places) there's plenty of it!",
                "is_boss": False,
                "flavor": "Puck holds up a tiny glowing card in a glass case. 'One of a kind. That's what makes it special!'",
            },
            {
                "id": "sd_competition",
                "title": "Competition Helps Buyers",
                "type": "quiz",
                "question": "Two ice cream trucks park on the same street. One charges $5 per cone, the other charges $3. What will probably happen?",
                "options": [
                    "Everyone buys the $5 cone because it must be better",
                    "The $5 truck will probably lower its price to compete",
                    "Both trucks will raise their prices",
                    "Nobody buys ice cream",
                ],
                "answer": "b",
                "hints": [
                    "If two sellers offer the same thing, which price would YOU choose?",
                    "When sellers compete, they try to offer the best deal to win customers.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Competition is great for buyers! When two or more sellers offer the same product, they compete for your money by lowering prices or improving quality. That's why having multiple shops and brands gives you better choices and better prices!",
                "is_boss": False,
                "flavor": "Two tiny ice cream trucks face off on the page while Puck grins. 'Competition means better deals for YOU!'",
            },
            {
                "id": "sd_market_in_action",
                "title": "A Market in Action",
                "type": "text",
                "question": "Imagine you're selling lemonade. On Monday it's hot and you sell 100 cups at $2 each. On Tuesday it rains and only 10 people come. What would you change about your price on Tuesday, and why?",
                "options": [],
                "answer": "lower the price because demand is lower on rainy days",
                "hints": [
                    "Fewer customers means less demand. How do you attract buyers when demand drops?",
                    "Think about what stores do when they have a slow day — they offer deals!",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "A smart seller adjusts prices based on demand. When demand drops (rainy day, fewer customers), lowering the price can attract more buyers. When demand is high (hot day), you can charge more. This is how real markets work every single day!",
                "is_boss": False,
                "flavor": "Puck stands behind a lemonade stand in the rain, flipping his price sign from $2 to $1. 'Adapt to the market!'",
            },
            {
                "id": "sd_boss_puzzle",
                "title": "The Market Puzzle",
                "type": "quiz",
                "question": "A new video game comes out. Millions of kids want it, but the company only made 1,000 copies. What happens to the price, and what is this an example of?",
                "options": [
                    "Price drops — this is competition",
                    "Price rises — this is supply and demand (low supply, high demand)",
                    "Price stays the same — this is a budget",
                    "Price disappears — this is bartering",
                ],
                "answer": "b",
                "hints": [
                    "Millions want it (high demand) but only 1,000 exist (low supply).",
                    "Remember: low supply + high demand = higher prices!",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "This is supply and demand in action! When supply (1,000 copies) is far less than demand (millions of kids), the price goes up — sometimes way up. People might even resell copies for much more than the original price. Understanding this helps you predict how markets behave!",
                "is_boss": True,
                "flavor": "Puck holds up a tiny glowing game cartridge while a crowd of miniature kids reaches for it. 'Supply and demand — the most powerful force in economics!'",
            },
        ],
    },
    "jobs_and_careers": {
        "id": "jobs_and_careers",
        "name": "Jobs & Careers",
        "description": "Explore different jobs, skills, and how people earn a living",
        "level_required": 1,
        "challenges": [
            {
                "id": "jc_why_people_work",
                "title": "Why People Work",
                "type": "quiz",
                "question": "Why do most grown-ups go to work?",
                "options": [
                    "Because they have nothing else to do",
                    "To earn money to pay for needs and wants",
                    "Because the government forces everyone to work",
                    "Just for fun",
                ],
                "answer": "b",
                "hints": [
                    "Think about how families pay for food, housing, and other things.",
                    "Working provides income — money that comes in regularly.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Most people work to earn income — money they use to pay for needs (food, shelter, clothing) and wants (vacations, toys, hobbies). Some people also work because they love what they do! The money earned from a job is called wages or a salary.",
                "is_boss": False,
                "flavor": "Puck puts on a tiny hard hat, then a chef hat, then a stethoscope. 'So many ways to earn a living!'",
            },
            {
                "id": "jc_different_jobs",
                "title": "Different Jobs",
                "type": "quiz",
                "question": "Which of these people provides a SERVICE (doing something helpful) rather than making a PRODUCT (a thing you can touch)?",
                "options": [
                    "A baker who makes bread",
                    "A doctor who treats sick people",
                    "A farmer who grows vegetables",
                    "A toymaker who builds wooden toys",
                ],
                "answer": "b",
                "hints": [
                    "Three of these people create something physical you can hold. One helps people in a different way.",
                    "A service is when someone uses their skills to help you, not to make a thing.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Jobs fall into two big categories: making products (things you can touch, like bread or toys) and providing services (doing something helpful, like healing the sick or teaching). Both are valuable! The economy needs both products and services to work.",
                "is_boss": False,
                "flavor": "Puck splits the page in two — products on one side, services on the other. 'The economy needs both!'",
            },
            {
                "id": "jc_skills_matter",
                "title": "Skills Matter",
                "type": "text",
                "question": "A brain surgeon earns much more than someone who mows lawns. Why do you think some jobs pay more than others? Type your answer.",
                "options": [],
                "answer": "jobs that require more skill training or education tend to pay more",
                "hints": [
                    "Think about how long it takes to learn brain surgery versus mowing a lawn.",
                    "Jobs that require rare skills, more education, or are more dangerous often pay more.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Jobs that require more education, special skills, or years of training usually pay more. A brain surgeon studies for over 10 years! Jobs that are dangerous, difficult, or that few people can do also tend to pay higher wages. This is supply and demand for workers!",
                "is_boss": False,
                "flavor": "Puck draws a staircase of skills — each step higher represents more training and higher pay. 'Every skill you learn is a step up!'",
            },
            {
                "id": "jc_entrepreneur_vs_employee",
                "title": "Boss or Worker?",
                "type": "quiz",
                "question": "What's the difference between an employee and an entrepreneur?",
                "options": [
                    "An employee works for someone else; an entrepreneur runs their own business",
                    "An employee is always richer than an entrepreneur",
                    "An entrepreneur doesn't have to work",
                    "There's no difference",
                ],
                "answer": "a",
                "hints": [
                    "One works FOR a company, the other CREATES a company.",
                    "An entrepreneur takes the risk of starting something new.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "An employee works for a company and earns a steady salary. An entrepreneur starts their own business — they take more risk but also have the chance to earn more. Both paths are valuable! Many successful people have been both at different times in their lives.",
                "is_boss": False,
                "flavor": "Puck stands at a crossroads — one path leads to an office, the other to a tiny shop with a handwritten sign. 'Two great paths!'",
            },
            {
                "id": "jc_earning_as_kid",
                "title": "Kids Can Earn Too",
                "type": "quiz",
                "question": "Which of these is a way a kid could earn money?",
                "options": [
                    "Wishing really hard for money",
                    "Setting up a lemonade stand or doing chores for neighbors",
                    "Taking money from someone else",
                    "Waiting until they're a grown-up",
                ],
                "answer": "b",
                "hints": [
                    "Think about simple jobs or businesses a young person could do.",
                    "Earning money means providing value — doing something useful for someone!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Kids can earn money too! Lemonade stands, dog walking, yard work, selling crafts, or doing extra chores are all real ways to earn. The key is providing value — doing something useful that someone is willing to pay for. Every entrepreneur started somewhere!",
                "is_boss": False,
                "flavor": "Puck holds up a tiny 'HELP WANTED: Dog Walker' sign. 'You're never too young to start earning!'",
            },
            {
                "id": "jc_community_helpers",
                "title": "Community Helpers",
                "type": "quiz",
                "question": "Firefighters, teachers, and police officers are paid with tax money. Why does the community pay for these jobs?",
                "options": [
                    "Because nobody else wants to do them",
                    "Because these services help EVERYONE in the community",
                    "Because the government likes spending money",
                    "Because these workers don't need money",
                ],
                "answer": "b",
                "hints": [
                    "Think about who benefits when a firefighter puts out a fire or a teacher educates children.",
                    "These are called public services — they serve the whole community.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Some jobs provide public services that benefit everyone — firefighters keep us safe, teachers educate our children, police maintain order. Because everyone benefits, everyone chips in through taxes to pay for them. This is how communities take care of each other!",
                "is_boss": False,
                "flavor": "Puck salutes a tiny row of community helpers — a firefighter, teacher, and officer — standing proudly on the page.",
            },
            {
                "id": "jc_dream_job",
                "title": "Your Dream Job",
                "type": "text",
                "question": "If you could have any job in the world, what would it be? What skills would you need to learn? Type your dream job and at least one skill it requires.",
                "options": [],
                "answer": "any job with a relevant skill",
                "hints": [
                    "Think about what you love doing and what job involves that activity.",
                    "Every job requires at least one special skill — what would yours be?",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Every job starts with a dream and a willingness to learn the skills you need. A game designer needs creativity and coding. A veterinarian needs science and compassion. Whatever your dream job is, you can start building those skills right now!",
                "is_boss": False,
                "flavor": "Puck opens a tiny door labeled 'YOUR FUTURE' and warm light pours out. 'What do you see in there?'",
            },
            {
                "id": "jc_boss_career_path",
                "title": "The Career Path",
                "type": "quiz",
                "question": "A young person wants to become a veterinarian (animal doctor). What's the BEST first step?",
                "options": [
                    "Skip school and go straight to the animal hospital",
                    "Study hard in science, volunteer at an animal shelter, and go to college",
                    "Watch a lot of animal videos online",
                    "Wait until someone offers them the job",
                ],
                "answer": "b",
                "hints": [
                    "Big careers require preparation — education, experience, and practice.",
                    "Think about the STEPS that lead to a goal: learn, practice, gain experience.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "Every career has a path: learn the basics, study the subject, gain experience, and keep improving. A veterinarian needs years of science education and hands-on practice. The journey starts with curiosity and small steps — like volunteering or reading about animals. Every expert was once a beginner!",
                "is_boss": True,
                "flavor": "Puck unrolls a tiny map with stepping stones leading to a glowing veterinary clinic. 'Every big journey starts with one step!'",
            },
        ],
    },
    "saving_and_budgeting": {
        "id": "saving_and_budgeting",
        "name": "Saving & Budgeting",
        "description": "Learn how to save money, set goals, and make a budget",
        "level_required": 1,
        "challenges": [
            {
                "id": "sb_why_save",
                "title": "Why Save Money?",
                "type": "quiz",
                "question": "Why is it smart to save some of your money instead of spending it all right away?",
                "options": [
                    "Because spending money is always bad",
                    "So you have money for bigger goals or unexpected problems",
                    "Because banks force you to save",
                    "You shouldn't save — spend it all while you can!",
                ],
                "answer": "b",
                "hints": [
                    "What if something breaks and you need to fix it? Or you want something big someday?",
                    "Saving is like planting seeds for the future.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Saving money helps you prepare for the future. It lets you buy bigger things you really want, handle emergencies (like a broken bike), and feel secure. People who save regularly have less stress about money because they're prepared!",
                "is_boss": False,
                "flavor": "Puck drops a coin into a piggy bank. 'Today's small coin is tomorrow's big treasure!'",
            },
            {
                "id": "sb_piggy_bank",
                "title": "The Piggy Bank",
                "type": "quiz",
                "question": "You save $2 every week in your piggy bank. How much will you have after 10 weeks?",
                "options": [
                    "$10",
                    "$12",
                    "$20",
                    "$22",
                ],
                "answer": "c",
                "hints": [
                    "Multiply: $2 times 10 weeks.",
                    "$2 + $2 + $2... ten times equals?",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "$2 per week times 10 weeks equals $20! Small amounts really add up over time. This is the power of consistent saving. If you saved $2 every week for a whole year (52 weeks), you'd have $104! Patience and consistency are the saver's superpowers.",
                "is_boss": False,
                "flavor": "Puck shakes a piggy bank and coins jingle inside. 'Listen to that — it's the sound of patience paying off!'",
            },
            {
                "id": "sb_savings_goal",
                "title": "Setting a Savings Goal",
                "type": "text",
                "question": "You want to buy a skateboard that costs $60. You earn $5 per week from chores. How many weeks will it take to save enough? Show your thinking.",
                "options": [],
                "answer": "12 weeks because 60 divided by 5 equals 12",
                "hints": [
                    "Divide the total cost by how much you save each week.",
                    "$60 divided by $5 per week = how many weeks?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "$60 divided by $5 per week = 12 weeks. That's about 3 months! Setting a savings goal means figuring out what you want, how much it costs, and how long it will take. Writing it down and tracking your progress makes saving exciting instead of boring!",
                "is_boss": False,
                "flavor": "Puck draws a thermometer on the page, marking $0 at the bottom and $60 at the top. 'Color it in as you save!'",
            },
            {
                "id": "sb_what_is_budget",
                "title": "What Is a Budget?",
                "type": "quiz",
                "question": "A budget is:",
                "options": [
                    "A rule that says you can never spend money",
                    "A plan for how you'll use your money",
                    "A type of bank account",
                    "Something only adults need",
                ],
                "answer": "b",
                "hints": [
                    "Think of it as a money MAP that shows where every dollar goes.",
                    "A budget doesn't stop you from spending — it helps you spend WISELY.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "A budget is simply a plan for your money. It helps you decide how much to spend, save, and share. Even kids can make a budget! The key is: money IN (what you earn) minus money OUT (what you spend) should leave some for savings.",
                "is_boss": False,
                "flavor": "Puck unfolds a tiny scroll with neat columns: EARN, SPEND, SAVE. 'A budget is your money's roadmap!'",
            },
            {
                "id": "sb_spending_wisely",
                "title": "Spending Wisely",
                "type": "quiz",
                "question": "You have $10. A toy costs $8 at Store A and $6 at Store B. Both toys are the same. What should a smart shopper do?",
                "options": [
                    "Buy from Store A because you saw it first",
                    "Buy from Store B and save $2",
                    "Buy from both stores",
                    "Don't buy anything ever",
                ],
                "answer": "b",
                "hints": [
                    "If the toys are exactly the same, why pay more?",
                    "Comparing prices before buying is called being a smart shopper!",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Smart shoppers compare prices before buying! If two items are the same, buy the cheaper one and save the difference. That extra $2 can go into your savings. This habit, called comparison shopping, can save you hundreds of dollars over time!",
                "is_boss": False,
                "flavor": "Puck holds up two identical toys with different price tags and points to the cheaper one with a grin. 'Same toy, more savings!'",
            },
            {
                "id": "sb_emergency_fund",
                "title": "The Rainy Day Fund",
                "type": "quiz",
                "question": "What is an 'emergency fund'?",
                "options": [
                    "Money you spend on emergencies like buying a new game quickly",
                    "Money you save for unexpected problems, like a broken bicycle",
                    "A fund for buying umbrellas when it rains",
                    "Money the government gives you",
                ],
                "answer": "b",
                "hints": [
                    "Sometimes unexpected things happen — a flat tire, a broken window, a lost lunch box.",
                    "An emergency fund is money set aside JUST for surprises.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "An emergency fund is money saved for unexpected problems — a broken bike, a lost backpack, or something that needs fixing. Having emergency savings means surprises don't become disasters. Even saving a small amount regularly builds a safety net over time!",
                "is_boss": False,
                "flavor": "Puck tucks a few coins under a tiny umbrella. 'For a rainy day — because you never know when rain comes!'",
            },
            {
                "id": "sb_budget_practice",
                "title": "Build a Budget",
                "type": "text",
                "question": "You earn $20 from chores this month. You want to split it between saving, spending, and sharing (giving). How would you divide the $20? Type your plan.",
                "options": [],
                "answer": "any reasonable split that includes saving spending and sharing",
                "hints": [
                    "A common plan is 50% save, 40% spend, 10% share — but you decide!",
                    "Make sure all three categories get something, and the total adds up to $20.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "There's no single right answer, but a good budget includes all three: saving (for future goals), spending (for things you need or want now), and sharing (to help others). A popular kid-friendly split is: Save $10, Spend $8, Share $2. The best budget is one you'll actually follow!",
                "is_boss": False,
                "flavor": "Puck sets up three tiny jars labeled SAVE, SPEND, and SHARE. 'Every dollar gets a job!'",
            },
            {
                "id": "sb_boss_budget_challenge",
                "title": "The Budget Challenge",
                "type": "quiz",
                "question": "Emma earns $15 per week. She spends $12 on wants and $5 on needs. What's wrong with her budget?",
                "options": [
                    "She's spending too much on needs",
                    "She's spending more than she earns ($17 > $15)",
                    "She should spend more on wants",
                    "Nothing is wrong — this is a great budget",
                ],
                "answer": "b",
                "hints": [
                    "Add up her total spending: $12 + $5 = ?",
                    "If you spend MORE than you earn, you're in trouble!",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "Emma is spending $17 but only earning $15 — she's $2 short every week! This is called a budget deficit, and it means she'll run out of money or go into debt. A healthy budget means spending LESS than you earn, so there's always some left to save.",
                "is_boss": True,
                "flavor": "Puck holds up a tiny calculator showing red numbers. 'When spending beats earning, that's a problem. Let's fix it!'",
            },
        ],
    },
    "trading_and_global": {
        "id": "trading_and_global",
        "name": "Trading & Global Economy",
        "description": "Explore how countries trade with each other and how the world economy works",
        "level_required": 1,
        "challenges": [
            {
                "id": "tg_what_is_trade",
                "title": "What Is Trade?",
                "type": "quiz",
                "question": "When one country sells bananas to another country that doesn't grow them, this is called:",
                "options": [
                    "Bartering",
                    "International trade",
                    "A gift",
                    "Stealing",
                ],
                "answer": "b",
                "hints": [
                    "When countries buy and sell things with each other, it has a special name.",
                    "'International' means between nations. 'Trade' means buying and selling.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "International trade is when countries buy and sell goods with each other. Countries trade because no single country can make everything it needs. Brazil grows coffee, Japan makes electronics, Australia mines iron — and they all trade with each other!",
                "is_boss": False,
                "flavor": "Puck unfolds a tiny world map with arrows showing bananas flying from one country to another. 'The whole world is one big marketplace!'",
            },
            {
                "id": "tg_imports_exports",
                "title": "Imports and Exports",
                "type": "quiz",
                "question": "If the United States buys tea from India, the tea is a(n) _____ for the US and a(n) _____ for India.",
                "options": [
                    "Export, import",
                    "Import, export",
                    "Gift, tax",
                    "Want, need",
                ],
                "answer": "b",
                "hints": [
                    "IMport = coming IN. EXport = going OUT (like an EXIT).",
                    "India sends the tea OUT (export). The US brings the tea IN (import).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "An import is something a country BRINGS IN from another country. An export is something a country SENDS OUT to another country. The same product is an import for the buyer and an export for the seller. Easy trick: IMport = IN, EXport = EXIT!",
                "is_boss": False,
                "flavor": "Puck stamps a tiny box with two labels — 'IMPORT' on one side, 'EXPORT' on the other. 'Same box, different perspectives!'",
            },
            {
                "id": "tg_why_trade",
                "title": "Why Countries Trade",
                "type": "text",
                "question": "Iceland is very cold and can't grow tropical fruits. Costa Rica is very warm and grows lots of bananas. Why is trade helpful for both countries? Type your answer.",
                "options": [],
                "answer": "trade lets each country get things it cannot produce itself",
                "hints": [
                    "Think about what each country is good at and what it can't do.",
                    "Iceland has fish and geothermal energy. Costa Rica has tropical fruits. Both want what the other has!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Countries trade because each one is better at producing different things. Iceland can catch fish but can't grow bananas. Costa Rica grows bananas but might need Iceland's fish or technology. Trade lets every country enjoy products from around the world!",
                "is_boss": False,
                "flavor": "Puck draws Iceland with snowflakes and Costa Rica with sunshine, then draws a bridge of bananas and fish between them. 'Trade connects the world!'",
            },
            {
                "id": "tg_currency",
                "title": "Different Money Around the World",
                "type": "quiz",
                "question": "In Japan, the currency is called the yen. In Europe, it's the euro. In the US, it's the dollar. What do we call the different types of money used in different countries?",
                "options": [
                    "Coins",
                    "Tokens",
                    "Currency",
                    "Receipts",
                ],
                "answer": "c",
                "hints": [
                    "Each country's official money has a special name for the category it belongs to.",
                    "Dollars, euros, and yen are all types of _______.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Currency is the official money used in a country. Every country (or group of countries, like the European Union) has its own currency. Dollars, euros, yen, pounds, rupees, yuan — they're all different currencies. This is why travelers need to exchange money!",
                "is_boss": False,
                "flavor": "Puck juggles tiny bills from different countries — dollars, euros, yen, and rupees fly through the air. 'So many currencies!'",
            },
            {
                "id": "tg_exchange_rates",
                "title": "Exchange Rates",
                "type": "quiz",
                "question": "If 1 US dollar equals 150 Japanese yen, how many yen would you get for $10?",
                "options": [
                    "15 yen",
                    "150 yen",
                    "1,500 yen",
                    "15,000 yen",
                ],
                "answer": "c",
                "hints": [
                    "If 1 dollar = 150 yen, then 10 dollars = 10 times 150.",
                    "Multiply: 10 × 150 = ?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "10 × 150 = 1,500 yen! An exchange rate tells you how much one currency is worth in another. Exchange rates change every day based on supply and demand. When you travel to another country, you exchange your money at a bank or currency exchange!",
                "is_boss": False,
                "flavor": "Puck stands at a tiny exchange booth, sliding dollars in one side and yen out the other. 'Math makes the world go round!'",
            },
            {
                "id": "tg_barter_to_digital",
                "title": "From Barter to Digital",
                "type": "quiz",
                "question": "What's the correct order of how trade evolved?",
                "options": [
                    "Digital payments → bartering → gold coins → paper money",
                    "Bartering → gold coins → paper money → digital payments",
                    "Paper money → bartering → digital payments → gold coins",
                    "Gold coins → paper money → bartering → digital payments",
                ],
                "answer": "b",
                "hints": [
                    "Start with the simplest, oldest method and end with the newest.",
                    "People traded stuff first, then used shiny metals, then paper, then computers!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Trade evolved over thousands of years: first bartering (swapping goods), then coins (metal money), then paper money (lighter and easier), and now digital payments (credit cards, phones, online banking). Each step made trading faster, easier, and more global!",
                "is_boss": False,
                "flavor": "Puck flips through a tiny history book, watching cave people barter, merchants count gold coins, bankers print paper, and kids tap phones. 'What a journey!'",
            },
            {
                "id": "tg_global_connection",
                "title": "A Global World",
                "type": "text",
                "question": "Look around your room. Can you name one thing that was probably made in another country? What country might it have come from, and how did it get to you? Type your answer.",
                "options": [],
                "answer": "any item with a plausible country of origin and mention of shipping or trade",
                "hints": [
                    "Check labels on your clothes, toys, or electronics — many say 'Made in...'",
                    "Most electronics come from Asia. Many clothes come from Bangladesh or Vietnam. Toys often come from China.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Almost everything in your home traveled across the world to reach you! Your shirt might be from Bangladesh, your tablet from China, your chocolate from Ghana. Global trade connects billions of people. The next time you pick something up, think about its amazing journey!",
                "is_boss": False,
                "flavor": "Puck flips over a teddy bear and reads the tiny tag: 'Made in China. Shipped across the Pacific Ocean!' His eyes go wide.",
            },
            {
                "id": "tg_boss_global_trade",
                "title": "The Global Trade Challenge",
                "type": "quiz",
                "question": "Country A makes great cars but can't grow coffee. Country B grows amazing coffee but can't make cars. What's the BEST solution?",
                "options": [
                    "Country A should give up and stop wanting coffee",
                    "Country B should try to build cars even though it can't",
                    "Both countries should trade — cars for coffee — so both get what they need",
                    "They should ignore each other completely",
                ],
                "answer": "c",
                "hints": [
                    "Each country is good at something different. How can both benefit?",
                    "This is the whole reason international trade exists!",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "This is called comparative advantage — each country focuses on what it does best and trades for the rest. Country A makes cars, Country B grows coffee, and both trade. Everyone wins! This is the foundation of the entire global economy and why trade makes the world better for everyone.",
                "is_boss": True,
                "flavor": "Puck draws two countries on the page, one with a car factory and one with coffee fields, then draws a bridge between them labeled 'TRADE.' 'Together, everyone wins!'",
            },
        ],
    },
}
