"""
zones.py — Introduction to Psychology zones and challenges.

5 zones, 8 challenges each (40 total). Mix of quiz and text challenges.
Covers: What is Psychology, Research Methods, The Brain & Nervous System,
Sensation & Perception, and States of Consciousness.
"""

ZONE_ORDER = [
    "what_is_psychology",
    "research_methods",
    "brain_nervous_system",
    "sensation_perception",
    "states_of_consciousness",
]

ZONES = {
    # ── Zone 1: What Is Psychology ────────────────────────────────────
    "what_is_psychology": {
        "id": "what_is_psychology",
        "name": "The Foundations",
        "description": "The origins, perspectives, and scope of psychology as a science",
        "level_required": 1,
        "challenges": [
            {
                "id": "wip_1",
                "title": "Defining the Discipline",
                "type": "quiz",
                "question": "Psychology is best defined as the scientific study of:",
                "options": [
                    "Mental illness and its treatment",
                    "Mind and behavior",
                    "The brain and its chemistry",
                    "Human emotions only",
                ],
                "answer": "b",
                "hints": [
                    "It's broader than just illness or the brain.",
                    "Think about the two main things psychologists study — internal processes AND observable actions.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Psychology is the scientific study of mind (internal mental processes like thoughts, feelings, and memories) and behavior (observable actions). It encompasses far more than mental illness — it includes perception, learning, development, social interaction, and everything the mind does.",
                "is_boss": False,
                "flavor": "ARIA projects the definition onto the neural lattice. 'Two words,' she says. 'Everything else follows from them.'",
            },
            {
                "id": "wip_2",
                "title": "The First Laboratory",
                "type": "quiz",
                "question": "Who established the first formal psychology laboratory in 1879, marking psychology's birth as an independent scientific discipline?",
                "options": [
                    "Sigmund Freud",
                    "William James",
                    "Wilhelm Wundt",
                    "Ivan Pavlov",
                ],
                "answer": "c",
                "hints": [
                    "It happened in Leipzig, Germany.",
                    "This person used introspection as a method to study conscious experience.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Wilhelm Wundt opened the first psychology laboratory at the University of Leipzig in 1879. He used introspection — trained self-observation — to study conscious experience. While his methods were later criticized, his insistence that the mind could be studied scientifically launched the entire discipline.",
                "is_boss": False,
                "flavor": "ARIA highlights a date on the timeline: 1879. A man in a German laboratory is asking subjects to describe their conscious experiences in precise, measurable terms.",
            },
            {
                "id": "wip_3",
                "title": "The Behaviorist Revolution",
                "type": "quiz",
                "question": "The behaviorist perspective, championed by John B. Watson and B.F. Skinner, argued that psychology should focus exclusively on:",
                "options": [
                    "Unconscious desires and childhood experiences",
                    "Observable, measurable behavior",
                    "Brain scans and neural imaging",
                    "Self-reported thoughts and feelings",
                ],
                "answer": "b",
                "hints": [
                    "Behaviorists rejected anything that couldn't be directly observed.",
                    "If you can't see it and measure it, it doesn't belong in science — that was their position.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Behaviorism dominated psychology from roughly 1920 to 1960. Watson declared that psychology should study only observable behavior, rejecting introspection entirely. Skinner extended this with operant conditioning, showing how consequences shape behavior. Their legacy: psychology became rigorously experimental. Their limitation: they ignored the mind itself.",
                "is_boss": False,
                "flavor": "ARIA shows a white rat in a maze, a pigeon pecking a lever. 'For forty years,' she says, 'the mind was off-limits. Only behavior counted.'",
            },
            {
                "id": "wip_4",
                "title": "The Unconscious Mind",
                "type": "quiz",
                "question": "Sigmund Freud's psychodynamic perspective emphasized that behavior is largely driven by:",
                "options": [
                    "Rational decision-making and logic",
                    "Unconscious conflicts, desires, and childhood experiences",
                    "Genetic inheritance and evolution",
                    "Environmental reinforcement and punishment",
                ],
                "answer": "b",
                "hints": [
                    "Freud believed the most powerful forces in the mind are the ones you're NOT aware of.",
                    "Think about dreams, slips of the tongue, and repressed memories.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Freud proposed that much of our mental life operates below conscious awareness. His psychodynamic perspective emphasizes unconscious motivations, defense mechanisms, and the lasting influence of early childhood experiences. While many of Freud's specific theories have been challenged, his core insight — that we are not fully aware of why we do what we do — remains influential.",
                "is_boss": False,
                "flavor": "ARIA dims the lights. 'Freud's most radical idea wasn't about sex,' she says. 'It was that you don't know your own reasons.'",
            },
            {
                "id": "wip_5",
                "title": "The Cognitive Revolution",
                "type": "quiz",
                "question": "The cognitive revolution of the 1950s-60s brought the study of internal mental processes back into psychology. What key metaphor did cognitive psychologists use to understand the mind?",
                "options": [
                    "The mind as a blank slate",
                    "The mind as an information-processing computer",
                    "The mind as a hydraulic system of pressures",
                    "The mind as a collection of reflexes",
                ],
                "answer": "b",
                "hints": [
                    "Computers were becoming widespread in the 1950s and offered a new way to think about thinking.",
                    "Input, processing, storage, output — sound familiar?",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The cognitive revolution restored the study of internal mental processes — memory, attention, language, problem-solving — by framing the mind as an information processor. Like a computer, the mind takes in data (sensation), processes it (cognition), stores it (memory), and produces output (behavior). This metaphor drove decades of productive research, though modern psychologists recognize its limits.",
                "is_boss": False,
                "flavor": "ARIA projects a flowchart: input → processing → output. 'The behaviorists banned the middle step,' she says. 'The cognitivists brought it back.'",
            },
            {
                "id": "wip_6",
                "title": "Nature vs. Nurture",
                "type": "quiz",
                "question": "The nature vs. nurture debate asks whether behavior is shaped primarily by genetics or environment. Modern psychology's answer is:",
                "options": [
                    "Nature (genetics) is clearly more important",
                    "Nurture (environment) is clearly more important",
                    "Both interact in complex ways — the question itself is too simplistic",
                    "Neither matters because people have free will",
                ],
                "answer": "c",
                "hints": [
                    "Think about how genes can influence which environments you seek out, and how environments can affect gene expression.",
                    "The modern answer isn't 'one or the other.'",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Modern psychology has moved beyond the nature-versus-nurture dichotomy. The field of epigenetics shows that environmental factors can literally turn genes on and off. Gene-environment interactions mean that the same genetic predisposition may produce different outcomes in different environments. The question isn't 'which one?' — it's 'how do they interact?'",
                "is_boss": False,
                "flavor": "ARIA splits the display in two — DNA on one side, a child's environment on the other. Then the dividing line dissolves. 'They were never separate,' she says.",
            },
            {
                "id": "wip_7",
                "title": "The Biopsychosocial Model",
                "type": "text",
                "question": "Explain why the biopsychosocial model is considered more complete than any single perspective in psychology. Give a concrete example of how biological, psychological, AND social factors all contribute to one specific behavior or condition.",
                "options": [],
                "answer": "A strong answer identifies all three levels (biological, psychological, social) and provides a specific example showing how they interact. For instance: depression involves brain chemistry (biological — serotonin levels), thought patterns (psychological — negative self-talk, learned helplessness), and social context (social — isolation, discrimination, poverty). No single level tells the full story.",
                "hints": [
                    "Pick one condition or behavior — depression, addiction, aggression — and trace it across all three levels.",
                    "Bio = body/brain, Psycho = thoughts/feelings, Social = relationships/culture.",
                ],
                "xp": 40,
                "difficulty": "medium",
                "lesson": "The biopsychosocial model recognizes that behavior emerges from the interaction of biological factors (genetics, brain chemistry, hormones), psychological factors (thoughts, emotions, personality), and social factors (family, culture, socioeconomic status). No single level of analysis is sufficient. For example, understanding depression requires considering neurotransmitter imbalances AND cognitive distortions AND social isolation — they feed into and amplify each other.",
                "is_boss": False,
                "flavor": "ARIA builds three overlapping circles: Biology. Psychology. Society. 'Every behavior you'll ever study,' she says, 'lives in the intersection.'",
            },
            {
                "id": "wip_boss",
                "title": "BOSS: The Perspectives Gauntlet",
                "type": "quiz",
                "question": "A patient is struggling with severe anxiety. A behaviorist would focus on learned associations and avoidance patterns. A psychodynamic therapist would explore unconscious conflicts. A cognitive psychologist would examine thought distortions. A biological psychologist would look at neurotransmitter levels. Which statement BEST captures the relationship between these approaches?",
                "options": [
                    "Only one can be correct — the others are outdated",
                    "They are competing explanations and the strongest evidence should win",
                    "They are complementary levels of analysis — each captures part of the truth, and integrating them gives the fullest picture",
                    "They are all equally wrong because psychology isn't a real science",
                ],
                "answer": "c",
                "hints": [
                    "Think about the biopsychosocial model you just learned.",
                    "Can anxiety have causes at multiple levels simultaneously?",
                ],
                "xp": 60,
                "difficulty": "boss",
                "is_boss": True,
                "lesson": "Psychology's major perspectives are not competing theories where one must be right and the rest wrong. They are complementary levels of analysis. Anxiety IS a pattern of learned avoidance (behavioral). It IS maintained by catastrophic thinking (cognitive). It IS influenced by neurotransmitter levels (biological). It IS shaped by early experiences (psychodynamic). The most effective treatments often integrate insights from multiple perspectives.",
                "flavor": "ARIA projects all the perspectives simultaneously — overlapping, interacting, each illuminating a different facet of the same phenomenon. 'The whole picture,' she says. 'That's what psychology is reaching for.'",
            },
        ],
    },

    # ── Zone 2: Research Methods ──────────────────────────────────────
    "research_methods": {
        "id": "research_methods",
        "name": "The Methods Lab",
        "description": "How psychologists design experiments, collect data, and separate truth from intuition",
        "level_required": 1,
        "challenges": [
            {
                "id": "rm_1",
                "title": "The Scientific Method",
                "type": "quiz",
                "question": "What is the correct sequence of steps in the scientific method as applied to psychological research?",
                "options": [
                    "Theory → Experiment → Hypothesis → Analysis",
                    "Observation → Hypothesis → Experiment → Analysis → Conclusion",
                    "Hypothesis → Publication → Experiment → Review",
                    "Data collection → Theory → Conclusion → Experiment",
                ],
                "answer": "b",
                "hints": [
                    "It starts with noticing something and asking a question.",
                    "You need a prediction BEFORE you run the experiment.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The scientific method in psychology follows a cycle: observe a phenomenon, form a testable hypothesis, design and conduct an experiment, analyze the data, and draw conclusions. The conclusions often generate new observations, restarting the cycle. This process is what separates psychological science from armchair speculation.",
                "is_boss": False,
                "flavor": "ARIA draws the cycle on the lab wall. 'Every finding in psychology,' she says, 'started with someone noticing something and asking: can I test that?'",
            },
            {
                "id": "rm_2",
                "title": "Correlation vs. Causation",
                "type": "quiz",
                "question": "A study finds that people who eat more ice cream are more likely to drown. This means:",
                "options": [
                    "Ice cream causes drowning",
                    "Drowning causes people to crave ice cream",
                    "A third variable (hot weather) likely causes both — correlation does not imply causation",
                    "The study must be wrong",
                ],
                "answer": "c",
                "hints": [
                    "When two things happen together, it doesn't mean one causes the other.",
                    "What third factor could explain why BOTH increase at the same time?",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Correlation means two variables change together, but it does NOT prove one causes the other. A third variable — a confound — may drive both. In this case, hot weather increases both ice cream consumption and swimming (leading to more drowning). Only controlled experiments with random assignment can establish causation.",
                "is_boss": False,
                "flavor": "ARIA draws two rising lines on a graph. 'They move together,' she says. 'But moving together is not the same as being connected.'",
            },
            {
                "id": "rm_3",
                "title": "Independent & Dependent Variables",
                "type": "quiz",
                "question": "In an experiment testing whether caffeine improves reaction time, the amount of caffeine given is the _____ variable and reaction time is the _____ variable.",
                "options": [
                    "Dependent; independent",
                    "Independent; dependent",
                    "Confounding; independent",
                    "Control; experimental",
                ],
                "answer": "b",
                "hints": [
                    "The variable the researcher MANIPULATES is the independent variable.",
                    "The variable being MEASURED (the outcome) is the dependent variable — it 'depends' on what you changed.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "The independent variable (IV) is what the researcher deliberately manipulates — here, caffeine dose. The dependent variable (DV) is what gets measured as the outcome — here, reaction time. The DV 'depends on' the IV. Remembering which is which is fundamental to reading and designing experiments.",
                "is_boss": False,
                "flavor": "ARIA adjusts a dial labeled 'Caffeine mg' and points at a flashing reaction-time counter. 'I change this. I measure that. That's an experiment.'",
            },
            {
                "id": "rm_4",
                "title": "The Placebo Effect",
                "type": "quiz",
                "question": "Why do researchers use placebo control groups in experiments?",
                "options": [
                    "To trick participants for entertainment",
                    "To ensure that observed effects are due to the treatment itself, not participants' expectations",
                    "Because placebos are cheaper than real treatments",
                    "Placebos are only used in medical research, not psychology",
                ],
                "answer": "b",
                "hints": [
                    "If people EXPECT to feel better, they often do — regardless of the treatment.",
                    "The control group helps you separate the effect of belief from the effect of the treatment.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The placebo effect demonstrates that expectation alone can produce real physiological and psychological changes. Control groups receiving placebos allow researchers to measure how much of an effect is due to the actual treatment versus participants' beliefs. Without a placebo control, you can't tell if your treatment works or if people just expected it to.",
                "is_boss": False,
                "flavor": "ARIA holds up two identical pills. 'One contains the drug. One contains sugar. Both groups improve. That's the problem you have to solve.'",
            },
            {
                "id": "rm_5",
                "title": "Random Assignment",
                "type": "quiz",
                "question": "Why is random assignment to experimental conditions so important?",
                "options": [
                    "It makes the experiment faster to run",
                    "It ensures each participant has an equal chance of being in any condition, reducing the influence of confounding variables",
                    "It guarantees the results will be statistically significant",
                    "It is only required for studies with more than 100 participants",
                ],
                "answer": "b",
                "hints": [
                    "Without random assignment, the groups might differ in ways that affect the outcome.",
                    "Imagine testing a new study technique but putting all the motivated students in one group.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Random assignment distributes participant characteristics (age, motivation, intelligence, personality) approximately equally across conditions. This means any difference in outcomes is likely due to the independent variable, not pre-existing group differences. Without it, confounding variables can masquerade as treatment effects.",
                "is_boss": False,
                "flavor": "ARIA flips a coin. 'Heads: Group A. Tails: Group B. This simple act is what separates an experiment from an anecdote.'",
            },
            {
                "id": "rm_6",
                "title": "Ethical Research",
                "type": "quiz",
                "question": "After the controversial Milgram obedience studies, psychology established strict ethical guidelines. Which of the following is NOW required for human research?",
                "options": [
                    "Participants must never experience any discomfort of any kind",
                    "Informed consent, the right to withdraw at any time, debriefing, and institutional review board approval",
                    "Experiments can only be conducted on college students",
                    "Deception is permanently banned in all psychological research",
                ],
                "answer": "b",
                "hints": [
                    "The key principles protect participants' autonomy, safety, and right to information.",
                    "Deception is still sometimes permitted under strict conditions — but informed consent is non-negotiable.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Modern research ethics require informed consent (participants know what they're agreeing to), the right to withdraw without penalty, debriefing after the study, and approval from an Institutional Review Board (IRB). Deception is allowed only when necessary and when debriefing fully explains it afterward. These safeguards exist because of past studies — like Milgram's — that caused genuine distress.",
                "is_boss": False,
                "flavor": "ARIA shows footage from Milgram's experiment — participants visibly distressed, an experimenter saying 'Please continue.' 'This is why we have ethics boards now,' she says quietly.",
            },
            {
                "id": "rm_7",
                "title": "Statistical Significance",
                "type": "text",
                "question": "A researcher finds that a new therapy reduces anxiety scores with a p-value of 0.03. Explain what this means in plain language, and describe one limitation of relying on p-values alone to evaluate whether a treatment works.",
                "options": [],
                "answer": "A strong answer explains that p = 0.03 means there is a 3% probability of obtaining results this extreme (or more extreme) if the treatment had no real effect — i.e., the result is unlikely to be due to chance alone. A limitation: p-values don't tell you the SIZE of the effect (a statistically significant but tiny effect may not be clinically meaningful), they don't prove the treatment works (only that the result is unlikely under the null hypothesis), and they're sensitive to sample size (large samples can produce significant p-values for trivial effects).",
                "hints": [
                    "P-value is about probability, not proof. What is the probability OF?",
                    "A tiny effect can be 'statistically significant' with a large enough sample — but does it matter in practice?",
                ],
                "xp": 40,
                "difficulty": "medium",
                "lesson": "A p-value of 0.03 means: if the treatment had NO real effect, there's only a 3% chance of seeing results this extreme by random chance. It does NOT mean there's a 97% chance the treatment works. Key limitations: p-values don't measure effect size (how BIG the effect is), they're influenced by sample size, and a 'significant' result can still be practically meaningless. Modern psychology increasingly emphasizes effect sizes and confidence intervals alongside p-values.",
                "is_boss": False,
                "flavor": "ARIA writes 'p = 0.03' on the lab display. 'Most people misread this,' she says. 'Including some researchers.'",
            },
            {
                "id": "rm_boss",
                "title": "BOSS: The Experimental Design Trial",
                "type": "quiz",
                "question": "A school claims its new teaching method improves test scores. They let students choose whether to use the new method or the traditional one. Students using the new method scored 15% higher. A psychologist reviewing this study would identify the BIGGEST flaw as:",
                "options": [
                    "The sample size was too small",
                    "Self-selection bias — students who chose the new method may have been more motivated, making it impossible to attribute the improvement to the method itself",
                    "The test was too easy",
                    "The study should have used brain imaging",
                ],
                "answer": "b",
                "hints": [
                    "What kind of students would volunteer to try a new method?",
                    "Without random assignment, the groups probably differ in ways that matter.",
                ],
                "xp": 60,
                "difficulty": "boss",
                "is_boss": True,
                "lesson": "Self-selection bias occurs when participants choose their own group. Students who opt into a new method likely differ from those who don't — in motivation, openness to change, academic confidence, or study habits. These pre-existing differences, not the teaching method, may explain the score difference. This is why random assignment is the gold standard: it prevents participants' characteristics from contaminating the results.",
                "flavor": "ARIA projects the study design. 'On the surface, it looks convincing,' she says. 'But there's a crack in the foundation. Find it.'",
            },
        ],
    },

    # ── Zone 3: The Brain & Nervous System ────────────────────────────
    "brain_nervous_system": {
        "id": "brain_nervous_system",
        "name": "The Neural Architecture",
        "description": "Neurons, neurotransmitters, brain structure, and the nervous system",
        "level_required": 1,
        "challenges": [
            {
                "id": "bns_1",
                "title": "The Neuron",
                "type": "quiz",
                "question": "A neuron receives signals through its _____ and sends signals along its _____.",
                "options": [
                    "Axon; dendrites",
                    "Dendrites; axon",
                    "Soma; synapse",
                    "Myelin sheath; cell body",
                ],
                "answer": "b",
                "hints": [
                    "Dendrites branch out like tree roots to RECEIVE incoming signals.",
                    "The axon is the long 'tail' that SENDS signals to the next neuron.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "A neuron has three main parts: dendrites (branching extensions that receive signals from other neurons), the cell body or soma (which processes signals), and the axon (a long fiber that transmits signals to other neurons). Information flows in one direction: dendrites → cell body → axon → synaptic terminals.",
                "is_boss": False,
                "flavor": "ARIA zooms in on a single neuron. Its dendrites reach out like fingers, gathering signals. Its axon stretches into the distance, carrying the message forward.",
            },
            {
                "id": "bns_2",
                "title": "The Action Potential",
                "type": "quiz",
                "question": "The 'all-or-nothing' principle of neural firing means that:",
                "options": [
                    "A neuron fires at full strength or not at all — there is no partial firing",
                    "All neurons in the brain fire at the same time",
                    "A neuron can only fire once in its lifetime",
                    "Strong stimuli cause neurons to fire with more voltage",
                ],
                "answer": "a",
                "hints": [
                    "Think of it like a gun — you either pull the trigger or you don't. There's no half-shot.",
                    "The intensity of a sensation isn't coded by stronger signals, but by MORE neurons firing or firing MORE FREQUENTLY.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "A neuron either reaches its threshold and fires a full-strength action potential, or it doesn't fire at all. There's no 'weak' action potential. The brain encodes intensity through the RATE of firing (more intense = faster firing) and the NUMBER of neurons activated, not through the strength of individual signals.",
                "is_boss": False,
                "flavor": "ARIA charges the neural simulation. The voltage builds... builds... then — SPIKE. 'It's binary,' she says. 'Fire or don't. The nuance is in the pattern.'",
            },
            {
                "id": "bns_3",
                "title": "Neurotransmitters",
                "type": "quiz",
                "question": "Which neurotransmitter is most associated with mood regulation, and is the primary target of SSRI antidepressant medications?",
                "options": [
                    "Dopamine",
                    "Acetylcholine",
                    "Serotonin",
                    "GABA",
                ],
                "answer": "c",
                "hints": [
                    "SSRI stands for Selective Serotonin Reuptake Inhibitor.",
                    "This neurotransmitter affects mood, sleep, and appetite.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Serotonin is a neurotransmitter involved in mood regulation, sleep, appetite, and impulse control. SSRIs (Selective Serotonin Reuptake Inhibitors) like Prozac and Zoloft work by blocking the reabsorption of serotonin in the synapse, making more available. Key neurotransmitters: dopamine (reward/movement), serotonin (mood/sleep), acetylcholine (learning/muscle), GABA (inhibition), glutamate (excitation), endorphins (pain/pleasure).",
                "is_boss": False,
                "flavor": "ARIA fills the synapse with tiny glowing molecules. 'Serotonin,' she says. 'Too little, and the world goes gray. The drugs don't add more — they just keep what's there from being cleaned up too fast.'",
            },
            {
                "id": "bns_4",
                "title": "The Cerebral Cortex",
                "type": "quiz",
                "question": "The frontal lobe of the cerebral cortex is primarily responsible for:",
                "options": [
                    "Processing visual information",
                    "Processing auditory information",
                    "Executive functions: planning, decision-making, impulse control, and personality",
                    "Processing touch and spatial awareness",
                ],
                "answer": "c",
                "hints": [
                    "This is the brain region that matures LAST — not fully developed until about age 25.",
                    "Phineas Gage's famous injury to this area dramatically changed his personality.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The frontal lobe — especially the prefrontal cortex — handles executive functions: planning, decision-making, impulse control, working memory, and aspects of personality. It's the last brain region to fully mature (around age 25), which partly explains adolescent risk-taking. The four lobes: frontal (executive function), parietal (touch/spatial), temporal (hearing/language), occipital (vision).",
                "is_boss": False,
                "flavor": "ARIA highlights the front of the brain in gold. 'This is what makes you YOU,' she says. 'Planning, restraint, judgment. It's also the last part to finish developing. That explains a lot about teenagers.'",
            },
            {
                "id": "bns_5",
                "title": "The Limbic System",
                "type": "quiz",
                "question": "The amygdala is a brain structure most closely associated with:",
                "options": [
                    "Language comprehension",
                    "Processing and responding to fear and other emotions",
                    "Regulating body temperature",
                    "Coordinating voluntary movement",
                ],
                "answer": "b",
                "hints": [
                    "This almond-shaped structure is part of the limbic system — the emotional brain.",
                    "It's especially active when you perceive threats.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "The amygdala is an almond-shaped structure in the limbic system critical for processing emotions, especially fear. It triggers the fight-or-flight response before your conscious mind even registers the threat. The limbic system also includes the hippocampus (memory formation), hypothalamus (hunger, thirst, body temperature), and thalamus (sensory relay station).",
                "is_boss": False,
                "flavor": "ARIA makes a sudden loud noise. Your heart rate spikes. 'That was your amygdala,' she says. 'It reacted before your cortex even knew what happened. Speed over accuracy — that's how you survive.'",
            },
            {
                "id": "bns_6",
                "title": "Brain Plasticity",
                "type": "quiz",
                "question": "Neuroplasticity refers to the brain's ability to:",
                "options": [
                    "Grow new skull tissue after injury",
                    "Reorganize itself by forming new neural connections throughout life",
                    "Only develop during the first five years of life",
                    "Replace damaged neurons with identical copies",
                ],
                "answer": "b",
                "hints": [
                    "The brain is not hardwired — it adapts and reorganizes based on experience.",
                    "London taxi drivers have been shown to have larger hippocampi from years of navigation practice.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Neuroplasticity is the brain's lifelong ability to reorganize itself by forming new neural connections. It's how we learn, how we recover from brain injuries, and why practice changes the brain. London taxi drivers develop enlarged hippocampi from years of spatial navigation. Musicians develop thicker cortex in motor and auditory areas. The brain you have today is physically different from the one you had a year ago.",
                "is_boss": False,
                "flavor": "ARIA shows two brain scans side by side — before and after someone learned to juggle. New connections glow where there were none. 'The brain isn't a fixed machine,' she says. 'It's a living, changing network.'",
            },
            {
                "id": "bns_7",
                "title": "The Autonomic Nervous System",
                "type": "text",
                "question": "Explain the difference between the sympathetic and parasympathetic divisions of the autonomic nervous system. Give a specific real-life example showing how they work in opposition.",
                "options": [],
                "answer": "A strong answer explains that the sympathetic nervous system activates the 'fight-or-flight' response (increases heart rate, dilates pupils, inhibits digestion, releases adrenaline) while the parasympathetic nervous system activates the 'rest-and-digest' response (slows heart rate, constricts pupils, stimulates digestion). Example: when you hear a sudden loud noise, the sympathetic system spikes your heart rate and floods you with adrenaline; once you realize it was just a door slamming, the parasympathetic system gradually calms you back down.",
                "hints": [
                    "Sympathetic = accelerator pedal. Parasympathetic = brake pedal.",
                    "Think fight-or-flight vs. rest-and-digest.",
                ],
                "xp": 40,
                "difficulty": "medium",
                "lesson": "The autonomic nervous system operates automatically, controlling heart rate, digestion, breathing, and other involuntary functions. Its sympathetic division activates during stress (fight-or-flight: increased heart rate, dilated pupils, suspended digestion). Its parasympathetic division calms the body (rest-and-digest: slower heart rate, activated digestion). They work in opposition like an accelerator and brake, maintaining physiological balance.",
                "is_boss": False,
                "flavor": "ARIA projects two systems running in parallel — one red, one blue. 'Gas pedal, brake pedal,' she says. 'Your body is constantly balancing between them. You never notice until one takes over.'",
            },
            {
                "id": "bns_boss",
                "title": "BOSS: The Neural Architecture Test",
                "type": "quiz",
                "question": "A patient suffers a stroke that damages their left hemisphere Broca's area. They can understand everything said to them, but struggle to produce fluent speech. Meanwhile, a second patient with damage to the right parietal lobe neglects the entire left side of their visual field. These cases BEST illustrate which principle of brain organization?",
                "options": [
                    "The brain operates as a single, undifferentiated unit",
                    "Localization of function — specific brain areas handle specific tasks, and lateralization means the two hemispheres have some specialized roles",
                    "All brain damage produces the same symptoms",
                    "Brain damage is always permanent and cannot be compensated for",
                ],
                "answer": "b",
                "hints": [
                    "Different areas damaged = different symptoms. What does that tell you about brain organization?",
                    "Left hemisphere damage affecting speech vs. right hemisphere damage affecting spatial awareness — that's lateralization.",
                ],
                "xp": 60,
                "difficulty": "boss",
                "is_boss": True,
                "lesson": "These cases illustrate two key principles: localization of function (specific brain areas perform specific tasks — Broca's area for speech production, parietal lobe for spatial awareness) and lateralization (the left hemisphere is typically dominant for language, the right for spatial processing). Brain damage creates predictable deficits based on the location and side of the injury, which is how neuroscientists mapped brain functions before modern imaging.",
                "flavor": "ARIA projects two patients' brain scans. Different regions damaged, different symptoms. 'The brain is not a homogeneous mass,' she says. 'It's an orchestra. Damage one section, and that instrument goes silent — but the rest keep playing.'",
            },
        ],
    },

    # ── Zone 4: Sensation & Perception ────────────────────────────────
    "sensation_perception": {
        "id": "sensation_perception",
        "name": "The Perception Chamber",
        "description": "How raw sensory data becomes meaningful experience",
        "level_required": 1,
        "challenges": [
            {
                "id": "sp_1",
                "title": "Sensation vs. Perception",
                "type": "quiz",
                "question": "The key difference between sensation and perception is:",
                "options": [
                    "Sensation occurs in the brain; perception occurs in the sense organs",
                    "Sensation is the detection of raw physical energy by sense organs; perception is the brain's interpretation and organization of that sensory input",
                    "They are two words for the same process",
                    "Perception happens first, then sensation",
                ],
                "answer": "b",
                "hints": [
                    "Sensation = raw data in. Perception = meaning applied.",
                    "Your eyes detect wavelengths of light (sensation). Your brain sees a face (perception).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Sensation is the process by which sensory receptors detect physical energy (light, sound, pressure, chemicals) and convert it to neural signals. Perception is the brain's process of organizing and interpreting those signals into meaningful experience. You sense wavelengths of light; you perceive colors. You sense pressure waves; you perceive music. The gap between the two is where psychology gets interesting.",
                "is_boss": False,
                "flavor": "ARIA projects raw visual data — millions of photon readings — next to what you actually 'see.' The difference is staggering. 'Your brain is doing an enormous amount of work between input and experience,' she says.",
            },
            {
                "id": "sp_2",
                "title": "Absolute Threshold",
                "type": "quiz",
                "question": "The absolute threshold is defined as the minimum amount of stimulation needed to:",
                "options": [
                    "Cause pain in a sensory organ",
                    "Detect a stimulus 50% of the time",
                    "Detect a stimulus 100% of the time",
                    "Distinguish between two different stimuli",
                ],
                "answer": "b",
                "hints": [
                    "It's not 100% — that would be too strict. Detection is probabilistic.",
                    "The threshold is where you go from 'I can't detect it' to 'I can detect it about half the time.'",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "The absolute threshold is the minimum intensity of a stimulus that can be detected 50% of the time. For example, a candle flame can be seen 30 miles away on a clear dark night — that's roughly the absolute threshold for vision. The 50% criterion acknowledges that detection isn't a sharp line; it's a gradual transition from 'never noticed' to 'always noticed.'",
                "is_boss": False,
                "flavor": "ARIA dims a light to almost nothing. 'Can you see it?' she asks. 'Sometimes yes, sometimes no — that boundary is what we're measuring.'",
            },
            {
                "id": "sp_3",
                "title": "Signal Detection Theory",
                "type": "quiz",
                "question": "Signal detection theory argues that detecting a stimulus depends not only on the stimulus intensity but also on:",
                "options": [
                    "The time of day",
                    "The observer's psychological state, expectations, and the consequences of being right or wrong",
                    "Whether the observer has eaten recently",
                    "The observer's age only",
                ],
                "answer": "b",
                "hints": [
                    "A radiologist looking for tumors is motivated differently than someone casually glancing at images.",
                    "Your expectations and what's at stake change your willingness to say 'I detect it.'",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Signal detection theory (SDT) recognizes that detection isn't purely about stimulus strength — it's also about the observer's decision criteria. A radiologist who misses a tumor faces catastrophic consequences, so they set a low threshold (calling 'yes' more often, accepting more false alarms to avoid misses). SDT separates sensitivity (ability to detect) from bias (willingness to report detection).",
                "is_boss": False,
                "flavor": "ARIA shows the same ambiguous X-ray to two doctors. One calls it suspicious, one calls it clear. 'Same image,' she says. 'Different stakes, different criteria, different answers.'",
            },
            {
                "id": "sp_4",
                "title": "Gestalt Principles",
                "type": "quiz",
                "question": "The Gestalt principle of 'closure' explains why we:",
                "options": [
                    "Prefer to look at closed doors rather than open ones",
                    "Perceive complete shapes even when parts are missing — our brain fills in the gaps",
                    "Feel satisfied when we finish a task",
                    "Close our eyes when we're scared",
                ],
                "answer": "b",
                "hints": [
                    "Think about how you can read the word 'SALE' even when parts of the letters are obscured.",
                    "Your brain COMPLETES incomplete figures automatically.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Gestalt psychology identified principles describing how the brain organizes sensory input into coherent wholes. Closure: we complete incomplete figures. Proximity: we group nearby objects together. Similarity: we group similar objects. Continuity: we perceive smooth, continuous patterns. Figure-ground: we separate objects from backgrounds. These principles are automatic and universal — your brain cannot help but organize.",
                "is_boss": False,
                "flavor": "ARIA draws three-quarters of a circle on the display. You see a complete circle with a gap. 'You perceive something that isn't there,' she says. 'Your brain added the missing piece. It always does.'",
            },
            {
                "id": "sp_5",
                "title": "Depth Perception",
                "type": "quiz",
                "question": "Binocular disparity — the slight difference between the images received by each eye — is a cue used for:",
                "options": [
                    "Color perception",
                    "Depth perception — judging how far away objects are",
                    "Detecting motion",
                    "Reading fine print",
                ],
                "answer": "b",
                "hints": [
                    "Hold a finger in front of your face and alternate closing each eye — the finger appears to jump. That's binocular disparity.",
                    "The brain computes depth from the DIFFERENCE between two slightly offset images.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Binocular disparity is a binocular depth cue: because your eyes are slightly apart, each receives a slightly different image. The brain computes the difference to estimate distance — objects closer to you produce greater disparity. This is why 3D movies and VR headsets work. Monocular cues (usable with one eye) include relative size, linear perspective, overlap, and texture gradient.",
                "is_boss": False,
                "flavor": "ARIA has you close one eye, then the other. The world flattens slightly. 'Two perspectives,' she says. 'From the gap between them, your brain calculates depth. Simple geometry, executed unconsciously.'",
            },
            {
                "id": "sp_6",
                "title": "Perceptual Constancy",
                "type": "quiz",
                "question": "A door appears to change shape as it opens — from a rectangle to a trapezoid — yet you perceive it as always being a rectangle. This is an example of:",
                "options": [
                    "Change blindness",
                    "Shape constancy — perceiving objects as maintaining their shape despite changes in the retinal image",
                    "An optical illusion",
                    "The Stroop effect",
                ],
                "answer": "b",
                "hints": [
                    "The image on your retina DOES change. But your perception doesn't.",
                    "Your brain uses context and experience to maintain a stable perception of the object.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Perceptual constancy is the brain's ability to perceive objects as unchanging despite variations in sensory input. Shape constancy: a door is always rectangular even when viewed at an angle. Size constancy: a person walking away doesn't seem to shrink. Color constancy: a white shirt still looks white in dim lighting. Without these constancies, the world would be chaotic — objects would appear to morph constantly.",
                "is_boss": False,
                "flavor": "ARIA swings a virtual door open and shut. 'The retinal image changes every degree,' she says. 'But you never once thought the door changed shape. That's your brain's constancy systems — invisible, essential, always running.'",
            },
            {
                "id": "sp_7",
                "title": "Selective Attention",
                "type": "text",
                "question": "Describe the cocktail party effect and explain what it reveals about how attention works. Why is this relevant to real-world situations like distracted driving?",
                "options": [],
                "answer": "A strong answer describes the cocktail party effect (the ability to focus on one conversation in a noisy room while filtering out others, AND the ability to suddenly notice your name being spoken in an unattended conversation), explains that it demonstrates both selective attention (filtering) and preattentive monitoring (your brain processes unattended information at a basic level), and connects to distracted driving (drivers on phones may miss critical stimuli because attention is a limited resource — even 'hearing' everything doesn't mean you're processing it).",
                "hints": [
                    "You can focus on one voice in a crowded room. But if someone across the room says your name, you notice. What does that tell you?",
                    "Your brain is processing unattended information at SOME level, even when you're not aware of it.",
                ],
                "xp": 40,
                "difficulty": "medium",
                "lesson": "The cocktail party effect shows that attention is both selective (you can focus on one conversation and filter others) and partially automatic (your name breaks through the filter, proving unattended information is processed at a basic level). This has real implications: drivers talking on phones show 'inattentional blindness' — they look at the road but don't process what they see. Attention is a limited resource, and dividing it degrades performance even when you don't realize it.",
                "is_boss": False,
                "flavor": "ARIA fills the room with overlapping conversations. One voice stands out clearly — the one you're focused on. Then someone across the room says your name. Your head turns. 'You weren't listening,' ARIA says, 'but you were.'",
            },
            {
                "id": "sp_boss",
                "title": "BOSS: The Illusion Gauntlet",
                "type": "quiz",
                "question": "The Müller-Lyer illusion causes two lines of equal length to appear different because of arrow-like fins at their ends. Research shows this illusion is WEAKER in people from cultures without 'carpentered environments' (buildings with straight lines and right angles). This finding BEST supports which claim about perception?",
                "options": [
                    "Perception is purely determined by genetics",
                    "Optical illusions are tricks that work on everyone equally",
                    "Perception is not purely bottom-up — it is shaped by experience, culture, and learned expectations about the environment",
                    "People from non-Western cultures have better eyesight",
                ],
                "answer": "c",
                "hints": [
                    "If the illusion were purely about the eye, it would affect everyone identically.",
                    "Growing up surrounded by buildings and straight edges may train your brain to interpret certain angle patterns as depth cues.",
                ],
                "xp": 60,
                "difficulty": "boss",
                "is_boss": True,
                "lesson": "The cross-cultural variation in the Müller-Lyer illusion is powerful evidence that perception is not just bottom-up (driven by raw sensory data) but also top-down (shaped by experience and expectations). People raised in environments full of straight lines and right angles unconsciously interpret the arrow fins as depth cues, making the lines appear different lengths. Perception is a construction — and culture is one of the architects.",
                "flavor": "ARIA projects the two lines. They look obviously different. Then she reveals they're identical. 'Your eyes reported the truth,' she says. 'Your brain overruled them — based on a lifetime of experience in a world of walls and corners.'",
            },
        ],
    },

    # ── Zone 5: States of Consciousness ───────────────────────────────
    "states_of_consciousness": {
        "id": "states_of_consciousness",
        "name": "The Consciousness Spectrum",
        "description": "Sleep, dreams, hypnosis, psychoactive substances, and the nature of awareness",
        "level_required": 1,
        "challenges": [
            {
                "id": "soc_1",
                "title": "What Is Consciousness?",
                "type": "quiz",
                "question": "Consciousness is best described as:",
                "options": [
                    "Being awake versus being asleep",
                    "Our awareness of ourselves and our environment, existing on a continuum from full alertness to deep unconsciousness",
                    "A uniquely human trait that no other animal possesses",
                    "Something that can only be studied through brain scans",
                ],
                "answer": "b",
                "hints": [
                    "It's not an on/off switch — there are many states between fully alert and deeply unconscious.",
                    "Think about daydreaming, meditation, anesthesia — different LEVELS of awareness.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Consciousness is our subjective awareness of ourselves and our environment. It exists on a continuum: fully alert → relaxed → daydreaming → drowsy → light sleep → deep sleep → coma. It's not binary. Psychologists study it by examining its altered states — sleep, dreams, hypnosis, meditation, and the effects of psychoactive substances — because understanding when consciousness changes reveals what it IS.",
                "is_boss": False,
                "flavor": "ARIA dims the neural lattice gradually. 'Consciousness isn't a light switch,' she says. 'It's a dimmer. And right now, yours is set to one very specific level. But it shifts — constantly.'",
            },
            {
                "id": "soc_2",
                "title": "Sleep Stages",
                "type": "quiz",
                "question": "During which stage of sleep do the most vivid dreams typically occur?",
                "options": [
                    "Stage 1 (light sleep)",
                    "Stage 2 (sleep spindles)",
                    "Stage 3 (deep/slow-wave sleep)",
                    "REM (Rapid Eye Movement) sleep",
                ],
                "answer": "d",
                "hints": [
                    "The eyes are moving rapidly behind closed lids. The brain is almost as active as when awake.",
                    "If you're woken during THIS stage, you'll almost certainly report a vivid dream.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Sleep cycles through stages roughly every 90 minutes. Stage 1: light sleep, easily awakened. Stage 2: deeper, with sleep spindles (bursts of brain activity). Stage 3: deep slow-wave sleep — hardest to wake, critical for physical restoration. REM: rapid eye movement, brain highly active, vivid dreaming, muscles paralyzed (atonia). REM increases in later cycles — you dream more toward morning.",
                "is_boss": False,
                "flavor": "ARIA displays the EEG traces — slow delta waves in deep sleep, fast jagged waves in REM. 'Your brain never stops working,' she says. 'It just changes what it's working ON.'",
            },
            {
                "id": "soc_3",
                "title": "Why We Sleep",
                "type": "quiz",
                "question": "Research consistently shows that sleep deprivation impairs which cognitive function MOST severely?",
                "options": [
                    "Long-term memory of childhood events",
                    "The ability to taste food",
                    "Executive functions: decision-making, attention, impulse control, and emotional regulation",
                    "The ability to recognize faces",
                ],
                "answer": "c",
                "hints": [
                    "Think about what happens when you haven't slept — you make poor decisions, can't focus, and get emotionally reactive.",
                    "The prefrontal cortex is especially vulnerable to sleep deprivation.",
                ],
                "xp": 30,
                "difficulty": "easy",
                "lesson": "Sleep deprivation most severely impairs executive functions — the higher-order abilities controlled by the prefrontal cortex: attention, decision-making, impulse control, and emotional regulation. After 24 hours without sleep, cognitive performance is comparable to being legally drunk. Sleep also plays critical roles in memory consolidation (moving information from short-term to long-term storage) and physical restoration (immune function, growth hormone release).",
                "is_boss": False,
                "flavor": "ARIA shows performance data from a sleep-deprivation study. After 24 hours, the line drops like a cliff. 'Your prefrontal cortex is the first thing to go,' she says. 'Which is unfortunate, because it's the part that tells you you're impaired.'",
            },
            {
                "id": "soc_4",
                "title": "Dreams and Their Theories",
                "type": "quiz",
                "question": "Freud proposed that dreams are the 'royal road to the unconscious' and contain hidden symbolic meaning. Modern neuroscience's activation-synthesis theory instead proposes that dreams are:",
                "options": [
                    "Meaningful messages from a spiritual realm",
                    "The brain's attempt to make sense of random neural activity during REM sleep",
                    "Perfect replays of the day's events",
                    "Completely meaningless and should be ignored",
                ],
                "answer": "b",
                "hints": [
                    "During REM, the brainstem sends random signals. The cortex tries to create a coherent narrative from them.",
                    "It's the brain doing what it always does — making sense of input — even when the input is random.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The activation-synthesis hypothesis (Hobson & McCarley, 1977) proposes that during REM sleep, the brainstem generates random neural activity, and the cortex tries to synthesize a coherent story from it — that story is the dream. This challenges Freud's view that dreams contain disguised unconscious wishes. Modern theories also suggest dreams play roles in memory consolidation, emotional processing, and threat simulation.",
                "is_boss": False,
                "flavor": "ARIA projects a chaotic storm of neural firing. Then the cortex activates and suddenly there's a narrative — fragmented, bizarre, but structured. 'Random noise in, story out,' she says. 'The brain can't help itself.'",
            },
            {
                "id": "soc_5",
                "title": "Hypnosis",
                "type": "quiz",
                "question": "Scientific research on hypnosis has shown that hypnotized individuals:",
                "options": [
                    "Are in a trance-like state where they lose all free will and can be made to do anything",
                    "Show genuine changes in perception, pain processing, and memory — but cannot be forced to act against their core values or beliefs",
                    "Are always faking their responses to please the hypnotist",
                    "Enter the same state as deep sleep",
                ],
                "answer": "b",
                "hints": [
                    "Brain imaging shows real changes during hypnosis — it's not just acting.",
                    "But stage hypnosis exaggerates the loss of control. People can't be made to do things they find truly objectionable.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "Hypnosis produces real, measurable changes in brain activity — particularly in regions involved in attention, pain processing, and self-monitoring. Hypnotized individuals can experience genuine pain reduction, altered perception, and enhanced focus. However, they cannot be forced to act against deeply held values. Hypnotic suggestibility varies widely: about 15% of people are highly hypnotizable, 15% are resistant, and most fall in between.",
                "is_boss": False,
                "flavor": "ARIA shows a brain scan during hypnosis — the pain-processing regions dimming in real time. 'It's not theater,' she says. 'The brain IS processing pain differently. The question is: how?'",
            },
            {
                "id": "soc_6",
                "title": "Psychoactive Substances",
                "type": "quiz",
                "question": "Psychoactive drugs alter consciousness by affecting neurotransmitter systems. A drug that mimics a neurotransmitter and activates its receptors is called:",
                "options": [
                    "An antagonist",
                    "An agonist",
                    "A reuptake inhibitor",
                    "A hallucinogen",
                ],
                "answer": "b",
                "hints": [
                    "Think of it as a key that fits the lock and OPENS it — the drug activates the receptor.",
                    "An antagonist does the opposite — it blocks the receptor.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "An agonist is a drug that mimics a neurotransmitter and activates its receptor (like morphine mimicking endorphins). An antagonist blocks a receptor, preventing the natural neurotransmitter from acting. A reuptake inhibitor blocks the reabsorption of a neurotransmitter, increasing its availability in the synapse (like SSRIs with serotonin). Understanding these mechanisms explains how every psychoactive drug — from caffeine to antidepressants — alters consciousness.",
                "is_boss": False,
                "flavor": "ARIA zooms into a synapse. A molecule shaped exactly like dopamine slides into a receptor and activates it. 'The receptor can't tell the difference,' she says. 'As far as the neuron is concerned, the drug IS the neurotransmitter.'",
            },
            {
                "id": "soc_7",
                "title": "Meditation and Flow",
                "type": "text",
                "question": "Compare meditation and flow states as altered states of consciousness. What do they have in common, and how do they differ in terms of attention, self-awareness, and brain activity?",
                "options": [],
                "answer": "A strong answer notes that both involve focused attention and altered time perception, but they differ: meditation typically involves INWARD focus, heightened meta-awareness (awareness of awareness), and decreased default mode network activity (less mind-wandering). Flow states involve OUTWARD focus on a challenging task, DECREASED self-awareness (you 'lose yourself'), and high engagement of attention networks with reduced activity in self-referential brain regions. Both are associated with well-being but through different mechanisms.",
                "hints": [
                    "In meditation, you're AWARE you're aware. In flow, you LOSE self-awareness.",
                    "One turns attention inward; the other directs it fully toward an external task.",
                ],
                "xp": 40,
                "difficulty": "medium",
                "lesson": "Meditation and flow are both altered states of consciousness associated with well-being, but they differ meaningfully. Meditation: inward focus, heightened meta-awareness, reduced default mode network activity (less rumination). Flow: outward focus on a challenge-skill matched task, reduced self-awareness (ego dissolution), full engagement of attention networks. Both alter time perception and reduce self-critical thinking. Research suggests regular practice of either can produce lasting changes in brain structure and function.",
                "is_boss": False,
                "flavor": "ARIA splits the display — a meditator's brain on one side, a musician in flow on the other. Different patterns, both extraordinary. 'Two paths to transcending ordinary consciousness,' she says. 'One goes inward. The other goes so far outward that the self disappears.'",
            },
            {
                "id": "soc_boss",
                "title": "BOSS: The Consciousness Synthesis",
                "type": "quiz",
                "question": "A patient under general anesthesia shows no behavioral responses and will have no memory of the surgery. Yet brain monitoring reveals occasional bursts of organized neural activity. A sleep researcher notes that similar 'islands of awareness' occur during certain sleep stages. A philosopher argues this shows consciousness may be a spectrum, not a binary state. Which conclusion is BEST supported by this evidence?",
                "options": [
                    "The patient is definitely conscious and suffering during surgery",
                    "Consciousness is purely a product of behavior — if they don't respond, they're not conscious",
                    "Consciousness exists on a continuum, and our current tools may not fully capture the boundary between conscious and unconscious states",
                    "Anesthesia doesn't work and should be abandoned",
                ],
                "answer": "c",
                "hints": [
                    "Organized neural activity doesn't guarantee subjective experience — but it doesn't rule it out either.",
                    "If consciousness were truly binary, you wouldn't see these 'islands.' The boundary is blurrier than we thought.",
                ],
                "xp": 60,
                "difficulty": "boss",
                "is_boss": True,
                "lesson": "This scenario illustrates one of the deepest problems in consciousness research: the gap between neural activity and subjective experience. Organized brain activity during anesthesia suggests consciousness isn't a clean on/off switch. Similar findings in sleep, coma, and vegetative states have challenged the binary model. Modern consciousness science increasingly views awareness as a continuum — and acknowledges that our tools for detecting it are still imperfect. The 'hard problem' of consciousness — why and how physical processes produce subjective experience — remains unsolved.",
                "flavor": "ARIA pauses. The neural lattice flickers — islands of light in a dark field. 'We can measure the brain,' she says. 'We can observe behavior. But consciousness itself — the experience of being aware — that's the one thing we still can't directly detect in anyone but ourselves.'",
            },
        ],
    },
}
