"""
zones.py — Transport zones and challenges.

Teaches Chinese transportation vocabulary, buying tickets, asking directions,
navigating stations, and travel conversations. Guided by Long Long the dragon.
"""

ZONE_ORDER = [
    "transportation_words",
    "buying_tickets",
    "asking_directions",
    "at_the_station",
    "travel_conversations",
]

ZONES = {
    # ── Zone 1: Transportation Words ──────────────────────────────────
    "transportation_words": {
        "id": "transportation_words",
        "name": "Transportation Words",
        "description": "Essential transportation vocabulary in Chinese",
        "level_required": 1,
        "challenges": [
            {
                "id": "gonggong_qiche_bus",
                "title": "The People's Ride",
                "type": "quiz",
                "question": "What does 'gong gong qi che' (公共汽车) mean?",
                "options": ["Taxi", "Bus", "Train", "Bicycle"],
                "answer": "b",
                "hints": [
                    "gong gong (公共) means 'public' and qi che (汽车) means 'vehicle'.",
                    "This is the vehicle that carries many people along a fixed route.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "公共汽车 (gong gong qi che) means 'bus' (literally 'public vehicle'). 公共 (gong gong) = public, 汽车 (qi che) = automobile/car. In daily speech, many people shorten it to 公交车 (gong jiao che). 坐公共汽车 (zuo gong gong qi che) = to ride the bus.",
                "is_boss": False,
                "flavor": "Long Long watches a crowded bus rumble past the castle gate. 'Gong gong qi che -- everyone rides together!'",
            },
            {
                "id": "ditie_subway",
                "title": "The Underground Dragon",
                "type": "quiz",
                "question": "How do you say 'subway / metro' in Chinese?",
                "options": ["huo che (火车)", "di tie (地铁)", "fei ji (飞机)", "qi che (汽车)"],
                "answer": "b",
                "hints": [
                    "di (地) means 'ground/earth' and tie (铁) means 'iron'.",
                    "Think of an iron road beneath the ground.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "地铁 (di tie) means 'subway/metro' (literally 'ground iron'). 地 (di) = ground/earth, 铁 (tie) = iron. 坐地铁 (zuo di tie) = to take the subway. 地铁站 (di tie zhan) = subway station. Major Chinese cities like Beijing, Shanghai, and Guangzhou have massive subway networks.",
                "is_boss": False,
                "flavor": "Long Long peers into a tunnel entrance. 'Di tie -- iron roads beneath the earth!'",
            },
            {
                "id": "chuzuche_taxi",
                "title": "Hail a Ride",
                "type": "quiz",
                "question": "What does 'chu zu che' (出租车) mean?",
                "options": ["Bus", "Bicycle", "Taxi", "Train"],
                "answer": "c",
                "hints": [
                    "chu zu (出租) means 'for rent' and che (车) means 'vehicle'.",
                    "This is a car you hire for a personal trip.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "出租车 (chu zu che) means 'taxi' (literally 'rental vehicle'). 出租 (chu zu) = for rent, 车 (che) = vehicle. 打车 (da che) or 叫车 (jiao che) = to call/hail a taxi. In China, ride-hailing apps like DiDi (滴滴) have largely replaced traditional taxis.",
                "is_boss": False,
                "flavor": "Long Long raises a claw to hail a carriage. 'Chu zu che! Take me to the market!'",
            },
            {
                "id": "huoche_train",
                "title": "The Fire Vehicle",
                "type": "quiz",
                "question": "What does 'huo che' (火车) literally mean?",
                "options": ["Water vehicle", "Fire vehicle", "Wind vehicle", "Iron vehicle"],
                "answer": "b",
                "hints": [
                    "huo (火) means 'fire' and che (车) means 'vehicle'.",
                    "Early trains were powered by steam and fire.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "火车 (huo che) means 'train' (literally 'fire vehicle'), named for the steam engines of old. 火 (huo) = fire, 车 (che) = vehicle. 高铁 (gao tie) = high-speed rail (literally 'high iron'). China's high-speed rail network is the world's largest. 火车站 (huo che zhan) = train station.",
                "is_boss": False,
                "flavor": "Long Long breathes a plume of steam. 'Huo che -- fire and iron, like a dragon on rails!'",
            },
            {
                "id": "feiji_airplane",
                "title": "The Flying Machine",
                "type": "quiz",
                "question": "How do you say 'airplane' in Chinese?",
                "options": ["di tie (地铁)", "huo che (火车)", "fei ji (飞机)", "lun chuan (轮船)"],
                "answer": "c",
                "hints": [
                    "fei (飞) means 'to fly' and ji (机) means 'machine'.",
                    "This vehicle soars through the sky.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "飞机 (fei ji) means 'airplane' (literally 'flying machine'). 飞 (fei) = to fly, 机 (ji) = machine. 机场 (ji chang) = airport (machine field). 坐飞机 (zuo fei ji) = to take a plane. 航班 (hang ban) = flight number.",
                "is_boss": False,
                "flavor": "Long Long spreads his wings. 'Fei ji -- humans learned to fly too, just with more metal!'",
            },
            {
                "id": "zixingche_bicycle",
                "title": "Two Wheels",
                "type": "quiz",
                "question": "What does 'zi xing che' (自行车) mean?",
                "options": ["Motorcycle", "Bicycle", "Scooter", "Tricycle"],
                "answer": "b",
                "hints": [
                    "zi xing (自行) means 'self-propelled' and che (车) means 'vehicle'.",
                    "You pedal this vehicle yourself.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "自行车 (zi xing che) means 'bicycle' (literally 'self-propelled vehicle'). 自行 (zi xing) = self-moving, 车 (che) = vehicle. 骑自行车 (qi zi xing che) = to ride a bicycle. Note: for bicycles you use 骑 (qi, to ride/straddle), not 坐 (zuo, to sit) like buses and trains.",
                "is_boss": False,
                "flavor": "Long Long tries to balance on a bicycle. 'Zi xing che -- harder than flying!'",
            },
            {
                "id": "transport_text_review",
                "title": "Transport Recall",
                "type": "text",
                "question": "Type the pinyin for 'subway' (two syllables, no tones):",
                "options": [],
                "answer": "di tie",
                "hints": [
                    "The first word means 'ground' or 'earth'.",
                    "The second word means 'iron'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "地铁 (di tie) = subway. Remember: 公共汽车 (gong gong qi che) bus, 地铁 (di tie) subway, 出租车 (chu zu che) taxi, 火车 (huo che) train, 飞机 (fei ji) airplane, 自行车 (zi xing che) bicycle.",
                "is_boss": False,
                "flavor": "Long Long tests your memory. 'Can you recall the iron beneath the ground?'",
            },
            {
                "id": "transport_boss",
                "title": "Transport Master",
                "type": "quiz",
                "question": "Which sentence means 'I take the subway to work'?",
                "options": [
                    "wo zuo di tie qu shang ban (我坐地铁去上班)",
                    "wo zuo fei ji qu shang ban (我坐飞机去上班)",
                    "wo qi zi xing che qu xue xiao (我骑自行车去学校)",
                    "wo da che qu ji chang (我打车去机场)",
                ],
                "answer": "a",
                "hints": [
                    "zuo di tie = take the subway, qu = to go, shang ban = go to work.",
                    "Which option mentions both subway and work?",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "我坐地铁去上班 (wo zuo di tie qu shang ban) = 'I take the subway to go to work.' Pattern: 我 (I) + 坐 (sit/ride) + [transport] + 去 (go to) + [destination/activity]. 上班 (shang ban) = go to work. This pattern works for any transport: 坐火车去北京 = take the train to Beijing.",
                "is_boss": True,
                "flavor": "Long Long roars with pride. 'You know every way to travel!'",
            },
        ],
    },

    # ── Zone 2: Buying Tickets ────────────────────────────────────────
    "buying_tickets": {
        "id": "buying_tickets",
        "name": "Buying Tickets",
        "description": "Learn to buy tickets and handle fares in Chinese",
        "level_required": 3,
        "challenges": [
            {
                "id": "piao_ticket",
                "title": "The Golden Ticket",
                "type": "quiz",
                "question": "What does 'piao' (票) mean?",
                "options": ["Money", "Ticket", "Station", "Seat"],
                "answer": "b",
                "hints": [
                    "You need this piece of paper to board a train or enter a theater.",
                    "It rhymes with the English word 'meow' (sort of).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "票 (piao, fourth tone) means 'ticket'. 买票 (mai piao) = buy a ticket. 火车票 (huo che piao) = train ticket. 机票 (ji piao) = plane ticket. 门票 (men piao) = entrance ticket. In China, you can buy most tickets through apps like 12306 (trains) or via WeChat.",
                "is_boss": False,
                "flavor": "Long Long holds up a golden ticket. 'Piao -- your pass to adventure!'",
            },
            {
                "id": "duoshao_qian_howmuch",
                "title": "The Price of Travel",
                "type": "quiz",
                "question": "How do you ask 'How much money?' in Chinese?",
                "options": [
                    "zhe shi shen me (这是什么)",
                    "duo shao qian (多少钱)",
                    "ji dian le (几点了)",
                    "zai na li (在哪里)",
                ],
                "answer": "b",
                "hints": [
                    "duo shao (多少) means 'how much/how many'.",
                    "qian (钱) means 'money'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "多少钱 (duo shao qian) means 'how much money?' 多少 (duo shao) = how much/how many, 钱 (qian) = money. 这个多少钱? (zhe ge duo shao qian?) = How much is this? 票多少钱? (piao duo shao qian?) = How much is the ticket? 块 (kuai) is the spoken word for yuan (元), China's currency.",
                "is_boss": False,
                "flavor": "Long Long inspects a price board. 'Duo shao qian -- always ask before you pay!'",
            },
            {
                "id": "wangfan_roundtrip",
                "title": "There and Back Again",
                "type": "quiz",
                "question": "What does 'wang fan' (往返) mean?",
                "options": ["One-way", "Round trip", "Express", "First class"],
                "answer": "b",
                "hints": [
                    "wang (往) means 'to go toward' and fan (返) means 'to return'.",
                    "This means going somewhere AND coming back.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "往返 (wang fan) means 'round trip' (literally 'go and return'). 往 (wang) = toward/go, 返 (fan) = return. 往返票 (wang fan piao) = round-trip ticket. The opposite is 单程 (dan cheng) = one-way. 往返票比两张单程票便宜 = Round-trip tickets are cheaper than two one-way tickets.",
                "is_boss": False,
                "flavor": "Long Long traces a circle in the air. 'Wang fan -- a journey there and back!'",
            },
            {
                "id": "dancheng_oneway",
                "title": "One Direction",
                "type": "quiz",
                "question": "How do you say 'one-way (trip)' in Chinese?",
                "options": ["wang fan (往返)", "dan cheng (单程)", "zhi da (直达)", "kuai che (快车)"],
                "answer": "b",
                "hints": [
                    "dan (单) means 'single' and cheng (程) means 'journey/trip'.",
                    "This is the opposite of round trip.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "单程 (dan cheng) means 'one-way' (literally 'single journey'). 单 (dan) = single, 程 (cheng) = journey/distance. 单程票 (dan cheng piao) = one-way ticket. 我要一张单程票 (wo yao yi zhang dan cheng piao) = I want one one-way ticket. 张 (zhang) is the measure word for flat things like tickets.",
                "is_boss": False,
                "flavor": "Long Long points forward. 'Dan cheng -- no looking back!'",
            },
            {
                "id": "mai_piao_buy_ticket",
                "title": "Making the Purchase",
                "type": "quiz",
                "question": "What does 'wo yao mai yi zhang piao' (我要买一张票) mean?",
                "options": [
                    "I want to buy one ticket",
                    "Where can I buy a ticket",
                    "How much is one ticket",
                    "I already have a ticket",
                ],
                "answer": "a",
                "hints": [
                    "wo yao (我要) = I want, mai (买) = to buy.",
                    "yi zhang (一张) = one (flat object), piao (票) = ticket.",
                ],
                "xp": 25,
                "difficulty": "medium",
                "lesson": "我要买一张票 (wo yao mai yi zhang piao) = 'I want to buy one ticket.' 要 (yao) = want/need, 买 (mai, third tone) = to buy. Be careful: 买 (mai, third tone) = buy, but 卖 (mai, fourth tone) = sell! 张 (zhang) is the measure word for tickets, papers, and other flat objects.",
                "is_boss": False,
                "flavor": "Long Long approaches the ticket window. 'Wo yao mai yi zhang piao!'",
            },
            {
                "id": "zuowei_seat",
                "title": "Finding Your Seat",
                "type": "quiz",
                "question": "What does 'zuo wei' (座位) mean?",
                "options": ["Platform", "Seat", "Window", "Aisle"],
                "answer": "b",
                "hints": [
                    "zuo (座) relates to sitting and wei (位) means 'position'.",
                    "This is where you sit on a train or plane.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "座位 (zuo wei) means 'seat' (literally 'sitting position'). 靠窗座位 (kao chuang zuo wei) = window seat. 靠过道座位 (kao guo dao zuo wei) = aisle seat. 有座位吗? (you zuo wei ma?) = Are there seats available? On Chinese trains, you can choose 硬座 (ying zuo, hard seat) or 软座 (ruan zuo, soft seat).",
                "is_boss": False,
                "flavor": "Long Long squeezes into a seat. 'Zuo wei -- dragons need extra legroom!'",
            },
            {
                "id": "ticket_text_review",
                "title": "Ticket Recall",
                "type": "text",
                "question": "Type the pinyin for 'ticket' (one syllable, no tones):",
                "options": [],
                "answer": "piao",
                "hints": [
                    "It starts with 'p' and has the 'iao' final.",
                    "Sounds a bit like 'pyow'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "票 (piao) = ticket. Key ticket phrases: 买票 (mai piao) buy a ticket, 多少钱 (duo shao qian) how much, 往返 (wang fan) round trip, 单程 (dan cheng) one-way, 一张票 (yi zhang piao) one ticket.",
                "is_boss": False,
                "flavor": "Long Long quizzes you at the counter. 'Quick -- what do you need to board?'",
            },
            {
                "id": "ticket_boss",
                "title": "Ticket Counter Master",
                "type": "quiz",
                "question": "You want to buy a round-trip train ticket. Which sentence is correct?",
                "options": [
                    "wo yao yi zhang huo che wang fan piao (我要一张火车往返票)",
                    "wo yao yi zhang fei ji dan cheng piao (我要一张飞机单程票)",
                    "piao duo shao qian di tie (票多少钱地铁)",
                    "mai piao zai na li gong gong qi che (买票在哪里公共汽车)",
                ],
                "answer": "a",
                "hints": [
                    "huo che = train, wang fan = round trip, piao = ticket.",
                    "Look for the option that combines train + round trip + ticket.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "我要一张火车往返票 (wo yao yi zhang huo che wang fan piao) = 'I want one round-trip train ticket.' Pattern: 我要 (I want) + number + 张 (measure word) + [transport type] + [trip type] + 票 (ticket). You can swap parts: 飞机单程票 = one-way plane ticket.",
                "is_boss": True,
                "flavor": "Long Long stamps your ticket with approval. 'You can buy any ticket in China now!'",
            },
        ],
    },

    # ── Zone 3: Asking Directions ─────────────────────────────────────
    "asking_directions": {
        "id": "asking_directions",
        "name": "Asking Directions",
        "description": "Learn to ask for and understand directions in Chinese",
        "level_required": 5,
        "challenges": [
            {
                "id": "zenme_qu_howto",
                "title": "How Do I Get There?",
                "type": "quiz",
                "question": "What does 'zen me qu' (怎么去) mean?",
                "options": ["Where is it?", "How to get there?", "How far?", "Which way?"],
                "answer": "b",
                "hints": [
                    "zen me (怎么) means 'how' and qu (去) means 'to go'.",
                    "You're asking about the method of getting somewhere.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "怎么去 (zen me qu) means 'how to get there / how to go'. 怎么 (zen me) = how, 去 (qu) = to go. Full pattern: [place] + 怎么去? Example: 火车站怎么去? (huo che zhan zen me qu?) = How do I get to the train station? You can also say 去[place]怎么走? (qu ... zen me zou?) for the same meaning.",
                "is_boss": False,
                "flavor": "Long Long looks at a crossroads. 'Zen me qu -- which path leads to treasure?'",
            },
            {
                "id": "zai_nali_where",
                "title": "Where Is It?",
                "type": "quiz",
                "question": "How do you ask 'Where is the subway station?' in Chinese?",
                "options": [
                    "di tie zhan zai na li (地铁站在哪里)",
                    "di tie zhan duo yuan (地铁站多远)",
                    "di tie zhan ji dian kai (地铁站几点开)",
                    "di tie zhan duo shao qian (地铁站多少钱)",
                ],
                "answer": "a",
                "hints": [
                    "zai na li (在哪里) means 'is where / at where'.",
                    "Put the place first, then ask where it is.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "地铁站在哪里 (di tie zhan zai na li) = 'Where is the subway station?' Pattern: [place] + 在哪里 (zai na li)? 在 (zai) = at/in, 哪里 (na li) = where. This works for anything: 厕所在哪里? (ce suo zai na li?) = Where is the bathroom? 机场在哪里? (ji chang zai na li?) = Where is the airport?",
                "is_boss": False,
                "flavor": "Long Long scratches his head with a claw. 'Zai na li -- even dragons get lost!'",
            },
            {
                "id": "zuo_left",
                "title": "Turn Left",
                "type": "quiz",
                "question": "What does 'zuo zhuan' (左转) mean?",
                "options": ["Turn right", "Turn left", "Go straight", "Turn around"],
                "answer": "b",
                "hints": [
                    "zuo (左) means 'left' and zhuan (转) means 'to turn'.",
                    "Your left hand makes an 'L' shape.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "左转 (zuo zhuan) means 'turn left'. 左 (zuo) = left, 转 (zhuan) = to turn. 左边 (zuo bian) = left side. Be careful: 左 (zuo, left) and 右 (you, right) look similar! The opposite is 右转 (you zhuan) = turn right. 在路口左转 (zai lu kou zuo zhuan) = Turn left at the intersection.",
                "is_boss": False,
                "flavor": "Long Long extends his left wing. 'Zuo zhuan -- follow the left wing!'",
            },
            {
                "id": "you_right",
                "title": "Turn Right",
                "type": "quiz",
                "question": "What does 'you' (右) mean when giving directions?",
                "options": ["Left", "Right", "Front", "Back"],
                "answer": "b",
                "hints": [
                    "This is the opposite of zuo (左).",
                    "右 has a 'mouth' radical (口) at the top.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "右 (you, fourth tone) means 'right'. 右转 (you zhuan) = turn right. 右边 (you bian) = right side. Direction pairs: 左/右 (zuo/you) = left/right, 前/后 (qian/hou) = front/back, 上/下 (shang/xia) = up/down. 在你的右边 (zai ni de you bian) = on your right side.",
                "is_boss": False,
                "flavor": "Long Long extends his right wing. 'You -- the other way from zuo!'",
            },
            {
                "id": "zhi_zou_straight",
                "title": "Straight Ahead",
                "type": "quiz",
                "question": "How do you say 'go straight' in Chinese?",
                "options": ["zuo zhuan (左转)", "you zhuan (右转)", "zhi zou (直走)", "wang hui zou (往回走)"],
                "answer": "c",
                "hints": [
                    "zhi (直) means 'straight' and zou (走) means 'to walk/go'.",
                    "No turning involved -- just keep going forward.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "直走 (zhi zou) means 'go straight'. 直 (zhi) = straight, 走 (zou) = to walk/go. You may also hear 一直走 (yi zhi zou) = keep going straight. Giving directions: 一直走，然后左转 (yi zhi zou, ran hou zuo zhuan) = Go straight, then turn left. 然后 (ran hou) = then/after that.",
                "is_boss": False,
                "flavor": "Long Long points his tail straight ahead. 'Zhi zou -- the shortest path!'",
            },
            {
                "id": "duoyuan_howfar",
                "title": "How Far Is It?",
                "type": "quiz",
                "question": "What does 'duo yuan' (多远) mean?",
                "options": ["How long?", "How far?", "How much?", "How many?"],
                "answer": "b",
                "hints": [
                    "duo (多) means 'how much' and yuan (远) means 'far'.",
                    "You ask this when you want to know the distance.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "多远 (duo yuan) means 'how far'. 多 (duo) = how (much), 远 (yuan) = far. 火车站离这里多远? (huo che zhan li zhe li duo yuan?) = How far is the train station from here? 离 (li) = from/away from. 不远 (bu yuan) = not far. 很远 (hen yuan) = very far.",
                "is_boss": False,
                "flavor": "Long Long squints into the distance. 'Duo yuan -- is it walking distance or flying distance?'",
            },
            {
                "id": "direction_text_review",
                "title": "Direction Recall",
                "type": "text",
                "question": "Type the pinyin for 'turn left' (two syllables, no tones):",
                "options": [],
                "answer": "zuo zhuan",
                "hints": [
                    "The first word means 'left'.",
                    "The second word means 'to turn'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "左转 (zuo zhuan) = turn left. Direction review: 左转 (zuo zhuan) turn left, 右转 (you zhuan) turn right, 直走 (zhi zou) go straight, 在哪里 (zai na li) where is, 怎么去 (zen me qu) how to get there, 多远 (duo yuan) how far.",
                "is_boss": False,
                "flavor": "Long Long spins around. 'Quick -- which way is left?'",
            },
            {
                "id": "direction_boss",
                "title": "Navigation Master",
                "type": "quiz",
                "question": "Someone tells you: '一直走，然后右转' (yi zhi zou, ran hou you zhuan). What should you do?",
                "options": [
                    "Turn left, then go straight",
                    "Go straight, then turn right",
                    "Turn right, then go straight",
                    "Go straight, then turn left",
                ],
                "answer": "b",
                "hints": [
                    "yi zhi zou = keep going straight, ran hou = then.",
                    "you zhuan = turn right.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "一直走，然后右转 (yi zhi zou, ran hou you zhuan) = 'Go straight, then turn right.' This is the most common direction-giving pattern: [action 1] + 然后 (ran hou, then) + [action 2]. You can chain more: 一直走，然后左转，再右转 = Go straight, turn left, then turn right. 再 (zai) = again/then.",
                "is_boss": True,
                "flavor": "Long Long applauds. 'You'll never get lost in China!'",
            },
        ],
    },

    # ── Zone 4: At the Station ────────────────────────────────────────
    "at_the_station": {
        "id": "at_the_station",
        "name": "At the Station",
        "description": "Navigate train and subway stations in Chinese",
        "level_required": 7,
        "challenges": [
            {
                "id": "zhan_station",
                "title": "The Station Gate",
                "type": "quiz",
                "question": "What does 'zhan' (站) mean?",
                "options": ["Track", "Station / Stop", "Platform", "Bridge"],
                "answer": "b",
                "hints": [
                    "This character has the 'standing person' radical on the left.",
                    "You wait here for your bus or train.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "站 (zhan) means 'station' or 'stop'. 火车站 (huo che zhan) = train station. 地铁站 (di tie zhan) = subway station. 公共汽车站 (gong gong qi che zhan) = bus stop. 下一站 (xia yi zhan) = next stop. The character 站 has the 'standing' radical (立) because you stand and wait at a station.",
                "is_boss": False,
                "flavor": "Long Long gazes at the grand station entrance. 'Zhan -- where journeys begin!'",
            },
            {
                "id": "chukou_exit",
                "title": "Finding the Exit",
                "type": "quiz",
                "question": "What does 'chu kou' (出口) mean?",
                "options": ["Entrance", "Exit", "Transfer", "Platform"],
                "answer": "b",
                "hints": [
                    "chu (出) means 'to go out' and kou (口) means 'opening/mouth'.",
                    "This is where you leave the station.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "出口 (chu kou) means 'exit' (literally 'go-out opening'). 出 (chu) = to exit/go out, 口 (kou) = mouth/opening. In Chinese subway stations, exits are labeled A口, B口, C口 etc. 从A出口出去 (cong A chu kou chu qu) = Go out from Exit A. The opposite is 入口 (ru kou) = entrance.",
                "is_boss": False,
                "flavor": "Long Long follows the green exit signs. 'Chu kou -- the way out!'",
            },
            {
                "id": "rukou_entrance",
                "title": "The Way In",
                "type": "quiz",
                "question": "What does 'ru kou' (入口) mean?",
                "options": ["Exit", "Entrance", "Ticket office", "Waiting room"],
                "answer": "b",
                "hints": [
                    "ru (入) means 'to enter' and kou (口) means 'opening'.",
                    "This is the opposite of chu kou (出口).",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "入口 (ru kou) means 'entrance' (literally 'enter opening'). 入 (ru) = to enter, 口 (kou) = mouth/opening. Station pairs to remember: 入口/出口 (ru kou/chu kou) = entrance/exit. 进站 (jin zhan) = enter the station. 出站 (chu zhan) = exit the station. Always follow the signs!",
                "is_boss": False,
                "flavor": "Long Long squeezes through the entrance gate. 'Ru kou -- in we go!'",
            },
            {
                "id": "huancheng_transfer",
                "title": "Changing Lines",
                "type": "quiz",
                "question": "What does 'huan cheng' (换乘) mean?",
                "options": ["Buy ticket", "Transfer / Change (lines)", "Board the train", "Wait"],
                "answer": "b",
                "hints": [
                    "huan (换) means 'to change/swap' and cheng (乘) means 'to ride'.",
                    "You do this when switching from one subway line to another.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "换乘 (huan cheng) means 'to transfer' (literally 'change ride'). 换 (huan) = to change/exchange, 乘 (cheng) = to ride. 换乘站 (huan cheng zhan) = transfer station. 在这站换乘二号线 (zai zhe zhan huan cheng er hao xian) = Transfer to Line 2 at this station. 号线 (hao xian) = line number.",
                "is_boss": False,
                "flavor": "Long Long studies the subway map. 'Huan cheng -- follow the colored lines!'",
            },
            {
                "id": "zhantai_platform",
                "title": "The Right Platform",
                "type": "quiz",
                "question": "What does 'zhan tai' (站台) mean?",
                "options": ["Ticket counter", "Waiting room", "Platform", "Information desk"],
                "answer": "c",
                "hints": [
                    "zhan (站) is 'station' and tai (台) means 'platform/stage'.",
                    "This is the raised area where you board the train.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "站台 (zhan tai) means 'platform'. 站 (zhan) = station, 台 (tai) = platform/stage. 第几站台? (di ji zhan tai?) = Which platform? 请到三号站台 (qing dao san hao zhan tai) = Please go to Platform 3. On Chinese train tickets, the platform number is shown as 站台 or 月台 (yue tai, an older term).",
                "is_boss": False,
                "flavor": "Long Long peers down the tracks. 'Zhan tai -- stand here and wait!'",
            },
            {
                "id": "xia_yi_zhan_next",
                "title": "The Next Stop",
                "type": "quiz",
                "question": "How do you say 'next stop' in Chinese?",
                "options": [
                    "shang yi zhan (上一站)",
                    "xia yi zhan (下一站)",
                    "zhe yi zhan (这一站)",
                    "zhong dian zhan (终点站)",
                ],
                "answer": "b",
                "hints": [
                    "xia (下) means 'next/below' and yi zhan (一站) means 'one stop'.",
                    "You hear this announcement on every bus and subway.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "下一站 (xia yi zhan) means 'next stop'. 下 (xia) = next/below, 一 (yi) = one, 站 (zhan) = stop. You'll hear this constantly on Chinese transit: 下一站是... (xia yi zhan shi...) = The next stop is... 上一站 (shang yi zhan) = previous stop. 终点站 (zhong dian zhan) = final stop/terminus.",
                "is_boss": False,
                "flavor": "Long Long listens to the announcement. 'Xia yi zhan -- almost there!'",
            },
            {
                "id": "station_text_review",
                "title": "Station Recall",
                "type": "text",
                "question": "Type the pinyin for 'exit' (two syllables, no tones):",
                "options": [],
                "answer": "chu kou",
                "hints": [
                    "The first word means 'to go out'.",
                    "The second word means 'mouth' or 'opening'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "出口 (chu kou) = exit. Station vocabulary: 站 (zhan) station, 出口 (chu kou) exit, 入口 (ru kou) entrance, 换乘 (huan cheng) transfer, 站台 (zhan tai) platform, 下一站 (xia yi zhan) next stop.",
                "is_boss": False,
                "flavor": "Long Long points to the signs. 'Which way is out?'",
            },
            {
                "id": "station_boss",
                "title": "Station Navigator",
                "type": "quiz",
                "question": "You hear: '下一站是换乘站，可以换乘三号线' (xia yi zhan shi huan cheng zhan, ke yi huan cheng san hao xian). What does it mean?",
                "options": [
                    "The next stop is the last stop on Line 3",
                    "The next stop is a transfer station where you can change to Line 3",
                    "Please exit at the next stop for Line 3",
                    "Line 3 is closed at the next stop",
                ],
                "answer": "b",
                "hints": [
                    "xia yi zhan = next stop, huan cheng zhan = transfer station.",
                    "ke yi huan cheng san hao xian = can transfer to Line 3.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "下一站是换乘站，可以换乘三号线 = 'The next stop is a transfer station; you can transfer to Line 3.' 可以 (ke yi) = can/may. 三号线 (san hao xian) = Line 3. This is a typical subway announcement. Knowing station vocabulary helps you navigate China's massive metro systems with confidence.",
                "is_boss": True,
                "flavor": "Long Long nods proudly. 'You can navigate any station in China!'",
            },
        ],
    },

    # ── Zone 5: Travel Conversations ──────────────────────────────────
    "travel_conversations": {
        "id": "travel_conversations",
        "name": "Travel Conversations",
        "description": "Real travel phrases and conversations in Chinese",
        "level_required": 9,
        "challenges": [
            {
                "id": "wo_yao_qu_iwantgo",
                "title": "Stating Your Destination",
                "type": "quiz",
                "question": "How do you say 'I want to go to Beijing' in Chinese?",
                "options": [
                    "wo yao qu Bei Jing (我要去北京)",
                    "wo zai Bei Jing (我在北京)",
                    "wo shi Bei Jing ren (我是北京人)",
                    "wo cong Bei Jing lai (我从北京来)",
                ],
                "answer": "a",
                "hints": [
                    "wo yao (我要) = I want, qu (去) = to go.",
                    "Which option uses 'want to go to'?",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "我要去北京 (wo yao qu Bei Jing) = 'I want to go to Beijing.' Pattern: 我要去 + [place]. This is the simplest way to state your destination. Other examples: 我要去机场 (wo yao qu ji chang) = I want to go to the airport. 我要去火车站 (wo yao qu huo che zhan) = I want to go to the train station.",
                "is_boss": False,
                "flavor": "Long Long unfurls a map. 'Wo yao qu -- name your destination!'",
            },
            {
                "id": "dao_le_ma_arrived",
                "title": "Are We There Yet?",
                "type": "quiz",
                "question": "What does 'dao le ma' (到了吗) mean?",
                "options": ["Can I sit here?", "Have we arrived?", "How long?", "Is this the right way?"],
                "answer": "b",
                "hints": [
                    "dao (到) means 'to arrive' and le (了) indicates completion.",
                    "ma (吗) makes it a yes/no question.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "到了吗 (dao le ma) = 'Have we arrived?' 到 (dao) = to arrive, 了 (le) = completed action marker, 吗 (ma) = question particle. 快到了 (kuai dao le) = Almost there. 到了! (dao le!) = We've arrived! 还没到 (hai mei dao) = Haven't arrived yet. This is essential for any trip.",
                "is_boss": False,
                "flavor": "Long Long fidgets impatiently. 'Dao le ma? Dao le ma? Are we there yet?'",
            },
            {
                "id": "hai_you_duo_yuan",
                "title": "How Much Further?",
                "type": "quiz",
                "question": "What does 'hai you duo yuan' (还有多远) mean?",
                "options": [
                    "How much does it cost?",
                    "How much further?",
                    "How long will it take?",
                    "How many stops left?",
                ],
                "answer": "b",
                "hints": [
                    "hai you (还有) means 'still have / remaining'.",
                    "duo yuan (多远) means 'how far'.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "还有多远 (hai you duo yuan) = 'How much further?' (literally 'still have how far'). 还有 (hai you) = still remaining. 还有多长时间? (hai you duo chang shi jian?) = How much longer (time)? 还有三站 (hai you san zhan) = Three more stops. 还有 is incredibly useful for asking about remaining distance, time, or quantity.",
                "is_boss": False,
                "flavor": "Long Long cranes his neck forward. 'Hai you duo yuan -- my wings are tired!'",
            },
            {
                "id": "qing_wen_excuse_me",
                "title": "Excuse Me...",
                "type": "quiz",
                "question": "What is the polite way to start asking for directions in Chinese?",
                "options": [
                    "ni hao (你好)",
                    "qing wen (请问)",
                    "dui bu qi (对不起)",
                    "xie xie (谢谢)",
                ],
                "answer": "b",
                "hints": [
                    "qing (请) means 'please' and wen (问) means 'to ask'.",
                    "This literally means 'may I ask' -- very polite.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "请问 (qing wen) means 'excuse me / may I ask' (literally 'please ask'). This is the polite opener for any question to a stranger. 请问，火车站怎么去? (qing wen, huo che zhan zen me qu?) = Excuse me, how do I get to the train station? Always start with 请问 when asking for help -- it shows respect.",
                "is_boss": False,
                "flavor": "Long Long bows politely. 'Qing wen -- manners open all doors!'",
            },
            {
                "id": "duo_chang_shijian",
                "title": "How Long Does It Take?",
                "type": "quiz",
                "question": "What does 'yao duo chang shi jian' (要多长时间) mean?",
                "options": [
                    "What time does it leave?",
                    "How long does it take?",
                    "When does it arrive?",
                    "How many stops?",
                ],
                "answer": "b",
                "hints": [
                    "yao (要) = need/take, duo chang (多长) = how long.",
                    "shi jian (时间) = time.",
                ],
                "xp": 25,
                "difficulty": "medium",
                "lesson": "要多长时间 (yao duo chang shi jian) = 'How long does it take?' 要 (yao) = need, 多长 (duo chang) = how long, 时间 (shi jian) = time. 到北京要多长时间? (dao Bei Jing yao duo chang shi jian?) = How long does it take to get to Beijing? Answer pattern: 大概两个小时 (da gai liang ge xiao shi) = About two hours.",
                "is_boss": False,
                "flavor": "Long Long checks the sun's position. 'Yao duo chang shi jian -- time matters!'",
            },
            {
                "id": "zuo_nalu_sit_where",
                "title": "Where Do I Sit?",
                "type": "text",
                "question": "Type the pinyin for 'have we arrived?' (three syllables, no tones):",
                "options": [],
                "answer": "dao le ma",
                "hints": [
                    "The first syllable means 'to arrive'.",
                    "The last syllable is the question particle.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "到了吗 (dao le ma) = Have we arrived? Key travel phrases: 我要去... (wo yao qu) I want to go to..., 到了吗 (dao le ma) have we arrived, 还有多远 (hai you duo yuan) how much further, 请问 (qing wen) excuse me, 要多长时间 (yao duo chang shi jian) how long does it take.",
                "is_boss": False,
                "flavor": "Long Long quizzes your memory. 'What do you say when you're eager to arrive?'",
            },
            {
                "id": "shifu_driver",
                "title": "Talking to the Driver",
                "type": "quiz",
                "question": "In a taxi, how would you politely say 'Please go to the airport'?",
                "options": [
                    "shi fu, qing qu ji chang (师傅，请去机场)",
                    "wo yao fei ji (我要飞机)",
                    "ji chang duo shao qian (机场多少钱)",
                    "ji chang zai na li (机场在哪里)",
                ],
                "answer": "a",
                "hints": [
                    "shi fu (师傅) is the respectful way to address a driver.",
                    "qing (请) means 'please' and qu (去) means 'go to'.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "师傅，请去机场 (shi fu, qing qu ji chang) = 'Driver, please go to the airport.' 师傅 (shi fu) = master/driver (respectful address for taxi drivers, craftsmen). 请去 (qing qu) = please go to. In a taxi, you can also say: 师傅，到了请告诉我 (shi fu, dao le qing gao su wo) = Driver, please let me know when we arrive.",
                "is_boss": False,
                "flavor": "Long Long climbs into a carriage. 'Shi fu -- always show respect to your driver!'",
            },
            {
                "id": "travel_boss",
                "title": "Travel Conversation Master",
                "type": "quiz",
                "question": "You're in a taxi and want to say: 'Excuse me, how long does it take to get to the train station?' Which is correct?",
                "options": [
                    "qing wen, dao huo che zhan yao duo chang shi jian (请问，到火车站要多长时间)",
                    "huo che zhan zai na li, duo shao qian (火车站在哪里，多少钱)",
                    "wo yao qu huo che zhan, dao le ma (我要去火车站，到了吗)",
                    "shi fu, huo che zhan hai you duo yuan ma (师傅，火车站还有多远吗)",
                ],
                "answer": "a",
                "hints": [
                    "qing wen = excuse me, dao = to arrive at, yao duo chang shi jian = how long does it take.",
                    "You need the phrase that asks about time to reach the train station.",
                ],
                "xp": 40,
                "difficulty": "hard",
                "lesson": "请问，到火车站要多长时间 (qing wen, dao huo che zhan yao duo chang shi jian) = 'Excuse me, how long does it take to get to the train station?' This combines: 请问 (polite opener) + 到 (to arrive at) + [place] + 要多长时间 (how long does it take). You now have all the tools to navigate travel in China with confidence!",
                "is_boss": True,
                "flavor": "Long Long breathes golden fire in celebration. 'You can travel anywhere in China now!'",
            },
        ],
    },
}
