"""
zones.py — Science zones and challenges.
"""

ZONE_ORDER = [
    "living_things",
    "sky_and_weather",
    "body_basics",
    "how_things_work",
    "simple_machines",
    "earth_and_space",
    "matter_and_energy",
    "weather_watch",
    "animal_world",
    "the_human_body",
    "ecosystems_and_food_chains",
]

ZONES = {
    "living_things": {
        "id": "living_things",
        "name": "The Garden of Living Things",
        "subtitle": "What's alive, and how can you tell?",
        "icon": "🌱",
        "description": "Discover what makes something alive",
        "level_required": 1,
        "challenges": [
            {
                "id": "lt_01",
                "title": "What Makes Something Alive?",
                "type": "quiz",
                "question": "Which of these is a living thing?",
                "lesson": "Living things grow, breathe, eat, and can have babies. Rocks do none of these — they're not alive!",
                "options": ["A rock", "A cloud", "A cat", "A shoe"],
                "answer": "c",
                "hints": ["Does it grow? Does it breathe? Does it eat?", "A cat grows, eats, and has kittens — it's alive!"],
                "xp": 30,
            },
            {
                "id": "lt_02",
                "title": "Plants Are Alive!",
                "type": "quiz",
                "question": "How do plants make their own food?",
                "lesson": "Plants make food from [bold yellow]sunlight, water, and air[/bold yellow]. This is called photosynthesis. That's why plants grow toward the light!",
                "options": ["They eat bugs", "They use sunlight, water, and air", "They get food from stores", "They eat other plants"],
                "answer": "b",
                "hints": ["Have you noticed how plants grow toward windows?", "Sun + water + air = food for plants!"],
                "xp": 30,
            },
            {
                "id": "lt_03",
                "title": "Animal or Plant?",
                "type": "quiz",
                "question": "What is the main difference between animals and plants?",
                "lesson": "Animals [bold yellow]move around[/bold yellow] to find food. Plants [bold yellow]stay in one place[/bold yellow] and make their own food from sunlight.",
                "options": ["Animals are bigger", "Animals move around to find food", "Plants are alive but animals aren't", "Animals live outside"],
                "answer": "b",
                "hints": ["Can a tree walk to the kitchen for a snack?", "Animals move! Plants stay put and make their own food."],
                "xp": 30,
            },
            {
                "id": "lt_04",
                "title": "Life Cycles",
                "type": "quiz",
                "question": "What comes after an egg in a frog's life cycle?",
                "lesson": "A frog's life: egg → [bold yellow]tadpole[/bold yellow] → frog. The tadpole swims like a fish and slowly grows legs!",
                "options": ["A frog right away", "A tadpole", "A butterfly", "A baby bird"],
                "answer": "b",
                "hints": ["Frogs start in water as babies — have you seen tadpoles?", "Egg → tadpole → frog!"],
                "xp": 35,
            },
            {
                "id": "lt_boss",
                "title": "Why Do Leaves Change Color?",
                "type": "quiz",
                "question": "Why do leaves turn red and orange in autumn?",
                "lesson": "In summer, leaves are full of [bold yellow]green chlorophyll[/bold yellow] which makes food. In autumn, days get shorter, trees stop making food, the green fades — and the hidden red, orange, and yellow colors show through!",
                "options": ["They get cold and freeze", "They stop making food and the green color fades away", "They get painted by the wind", "They are sick"],
                "answer": "b",
                "hints": ["The colors were hiding all along under the green!", "Leaves have red and yellow pigments — we just can't see them in summer."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "sky_and_weather": {
        "id": "sky_and_weather",
        "name": "The Sky Watchers",
        "subtitle": "Sun, clouds, seasons, and storms",
        "icon": "☁️",
        "description": "Understand weather and the sky",
        "level_required": 2,
        "challenges": [
            {
                "id": "sw_01",
                "title": "Why Does the Sun Rise?",
                "type": "quiz",
                "question": "Why does the sun seem to move across the sky each day?",
                "lesson": "The sun doesn't move — [bold yellow]the Earth spins![/bold yellow] As our planet rotates, the sun appears to rise in the east, move across the sky, and set in the west.",
                "options": ["The sun walks across the sky", "The Earth spins around", "The clouds push the sun", "The moon moves the sun"],
                "answer": "b",
                "hints": ["The Earth is spinning right now — you just can't feel it!", "Earth rotates once every 24 hours — that's why we have day and night."],
                "xp": 30,
            },
            {
                "id": "sw_02",
                "title": "The Four Seasons",
                "type": "quiz",
                "question": "Why is summer warmer than winter?",
                "lesson": "In summer, the sun is [bold yellow]higher in the sky[/bold yellow] and shines more directly on us, giving more warmth. In winter, the Earth is tilted away from the sun, so sunlight hits at an angle and feels weaker.",
                "options": ["The sun is closer in summer", "The Earth tilts toward the sun in summer", "There are more clouds in winter", "The moon blocks the sun in winter"],
                "answer": "b",
                "hints": ["It's not about distance — it's about the angle!", "Earth's tilt changes how directly the sun hits us."],
                "xp": 35,
            },
            {
                "id": "sw_03",
                "title": "Where Does Rain Come From?",
                "type": "quiz",
                "question": "How does rain form?",
                "lesson": "The sun heats water in oceans and lakes. The water rises as invisible vapor, cools high up, and forms [bold yellow]clouds[/bold yellow]. When enough water collects, it falls as rain. Then the cycle starts again!",
                "options": ["Clouds are bags of water that pop", "Water evaporates, forms clouds, then falls as rain", "The sky makes new water", "Mountains push water into the sky"],
                "answer": "b",
                "hints": ["Have you seen steam from a hot cup? Water turning to vapor is similar!", "It's a cycle: water evaporates → forms clouds → rains → evaporates again."],
                "xp": 35,
            },
            {
                "id": "sw_04",
                "title": "What Is a Cloud?",
                "type": "quiz",
                "question": "What are clouds made of?",
                "lesson": "Clouds are made of [bold yellow]billions of tiny water droplets[/bold yellow] (or ice crystals) floating in the sky. They look white and fluffy but up close they look just like fog!",
                "options": ["Cotton fluff", "Smoke", "Tiny water droplets or ice crystals", "Dust and dirt"],
                "answer": "c",
                "hints": ["Have you ever walked through fog? That's basically a cloud at ground level!", "Tiny drops of water floating in air = cloud!"],
                "xp": 30,
            },
            {
                "id": "sw_boss",
                "title": "Why Is the Sky Blue?",
                "type": "quiz",
                "question": "Why does the sky look blue during the day?",
                "lesson": "Sunlight is actually [bold yellow]all colors mixed together[/bold yellow]. When it hits the atmosphere, blue light bounces around the most (it scatters), filling the whole sky with blue. At sunset, the light has to travel through more air, so the blue scatters away and we see red and orange!",
                "options": ["The ocean reflects blue upward", "Blue light scatters more through the atmosphere", "The sky is made of blue water", "Stars are blue"],
                "answer": "b",
                "hints": ["Sunlight has all colors — a rainbow proves it!", "Blue light bounces around in the atmosphere more than other colors."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "body_basics": {
        "id": "body_basics",
        "name": "The Amazing Body",
        "subtitle": "Your body is working right now",
        "icon": "❤️",
        "description": "Understand your senses and how your body works",
        "level_required": 3,
        "challenges": [
            {
                "id": "bb_01",
                "title": "The Five Senses",
                "type": "quiz",
                "question": "How many senses does a human have? What are they?",
                "lesson": "Five senses: [bold yellow]sight, hearing, smell, taste, and touch[/bold yellow]. Together they help your brain understand the world around you.",
                "options": ["3 — sight, hearing, touch", "4 — sight, hearing, smell, taste", "5 — sight, hearing, smell, taste, touch", "6 — including a sixth sense"],
                "answer": "c",
                "hints": ["Use your fingers: eyes, ears, nose, tongue, skin!", "S-H-S-T-T: Sight, Hearing, Smell, Taste, Touch"],
                "xp": 30,
            },
            {
                "id": "bb_02",
                "title": "Your Heart",
                "type": "quiz",
                "question": "What does your heart do?",
                "lesson": "Your heart is a [bold yellow]pump[/bold yellow]. It beats about 70 times per minute, pushing blood through your entire body — delivering food and oxygen to every part of you!",
                "options": ["It stores energy like a battery", "It pumps blood through your whole body", "It controls your thoughts", "It makes you breathe"],
                "answer": "b",
                "hints": ["Put your hand on your chest — can you feel it beating?", "Your heart pumps blood everywhere!"],
                "xp": 30,
            },
            {
                "id": "bb_03",
                "title": "Breathing",
                "type": "quiz",
                "question": "Why do we breathe?",
                "lesson": "We breathe to get [bold yellow]oxygen[/bold yellow] into our blood. Our bodies use oxygen to turn food into energy. We breathe out carbon dioxide — the waste product.",
                "options": ["To cool ourselves down", "To get oxygen our bodies need for energy", "To make our voices work", "To smell things"],
                "answer": "b",
                "hints": ["Without oxygen, your body can't turn food into energy!", "In: oxygen. Out: carbon dioxide."],
                "xp": 30,
            },
            {
                "id": "bb_04",
                "title": "What Do Bones Do?",
                "type": "quiz",
                "question": "How many bones does an adult human body have?",
                "lesson": "Adult humans have [bold yellow]206 bones[/bold yellow]. Babies are born with about 270 smaller bones that fuse together as they grow. Bones give your body its shape, protect your organs, and let you move!",
                "options": ["26", "106", "206", "306"],
                "answer": "c",
                "hints": ["It's more than 100 but less than 300!", "206 bones hold your whole body together!"],
                "xp": 35,
            },
            {
                "id": "bb_boss",
                "title": "Why Do We Need Sleep?",
                "type": "quiz",
                "question": "Why is sleep so important for your body?",
                "lesson": "While you sleep, your [bold yellow]brain sorts memories[/bold yellow], your [bold yellow]body grows and repairs itself[/bold yellow], and your [bold yellow]immune system gets stronger[/bold yellow]. Without enough sleep, it's hard to learn, remember things, or feel well. Sleep is when your body does its best work!",
                "options": ["So we don't get bored at night", "So our brain and body can grow, repair, and process memories", "To save energy like a phone", "Because it gets dark outside"],
                "answer": "b",
                "hints": ["Think about how you feel after a bad night's sleep!", "Your brain and body do their repair work while you rest."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "how_things_work": {
        "id": "how_things_work",
        "name": "The Workshop of Wonders",
        "subtitle": "Cause, effect, and simple machines",
        "icon": "⚙️",
        "description": "Discover how forces and simple machines work",
        "level_required": 4,
        "challenges": [
            {
                "id": "hw_01",
                "title": "Gravity",
                "type": "quiz",
                "question": "Why do things fall down when you drop them?",
                "lesson": "[bold yellow]Gravity[/bold yellow] is a force that pulls everything toward the Earth. The bigger an object, the stronger its gravity. Earth is so big, it pulls everything toward its center — so 'down' always means toward the ground!",
                "options": ["Because the air pushes them down", "Because gravity pulls everything toward Earth", "Because they're heavy", "Because of the wind"],
                "answer": "b",
                "hints": ["What holds you on the ground? Why doesn't the moon float away?", "Gravity is a pull between objects — bigger objects pull harder!"],
                "xp": 30,
            },
            {
                "id": "hw_02",
                "title": "A Ramp Helps",
                "type": "quiz",
                "question": "Why is it easier to push a heavy box up a ramp than to lift it straight up?",
                "lesson": "A [bold yellow]ramp[/bold yellow] (also called an inclined plane) is a simple machine. It spreads the work over a longer distance, so each step takes less force. Less force needed at once = easier!",
                "options": ["The ramp makes the box lighter", "The ramp makes the box slide", "The ramp spreads the work over a longer distance, needing less force at once", "Ramps are slippery"],
                "answer": "c",
                "hints": ["Think about loading ramps trucks use — why are they so long?", "A ramp trades distance for force: go further but push less hard!"],
                "xp": 35,
            },
            {
                "id": "hw_03",
                "title": "Shadows",
                "type": "quiz",
                "question": "How is a shadow made?",
                "lesson": "A shadow forms when a [bold yellow]solid object blocks light[/bold yellow]. Light travels in straight lines and can't bend around corners — so where the object blocks it, a dark area (shadow) appears behind it.",
                "options": ["The object absorbs the sun's color", "The object blocks light from reaching the surface behind it", "Shadows are reflections", "Dark air collects behind objects"],
                "answer": "b",
                "hints": ["On a sunny day, face the sun — where is your shadow?", "Light travels straight. When something blocks it, a shadow forms!"],
                "xp": 30,
            },
            {
                "id": "hw_04",
                "title": "Magnets",
                "type": "quiz",
                "question": "A magnet will attract (pull toward itself) which of these?",
                "lesson": "Magnets attract [bold yellow]iron and steel[/bold yellow]. They don't attract plastic, wood, glass, or most other materials. That's why fridges use magnets but your wooden desk doesn't stick to them!",
                "options": ["A plastic bottle", "A wooden pencil", "A steel paper clip", "A glass cup"],
                "answer": "c",
                "hints": ["Think about what sticks to a refrigerator!", "Iron and steel are attracted to magnets — most other materials aren't."],
                "xp": 30,
            },
            {
                "id": "hw_boss",
                "title": "Sink or Float?",
                "type": "quiz",
                "question": "A giant steel ship weighs thousands of tons, but it floats. A small steel coin sinks. Why?",
                "lesson": "An object floats if it displaces (pushes aside) water that weighs [bold yellow]more than the object itself[/bold yellow]. The hollow ship pushes aside a lot of water. The coin is solid and small, so the water it pushes weighs less than the coin — so it sinks!",
                "options": ["Ships are magic", "Ships are made of lighter steel", "The ship's hollow shape pushes aside more water than the coin", "The ocean is saltier near ships"],
                "answer": "c",
                "hints": ["What happens if you fill a bowl with water and put it in more water?", "It's about the space the object takes up, not just its weight!"],
                "xp": 80,
                "is_boss": True,
            },
        ],
    },

    "simple_machines": {
        "id": "simple_machines",
        "name": "The Simple Machines Workshop",
        "subtitle": "Six tools that make every hard job easier",
        "icon": "🔧",
        "description": "Discover the six ancient tools that built every civilization",
        "level_required": 5,
        "challenges": [
            {
                "id": "sm_01",
                "title": "The Lever",
                "type": "quiz",
                "question": "A seesaw is a great example of which simple machine?",
                "lesson": "A [bold yellow]lever[/bold yellow] is a bar that rests on a pivot point called a fulcrum. It lets you lift heavy things with less effort. Seesaws, crowbars, and even your arm are all levers!",
                "options": ["A wheel and axle", "A pulley", "A lever", "A screw"],
                "answer": "c",
                "hints": ["Think about the plank that tips up and down at the playground!", "A seesaw balances on a pivot point in the middle — that's a lever!"],
                "xp": 30,
            },
            {
                "id": "sm_02",
                "title": "Wheel and Axle",
                "type": "quiz",
                "question": "Which everyday object is the best example of a wheel and axle?",
                "lesson": "A [bold yellow]wheel and axle[/bold yellow] is a round wheel attached to a rod (the axle). When you turn the wheel, the axle turns too — making it much easier to move things. Bicycles, cars, and rolling pins all use wheels and axles!",
                "options": ["A see-saw at the playground", "A bicycle wheel turning on its axle", "A knife cutting bread", "A flag rope pulled up a pole"],
                "answer": "b",
                "hints": ["Think about something you ride that has round spinning things!", "A bike wheel spins around a rod called an axle — wheel and axle!"],
                "xp": 30,
            },
            {
                "id": "sm_03",
                "title": "The Inclined Plane",
                "type": "quiz",
                "question": "Which of these is the best example of an inclined plane?",
                "lesson": "An [bold yellow]inclined plane[/bold yellow] is just a flat slanted surface — a ramp! It lets you move something heavy to a higher place by sliding it up gradually instead of lifting it straight up. Less force needed, just more distance!",
                "options": ["A pair of scissors", "A door handle", "A ramp at the entrance of a building", "A pulley on a flagpole"],
                "answer": "c",
                "hints": ["Think about how wheelchair ramps or loading ramps work.", "A ramp is a slanted surface — an inclined plane!"],
                "xp": 30,
            },
            {
                "id": "sm_04",
                "title": "The Pulley",
                "type": "quiz",
                "question": "Workers use a pulley to lift heavy boxes up to a high shelf. What does the pulley do?",
                "lesson": "A [bold yellow]pulley[/bold yellow] is a wheel with a rope around it. It changes the direction of your pull — instead of lifting something straight up (which is hard), you pull a rope down (which feels much easier). Cranes, flagpoles, and blinds all use pulleys!",
                "options": ["It makes the box lighter", "It changes the direction you pull so lifting feels easier", "It spins the box around", "It melts the rope to release the box"],
                "answer": "b",
                "hints": ["Think about how you pull a rope DOWN to make something go UP!", "Pulleys change which direction you push or pull — that's their superpower!"],
                "xp": 35,
            },
            {
                "id": "sm_05",
                "title": "The Wedge",
                "type": "quiz",
                "question": "An axe splitting a log is an example of which simple machine?",
                "lesson": "A [bold yellow]wedge[/bold yellow] is two inclined planes put together to form a sharp edge. It focuses your force into a very small point, making it easy to split or cut things. Knives, axes, chisels, and even your front teeth are wedges!",
                "options": ["A lever", "A screw", "A pulley", "A wedge"],
                "answer": "d",
                "hints": ["What shape is an axe head? It comes to a sharp edge!", "A wedge has a thin edge that pushes things apart — like an axe or a knife!"],
                "xp": 35,
            },
            {
                "id": "sm_boss",
                "title": "The Screw",
                "type": "quiz",
                "question": "A screw is actually a simple machine in disguise. What is it really?",
                "lesson": "A [bold yellow]screw[/bold yellow] is an inclined plane (a ramp!) wrapped around a cylinder. As you turn it, the spiral thread bites into the material and holds everything together with tremendous force. Bottle caps, jar lids, and drill bits all work the same way!",
                "options": ["A lever wrapped in metal", "A pulley made very small", "An inclined plane wrapped around a cylinder", "A wheel and axle that doesn't move"],
                "answer": "c",
                "hints": ["Look at the spiral groove on a screw — imagine unrolling that spiral. What shape would it be?", "A screw's spiral thread is just a ramp wound around and around!"],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "earth_and_space": {
        "id": "earth_and_space",
        "name": "The Sky Observatory",
        "subtitle": "Earth, the Moon, the Sun, and the stars",
        "icon": "🌙",
        "description": "Explore the Earth, the Moon, and what's beyond",
        "level_required": 6,
        "challenges": [
            {
                "id": "es_01",
                "title": "Earth Goes Around the Sun",
                "type": "quiz",
                "question": "Which is correct — does the Earth go around the Sun, or does the Sun go around the Earth?",
                "lesson": "The [bold yellow]Earth orbits the Sun[/bold yellow] — not the other way around! It looks like the Sun moves across our sky, but that's because the Earth is spinning. Earth travels all the way around the Sun once every year.",
                "options": ["The Sun goes around the Earth", "The Earth goes around the Sun", "They both stay completely still", "The Moon pushes the Earth around the Sun"],
                "answer": "b",
                "hints": ["Even though the Sun seems to move across the sky, it's actually Earth that's moving!", "Earth travels around the Sun — that's what makes a year!"],
                "xp": 30,
            },
            {
                "id": "es_02",
                "title": "The Moon Orbits Earth",
                "type": "quiz",
                "question": "What does the Moon orbit (travel around)?",
                "lesson": "The [bold yellow]Moon orbits Earth[/bold yellow]. Our Moon is Earth's only natural satellite — it travels around us, and we see it in the night sky almost every night. It takes about 27 days to go all the way around!",
                "options": ["The Sun", "Mars", "The Earth", "The stars"],
                "answer": "c",
                "hints": ["You can see the Moon from Earth — it's very close compared to the stars!", "The Moon goes around the Earth, just like Earth goes around the Sun!"],
                "xp": 30,
            },
            {
                "id": "es_03",
                "title": "One Year",
                "type": "quiz",
                "question": "How long does it take Earth to travel all the way around the Sun?",
                "lesson": "Earth takes [bold yellow]one year (365 days)[/bold yellow] to complete one orbit around the Sun. That's why we have birthdays once a year — each birthday marks one full trip around the Sun!",
                "options": ["One day", "One month", "One year (365 days)", "Ten years"],
                "answer": "c",
                "hints": ["Your birthday comes around once every time Earth completes its trip!", "One trip around the Sun = one year = 365 days!"],
                "xp": 30,
            },
            {
                "id": "es_04",
                "title": "Day and Night",
                "type": "quiz",
                "question": "What causes day and night on Earth?",
                "lesson": "Day and night happen because [bold yellow]Earth spins[/bold yellow]. As it rotates, one side faces the Sun (daytime) while the other side faces away (nighttime). One full spin takes 24 hours — that's why a day is 24 hours long!",
                "options": ["The Sun turns its light on and off", "The Moon blocks the Sun at night", "Earth spins, so one side faces the Sun while the other is in darkness", "Clouds cover the Sun at nighttime"],
                "answer": "c",
                "hints": ["Earth is spinning right now — very, very slowly compared to a spin top.", "When your part of Earth faces the Sun, it's day. When it spins away, it's night!"],
                "xp": 30,
            },
            {
                "id": "es_05",
                "title": "Moon Phases",
                "type": "quiz",
                "question": "Why does the Moon look different shapes at different times of the month?",
                "lesson": "The Moon doesn't change shape — but as it orbits Earth, we see [bold yellow]different amounts of its sunlit side[/bold yellow]. When we see the whole lit side, it's a full moon. When we see none of it, it's a new moon. In between are the quarters and crescents!",
                "options": ["The Moon shrinks and grows", "The Earth's shadow always covers part of it", "We see different amounts of the Moon's sunlit side as it orbits Earth", "Clouds slowly eat the Moon and spit it back out"],
                "answer": "c",
                "hints": ["The Moon is always a sphere — it just looks different from where we're standing!", "Think of shining a light on a ball and walking around it — different amounts of the lit side would show!"],
                "xp": 35,
            },
            {
                "id": "es_boss",
                "title": "What Are Stars?",
                "type": "quiz",
                "question": "Stars look like tiny dots, but what are they really?",
                "lesson": "Stars are [bold yellow]enormous balls of glowing gas — just like our Sun![/bold yellow] They look tiny because they are incredibly far away. Our Sun is a star — the closest one to Earth. On a clear night, every single star you see is a sun, far, far away. Isn't that AMAZING?",
                "options": ["Holes in the sky where light shines through", "Chunks of glowing ice floating in space", "Enormous balls of glowing gas, just like our Sun, only very far away", "Lights left on by astronauts"],
                "answer": "c",
                "hints": ["The Sun is a star — just the closest one to us!", "Every tiny dot you see at night is a giant glowing ball like our Sun — just vastly far away."],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "matter_and_energy": {
        "id": "matter_and_energy",
        "name": "The Matter Lab",
        "subtitle": "Solid, liquid, and gas — and how they change",
        "icon": "🧊",
        "description": "Explore the three states of matter and how they transform",
        "level_required": 7,
        "challenges": [
            {
                "id": "me_01",
                "title": "Solids",
                "type": "quiz",
                "question": "What is special about a solid?",
                "lesson": "A [bold yellow]solid[/bold yellow] has a definite shape and size. You can't pour it into a different shape the way you can pour water. Rocks, wood, ice, and your pencil are all solids — they hold their shape!",
                "options": ["It fills whatever container you put it in", "It floats in the air", "It has a definite shape and keeps that shape", "It can only be touched, not seen"],
                "answer": "c",
                "hints": ["If you move a rock from one bowl to another, does its shape change?", "Solids keep their own shape — they don't pour!"],
                "xp": 25,
            },
            {
                "id": "me_02",
                "title": "Liquids",
                "type": "quiz",
                "question": "What happens when you pour water into a differently shaped cup?",
                "lesson": "A [bold yellow]liquid[/bold yellow] takes the shape of whatever container it's in. Water in a tall thin glass is tall and thin. The same water in a wide bowl is wide and flat. Liquids flow and change shape, but they always take up the same amount of space!",
                "options": ["It stays the same shape it was before", "It disappears into the cup", "It takes the shape of the new cup", "It turns into a solid"],
                "answer": "c",
                "hints": ["Pour water from a bottle into a bowl — what does the water look like now?", "Liquids flow and take the shape of their container!"],
                "xp": 25,
            },
            {
                "id": "me_03",
                "title": "Gases",
                "type": "quiz",
                "question": "What does a gas do when released into a room?",
                "lesson": "A [bold yellow]gas[/bold yellow] expands to fill all the available space. That's why you can smell something across the whole room — the scent molecules (a gas) spread out to fill everywhere. Air is a gas, and it fills every corner of a room!",
                "options": ["It sinks to the floor and stays there", "It stays in one corner of the room", "It spreads out to fill all the available space", "It turns into a liquid right away"],
                "answer": "c",
                "hints": ["When someone opens a bag of popcorn, can you smell it from across the room?", "Gas spreads out to fill every bit of available space!"],
                "xp": 25,
            },
            {
                "id": "me_04",
                "title": "Melting",
                "type": "quiz",
                "question": "When ice warms up and turns into liquid water, what is this called?",
                "lesson": "[bold yellow]Melting[/bold yellow] is when a solid turns into a liquid because it gets warmer. Ice melts into water. Butter melts in a warm pan. Chocolate melts in your hands! Heat gives the tiny particles in a solid enough energy to flow freely.",
                "options": ["Freezing", "Evaporating", "Melting", "Condensing"],
                "answer": "c",
                "hints": ["Ice on a warm day — does it get harder or does it go soft and wet?", "Solid → liquid when it warms up = melting!"],
                "xp": 30,
            },
            {
                "id": "me_05",
                "title": "Freezing",
                "type": "quiz",
                "question": "When liquid water gets very cold, it turns into ice. What is this called?",
                "lesson": "[bold yellow]Freezing[/bold yellow] is when a liquid turns into a solid because it gets colder. Water freezes into ice. The cold slows down the tiny moving particles until they lock into place and form a solid.",
                "options": ["Melting", "Freezing", "Evaporating", "Boiling"],
                "answer": "b",
                "hints": ["What happens to water when you put it in a freezer overnight?", "Liquid → solid when it cools down = freezing!"],
                "xp": 30,
            },
            {
                "id": "me_boss",
                "title": "Evaporation",
                "type": "quiz",
                "question": "After rain, puddles slowly disappear even on a cool day. Where does the water go?",
                "lesson": "[bold yellow]Evaporation[/bold yellow] is when liquid water turns into water vapor (a gas) and rises into the air. It happens whenever water is exposed to air — even without boiling. The sun speeds it up! This is how water gets into the clouds to make rain later.",
                "options": ["The ground drinks the water", "It turns into ice underground", "It evaporates — turns into water vapor (a gas) and rises into the air", "Worms carry it away"],
                "answer": "c",
                "hints": ["Have you ever seen a wet shirt dry in the sun? Where did the water go?", "Liquid water turns into invisible water vapor and floats up into the sky — evaporation!"],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "weather_watch": {
        "id": "weather_watch",
        "name": "The Weather Watchtower",
        "subtitle": "Read the sky like a story",
        "icon": "🌦️",
        "description": "Learn to understand clouds, wind, seasons, and storms",
        "level_required": 8,
        "challenges": [
            {
                "id": "ww_01",
                "title": "Dark Puffy Clouds",
                "type": "quiz",
                "question": "What do dark, puffy clouds usually bring?",
                "lesson": "[bold yellow]Dark, puffy clouds[/bold yellow] are called cumulonimbus clouds. They're full of water droplets and often bring rain — and sometimes thunder and lightning!",
                "options": ["Sunshine", "Rain", "Snow", "Nothing"],
                "answer": "b",
                "hints": ["Dark clouds are heavy with water — what do you think comes next?", "When clouds look dark and puffy, it's usually time to find an umbrella!"],
                "xp": 25,
            },
            {
                "id": "ww_02",
                "title": "What Is Wind?",
                "type": "quiz",
                "question": "What is wind?",
                "lesson": "[bold yellow]Wind is moving air.[/bold yellow] When air warms up it rises, and cooler air rushes in to take its place. That movement is what we feel as wind!",
                "options": ["Moving water", "Moving air", "Falling leaves", "Spinning clouds"],
                "answer": "b",
                "hints": ["You can't see it, but you can feel it — and it's everywhere!", "Wind is just air that's on the move!"],
                "xp": 25,
            },
            {
                "id": "ww_03",
                "title": "Snowy Season",
                "type": "quiz",
                "question": "Which season has the most snow?",
                "lesson": "In [bold yellow]winter[/bold yellow], temperatures drop the lowest — low enough for water in clouds to freeze into snowflakes before falling. That's why winter is the snowy season!",
                "options": ["Spring", "Summer", "Fall", "Winter"],
                "answer": "d",
                "hints": ["Think about when you bundle up the most!", "Snow needs very cold temperatures — which season is coldest?"],
                "xp": 25,
            },
            {
                "id": "ww_04",
                "title": "Making a Rainbow",
                "type": "quiz",
                "question": "What makes a rainbow?",
                "lesson": "A rainbow forms when [bold yellow]sunlight shines through raindrops[/bold yellow]. Each tiny drop acts like a tiny prism, splitting the white sunlight into all its hidden colors: red, orange, yellow, green, blue, and violet!",
                "options": ["Clouds + wind", "Sun + rain", "Moon + stars", "Thunder + lightning"],
                "answer": "b",
                "hints": ["You need sunshine AND rain at the same time — have you noticed that?", "Raindrops split sunlight into all the colors of the rainbow!"],
                "xp": 30,
            },
            {
                "id": "ww_05",
                "title": "Spinning Storm",
                "type": "quiz",
                "question": "What do we call a very strong spinning wind storm?",
                "lesson": "A [bold yellow]tornado[/bold yellow] is a powerful column of spinning air that reaches from a storm cloud down to the ground. Tornadoes can be very dangerous because the spinning winds are so strong.",
                "options": ["Hurricane", "Blizzard", "Tornado", "Drought"],
                "answer": "c",
                "hints": ["This one spins like a top from the cloud all the way to the ground!", "A tornado is a funnel of spinning wind reaching down from the sky."],
                "xp": 30,
            },
            {
                "id": "ww_boss",
                "title": "Freezing Point",
                "type": "quiz",
                "question": "If the temperature is 32°F (0°C), what might fall from the sky?",
                "lesson": "At [bold yellow]32°F (0°C)[/bold yellow], water freezes. That means water droplets in clouds can freeze into snowflakes and fall as snow. This temperature is called the freezing point — below it, you get snow; above it, you get rain!",
                "options": ["Rain", "Hail", "Snow", "Fog"],
                "answer": "c",
                "hints": ["32°F is exactly the freezing point of water!", "At the freezing point, water turns to ice — so those droplets fall as snow!"],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "animal_world": {
        "id": "animal_world",
        "name": "The Animal Kingdom",
        "subtitle": "Every creature has something amazing about it",
        "icon": "🐾",
        "description": "Explore the amazing world of animals",
        "level_required": 9,
        "challenges": [
            {
                "id": "aw_01",
                "title": "Plant Eaters",
                "type": "quiz",
                "question": "What do we call animals that only eat plants?",
                "lesson": "[bold yellow]Herbivores[/bold yellow] are animals that eat only plants — grasses, leaves, fruits, seeds. Rabbits, deer, and cows are all herbivores. The word comes from the Latin for 'plant' (herba) and 'to eat' (vorare).",
                "options": ["Carnivores", "Omnivores", "Herbivores", "Predators"],
                "answer": "c",
                "hints": ["The word starts with 'herb' — like herbs and plants!", "Her-bi-vore: an animal that eats plants!"],
                "xp": 25,
            },
            {
                "id": "aw_02",
                "title": "Which Is a Mammal?",
                "type": "quiz",
                "question": "Which of these animals is a mammal?",
                "lesson": "[bold yellow]Dolphins are mammals![/bold yellow] Even though they live in the ocean, dolphins breathe air, give birth to live babies, and feed them milk — just like land mammals. Being a mammal isn't about where you live, it's about how your body works.",
                "options": ["Frog", "Eagle", "Dolphin", "Salmon"],
                "answer": "c",
                "hints": ["Mammals breathe air — even in the ocean!", "Dolphins come to the surface to breathe — they're mammals just like us!"],
                "xp": 25,
            },
            {
                "id": "aw_03",
                "title": "What Makes a Mammal?",
                "type": "quiz",
                "question": "What is special about mammals?",
                "lesson": "Mammals [bold yellow]feed their babies milk[/bold yellow] — and that's the most special thing about them! They also breathe air, are warm-blooded, and most have hair or fur. Humans, dogs, whales, and bats are all mammals.",
                "options": ["They have feathers", "They lay eggs", "They feed babies milk", "They breathe underwater"],
                "answer": "c",
                "hints": ["Think about how a kitten or puppy gets its first food!", "Mammals feed their young with milk — that's what makes them mammals!"],
                "xp": 30,
            },
            {
                "id": "aw_04",
                "title": "Caterpillar to What?",
                "type": "quiz",
                "question": "What do caterpillars turn into?",
                "lesson": "Caterpillars go through an amazing change called [bold yellow]metamorphosis[/bold yellow]. They wrap themselves in a chrysalis and — through an incredible transformation — emerge as beautiful butterflies! It's one of nature's most magical changes.",
                "options": ["Beetles", "Butterflies", "Dragonflies", "Moths"],
                "answer": "b",
                "hints": ["Have you ever seen a chrysalis hanging from a leaf?", "Caterpillar → chrysalis → butterfly: that's metamorphosis!"],
                "xp": 30,
            },
            {
                "id": "aw_05",
                "title": "An Amphibian",
                "type": "quiz",
                "question": "Which of these is an amphibian?",
                "lesson": "[bold yellow]Frogs are amphibians![/bold yellow] Amphibians are animals that start life in water (breathing through gills) and grow to live on land (breathing with lungs). The word 'amphibian' comes from the Greek for 'both lives' — because they live in two worlds!",
                "options": ["Snake", "Frog", "Fish", "Turtle"],
                "answer": "b",
                "hints": ["This animal starts life in the water and later lives on land!", "Frogs live in two worlds — amphibians do!"],
                "xp": 30,
            },
            {
                "id": "aw_boss",
                "title": "Warm vs Cold Blooded",
                "type": "quiz",
                "question": "What is the difference between a cold-blooded and warm-blooded animal?",
                "lesson": "[bold yellow]Cold-blooded animals use the environment for heat.[/bold yellow] A lizard sits in the sun to warm up because its body can't make its own heat. Warm-blooded animals (like us!) generate their own body heat from the inside, no matter the temperature outside.",
                "options": ["Cold-blooded animals make their own heat", "Warm-blooded animals use the sun for heat", "Cold-blooded animals use the environment for heat", "There is no difference"],
                "answer": "c",
                "hints": ["Have you ever seen a lizard sunbathing on a rock? Why does it do that?", "Cold-blooded means your body temperature matches the world around you!"],
                "xp": 70,
                "is_boss": True,
            },
        ],
    },

    "the_human_body": {
        "id": "the_human_body",
        "name": "The Body Map",
        "description": "Explore the amazing systems inside your own body",
        "level_required": 10,
        "challenges": [
            {
                "id": "hb_01",
                "title": "The Heart",
                "type": "quiz",
                "question": "What does your heart do?",
                "lesson": "Your [bold yellow]heart[/bold yellow] is a muscle that [bold white]pumps blood through your body[/bold white]. It beats about 100,000 times every day, sending blood — and the oxygen and nutrients it carries — to every part of you.",
                "options": ["helps you breathe", "pumps blood through your body", "helps you think", "makes you grow"],
                "answer": "b",
                "hints": ["Put your hand on your chest. Feel that? That's your heart working!", "The heart is like a pump — it pushes blood through tubes called blood vessels."],
                "xp": 30,
            },
            {
                "id": "hb_02",
                "title": "Bones",
                "type": "quiz",
                "question": "How many bones does an adult human body have?",
                "lesson": "An adult human body has [bold yellow]about 206 bones[/bold yellow]. Babies are born with around 270 bones, but many fuse together as we grow. Your bones give your body its shape and protect your organs!",
                "options": ["about 100", "about 206", "about 300", "about 50"],
                "answer": "b",
                "hints": ["It's more than 100 but fewer than 300.", "The number is between 200 and 210."],
                "xp": 30,
            },
            {
                "id": "hb_03",
                "title": "The Lungs",
                "type": "quiz",
                "question": "What do your lungs do?",
                "lesson": "Your [bold yellow]lungs[/bold yellow] are like two spongy bags inside your chest. Every time you breathe in, they take in [bold white]oxygen[/bold white]. Every time you breathe out, they push out [bold white]carbon dioxide[/bold white]. Your body needs oxygen to stay alive!",
                "options": ["pump blood", "help you move", "bring oxygen in and send carbon dioxide out", "digest food"],
                "answer": "c",
                "hints": ["Take a deep breath. What are you filling up?", "Lungs breathe in the good stuff (oxygen) and breathe out what the body doesn't need."],
                "xp": 30,
            },
            {
                "id": "hb_04",
                "title": "The Brain",
                "type": "quiz",
                "question": "What organ controls everything your body does, including thinking?",
                "lesson": "The [bold yellow]brain[/bold yellow] is the control center of your whole body. It handles your thoughts, memories, and feelings — and it also controls your heartbeat, breathing, and movement, even while you sleep!",
                "options": ["the heart", "the stomach", "the lungs", "the brain"],
                "answer": "d",
                "hints": ["It's inside your head, protected by your skull.", "You're using it right now to answer this question!"],
                "xp": 30,
            },
            {
                "id": "hb_05",
                "title": "Muscles",
                "type": "quiz",
                "question": "What do muscles do?",
                "lesson": "[bold yellow]Muscles[/bold yellow] make your body move. They pull on your bones when they contract (tighten). You have over 600 muscles — from the big ones in your legs to the tiny ones that move your eyes!",
                "options": ["pump blood", "help your body move", "store energy", "filter air"],
                "answer": "b",
                "hints": ["Flex your arm. Feel that hard part? That's a muscle tightening up!", "Muscles are attached to bones and pull them to create movement."],
                "xp": 30,
            },
            {
                "id": "hb_boss",
                "title": "Healthy Habits",
                "type": "quiz",
                "question": "Which of these is a healthy habit for your body?",
                "lesson": "[bold yellow]Sleeping 8–10 hours and drinking water[/bold yellow] are two of the most important things you can do for your body. Sleep lets your brain and body repair and grow. Water keeps every system running smoothly. Simple habits — big difference!",
                "options": ["eating only sweets", "sleeping 8-10 hours and drinking water", "watching screens all day", "skipping meals"],
                "answer": "b",
                "hints": ["Your body needs rest and water to do its best work.", "Think about what makes you feel strong, awake, and well."],
                "xp": 60,
                "is_boss": True,
            },
        ],
    },
    "ecosystems_and_food_chains": {
        "id": "ecosystems_and_food_chains",
        "name": "Ecosystems and Food Chains",
        "description": "How living things depend on each other and their environment",
        "level_required": 1,
        "challenges": [
            {
                "id": "ec_01",
                "title": "What Is an Ecosystem?",
                "type": "quiz",
                "question": "An ecosystem is all the living things in an area PLUS the non-living things (water, soil, sunlight, air). Which of these is an example of an ecosystem?",
                "lesson": "An [bold yellow]ecosystem[/bold yellow] includes [bold white]everything[/bold white] in an area — the plants, animals, fungi, bacteria, AND the water, rocks, air, and sunlight. A pond, a forest, a desert, even your backyard is an ecosystem. Everything in it is connected: change one part and everything else is affected.",
                "options": ["a library", "a rainforest", "a shopping mall", "a car"],
                "answer": "b",
                "hints": ["An ecosystem must include living AND non-living things interacting together.", "Think of a place where plants, animals, water, and sunlight all work together."],
                "xp": 30,
            },
            {
                "id": "ec_02",
                "title": "Producers",
                "type": "quiz",
                "question": "Plants are called 'producers' in a food chain. Why?",
                "lesson": "[bold yellow]Producers[/bold yellow] are living things that make their own food using sunlight, water, and air — through [bold white]photosynthesis[/bold white]. They are the foundation of almost every food chain on Earth. Without producers, there would be no energy for animals to eat.",
                "options": [
                    "They produce baby plants very quickly",
                    "They make their own food from sunlight and are the base of the food chain",
                    "They produce oxygen only, not food",
                    "They grow faster than animals",
                ],
                "answer": "b",
                "hints": ["The word 'producer' means something that creates or makes.", "They turn sunlight into energy — that energy flows to everything that eats them."],
                "xp": 30,
            },
            {
                "id": "ec_03",
                "title": "Herbivores, Carnivores, Omnivores",
                "type": "fill_blank",
                "question": "An animal that eats ONLY plants is called a _____ (starts with 'h').",
                "lesson": "[bold yellow]Herbivores[/bold yellow] eat only plants (rabbits, deer, horses). [bold yellow]Carnivores[/bold yellow] eat only meat (wolves, eagles, sharks). [bold yellow]Omnivores[/bold yellow] eat both plants and animals (bears, humans, crows). These feeding habits determine where each animal sits in the food chain.",
                "answer": "herbivore",
                "hints": ["'Herbi' comes from the Latin word for grass or plants.", "Rabbits and deer are examples."],
                "xp": 30,
            },
            {
                "id": "ec_04",
                "title": "The Food Chain",
                "type": "quiz",
                "question": "In the food chain: grass → rabbit → fox → eagle — what would happen if all the rabbits disappeared?",
                "lesson": "In a [bold yellow]food chain[/bold yellow], each link depends on the others. If rabbits disappeared, foxes would have less food (their population would drop), and eagles would have fewer foxes to hunt. The grass might grow more with no one eating it. This is why the loss of [bold white]one species can affect the entire ecosystem[/bold white] — everything is connected.",
                "options": [
                    "Nothing would change",
                    "Foxes and eagles would have less food; grass might overgrow",
                    "Only eagles would be affected",
                    "The grass would disappear too",
                ],
                "answer": "b",
                "hints": ["Think about what happens to the animals that eat rabbits if rabbits are gone.", "And think about what happens to the grass if nothing is eating it."],
                "xp": 30,
            },
            {
                "id": "ec_05",
                "title": "Decomposers",
                "type": "quiz",
                "question": "When animals and plants die, they are broken down into nutrients that go back into the soil. The living things that do this important job are called:",
                "lesson": "[bold yellow]Decomposers[/bold yellow] — fungi and bacteria — break down dead material and return nutrients to the soil, which feeds new plants. Without decomposers, dead things would pile up forever and the nutrients they contain would be locked away. Decomposers complete the cycle of life!",
                "options": ["Producers", "Carnivores", "Decomposers", "Herbivores"],
                "answer": "c",
                "hints": ["They break things down — 'de-compose' means to come apart.", "Mushrooms and certain bacteria are examples."],
                "xp": 30,
            },
            {
                "id": "ec_boss",
                "title": "The Keystone Species",
                "type": "quiz",
                "question": "A 'keystone species' is one whose presence is so important that removing it causes the whole ecosystem to collapse — like pulling the keystone from an arch. In Yellowstone, wolves were removed and came back. When they returned, they changed the rivers too (by changing where deer grazed). This shows that ecosystems are:",
                "lesson": "[bold yellow]Keystone species[/bold yellow] hold ecosystems together. When wolves were removed from Yellowstone, deer overgrazed rivers, trees disappeared, and riverbanks eroded. When wolves returned, deer moved more, plants grew back, and rivers stabilized. This is called a [bold white]trophic cascade[/bold white] — a chain reaction through the food web. Every species matters!",
                "options": [
                    "Simple — one change only affects one other thing",
                    "Deeply interconnected — one change can ripple through the entire system",
                    "Stable — they usually bounce back without needing help",
                    "Unpredictable — there's no way to know what will happen",
                ],
                "answer": "b",
                "hints": ["Think about the wolf story — the wolves changed the rivers! How many steps was that?", "Ecosystems are webs, not chains — everything touches everything else."],
                "xp": 60,
                "is_boss": True,
            },
        ],
    },
}
