"""
zones.py — Culture zones and challenges for the Culture skill pack.

All challenges use "type": "quiz" with multiple-choice options.
Guided by 龙龙 (Lóng Lóng), a friendly dragon guide.
"""

ZONE_ORDER = [
    "chinese_festivals",
    "zodiac",
    "calligraphy",
    "tea_culture",
    "martial_arts",
    "modern_china",
    "idioms_chengyu",
]

ZONES = {
    "chinese_festivals": {
        "id": "chinese_festivals",
        "name": "Celebrate! — 节日",
        "description": "Learn about China's most important festivals",
        "level_required": 1,
        "challenges": [
            {
                "id": "fest_spring",
                "title": "The Biggest Holiday",
                "type": "quiz",
                "question": "春节 (Chūnjié) is the most important Chinese holiday. What is it?",
                "options": ["Spring Festival / Chinese New Year", "Dragon Boat Festival", "Mid-Autumn Festival", "Lantern Festival"],
                "answer": "a",
                "hints": [
                    "春 means 'spring' and 节 means 'festival.'",
                    "It falls between January 21 and February 20 based on the lunar calendar.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "春节 (Chūnjié) = Spring Festival / Chinese New Year. It's the biggest holiday in the world — over a billion people celebrate! Traditions include 红包 (red envelopes), 饺子 (dumplings), 春联 (couplets), and 放鞭炮 (firecrackers).",
                "is_boss": False,
                "flavor": "龙龙 dances through a shower of red and gold firecrackers.",
            },
            {
                "id": "fest_mid_autumn",
                "title": "The Moon Festival",
                "type": "quiz",
                "question": "中秋节 (Zhōngqiūjié) is celebrated by eating 月饼 (yuèbǐng). What are 月饼?",
                "options": ["Rice dumplings", "Mooncakes", "Tangyuan (sweet rice balls)", "Zongzi (rice wraps)"],
                "answer": "b",
                "hints": [
                    "月 means 'moon' and 饼 means 'cake/pastry.'",
                    "They're round to symbolize the full moon and family reunion.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "中秋节 (Zhōngqiūjié) = Mid-Autumn Festival. Families gather to eat 月饼 (mooncakes) and admire the full moon. The legend of 嫦娥 (Cháng'é), the Moon Goddess, is told on this night. It falls on the 15th of the 8th lunar month.",
                "is_boss": False,
                "flavor": "龙龙 gazes at the full moon with a mooncake in each claw.",
            },
            {
                "id": "fest_dragon_boat",
                "title": "Racing on the Water",
                "type": "quiz",
                "question": "端午节 (Duānwǔjié) features dragon boat races and 粽子 (zòngzi). What are 粽子?",
                "options": [
                    "Mooncakes",
                    "Sticky rice wrapped in bamboo leaves",
                    "Steamed buns",
                    "Spring rolls",
                ],
                "answer": "b",
                "hints": [
                    "粽子 are pyramid-shaped parcels of sticky rice with various fillings.",
                    "The festival honors the poet Qu Yuan (屈原), who drowned himself in protest.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "端午节 (Duānwǔjié) = Dragon Boat Festival (5th day of 5th lunar month). People eat 粽子 (sticky rice in bamboo leaves) and race 龙舟 (dragon boats). It commemorates the poet 屈原 (Qū Yuán), who drowned in 278 BC. Now a UNESCO Intangible Cultural Heritage!",
                "is_boss": False,
                "flavor": "龙龙 serves as the figurehead of a dragon boat, looking very proud.",
            },
            {
                "id": "fest_lantern",
                "title": "Lights in the Night",
                "type": "quiz",
                "question": "元宵节 (Yuánxiāojié) — the Lantern Festival — marks the end of Chinese New Year celebrations. When is it?",
                "options": [
                    "1st day of the 1st lunar month",
                    "15th day of the 1st lunar month",
                    "5th day of the 5th lunar month",
                    "15th day of the 8th lunar month",
                ],
                "answer": "b",
                "hints": [
                    "元宵 means 'first night' — the first full moon of the new year!",
                    "People eat 汤圆 (tāngyuán, sweet rice balls) and solve riddles on lanterns.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "元宵节 (Yuánxiāojié) = Lantern Festival. 15th of the 1st lunar month — the first full moon of the year. Traditions: 看花灯 (viewing lanterns), 猜灯谜 (solving lantern riddles), 吃汤圆 (eating sweet rice balls for family unity).",
                "is_boss": False,
                "flavor": "龙龙 floats among thousands of glowing paper lanterns.",
            },
            {
                "id": "fest_greeting",
                "title": "New Year Greetings",
                "type": "quiz",
                "question": "新年快乐 (Xīnnián kuàilè) means 'Happy New Year.' What does 恭喜发财 (Gōngxǐ fācái) mean?",
                "options": [
                    "May you be healthy",
                    "May you have good luck",
                    "Wishing you prosperity / May you get rich",
                    "May your family grow",
                ],
                "answer": "c",
                "hints": [
                    "恭喜 = congratulations, 发财 = get rich/become prosperous.",
                    "This is the most famous Chinese New Year greeting!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "恭喜发财 (Gōngxǐ fācái) = Wishing you prosperity! The most iconic CNY greeting. In Cantonese: 'Gung Hei Fat Choi.' Often followed by 红包拿来! (Hóngbāo ná lái! — Give me a red envelope!) by cheeky children!",
                "is_boss": True,
                "flavor": "龙龙 hands out red envelopes left and right. '恭喜发财! 红包拿来!'",
            },
        ],
    },
    "zodiac": {
        "id": "zodiac",
        "name": "The Twelve Animals — 十二生肖",
        "description": "Master the Chinese zodiac — animals, years, and personality traits",
        "level_required": 2,
        "challenges": [
            {
                "id": "zodiac_animals_all",
                "title": "The Complete Twelve",
                "type": "quiz",
                "question": "Which is the correct order of the first six Chinese zodiac animals?",
                "options": [
                    "鼠 Rat, 牛 Ox, 虎 Tiger, 兔 Rabbit, 龙 Dragon, 蛇 Snake",
                    "龙 Dragon, 虎 Tiger, 鼠 Rat, 牛 Ox, 蛇 Snake, 兔 Rabbit",
                    "虎 Tiger, 龙 Dragon, 蛇 Snake, 鼠 Rat, 兔 Rabbit, 牛 Ox",
                    "牛 Ox, 鼠 Rat, 兔 Rabbit, 虎 Tiger, 蛇 Snake, 龙 Dragon",
                ],
                "answer": "a",
                "hints": [
                    "The rat won the race by riding on the ox's back!",
                    "The dragon is 5th — after rabbit, before snake.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "The 12 animals in order: 鼠(Rat), 牛(Ox), 虎(Tiger), 兔(Rabbit), 龙(Dragon), 蛇(Snake), 马(Horse), 羊(Goat), 猴(Monkey), 鸡(Rooster), 狗(Dog), 猪(Pig). Each animal has personality traits associated with it.",
                "is_boss": False,
                "flavor": "龙龙 lines up tiny smoke sculptures of all 12 animals.",
            },
            {
                "id": "zodiac_year_calc",
                "title": "Which Year Is Yours?",
                "type": "quiz",
                "question": "If 2024 is the Year of the Dragon (龙), what animal year is 2025?",
                "options": ["兔 Rabbit", "蛇 Snake", "马 Horse", "虎 Tiger"],
                "answer": "b",
                "hints": [
                    "The zodiac follows a fixed order: ...Rabbit, Dragon, Snake, Horse...",
                    "After Dragon comes Snake — every time, no exceptions.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "2025 is the Year of the Snake (蛇年, shénián). The cycle never changes: after Dragon always comes Snake. To find your zodiac: if you know any year's animal, count forward or backward by position. 2024=Dragon, 2025=Snake, 2026=Horse...",
                "is_boss": False,
                "flavor": "龙龙 passes the baton to a graceful snake. 'Your turn, my friend!'",
            },
            {
                "id": "zodiac_dragon_traits",
                "title": "Dragon Personality",
                "type": "quiz",
                "question": "People born in the Year of the Dragon (龙年) are traditionally said to be...?",
                "options": [
                    "Shy, quiet, and cautious",
                    "Confident, ambitious, and charismatic",
                    "Patient, stubborn, and reliable",
                    "Funny, playful, and mischievous",
                ],
                "answer": "b",
                "hints": [
                    "The dragon is the most powerful and auspicious zodiac animal.",
                    "Dragon year babies are considered especially lucky and destined for greatness.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Dragon people are said to be: confident, ambitious, charismatic, energetic, and lucky. Birth rates actually spike in Dragon years in China! Famous Dragon year people include Bruce Lee, John Lennon, and many Chinese emperors.",
                "is_boss": False,
                "flavor": "龙龙 puffs up with pride. 'Naturally, dragon people are the best!'",
            },
            {
                "id": "zodiac_rat_traits",
                "title": "The Clever Rat",
                "type": "quiz",
                "question": "The Rat (鼠) is first in the zodiac because of its...?",
                "options": ["Strength", "Speed", "Cleverness", "Beauty"],
                "answer": "c",
                "hints": [
                    "The rat outsmarted the much larger ox in the legendary race.",
                    "Rat year people are said to be quick-witted, resourceful, and adaptable.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "Rat (鼠) people are considered: clever, resourceful, quick-witted, and adaptable. The rat earned first place through brains, not brawn — riding the ox and jumping ahead at the last moment. 鼠年 (shǔnián) = Year of the Rat.",
                "is_boss": False,
                "flavor": "龙龙 narrates the legend of the rat's clever trick.",
            },
            {
                "id": "zodiac_ben_ming_nian",
                "title": "Your Zodiac Year Returns",
                "type": "quiz",
                "question": "本命年 (běnmìngnián) is when your zodiac animal year comes back around. How often does this happen?",
                "options": ["Every 10 years", "Every 12 years", "Every 8 years", "Every 15 years"],
                "answer": "b",
                "hints": [
                    "There are 12 zodiac animals, so the cycle repeats every 12 years.",
                    "Your 本命年 happens at ages 12, 24, 36, 48, 60...",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "本命年 (běnmìngnián) = your zodiac year. It comes every 12 years and is considered UNLUCKY — you must wear red underwear the entire year for protection! At age 60, you complete the full cycle (五个本命年), which is a major celebration.",
                "is_boss": False,
                "flavor": "龙龙 whispers conspiratorially. 'Always wear red underwear in your 本命年!'",
            },
            {
                "id": "zodiac_compatibility",
                "title": "Zodiac Matchmaking",
                "type": "quiz",
                "question": "In Chinese zodiac compatibility, which animal is traditionally considered the Dragon's best match?",
                "options": ["虎 Tiger", "鼠 Rat", "狗 Dog", "兔 Rabbit"],
                "answer": "b",
                "hints": [
                    "The Rat's cleverness complements the Dragon's power.",
                    "Rat and Dragon are traditionally one of the most compatible pairs.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Dragon + Rat is a classic compatible pair! Chinese zodiac compatibility (属相配对, shǔxiàng pèiduì) is still consulted for marriages. The six harmonious pairs: Rat-Ox, Tiger-Pig, Rabbit-Dog, Dragon-Rooster, Snake-Monkey, Horse-Goat. But every system has variations!",
                "is_boss": True,
                "flavor": "龙龙 and a tiny rat high-five. 'Best friends forever! 最佳拍档!'",
            },
        ],
    },
    "calligraphy": {
        "id": "calligraphy",
        "name": "The Art of Writing — 书法",
        "description": "Discover Chinese calligraphy — brush, ink, and character structure",
        "level_required": 3,
        "challenges": [
            {
                "id": "calli_four_treasures",
                "title": "Tools of the Art",
                "type": "quiz",
                "question": "文房四宝 (Wénfáng Sì Bǎo) — the 'Four Treasures of the Study' — are the essential calligraphy tools. Which is NOT one of them?",
                "options": ["笔 (bǐ) — Brush", "墨 (mò) — Ink", "尺 (chǐ) — Ruler", "砚 (yàn) — Inkstone"],
                "answer": "c",
                "hints": [
                    "The four treasures are: brush, ink, paper, and inkstone.",
                    "A ruler is useful but not part of the traditional four.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "文房四宝 = Four Treasures of the Study: 笔 (brush), 墨 (ink stick), 纸 (paper), 砚 (inkstone). These four items define Chinese calligraphy. The brush is held vertically, not at an angle like a Western pen!",
                "is_boss": False,
                "flavor": "龙龙 arranges brush, ink, paper, and inkstone with ceremonial care.",
            },
            {
                "id": "calli_brush",
                "title": "The Brush",
                "type": "quiz",
                "question": "毛笔 (máobǐ) means 'calligraphy brush.' What does 毛 literally mean?",
                "options": ["Paint", "Hair / fur", "Bamboo", "Feather"],
                "answer": "b",
                "hints": [
                    "Calligraphy brushes are traditionally made from animal hair.",
                    "毛 appears in 毛衣 (máoyī, sweater — 'hair clothes').",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "毛笔 (máobǐ) = calligraphy brush. 毛 = hair/fur, 笔 = pen/writing tool. Brushes are made from animal hair: 羊毫 (goat hair — soft), 狼毫 (wolf/weasel hair — firm), 兼毫 (mixed). The brush was invented over 2,000 years ago!",
                "is_boss": False,
                "flavor": "龙龙 dips a brush made from its own whisker into ink.",
            },
            {
                "id": "calli_ink",
                "title": "Black as Night",
                "type": "quiz",
                "question": "墨 (mò) is ink. How was traditional Chinese ink prepared?",
                "options": [
                    "Mixed from chemicals in a bottle",
                    "Ground from a solid ink stick on an inkstone with water",
                    "Extracted from squid",
                    "Boiled from tree bark",
                ],
                "answer": "b",
                "hints": [
                    "The inkstone (砚) is used to grind the ink stick with water.",
                    "This meditative grinding process is considered part of the art itself.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "Traditional ink is made by grinding a 墨条 (ink stick, made from soot and glue) on a 砚 (inkstone) with water. The grinding is meditative and calming — it prepares the mind for writing. The best ink sticks are from 徽墨 (Anhui province).",
                "is_boss": False,
                "flavor": "龙龙 slowly grinds ink, looking peaceful for once.",
            },
            {
                "id": "calli_strokes",
                "title": "The Basic Strokes",
                "type": "quiz",
                "question": "How many basic strokes (基本笔画, jīběn bǐhuà) are there in Chinese calligraphy?",
                "options": ["4", "6", "8", "12"],
                "answer": "c",
                "hints": [
                    "The character 永 (yǒng, eternal) is famous because it contains all basic strokes.",
                    "The 永字八法 (Yǒngzì Bāfǎ) — 'Eight Principles of Yong' — is a classic teaching method.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "There are 8 basic strokes, all found in 永 (yǒng, eternal): 横 (héng, horizontal), 竖 (shù, vertical), 撇 (piě, left-falling), 捺 (nà, right-falling), 点 (diǎn, dot), 折 (zhé, turning), 钩 (gōu, hook), 提 (tí, rising). Master these 8, and you can write any character!",
                "is_boss": False,
                "flavor": "龙龙 writes 永 with perfect form. 'One character, eight strokes, infinite beauty!'",
            },
            {
                "id": "calli_structure",
                "title": "Building Blocks",
                "type": "quiz",
                "question": "Chinese characters are built from components. What is a 偏旁 (piānpáng)?",
                "options": [
                    "A full character",
                    "A radical / component that gives meaning or pronunciation clues",
                    "A punctuation mark",
                    "A calligraphy style",
                ],
                "answer": "b",
                "hints": [
                    "偏旁 are the building blocks — like 氵(water), 女 (woman), 口 (mouth).",
                    "Knowing radicals helps you guess the meaning of unknown characters.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "偏旁 (piānpáng) = radical/component. Chinese characters are modular! 氵= water (in 河, 海, 洗), 女 = woman (in 妈, 姐, 好), 口 = mouth (in 吃, 喝, 唱). There are ~214 radicals — knowing them is the key to reading Chinese!",
                "is_boss": False,
                "flavor": "龙龙 assembles a character from its component parts like building blocks.",
            },
            {
                "id": "calli_styles",
                "title": "The Five Scripts",
                "type": "quiz",
                "question": "草书 (cǎoshū) is a calligraphy style where characters are extremely fluid and connected. What does 草 mean?",
                "options": ["Gold", "Formal", "Grass / cursive", "Ancient"],
                "answer": "c",
                "hints": [
                    "草 means 'grass' — the style flows like grass in the wind.",
                    "草书 is the hardest to read but the most expressive to write.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "Chinese calligraphy has 5 major scripts: 篆书 (seal), 隶书 (clerical), 楷书 (regular — the one you learn first), 行书 (running/semi-cursive), 草书 (grass/cursive — the wildest). Each tells the story of how Chinese writing evolved over 3,000+ years.",
                "is_boss": True,
                "flavor": "龙龙 writes the same character in five different styles. 'Same word, five personalities!'",
            },
        ],
    },
    "tea_culture": {
        "id": "tea_culture",
        "name": "The Way of Tea — 茶道",
        "description": "Explore China's rich tea culture",
        "level_required": 4,
        "challenges": [
            {
                "id": "tea_character",
                "title": "The Word for Tea",
                "type": "quiz",
                "question": "茶 (chá) means 'tea.' The word for tea in almost every language comes from Chinese. Which two pronunciations spread worldwide?",
                "options": [
                    "'Cha' (Mandarin/Cantonese route) and 'Te' (Hokkien/Min route)",
                    "'Tea' (English) and 'Chai' (Russian)",
                    "'Cha' (land route) and 'Shu' (sea route)",
                    "'Te' (northern China) and 'Cha' (southern China)",
                ],
                "answer": "a",
                "hints": [
                    "Languages that got tea via the Silk Road say 'cha/chai.' Languages that got it by sea say 'te/tea.'",
                    "The trade route determined the pronunciation!",
                ],
                "xp": 30,
                "difficulty": "hard",
                "lesson": "茶 (chá) = tea. Almost every language's word for tea comes from Chinese! Land route (Silk Road) → 'cha/chai' (Russian чай, Hindi चाय, Turkish çay). Sea route (Fujian ports) → 'te/tea' (English tea, French thé, Spanish té). The trade route determined the word!",
                "is_boss": False,
                "flavor": "龙龙 traces the tea trade routes on a world map. 'China gave tea to the world!'",
            },
            {
                "id": "tea_types",
                "title": "So Many Teas!",
                "type": "quiz",
                "question": "Which of these is NOT one of China's six major tea categories?",
                "options": ["绿茶 (lǜchá) — Green tea", "红茶 (hóngchá) — Red/Black tea", "蓝茶 (lánchá) — Blue tea", "白茶 (báichá) — White tea"],
                "answer": "c",
                "hints": [
                    "The six categories are based on processing method: green, white, yellow, oolong, red, dark.",
                    "There is no 'blue tea' in Chinese classification.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "China's 6 tea types: 绿茶 (green), 白茶 (white), 黄茶 (yellow), 乌龙茶 (oolong), 红茶 (red — what English calls 'black tea'!), 黑茶 (dark/fermented, including Pu'er). Fun fact: Chinese 红茶 (red tea) = English 'black tea.' The names don't match!",
                "is_boss": False,
                "flavor": "龙龙 arranges six different teas in a rainbow. 'Each one, a different world of flavor!'",
            },
            {
                "id": "tea_ceremony",
                "title": "The Art of Serving",
                "type": "quiz",
                "question": "In a Chinese tea ceremony, why do you tap the table with two fingers when someone pours you tea?",
                "options": [
                    "To show the tea is too hot",
                    "To say 'thank you' silently (叩手礼, kòushǒulǐ)",
                    "To ask for more tea",
                    "To signal you don't want tea",
                ],
                "answer": "b",
                "hints": [
                    "This gesture represents a person bowing — the bent fingers are the bowed head.",
                    "It originated from a Qing Dynasty emperor's incognito visit to a teahouse.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "叩手礼 (kòushǒulǐ) = finger-tapping thanks. You tap two bent fingers on the table when someone pours your tea. Legend says it began when Emperor Qianlong disguised himself and poured tea for his servant, who couldn't bow without revealing the emperor's identity — so he 'bowed' with his fingers!",
                "is_boss": False,
                "flavor": "龙龙 taps two claws on the table. 'A silent thank you — very elegant!'",
            },
            {
                "id": "tea_gongfu",
                "title": "Gongfu Tea",
                "type": "quiz",
                "question": "功夫茶 (Gōngfū chá) means 'Gongfu tea.' What does 功夫 mean in this context?",
                "options": [
                    "Fighting/martial arts",
                    "Skill / effort / mastery through practice",
                    "Quick and easy",
                    "Ancient tradition",
                ],
                "answer": "b",
                "hints": [
                    "功夫 doesn't always mean martial arts — its root meaning is 'skill gained through effort.'",
                    "Gongfu tea is brewed with great skill and attention to detail.",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "功夫茶 (Gōngfū chá) = 'tea made with skill.' 功夫 means 'skill/mastery through practice' — not just martial arts! Gongfu tea uses a small 紫砂壶 (zǐshā hú, Yixing clay teapot), multiple short infusions, and careful technique. It's the opposite of fast tea-bag brewing!",
                "is_boss": False,
                "flavor": "龙龙 pours tea from a tiny Yixing teapot with exquisite precision.",
            },
            {
                "id": "tea_proverb",
                "title": "Tea Wisdom",
                "type": "quiz",
                "question": "开门七件事: 柴米油盐酱醋茶。Tea is one of the 'seven necessities of daily life.' What are the others?",
                "options": [
                    "Firewood, rice, oil, salt, sauce, vinegar",
                    "Water, bread, meat, vegetables, fruit, milk",
                    "Gold, silk, jade, wine, books, music",
                    "Wood, fire, earth, metal, water, air",
                ],
                "answer": "a",
                "hints": [
                    "柴(firewood)米(rice)油(oil)盐(salt)酱(sauce)醋(vinegar)茶(tea).",
                    "These are the seven things every household needs to survive.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "开门七件事: 柴米油盐酱醋茶 — 'Seven necessities upon opening the door: firewood, rice, oil, salt, sauce, vinegar, tea.' Tea is so essential it's listed alongside food staples! This saying dates to the Song Dynasty (960-1279).",
                "is_boss": True,
                "flavor": "龙龙 sips tea contentedly. 'Tea is not a luxury — it is a necessity!'",
            },
        ],
    },
    "martial_arts": {
        "id": "martial_arts",
        "name": "The Way of the Warrior — 武术",
        "description": "Explore Chinese martial arts — kung fu, tai chi, and philosophy",
        "level_required": 5,
        "challenges": [
            {
                "id": "ma_kungfu",
                "title": "The Art of Fighting",
                "type": "quiz",
                "question": "功夫 (gōngfu) is known worldwide as 'kung fu.' But what does it literally mean?",
                "options": [
                    "Fighting technique",
                    "Skill achieved through hard work and time",
                    "Ancient warrior",
                    "Dragon power",
                ],
                "answer": "b",
                "hints": [
                    "功 means 'achievement/work' and 夫 means 'man/effort.'",
                    "You can have 功夫 in anything — cooking, calligraphy, or martial arts.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "功夫 (gōngfu) literally means 'skill through effort/time.' A chef can have 功夫, a painter can have 功夫. The martial arts meaning became dominant through movies. The proper martial arts term is 武术 (wǔshù): 武 = martial, 术 = art/technique.",
                "is_boss": False,
                "flavor": "龙龙 strikes a kung fu pose. 'Real 功夫 takes years of practice!'",
            },
            {
                "id": "ma_taichi",
                "title": "Slow and Powerful",
                "type": "quiz",
                "question": "太极 (tàijí) is a martial art practiced by millions. What makes it unique?",
                "options": [
                    "It uses weapons only",
                    "Slow, flowing movements that cultivate inner energy (气, qì)",
                    "It's only for competition",
                    "It's the most aggressive martial art",
                ],
                "answer": "b",
                "hints": [
                    "太极 means 'supreme ultimate' — the concept from Chinese philosophy.",
                    "Look in any Chinese park at dawn — you'll see people practicing 太极.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "太极 (tàijí) = Tai Chi. It emphasizes slow, flowing movements, deep breathing, and 气 (qì, life energy). Millions practice it daily in parks across China. It's based on the Taoist concept of 阴阳 (yīnyáng) — balance between opposing forces.",
                "is_boss": False,
                "flavor": "龙龙 performs tai chi in a misty morning park, moving like water.",
            },
            {
                "id": "ma_shaolin",
                "title": "The Temple of Kung Fu",
                "type": "quiz",
                "question": "少林寺 (Shàolín Sì) is the legendary birthplace of Chinese martial arts. Where is it?",
                "options": [
                    "Beijing",
                    "Henan Province (河南省, Song Mountain)",
                    "Shanghai",
                    "Sichuan Province",
                ],
                "answer": "b",
                "hints": [
                    "少林 = 'young forest,' 寺 = temple. It sits on Song Mountain (嵩山).",
                    "Founded in 495 AD, it became the center of martial arts after Bodhidharma's visit.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "少林寺 (Shàolín Sì) = Shaolin Temple, in Henan Province on Song Mountain. Founded 495 AD. Legend says the Indian monk Bodhidharma (达摩, Dámó) brought meditation and exercises that evolved into kung fu. Today it's a UNESCO World Heritage Site and trains thousands of students.",
                "is_boss": False,
                "flavor": "龙龙 stands before the ancient temple gates. 'This is where it all began!'",
            },
            {
                "id": "ma_philosophy",
                "title": "The Warrior's Mind",
                "type": "quiz",
                "question": "以柔克刚 (yǐ róu kè gāng) is a core martial arts philosophy. What does it mean?",
                "options": [
                    "The strong always win",
                    "Use softness to overcome hardness",
                    "Attack first, think later",
                    "Practice makes perfect",
                ],
                "answer": "b",
                "hints": [
                    "柔 = soft/flexible, 刚 = hard/rigid. This is the principle behind tai chi and judo.",
                    "Think of water wearing down stone — softness conquers hardness over time.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "以柔克刚 (yǐ róu kè gāng) = 'use softness to overcome hardness.' This Taoist principle underpins tai chi, aikido, and judo. Water is soft but carves canyons. A bamboo bends but doesn't break. Chinese martial arts philosophy values intelligence over brute force.",
                "is_boss": False,
                "flavor": "龙龙 redirects a boulder with one gentle claw push. 'Softness wins!'",
            },
            {
                "id": "ma_wuxia",
                "title": "Heroes of Legend",
                "type": "quiz",
                "question": "武侠 (wǔxiá) is a beloved Chinese genre. What does it mean?",
                "options": [
                    "War history",
                    "Martial heroes / heroic martial arts (fiction)",
                    "Military strategy",
                    "Ancient weapons",
                ],
                "answer": "b",
                "hints": [
                    "武 = martial/warrior, 侠 = chivalrous hero/knight-errant.",
                    "Think of it as Chinese fantasy adventure — like Western sword-and-sorcery but with kung fu.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "武侠 (wǔxiá) = martial heroes genre. 武 = martial, 侠 = chivalrous hero. This genre features wandering warriors, hidden masters, and epic battles. Authors like 金庸 (Jīn Yōng) are national heroes. His novels (射雕英雄传, 笑傲江湖) are as beloved as Harry Potter in the West!",
                "is_boss": True,
                "flavor": "龙龙 draws a sword from nowhere. 'Every dragon loves a good 武侠 story!'",
            },
        ],
    },
    "modern_china": {
        "id": "modern_china",
        "name": "Digital China — 数字中国",
        "description": "Discover how technology shapes modern Chinese life",
        "level_required": 6,
        "challenges": [
            {
                "id": "mod_wechat",
                "title": "The Everything App",
                "type": "quiz",
                "question": "微信 (Wēixìn) is China's most essential app. What is it known as in English?",
                "options": ["TikTok", "WeChat", "Alipay", "Weibo"],
                "answer": "b",
                "hints": [
                    "微 means 'micro/tiny' and 信 means 'message/letter.'",
                    "It combines messaging, social media, payments, and mini-programs all in one.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "微信 (Wēixìn) = WeChat. It's not just messaging — it's payments, social media, food ordering, ride-hailing, government services, and more. Over 1.3 billion monthly users. In China, 没有微信 (no WeChat) is like not existing digitally!",
                "is_boss": False,
                "flavor": "龙龙 sends a WeChat message. 'In China, EVERYTHING runs on 微信!'",
            },
            {
                "id": "mod_alipay",
                "title": "Cashless Society",
                "type": "quiz",
                "question": "支付宝 (Zhīfùbǎo) means...?",
                "options": ["Online banking", "Alipay (mobile payment)", "Credit card", "ATM machine"],
                "answer": "b",
                "hints": [
                    "支付 means 'to pay' and 宝 means 'treasure.'",
                    "Together with WeChat Pay, it has made China nearly cashless.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "支付宝 (Zhīfùbǎo) = Alipay. 支付 = payment, 宝 = treasure. China is the world's most cashless society — even street food vendors use QR codes! 扫码支付 (sǎomǎ zhīfù) = scan-to-pay. 现金 (xiànjīn, cash) is barely used in major cities.",
                "is_boss": False,
                "flavor": "龙龙 scans a QR code with its eye. 'Who needs gold when you have 支付宝?'",
            },
            {
                "id": "mod_highspeed_rail",
                "title": "The Speed Revolution",
                "type": "quiz",
                "question": "高铁 (gāotiě) literally means 'high iron.' What is it?",
                "options": ["Skyscraper", "High-speed rail", "Elevated highway", "Iron mine"],
                "answer": "b",
                "hints": [
                    "高 = high, 铁 = iron (short for 铁路, railway).",
                    "China's network is the world's largest at over 45,000 km.",
                ],
                "xp": 25,
                "difficulty": "easy",
                "lesson": "高铁 (gāotiě) = high-speed rail. China's HSR network is the world's largest: 45,000+ km, max speed 350 km/h. Beijing to Shanghai (1,300 km) takes just 4.5 hours! 高铁站 (gāotiězhàn) = HSR station. A symbol of modern China.",
                "is_boss": False,
                "flavor": "龙龙 races a bullet train. 'Okay, the 高铁 might be faster than me!'",
            },
            {
                "id": "mod_ecommerce",
                "title": "Shopping Festival",
                "type": "quiz",
                "question": "双十一 (Shuāng Shíyī) — 'Double Eleven' (November 11) — is the world's biggest...?",
                "options": ["Sports event", "Music festival", "Online shopping day", "National holiday"],
                "answer": "c",
                "hints": [
                    "11/11 was originally 'Singles' Day' (光棍节) because 1111 looks like four single people.",
                    "Alibaba turned it into a shopping event that dwarfs Black Friday and Cyber Monday combined.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "双十一 (Shuāng Shíyī) = Double 11 / Singles' Day (Nov 11). Started as a joke holiday for single people, Alibaba turned it into the world's largest shopping event. In 2023, sales exceeded $150 billion — dwarfing Black Friday + Cyber Monday combined!",
                "is_boss": False,
                "flavor": "龙龙's shopping cart overflows. 'I bought too much during 双十一 again!'",
            },
            {
                "id": "mod_tiktok",
                "title": "Short Video Empire",
                "type": "quiz",
                "question": "抖音 (Dǒuyīn) is TikTok's Chinese name (and original version). What does 抖音 literally mean?",
                "options": ["Quick video", "Vibrating sound / vibrato", "Dancing picture", "Short music"],
                "answer": "b",
                "hints": [
                    "抖 means 'to shake/vibrate' and 音 means 'sound.'",
                    "The name refers to the musical vibrato effect popular in early videos.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "抖音 (Dǒuyīn) = TikTok (Chinese version). 抖 = vibrate/shake, 音 = sound. Created by ByteDance (字节跳动, Zìjié Tiàodòng) in Beijing. The international version was named TikTok. China's tech vocabulary is worth knowing — it's shaping the global digital landscape!",
                "is_boss": False,
                "flavor": "龙龙 tries to make a 抖音 video. 'How do humans hold phones with no claws?!'",
            },
            {
                "id": "mod_social_credit",
                "title": "Living Digital",
                "type": "quiz",
                "question": "二维码 (èrwéimǎ) means 'QR code' (literally '2D code'). In modern China, QR codes are used for...?",
                "options": [
                    "Payments only",
                    "Almost everything: payments, restaurant menus, transit, IDs, COVID tracking",
                    "Entertainment only",
                    "Government documents only",
                ],
                "answer": "b",
                "hints": [
                    "In China, scanning QR codes is as natural as breathing.",
                    "二维 = two-dimensional, 码 = code.",
                ],
                "xp": 35,
                "difficulty": "medium",
                "lesson": "二维码 (èrwéimǎ) = QR code. In modern China, QR codes are everywhere: payments (扫码支付), restaurant ordering, subway entry, bike-sharing, adding contacts, COVID health codes. 扫一扫 (sǎo yī sǎo) = 'scan it' — possibly the most-used phrase in digital China!",
                "is_boss": True,
                "flavor": "龙龙 projects a QR code from its eye. 'Scan me! Welcome to digital China!'",
            },
        ],
    },
    "idioms_chengyu": {
        "id": "idioms_chengyu",
        "name": "Four-Character Wisdom — 成语",
        "description": "Learn famous Chinese four-character idioms with their stories",
        "level_required": 7,
        "challenges": [
            {
                "id": "chengyu_snake",
                "title": "Too Much of a Good Thing",
                "type": "quiz",
                "question": "画蛇添足 (huà shé tiān zú) literally means 'draw a snake, add feet.' What does this idiom mean?",
                "options": [
                    "Practice makes perfect",
                    "To ruin something by adding unnecessary extras",
                    "To be creative and innovative",
                    "To finish a task perfectly",
                ],
                "answer": "b",
                "hints": [
                    "If you draw a perfectly good snake and then add feet... you've ruined it!",
                    "Snakes don't have feet — adding them makes it no longer a snake.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "画蛇添足 (huà shé tiān zú) = 'draw a snake, add feet' — to ruin something by overdoing it. The story: men competed to draw a snake fastest. The winner finished first but added feet while waiting — and lost because his drawing was no longer a snake! Lesson: know when to stop.",
                "is_boss": False,
                "flavor": "龙龙 draws a snake, then mischievously adds tiny feet. 'See? Ruined!'",
            },
            {
                "id": "chengyu_cow_music",
                "title": "Wrong Audience",
                "type": "quiz",
                "question": "对牛弹琴 (duì niú tán qín) means 'play the lute to a cow.' What does it really mean?",
                "options": [
                    "Music soothes animals",
                    "To speak to someone who can't understand — a wasted effort",
                    "Cows love music",
                    "To practice alone",
                ],
                "answer": "b",
                "hints": [
                    "A cow can't appreciate fine music — the effort is wasted on the wrong audience.",
                    "Used when someone talks about something too complex for their listener.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "对牛弹琴 (duì niú tán qín) = 'play the lute to a cow' — wasting your effort on someone who can't appreciate it. Like explaining quantum physics to a toddler. Be careful using this one — it implies the listener is as dumb as a cow!",
                "is_boss": False,
                "flavor": "龙龙 plays a beautiful melody while a cow chews grass, completely unimpressed.",
            },
            {
                "id": "chengyu_frog_well",
                "title": "The Narrow View",
                "type": "quiz",
                "question": "井底之蛙 (jǐng dǐ zhī wā) means 'frog at the bottom of a well.' What does it describe?",
                "options": [
                    "Someone who is trapped",
                    "Someone with a narrow, limited worldview",
                    "Someone who likes to swim",
                    "Someone who is patient",
                ],
                "answer": "b",
                "hints": [
                    "A frog at the bottom of a well thinks the sky is only as big as the well opening.",
                    "It's about having a limited perspective and not knowing what you don't know.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "井底之蛙 (jǐng dǐ zhī wā) = 'frog at the bottom of a well' — someone with a narrow worldview. The frog thinks the tiny circle of sky above is the entire world. This idiom encourages travel, learning, and broadening your horizons. Don't be a well frog!",
                "is_boss": False,
                "flavor": "龙龙 peers down a well. 'See the world! Don't be a 井底之蛙!'",
            },
            {
                "id": "chengyu_iron_needle",
                "title": "Never Give Up",
                "type": "quiz",
                "question": "只要功夫深,铁杵磨成针 (zhǐyào gōngfu shēn, tiěchǔ mó chéng zhēn) means...?",
                "options": [
                    "Iron is the strongest material",
                    "With enough effort, an iron rod can be ground into a needle — perseverance wins",
                    "Needles are more useful than rods",
                    "Kung fu masters use iron needles",
                ],
                "answer": "b",
                "hints": [
                    "The story: young Li Bai (famous poet) saw an old woman grinding an iron rod into a needle. Her patience inspired him to study harder.",
                    "功夫 here means 'effort/skill' — not martial arts!",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "铁杵磨成针 = 'grind an iron rod into a needle.' With enough persistence and effort (功夫), anything is possible. This story features young Li Bai (李白), China's most famous poet, who was inspired by the old woman's patience to never give up on his studies.",
                "is_boss": False,
                "flavor": "龙龙 grinds a tiny iron rod with determination. 'Patience! Almost a needle!'",
            },
            {
                "id": "chengyu_four_char",
                "title": "The Power of Four",
                "type": "quiz",
                "question": "Why are most 成语 (chéngyǔ) exactly four characters long?",
                "options": [
                    "Four is a lucky number in Chinese",
                    "Four characters create a rhythmic, balanced structure perfect for memory",
                    "Chinese grammar requires four characters",
                    "There are only four tones in Mandarin",
                ],
                "answer": "b",
                "hints": [
                    "Four characters create two pairs — a natural rhythm: XX-XX.",
                    "This 2+2 structure is pleasing to the ear and easy to memorize.",
                ],
                "xp": 30,
                "difficulty": "medium",
                "lesson": "成语 (chéngyǔ) = four-character idioms. The 2+2 rhythm (XX-XX) creates natural balance and is easy to remember. There are over 50,000 chengyu! They come from ancient stories, historical events, and classical texts. Using chengyu makes your Chinese sound educated and elegant.",
                "is_boss": False,
                "flavor": "龙龙 writes 四字成语 in the air. 'Four characters, infinite wisdom!'",
            },
            {
                "id": "chengyu_context",
                "title": "Use It Right",
                "type": "quiz",
                "question": "Your friend spends 30 minutes making a beautiful cake, then accidentally drops it while adding one more decoration. Which 成语 fits?",
                "options": [
                    "对牛弹琴 (playing lute to a cow)",
                    "画蛇添足 (drawing feet on a snake)",
                    "井底之蛙 (frog in a well)",
                    "守株待兔 (waiting by a stump for a rabbit)",
                ],
                "answer": "b",
                "hints": [
                    "The cake was perfect — the extra decoration was unnecessary and ruined it.",
                    "Which idiom is about adding something unnecessary that ruins the result?",
                ],
                "xp": 35,
                "difficulty": "hard",
                "lesson": "画蛇添足 fits perfectly — the cake was finished but the unnecessary extra 'decoration' ruined it. Using chengyu correctly in context shows real Chinese mastery. Native speakers are always impressed when foreigners use chengyu naturally in conversation!",
                "is_boss": True,
                "flavor": "龙龙 applauds. 'You used a 成语 in context! That's real Chinese fluency!'",
            },
        ],
    },
}
