"""
zones.py -- Home & Housing zones and challenges.

Mix of quiz and text challenges covering rooms of the house, furniture & objects,
household chores, describing your home, and renting & moving.
Guided by Señora Carmen, a warm real-estate agent showing homes at sunset.
"""

ZONE_ORDER = [
    "rooms_of_the_house",
    "furniture_objects",
    "household_chores",
    "describing_your_home",
    "renting_moving",
]

ZONES = {
    # -- Zone 1: Rooms of the House --
    "rooms_of_the_house": {
        "id": "rooms_of_the_house",
        "name": "Rooms of the House",
        "description": "Learn the Spanish names for rooms in a home",
        "level_required": 1,
        "challenges": [
            {
                "id": "rm_sala",
                "title": "The Living Room",
                "type": "quiz",
                "question": "How do you say 'living room' in Spanish?",
                "options": ["La cocina", "La sala", "El baño", "El dormitorio"],
                "answer": "b",
                "hints": ["It starts with 's'.", "Think of the word 'salón' -- a related term."],
                "xp": 25,
                "lesson": "'La sala' = the living room. Also called 'el salón' or 'la sala de estar' (literally 'the room for being'). This is where families gather: 'Estamos en la sala' = We are in the living room. 'La sala es la habitación más grande' = The living room is the biggest room.",
            },
            {
                "id": "rm_cocina",
                "title": "The Kitchen",
                "type": "text",
                "question": "Type the Spanish word for 'kitchen' (with the article 'la'):",
                "options": [],
                "answer": "la cocina",
                "hints": ["It starts with 'c'.", "The verb 'cocinar' (to cook) comes from this word."],
                "xp": 25,
                "lesson": "'La cocina' = the kitchen. 'Cocinar' = to cook. 'Estoy en la cocina' = I'm in the kitchen. 'La cocina española es famosa' = Spanish cuisine is famous. The kitchen is the heart of many Spanish homes -- 'El corazón de la casa es la cocina.'",
            },
            {
                "id": "rm_dormitorio",
                "title": "The Bedroom",
                "type": "quiz",
                "question": "'Mi dormitorio es pequeño pero cómodo' means:",
                "options": ["My kitchen is small but clean", "My bedroom is small but comfortable", "My bathroom is small but modern", "My garden is small but pretty"],
                "answer": "b",
                "hints": ["'Dormitorio' comes from 'dormir' (to sleep).", "'Cómodo' = comfortable."],
                "xp": 25,
                "lesson": "'El dormitorio' = the bedroom. Also called 'la habitación' or 'el cuarto.' 'Dormir' = to sleep. 'Mi dormitorio tiene una cama grande' = My bedroom has a big bed. 'La habitación de invitados' = the guest room. 'Voy a mi habitación' = I'm going to my room.",
            },
            {
                "id": "rm_bano",
                "title": "The Bathroom",
                "type": "text",
                "question": "Type how you ask 'Where is the bathroom?' in Spanish:",
                "options": [],
                "answer": "¿Dónde está el baño?",
                "hints": ["'Dónde está' = where is.", "'El baño' = the bathroom."],
                "xp": 25,
                "lesson": "'¿Dónde está el baño?' = Where is the bathroom? One of the most essential phrases! 'El baño' = the bathroom. 'El aseo' is also used in Spain for a half-bath or restroom. 'Necesito ir al baño' = I need to go to the bathroom. In restaurants you might hear 'los servicios' or 'los aseos.'",
            },
            {
                "id": "rm_comedor",
                "title": "The Dining Room",
                "type": "quiz",
                "question": "'Cenamos en el comedor' means:",
                "options": ["We cook in the kitchen", "We sleep in the bedroom", "We eat dinner in the dining room", "We relax in the living room"],
                "answer": "c",
                "hints": ["'Cenar' = to have dinner.", "'Comedor' comes from 'comer' (to eat)."],
                "xp": 25,
                "lesson": "'El comedor' = the dining room. From 'comer' (to eat). 'Cenamos en el comedor' = We eat dinner in the dining room. Meals: 'desayunar' (breakfast), 'almorzar/comer' (lunch), 'cenar' (dinner). In Spain, lunch is the main meal, often eaten around 2-3 PM. 'La mesa del comedor' = the dining table.",
            },
            {
                "id": "rm_jardin",
                "title": "The Garden",
                "type": "quiz",
                "question": "Which is the correct Spanish word for 'garden'?",
                "options": ["El garaje", "El jardín", "El pasillo", "El sótano"],
                "answer": "b",
                "hints": ["Note the accent mark on the 'i'.", "It sounds similar to 'jardin' in French."],
                "xp": 25,
                "lesson": "'El jardín' = the garden. 'Los jardines' = the gardens (plural). 'Tenemos un jardín pequeño' = We have a small garden. Related: 'el patio' (patio/courtyard), 'la terraza' (terrace/balcony), 'las plantas' (plants), 'las flores' (flowers). Spanish patios with flowers are world-famous, especially in Córdoba!",
            },
            {
                "id": "rm_garage",
                "title": "The Garage",
                "type": "text",
                "question": "Type the Spanish word for 'garage' (with the article 'el'):",
                "options": [],
                "answer": "el garaje",
                "hints": ["It's very similar to the English word.", "Note the spelling ends in '-aje' not '-age'."],
                "xp": 25,
                "lesson": "'El garaje' = the garage. Note the Spanish spelling: '-aje' instead of '-age.' 'El coche está en el garaje' = The car is in the garage. Related spaces: 'el sótano' (basement), 'el desván/ático' (attic), 'el trastero' (storage room). 'Plaza de garaje' = parking spot (in apartment buildings).",
            },
            {
                "id": "rm_rooms_boss",
                "title": "House Tour",
                "type": "quiz",
                "question": "A friend visits your home. Which sentence best describes a house tour?",
                "options": ["Aquí está la casa.", "Esta es la sala, la cocina está a la derecha, el dormitorio está arriba y el baño está al fondo del pasillo.", "Tengo una casa.", "La casa es bonita."],
                "answer": "b",
                "hints": ["A good tour names specific rooms and their locations.", "Use direction words like 'a la derecha' and 'arriba.'"],
                "xp": 35,
                "lesson": "A good house tour names rooms and gives locations: 'esta es la sala' (this is the living room), 'a la derecha' (to the right), 'arriba' (upstairs), 'al fondo del pasillo' (at the end of the hallway). Direction words: 'a la izquierda' (left), 'abajo' (downstairs), 'enfrente' (in front). You can now give a full house tour in Spanish!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 2: Furniture & Objects --
    "furniture_objects": {
        "id": "furniture_objects",
        "name": "Furniture & Objects",
        "description": "Learn the Spanish names for common household furniture and objects",
        "level_required": 1,
        "challenges": [
            {
                "id": "fo_mesa",
                "title": "The Table",
                "type": "quiz",
                "question": "'Pon los platos en la mesa' means:",
                "options": ["Put the plates on the table", "Put the plates in the sink", "Clear the table", "Set the chairs around the table"],
                "answer": "a",
                "hints": ["'La mesa' = the table.", "'Poner' = to put."],
                "xp": 25,
                "lesson": "'La mesa' = the table. 'Poner la mesa' = to set the table (a very common phrase!). 'La mesa de comedor' = dining table. 'La mesa de centro' = coffee table. 'La mesita de noche' = nightstand (literally 'little night table'). 'Sentarse a la mesa' = to sit at the table.",
            },
            {
                "id": "fo_silla",
                "title": "The Chair",
                "type": "text",
                "question": "Type the Spanish word for 'chair' (with the article 'la'):",
                "options": [],
                "answer": "la silla",
                "hints": ["It starts with 's'.", "The double 'l' makes a 'y' sound in most dialects."],
                "xp": 25,
                "lesson": "'La silla' = the chair. 'Las sillas' = chairs. Related seating: 'el sillón' (armchair), 'el taburete' (stool), 'el banco' (bench). 'Siéntate en la silla' = Sit in the chair. 'Necesitamos más sillas' = We need more chairs. 'La silla de ruedas' = wheelchair.",
            },
            {
                "id": "fo_cama",
                "title": "The Bed",
                "type": "quiz",
                "question": "How do you say 'make the bed' in Spanish?",
                "options": ["Lavar la cama", "Hacer la cama", "Comprar la cama", "Romper la cama"],
                "answer": "b",
                "hints": ["'Hacer' has many meanings beyond 'to do.'", "'La cama' = the bed."],
                "xp": 25,
                "lesson": "'Hacer la cama' = to make the bed. 'La cama' = the bed. Sizes: 'cama individual' (single bed), 'cama doble' (double bed), 'cama de matrimonio' (queen/king bed). 'Irse a la cama' = to go to bed. 'Quedarse en la cama' = to stay in bed. 'La ropa de cama' = bedding/bed linen.",
            },
            {
                "id": "fo_sofa",
                "title": "The Sofa",
                "type": "quiz",
                "question": "'Me gusta sentarme en el sofá después del trabajo' means:",
                "options": ["I like to eat on the sofa after work", "I like to sit on the sofa after work", "I like to sleep on the sofa after work", "I like to read on the sofa after work"],
                "answer": "b",
                "hints": ["'Sentarse' = to sit down.", "'Después del trabajo' = after work."],
                "xp": 25,
                "lesson": "'El sofá' = the sofa/couch. Note the accent on the final 'a.' 'Sentarse en el sofá' = to sit on the sofa. 'Un sofá cama' = a sofa bed (very practical!). 'Los cojines del sofá' = the sofa cushions. 'Tumbarse en el sofá' = to lie down on the sofa. A very important piece of furniture for 'la siesta!'",
            },
            {
                "id": "fo_lampara",
                "title": "The Lamp",
                "type": "text",
                "question": "Type the Spanish word for 'lamp' (with the article 'la'):",
                "options": [],
                "answer": "la lámpara",
                "hints": ["Don't forget the accent mark!", "It's similar to the English word."],
                "xp": 25,
                "lesson": "'La lámpara' = the lamp. Note the accent: 'lámpara.' 'Enciende la lámpara' = Turn on the lamp. 'Apaga la lámpara' = Turn off the lamp. Related: 'la luz' (the light), 'el interruptor' (the switch), 'la bombilla' (the light bulb). 'No hay luz' = There's no light / The power is out.",
            },
            {
                "id": "fo_armario",
                "title": "The Wardrobe",
                "type": "quiz",
                "question": "'La ropa está en el armario' means:",
                "options": ["The clothes are on the floor", "The clothes are in the wardrobe", "The clothes are in the washing machine", "The clothes are on the bed"],
                "answer": "b",
                "hints": ["'El armario' is where you store things.", "'La ropa' = clothes."],
                "xp": 25,
                "lesson": "'El armario' = the wardrobe/closet. 'La ropa está en el armario' = The clothes are in the wardrobe. 'El armario empotrado' = built-in closet. Related storage: 'la estantería' (bookshelf), 'la cómoda' (dresser/chest of drawers), 'el cajón' (drawer). 'Ordenar el armario' = to organize the closet.",
            },
            {
                "id": "fo_espejo",
                "title": "The Mirror",
                "type": "text",
                "question": "Type the Spanish word for 'mirror' (with the article 'el'):",
                "options": [],
                "answer": "el espejo",
                "hints": ["It starts with 'e'.", "Think of 'espejismo' (mirage)."],
                "xp": 25,
                "lesson": "'El espejo' = the mirror. 'Mirarse en el espejo' = to look at oneself in the mirror. 'El espejo del baño' = the bathroom mirror. The famous fairy tale line: 'Espejito, espejito, ¿quién es la más bella?' = Mirror, mirror, who is the fairest? 'Un espejo de cuerpo entero' = a full-length mirror.",
            },
            {
                "id": "fo_furniture_boss",
                "title": "Furnish the Room",
                "type": "quiz",
                "question": "You're describing your living room to a friend. Which is the most complete description?",
                "options": ["Tengo muebles.", "En la sala hay un sofá grande, una mesa de centro, dos sillas, una lámpara y un espejo en la pared.", "La sala está vacía.", "Hay cosas en la sala."],
                "answer": "b",
                "hints": ["Name specific furniture items with details.", "Use 'hay' (there is/are) to list what's in the room."],
                "xp": 35,
                "lesson": "A complete room description uses 'hay' (there is/are) + specific items with details: 'un sofá grande' (a big sofa), 'una mesa de centro' (a coffee table), 'dos sillas' (two chairs), 'en la pared' (on the wall). 'Los muebles' = furniture. You can now describe any furnished room in Spanish!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 3: Household Chores --
    "household_chores": {
        "id": "household_chores",
        "name": "Household Chores",
        "description": "Learn to talk about cleaning, cooking, and daily tasks at home",
        "level_required": 2,
        "challenges": [
            {
                "id": "ch_limpiar",
                "title": "To Clean",
                "type": "quiz",
                "question": "'Tengo que limpiar la casa' means:",
                "options": ["I have to leave the house", "I have to clean the house", "I have to paint the house", "I have to sell the house"],
                "answer": "b",
                "hints": ["'Limpiar' = to clean.", "'Tengo que' = I have to."],
                "xp": 25,
                "lesson": "'Limpiar' = to clean. 'Tengo que limpiar la casa' = I have to clean the house. 'Limpio/a' = clean (adjective). 'La limpieza' = cleaning/cleanliness. 'Productos de limpieza' = cleaning products. 'Limpiar el polvo' = to dust. 'La casa está limpia' = The house is clean.",
            },
            {
                "id": "ch_cocinar",
                "title": "To Cook",
                "type": "text",
                "question": "Type how you say 'I like to cook' in Spanish:",
                "options": [],
                "answer": "Me gusta cocinar",
                "hints": ["'Me gusta' = I like.", "'Cocinar' = to cook."],
                "xp": 25,
                "lesson": "'Me gusta cocinar' = I like to cook. 'Cocinar' = to cook. 'El/la cocinero/a' = the cook. 'La receta de cocina' = the cooking recipe. 'Cocinar a fuego lento' = to cook on low heat. '¿Qué vamos a cocinar hoy?' = What are we going to cook today? Spanish cuisine ('la cocina española') is world-renowned!",
            },
            {
                "id": "ch_lavar",
                "title": "To Wash",
                "type": "quiz",
                "question": "Which phrase means 'to wash the dishes'?",
                "options": ["Lavar la ropa", "Lavar los platos", "Lavar el coche", "Lavar el perro"],
                "answer": "b",
                "hints": ["'Los platos' = the dishes.", "'Lavar' = to wash."],
                "xp": 25,
                "lesson": "'Lavar los platos' = to wash the dishes. 'Lavar' is versatile: 'lavar la ropa' (wash clothes), 'lavar el coche' (wash the car), 'lavarse las manos' (wash one's hands). 'El lavavajillas' = dishwasher. 'La lavadora' = washing machine. 'El lavabo' = the sink (bathroom). 'Fregar los platos' is also common in Spain.",
            },
            {
                "id": "ch_barrer",
                "title": "To Sweep",
                "type": "text",
                "question": "Type the Spanish word for 'to sweep':",
                "options": [],
                "answer": "barrer",
                "hints": ["It starts with 'b'.", "Think of 'broom' -- the tool used."],
                "xp": 25,
                "lesson": "'Barrer' = to sweep. 'La escoba' = the broom. 'Barrer el suelo' = to sweep the floor. Related cleaning verbs: 'fregar' (to mop/scrub), 'aspirar' (to vacuum), 'recoger' (to pick up/tidy). 'La fregona' = the mop. 'El aspirador / la aspiradora' = the vacuum cleaner. 'El suelo está sucio, hay que barrer' = The floor is dirty, we need to sweep.",
            },
            {
                "id": "ch_planchar",
                "title": "To Iron",
                "type": "quiz",
                "question": "'Necesito planchar las camisas' means:",
                "options": ["I need to fold the shirts", "I need to iron the shirts", "I need to buy the shirts", "I need to hang the shirts"],
                "answer": "b",
                "hints": ["'Planchar' involves heat and wrinkles.", "'Las camisas' = the shirts."],
                "xp": 25,
                "lesson": "'Planchar' = to iron. 'La plancha' = the iron (appliance). 'Planchar la ropa' = to iron clothes. 'Tender la ropa' = to hang out the laundry. In Spain, most people hang clothes outside to dry ('tender la ropa al sol'). 'Doblar la ropa' = to fold clothes. A full laundry cycle: 'lavar, tender, planchar, doblar.'",
            },
            {
                "id": "ch_ordenar",
                "title": "To Tidy Up",
                "type": "text",
                "question": "Type how you say 'I need to tidy my room' in Spanish:",
                "options": [],
                "answer": "Necesito ordenar mi habitación",
                "hints": ["'Ordenar' = to tidy/organize.", "'Mi habitación' = my room."],
                "xp": 30,
                "lesson": "'Ordenar' = to tidy up / organize. 'Necesito ordenar mi habitación' = I need to tidy my room. 'El orden' = order/tidiness. 'Desordenado' = messy. 'Recoger la casa' = to tidy up the house. 'Cada cosa en su lugar' = Everything in its place -- a common saying. 'La casa está muy desordenada' = The house is very messy.",
            },
            {
                "id": "ch_sacar_basura",
                "title": "Taking Out the Trash",
                "type": "quiz",
                "question": "'¿Puedes sacar la basura?' means:",
                "options": ["Can you buy groceries?", "Can you take out the trash?", "Can you wash the car?", "Can you walk the dog?"],
                "answer": "b",
                "hints": ["'Sacar' = to take out.", "'La basura' = the trash/garbage."],
                "xp": 25,
                "lesson": "'Sacar la basura' = to take out the trash. 'La basura' = trash/garbage. 'El contenedor' = the dumpster/bin. In Spain, recycling is common: 'el contenedor amarillo' (plastics), 'el azul' (paper), 'el verde' (glass), 'el gris/marrón' (organic). '¡No olvides sacar la basura!' = Don't forget to take out the trash!",
            },
            {
                "id": "ch_chores_boss",
                "title": "Chore Day",
                "type": "quiz",
                "question": "It's Saturday cleaning day. Which sentence describes the most complete plan?",
                "options": ["Voy a limpiar.", "Primero voy a barrer y fregar el suelo, después lavar los platos, y luego planchar la ropa y sacar la basura.", "La casa está sucia.", "No me gustan las tareas del hogar."],
                "answer": "b",
                "hints": ["List multiple chores in a logical order.", "Use sequence words: 'primero,' 'después,' 'luego.'"],
                "xp": 35,
                "lesson": "A complete chore plan uses sequence words: 'primero' (first), 'después' (then), 'luego' (later). 'Las tareas del hogar' = household chores. 'Repartir las tareas' = to share the chores. You can now describe a full cleaning routine in Spanish -- from sweeping to ironing!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 4: Describing Your Home --
    "describing_your_home": {
        "id": "describing_your_home",
        "name": "Describing Your Home",
        "description": "Use adjectives to describe your home and its features",
        "level_required": 2,
        "challenges": [
            {
                "id": "dh_grande",
                "title": "Big",
                "type": "quiz",
                "question": "'La casa es grande y luminosa' means:",
                "options": ["The house is small and dark", "The house is big and bright", "The house is old and cold", "The house is new and expensive"],
                "answer": "b",
                "hints": ["'Grande' = big.", "'Luminosa' = bright/full of light."],
                "xp": 25,
                "lesson": "'Grande' = big/large. 'La casa es grande' = The house is big. 'Luminoso/a' = bright, full of light. Related size words: 'enorme' (enormous), 'amplio/a' (spacious), 'espacioso/a' (roomy). 'Una casa grande con jardín' = A big house with a garden. In Spain, 'un piso grande' = a big apartment.",
            },
            {
                "id": "dh_pequeno",
                "title": "Small",
                "type": "text",
                "question": "Type how you say 'My apartment is small' in Spanish:",
                "options": [],
                "answer": "Mi piso es pequeño",
                "hints": ["'Pequeño' = small.", "'Mi piso' = my apartment."],
                "xp": 25,
                "lesson": "'Pequeño/a' = small. 'Mi piso es pequeño' = My apartment is small. In Spain, 'piso' = apartment (in Latin America: 'apartamento' or 'departamento'). 'Pequeño pero acogedor' = small but cozy. 'Un estudio' = a studio apartment. 'Un piso de dos habitaciones' = a two-bedroom apartment. Size matters in Spanish real estate!",
            },
            {
                "id": "dh_nuevo",
                "title": "New",
                "type": "quiz",
                "question": "How do you say 'We have a new house' in Spanish?",
                "options": ["Tenemos una casa vieja", "Tenemos una casa nueva", "Tenemos una casa bonita", "Tenemos una casa cara"],
                "answer": "b",
                "hints": ["'Nuevo/a' = new.", "Remember gender agreement: 'casa' is feminine."],
                "xp": 25,
                "lesson": "'Nuevo/a' = new. 'Tenemos una casa nueva' = We have a new house. Note: 'nueva' matches the feminine 'casa.' 'Obra nueva' = new construction. 'De segunda mano' = second-hand. 'Recién reformado' = recently renovated. 'Estrenar casa' = to move into a brand-new home (a uniquely Spanish expression!).",
            },
            {
                "id": "dh_viejo",
                "title": "Old",
                "type": "quiz",
                "question": "'El edificio es viejo pero tiene mucho carácter' means:",
                "options": ["The building is ugly but cheap", "The building is old but has a lot of character", "The building is new but plain", "The building is old and should be demolished"],
                "answer": "b",
                "hints": ["'Viejo' = old.", "'Carácter' = character/charm."],
                "xp": 25,
                "lesson": "'Viejo/a' = old. 'Antiguo/a' is used for 'old' in a charming or historic sense. 'Un edificio antiguo' = an old/historic building (positive). 'Un edificio viejo' can sound more negative. 'Con encanto' = charming. Spain is full of beautiful old buildings: 'El casco antiguo' = the old town. 'Un piso con historia' = an apartment with history.",
            },
            {
                "id": "dh_bonito",
                "title": "Pretty",
                "type": "text",
                "question": "Type how you say 'The neighborhood is very pretty' in Spanish:",
                "options": [],
                "answer": "El barrio es muy bonito",
                "hints": ["'Bonito' = pretty.", "'El barrio' = the neighborhood."],
                "xp": 25,
                "lesson": "'Bonito/a' = pretty/nice. 'El barrio es muy bonito' = The neighborhood is very pretty. 'El barrio' = the neighborhood. Related: 'hermoso/a' (beautiful), 'precioso/a' (gorgeous), 'feo/a' (ugly). 'Un barrio tranquilo' = a quiet neighborhood. 'Una zona céntrica' = a central area. 'Bien comunicado' = well-connected (good transport).",
            },
            {
                "id": "dh_comodo",
                "title": "Comfortable",
                "type": "quiz",
                "question": "'Esta casa es muy cómoda y acogedora' means:",
                "options": ["This house is very expensive and modern", "This house is very comfortable and cozy", "This house is very large and empty", "This house is very cold and dark"],
                "answer": "b",
                "hints": ["'Cómodo/a' = comfortable.", "'Acogedor/a' = cozy/welcoming."],
                "xp": 25,
                "lesson": "'Cómodo/a' = comfortable. 'Acogedor/a' = cozy, welcoming. These are key words for describing a home. 'Un hogar acogedor' = a welcoming home. 'Hogar' = home (more emotional than 'casa'). 'Hogar, dulce hogar' = Home, sweet home. 'Sentirse como en casa' = to feel at home.",
            },
            {
                "id": "dh_piso",
                "title": "What Floor?",
                "type": "text",
                "question": "Type how you say 'I live on the third floor' in Spanish:",
                "options": [],
                "answer": "Vivo en el tercer piso",
                "hints": ["'Vivo en' = I live on/in.", "'Tercer' = third (before a noun)."],
                "xp": 30,
                "lesson": "'Vivo en el tercer piso' = I live on the third floor. Floor numbers: 'primer piso' (1st), 'segundo piso' (2nd), 'tercer piso' (3rd), 'cuarto piso' (4th). Note: 'planta baja' = ground floor (in Spain, the ground floor is floor 0, so 'primer piso' = what Americans call the 2nd floor). 'El ascensor' = the elevator. 'Sin ascensor' = no elevator (common in old Spanish buildings!).",
            },
            {
                "id": "dh_describe_boss",
                "title": "Real Estate Listing",
                "type": "quiz",
                "question": "You're describing your home for a listing. Which is the most complete description?",
                "options": ["Es una casa.", "Piso grande y luminoso en un barrio bonito y tranquilo, con tres dormitorios, dos baños y una cocina nueva.", "Vivo aquí.", "Se vende piso."],
                "answer": "b",
                "hints": ["Include size, light, location, and room count.", "Use multiple adjectives to paint a picture."],
                "xp": 35,
                "lesson": "A good real estate description includes: size ('grande'), light ('luminoso'), location ('barrio bonito y tranquilo'), rooms ('tres dormitorios, dos baños'), and features ('cocina nueva'). 'Se vende' = for sale. 'Se alquila' = for rent. You can now describe any home in detail in Spanish!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 5: Renting & Moving --
    "renting_moving": {
        "id": "renting_moving",
        "name": "Renting & Moving",
        "description": "Navigate renting an apartment and moving in Spanish",
        "level_required": 3,
        "challenges": [
            {
                "id": "rn_alquilar",
                "title": "To Rent",
                "type": "quiz",
                "question": "'Quiero alquilar un piso en el centro' means:",
                "options": ["I want to buy an apartment downtown", "I want to rent an apartment downtown", "I want to visit an apartment downtown", "I want to sell an apartment downtown"],
                "answer": "b",
                "hints": ["'Alquilar' = to rent.", "'En el centro' = downtown."],
                "xp": 25,
                "lesson": "'Alquilar' = to rent. 'El alquiler' = the rent (noun). 'Quiero alquilar un piso' = I want to rent an apartment. '¿Cuánto es el alquiler?' = How much is the rent? 'Alquiler mensual' = monthly rent. In Spain, renting is very common, especially in big cities like Madrid and Barcelona. 'Piso en alquiler' = apartment for rent.",
            },
            {
                "id": "rn_mudarse",
                "title": "To Move",
                "type": "text",
                "question": "Type how you say 'We are going to move next month' in Spanish:",
                "options": [],
                "answer": "Nos vamos a mudar el mes que viene",
                "hints": ["'Mudarse' = to move (change homes).", "'El mes que viene' = next month."],
                "xp": 25,
                "lesson": "'Mudarse' = to move (change residence). 'Nos mudamos' = we're moving. 'La mudanza' = the move (noun). 'La empresa de mudanzas' = moving company. 'Hacer las cajas' = to pack boxes. 'Desempacar' / 'deshacer las cajas' = to unpack. 'Cambiar de casa' = to change homes. Moving day: 'el día de la mudanza.'",
            },
            {
                "id": "rn_piso",
                "title": "The Apartment",
                "type": "quiz",
                "question": "In Spain, what does 'un piso' typically refer to?",
                "options": ["A house with a garden", "An apartment/flat", "A parking space", "A storage room"],
                "answer": "b",
                "hints": ["It's the most common type of housing in Spanish cities.", "In Latin America, they say 'apartamento' or 'departamento' instead."],
                "xp": 25,
                "lesson": "'El piso' = apartment/flat (Spain). In Latin America: 'el apartamento' or 'el departamento.' 'Un piso amueblado' = a furnished apartment. 'Un piso sin amueblar' = an unfurnished apartment. 'Compartir piso' = to share an apartment (very common among students). 'Compañero de piso' = flatmate/roommate.",
            },
            {
                "id": "rn_vecino",
                "title": "The Neighbor",
                "type": "text",
                "question": "Type the Spanish word for 'neighbor' (masculine, with article):",
                "options": [],
                "answer": "el vecino",
                "hints": ["It starts with 'v'.", "The neighborhood is 'el vecindario.'"],
                "xp": 25,
                "lesson": "'El vecino' / 'la vecina' = the neighbor. 'Los vecinos' = the neighbors. 'El vecindario' = the neighborhood. 'La comunidad de vecinos' = the homeowners' association (very important in Spanish apartment buildings!). 'Llevarse bien con los vecinos' = to get along with the neighbors. 'La reunión de vecinos' = the neighbors' meeting.",
            },
            {
                "id": "rn_contrato",
                "title": "The Contract",
                "type": "quiz",
                "question": "'Antes de mudarte, firma el contrato de alquiler' means:",
                "options": ["Before moving, read the reviews", "Before moving, sign the rental contract", "Before moving, pay the deposit", "Before moving, meet the neighbors"],
                "answer": "b",
                "hints": ["'Firmar' = to sign.", "'El contrato de alquiler' = the rental contract."],
                "xp": 25,
                "lesson": "'El contrato de alquiler' = the rental contract. 'Firmar' = to sign. 'La fianza' = the deposit (usually one or two months' rent in Spain). 'El propietario' / 'la propietaria' = the landlord/owner. 'El inquilino' / 'la inquilina' = the tenant. 'Leer el contrato antes de firmar' = Read the contract before signing. Always!",
            },
            {
                "id": "rn_fianza",
                "title": "The Deposit",
                "type": "text",
                "question": "Type how you ask 'How much is the deposit?' in Spanish:",
                "options": [],
                "answer": "¿Cuánto es la fianza?",
                "hints": ["'¿Cuánto es...?' = How much is...?", "'La fianza' = the deposit."],
                "xp": 30,
                "lesson": "'La fianza' = the deposit/security deposit. '¿Cuánto es la fianza?' = How much is the deposit? In Spain, the legal minimum deposit is one month's rent for residential rentals. 'Pagar la fianza' = to pay the deposit. 'Recuperar la fianza' = to get the deposit back. 'Los gastos incluidos' = utilities included. 'Los gastos no incluidos' = utilities not included.",
            },
            {
                "id": "rn_servicios",
                "title": "Utilities & Services",
                "type": "quiz",
                "question": "'¿Los gastos de agua y luz están incluidos en el alquiler?' means:",
                "options": ["Is the water and electricity bill expensive?", "Are water and electricity included in the rent?", "When do I pay the water and electricity?", "Where is the water and electricity meter?"],
                "answer": "b",
                "hints": ["'Incluidos' = included.", "'Gastos' = expenses/costs."],
                "xp": 25,
                "lesson": "'Los gastos' = expenses/utilities. Key utilities: 'el agua' (water), 'la luz/electricidad' (electricity), 'el gas' (gas), 'internet/wifi.' 'Gastos incluidos' = utilities included. 'Dar de alta la luz' = to set up electricity service. 'Dar de baja' = to cancel service. Always ask: '¿Qué gastos están incluidos?' = What utilities are included?",
            },
            {
                "id": "rn_moving_boss",
                "title": "The Apartment Search",
                "type": "quiz",
                "question": "You're visiting a rental apartment. Which set of questions is the most useful to ask the landlord?",
                "options": ["¿Es bonito el barrio?", "¿Cuánto es el alquiler mensual? ¿La fianza es de un mes? ¿Los gastos de agua y luz están incluidos? ¿Cuándo puedo mudarme?", "¿Tiene vecinos?", "¿Puedo ver otra vez la cocina?"],
                "answer": "b",
                "hints": ["Cover rent, deposit, utilities, and move-in date.", "Ask practical questions about the rental terms."],
                "xp": 35,
                "lesson": "Essential rental questions: '¿Cuánto es el alquiler mensual?' (monthly rent), '¿la fianza?' (deposit), '¿gastos incluidos?' (utilities included), '¿cuándo puedo mudarme?' (when can I move in). Also useful: '¿Se admiten mascotas?' (are pets allowed?), '¿cuánto dura el contrato?' (how long is the lease?). You're ready to apartment-hunt in Spanish!",
                "is_boss": True,
            },
        ],
    },
}
