"""
zones.py — Health & Body zones and challenges.

Mix of quiz and text challenges covering body parts, feelings & emotions,
visiting the doctor, pharmacy & medicine, and healthy habits.
Guided by Doctora Elena, a warm and experienced physician in a Spanish clinic at sunset.
"""

ZONE_ORDER = [
    "body_parts",
    "feelings_emotions",
    "at_the_doctor",
    "pharmacy_medicine",
    "healthy_habits",
]

ZONES = {
    # -- Zone 1: Body Parts --
    "body_parts": {
        "id": "body_parts",
        "name": "Body Parts",
        "description": "Learn the Spanish names for parts of the body",
        "level_required": 1,
        "challenges": [
            {
                "id": "bp_cabeza",
                "title": "The Head",
                "type": "quiz",
                "question": "How do you say 'head' in Spanish?",
                "options": ["La cabeza", "El brazo", "La pierna", "El pecho"],
                "answer": "a",
                "hints": ["It starts with 'c'.", "Think of the phrase 'cabeza de familia' (head of the family)."],
                "xp": 25,
                "lesson": "'La cabeza' = the head. This is one of the most important body words. 'Me duele la cabeza' (My head hurts / I have a headache) is one of the most common health phrases in Spanish. 'Dolor de cabeza' = headache.",
            },
            {
                "id": "bp_brazo",
                "title": "The Arm",
                "type": "text",
                "question": "Type the Spanish word for 'arm' (with the article 'el'):",
                "options": [],
                "answer": "el brazo",
                "hints": ["It's a masculine noun.", "It starts with 'b'."],
                "xp": 25,
                "lesson": "'El brazo' = the arm. 'Los brazos' = the arms (plural). Related words: 'el codo' (elbow), 'la muñeca' (wrist), 'el hombro' (shoulder). 'Me duele el brazo' = My arm hurts. 'Levanta los brazos' = Raise your arms.",
            },
            {
                "id": "bp_pierna",
                "title": "The Leg",
                "type": "quiz",
                "question": "'Me duele la pierna' means:",
                "options": ["My arm hurts", "My leg hurts", "My back hurts", "My foot hurts"],
                "answer": "b",
                "hints": ["'La pierna' is a body part below the waist.", "'Duele' means it hurts."],
                "xp": 25,
                "lesson": "'La pierna' = the leg. 'Las piernas' = the legs. Related: 'la rodilla' (knee), 'el tobillo' (ankle), 'el muslo' (thigh). 'No puedo mover la pierna' = I can't move my leg. 'Tengo dolor en la pierna derecha' = I have pain in my right leg.",
            },
            {
                "id": "bp_mano",
                "title": "The Hand",
                "type": "quiz",
                "question": "Which is the correct Spanish word for 'hand'?",
                "options": ["El pie", "La mano", "El dedo", "La uña"],
                "answer": "b",
                "hints": ["It's feminine despite ending in 'o' -- a rare exception!", "Think 'manual' in English."],
                "xp": 25,
                "lesson": "'La mano' = the hand. Note: 'la mano' is feminine even though it ends in -o -- one of the few exceptions in Spanish! 'Las manos' = the hands. 'Los dedos de la mano' = fingers. 'Lavarse las manos' = to wash one's hands. 'Dame la mano' = Give me your hand.",
            },
            {
                "id": "bp_ojo",
                "title": "The Eye",
                "type": "text",
                "question": "Type the Spanish word for 'eye' (with the article 'el'):",
                "options": [],
                "answer": "el ojo",
                "hints": ["It's a very short word.", "It starts with 'o'."],
                "xp": 25,
                "lesson": "'El ojo' = the eye. 'Los ojos' = the eyes. 'Ojo!' on its own means 'Watch out!' or 'Be careful!' Related: 'la ceja' (eyebrow), 'la pestaña' (eyelash), 'la pupila' (pupil). 'Me duelen los ojos' = My eyes hurt. 'Tengo los ojos rojos' = My eyes are red.",
            },
            {
                "id": "bp_oreja",
                "title": "The Ear",
                "type": "quiz",
                "question": "'La oreja' refers to:",
                "options": ["The mouth", "The nose", "The ear", "The neck"],
                "answer": "c",
                "hints": ["It's on the side of your head.", "It starts with 'o' like 'ojo.'"],
                "xp": 25,
                "lesson": "'La oreja' = the ear (outer ear). 'El oído' = the inner ear or hearing. 'Me duele el oído' (My ear hurts -- usually means an ear infection). 'No oigo bien' = I can't hear well. 'Habla más alto, por favor' = Speak louder, please. The distinction between oreja and oído matters at the doctor!",
            },
            {
                "id": "bp_espalda",
                "title": "The Back",
                "type": "text",
                "question": "Type how you say 'My back hurts' in Spanish (use 'la espalda'):",
                "options": [],
                "answer": "Me duele la espalda",
                "hints": ["'Me duele' = it hurts me.", "'La espalda' = the back."],
                "xp": 30,
                "lesson": "'Me duele la espalda' = My back hurts. 'La espalda' = the back. 'Dolor de espalda' = back pain. Related: 'la columna' (spine), 'la espalda baja' (lower back). Back pain is one of the most common complaints: 'Tengo mucho dolor de espalda' = I have a lot of back pain.",
            },
            {
                "id": "bp_body_boss",
                "title": "Point to the Pain",
                "type": "quiz",
                "question": "A doctor asks 'Dónde le duele?' (Where does it hurt?). You have a headache and your right arm hurts. Which is the best answer?",
                "options": ["Duele todo.", "Me duele la cabeza y el brazo derecho.", "Estoy mal.", "No sé dónde me duele."],
                "answer": "b",
                "hints": ["Name the specific body parts.", "'Derecho' means right."],
                "xp": 35,
                "lesson": "'Me duele la cabeza y el brazo derecho' = My head and my right arm hurt. Being specific helps the doctor! Directions: 'derecho/a' (right), 'izquierdo/a' (left). Pattern: 'Me duele' + singular body part, 'Me duelen' + plural body parts. You can now describe exactly where it hurts!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 2: Feelings & Emotions --
    "feelings_emotions": {
        "id": "feelings_emotions",
        "name": "Feelings & Emotions",
        "description": "Express how you feel in Spanish",
        "level_required": 1,
        "challenges": [
            {
                "id": "fe_feliz",
                "title": "Happy",
                "type": "quiz",
                "question": "'Estoy feliz' means:",
                "options": ["I am sad", "I am happy", "I am tired", "I am angry"],
                "answer": "b",
                "hints": ["'Feliz' is a positive emotion.", "Think 'felicidad' (happiness)."],
                "xp": 25,
                "lesson": "'Estoy feliz' = I am happy. We use 'estar' (not 'ser') because feelings are temporary states. 'Estoy muy feliz' = I'm very happy. Synonyms: 'contento/a' (content), 'alegre' (cheerful). 'Feliz cumpleaños' = Happy birthday! 'Feliz Navidad' = Merry Christmas!",
            },
            {
                "id": "fe_triste",
                "title": "Sad",
                "type": "text",
                "question": "Type how you say 'I am sad' in Spanish (use 'estar'):",
                "options": [],
                "answer": "Estoy triste",
                "hints": ["'Estoy' = I am (temporary state).", "'Triste' means sad."],
                "xp": 25,
                "lesson": "'Estoy triste' = I am sad. 'Tristeza' = sadness (noun). 'Estoy un poco triste' = I'm a little sad. 'Estoy muy triste' = I'm very sad. 'No estés triste' = Don't be sad. Using 'estar' shows it's a current state, not a permanent trait -- an important distinction in Spanish!",
            },
            {
                "id": "fe_cansado",
                "title": "Tired",
                "type": "quiz",
                "question": "How do you say 'I am tired' in Spanish (masculine)?",
                "options": ["Estoy enfermo", "Estoy cansado", "Estoy aburrido", "Estoy nervioso"],
                "answer": "b",
                "hints": ["'Cansado' comes from 'cansar' (to tire).", "It describes physical fatigue."],
                "xp": 25,
                "lesson": "'Estoy cansado' (masc.) / 'Estoy cansada' (fem.) = I am tired. 'Estoy muy cansado' = I'm very tired. 'Estoy agotado/a' = I'm exhausted (stronger). 'Estoy cansado de trabajar' = I'm tired from working. 'Necesito descansar' = I need to rest.",
            },
            {
                "id": "fe_enfermo",
                "title": "Sick",
                "type": "quiz",
                "question": "'Me siento enfermo' means:",
                "options": ["I feel happy", "I feel hungry", "I feel sick", "I feel cold"],
                "answer": "c",
                "hints": ["'Enfermo' relates to illness.", "'Me siento' = I feel."],
                "xp": 25,
                "lesson": "'Me siento enfermo/a' = I feel sick. 'Estoy enfermo/a' also works. 'Enfermedad' = illness/disease. 'Enfermero/a' = nurse. 'No me siento bien' = I don't feel well (a versatile phrase). 'Me siento mal' = I feel bad. These are essential phrases when you need to explain you're unwell.",
            },
            {
                "id": "fe_hambre",
                "title": "Hungry",
                "type": "text",
                "question": "Type how you say 'I am hungry' in Spanish (hint: Spanish uses 'tener' -- to have):",
                "options": [],
                "answer": "Tengo hambre",
                "hints": ["In Spanish you 'have hunger' rather than 'are hungry.'", "'Hambre' = hunger."],
                "xp": 25,
                "lesson": "'Tengo hambre' = I am hungry (literally 'I have hunger'). Spanish uses 'tener' for many sensations: 'tengo sed' (I'm thirsty), 'tengo frío' (I'm cold), 'tengo calor' (I'm hot), 'tengo sueño' (I'm sleepy), 'tengo miedo' (I'm afraid). This 'tener + noun' pattern is essential!",
            },
            {
                "id": "fe_preocupado",
                "title": "Worried",
                "type": "quiz",
                "question": "'Estoy preocupado por mi salud' means:",
                "options": ["I'm happy about my health", "I'm worried about my health", "I'm proud of my health", "I'm focused on my health"],
                "answer": "b",
                "hints": ["'Preocupado' = worried.", "'Salud' = health."],
                "xp": 30,
                "lesson": "'Estoy preocupado/a por mi salud' = I'm worried about my health. 'Preocuparse' = to worry. 'No te preocupes' = Don't worry. 'La salud' = health. 'Salud!' is also what you say when someone sneezes (like 'Bless you!') and when toasting ('Cheers!'). A versatile word!",
            },
            {
                "id": "fe_mejor",
                "title": "Feeling Better",
                "type": "text",
                "question": "Type how you say 'I feel better' in Spanish:",
                "options": [],
                "answer": "Me siento mejor",
                "hints": ["'Me siento' = I feel.", "'Mejor' = better."],
                "xp": 30,
                "lesson": "'Me siento mejor' = I feel better. 'Mejor' = better, 'peor' = worse. 'Me siento mucho mejor' = I feel much better. 'Me siento peor' = I feel worse. 'Cada día me siento mejor' = Every day I feel better. These comparison words are vital for describing your condition to a doctor!",
            },
            {
                "id": "fe_feelings_boss",
                "title": "How Are You Really?",
                "type": "quiz",
                "question": "A friend asks '¿Cómo te sientes?' (How do you feel?). You're tired, a bit sad, but getting better. Which is the most complete answer?",
                "options": ["Bien.", "Estoy cansado y un poco triste, pero me siento mejor.", "No sé.", "Estoy feliz y tengo hambre."],
                "answer": "b",
                "hints": ["Combine multiple feelings for a complete answer.", "Use 'pero' (but) to show contrast."],
                "xp": 35,
                "lesson": "'Estoy cansado y un poco triste, pero me siento mejor' combines multiple feelings naturally. Key connectors: 'y' (and), 'pero' (but), 'un poco' (a little), 'muy' (very). You can now express complex emotional states in Spanish -- not just 'bien' or 'mal' but real, nuanced feelings!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 3: At the Doctor --
    "at_the_doctor": {
        "id": "at_the_doctor",
        "name": "At the Doctor",
        "description": "Navigate a doctor's visit in Spanish",
        "level_required": 2,
        "challenges": [
            {
                "id": "doc_medico",
                "title": "The Doctor",
                "type": "quiz",
                "question": "How do you say 'I need to see a doctor' in Spanish?",
                "options": ["Necesito ver a un médico", "Quiero ir al banco", "Necesito un taxi", "Voy a la tienda"],
                "answer": "a",
                "hints": ["'Médico' means doctor.", "'Necesito' = I need."],
                "xp": 25,
                "lesson": "'Necesito ver a un médico' = I need to see a doctor. 'El médico' / 'la médica' = the doctor. 'El/la doctor/a' also works. 'Ir al médico' = to go to the doctor. 'Tengo cita con el médico' = I have an appointment with the doctor. In emergencies: '¡Llamen a un médico!' = Call a doctor!",
            },
            {
                "id": "doc_hospital",
                "title": "The Hospital",
                "type": "text",
                "question": "Type how you ask 'Where is the hospital?' in Spanish:",
                "options": [],
                "answer": "¿Dónde está el hospital?",
                "hints": ["'Dónde está' = where is.", "'Hospital' is almost the same in English!"],
                "xp": 25,
                "lesson": "'¿Dónde está el hospital?' = Where is the hospital? 'El hospital' = the hospital. Related: 'urgencias' (emergency room), 'la clínica' (clinic), 'el centro de salud' (health center). 'Necesito ir a urgencias' = I need to go to the ER. In Spain, the health system is excellent and emergency care is free for everyone.",
            },
            {
                "id": "doc_medicina",
                "title": "Medicine",
                "type": "quiz",
                "question": "'El médico me recetó una medicina' means:",
                "options": ["The doctor gave me a bill", "The doctor prescribed me a medicine", "The doctor refused me medicine", "The doctor recommended a hospital"],
                "answer": "b",
                "hints": ["'Recetar' means to prescribe.", "'Medicina' = medicine."],
                "xp": 25,
                "lesson": "'Recetar' = to prescribe. 'La medicina' or 'el medicamento' = medicine/medication. 'La receta' = prescription. 'Tomar la medicina' = to take the medicine. '¿Cada cuánto tomo la medicina?' = How often do I take the medicine? 'Dos veces al día' = Twice a day.",
            },
            {
                "id": "doc_dolor",
                "title": "Pain",
                "type": "text",
                "question": "Type how you say 'I have a lot of pain' in Spanish:",
                "options": [],
                "answer": "Tengo mucho dolor",
                "hints": ["'Dolor' = pain.", "'Mucho' = a lot of."],
                "xp": 25,
                "lesson": "'Tengo mucho dolor' = I have a lot of pain. 'El dolor' = pain. Describing pain: 'dolor agudo' (sharp pain), 'dolor leve' (mild pain), 'dolor constante' (constant pain). 'En una escala del uno al diez, ¿cuánto le duele?' = On a scale of 1-10, how much does it hurt? Very useful at the doctor!",
            },
            {
                "id": "doc_fiebre",
                "title": "Fever",
                "type": "quiz",
                "question": "'Tengo fiebre y escalofríos' means:",
                "options": ["I have a cough and cold", "I have fever and chills", "I have a headache and nausea", "I have allergies and sneezing"],
                "answer": "b",
                "hints": ["'Fiebre' = fever.", "'Escalofríos' = chills/shivers."],
                "xp": 25,
                "lesson": "'Tengo fiebre' = I have a fever. 'Escalofríos' = chills. 'Tengo 38 grados de fiebre' = I have a fever of 38 degrees (Celsius is used in Spain). Related symptoms: 'tos' (cough), 'gripe' (flu), 'resfriado' (cold), 'estornudar' (to sneeze). 'Tengo fiebre desde ayer' = I've had a fever since yesterday.",
            },
            {
                "id": "doc_sintomas",
                "title": "Describing Symptoms",
                "type": "quiz",
                "question": "The doctor asks '¿Qué síntomas tiene?' How should you respond if you have a cough and sore throat?",
                "options": ["Tengo hambre y sed", "Tengo tos y dolor de garganta", "Tengo sueño y frío", "Tengo prisa y estrés"],
                "answer": "b",
                "hints": ["'Tos' = cough.", "'Dolor de garganta' = sore throat."],
                "xp": 30,
                "lesson": "'Tengo tos y dolor de garganta' = I have a cough and sore throat. '¿Qué síntomas tiene?' = What symptoms do you have? Common symptoms: 'náuseas' (nausea), 'mareo' (dizziness), 'vómitos' (vomiting), 'diarrea' (diarrhea), 'congestión nasal' (nasal congestion). Be specific -- it helps the doctor!",
            },
            {
                "id": "doc_desde_cuando",
                "title": "Since When?",
                "type": "text",
                "question": "Type how you say 'Since three days ago' in Spanish (use 'desde hace'):",
                "options": [],
                "answer": "Desde hace tres días",
                "hints": ["'Desde hace' expresses duration from the past.", "'Tres días' = three days."],
                "xp": 30,
                "lesson": "'Desde hace tres días' = Since three days ago / For three days. The doctor will ask '¿Desde cuándo tiene estos síntomas?' (Since when have you had these symptoms?). 'Desde hace una semana' (for a week), 'desde ayer' (since yesterday), 'desde esta mañana' (since this morning).",
            },
            {
                "id": "doc_doctor_boss",
                "title": "The Full Consultation",
                "type": "quiz",
                "question": "You're at the doctor with a fever and headache for two days. Which is the most complete way to explain your situation?",
                "options": ["Estoy mal.", "Tengo fiebre y dolor de cabeza desde hace dos días. También tengo escalofríos.", "Me duele.", "Necesito medicina."],
                "answer": "b",
                "hints": ["Include symptoms, duration, and additional details.", "Be specific about what you feel and for how long."],
                "xp": 35,
                "lesson": "A complete doctor explanation includes: symptoms ('tengo fiebre y dolor de cabeza'), duration ('desde hace dos días'), and additional details ('también tengo escalofríos'). This gives the doctor everything they need. You can now navigate a medical visit in Spanish with confidence!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 4: Pharmacy & Medicine --
    "pharmacy_medicine": {
        "id": "pharmacy_medicine",
        "name": "Pharmacy & Medicine",
        "description": "Get what you need at a Spanish pharmacy",
        "level_required": 2,
        "challenges": [
            {
                "id": "ph_farmacia",
                "title": "The Pharmacy",
                "type": "quiz",
                "question": "How do you ask 'Is there a pharmacy nearby?' in Spanish?",
                "options": ["¿Hay una farmacia cerca?", "¿Dónde está el banco?", "¿Hay un supermercado?", "¿Tiene una tienda?"],
                "answer": "a",
                "hints": ["'Farmacia' = pharmacy.", "'Cerca' = nearby."],
                "xp": 25,
                "lesson": "'¿Hay una farmacia cerca?' = Is there a pharmacy nearby? 'La farmacia' = the pharmacy. In Spain, pharmacies are marked with a green flashing cross. 'Farmacia de guardia' = duty pharmacy (open 24 hours, rotating schedule). Pharmacists in Spain can recommend over-the-counter medicines directly!",
            },
            {
                "id": "ph_receta",
                "title": "The Prescription",
                "type": "text",
                "question": "Type the Spanish word for 'prescription' (feminine noun):",
                "options": [],
                "answer": "receta",
                "hints": ["It starts with 'r'.", "It's related to 'recetar' (to prescribe)."],
                "xp": 25,
                "lesson": "'La receta' = the prescription. 'Necesito una receta' = I need a prescription. '¿Necesito receta para este medicamento?' = Do I need a prescription for this medication? 'Sin receta' = over the counter (without prescription). 'Con receta' = by prescription only. Important distinction at Spanish pharmacies!",
            },
            {
                "id": "ph_pastilla",
                "title": "The Pill",
                "type": "quiz",
                "question": "'Tome una pastilla cada ocho horas' means:",
                "options": ["Take a pill every eight hours", "Take a pill every day", "Buy eight pills", "The pill costs eight euros"],
                "answer": "a",
                "hints": ["'Pastilla' = pill/tablet.", "'Cada ocho horas' = every eight hours."],
                "xp": 25,
                "lesson": "'Tome una pastilla cada ocho horas' = Take one pill every eight hours. 'La pastilla' = pill/tablet. 'El jarabe' = syrup. 'Las gotas' = drops. 'La pomada' = ointment/cream. Dosage phrases: 'una vez al día' (once a day), 'dos veces al día' (twice a day), 'antes de comer' (before eating), 'después de comer' (after eating).",
            },
            {
                "id": "ph_alergia",
                "title": "Allergies at the Pharmacy",
                "type": "quiz",
                "question": "'¿Tiene algo para la alergia?' means:",
                "options": ["Do you have something for the allergy?", "Am I allergic to this?", "Is this allergy medicine?", "How much is the allergy medicine?"],
                "answer": "a",
                "hints": ["'¿Tiene algo para...?' = Do you have something for...?", "'La alergia' = the allergy."],
                "xp": 25,
                "lesson": "'¿Tiene algo para la alergia?' = Do you have something for the allergy? The pattern '¿Tiene algo para...?' is incredibly useful at pharmacies: '...para el dolor de cabeza' (for a headache), '...para la tos' (for a cough), '...para el estómago' (for the stomach), '...para las quemaduras de sol' (for sunburn).",
            },
            {
                "id": "ph_efectos",
                "title": "Side Effects",
                "type": "text",
                "question": "Type how you ask 'Does this medicine have side effects?' in Spanish (use 'efectos secundarios'):",
                "options": [],
                "answer": "¿Este medicamento tiene efectos secundarios?",
                "hints": ["'Efectos secundarios' = side effects.", "'Este medicamento' = this medicine."],
                "xp": 30,
                "lesson": "'Efectos secundarios' = side effects. Always ask! Common side effects: 'somnolencia' (drowsiness), 'mareo' (dizziness), 'náuseas' (nausea), 'dolor de estómago' (stomach pain). '¿Puedo conducir después de tomar esto?' = Can I drive after taking this? The pharmacist is always happy to explain.",
            },
            {
                "id": "ph_antibiotico",
                "title": "Antibiotics",
                "type": "quiz",
                "question": "'Los antibióticos necesitan receta médica' means:",
                "options": ["Antibiotics are expensive", "Antibiotics need a medical prescription", "Antibiotics are sold everywhere", "Antibiotics are not effective"],
                "answer": "b",
                "hints": ["'Receta médica' = medical prescription.", "'Necesitan' = they need."],
                "xp": 25,
                "lesson": "'Los antibióticos necesitan receta médica' = Antibiotics require a medical prescription. In Spain, antibiotics are strictly prescription-only. 'Receta médica' = medical prescription. 'Medicamento con receta' = prescription medication. 'Medicamento sin receta' = over-the-counter medication. This rule helps fight antibiotic resistance!",
            },
            {
                "id": "ph_como_tomar",
                "title": "How to Take It",
                "type": "text",
                "question": "Type how you ask 'How should I take this medicine?' in Spanish:",
                "options": [],
                "answer": "¿Cómo debo tomar este medicamento?",
                "hints": ["'¿Cómo debo...?' = How should I...?", "'Tomar' = to take."],
                "xp": 30,
                "lesson": "'¿Cómo debo tomar este medicamento?' = How should I take this medicine? The pharmacist might say: 'Con agua' (with water), 'con comida' (with food), 'en ayunas' (on an empty stomach), 'antes de acostarse' (before bed). 'No mezclar con alcohol' = Do not mix with alcohol.",
            },
            {
                "id": "ph_pharmacy_boss",
                "title": "The Pharmacy Visit",
                "type": "quiz",
                "question": "You have a cold and need medicine. Which is the most effective way to get help at the pharmacy?",
                "options": ["Estoy mal, deme algo.", "Buenos días. Tengo tos y dolor de garganta desde ayer. ¿Tiene algo para el resfriado? ¿Necesito receta?", "Quiero antibióticos.", "¿Cuánto cuesta todo?"],
                "answer": "b",
                "hints": ["Describe your symptoms, duration, and ask about the medicine.", "Be specific and ask if a prescription is needed."],
                "xp": 35,
                "lesson": "An effective pharmacy visit includes: greeting ('buenos días'), symptoms ('tengo tos y dolor de garganta'), duration ('desde ayer'), specific request ('¿tiene algo para el resfriado?'), and practical question ('¿necesito receta?'). Spanish pharmacists are highly trained and can recommend treatments -- use this resource!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 5: Healthy Habits --
    "healthy_habits": {
        "id": "healthy_habits",
        "name": "Healthy Habits",
        "description": "Talk about exercise, sleep, nutrition, and wellness in Spanish",
        "level_required": 3,
        "challenges": [
            {
                "id": "hh_ejercicio",
                "title": "Exercise",
                "type": "quiz",
                "question": "'Hago ejercicio tres veces a la semana' means:",
                "options": ["I exercise three times a week", "I exercise three hours a day", "I started exercising three weeks ago", "I need to exercise three more times"],
                "answer": "a",
                "hints": ["'Hacer ejercicio' = to exercise.", "'Tres veces a la semana' = three times a week."],
                "xp": 25,
                "lesson": "'Hacer ejercicio' = to exercise. 'Hago ejercicio' = I exercise. 'Tres veces a la semana' = three times a week. Types: 'correr' (to run), 'nadar' (to swim), 'caminar' (to walk), 'ir al gimnasio' (to go to the gym), 'hacer yoga' (to do yoga). 'El ejercicio es bueno para la salud' = Exercise is good for health.",
            },
            {
                "id": "hh_dormir",
                "title": "Sleep",
                "type": "text",
                "question": "Type how you say 'I need to sleep eight hours' in Spanish:",
                "options": [],
                "answer": "Necesito dormir ocho horas",
                "hints": ["'Dormir' = to sleep.", "'Ocho horas' = eight hours."],
                "xp": 25,
                "lesson": "'Necesito dormir ocho horas' = I need to sleep eight hours. 'Dormir' = to sleep. 'El sueño' = sleep (noun). 'Tengo insomnio' = I have insomnia. 'No puedo dormir' = I can't sleep. 'Dormir bien es fundamental para la salud' = Sleeping well is essential for health. 'La siesta' is a treasured Spanish tradition!",
            },
            {
                "id": "hh_comer_bien",
                "title": "Eating Well",
                "type": "quiz",
                "question": "'Es importante comer bien y variado' means:",
                "options": ["It's important to eat fast", "It's important to eat well and varied", "It's important to eat less", "It's important to eat only vegetables"],
                "answer": "b",
                "hints": ["'Comer bien' = to eat well.", "'Variado' = varied."],
                "xp": 25,
                "lesson": "'Comer bien y variado' = to eat well and varied. 'Una dieta equilibrada' = a balanced diet. Key food groups: 'frutas y verduras' (fruits and vegetables), 'proteínas' (proteins), 'cereales' (grains). 'Comer cinco porciones de fruta al día' = Eat five portions of fruit a day. The Mediterranean diet from Spain is world-famous!",
            },
            {
                "id": "hh_agua",
                "title": "Drinking Water",
                "type": "text",
                "question": "Type how you say 'You should drink more water' in Spanish (use 'deberías'):",
                "options": [],
                "answer": "Deberías beber más agua",
                "hints": ["'Deberías' = you should.", "'Beber' = to drink, 'agua' = water."],
                "xp": 25,
                "lesson": "'Deberías beber más agua' = You should drink more water. 'El agua' = water (uses 'el' even though it's feminine -- another exception!). 'Mantenerse hidratado' = to stay hydrated. 'Beber dos litros de agua al día' = Drink two liters of water a day. 'El agua es esencial para la salud' = Water is essential for health.",
            },
            {
                "id": "hh_estres",
                "title": "Managing Stress",
                "type": "quiz",
                "question": "'Necesito reducir el estrés' means:",
                "options": ["I need to increase stress", "I need to reduce stress", "I need to ignore stress", "I need to create stress"],
                "answer": "b",
                "hints": ["'Reducir' = to reduce.", "'El estrés' = stress."],
                "xp": 25,
                "lesson": "'Reducir el estrés' = to reduce stress. Ways to manage: 'meditar' (to meditate), 'respirar profundo' (breathe deeply), 'tomarse un descanso' (take a break), 'pasar tiempo al aire libre' (spend time outdoors). 'El estrés afecta la salud' = Stress affects health. Mental health matters: 'la salud mental' = mental health.",
            },
            {
                "id": "hh_chequeo",
                "title": "Regular Check-ups",
                "type": "quiz",
                "question": "'Es recomendable hacerse un chequeo médico anual' means:",
                "options": ["It's recommended to get an annual medical check-up", "It's expensive to visit the doctor yearly", "Annual check-ups are not important", "Doctors recommend changing medicine annually"],
                "answer": "a",
                "hints": ["'Chequeo médico' = medical check-up.", "'Anual' = annual."],
                "xp": 30,
                "lesson": "'Hacerse un chequeo médico' = to get a medical check-up. 'Anual' = annual/yearly. 'Un análisis de sangre' = a blood test. 'La presión arterial' = blood pressure. 'Revisión dental' = dental check-up. Prevention is key: 'Prevenir es mejor que curar' = Prevention is better than cure -- a common Spanish saying!",
            },
            {
                "id": "hh_equilibrio",
                "title": "Work-Life Balance",
                "type": "text",
                "question": "Type how you say 'It is important to rest' in Spanish:",
                "options": [],
                "answer": "Es importante descansar",
                "hints": ["'Es importante' = it is important.", "'Descansar' = to rest."],
                "xp": 30,
                "lesson": "'Es importante descansar' = It's important to rest. 'Descansar' = to rest. 'El descanso' = rest (noun). 'Equilibrio entre trabajo y vida personal' = work-life balance. Spanish culture values this: long lunches, the paseo (evening walk), and strong family time. 'Disfrutar de la vida' = to enjoy life!",
            },
            {
                "id": "hh_habits_boss",
                "title": "Your Wellness Plan",
                "type": "quiz",
                "question": "A friend asks for health advice. Which response covers the most healthy habits?",
                "options": ["Come más.", "Deberías hacer ejercicio, dormir ocho horas, beber mucha agua y comer frutas y verduras.", "No te preocupes por nada.", "Ve al médico todos los días."],
                "answer": "b",
                "hints": ["A good wellness plan covers exercise, sleep, hydration, and nutrition.", "Combine multiple habits in one recommendation."],
                "xp": 35,
                "lesson": "A complete wellness plan in Spanish: 'hacer ejercicio' (exercise), 'dormir ocho horas' (sleep eight hours), 'beber mucha agua' (drink lots of water), 'comer frutas y verduras' (eat fruits and vegetables). You can now discuss healthy living in Spanish -- from diet to sleep to stress management. ¡Cuida tu salud!",
                "is_boss": True,
            },
        ],
    },
}
