"""
zones.py — French Basics zones and challenges.

All challenges use "type": "quiz" with multiple-choice options.
Guided by Marie, a patient and enthusiastic French teacher.
"""

ZONE_ORDER = [
    "alphabet_pronunciation",
    "articles",
    "subject_pronouns",
    "etre_avoir",
    "common_adjectives",
]

ZONES = {
    # -- Zone 1: Alphabet & Pronunciation --
    "alphabet_pronunciation": {
        "id": "alphabet_pronunciation",
        "name": "Alphabet & Pronunciation",
        "description": "Learn the French alphabet and key pronunciation rules",
        "level_required": 1,
        "challenges": [
            {
                "id": "alpha_vowels",
                "title": "French Vowels",
                "type": "quiz",
                "question": "How many vowel letters does the French alphabet have (a, e, i, o, u, y)?",
                "options": ["5", "6", "7", "4"],
                "answer": "b",
                "hints": ["Don't forget 'y', which is considered a vowel in French.", "Count: a, e, i, o, u, y."],
                "xp": 25,
                "lesson": "French has 6 vowel letters: a, e, i, o, u, y. French vowels are 'pure' -- they don't glide like English vowels. The letter 'e' alone has multiple sounds depending on accents: e, e, e (as in le, ete, pere).",
            },
            {
                "id": "alpha_accent_aigu",
                "title": "The Accent Aigu",
                "type": "quiz",
                "question": "What sound does 'e' make in words like 'cafe' and 'ete'?",
                "options": ["Like 'uh' in 'the'", "Like 'ay' in 'day'", "Like 'ee' in 'see'", "Like 'eh' in 'bed'"],
                "answer": "b",
                "hints": ["The accent aigu (e) always makes the same sound.", "Think of the English word 'cafe' -- that final sound."],
                "xp": 25,
                "lesson": "The accent aigu (e) is the most common French accent. It only appears on 'e' and makes an 'ay' sound (like 'day'). Examples: cafe, ete (summer), ecole (school), etudiant (student). It tells you exactly how to pronounce the vowel.",
            },
            {
                "id": "alpha_silent_letters",
                "title": "Silent Letters",
                "type": "quiz",
                "question": "In French, which final consonant is usually NOT silent?",
                "options": ["s", "t", "c", "d"],
                "answer": "c",
                "hints": ["Think of the word 'avec' (with) -- you hear that final consonant.", "The memory aid is 'CaReFuL' -- C, R, F, L are usually pronounced."],
                "xp": 25,
                "lesson": "Most final consonants in French are silent: 'petit' (puh-TEE), 'pas' (PAH). But C, R, F, and L are usually pronounced -- remember 'CaReFuL': avec (with), bonjour (hello), sportif (sporty), animal. This rule has exceptions but works most of the time!",
            },
            {
                "id": "alpha_nasal_vowels",
                "title": "Nasal Sounds",
                "type": "quiz",
                "question": "The word 'bon' (good) contains a nasal vowel. What makes it nasal?",
                "options": ["The 'b' is pronounced through the nose", "The 'on' is pronounced through the nose without saying the 'n'", "You hum while saying it", "The 'o' is pronounced longer"],
                "answer": "b",
                "hints": ["The 'n' after a vowel signals a nasal sound in French.", "You don't actually pronounce the 'n' as a separate consonant."],
                "xp": 25,
                "lesson": "French has nasal vowels -- the air goes through your nose. The key nasal combinations: 'on/om' (bon, nom), 'an/am/en/em' (dans, temps), 'in/im/ain/ein' (vin, pain). The 'n' or 'm' is not pronounced as a consonant -- it just nasalizes the vowel.",
            },
            {
                "id": "alpha_liaison",
                "title": "Liaison",
                "type": "quiz",
                "question": "In 'les amis' (the friends), why do you hear a 'z' sound between the two words?",
                "options": ["There is a hidden 'z' in French", "The silent 's' in 'les' links to the vowel in 'amis'", "It's a regional accent", "The 'a' in 'amis' sounds like 'z'"],
                "answer": "b",
                "hints": ["This linking phenomenon is called 'liaison'.", "Silent final consonants come alive before a vowel."],
                "xp": 25,
                "lesson": "Liaison is when a normally silent final consonant is pronounced because the next word starts with a vowel: les amis (lay-zah-MEE), un ami (uh-nah-MEE), vous avez (voo-zah-VAY). It makes French flow smoothly and is essential for natural speech.",
            },
            {
                "id": "alpha_r_sound",
                "title": "The French R",
                "type": "quiz",
                "question": "The French 'r' is produced:",
                "options": ["At the tip of the tongue like English", "In the back of the throat", "By rolling the tongue like Spanish", "With the lips like a 'w'"],
                "answer": "b",
                "hints": ["Think of a gentle gargling sound.", "It's a uvular sound, not a tongue-tip sound."],
                "xp": 25,
                "lesson": "The French 'r' is uvular -- produced in the back of the throat, like a soft gargle. It's one of the most distinctive French sounds. Practice with: rouge (red), rue (street), bonjour (hello). Start by gargling gently and reducing the intensity!",
            },
            {
                "id": "alpha_cedilla",
                "title": "The Cedilla",
                "type": "quiz",
                "question": "What does the cedilla (c) do in words like 'francais' and 'garcon'?",
                "options": ["Makes the 'c' sound like 'k'", "Makes the 'c' sound like 's'", "Makes the 'c' silent", "Makes the 'c' sound like 'ch'"],
                "answer": "b",
                "hints": ["Without the cedilla, 'c' before 'a', 'o', 'u' sounds like 'k'.", "The cedilla softens the 'c'."],
                "xp": 25,
                "lesson": "The cedilla (c) makes 'c' sound like 's' before a, o, u. Without it, 'c' before those letters sounds like 'k'. Compare: ca = 'ka', but ca = 'sa'. Examples: francais (French), garcon (boy), lecon (lesson), recu (received).",
            },
            {
                "id": "alpha_boss",
                "title": "Pronunciation Master",
                "type": "quiz",
                "question": "Which word is pronounced with a silent final consonant?",
                "options": ["Avec", "Petit", "Bonjour", "Animal"],
                "answer": "b",
                "hints": ["Remember the CaReFuL rule for final consonants that ARE pronounced.", "'Petit' ends in 't' -- is 't' in the CaReFuL group?"],
                "xp": 30,
                "lesson": "'Petit' is pronounced 'puh-TEE' -- the final 't' is silent. The other words follow the CaReFuL rule: avec (the 'c' is heard), bonjour (the 'r' is heard), animal (the 'l' is heard). Mastering silent letters is key to sounding French!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 2: Articles (le/la/les/un/une) --
    "articles": {
        "id": "articles",
        "name": "Articles: le, la, les, un, une",
        "description": "Learn French definite and indefinite articles",
        "level_required": 1,
        "challenges": [
            {
                "id": "art_le_la",
                "title": "Le vs La",
                "type": "quiz",
                "question": "In French, 'le' is used for ___ nouns and 'la' is used for ___ nouns.",
                "options": ["Feminine / masculine", "Masculine / feminine", "Singular / plural", "Plural / singular"],
                "answer": "b",
                "hints": ["'Le' goes with masculine, 'la' goes with feminine.", "Every French noun has a gender!"],
                "xp": 25,
                "lesson": "'Le' = the (masculine): le livre (the book), le chat (the cat). 'La' = the (feminine): la maison (the house), la fleur (the flower). Every French noun is either masculine or feminine -- there's no 'it'. Always learn the article with the noun!",
            },
            {
                "id": "art_les",
                "title": "Les - The Plural",
                "type": "quiz",
                "question": "'Les' is the plural form of 'the.' It is used for:",
                "options": ["Only masculine plural nouns", "Only feminine plural nouns", "Both masculine and feminine plural nouns", "Uncountable nouns"],
                "answer": "c",
                "hints": ["'Les' doesn't care about gender.", "It replaces both 'le' and 'la' in the plural."],
                "xp": 25,
                "lesson": "'Les' = the (plural), for both genders: les livres (the books), les maisons (the houses). Unlike le/la, 'les' doesn't distinguish gender. Remember liaison: 'les amis' is pronounced 'lay-zah-MEE'.",
            },
            {
                "id": "art_un_une",
                "title": "Un vs Une",
                "type": "quiz",
                "question": "How do you say 'a cat' if 'chat' is masculine?",
                "options": ["Une chat", "Un chat", "Le chat", "Des chat"],
                "answer": "b",
                "hints": ["'Un' is the indefinite article for masculine nouns.", "'A/an' in French depends on the noun's gender."],
                "xp": 25,
                "lesson": "'Un' = a/an (masculine): un chat (a cat), un livre (a book). 'Une' = a/an (feminine): une maison (a house), une fleur (a flower). The indefinite articles match gender just like le/la.",
            },
            {
                "id": "art_l_apostrophe",
                "title": "L' - The Elision",
                "type": "quiz",
                "question": "Why do we write 'l'ecole' instead of 'la ecole'?",
                "options": ["It's a spelling error", "French drops the vowel in le/la before words starting with a vowel", "Ecole is masculine", "L' is only used for schools"],
                "answer": "b",
                "hints": ["Two vowel sounds in a row is avoided in French.", "This is called 'elision' -- the vowel is replaced by an apostrophe."],
                "xp": 25,
                "lesson": "Before a vowel or silent 'h', le and la become l': l'ecole (the school), l'homme (the man), l'eau (the water). This is called elision. It makes French flow smoothly by avoiding two vowel sounds in a row.",
            },
            {
                "id": "art_des",
                "title": "Des - Some/Plural A",
                "type": "quiz",
                "question": "What is the plural of 'un/une' (a/an)?",
                "options": ["Les", "Des", "Uns", "De"],
                "answer": "b",
                "hints": ["English doesn't have a plural of 'a', but French does.", "'Des' = some, used for unspecified plural items."],
                "xp": 25,
                "lesson": "'Des' is the plural indefinite article -- it means 'some' or just marks an unspecified plural: des livres (some books), des amis (some friends). English often drops the article ('I have books'), but French always requires one: 'J'ai des livres.'",
            },
            {
                "id": "art_gender_tips",
                "title": "Guessing Gender",
                "type": "quiz",
                "question": "Nouns ending in '-tion' (like 'nation', 'information') are usually:",
                "options": ["Masculine", "Feminine", "Could be either", "Plural only"],
                "answer": "b",
                "hints": ["Think of 'la nation', 'la situation'.", "Most nouns ending in -tion, -sion, -te are feminine."],
                "xp": 25,
                "lesson": "Gender tips: usually feminine endings include -tion (la nation), -sion (la decision), -te (la liberte), -ure (la nature), -ence/-ance (la science). Usually masculine: -ment (le moment), -age (le voyage), -eau (le gateau). These patterns help, but always learn the article!",
            },
            {
                "id": "art_du_de_la",
                "title": "Partitive Articles",
                "type": "quiz",
                "question": "To say 'I want some water' (Je veux ___ eau), which article fills the blank?",
                "options": ["La", "De l'", "Le", "Un"],
                "answer": "b",
                "hints": ["'Eau' starts with a vowel, and we need the partitive 'some'.", "The partitive before a vowel uses elision."],
                "xp": 25,
                "lesson": "Partitive articles express 'some' with uncountable nouns: du (masc) = du pain (some bread), de la (fem) = de la confiture (some jam), de l' (before vowel) = de l'eau (some water). French always specifies 'some' where English might skip it.",
            },
            {
                "id": "art_boss",
                "title": "Article Master",
                "type": "quiz",
                "question": "Choose the correct article: '___ amie de Marie est gentille.' (Marie's friend is nice. 'Amie' = female friend.)",
                "options": ["Le", "La", "L'", "Un"],
                "answer": "c",
                "hints": ["'Amie' starts with a vowel.", "We need the definite article (the), and it must elide."],
                "xp": 30,
                "lesson": "'L'amie' -- since 'amie' starts with a vowel, we use l' (elision). It doesn't matter that 'amie' is feminine; before a vowel, both 'le' and 'la' become 'l''. This is one of the most important rules in French article usage!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 3: Subject Pronouns --
    "subject_pronouns": {
        "id": "subject_pronouns",
        "name": "Subject Pronouns",
        "description": "Learn je, tu, il, elle, on, nous, vous, ils, elles",
        "level_required": 2,
        "challenges": [
            {
                "id": "pron_je_tu",
                "title": "Je & Tu",
                "type": "quiz",
                "question": "'Je' means 'I' and 'tu' means 'you' (informal). What happens to 'je' before a vowel?",
                "options": ["It stays 'je'", "It becomes 'j'' (j'aime, j'ai)", "It becomes 'ji'", "It is dropped entirely"],
                "answer": "b",
                "hints": ["Elision applies to 'je' just like articles.", "Think of 'j'ai' (I have) and 'j'aime' (I love)."],
                "xp": 25,
                "lesson": "'Je' becomes 'j'' before a vowel or silent 'h': j'ai (I have), j'aime (I love), j'habite (I live). 'Tu' does NOT elide: tu aimes (you love), not *t'aimes. This elision only applies to 'je' among the pronouns.",
            },
            {
                "id": "pron_il_elle",
                "title": "Il & Elle",
                "type": "quiz",
                "question": "'Il' means ___ and 'elle' means ___.",
                "options": ["She / he", "He / she", "We / they", "It / that"],
                "answer": "b",
                "hints": ["'Il' is masculine, 'elle' is feminine.", "Both can also mean 'it' for objects."],
                "xp": 25,
                "lesson": "'Il' = he/it (masculine) and 'elle' = she/it (feminine). Since all French nouns have gender, 'il' and 'elle' also replace things: le livre -> il est grand (it is big), la maison -> elle est grande (it is big).",
            },
            {
                "id": "pron_on",
                "title": "On - The Versatile Pronoun",
                "type": "quiz",
                "question": "In everyday French, 'on' is commonly used to mean:",
                "options": ["He", "She", "We (informal)", "They (formal)"],
                "answer": "c",
                "hints": ["Officially 'on' means 'one' or 'people', but in conversation...", "French friends say 'on va au cinema' instead of 'nous allons'."],
                "xp": 25,
                "lesson": "'On' officially means 'one/people in general' (On parle francais ici = People speak French here). But in everyday French, 'on' replaces 'nous' (we): 'On y va!' (Let's go!). It uses the il/elle verb form. This is the #1 way to say 'we' in casual French.",
            },
            {
                "id": "pron_nous_vous",
                "title": "Nous & Vous",
                "type": "quiz",
                "question": "'Vous' can mean:",
                "options": ["Only 'you' plural", "Only 'you' formal singular", "Both 'you' plural and 'you' formal singular", "We"],
                "answer": "c",
                "hints": ["Like 'usted/ustedes' in Spanish, 'vous' has a double role.", "It's the polite form AND the plural form."],
                "xp": 25,
                "lesson": "'Nous' = we (formal/written). 'Vous' = you (plural) OR you (formal singular). Talking to your boss? 'Vous.' Talking to two friends? Also 'vous.' This dual role is just like 'you' in English serving both singular and plural.",
            },
            {
                "id": "pron_ils_elles",
                "title": "Ils & Elles",
                "type": "quiz",
                "question": "If a group contains 10 women and 1 man, which pronoun do you use?",
                "options": ["Elles", "Ils", "On", "Nous"],
                "answer": "b",
                "hints": ["French grammar has a rule about mixed groups.", "If there's even one masculine noun, the masculine pronoun wins."],
                "xp": 25,
                "lesson": "'Ils' = they (masculine or mixed group). 'Elles' = they (all feminine). Even one masculine person in a group of 100 women makes it 'ils'. This is called the 'masculine default' rule. 'Elles' is only used when everyone is female.",
            },
            {
                "id": "pron_ce_cest",
                "title": "C'est - It is",
                "type": "quiz",
                "question": "How do you say 'It's beautiful' in French?",
                "options": ["Il est beau", "C'est beau", "Elle est belle", "Ce beau"],
                "answer": "b",
                "hints": ["'C'est' is used for general statements and descriptions.", "It comes from 'ce' (this/it) + 'est' (is)."],
                "xp": 25,
                "lesson": "'C'est' (it is / this is) is used constantly in French. C'est beau (It's beautiful), c'est bon (It's good), c'est facile (It's easy). For people: c'est mon ami (this is my friend). The plural form is 'ce sont': ce sont mes amis (these are my friends).",
            },
            {
                "id": "pron_subject_review",
                "title": "Pronoun Pairs",
                "type": "quiz",
                "question": "Match the correct pair: 'they (all female)' and 'we (informal spoken)':",
                "options": ["Ils / nous", "Elles / on", "Ils / on", "Elles / nous"],
                "answer": "b",
                "hints": ["All-female 'they' = elles.", "Informal 'we' in spoken French = on."],
                "xp": 25,
                "lesson": "'Elles' = they (all female), 'on' = we (informal). The full pronoun chart: je (I), tu (you informal), il/elle/on (he/she/we-one), nous (we formal), vous (you formal/plural), ils/elles (they). Master these and every verb conjugation will click!",
            },
            {
                "id": "pron_boss",
                "title": "Pronoun Master",
                "type": "quiz",
                "question": "Your teacher asks 'Vous comprenez?' What does 'vous' mean here if she's speaking to the whole class?",
                "options": ["You (formal singular)", "You (plural - the whole class)", "We", "They"],
                "answer": "b",
                "hints": ["She's addressing multiple students.", "When speaking to a group, 'vous' is always plural."],
                "xp": 30,
                "lesson": "Context is key with 'vous'! Speaking to a class = you (plural). Speaking to one person you don't know well = you (formal). The verb form is the same either way. When in doubt, use 'vous' -- it's never wrong to be polite!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 4: Etre & Avoir --
    "etre_avoir": {
        "id": "etre_avoir",
        "name": "Etre & Avoir",
        "description": "Master the two most important French verbs: to be and to have",
        "level_required": 2,
        "challenges": [
            {
                "id": "verb_etre_meaning",
                "title": "Etre = To Be",
                "type": "quiz",
                "question": "What does 'etre' mean?",
                "options": ["To have", "To be", "To go", "To do"],
                "answer": "b",
                "hints": ["'Je suis' = I am.", "It's the French equivalent of English 'to be'."],
                "xp": 25,
                "lesson": "'Etre' (to be) is the most used verb in French. Conjugation: je suis (I am), tu es (you are), il/elle est (he/she is), nous sommes (we are), vous etes (you are), ils/elles sont (they are). It's completely irregular -- memorize each form!",
            },
            {
                "id": "verb_etre_je_tu",
                "title": "Je suis, Tu es",
                "type": "quiz",
                "question": "Complete: 'Je ___ francais.' (I am French.)",
                "options": ["es", "suis", "est", "sommes"],
                "answer": "b",
                "hints": ["'Je' goes with 'suis'.", "I am = je suis."],
                "xp": 25,
                "lesson": "'Je suis' (I am) is one of the first things you'll say in French. Je suis americain(e) (I'm American), Je suis etudiant(e) (I'm a student), Je suis fatigue(e) (I'm tired). Note: adjectives change form for feminine (-e ending).",
            },
            {
                "id": "verb_etre_il_elle",
                "title": "Il est, Elle est",
                "type": "quiz",
                "question": "How do you say 'She is intelligent'?",
                "options": ["Elle suis intelligente", "Elle es intelligente", "Elle est intelligente", "Elle sont intelligente"],
                "answer": "c",
                "hints": ["Il/elle uses 'est'.", "Note the feminine form of the adjective too."],
                "xp": 25,
                "lesson": "'Il est' / 'Elle est' (he is / she is). The adjective must agree in gender: il est intelligent, elle est intelligente (added -e). il est grand, elle est grande. This gender agreement is a fundamental French rule.",
            },
            {
                "id": "verb_avoir_meaning",
                "title": "Avoir = To Have",
                "type": "quiz",
                "question": "What does 'avoir' mean?",
                "options": ["To be", "To have", "To see", "To want"],
                "answer": "b",
                "hints": ["'J'ai' = I have.", "The second most important French verb."],
                "xp": 25,
                "lesson": "'Avoir' (to have): j'ai (I have), tu as (you have), il/elle a (he/she has), nous avons (we have), vous avez (you have), ils/elles ont (they have). Also irregular -- note 'j'ai' with elision, and the silent 'h' in the infinitive.",
            },
            {
                "id": "verb_avoir_age",
                "title": "Avoir for Age",
                "type": "quiz",
                "question": "In French, 'I am 20 years old' is said as:",
                "options": ["Je suis 20 ans", "J'ai 20 ans", "Je fais 20 ans", "J'es 20 ans"],
                "answer": "b",
                "hints": ["French uses 'to have' for age, not 'to be'.", "Literally: 'I have 20 years.'"],
                "xp": 25,
                "lesson": "French uses 'avoir' (to have) for age: 'J'ai 20 ans' = I have 20 years (I'm 20). 'Quel age as-tu?' = What age do you have? (How old are you?) This is a key difference from English -- never use 'etre' for age!",
            },
            {
                "id": "verb_avoir_expressions",
                "title": "Avoir Expressions",
                "type": "quiz",
                "question": "'J'ai faim' literally means 'I have hunger.' What does it really mean?",
                "options": ["I am hungry", "I have food", "I am full", "I need to eat hunger"],
                "answer": "a",
                "hints": ["French says 'to have hunger' where English says 'to be hungry'.", "Many feelings use 'avoir' in French."],
                "xp": 25,
                "lesson": "French uses 'avoir' for many states that English uses 'to be' for: j'ai faim (I'm hungry), j'ai soif (I'm thirsty), j'ai froid (I'm cold), j'ai chaud (I'm hot), j'ai peur (I'm scared), j'ai sommeil (I'm sleepy), j'ai raison (I'm right).",
            },
            {
                "id": "verb_etre_vs_avoir",
                "title": "Etre vs Avoir",
                "type": "quiz",
                "question": "Which sentence is correct for 'We are tired'?",
                "options": ["Nous avons fatigues", "Nous sommes fatigues", "Nous sont fatigues", "Nous etes fatigues"],
                "answer": "b",
                "hints": ["'Tired' is a state of being, not something you 'have'.", "'Nous' + etre = nous sommes."],
                "xp": 25,
                "lesson": "'Nous sommes fatigues' (We are tired). Use 'etre' for descriptions and states (je suis content, elle est grande). Use 'avoir' for age, hunger, thirst, fear, etc. The trick is that some expressions that use 'to be' in English use 'avoir' in French!",
            },
            {
                "id": "verb_boss",
                "title": "Verb Master",
                "type": "quiz",
                "question": "Fill in both blanks: 'Elle ___ 25 ans et elle ___ professeur.'",
                "options": ["est / a", "a / est", "suis / ai", "as / es"],
                "answer": "b",
                "hints": ["Age uses 'avoir', profession uses 'etre'.", "Both blanks use the il/elle form."],
                "xp": 30,
                "lesson": "'Elle a 25 ans et elle est professeur.' Age = avoir (she has 25 years). Profession = etre (she is a teacher). Note: French doesn't use an article before professions with etre: 'elle est professeur' (not 'elle est une professeur'). Mastering etre and avoir is the foundation of all French!",
                "is_boss": True,
            },
        ],
    },

    # -- Zone 5: Common Adjectives --
    "common_adjectives": {
        "id": "common_adjectives",
        "name": "Common Adjectives",
        "description": "Describe the world around you with essential French adjectives",
        "level_required": 3,
        "challenges": [
            {
                "id": "adj_gender_agreement",
                "title": "Gender Agreement",
                "type": "quiz",
                "question": "The masculine adjective 'petit' (small) becomes ___ in the feminine.",
                "options": ["petit", "petite", "petits", "petites"],
                "answer": "b",
                "hints": ["Most adjectives add -e for feminine.", "The final 't' becomes pronounced in the feminine form."],
                "xp": 25,
                "lesson": "Most French adjectives add -e for feminine: petit -> petite, grand -> grande, intelligent -> intelligente. This often changes pronunciation: the final consonant becomes audible. 'Petit' = puh-TEE, 'petite' = puh-TEET.",
            },
            {
                "id": "adj_plural",
                "title": "Plural Adjectives",
                "type": "quiz",
                "question": "How do you make 'grand' (big/tall) plural masculine?",
                "options": ["Grande", "Grands", "Grandes", "Grander"],
                "answer": "b",
                "hints": ["Plural usually adds -s, just like nouns.", "Masculine plural = base form + s."],
                "xp": 25,
                "lesson": "Adjective agreement has 4 forms: grand (masc sing), grande (fem sing), grands (masc plural), grandes (fem plural). The -s is silent in speech: 'grands' sounds the same as 'grand'. But it must be written!",
            },
            {
                "id": "adj_position",
                "title": "Before or After?",
                "type": "quiz",
                "question": "Most French adjectives go ___ the noun, unlike English.",
                "options": ["Before", "After", "Either position", "Inside"],
                "answer": "b",
                "hints": ["English says 'a red car', French says 'une voiture rouge' (a car red).", "Position is reversed compared to English."],
                "xp": 25,
                "lesson": "Most French adjectives come AFTER the noun: une voiture rouge (a red car), un film interessant (an interesting movie). But common short adjectives go BEFORE: petit, grand, bon, mauvais, beau, joli, nouveau, vieux, jeune. Remember BANGS: Beauty, Age, Number, Goodness, Size.",
            },
            {
                "id": "adj_beau_belle",
                "title": "Beau & Belle",
                "type": "quiz",
                "question": "'Beau' (beautiful/handsome) becomes ___ in the feminine.",
                "options": ["Beaue", "Belle", "Beau", "Beaute"],
                "answer": "b",
                "hints": ["This is an irregular adjective -- it changes completely.", "Think of the name 'Belle' from Beauty and the Beast."],
                "xp": 25,
                "lesson": "Some adjectives are irregular: beau -> belle (beautiful), nouveau -> nouvelle (new), vieux -> vieille (old). Before a masculine vowel-word, special forms exist: un bel homme (a handsome man), un nouvel ami (a new friend), un vieil arbre (an old tree).",
            },
            {
                "id": "adj_bon_mauvais",
                "title": "Bon & Mauvais",
                "type": "quiz",
                "question": "'Bon' means good and 'mauvais' means bad. What is the feminine of 'bon'?",
                "options": ["Bone", "Bonne", "Bons", "Bonnes"],
                "answer": "b",
                "hints": ["'Bon' doubles the 'n' before adding -e.", "Like 'bonne nuit' (good night)."],
                "xp": 25,
                "lesson": "'Bon' -> 'bonne' (good): the 'n' doubles. Un bon repas (a good meal), une bonne idee (a good idea). 'Mauvais' -> 'mauvaise' (bad): just adds -e. Bon and mauvais go BEFORE the noun: un bon livre (a good book), un mauvais jour (a bad day).",
            },
            {
                "id": "adj_colors",
                "title": "Colors",
                "type": "quiz",
                "question": "The color 'blanc' (white) becomes ___ in the feminine.",
                "options": ["Blanque", "Blanche", "Blanc", "Blance"],
                "answer": "b",
                "hints": ["This is an irregular feminine form.", "Think of the name 'Blanche'."],
                "xp": 25,
                "lesson": "Colors follow adjective rules and go AFTER the noun: un chat noir (a black cat), une robe rouge (a red dress). Some have irregular feminines: blanc -> blanche (white), and some never change: orange, marron (brown). Colors always agree in gender and number.",
            },
            {
                "id": "adj_tres",
                "title": "Very & Really",
                "type": "quiz",
                "question": "How do you say 'very big' in French?",
                "options": ["Grand tres", "Beaucoup grand", "Tres grand", "Trop grand"],
                "answer": "c",
                "hints": ["'Tres' means 'very' and goes before the adjective.", "Like English: very + adjective."],
                "xp": 25,
                "lesson": "'Tres' (very) goes before adjectives: tres grand (very big), tres beau (very beautiful), tres interessant (very interesting). Other modifiers: assez (quite), trop (too much), vraiment (really), un peu (a little). These never change form.",
            },
            {
                "id": "adj_boss",
                "title": "Adjective Master",
                "type": "quiz",
                "question": "Choose the correct sentence for 'She is a beautiful new house': 'C'est une ___ ___ maison.'",
                "options": ["belle nouvelle", "beau nouveau", "nouvelle belle", "belles nouvelles"],
                "answer": "a",
                "hints": ["'Maison' is feminine, so both adjectives need feminine forms.", "Beau -> belle, nouveau -> nouvelle."],
                "xp": 30,
                "lesson": "'C'est une belle nouvelle maison.' Both adjectives must agree with the feminine noun 'maison': beau -> belle, nouveau -> nouvelle. They go BEFORE the noun (BANGS rule). Adjective agreement in gender and number is the heartbeat of French grammar!",
                "is_boss": True,
            },
        ],
    },
}
