"""
zones.py — Art skill pack zones for Primer.
"""

from engine.zone import Zone
from engine.challenge import Challenge

ZONE_ORDER = [
    "colors_and_mixing",
    "shapes_and_patterns",
    "art_tools",
    "famous_artwork",
    "art_elements",
    "famous_artists",
    "art_styles_through_history",
    "music_and_rhythm",
    "photography_and_film",
    "dance_and_theater",
    "architecture_and_design",
]

ZONES = {
    "colors_and_mixing": Zone(
        id="colors_and_mixing",
        title="Colors and Mixing",
        description="Learn about primary, secondary, and complementary colors and how to mix them.",
        challenges=[
            Challenge(
                id="art_primary_colors",
                type="quiz",
                prompt="What are the three primary colors?",
                options=["Green, Orange, Purple", "Red, Yellow, Blue", "Pink, White, Black", "Brown, Gray, Silver"],
                answer="b",
                explanation="Red, yellow, and blue are the primary colors! They can't be made by mixing other colors, but they can be mixed together to make all other colors.",
                xp=10,
            ),
            Challenge(
                id="art_mix_red_yellow",
                type="quiz",
                prompt="What color do you get when you mix red and yellow together?",
                options=["Purple", "Green", "Orange", "Brown"],
                answer="c",
                explanation="Red + yellow = orange! Orange is a secondary color because it's made by mixing two primary colors.",
                xp=10,
            ),
            Challenge(
                id="art_mix_blue_yellow",
                type="quiz",
                prompt="What color do you get when you mix blue and yellow?",
                options=["Orange", "Purple", "Green", "Gray"],
                answer="c",
                explanation="Blue + yellow = green! Like the color of leaves and grass. Green is another secondary color.",
                xp=10,
            ),
            Challenge(
                id="art_mix_red_blue",
                type="quiz",
                prompt="What color do you get when you mix red and blue?",
                options=["Orange", "Purple", "Green", "Pink"],
                answer="b",
                explanation="Red + blue = purple! Purple is the third secondary color. The three secondary colors are orange, green, and purple.",
                xp=10,
            ),
            Challenge(
                id="art_warm_cool",
                type="quiz",
                prompt="Which group of colors feels warm, like sunshine and fire?",
                options=["Blue, green, purple", "Red, orange, yellow", "Black, white, gray", "Pink, lavender, mint"],
                answer="b",
                explanation="Red, orange, and yellow are warm colors! They remind us of the sun, fire, and warmth. Blue, green, and purple are cool colors — like water, trees, and sky.",
                xp=10,
            ),
            Challenge(
                id="art_white_black",
                type="fill_blank",
                prompt="When you mix all the colors of paint together, you get a dark muddy _____.",
                answer="brown",
                explanation="Mixing lots of paint colors together makes a muddy brown (not black like mixing light does). In painting, black is usually used directly rather than mixed.",
                xp=15,
                hints=["It's a dark earthy color", "The color of mud or chocolate"],
            ),
        ],
    ),
    "shapes_and_patterns": Zone(
        id="shapes_and_patterns",
        title="Shapes and Patterns",
        description="Discover geometric shapes, symmetry, and repeating patterns in art.",
        challenges=[
            Challenge(
                id="art_shapes_basic",
                type="quiz",
                prompt="A shape that has 4 equal sides and 4 equal corners is called a:",
                options=["Rectangle", "Triangle", "Square", "Circle"],
                answer="c",
                explanation="A square has 4 equal sides and 4 right angle corners. Squares are everywhere in art — tiles, windows, and grids!",
                xp=10,
            ),
            Challenge(
                id="art_symmetry",
                type="quiz",
                prompt="A butterfly has symmetry. What does that mean?",
                options=[
                    "It has many different colors",
                    "Both sides look the same — if you fold it in half, the wings match",
                    "It can fly very fast",
                    "It has a pattern of dots",
                ],
                answer="b",
                explanation="Symmetry means both sides are mirror images of each other. Butterflies, human faces, and many works of art use symmetry because it looks balanced and beautiful.",
                xp=10,
            ),
            Challenge(
                id="art_pattern",
                type="quiz",
                prompt="A pattern repeats. Which of these is a pattern?",
                options=[
                    "A single red circle",
                    "A random collection of shapes",
                    "Circle, square, circle, square, circle, square...",
                    "One big yellow triangle",
                ],
                answer="c",
                explanation="A pattern repeats in a predictable way! Artists use patterns in fabric, tiles, wallpaper, and paintings. Patterns can use colors, shapes, lines, or pictures.",
                xp=10,
            ),
            Challenge(
                id="art_triangle_sides",
                type="fill_blank",
                prompt="A triangle has _____ sides.",
                answer="3",
                explanation="A triangle has 3 sides and 3 corners (angles). 'Tri' means three — like tricycle (3 wheels) or tripod (3 legs). Triangles appear in art, architecture, and nature!",
                xp=10,
            ),
            Challenge(
                id="art_abstract_shapes",
                type="quiz",
                prompt="In art, an 'organic' shape looks like:",
                options=[
                    "A perfect circle drawn with a compass",
                    "A grid of equal squares",
                    "A free-flowing shape like a leaf, cloud, or puddle",
                    "A triangle with equal sides",
                ],
                answer="c",
                explanation="Organic shapes are irregular and natural-looking, like shapes found in nature — leaves, clouds, puddles, animals. Geometric shapes (circles, squares) are more precise and mathematical.",
                xp=15,
                hints=["Think of shapes you find outside in nature"],
            ),
            Challenge(
                id="art_tessellation",
                type="quiz",
                prompt="When shapes fit together perfectly with no gaps (like a tile floor), it's called a:",
                options=["Symphony", "Tessellation", "Gradient", "Silhouette"],
                answer="b",
                explanation="A tessellation is when shapes fit together without gaps or overlaps, like bathroom tiles or honeycomb! The artist M.C. Escher made famous tessellations using birds and fish.",
                xp=15,
                hints=["Think of a tiled floor or bathroom wall"],
            ),
        ],
    ),
    "art_tools": Zone(
        id="art_tools",
        title="Art Tools and Materials",
        description="Learn about the different tools and materials artists use to create.",
        challenges=[
            Challenge(
                id="art_pencil",
                type="quiz",
                prompt="What does HB mean on a pencil?",
                options=[
                    "Hard Blue — for drawing in blue",
                    "Hard and Black — a medium pencil good for writing",
                    "High Brightness — for glowing drawings",
                    "Heavy Bold — for thick lines only",
                ],
                answer="b",
                explanation="HB stands for Hard and Black — it's a medium pencil perfect for writing and drawing. H pencils are harder (lighter lines), B pencils are softer (darker, smudgier lines).",
                xp=10,
            ),
            Challenge(
                id="art_watercolor",
                type="quiz",
                prompt="Watercolor paint is special because it:",
                options=[
                    "Never dries and stays wet forever",
                    "Can only be used in black and white",
                    "Is transparent — you can see layers through each other",
                    "Must be heated to use",
                ],
                answer="c",
                explanation="Watercolor is transparent (see-through), which makes it magical — light reflects off the white paper through the paint. Artists build up layers of color, each one showing through the last.",
                xp=10,
            ),
            Challenge(
                id="art_sculpture",
                type="fill_blank",
                prompt="Art that you can touch from all sides and has height, width, AND depth is called _____ art.",
                answer="sculpture",
                explanation="Sculpture is 3-dimensional (3D) art! You can walk around it. A painting is 2D (flat). Sculptures can be made from clay, stone, wood, metal, or even ice!",
                xp=15,
                hints=["Think of statues", "Starts with 'S', rhymes with 'culture'"],
            ),
            Challenge(
                id="art_canvas",
                type="quiz",
                prompt="What do most painters use to paint on?",
                options=["A window", "A canvas", "A mirror", "A chalkboard"],
                answer="b",
                explanation="A canvas is a special stretched fabric that painters use. Before canvas, artists painted on wooden panels, walls (frescoes), or even on ceiling (like Michelangelo in the Sistine Chapel)!",
                xp=10,
            ),
            Challenge(
                id="art_collage",
                type="quiz",
                prompt="A collage is made by:",
                options=[
                    "Drawing with pencils only",
                    "Cutting and gluing different materials (paper, fabric, photos) onto a surface",
                    "Painting with your fingers",
                    "Carving shapes from stone",
                ],
                answer="b",
                explanation="Collage (from the French word 'coller', to glue) is the art of assembling different materials! The artist Pablo Picasso helped make collage famous as a serious art form.",
                xp=10,
            ),
            Challenge(
                id="art_perspective",
                type="quiz",
                prompt="In a drawing, why do faraway objects look smaller than nearby objects?",
                options=[
                    "They actually ARE smaller",
                    "The artist uses perspective to make flat pictures look 3-dimensional",
                    "Light makes them shrink",
                    "It's just a mistake",
                ],
                answer="b",
                explanation="Perspective is a technique artists use to make flat (2D) drawings look 3-dimensional! Objects farther away are drawn smaller. Artists discovered perspective during the Renaissance around 500 years ago.",
                xp=15,
                hints=["It's a technique for making flat art look deep"],
            ),
        ],
    ),
    "famous_artwork": Zone(
        id="famous_artwork",
        title="Famous Artwork",
        description="Recognize and learn about some of the most famous paintings and sculptures in the world.",
        challenges=[
            Challenge(
                id="art_mona_lisa",
                type="quiz",
                prompt="The Mona Lisa, one of the most famous paintings in the world, shows:",
                options=["A queen on a throne", "A smiling woman with a mysterious expression", "A battle scene", "A bowl of fruit"],
                answer="b",
                explanation="The Mona Lisa is a portrait of a woman with a famous mysterious smile! Leonardo da Vinci painted it around 1503-1519. It hangs in the Louvre museum in Paris, France.",
                xp=10,
            ),
            Challenge(
                id="art_starry_night",
                type="quiz",
                prompt="The Starry Night, with its swirling sky and bright stars, was painted by:",
                options=["Claude Monet", "Pablo Picasso", "Vincent van Gogh", "Frida Kahlo"],
                answer="c",
                explanation="Vincent van Gogh painted The Starry Night in 1889. He used thick, swirling brushstrokes to show a night sky full of energy. It's now in the Museum of Modern Art in New York.",
                xp=10,
            ),
            Challenge(
                id="art_david",
                type="quiz",
                prompt="The statue of David — a giant marble sculpture of a young man — was carved by:",
                options=["Leonardo da Vinci", "Rembrandt", "Michelangelo", "Raphael"],
                answer="c",
                explanation="Michelangelo carved the statue of David from a single block of marble between 1501 and 1504. It's over 5 meters (17 feet) tall and stands in Florence, Italy.",
                xp=10,
            ),
            Challenge(
                id="art_sistine",
                type="fill_blank",
                prompt="Michelangelo painted famous scenes from the Bible on the _____ of the Sistine Chapel.",
                answer="ceiling",
                explanation="Michelangelo spent 4 years painting the Sistine Chapel ceiling! He had to lie on scaffolding high above the ground. It shows the story of creation, including the famous image of God reaching toward Adam.",
                xp=15,
                hints=["He had to look UP while painting", "The top of a room"],
            ),
            Challenge(
                id="art_water_lilies",
                type="quiz",
                prompt="The series of paintings called Water Lilies, showing a garden pond, was painted by:",
                options=["Vincent van Gogh", "Claude Monet", "Pablo Picasso", "Salvador Dalí"],
                answer="b",
                explanation="Claude Monet painted over 250 Water Lilies paintings! He built a special pond in his garden in Giverny, France, just to paint it. Monet was a famous Impressionist painter.",
                xp=10,
            ),
            Challenge(
                id="art_guernica",
                type="quiz",
                prompt="The painting Guernica, which shows the suffering caused by war in black and white and gray, was painted by:",
                options=["Pablo Picasso", "Leonardo da Vinci", "Frida Kahlo", "Claude Monet"],
                answer="a",
                explanation="Pablo Picasso painted Guernica in 1937 after a town in Spain was bombed during a war. It's a powerful protest against violence — one of the most important political paintings ever made.",
                xp=15,
                hints=["He's also famous for Cubism", "Spanish artist, rhymes with 'Picasso'"],
            ),
        ],
    ),
    "art_elements": Zone(
        id="art_elements",
        title="Elements of Art",
        description="Discover the basic building blocks that every artist uses: line, shape, color, texture, and space.",
        challenges=[
            Challenge(
                id="art_line_types",
                type="quiz",
                prompt="In art, a zigzag line usually makes a picture feel:",
                options=["Calm and peaceful", "Exciting, energetic, or tense", "Sad", "Round and soft"],
                answer="b",
                explanation="Different lines create different feelings! Zigzag lines feel energetic and exciting. Wavy lines feel calm and gentle. Diagonal lines feel like movement. Horizontal lines feel restful.",
                xp=10,
            ),
            Challenge(
                id="art_texture",
                type="quiz",
                prompt="In art, texture means:",
                options=[
                    "The size of the painting",
                    "How a surface feels (rough, smooth, bumpy) — or how it LOOKS like it would feel",
                    "The brightness of colors",
                    "Whether the painting has people in it",
                ],
                answer="b",
                explanation="Texture is how something feels to touch — or in a painting, how it LOOKS like it would feel. A painting of tree bark can look rough and bumpy even though the canvas is flat!",
                xp=10,
            ),
            Challenge(
                id="art_foreground_background",
                type="quiz",
                prompt="In a painting, the 'foreground' is:",
                options=[
                    "The very back of the scene, far away",
                    "The sky at the top",
                    "The part of the scene that is closest to the viewer",
                    "The frame around the painting",
                ],
                answer="c",
                explanation="The foreground is the front of the picture — the part closest to you. The background is the far-away part. The middle ground is in between! Artists use these to create depth.",
                xp=10,
            ),
            Challenge(
                id="art_contrast",
                type="fill_blank",
                prompt="Placing light colors next to dark colors creates _____ in artwork.",
                answer="contrast",
                explanation="Contrast means big differences — light next to dark, big next to small, rough next to smooth. Artists use contrast to make things stand out and to create exciting, dramatic effects.",
                xp=15,
                hints=["When opposites are placed next to each other"],
            ),
            Challenge(
                id="art_negative_space",
                type="quiz",
                prompt="In art, 'negative space' is:",
                options=[
                    "A painting that feels sad",
                    "The empty space AROUND and between the objects in a picture",
                    "Dark colors only",
                    "A painting with nothing in it",
                ],
                answer="b",
                explanation="Negative space is the space around objects — the background, the empty areas. The object itself is 'positive space.' Smart artists design both! The FedEx logo hides an arrow in its negative space.",
                xp=15,
                hints=["It's what's NOT the object — the space around it"],
            ),
            Challenge(
                id="art_proportion",
                type="quiz",
                prompt="If an artist draws a person with a HUGE head and tiny body, they are using:",
                options=[
                    "Perspective",
                    "Proportion — deliberately making parts different sizes for effect",
                    "Tessellation",
                    "Impressionism",
                ],
                answer="b",
                explanation="Proportion is the size relationship between parts. Cartoons and caricatures often exaggerate proportions for humor. Renaissance artists studied proportion carefully to make figures look realistic.",
                xp=10,
            ),
        ],
    ),
    "famous_artists": Zone(
        id="famous_artists",
        title="Famous Artists",
        description="Learn about the most celebrated artists in history and what made them unique.",
        challenges=[
            Challenge(
                id="art_da_vinci",
                type="quiz",
                prompt="Leonardo da Vinci was famous for being both an artist AND a:",
                options=[
                    "King of Italy",
                    "Scientist and inventor — he designed flying machines, studied anatomy, and engineered canals",
                    "Professional musician",
                    "Sailor who explored new continents",
                ],
                answer="b",
                explanation="Leonardo da Vinci (1452-1519) was a Renaissance genius — artist, scientist, engineer, and inventor. He designed early flying machines, studied the human body, and filled thousands of notebook pages with ideas!",
                xp=10,
            ),
            Challenge(
                id="art_frida_kahlo",
                type="quiz",
                prompt="Frida Kahlo, a famous Mexican artist, is known for painting:",
                options=[
                    "Large battle scenes and wars",
                    "Seascapes and ocean waves",
                    "Self-portraits that expressed her pain and Mexican culture",
                    "Abstract shapes with no recognizable objects",
                ],
                answer="c",
                explanation="Frida Kahlo (1907-1954) painted dozens of self-portraits that showed her inner feelings, physical pain, and pride in Mexican culture. She's one of the most celebrated female artists ever.",
                xp=10,
            ),
            Challenge(
                id="art_impressionism",
                type="quiz",
                prompt="Impressionist painters like Monet painted:",
                options=[
                    "Exactly what things look like with every tiny detail",
                    "Abstract shapes with no connection to real life",
                    "The feeling and impression of light and movement, with loose brushstrokes",
                    "Only religious subjects from the Bible",
                ],
                answer="c",
                explanation="Impressionists (1860s-1890s) wanted to capture a MOMENT — light changing on water, wind moving through grass. They used quick, visible brushstrokes outdoors. The name came from Monet's painting 'Impression, Sunrise.'",
                xp=10,
            ),
            Challenge(
                id="art_georgia_okeeffe",
                type="fill_blank",
                prompt="Georgia O'Keeffe, an American artist famous for giant close-up paintings of flowers and bones, was inspired by the landscapes of New _____ (US state).",
                answer="Mexico",
                explanation="Georgia O'Keeffe (1887-1986) moved to New Mexico and painted the desert landscapes, skulls, flowers, and sky in large, dramatic close-ups. She's one of America's most important modern artists.",
                xp=15,
                hints=["A southwestern US state", "It starts with 'M'"],
            ),
            Challenge(
                id="art_picasso_cubism",
                type="quiz",
                prompt="Pablo Picasso invented Cubism — a style where:",
                options=[
                    "Everything is painted in cubes of perfect geometry",
                    "Subjects are shown from multiple viewpoints at once, fragmented and reassembled",
                    "Only the color blue is used",
                    "Paintings look like photographs",
                ],
                answer="b",
                explanation="Cubism shows things from MULTIPLE angles at the same time — like seeing the front, side, and back of a face all at once. Picasso and Georges Braque invented it around 1907-1914.",
                xp=15,
                hints=["Multiple viewpoints simultaneously"],
            ),
            Challenge(
                id="art_basquiat",
                type="quiz",
                prompt="Jean-Michel Basquiat, who became famous as a young Black artist in New York in the 1980s, started his art career:",
                options=[
                    "At a prestigious art school",
                    "By painting graffiti and tagging buildings in New York City",
                    "Working as a museum curator",
                    "By winning a national art contest",
                ],
                answer="b",
                explanation="Jean-Michel Basquiat (1960-1988) started by spray-painting poetry and imagery on buildings in Manhattan. His energetic, raw style combined words, figures, and symbols. By 20, he was showing in major galleries worldwide.",
                xp=15,
                hints=["Started on city streets, not in a gallery"],
            ),
        ],
    ),
    "art_styles_through_history": Zone(
        id="art_styles_through_history",
        title="Art Styles Through History",
        description="Travel through time to discover how art changed from ancient cave paintings to modern street art.",
        challenges=[
            Challenge(
                id="art_cave_paintings",
                type="quiz",
                prompt="The oldest art humans ever made was painted on cave walls! What did early people mostly paint in caves like Lascaux in France?",
                options=[
                    "Flowers and trees",
                    "Animals like horses, bison, and deer",
                    "Portraits of their families",
                    "Maps of their land",
                ],
                answer="b",
                explanation="Cave paintings from 17,000+ years ago show mostly animals — horses, bison, deer, and rhinos. The Lascaux caves in France have over 600 painted animals! Early humans made paint from charcoal, clay, and berries.",
                xp=10,
            ),
            Challenge(
                id="art_renaissance_meaning",
                type="quiz",
                prompt="The Renaissance was an exciting period of art and ideas. What does the word 'Renaissance' mean?",
                options=["New beginning", "Rebirth", "Great age", "Golden time"],
                answer="b",
                explanation="Renaissance means 'rebirth' in French! (1300s-1600s). Artists like da Vinci and Michelangelo reborn the styles of ancient Greece and Rome while adding their own genius — realistic people, perfect proportions, and stunning detail.",
                xp=10,
            ),
            Challenge(
                id="art_baroque_style",
                type="quiz",
                prompt="Baroque art (1600s-1700s) was very dramatic. Which words BEST describe the Baroque style?",
                options=[
                    "Simple, calm, and quiet",
                    "Bold, dramatic, with strong light and dark contrast",
                    "Flat, geometric, and colorless",
                    "Blurry and impressionistic",
                ],
                answer="b",
                explanation="Baroque art was DRAMATIC! Artists like Rembrandt used chiaroscuro — sharp contrast between light and dark — to create tension and emotion. It was the Hollywood blockbuster of its era!",
                xp=10,
            ),
            Challenge(
                id="art_abstract_meaning",
                type="quiz",
                prompt="Abstract art does NOT try to look like real things. Which of these is an example of abstract art?",
                options=[
                    "A painting of a bowl of fruit",
                    "A portrait of a queen",
                    "Colored shapes and lines with no recognizable objects",
                    "A landscape of mountains",
                ],
                answer="c",
                explanation="Abstract art uses shapes, colors, lines, and textures to express ideas and feelings WITHOUT copying real objects. Wassily Kandinsky (1866-1944) was one of the first abstract painters — he believed colors and shapes could express music!",
                xp=10,
            ),
            Challenge(
                id="art_pop_art",
                type="quiz",
                prompt="Pop Art (1950s-60s) celebrated everyday objects and popular culture. Who was the most famous Pop Art artist, known for painting Campbell's Soup cans?",
                options=["Claude Monet", "Andy Warhol", "Salvador Dalí", "Jackson Pollock"],
                answer="b",
                explanation="Andy Warhol (1928-1987) made art out of everyday things — soup cans, Coca-Cola bottles, and celebrity faces like Marilyn Monroe. He said if you look closely at ordinary things, they become extraordinary.",
                xp=10,
            ),
            Challenge(
                id="art_surrealism",
                type="fill_blank",
                prompt="Surrealism was an art movement where artists painted dream-like, impossible scenes. Salvador Dalí was famous for his painting of melting _____ (time-keeping objects).",
                answer="clocks",
                explanation="Salvador Dalí's 'The Persistence of Memory' (1931) shows melting clocks dripping over a landscape — like a dream where time stops making sense! Surrealists believed dreams and imagination were more real than ordinary life.",
                xp=15,
                hints=["Objects that tell time", "They drip and melt like wax in the painting"],
            ),
        ],
    ),
    "music_and_rhythm": Zone(
        id="music_and_rhythm",
        title="Music and Rhythm",
        description="Discover how music is made, from instruments and notes to composers and rhythm.",
        challenges=[
            Challenge(
                id="art_music_notes",
                type="quiz",
                prompt="Musical notes are named using letters. What are the seven musical notes?",
                options=[
                    "A, B, C, D, E, F, G",
                    "Do, Re, Mi, Fa, Sol, La, Si",
                    "Both of the above — they are two names for the same notes!",
                    "1, 2, 3, 4, 5, 6, 7",
                ],
                answer="c",
                explanation="Musical notes have two naming systems! The letter names (A B C D E F G) and the solfège names (Do Re Mi Fa Sol La Ti) both describe the same 7 notes. You may know solfège from 'Do-Re-Mi' in The Sound of Music!",
                xp=10,
            ),
            Challenge(
                id="art_instrument_families",
                type="quiz",
                prompt="Instruments in an orchestra are grouped into families. A violin belongs to which family?",
                options=["Brass", "Woodwind", "Percussion", "Strings"],
                answer="d",
                explanation="The violin belongs to the string family! String instruments make sound by vibrating strings — either bowed (violin, cello) or plucked (guitar, harp). Other families are: brass (trumpet, tuba), woodwind (flute, clarinet), and percussion (drums, xylophone).",
                xp=10,
            ),
            Challenge(
                id="art_beethoven",
                type="quiz",
                prompt="Ludwig van Beethoven was one of history's greatest composers. What is AMAZING about Beethoven's greatest symphony, his Ninth Symphony?",
                options=[
                    "It was the shortest symphony ever written",
                    "He wrote it while completely deaf — he could not hear a single note!",
                    "It used 1,000 instruments",
                    "It was written in one single day",
                ],
                answer="b",
                explanation="Beethoven (1770-1827) lost his hearing in his 20s, yet composed some of his most powerful music while completely deaf — including the famous Ninth Symphony with its joyful 'Ode to Joy' finale. He never heard it performed!",
                xp=10,
            ),
            Challenge(
                id="art_rhythm_beat",
                type="quiz",
                prompt="The BEAT in music is like the heartbeat of a song. Which word describes music that has a fast beat?",
                options=["Largo", "Andante", "Allegro", "Adagio"],
                answer="c",
                explanation="Allegro means fast and lively in music! Musical speed (tempo) has Italian names: Largo = very slow, Andante = walking pace, Moderato = medium, Allegro = fast, Presto = very fast. Italian was used because Italy was the center of classical music!",
                xp=10,
            ),
            Challenge(
                id="art_mozart",
                type="quiz",
                prompt="Wolfgang Amadeus Mozart was a child prodigy. At what age did Mozart start composing his own music?",
                options=["5 years old", "12 years old", "18 years old", "25 years old"],
                answer="a",
                explanation="Mozart (1756-1791) started composing at AGE FIVE! By age 6, he was performing for royalty. By 12, he had composed symphonies, sonatas, and concertos. He composed over 600 works before dying at just 35 years old.",
                xp=10,
            ),
            Challenge(
                id="art_music_genres",
                type="fill_blank",
                prompt="Jazz music was invented in New _____, a city famous for blending African, Caribbean, and European musical traditions.",
                answer="Orleans",
                explanation="Jazz was born in New Orleans, Louisiana around 1900! It blended African rhythms, blues, ragtime, and European harmonies. Jazz gave musicians freedom to improvise — to make up music on the spot — which was revolutionary!",
                xp=15,
                hints=["A city in Louisiana on the Mississippi River", "Famous for Mardi Gras"],
            ),
        ],
    ),
    "photography_and_film": Zone(
        id="photography_and_film",
        title="Photography and Film",
        description="Explore how cameras, photographs, and movies capture the world and tell stories.",
        challenges=[
            Challenge(
                id="art_first_photo",
                type="quiz",
                prompt="The very first photograph ever taken showed a view from a window and took HOW LONG to expose (capture the image)?",
                options=["1 second", "10 minutes", "8 hours", "3 days"],
                answer="c",
                explanation="The oldest surviving photograph, taken by Joseph Nicéphore Niépce in 1826, required an 8-HOUR exposure! Modern cameras can capture images in 1/1000th of a second. Early cameras needed bright light for a very long time.",
                xp=10,
            ),
            Challenge(
                id="art_pixels",
                type="quiz",
                prompt="Digital photos are made up of tiny colored dots. What are these tiny dots called?",
                options=["Specks", "Pixels", "Dots", "Grains"],
                answer="b",
                explanation="Digital images are made of PIXELS — tiny squares of color! A 12-megapixel camera captures 12 million pixels. The more pixels, the sharper and more detailed the image. Pixel comes from 'picture element.'",
                xp=10,
            ),
            Challenge(
                id="art_film_frames",
                type="quiz",
                prompt="Movies are actually thousands of still photographs shown very quickly to fool your brain into seeing motion. How many frames (photos) per second do most movies show?",
                options=["5 frames", "12 frames", "24 frames", "100 frames"],
                answer="c",
                explanation="Standard movies show 24 frames per second! Your brain sees this as smooth motion. Modern action movies and video games often use 60 frames per second for ultra-smooth movement. Below 12 fps starts to look choppy.",
                xp=10,
            ),
            Challenge(
                id="art_camera_obscura",
                type="quiz",
                prompt="Before cameras were invented, artists used a 'camera obscura' to help draw realistically. What did a camera obscura do?",
                options=[
                    "It was a dark room or box that projected an image through a tiny hole onto a wall",
                    "It was a special lens that made things look bigger",
                    "It was a filter that removed color from a scene",
                    "It was a mirror that showed reflections in reverse",
                ],
                answer="a",
                explanation="Camera obscura (Latin for 'dark room') projected light through a tiny hole, creating an upside-down image inside! Artists would trace the projected image. It works on the same principle as a camera — which is where the name 'camera' comes from!",
                xp=10,
            ),
            Challenge(
                id="art_animation",
                type="quiz",
                prompt="Traditional hand-drawn animation (like early Disney films) required animators to draw each frame individually. About how many drawings were needed for ONE MINUTE of animation?",
                options=["24 drawings", "240 drawings", "1,440 drawings", "14,400 drawings"],
                answer="c",
                explanation="At 24 frames per second × 60 seconds = 1,440 drawings per minute! Snow White (1937) had over 2 MILLION drawings. Modern computer animation (CGI) creates frames mathematically, but still requires enormous creative effort.",
                xp=15,
                hints=["24 frames per second × 60 seconds in a minute"],
            ),
            Challenge(
                id="art_photo_composition",
                type="fill_blank",
                prompt="Photographers use the 'Rule of ___' — dividing a photo into a 3×3 grid and placing the subject at the intersection of the lines — to make images more interesting.",
                answer="Thirds",
                explanation="The Rule of Thirds is one of the most important composition techniques! By placing your subject off-center (at the grid intersections), photos become more balanced and dynamic. Full-centered subjects can look stiff and boring by comparison.",
                xp=15,
                hints=["It involves dividing the frame into 3 sections each way", "A number between 2 and 4"],
            ),
        ],
    ),
    "dance_and_theater": Zone(
        id="dance_and_theater",
        title="Dance and Theater",
        description="Explore the performing arts — dance, drama, and storytelling on stage.",
        challenges=[
            Challenge(
                id="art_ballet",
                type="quiz",
                prompt="Ballet is a type of dance that began in the royal courts of which country about 500 years ago?",
                options=["France and Italy", "Russia and England", "Spain and Greece", "China and Japan"],
                answer="a",
                explanation="Ballet began in the Italian Renaissance courts around the 1400s and was developed further in France. The French influence is so strong that ballet terms (like 'plié', 'arabesque', 'grand jeté') are still in French today! Russia later became famous for amazing ballet companies like the Bolshoi.",
                xp=10,
                hints=["Think about the Italian Renaissance and French royal courts", "Ballet terms are still in French today"],
            ),
            Challenge(
                id="art_theater_masks",
                type="quiz",
                prompt="In ancient Greek theater, actors wore large masks. Two famous types represented comedy and tragedy. The comedy mask showed what expression?",
                options=["A big smile / turned-up mouth", "A frown / turned-down mouth", "A surprised open mouth", "Closed eyes"],
                answer="a",
                explanation="The two Greek theater masks — comedy (smiling face) and tragedy (frowning face) — are still used as the symbol for theater today! Greek plays were performed outdoors in huge amphitheaters where masks helped the audience see emotions from far away. The Greek word for 'actor' gave us the word 'hypocrite' (one who plays a role).",
                xp=10,
                hints=["Comedy = funny and happy", "One mask smiles, one frowns"],
            ),
            Challenge(
                id="art_musical_theater",
                type="quiz",
                prompt="A 'musical' is a type of theater show where the story is told using singing, dancing, AND acting together. Which famous musical is based on the story of a young lion who becomes king?",
                options=["Hamilton", "The Lion King", "Cats", "Wicked"],
                answer="b",
                explanation="The Lion King began as a Disney animated film (1994) and became one of the most successful Broadway musicals ever! It uses incredible costumes, puppetry, and African music. Hamilton uses hip-hop to tell the story of American founding father Alexander Hamilton. Wicked tells the untold story of the witches from The Wizard of Oz.",
                xp=10,
                hints=["Think about a Disney film with lions and the savanna", "The circle of life..."],
            ),
            Challenge(
                id="art_types_of_dance",
                type="fill_blank",
                prompt="A dance style born in New York City in the 1970s, danced to hip-hop music, often including breakdancing and popping, is called _____ dance.",
                answer="hip-hop",
                explanation="Hip-hop dance grew alongside hip-hop music in New York's South Bronx in the 1970s. It includes breakdancing (b-boy/b-girl), popping, locking, and freestyle. Street dance styles eventually made their way to TV shows and world competitions. Today hip-hop is one of the most popular dance styles globally!",
                xp=10,
                hints=["It shares its name with a music genre", "Think breakdancing and freestyles"],
            ),
            Challenge(
                id="art_storytelling_dance",
                type="quiz",
                prompt="In India, classical dance forms like Bharatanatyam use hand gestures called 'mudras' to tell stories. This makes Indian classical dance also a type of:",
                options=[
                    "Acrobatics — it requires extreme flexibility",
                    "Storytelling — the gestures and expressions act out characters and events",
                    "Meditation — it calms the mind",
                    "Exercise — it focuses on fitness",
                ],
                answer="b",
                explanation="Bharatanatyam and other Indian classical dances are complete storytelling systems! Each of the 64 basic hand gestures (mudras) represents a specific meaning — a flower, a bird, a character, an emotion. Performers can 'speak' entire stories through movement without words. It's over 2,000 years old!",
                xp=15,
                hints=["The hand gestures carry meaning — what are they communicating?", "Stories told through movement"],
            ),
            Challenge(
                id="art_theater_boss",
                type="quiz",
                prompt="You're directing a school play. The story, acting, costumes, set design, lighting, and music are all part of creating the experience. The performing art that combines ALL of these elements together is called:",
                options=["A concert", "A recital", "A theatrical production", "A gallery show"],
                answer="c",
                explanation="A theatrical production is the grand collaboration of art forms — writing (script), acting (performance), visual art (set, costumes, lighting), and music all working together. Theater is sometimes called the 'total art form' because it uses almost every other type of art. Shakespeare's plays have been performed for 400+ years!",
                xp=15,
                hints=["When all performing arts come together on one stage", "This is what makes theater unique — it combines everything"],
            ),
        ],
    ),
    "architecture_and_design": Zone(
        id="architecture_and_design",
        title="Architecture and Design",
        description="Discover how buildings, bridges, and spaces are designed and built.",
        challenges=[
            Challenge(
                id="art_architecture_def",
                type="quiz",
                prompt="Architecture is the art and science of designing buildings. The person who designs a building — creating the plans that builders follow — is called an:",
                options=["Engineer", "Contractor", "Architect", "Interior designer"],
                answer="c",
                explanation="An architect designs buildings — deciding how they look, how spaces connect, and how structures stay safe and standing. Engineers then calculate the math and physics to make the architect's vision work. Contractors build it. Interior designers choose the furniture and finishes inside. Architecture is one of the oldest art forms — buildings from 5,000 years ago still stand!",
                xp=10,
                hints=["The word comes from Greek — 'archi' means chief, 'tekton' means builder", "They draw the plans"],
            ),
            Challenge(
                id="art_eiffel_tower",
                type="fill_blank",
                prompt="The Eiffel Tower in Paris, France, was built in 1889 using _____ — a strong, flexible building material that was new and exciting at the time.",
                answer="iron",
                explanation="The Eiffel Tower was built from wrought iron — 18,038 pieces held together by 2.5 million rivets! At 330 meters tall, it was the world's tallest structure for 41 years. When it was built, many Parisians hated it and called it 'the iron lady' or 'an eyesore.' Today it's one of the most visited monuments in the world, with 7 million visitors per year!",
                xp=10,
                hints=["A metal used in construction", "Not steel — it was made before steel was widely used"],
            ),
            Challenge(
                id="art_pyramid_design",
                type="quiz",
                prompt="The ancient Egyptians designed the pyramids as triangular shapes (rather than rectangular buildings). This shape gave them special structural strength. Why are triangles stronger than rectangles in construction?",
                options=[
                    "Triangles are heavier, so they press down more firmly",
                    "Triangles distribute force evenly to all corners and resist changing shape without breaking",
                    "Triangles look more impressive, which is why architects prefer them",
                    "Triangles are easier to carve from stone than right angles",
                ],
                answer="b",
                explanation="A triangle is the strongest shape! When force is applied, a triangle distributes the pressure to its corners, and the sides resist bending. A rectangle, by contrast, can become a parallelogram (lean sideways) without breaking. This is why bridges use triangular trusses, and the pyramid shape has kept those structures standing for 4,500 years!",
                xp=15,
                hints=["Think about what shape doesn't deform — can you push a triangle sideways?", "It has to do with how force moves through the shape"],
            ),
            Challenge(
                id="art_sagrada_familia",
                type="quiz",
                prompt="The Sagrada Família in Barcelona, Spain, is a famous church designed by architect Antoni Gaudí. It's been under construction since 1882. What makes Gaudí's style especially unusual?",
                options=[
                    "He used only straight lines and flat surfaces — no curves at all",
                    "He took inspiration from nature — using curved shapes like bones, plants, and shells",
                    "He designed only using computers — the first architect to do so",
                    "He built entirely underground — all his buildings are below street level",
                ],
                answer="b",
                explanation="Antoni Gaudí was inspired by the natural world. His buildings look like they grew organically — curved surfaces, columns shaped like tree trunks, details inspired by honeycombs, seashells, and bones. He said 'there are no straight lines in nature.' The Sagrada Família is still being completed over 140 years later, projected to finish around 2026!",
                xp=10,
                hints=["Look at his buildings — do they have sharp corners or flowing curves?", "Think of trees, bones, and shells"],
            ),
            Challenge(
                id="art_bridge_types",
                type="quiz",
                prompt="The Golden Gate Bridge in San Francisco uses strong cables suspended from tall towers to hold up the road. This type of bridge is called a:",
                options=["Arch bridge", "Beam bridge", "Suspension bridge", "Truss bridge"],
                answer="c",
                explanation="A suspension bridge hangs the roadway from massive cables attached to tall towers. The cables transfer the weight to the towers, which carry it to the ground. Suspension bridges can span huge distances — the Golden Gate's main span is 1,280 meters! Arch bridges use curved arches to transfer weight. Beam bridges are the simplest: a flat beam across supports.",
                xp=10,
                hints=["The road is 'suspended' — held up from above by cables", "Think of how the road is attached to the towers"],
            ),
            Challenge(
                id="art_design_function",
                type="quiz",
                prompt="Great design balances beauty with usefulness. The idea that 'a building (or object) should look the way it works — its appearance should follow its function' is captured in the famous design principle:",
                options=[
                    "'Beauty first, function second'",
                    "'Form follows function'",
                    "'More is more'",
                    "'If it looks good, it works good'",
                ],
                answer="b",
                explanation="'Form follows function' is one of the most famous principles in architecture and design, coined by architect Louis Sullivan in 1896. It means: the shape of something should come from what it needs to do. A chair that looks beautiful but hurts to sit in has failed as design. This principle influenced the Bauhaus school, Apple's product design, and modern architecture worldwide.",
                xp=15,
                hints=["It says that looks should come from purpose", "Form = appearance, Function = purpose"],
            ),
        ],
    ),
}
